### ISSUE TITLE
ISIS2 - isis2pds corrupting label

### ISSUE THREAD

**Issue by EllaMaeLee** [DOI-USGS/ISIS3#1364]
The PRODUCT_CREATION_TIME is getting corrupted when the PDS image/label file are created.  Current work around is setting the time in the PDS template, but it is annoying to create a new template every time the date/time changes for a file.

**Comment by jlaura** [comment]
Is this an issue with ISIS2?

**Comment by EllaMaeLee** [comment]
yes, it is an ISIS2 issue

**Comment by jlaura** [comment]
@EllaMaeLee Currently, we do not support ISIS2. Apologies.
