### ISSUE TITLE
phocube uses many global variables in its cpp file

### ISSUE THREAD

**Issue by kaitlyndlee** [DOI-USGS/ISIS3#2466]
While working on a ticket for phocube, I noticed that it uses global variables to keep track of which bands to export. I needed to add a variable storing which band RA will be exported as and added this variable as a global variable to follow the previous work. Should phocube be refactored to not contain these global variables?

**Comment by jessemapel** [comment]
As we push to make applications callable programmatically, we need to do this. Even moving to just gtest may need this work to happen.
