### ISSUE TITLE
Add tracking to tgocassismos if it is currently set to off

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#2636]
(1) Check to see if tracking is on in tgocassismos
(2) If not, turn tracking on.

**Comment by krlberry** [comment]
Tracking is currently off. Should we turn it on?

**Comment by jlaura** [comment]
This change will create a tracking cube every time that `tgocassismos` is run. We need get make sure this change is in release notes.

**Comment by jlaura** [comment]
The change is in the `tgocassismos.cpp` line 212ish.
