### ISSUE TITLE
Prog27 has an Anaconda issue

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#2850]
When trying to build a release on Prog27, it complains that the most recent cspice build is corrupted. I completely cleared all the caches and downloaded a specific zip file off Anaconda that I knew was not corrupted and it still complained.

The current work around is to just build the mac release on a laptop.

**Comment by jlaura** [comment]
@scsides @SgStapleton Can you weigh in here? What happens if we reimage this machine?

**Comment by SgStapleton** [comment]
I have run into the same issue many times. I was able to temporarily fix this before by pinning particular builds of cspice from conda-forge, but this is clearly not an actual solution and we are in the process of working away from pins anyway.

**Comment by jlaura** [comment]
@SgStapleton :+1: Are you aware of any processes that we need to backup or maintain if this machine is wiped and re-imaged to start over? @scsides Same question?

**Comment by SgStapleton** [comment]
I hope you weren't waiting on me. I am not aware of any myself if the machine's name does not change ("prog27"). I certainly don't feel qualified to give that answer officially, though.

**Comment by jlaura** [comment]
:+1: I'll ask IT to reimage

**Comment by scsides** [comment]
For the sake of completeness: I can not think of any reason this can't be re-installed.

**Comment by SgStapleton** [comment]
Is there a rough estimate of when this may happen?

**Comment by jessemapel** [comment]
This looks like a problem with the anaconda installation

If I install using `/usgs/cpkgs/anaconda3_macOS` this is what the package looks like

```
(isis3) isis3mgr@igswzawgws-osxv # ls -al /usgs/cpkgs/anaconda3_macOS/pkgs/cspice-66-h1de35cc_1004/bin/
total 41384
drwxr-sr-x  2 isis3mgr  softlib     4096 Mar 28 15:41 .
drwxr-sr-x  6 isis3mgr  softlib     4096 Mar 28 15:41 ..
-rwxrwxr-x  1 isis3mgr  softlib   982704 Sep 20  2018 brief
-rwxrwxr-x  1 isis3mgr  softlib  1431676 Sep 20  2018 chronos
-rwxrwxr-x  1 isis3mgr  softlib   998456 Sep 20  2018 ckbrief
-rwxrwxr-x  1 isis3mgr  softlib   385528 Sep 20  2018 commnt
-rwxrwxr-x  1 isis3mgr  softlib   938000 Sep 20  2018 dskbrief
-rwxrwxr-x  1 isis3mgr  softlib   286552 Sep 20  2018 dskexp
-rwxrwxr-x  1 isis3mgr  softlib  1486280 Sep 20  2018 frmdiff
-rwxrwxr-x  1 isis3mgr  softlib  1503772 Sep 20  2018 inspekt
-rwxrwxr-x  1 isis3mgr  softlib  1203096 Sep 20  2018 mkdsk
-rwxrwxr-x  1 isis3mgr  softlib  1488880 Sep 20  2018 mkspk
-rwxrwxr-x  1 isis3mgr  softlib  1073264 Sep 20  2018 msopck
-rwxrwxr-x  1 isis3mgr  softlib  1323700 Sep 20  2018 simple
-rwxrwxr-x  1 isis3mgr  softlib  1084576 Sep 20  2018 spacit
-rwxrwxr-x  1 isis3mgr  softlib  1426280 Sep 20  2018 spkdiff
-rwxrwxr-x  1 isis3mgr  softlib  1037048 Sep 20  2018 spkmerge
-rwxrwxr-x  1 isis3mgr  softlib  1323436 Sep 20  2018 states
-rwxrwxr-x  1 isis3mgr  softlib  1485700 Sep 20  2018 subpt
-rwxrwxr-x  1 isis3mgr  softlib   862220 Sep 20  2018 tictoc
-rwxrwxr-x  1 isis3mgr  softlib   395320 Sep 20  2018 tobin
-rwxrwxr-x  1 isis3mgr  softlib   352632 Sep 20  2018 toxfr
-rwxrwxr-x  1 isis3mgr  softlib   105768 Sep 20  2018 version
```

If I install on my macbook this is what the package looks like

```
igswzawglt1183:TSC jmapel$ ls ~/miniconda3/pkgs/cspice-66-h1de35cc_1004/bin/ -la 
total 20808
drwxr-xr-x 44 jmapel domainusers    1408 Feb 11 09:05 .
drwxr-xr-x  6 jmapel domainusers     192 Feb 11 09:05 ..
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._brief
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._chronos
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._ckbrief
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._commnt
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._dskbrief
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._dskexp
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._frmdiff
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._inspekt
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._mkdsk
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._mkspk
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._msopck
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._simple
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._spacit
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._spkdiff
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._spkmerge
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._states
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._subpt
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._tictoc
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._tobin
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._toxfr
-rwxrwxr-x  4 jmapel domainusers     280 Sep 20  2018 ._version
-rwxrwxr-x  4 jmapel domainusers  982704 Sep 20  2018 brief
-rwxrwxr-x  4 jmapel domainusers 1431676 Sep 20  2018 chronos
-rwxrwxr-x  4 jmapel domainusers  998456 Sep 20  2018 ckbrief
-rwxrwxr-x  4 jmapel domainusers  385528 Sep 20  2018 commnt
-rwxrwxr-x  4 jmapel domainusers  938000 Sep 20  2018 dskbrief
-rwxrwxr-x  4 jmapel domainusers  286552 Sep 20  2018 dskexp
-rwxrwxr-x  4 jmapel domainusers 1486280 Sep 20  2018 frmdiff
-rwxrwxr-x  4 jmapel domainusers 1503772 Sep 20  2018 inspekt
-rwxrwxr-x  4 jmapel domainusers 1203096 Sep 20  2018 mkdsk
-rwxrwxr-x  4 jmapel domainusers 1488880 Sep 20  2018 mkspk
-rwxrwxr-x  4 jmapel domainusers 1073264 Sep 20  2018 msopck
-rwxrwxr-x  4 jmapel domainusers 1323700 Sep 20  2018 simple
-rwxrwxr-x  4 jmapel domainusers 1084576 Sep 20  2018 spacit
-rwxrwxr-x  4 jmapel domainusers 1426280 Sep 20  2018 spkdiff
-rwxrwxr-x  4 jmapel domainusers 1037048 Sep 20  2018 spkmerge
-rwxrwxr-x  4 jmapel domainusers 1323436 Sep 20  2018 states
-rwxrwxr-x  4 jmapel domainusers 1485700 Sep 20  2018 subpt
-rwxrwxr-x  4 jmapel domainusers  862220 Sep 20  2018 tictoc
-rwxrwxr-x  4 jmapel domainusers  395320 Sep 20  2018 tobin
-rwxrwxr-x  4 jmapel domainusers  352632 Sep 20  2018 toxfr
-rwxrwxr-x  4 jmapel domainusers  105768 Sep 20  2018 version
```

Maybe the NFS is deleting the `._*` files.

**Comment by jessemapel** [comment]
copying the `._*` files over seems to have allowed me to install cspice. I am not sure if I will be able to get the whole environment.

**Comment by jessemapel** [comment]
so copying them over fixed this... I'm going to test out an anaconda installation on a local disk for prog26 and see if it works there.

**Comment by jessemapel** [comment]
So an anaconda installation on the local disc fixed this. I'm going to put a ticket into IT to see what the NFS is doing.

For right now, I've modified isis3mgr's bashrc and bash_profile to use the anaconda install at `/jessetest/miniconda3` and have created an isis3 environment with the isis3 development environment.

**Comment by jlaura** [comment]
I would be willing to bet that this issue and the malloc issue are related. Conda on NFS is great - if the OSes are absolutely identical and the hardware is basically identical. When that is the case, the low level system libs that get linked in are all the same. We need to use anaconda installations that are local to the hardware they are running on for testing I suspect. (or in containers that are 'local').

**Comment by jessemapel** [comment]
@jlaura I'm going to be running the malloc issue with a build from the local anaconda today on prog26. I would like to touch base with @SgStapleton about nightly builds on prog26 first. The nightly build script should automatically use the local anaconda install.
