### ISSUE TITLE
ISIS support website still points to redmine and it is still accepting new tickets

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3147]
**ISIS version(s) affected**: All/current

**Description**  
ISIS support website still points to redmine and is still accepting new tickets

**How to reproduce**  
Go to https://isis.astrogeology.usgs.gov/index.html
click on support
log in
report a new issue
ticket goes into a black hole with no indication of any problem.  

**Possible Solution**  
Point to the git issues site

**Additional context**  
I was trying to report a different serious issue with our website and realized that my ticket was going into redmine instead of the correct place.

**Comment by lavalaz** [comment]
I am under the impression that my new redmine ticket has just gone into a black hole.  Is this correct?

**Comment by lwellerastro** [comment]
It looks like some of the Projects will still take new issues.  ISIS definitely will not and when you go to that projects specific Home page it points users to GitHub and there is no new issue button on the issues page. But if I felt like it, I can add a new issue to any of the other projects listed (after I log on).

**Comment by krlberry** [comment]
@lavalaz I did find your bug on Redmine: https://isis.astrogeology.usgs.gov/fixit/issues/5561, but I don't think that the "all issues" area on Redmine (https://isis.astrogeology.usgs.gov/fixit/issues) is being very actively watched right now. (I agree that this needs to be updated somehow so that this doesn't happen again.)

**Comment by lavalaz** [comment]
Thank you!  I re-did the redmine issue in git, so the redmine version can be closed, if anyone is monitoring that.  The real issue is that the link on our isis support website should be changed because I see no link to git issues from there.  And maybe shut redmine off totally?  I know, there are a lot of loose ends to chase down every time we make a change - even a change for the better!

**Comment by jlaura** [comment]
@scsides @kdl222 Is this good to close now?

**Comment by scsides** [comment]
The "Support" link in the upper left corner, from how to reproduce, still points to http://isis.astrogeology.usgs.gov/fixit

**Comment by jessemapel** [comment]
@scsides @jlaura Can we have students get that link fixed this week?
