### ISSUE TITLE
Installation instructions for the /base data is incorrect

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3148]
**ISIS version(s) affected**: All

**Description**  
If you follow the instructions on our installation page you make a royal mess on your computer and ISIS does not run.  

**How to reproduce**  
Go to https://isis.astrogeology.usgs.gov/documents/InstallGuide/index.html
Follow the instructions methodically and exactly
You will get /data folders being installed in random locations on your computer.  

**Possible Solution**  
Simplest solution takes two steps
(1) make where you cd to explicitly clear.  Right now it seems to suggest that you should 
cd $ISIS3DATA
but it is ambiguous if you need to do this if all you want to download is the /base or mission specific data.  I suggest you make it clear that step one is to cd $ISIS3DATA.
(2) correct the rsync commands so they work if you are in $ISIS3DATA.  Specifically, get rid of the /data at the end of every command.  You just need a .

**Additional context**  
This mistake has cost my student and I literally all of November, December, January, and February.  I could not figure out why ISIS would not run on his machine.  He would bring it in and there would be data folders scattered all over the place because he ran the rsync from wherever he happened to be. I know, we no longer support users who are not technically savvy so the real problem is that I am too stupid to use ISIS.

**Comment by jlaura** [comment]
@USGSsakins We should get this pushed onto the support stack ASAP.

**Comment by jessemapel** [comment]
@lavalaz Was your student following the instructions top to bottom or did they do an installation and then later do the data download? It sounds like they only did the partial data download.

**Comment by lavalaz** [comment]
They were following top to bottom but skipped the download everything.  Wanted to just get /base and /tgo.

**Comment by jessemapel** [comment]
> I know, we no longer support users who are not technically savvy so the real problem is that I am too stupid to use ISIS.

If we're providing command lines that can be copied and pasted, I think we are supporting users who are not fully aware of what the commands do.

A big problem with that page is it doesn't explain what the data area is and how it is used before providing commands to download data into it.

In the main installation instructions, it mentions setting custom data and test data areas but doesn't explain what they are

> Executing this script with no arguments will result in $ISIS3DATA=$CONDA_PREFIX/data, and $ISIS3TESTDATA=$CONDA_PREFIX/testdata.  The user can specify different directories for both of these optional values:

At the start of the data download all it says is this:

> ISIS3 supports many planetary missions; in fact, over 40 different instruments including some flown as early as the 1960s. Ancillary data are required to process images from these instruments.

**Comment by jessemapel** [comment]
This can be closed as soon as the updated install guide is pushed to the website. We'll probably get to that next week.

**Comment by jessemapel** [comment]
I'm going to close this as we'll be pushing up new docs with the 3.7.0 release
