### ISSUE TITLE
findrx does not get stored in history object

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#3150]
**ISIS version(s) affected**: 3.6.0

**Description**  
There is no history of running findrx on an image when cathist is run afterwards.

**How to reproduce**  
Run findrx on an image which has reseau points, then run cathist - findrx does not appear in the history.

**Possible Solution**  
Add a history object (or whatever it is) to findrx

**Additional context**  
Data: /work/users/lweller/Findrx/c1631247.lev0.cub
There is a file named norx_c1631247.lev0.cub where findrx hasn't been run if you need it.

Processing steps as follows: 
voy2isis from=/pds_san/PDS_Archive/Voyager/vg_0017/europa/c1631xxx/c1631247.imq to=c1631247.lev0.cub
spiceinit from=c1631247.lev0.cub attach=true extra=/usgs/cpkgs/isis3/data/base/kernels/pck/pck00010_msgr_v23.tpc
findrx from=c1631247.lev0.cub

Cathist run:
cathist from=c1631247.lev0.cub mode=brief

voy2isis from=/pds_san/PDS_Archive/Voyager/vg_0017/europa/c1631xxx/c1631247.imq to=c1631247.lev0.cub 
spiceinit from=c1631247.lev0.cub web=false attach=true cksmithed=FALSE ckrecon=TRUE ckpredicted=FALSE cknadir=FALSE spksmithed=FALSE spkrecon=TRUE spkpredicted=FALSE extra=/usgs/cpkgs/isis3/data/base/kernels/pck/pck00010_msgr_v23.tpc shape=SYSTEM startpad=0.0 endpad=0.0 url=https://services.isis.astrogeology.usgs.gov/cgi-bin/spiceinit.cgi port=443

**Comment by jessemapel** [comment]
This should be a very easy fix and may be good for new developers.

**Comment by jlaura** [comment]
tagging 3.7.0 so that it is on the radar when we schedule that we should have a support sprint scheduled before 3.7.0 is RCed. @USGSsakins

**Comment by lwellerastro** [comment]
This is super low priority.  I just discovered it while looking at the processing history of one of my Voyager images and realized findrx didn't make it.  It doesn't affect the work in the least bit.  There are likely more important issues to address than this.  I was just reporting a bug.

**Comment by jessemapel** [comment]
@lwellerastro This may be a good opportunity for our new developers to make a small change and interact with the support process.

**Comment by kaitlyndlee** [comment]
I did something similar with sumspice. Might be helpful to check out: https://github.com/USGS-Astrogeology/ISIS3/issues/2476

**Comment by kaitlyndlee** [comment]
@lwellerastro Testing build at /work/projects/isis/latest/m03150/ using the shared conda env isis3CentOS7.

**Comment by jlaura** [comment]
@kdl222 Instead of a testing build, can you reproduce without failure the process above? If so, we should get a code review, merge into dev and close. That way we are not bottlenecking on someone to test or asking someone who is working on another project to test.  Thanks!

**Comment by jlaura** [comment]
@kdl222 We should also do a 3.6.3 release on this. We can talk tomorrow at the standup and have a plan on this. @jessemapel can you also think about how we want to get these bug fix builds merged and pushed when doing a support sprint like we are now?

**Comment by jessemapel** [comment]
@jlaura We can do one bug fix release at the end of the sprint. Then, pull off the release candidate fro 3.7.0

**Comment by jlaura** [comment]
:+1: See https://astrodiscuss.usgs.gov/t/support-sprints-and-bug-releases/133 for a better place to discuss this (I think?).

**Comment by kaitlyndlee** [comment]
@jlaura I can reproduce the process without failure. I opened a PR for the changes.
