### ISSUE TITLE
The anaconda upload command is not being recognized

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#3151]
The anaconda upload command is not being recognized (sometimes) when conda set to /usgs/cpkgs/anaconda_linux. When attempting to run the command ```anaconda upload -u usgs-astrogeology -l hayabusa2_fy19 /usgs/cpkgs/anaconda3_linux/conda-bld/linux-64/isis3-3.6.1_hayabusa2-py36_0.tar.bz2``` output is :

```
Starting installer, one moment...
usage: anaconda [-h] [--version] [-G] [-T] [-C] [--noninteractive] [--proxy PROXY_URL] [--waitfornet TIMEOUT_IN_SECONDS] [-d] [--ks] [--kickstart KICKSTART_PATH] [--ksstrict] [--rescue]
                [--armplatform PLATFORM_ID] [--multilib] [-m METHOD] [--askmethod] [--repo REPO_URL] [--stage2 STAGE2_URL] [--noverifyssl] [--liveinst] [--resolution WIDTHxHEIGHT]
                [--usefbx] [--vnc] [--vncconnect HOST:PORT] [--vncpassword PASSWORD] [--xdriver DRIVER] [--xtimeout TIMEOUT_IN_SECONDS] [--decorated] [--keymap KEYMAP] [--lang LANG]
                [--singlelang] [--loglevel LEVEL] [--syslog HOST[:PORT]] [--remotelog HOST:PORT] [--noselinux] [--selinux [SELINUX]] [--nompath] [--mpath] [--nodmraid] [--dmraid]
                [--noibft] [--ibft] [--geoloc PROVIDER_ID] [--geoloc-use-with-ks] [--legacygrub] [--nosave [NOSAVE]] [--nomount] [--updates UPDATES_URL] [--image IMAGE_SPEC]
                [--dirinstall [DIRINSTALL]] [--memcheck] [--nomemcheck] [--leavebootorder] [--noeject] [--extlinux] [--nombr] [--mpathfriendlynames] [--kexec]
anaconda: error: unrecognized arguments: upload -u usgs-astrogeology -l hayabusa2_fy19 /usgs/cpkgs/anaconda3_linux/conda-bld/linux-64/isis3-3.6.1_hayabusa2-py36_0.tar.bz2
```

Entering ```anaconda upload --help```, the help text prints outs. Entering ```which anaconda```, however, outputs ```/usr/sbin/anaconda```.

This was attempted in both the base environment as well as the uploadTest environment.

I am wondering if this may have something to do with how the newer version of anaconda is making use of their etc/profile.d/conda.sh script. (Anaconda bin no longer being added to the $PATH variable - only individual environments are added once activated.)

**Comment by jlaura** [comment]
@SgStapleton With the 3.7.0 release are you still seeing this behavior?

**Comment by jessemapel** [comment]
This is no longer happening
