### ISSUE TITLE
Installation instructions in README do not have update instructions

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#3154]
**Description**
The 'Installation' instructions on your main README do not tell people how to 'update' a conda-installed version of ISIS, only how to install it for the first time.

Sure, it is as easy as saying `conda update isis3` but the README doesn't mention this.  It is probably also worth a short paragraph telling people how easy it is to have 'multiple' conda-installed versions of ISIS on their machine, by creating multiple environments.  Remember, this installation of ISIS is most likely the very first time a user will have used conda, and they cannot be expected to know anything about the subtleties of how conda works, best practices, or even really anything beyond what is in your README.

Thanks!

**Comment by jlaura** [comment]
@rbeyer Thanks for the report. Would you consider opening a PR?  Thanks!
