### ISSUE TITLE
Adding camera distortion model for Cassini ISS

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#3155]
**Description**  
Currently the ISIS camera model for the Cassini Imaging Science Subsystem (ISS) NAC and WAC cameras does not use a distortion model. The distortion is 0.45 pixels on the NAC and 3.6 pixels on the WAC (Thomas 2002, Owen 2003, Porco et al., 2004, attached). The distortion parameter for both the NAC and WAC are well-documented in the attached.
  
[casgeomcal_v2.docx](https://github.com/USGS-Astrogeology/ISIS3/files/2958435/casgeomcal_v2.docx)
[owen2003.pdf](https://github.com/USGS-Astrogeology/ISIS3/files/2958436/owen2003.pdf)
[PORCO_etal_2004ssr.pdf](https://github.com/USGS-Astrogeology/ISIS3/files/2958437/PORCO_etal_2004ssr.pdf)

**Example**
Although the distortion for the NAC is small, the WAC distortion is large and will affect the quality of control network bundle solutions, such as those being performed for Enceladus.

**Comment by jessemapel** [comment]
From Porco et al., 2004:

R_obs = R_id / (1 + k * R_id ^2)

for the NAC:
k=-8.26 x 10^-6 

for the WAC:
k = -6.27 x 10^-5

**Comment by jessemapel** [comment]
From Thomas, 2002:

R = sqrt(x_obs^2 + y_obs^2)
x_id = x_obs(1 + k * R^2)
y_id = y_obs(1 + k * R^2)

for the NAC:
k = -8 x 10^-6

for the WAC:
k = -6.2 x 10^-5

**Comment by jessemapel** [comment]
From Owen, 2003:

R^2 = x_obs^2 + y_obs^2
x_id = x_obs + (x_obs * R^2 * E_2) + (x_obs * y_obs * E_5) + (x_obs^2 * E_6)
y_id = y_obs + (y_obs * R^2 * E_2) + (y_obs^2 * E_5) + (x_obs * y_obs * E_6)

for the NAC:
E_2 = 8.26 x 10^-6
E_5 = 5.45 x 10^-6
E_6 = -19.67 x 10^-6

for the WAC:
E_2 = 60.89 x 10^-6
E_5 = 4.93 x 10^-6
E_6 = -72.28 x 10^-6

**Comment by jessemapel** [comment]
@blandoplanet Do you have any insight about which distortion model to use? I'm leaning towards Porco as it's more recent and agrees relatively well wtih the other two.

**Comment by blandoplanet** [comment]
I agree. The Porco 2004 reference is typically the standard reference when describing the camera, so I think it makes sense to you the correction from there.

**Comment by jessemapel** [comment]
Turns out this is already done!

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/cassini/objs/IssNACamera/IssNACamera.cpp#L113

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/cassini/objs/IssWACamera/IssWACamera.cpp#L89

**Comment by jessemapel** [comment]
From the IAK we have:

WAC:

```
INS-82361_K1=.000062
```

NAC:

```
INS-82360_K1=.000008
```

Which are the numbers from Thomas. We can easily change to Porco if we want to.

**Comment by blandoplanet** [comment]
Thanks, @jessemapel. The values from Thomas are great. I'm not quite sure where the confusion stemmed from. Sorry to be naive - this information was in the IAK rather than the IK? Is this always the case for ISIS cameras?

**Comment by jlaura** [comment]
@blandoplanet The NAIF kernels do not include the distortion model. Therefore, the ISIS application adds an IAK (addendum) kernel into the pool that includes, in this case, the distortion information. Other examples of this that spring to mind are the ITRANSS/L keys for Apollo metric where information for conversion from film millimeters to detector space were not in the NAIF kernels.

**Comment by jessemapel** [comment]
@blandoplanet There's often camera parameters that we add in the IAK, which is our own special thing. Usually, these get communicated back to the mission team and NAIF for integration into the IK. We should send an e-mail to NAIF about having them added to the IK.
