### ISSUE TITLE
setisis internal command malfunctioning

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#3158]
The setisis command appears to be working as far as recognizing where to find ISIS binaries (a ```which qview``` command shows the proper location of the binaries), but when you ```echo $PATH``` there appears to be garbage thrown into the path. I am not sure what is happening here or if this is even causing any issue.

**Comment by acpaquette** [comment]
Solved for the time being. Issue was an old snippet of code adding binary paths for qt3 and qtdir. Will reopen this if there are any problems with setisis for internal users who are still using a qt3 build.

**Comment by jlaura** [comment]
:+1: Does it make sense to put the code snippet into this issue incase someone else runs across this or is it well documented or my question is just completely ill-informed?

**Comment by acpaquette** [comment]
```shell
  #####################################################################
  # If we have Qt3 the QTDIR must be set.  Qt4 no longer requires     #
  #  QTDIR.  Also, we moved the 3rd party libraries and includes from #
  #  $ISISROOT/../3rdParty to /usgs/pkgs/local.  So, we Change the    #
  #  path to point at the third party executables allowing us to run  #
  #  moc, Xalan, doxygen, etc.                                        #
  #####################################################################
  ThirdPartySuffix=`/usgs/cpkgs/isis3/isis3mgr_scripts/utils/printIsisVersion -l`
  ThirdPartyPath=/usgs/pkgs/local/$ThirdPartySuffix
  dOxygen=/usr/local/bin
  for i in $ThirdPartyPath/bin $dOxygen; do
    builtin echo $PATH |grep $i -q
    if [ $? != 0 ]; then
      if [ "x$PATH" == "x" ]; then
        export PATH=$i
      else
        export PATH="$i:$PATH"
      fi
    fi
  done
  unset i
```

Old qt3 code snippet. This honestly seems more like when we were building and maintaining a bunch of 3rd party dependencies and is no longer needed with the cmake system.

**Comment by jessemapel** [comment]
I looked back at old versions of ISIS. On Atrovm3 I found 3.2 and it was using qt4. So, this looks like it's quite old.
