### ISSUE TITLE
Updates to tgocassisrdrgen exported PDS4 label are needed.

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3171]
**ISIS version(s) affected**: 3.6.2+

**Description**  
Problems:

* The PDS4 label exported by `tgocassisrdrgen` identifies the image as a ExoMars TGO FREND file, not an ExoMars TGO CaSSIS file in the `logical_identifier`
* `data_mosaic` is not a valid level of data processing.

From the label:

``` 
<logical_identifier>urn:esa:psa:em16_tgo_frd:data_mosaic:MY34_004224_188_1_PAN</logical_identifier>

```

This is an example of a correctly-formatted `logical_identifier`:

```
urn:esa:psa:em16_tgo_cas:data_raw:cas_raw_sc_20161124t160000-20161124t220000-8-1-1-20161124t185305854-blu-4-0
```
"frd" needs to be changed to "cas" and `data_mosaic` is not valid, so this needs to be changed to something that is valid.

**How to reproduce**  
Run `tgocassisrdrgen` on any CaSSIS cube and look at the exported label.

**Possible Solution**  
Update the appropriate translation file or code to change the output string.

**Additional context**  
This is further work on the result of the last CaSSIS sprint: #2635 

Tanya Lim from PSA pointed out this issue at LPSC.

I will add any additional needed changes that are identified to this ticket.

**Comment by jessemapel** [comment]
@kberryUSGS Is this fixed?

**Comment by krlberry** [comment]
Fixed.
