### ISSUE TITLE
Maintaining anaconda environments

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#3187]
Is it time to clean up the environments in the shared anaconda and standardize naming conventions for them? Right now we have an interesting hodge-podge happening. I believe that isis3.6.0 is the latest environment with the isis3 dependencies that is used for development, but then isis3.6.2 is the name of the environment with the actual isis3 binaries... This is naming convention is very confusing.

I think it may be time to address how to keep the development environment(s) up to date as well. Do we make it the responsibility of whoever modified the environment yamls to update the dev environments in the shared anaconda? Do we hold onto old versions of the dev environments for building older versions of ISIS? ***NOTE*** Our nightly scripts make use of the "isis3" environment currently.

Also, how many versions of isis do we want to maintain isis binary libraries for?

**Comment by SgStapleton** [comment]
I think I may go through and remove environments with "test" in the name. Unless anyone has any objections?

**Comment by jessemapel** [comment]
I agree it's a bit nonsensical. I don't think we should worry about maintaining old development environments because they should be available in the old environment.yml files. As far as builds keep, I've written some up on [astrodiscuss](https://astrodiscuss.usgs.gov/t/internal-rfc-distribution-of-isis3-at-asc/52/29?u=jessemapel).

**Comment by SgStapleton** [comment]
I think how you laid-out the release builds there makes a lot of sense. Do you really think we should not keep a few of the older version devs around for a little bit? We won't/shouldn't have near as many of them, and they take a long time to build and are easy to mess-up if someone is not as familiar with building them.

**Comment by jessemapel** [comment]
My opinion is that they are not particularly useful, but we should have others weigh in.

**Comment by jessemapel** [comment]
@all thoughts on naming conventions? I'd like to preserve `isis3`, `isis#.#.#`, and `isis#.#.#-rc#` for user installs. how do people feel about `isisdev#.#.#` for dev environments?

**Comment by jessemapel** [comment]
Discussion continued on [astrodiscuss](https://astrodiscuss.usgs.gov/t/shared-anaconda-environment-naming-conventions/143?u=jessemapel).
