### ISSUE TITLE
clemhirescal: Passing KVALUE unfairly forces user to also pass KFROM

### ISSUE THREAD

**Issue by dpmayerUSGS** [DOI-USGS/ISIS3#3189]
**ISIS version(s) affected**: 3.6.0 (actually all versions of ISIS3 since 2009)

**Description**  
By default, `clemhirescal` selects a calibration factor from a lookup table, but it can alternatively accept a value passed by the user using the `KVALUE` option. However, the program currently forces the user to also enter `KFROM=USER` in order to get it to run and use the user-supplied value

**How to reproduce**  

```
clemhirescal from=lhd3062h.088.cub to=lhd3062h.088.cal.cub kvalue= 0.00125 
**USER ERROR** Parameter [KVALUE] can not be entered if parameter [KFROM] is equal to [COMPUTED].

# The program wants the user to do this instead:
clemhirescal from=lhd3062h.088.cub to=lhd3062h.088.cal.cub kvalue= 0.00125 kfrom=USER
```
:-1:

**Possible Solution**  
If the user passes `KVALUE` on the commandline, it should imply `KFROM=USER`:
```
clemhirescal from=lhd3062h.088.cub to=lhd3062h.088.cal.cub kvalue= 0.00125 
```
 :+1:

**Comment by dpmayerUSGS** [comment]
@jessemapel Could you add the "Products" label to this issue?

I don't have permissions to add labels

**Comment by jlaura** [comment]
@dpmayerUSGS PR solicited.

**Comment by dpmayerUSGS** [comment]
@jlaura Might as well tag it wontfix then because I have no idea how to program anything in ISIS

**Comment by egaultUSGS** [comment]
A possible solution would be to set the default KFROM value to USER in the XML file, and conversely set the KFROM value to COMPUTED when the KVALUE isn't specified.

I do not know where to access a valid clementine .cub file to test this, however.

**Comment by dpmayerUSGS** [comment]
I've got a valid Clemintine HIRES cube handy. I'll send you the path on Gitter

**Comment by SgStapleton** [comment]
Possibly add deprecation warning.

**Comment by scsides** [comment]
This is working as expected. The XML controlling this is correct. To see what is going on, run clemhirescal in the gui mode and play with the radio buttons on kfrom. After getting user input regarding options like this it was determined that issuing an error when a parameter was entered (kvalue), but not being used, was preferable to running without warning the user a parameters they entered was being ignored, or automatically overriding another parameter (kfrom) without warning the user especially for novice users. Also, there is no concept of a "warning" within ISIS. If a program is working correctly, there will always be an error issued if the command line is not correct.

As mentioned, the other way to code this, but breaking the existing UI, is to remove kfrom, and have kvalue have an xml "internal default" of "computed". Then the app needs to check to see if kvalue was entered, and override the default value with the user entered number.

**Comment by dpmayerUSGS** [comment]
Closing this then because apparently it's not actually a bug. 
I'm not a huge fan of the current behavior, but I understand and accept the reasoning that @scsides outlined above. 

Thank you, Stuart for the explanation and thank you @egaultUSGS for having a go at it.
