### ISSUE TITLE
Changes for the tgo sprint broke a nightly test

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#3201]
**ISIS version(s) affected**: 3.7.0

**Description**  

Nightly tests for tgocassis2isis_app_test_exportedFile is failing since changes for tgo sprint.

**How to reproduce**  

Run tests

**Possible Solution**  

Fix changes to StartTime value in ProccessExportPds4

**Additional context**  

(None)

**Comment by krlberry** [comment]
Closed by #3202
