### ISSUE TITLE
Flytrap (ISIS data and test data backup) not getting updated

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3206]
**ISIS version(s) affected**: all

**Description**  
Flytrap, the place the internal ISIS test data and public data (kernels, translation files) is backed up to, is not getting updated. 
This has at least been happening since at least September 2018. 

**How to reproduce**  
Look in `/work/projects/flytrap` and see that there is no actual test data backup since last September. 

**Possible Solution**  

**Additional context**  
I believe this problem is "known" by others, but it hasn't been fixed yet and there's no ticket, so I made a ticket for it.

This is important to fix because the ISIS test data is usually changed whenever a change is made to an ISIS application, which occurs often. ISIS data is also updated frequently (when new kernels are available, when translation files need to be changed, etc.) Without this backup, it would be difficult to restore to a previous version of test data if necessary.

**Comment by SgStapleton** [comment]
I spoke with @scsides about what could have potentially gone wrong here and have updated a cronjob on flytrap to run tonight. This will hopefully "reset" things in a way to allow the rsync script to run successfully. I will update when this is tested.

**Comment by krlberry** [comment]
Looks like this is still failing.

**Comment by SgStapleton** [comment]
It is. I believe I know what needs to be done now, but need IT's help with this one as I do not have file permissions for the scripts. Just put in a ticket with IT and am getting ready to head on over.

**Comment by SgStapleton** [comment]
I believe this is finally now working. Had to work around some permissions and cronjobs, but I am saying that this is now solved. 

As an FYI: to access backups older than 20190422, you will need to look in /work/projects/flytrap/isis-oldsnaps/isis3/
