### ISSUE TITLE
gllssi2isis does not create/store OriginalLabel properly for summed images

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#3207]
**ISIS version(s) affected**: 3.6.2

**Description**  
The ingestion application gllssi2isis does not appear to be storing the original pds label information properly.  The program appears to run successfully and many other applications applied to the ingested data don't have problems (spiceinit, gllssical, footprintinint, etc.), however, caminfo (using originallabel=true) will fail on these images as does catoriglab with the messages saying the OriginalLabel could not be opened or found (see details below).

This affects 174 of my Galileo Europa images (25% of the data).

**How to reproduce**  
Data used below available here: /work/users/lweller/Isis3Tests/Gllssi2isis/
I thought it would be easier to have the pds data locally, but if you need original location information, let me know.

Ingest a summed image using gllssi2isis then run catoriglab or caminfo to get an error:

gllssi2isis from=9825r.lbl to=9825r.cub

catoriglab from=9825r.cub to=origlbl_9825r.pvl

    Program = catoriglab
    Class   = "USER ERROR"
    Code    = 2
    Message = "Could not find OriginalLabel or OriginalXmlLabel in input file
               [9825r.cub]"
    File    = catoriglab.cpp
    Line    = 81

Here is the error from caminfo since it might be slightly more helpful:

    Program = caminfo
    Class   = "I/O ERROR"
    Code    = 4
    Message = "Unable to open OriginalLabel [IsisCube] in file [9825r.cub]"
    File    = Blob.cpp
    Line    = 289

Image 7765r is provided as an example of a full frame (unsummed) image that appears to have its original label information stored properly (output from catoriglab is origlab_7765r.pvl).

I ran both images in the directory through ingestion, spiceinit and footprintinit.

I don't see anything about summing mode in the pds lbl files, but full frame images are 800x800 and summed images are 400x400 samples and lines.

**Possible Solution**  
Handle images having summing=2 properly.

**Additional context**  
I originally ran into this problem while running caminfo with the settings "isislabel=true geometry=true originallabel=true statistics=true camstats=true linc=10 sinc=10 uselabel=true".  I use all of this output to populate a database for image selection and overlap information.  Although there a few original label keywords I would like access to (we don't propagate them to the isis label upon ingestion), the polygon information is critical and it appears I can get that information for summing mode 2 images by setting originallabel=false.  So I have a work around for the most important information.

A side note - this ingestion bug and subsequent problems with caminfo may explain why there are so many "unmapped" Galileo SSI images on PILOT (FYI @USGSsakins).  I looked at some of the info files for the unmapped images that were also in my failure list and they say "Error running caminfo on file". 
 Anyway, fixing this bug would likely help PILOT serve more Galileo SSI images of Europa to the public (and possible some other bothers as well).

Please let me know if you have questions or if I left something critical out of my description.

**Comment by jlaura** [comment]
Target for the RC2 release.
