### ISSUE TITLE
tgocassis2isis output cubes missing SummingMode keyword

### ISSUE THREAD

**Issue by audiefen** [DOI-USGS/ISIS3#3208]
**ISIS version(s) affected**: 3.6.1 (CaSSIS beta)

**Description**  
Starting 4/2/19, running tgocassis2isis produces output cubes that are missing the SummingMode keyword in the Instrument group of the label. I noticed there is a new keyword, Expanded, in Instrument group.

**How to reproduce**  
tgocassis2isis FROM=MY34_005534_185_1_000_PAN00-C1.xml TO=MY34_005534_185_1_000_PAN00-C1.cub

**Possible Solution**  

**Additional context**  
I was able to successfully process products on 3/30/19. When I tried processing them on 4/2/19 the keyword was missing. I suspect that something changed in a translation file maybe? I believe we rsync over the ISIS data area nightly or weekly, but unfortunately the person who manages our ISIS installation is unavailable, so I can't confirm that. I can confirm that we did not make any updates to the ISIS programs themselves though. Did a new translation file get inadvertently released?

Also, spiceint fails on CaSSIS cubes that do not have SummingMode keyword.
Group = Kernels
  NaifFrameCode             = -143400
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = MY34_005534_185_custom.tpc
  TargetPosition            = ($tgo/kernels/tspk/de432s.bsp,
                               $tgo/kernels/tspk/mar097.bsp)
  InstrumentPointing        = (/CaSSIS/Data/SPICE/CK/em16_tgo_sc_fsp_066_01-
                               _20180222_20190413_s20190208_v01.bc,
                               /CaSSIS/Data/SPICE/CK/cassis_ck_p_160312_1912-
                               31_181215.bc, $tgo/kernels/fk/em16_tgo_v17.tf,
                               $tgo/kernels/fk/em16_tgo_ops_v02.tf,
                               $tgo/kernels/fk/rssd0002.tf)
  Instrument                = $tgo/kernels/ik/em16_tgo_cassis_v07.ti
  SpacecraftClock           = $tgo/kernels/sclk/em16_tgo_step_20190208.tsc
  InstrumentPosition        = /CaSSIS/Data/SPICE/SPK/em16_tgo_fsp_066_01_20-
                              181127_20190516_v01.bsp
  InstrumentAddendum        = $tgo/kernels/iak/tgoCassisAddendum007.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Predicted
  InstrumentPointingQuality = Predicted
  CameraVersion             = 1
  Error                     = "PVL Keyword [SummingMode] does not exist in
                               [Group = Instrument]"
End_Group

**Comment by jlaura** [comment]
@kberryUSGS @SgStapleton Can we confirm that this is occurring on 3.7.0-RC1? Also, any thoughts if a change occurred here as we got the 3.7.0-RC1 pushed?

**Comment by audiefen** [comment]
After more investigation I found we were rsyncing the ISIS3DATA area nightly. On April 2nd the following translation files were updated by the rsync:
tgoCassisExport.trn
tgoCassisExportedInstrument.trn
tgoCassisInstrument.trn

We replaced those with the older files from our systems snapshots and it fixed the problem.

We have turned off our rsync for the time being.

Thanks, 
Audrie

**Comment by jlaura** [comment]
@audiefen Thanks for the added information. This should make applying a fix very straightforward. @kberryUSGS @SgStapleton Can you all take a look at this and apply the fix so that the nightly rsync is working as expected? Alternatively, have we intentionally changed something?

**Comment by krlberry** [comment]
Only the kernels are being updated daily; the rest of the data area was only updated with the RC release. 

I haven't looked into this much yet, but...

We updated the listed .trn files on the rsync server associated with CaSSIS-related code changes present in the ISIS 3.7.0 release candidate on Monday when the release candidate went out.  It looks like the changes in the data area were not backwards compatible with ISIS 3.6.1-Cassis. We did not anticipate this.

**Comment by jlaura** [comment]
@kberryUSGS :+1: Sounds great. This is 100% something to address before 3.7.0 officially drops. We can collect this with the other issues we are seeing and then identify which / who.

**Comment by krlberry** [comment]
@audiefen The two potential paths forward I can see for this are: 

(1) You could upgrade to the ISIS 3.7.0 release candidate (see: https://astrodiscuss.usgs.gov/t/a-release-candidate-for-isis-3-7-0-is-now-available/147) This has the updates from the last work done on CaSSIS including the fix for the Summing mode bug and the changes to the exported label from tgocassisrdrgen. 

(2) We could create a new separate CaSSIS data area compatible with 3.6.1 (CaSSIS beta) for you to rsync from. 

Do either of these sound good to you?

**Comment by audiefen** [comment]
@kberryUSGS We've discussed it here and decided to update to ISIS 3.7.0. Probably won't happen until next week sometime. We're should be good until then with our rsync disabled. Thanks for your response!
