### ISSUE TITLE
Instructions to download data on README are wrong.

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3212]
**Description**

I followed the instructions on the github page (https://github.com/USGS-Astrogeology/ISIS3#full-isis3-data-download).  It dumped data into my home area.  I looked around and inferred that I should follow part of the instructions for downloading all the data and copy-pasted the command given in the instructions (_cd $ISIS3DATA_).  Then I tried to update the TGO data, and copy-pasted the command given in the instructions (_rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/tgo data/_).  Now I have new data in a new folder where ISIS3 won't find it.  No error messages or anything to tell the user there is a problem.  I only know there is a problem because I spent months debugging my student's ISIS3 installation and know what to look for.  

**Suggested Edit**

I already suggested a fix but that didn't seem to help.  At this point I am suggesting you write out the explicit single-line rsync command that will put the data in the right folder on the user's computer.  

Thanks!

**Comment by jessemapel** [comment]
This was updated in the document that is generated for our website in #3170, but not on our github README. It won't take much to copy those changes to our README.

**Comment by jessemapel** [comment]
@lavalaz If you find that a previous issue has not been resolved, you can re-open that issue as the reporter. I'm leaving this open because this is a separate issue. #3148 was for the website documentation, which we will no longer link to. This issue is for our github documentation which we will be directing people to as of 3.7.0

**Comment by lavalaz** [comment]
OK, your edit is correct.  I did not realize the webpage is deprecated...  Do I need to put in another ticket saying I still get bad instructions if I google for USGS ISIS3 installation help because the old web page is still up?  I don't mean to beat a dead horse, but I do want this problem really eliminated.  And sorry if I don't know how to help other than be a nag...

**Comment by jessemapel** [comment]
@lavalaz Don't feel like a nag, this is still a valid issue. The website install instruction page has been updated, but it won't be pushed publicly until the 3.7.0 release when we push all of the updated docs. We may also delete the contents of that page and have it point to out github readme.

**Comment by lavalaz** [comment]
OK, thanks!  And for what its worth, I totally support the idea of having only one place for install instructions (i.e., delete the contents of the current page and point people to github).

**Comment by jessemapel** [comment]
@lavalaz Agreed, we have already started working on this consolidation in #3178

**Comment by jessemapel** [comment]
@lavalaz Instructions should be fixed now. If you think there's still ambiguity in anything please re-open this issue.

**Comment by lavalaz** [comment]
I just copy-pasted and worked fine and the instructions should be clear to any prospective user.  Thank you!
