### ISSUE TITLE
rsync can't copy 5 of the files in the tgo data area

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3213]
**ISIS version(s) affected**: x.y.z
All

**Description**  

I get "Permission denied (13)" error.  Copy-pasted below
rsync: send_files failed to open "/data/tgo/kernels/ck/cassis_ck_p_160312_191231_190216.bc" (in isis3data): Permission denied (13)
rsync: send_files failed to open "/data/tgo/kernels/ck/cassis_ck_p_160312_191231_190223.bc" (in isis3data): Permission denied (13)
rsync: send_files failed to open "/data/tgo/kernels/ck/cassis_ck_p_160312_191231_190309.bc" (in isis3data): Permission denied (13)
rsync: send_files failed to open "/data/tgo/kernels/ck/cassis_ck_p_160312_191231_190316.bc" (in isis3data): Permission denied (13)
rsync: send_files failed to open "/data/tgo/kernels/ck/readme.txt" (in isis3data): Permission denied (13)

**How to reproduce**  

rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/tgo data/

**Possible Solution**  

change permissions of these 5 files to match the other files. 

**Additional context**  

Thanks!

**Comment by jessemapel** [comment]
@kberryUSGS

**Comment by krlberry** [comment]
@lavalaz This should now be fixed on the rsync server.

**Comment by krlberry** [comment]
To stop this problem from happening in the future, I added "fix the permissions" to #2638

**Comment by lavalaz** [comment]
Just ran it and went perfectly.

**Comment by krlberry** [comment]
@lavalaz :+1: Thanks!
