### ISSUE TITLE
Changes to be made to or things to investigate for Kaguya TC Sensor Model

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3217]
**ISIS version(s) affected**: 3.7.0+

**Description**  
The current draft version of the Kaguya TC Sensor Model does not produce good pointing. We need to investigate: 

- [x] Check how the size/position of the f.o.v for each swath mode: nominal, half, full should be used to determine the origin of the focal plane map. 
- [x] Why are images mirrored when projected, in comparison with the DEM.
- [x] Why is there only one record in each of the InstrumentPosition, Pointing, and BodyRotation tables? this is a linescanner!
- [x] Why are the projected images trapezoidal? Expected thin rectanges.
- [ ] Make sure exposure duration is changing for low vs. high altitude images
- [x] Switch from using `StartTime` for the time used in the detector map to using the S/C clock time. 
- [ ] Update IK in system with actual distortion eq used and ISIS code comments accordingly as in https://github.com/USGS-Astrogeology/usgscsm/pull/225/files#r275095482
- [x] Update this to dev so the merge is easier

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by krlberry** [comment]
@scsides I think I fixed "why is there only one record in the Position/Orientation tables" problem in PR #3218 !

**Comment by krlberry** [comment]
Images that were flipped upside down before the update are now successfully facing the correct up-down direction, but we're still seeing a mirrored image with the current sensor model, in comparison with the DEM it was projected to.

**Comment by jlaura** [comment]
@kberryUSGS @scsides Can we close this?

**Comment by scsides** [comment]
The main support link in the upper left corner of the main site still points to: http://isis.astrogeology.usgs.gov/fixit

**Comment by scsides** [comment]
The PR was waiting for 3.7.0 and now the PR is waiting reviews. Beyond that it is ready.

**Comment by scsides** [comment]
@jlaura  The PR was waiting for 3.7.0, and now is waiting for review. Beyond that it is ready.

**Comment by lwellerastro** [comment]
Is this for csm?  Seems like camera model is ok under isis, so above has little to no user impact?  Kaguya is currently being worked on so trying to understand if this should be a concern or not.  Thanks!

**Comment by jessemapel** [comment]
This change has been made in USGSCSM and we need to investigate if it should be made in ISIS. We're comparing sensor models between USGSCSM and ISIS at the moment and this came up as a reason why we're seeing differences for Kaguya TC.

For reference here's what's in the Kaguya TC IK about the distortion model:

```
Distortion information
---------------------------------------------------------------------------
  Line-of-sight vector of pixel no. n can be expressed as below.

   Distortion coefficients information:
     INS<INSTID>_DISTORTION_COEF_X  = ( a0, a1, a2, a3)
     INS<INSTID>_DISTORTION_COEF_Y  = ( b0, b1, b2, b3),

   Distance r from the center:
     r = - (n - INS<INSTID>_CENTER) * INS<INSTID>_PIXEL_SIZE.

   Line-of-sight vector v is calculated as
     v[X] = INS<INSTID>BORESIGHT[X]
            +a0 +a1*r +a2*r^2 +a3*r^3 ,
     v[Y] = INS<INSTID>BORESIGHT[Y]
            +r +a0 +a1*r +a2*r^2 +a3*r^3 ,
     v[Z] = INS<INSTID>BORESIGHT[Z] .
```

It looks like this has already been done in ISIS though https://github.com/USGS-Astrogeology/ISIS3/pull/3498

**Comment by lwellerastro** [comment]
Thanks @jessemapel.  Hopefully isis is all good to go then.  We'll keep an eye out for any changes though.

**Comment by acpaquette** [comment]
There are no issue with the ISIS distortion model relative to a round trip (setImage, setGround) in ISIS. There is still something going on between the USGSCSM and ISIS distortion models when going image-to-ground in ISIS and ground-to-image in USGSCSM. However this is something to be addressed in USGSCSM or ALE work and not during a product support sprint.
