### ISSUE TITLE
ISIS3.6 looking for deprecated libnsl.so.1 on Fedora 28

### ISSUE THREAD

**Issue by mlwalpert** [DOI-USGS/ISIS3#3219]
**ISIS version(s) affected**: 3.6

**Description**  

I'm new to ISIS and Linux both, so I apologize if my issue is best handled in another forum.

I'm trying to run ISIS 3.6 on Fedora 28 64bit. Everything about the installation appears to work fine, but when I try to run any function (ex: Qview) I get this error:

qview: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory

From what I've read on other forums, it appears that Fedora  28 no longer installs libnsl.so.1

How have other ISIS users on Fedora 28 dealt with this problem?

Thanks!

**How to reproduce**  

(isis3) [michael@localhost isis3]$ conda activate isis3
(isis3) [michael@localhost isis3]$ qview
qview: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory

**Comment by mlwalpert** [comment]
Update:

Turns out it was an easy fix. All I had to do was download and install a legacy version of libnsl.so.1 and Qview started working.

Sorry if I wasted anybody's time with this question.

**Comment by jlaura** [comment]
No waste at all and thank you for posting. We appreciate the information and your post of a solution for anyone else that might encounter this issue.
