### ISSUE TITLE
Nightly build emails not checking gtest output

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#3223]
The nightly testing emails are not checking the output of the run of gtest. The gtests are being run each night with logs output and even copied-over to the backup logs where the email script parses. We just need to add parsing for this log file.

*This could possibly be a great introduction to the internal scripting process

**Comment by SgStapleton** [comment]
There have already been a number of old tests that have been removed after they were rewritten in gtest, so this probably needs to be addressed soon.

**Comment by SgStapleton** [comment]
Confirmed gtest results are being included in the nightly build emails. We should be good to close this and remove old tests.

**Comment by jlaura** [comment]
:+1: Nice job @kdl222 @paarongiroux @SgStapleton
