### ISSUE TITLE
Automos unable to open THEMIS cubes

### ISSUE THREAD

**Issue by mlwalpert** [DOI-USGS/ISIS3#3225]
**ISIS version(s) affected**: 3.6.2

**Description**  
Automos is giving me a generic error whenever I try to run it on my list. It just says I/O ERROR unable to open. I've confirmed that the names in the list are correct and have the correct paths. The cubes are not open anywhere, so they're not locked. And the same list has been used for other operations, so I know the list is good.

 Anybody know how to fix this?

**How to reproduce**  
Automos version:
```
automos fromlist=/home/michael/data/THEMIS/norm/normalized.lis mosaic=/home/michael/data/THEMIS/Thermal_Mosaic priority=average
```

Noseam version: 
```
noseam fromlist=normalized.lis to=Thermal.cub samples=73 lines=73 matchbandbin=true removetemp=true
```

Both give the same error. ISIS says it's unable to open whichever cube happens to be first on the list
```
**ERROR** Running Isis program [automos] failed with return status [4].
**I/O ERROR** Unable to open [i01693007edr_projected_odd_normalized].
```

**Proposed Solution**
THEMIS documentation says something about resetting band number values during initial preprocessing. I didn't do this because I couldn't figure out how. 

Could that be causing my problem?

The exact quote is:
> the ISIS-3 keyword
> BandNumber, available after version 3.4.8 (2014), has the same value as the RDR keyword
BAND_BIN_BAND_NUMBER. The default value of the ISIS-3 keyword OriginalBand is a
confusing re-mapping of the THEMIS camera band designations, which does not correlate to any
RDR keyword value, and actually may cause problems during later processing steps. Therefore,
the THEMIS Team resets the ISIS-3 OriginalBand values to be equal to the RDR keyword
BAND_BIN_BAND_NUMBER values before continuing with additional processing

Reference:
THEMIS GEOMETRIC PROCESSING USER'S GUIDE. Murray, Kimberly et. al. 07/01/2017

Thanks!

**Comment by jessemapel** [comment]
@mlwalpert Can you post the contents of your list file? It looks like you may not have file extensions in your list.

**Comment by krlberry** [comment]
Hi @mlwalpert, To help us determine what is going on, could you post the contents of `normalized.lis`? (Or if this is long, could you post a few entries from the list?) It looks like the cubes in the list may lack file extensions.
Thanks!

**Comment by mlwalpert** [comment]
Sorry I should have updated this post.

Turns out the problem was that Automos requires the extension be expliciyly
part of the list, where the other scripts dont.

As soon as I included extensions it worked just fine.
