### ISSUE TITLE
The permissions for the builds on prog29 from 04/13-04/15 are only visible to isis3mgr

### ISSUE THREAD

**Issue by twilson271828** [DOI-USGS/ISIS3#3228]
**ISIS version(s) affected:  isis3nightly2019-04-03 - isis3nightly2019-04-15

**Description**  
The build directories in /usgs/pkgs are only accessible to isis3mgr from 04-03 to present.

**How to reproduce**  
ssh into prog29 and try to setisis to any of the nightly builds from 04-03 on.

**Possible Solution**

**Comment by SgStapleton** [comment]
This was related to the umask defaults in the /etc/login.defs file for isis3mgr on prog29. This has been fixed by Mike Klinke in our IT department.
