### ISSUE TITLE
Nightly cleanupBuilds cronjob on prog24 failing

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#3238]
This script has been failing with a "make: *** No rule to make target `cleansrc'.  Stop." error message. This script runs for each machine in the prog24 cron job. Not super high priority, but builds are starting to pile up in /usgs/pkgs/ dir on each system.

**Comment by jessemapel** [comment]
Things appear to be cleaning up on prog24 now
