### ISSUE TITLE
Documentation for Release Process

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#3258]
The full release process needs to be documented.

**Comment by SgStapleton** [comment]
The full process has been documented in the [internal wiki](https://github.com/USGS-Astrogeology/ISIS3/wiki/Public-Release-Process)

**Comment by jlaura** [comment]
Wiki navigation sidebar has been updated with the link. For the next 3.7.1 release at the end of the week we want to have someone other than Summer go through this process.
