### ISSUE TITLE
Pull rsync part out into function for Isis kernel scripts

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3279]
**Description**  
Pull repeated rsync command in all kernel scripts into function

**Comment by kaitlyndlee** [comment]
The rsync command is being executed in the distributeData script. In this script, an isis version needs to be passed and set. Only some download scripts are passing in an isis version (we are already setting an isis version in the download script, we shouldn't need to set it again in distributeData). We could remove setting isis in the distribute data script?

**Comment by krlberry** [comment]
Check to see if/where `distributeData` is being used.
