### ISSUE TITLE
Isis Kernel Scripts - write "purge" script 

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3280]
**Description**  
Write a utility function to purge (remove) all but the last n (default=10) kernel database files for a mission, and this to the kernel script.

**Comment by krlberry** [comment]
Update to be more generic (takes a regex) so that it could also be used to purge old kernels based on a pattern.

**Comment by krlberry** [comment]
For updating the scripts, only use this function to clean up all but the last last n. In the script, unless we know otherwise, use n=10.

**Comment by kaitlyndlee** [comment]
Just noticed that cassis has three different db files for ck kernels. Generalizing this function will be helpful in differentiating between these different db files. 

Before adding this method, check to see the name of db files.
