### ISSUE TITLE
Considerations for the new LFS set-up for ISIS data and testData

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#3282]
## Description
We will shortly be moving forward on an externally-facing data repository for ISIS using the LFS server. This issue will be to organize our thoughts/concerns on the infrastructure.

A few things to keep in mind:

- Binaries are stored differently than non-binary files.
  - We get to specify which files will be stored in the standard GitLab (git) manner and which files will be pointers to data stored in some other storage area (GitLFS). As we would like to have external users be able to access all of the ISIS data (including test data) we want to have all of the data externally accessible. We are working through getting an externally facing GitLab instances cleared through security. This will allow all of the 'small' stuff to be accessed by external users. Then we push the binary data to someplace else. In our case this will go to S3.

## Current Plan

- The idea will be to have a local repository (currently being set-up in /usgs/cpkgs/isis3/dataRepo) that will house both our data and testData dirs. 
- Eventually, data and testData will simply be symlinks that point to the dataRepo/(data and testData) directories.
  - Until we get kinks worked-out, keep two full copies of both dirs in both locations
    - (Currently working on this - but ran out of space in /usgs/cpkgs/isis3)
- Determine how large a local (development) copy of the test data without all of the LFS data downloaded would be. 
  - Thinking about this more as well - working with a large test area will cause some friction. I think that this is good friction that can help focus our efforts to move more testing to GTest.
- @jlaura needs to create an RFC and get it appropriately communicated.

## Concerns

- Scripts will need to be updated with git commands. This is especially true of any scripts involving copying or rsyncing files in data/ and testData/
- Does it make ore sense to have just the one local repository that everyone works from, or does it make more sense for developers to also each maintain their own local repos? (Keep in mind that binaries will actually be pointers to the files out on the LFS server, so only non-binaries will be kept locally for each developer)
  - When a dev needs a binary, though, like to modify testData directly, that file will then be downloaded and exist locally. Is there anyway to change this back to pointer once work has completed on the file? Would this be a worth-while consideration?

**Comment by SgStapleton** [comment]
Everyone, feel free to add to the comment above directly to keep ideas centrally located rather than having to read through comments to get the whole story.

@jlaura @scsides Please feel free to expand on what I have started - I feel horribly under qualified on the topics.

**Comment by jessemapel** [comment]
I'd imagine we will all need our own clones so that we can make changes to the data and test data areas. If we had a shared area then making changes would impact everyone else before the changes are finished and merged.

**Comment by jlaura** [comment]
> Scripts will need to be updated with git commands. This is especially true of any scripts involving copying or rsyncing files in data/ and testData/

Why? For now, we should have a single internal repository of record for all of our internal users (that work using a shared data area). Our current download scripts for things like kernels should continue to use the method that they are using. We then need to determine how to (a) validate the newly pulled changes (I believe @kberryUSGS talked about this today even) and (b) determine how frequently to push the newly downloaded data to the GitLab repo.

> Does it make ore sense to have just the one local repository that everyone works from, or does it make more sense for developers to also each maintain their own local repos? (Keep in mind that binaries will actually be pointers to the files out on the LFS server, so only non-binaries will be kept locally for each developer)

Individual for the test data. This will definitely cause friction in the short term. As I said in my edit to the original post, I think that the friction is a good thing. Look at the pain that has been endured by updating the .bsp. This is a product of using live kernels.

> When a dev needs a binary, though, like to modify testData directly, that file will then be downloaded and exist locally. Is there anyway to change this back to pointer once work has completed on the file? Would this be a worth-while consideration?

We are talking 60GB? I suspect it is less expensive to keep migrating tests and buy everyone a thumb drive.

**Comment by krlberry** [comment]
@jlaura In response to: 

> > Scripts will need to be updated with git commands. This is especially true of any scripts involving copying or rsyncing files in data/ and testData/

> 
> Why? For now, we should have a single internal repository of record for all of our internal users (that work using a shared data area). Our current download scripts for things like kernels should continue to use the method that they are using. We then need to determine how to (a) validate the newly pulled changes (I believe @kberryUSGS talked about this today even) and (b) determine how frequently to push the newly downloaded data to the GitLab repo.

As an example of something that may need to be changed, the commands `make checkout` to get a local copy of test truthdata and `make checkin` to "check in" a local copy of truthdata to the system `$ISIS3TESTDATA` do so by rsyncing back and forth. Presumably we want to change this behavior, as the system `$ISIS3TESTDATA` should no longer be modified directly? see: [isismake.tsts](https://github.com/USGS-Astrogeology/ISIS3/blob/1f35bec3c3b1fceb3cada6519dd53b8fc2bf97b0/isis/make/isismake.tsts)

For the Isis kernel download scripts, right now they are being directly downloaded to the system `$ISIS3DATA` and then pushed to the user-facing rsync server for distribution. We are adding a "testing/validation" stage between these steps, but not setting up an additional data staging area. It's clear to me that with the change described in this ticket, after the "validation stage," the updated data should get pushed to the gitlab repo, but, I'm having trouble picturing what the first stage of this will look like after the update described in this ticket, since directly modifying `$ISIS3DATA` will not be an option. Would we need to clone data/ locally ~nightly, check for new kernels, test, and if tests pass, push the updates to the gitlab repo?

**Comment by jessemapel** [comment]
> As an example of something that may need to be changed, the commands `make checkout` to get a local copy of test truthdata and `make checkin` to "check in" a local copy of truthdata to the system `$ISIS3TESTDATA` do so by rsyncing back and forth. Presumably we want to change this behavior, as the system `$ISIS3TESTDATA` should no longer be modified directly? see: [isismake.tsts](https://github.com/USGS-Astrogeology/ISIS3/blob/1f35bec3c3b1fceb3cada6519dd53b8fc2bf97b0/isis/make/isismake.tsts)

In this case can't we just set our `$ISIS3TESTDATA` to our own clone of the test data? Then, we can still use `make checkout` and `make checkin` to move data into and out of our clone. Then, once we're ready, we can commit to our clone and pr into gitlab.

> For the Isis kernel download scripts, right now they are being directly downloaded to the system `$ISIS3DATA` and then pushed to the user-facing rsync server for distribution. We are adding a "testing/validation" stage between these steps, but not setting up an additional data staging area. It's clear to me that with the change described in this ticket, after the "validation stage," the updated data should get pushed to the gitlab repo, but, I'm having trouble picturing what the first stage of this will look like after the update described in this ticket, since directly modifying `$ISIS3DATA` will not be an option. Would we need to clone data/ locally ~nightly, check for new kernels, test, and if tests pass, push the updates to the gitlab repo?

I don't think we need to clone nightly, we can keep a clone around and just do the following each day:

1. pull from gitlab
1. download any updates
1. commit to clone
1. push to gitlab

**Comment by Kelvinrr** [comment]
On the subject of how to split up the files under `ISIS3DATA` and `ISIS3TESTDATA`. 

Some quick numbers on `ISIS3DATA`

* The entire `ISIS3DATA` directory is 610.70GB:
* Binary data makes up 583.42GB 
* text data makes up 27.28GB
* The biggest file for both binary and text files is ~2GB (i.e. biggest binary is 2GB, but biggest text file is about the same)
* if we naively commit every text file under 1MB into normal git, the repo would be 220.92MB (for perspective, the ISIS3 repository is 221MB)

Do we want to just add all small text files to normal git and the rest to LFS? Or do we want to be exact with the files placed under normal git?

**Comment by jlaura** [comment]
Every text file <= 1MB to Git, >1MB to LFS looks like a very reasonable way to do this. Can we write a 'simple' rules config to do this or would we need to do a custom script that generates the config on a per file basis?

**Comment by Kelvinrr** [comment]
From looking aroud it seems git lfs track only works with file name patterns. I would like to be wrong here though. I'll keep looking but for now, it seems we will need something custom.

**Comment by jlaura** [comment]
That is also what I have seen in the past. What happens if we LFS all directories containing one or more text file with a size >= 1MB? What does that do to the size numbers? I fear that might have everything in LFS...?

**Comment by Kelvinrr** [comment]
I'll run it and see. 

Apparently, this is as far as they got on the issue so far, at least until the feature is official https://github.com/git-lfs/git-lfs/issues/282#issuecomment-463262318

fun

**Comment by jlaura** [comment]
> What the heck is this piece of code? Absolute mother piece of hack?

Best comment ever.

**Comment by Kelvinrr** [comment]
I had to double-check to make sure I wasn't making any mistakes, but the sum of all files in directories where there exists at least one text file with the total size >1MB is ~610.68GB, basically leaving the non LFS stuff to 24.29MB. 

Cranking up the minimum size for non lfs to 10MB gets us 221.36MB in non lfs and the rest in LFS.

**Comment by jlaura** [comment]
I suspect the config file will look cleaner at the 10MB threshold, but I defer to your thoughts and the thoughts of others on this. Aiming to be around 200MB is probably a good target. The initial ISIS clone is long (for a git clone), but not truly painful.

**Comment by Kelvinrr** [comment]
We ended switching to just making the entire data directory LFS, same with ISIS3DATA. We can move things out as needed. The repo size is still gigantic even while being super conservative about what stays non-LFS. I'm not sure why, but this would be easier to manage anyways. 

I'm not sure how to handle creating copies of repos on a per dev basis? Unless we all have somewhere NFS mounted we can do it from. I don't see turning unused files back into pointers just to acquire them later as an efficient workflow and therefore probably keep several copies of the complete ~500GB data directory. Or we keep it centralized and basically defeating some of the benefits of git?

**Comment by jessemapel** [comment]
I think we're all just going to have our own clones, the vast majority of the data we will never use, so the data areas shouldn't grow dramatically.

**Comment by jlaura** [comment]
Just wanted to update here since the associated RFC is still open. We are working with our bureau wide IT department to understand how best to handle the 80GB of test data (and not the ~800GB) of SPICE data. It is not clear that GitHub, a custom GitLab instance, straight S3, or some other solution is the best option. I'll update this issue and the RFC as we determine what options are viable so that we can best serve the community.

In the interim. the rsync server is still live and well.

**Comment by jessemapel** [comment]
I am going to close this because we've moved off of the Git LFS solution as it's likely non-viable. @jlaura if you want this to remain open please re-open but I don't think there's further discussion to happen here.
