### ISSUE TITLE
Isis Kernel Scripts - investigate curl for kernel downloads

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3285]
**Description**  
Investigate switching wget to curl for fetching kernels.

**Comment by acpaquette** [comment]
So in looking into this I found that curl is rather limited in doing this sort of mass file transfer. There are ways to work around it and it drastically reduces the time to run but I'm not sure if the general programmer overhead is worth it.

```
KERNELSERVERDIR="/pub/naif/MEX/kernels/"
KERNELURL="https://naif.jpl.nasa.gov${KERNELSERVERDIR}"
KERNELDIR="${ISIS3DATA}/mex/kernels/"

for file in $( curl ${KERNELURL}sclk/ | grep href | sed 's/.*href="//' | sed 's/".*//' | grep MEX_[0-9]*_STEP.TSC); do
  curl "${KERNELURL}sclk/$file" > "${KERNELDIR}sclk/$file"
done
```
The above is what I had to do to get the sclk for the MEX mission

**Comment by acpaquette** [comment]
Alternatively!
```
wget -r -nd -N -e robots=off ftp://naif.jpl.nasa.gov/pub/naif/MEX/kernels/sclk/* -A "MEX_??????_STEP.TSC" -X ${KERNELSERVERDIR}*/former_versions/
```

This seems to work for MEX and greatly simplifies and reduces the time of the wget command.

**Comment by krlberry** [comment]
Decided to use ftp if available for all scripts.
