### ISSUE TITLE
Update Version Information in CMakeLists.txt

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#3298]
**ISIS version(s) affected**: x.y.z
3.7.x

**Description**  
The version numbers and release date also need to be updated in the CMakeLists.txt when doing a release.

**How to reproduce**  

Open the CMakeLists.txt.

**Possible Solution**  

I will update the wiki right now. The code needs to be updated before we push 3.7.1 to anaconda.org.

**Additional context**  

A best practice is probably to determine the one place where we want to set the version and then go from there. Right now we need to update the meta.yaml, the version file, and cmakelists.txt. This is a little redundant...

**Comment by jessemapel** [comment]
As a temporary measure, I'm going to add these three locations to the release docs

**Comment by jlaura** [comment]
I got the wiki updated this morning so I think that that should be good to go - unless the wiki edit didn't save like the roadmap one...

**Comment by jessemapel** [comment]
It's up there. I'm going through and cleaning up the wiki while I test the 3.7.1 build

**Comment by SgStapleton** [comment]
I'm sorry I missed the CMakeLists.txt file guys!
