### ISSUE TITLE
Problems of forming MESSENGER phase-ratio images

### ISSUE THREAD

**Issue by ycwang0011** [DOI-USGS/ISIS3#3308]
I'm doing phase-ratio analysis of features on Mercury and try to repeat previous work in Blewett et al_2014_Icarus using the same MDIS NAC and WAC data. But we meet some problems:
1.  The NAC data failed when running with the coreg step. "Group=AutoRegStatistics" in coreg results shows: Total=1024 but successful=0. PatternChip we set is 45 and SearchChip is 65.
2.  The repeated ratio images we did were generally darker than the figures in Blewett_2014.
![Hollows_redo](https://user-images.githubusercontent.com/43131279/58219110-4d4e5600-7d3c-11e9-8d15-b3bdd0e93360.png)
![image](https://user-images.githubusercontent.com/43131279/58219193-8981b680-7d3c-11e9-9254-b3495d9274da.png)

We used isis3 mdis2isis, mdiscal, spiceinit, camstats, footprintinit, cam2map(map drived from mosrange) and photomet, coreg and ratio for processing.  We think that the parameters setting in the coreg lead to such problems. Because for problem 1, no failures and warnings occured in coreg step when we increased the patternchip value from 45 to 60 and searchchip value from 65 to 150. However, the phase-ratio images still look much darker.

Are our operation steps or the coreg parameters wrong? If so, what's the most appropriate coreg parameters for MDIS NAC data?

The data name are: EN1000706325M; EN0251516942M

**Comment by jlaura** [comment]
This is a great question. Would you please post this over at https://astrodiscuss.usgs.gov/ Many more non-developers also frequent that forum and can provide additional support.  Thanks!

**Comment by jessemapel** [comment]
This is a question about appropriate parametrization of an application not a problem with functionality; so I am closing it. Any further discussions should take place on astrodiscuss.
