### ISSUE TITLE
How to use mercury MDIS EDR data to generate calibrated albedo images？

### ISSUE THREAD

**Issue by ycwang0011** [DOI-USGS/ISIS3#3310]
How to use mercury MDIS EDR data to generate calibrated albedo images？
Here's an example of MDIS WAC EDR data.
[EW0218373494G.zip](https://github.com/USGS-Astrogeology/ISIS3/files/3214917/EW0218373494G.zip)

Thanks!

**Comment by jlaura** [comment]
Please open questions like these on https://astrodiscuss.usgs.gov.

Thanks!
