### ISSUE TITLE
Can these internal scripts be archived? 

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3312]
**Description**  
The following `isis3mgr_scripts` do not currently appear to be in use: 

* `FindCVS.sh`
* `cvsStartup.csh`
* `cvsStartup.sh`
* `buildIsis` (replaced by `buildIsisCmake`)
* `buildIsisAllSys` (replaced by `buildIsisCmakeAllSys`) 
* `initIsis.sh` (replace by `initIsisCmake.sh`)
* `initIsis.csh` (replace by `initIsisCmake.csh`) 
* was `sendBuildEmail` replaced by `sendCmakeBuildEmail`? 

There are others that could potentially be added to this list, the included ones are the ones I was more sure about. 

Can these be archived by moving them into `isis3mgr_scripts/archive` ?

**Comment by jessemapel** [comment]
The only things I'm unsure about are the initIsis scripts. They could be convenient for working with old versions of ISIS, but users can just use the public isis3Setup scripts in the actual codes.

**Comment by jessemapel** [comment]
It's been 6 months. We should archive these except the initIsis scripts.
