### ISSUE TITLE
Dawn FC Camera model should not throw an error that says to email someone

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3318]
**ISIS version(s) affected**: all

**Description**  
On line 102 of `DawnFcCamera.cpp`, an error message for an exception has the following appended to it: 
    
```
msg += "Please contact Jeff Anderson (janderson@usgs.gov) with the Dawn FC PDS filename for further testing.";
```

As Jeff Anderson is retired, this line should either be updated or eliminated. (The error message does explain what is wrong without this addition.) 

**How to reproduce**  
N/A - If you wanted to test that the exception is thrown, you'd need to edit a dawn image to not have 1024 x 1024 pixels before ingesting it, but I think just modifying the error message would complete this issue and further testing isn't necessary for this ticket.

**Comment by jlaura** [comment]
Can someone grab this this sprint and just clean it out? This is a super tiny issue that we can fix really fast I think?
