### ISSUE TITLE
qview advanced stretch tool crashes for uniform-value bands

### ISSUE THREAD

**Issue by rvwagner** [DOI-USGS/ISIS3#3323]
**ISIS version(s) affected**: 3.5.1 and 3.7.1 tested so far
Tested on MacOS 10.12.6 and Ubuntu 14.04.5 LTS

**Description**  
In qview, if a cube is displayed in RGB mode, and one of the displayed bands contains entirely 1's (probably any value that is constant over the entire band?), if you start the Advanced Stretch tool, qview hangs for several minutes at 100% CPU usage, and eventually crashes.

**Comment by jessemapel** [comment]
Hi @rvwagner, is there a specific image that this happened on or is it any image with a single value in a band?

If you haven't tested many images, that's okay. It is not hard for us to make a simple test image for this bug.

**Comment by rvwagner** [comment]
I tested it on a 63-band image that the LROC team will be releasing to the PDS soon, but the output of `makecube to=t.cub val=1 sam=5 line=5 band=1` seems to do the same thing.

**Comment by jlaura** [comment]
@scsides What is the status on this? I thought that this work was completed?

**Comment by scsides** [comment]
Fixed with #3616. Forgot to add the Fixes. Closing
