### ISSUE TITLE
qview fails to launch and exits without error message

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#3326]
I'm working on astrovm4 via Putty on my Windows machine. 

Initializing the default ISIS (3.6.0) via 'setisis isis3' (I know - I haven't converted to conda) is successful. When trying to launch qview by simply typing 'qview', the system pauses for a moment and returns to my prompt without providing an error message. Other q applications - qmos, qnet - seem to be acting normally. I was using qview extensively yesterday both from the office and (slowly) from home. This seems to be new this morning.

**Comment by jessemapel** [comment]
What is the error message?

**Comment by jessemapel** [comment]
Also, please fill out the bug template

**ISIS version(s) affected**: x.y.z

**Description**  


**How to reproduce**  


**Possible Solution**  


**Additional context**

**Comment by blandoplanet** [comment]
There is no error message.

ISIS version(s) affected 
3.6.0

Description
I'm working on astrovm4 via Putty on my Windows machine.  Initializing the default ISIS (3.6.0) via 'setisis isis3' (I know - I haven't converted to conda) is successful. When trying to launch qview by simply typing 'qview', the system pauses for a moment and returns to my prompt without providing an error message. Other q applications - qmos, qnet - seem to be acting normally.

How to reproduce
Try typing 'qview' at the command prompt

Possible Solution

Additional context
I was using qview extensively yesterday both from the office and (slowly) from home. This seems to be new this morning.

**Comment by jlaura** [comment]
Is this also present in 3.7.1?

**Comment by blandoplanet** [comment]
Hmmm. Maybe this is a Xming bug. I reproduced this 3 or 4 times an hour ago (even tried a restart of my machine), but now it seems to be working fine.
