### ISSUE TITLE
Running 'setisis isis3' defaults to ISIS3.6.0 rather than the current version of ISIS (3.7.1)

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#3327]
**ISIS version(s) affected**: 3.6.0 and current version

**Description**  
Working on astrovm4, initializing ISIS with 'setisis isis3' defaults to isis3.6.0 rather then the current version (3.7.1).

**How to reproduce**  
On astrovm4, type 'setisis isis3' at the command prompt. Verify that the output states something like:  "ISIS3 Setup In: /usgs/pkgs/isis3.6.0/install - Successful"

**Possible Solution**  
Change the default version of ISIS

**Additional context**  
The same issue is found on astrovm5

**Comment by jessemapel** [comment]
How quickly does products want us to bump to the newest release? As soon as it's out? A week after? This is a very easy fix, just a symlink.

**Comment by jlaura** [comment]
This is a really good question! Where do people work? Do you start a project and pin the version for the entire project? Do you work near the head knowing that issues could arise doing this (the move to the new kernel is a prime example)?

**Comment by blandoplanet** [comment]
I agree that this is a really good question. I assume our "superusers" will be setting ISIS to whatever flavor they want anyway, so this really only affects a small set of people. I would think the default should be to keep up with the current public version (i.e., not the release candidates, but once there's a new release and any bug fixes - 3.7.*). Users can always roll back if we encounter a problem. That's just one opinion though.

**Comment by jessemapel** [comment]
We should go ahead and update the symlink to 3.7.1. I've sent out an e-mail to switch over on the 14th.

**Comment by jessemapel** [comment]
Unfortunately I was out sick on the date we were suppose to switch over and then I got caught up in conferences, so I am going to do this tomorrow morning.

**Comment by jessemapel** [comment]
Done
