### ISSUE TITLE
noprojInstrumentsXXX.pvl entries for Mariner 10

### ISSUE THREAD

**Issue by patmfry** [DOI-USGS/ISIS3#3330]
**Description**  
Could there be entries in noprojInstrumentsXXX.pvl for Mariner 10 vidicons? I know I can add them myself but would like to not have to after data rsync. Thanks.

**Example**  

  Group = "MARINER_10/M10_VIDICON_A"
    DetectorSamples = 832
    DetectorLines = 700
  End_Group

  Group = "MARINER_10/M10_VIDICON_B"
    DetectorSamples = 832
    DetectorLines = 700
  End_Group

**Comment by jessemapel** [comment]
@patmfry Do you have a source for the detector sizes for the instruments? I'd like to have the provenance documented somehow when this is done.

**Comment by patmfry** [comment]
Hi,
How about

@ARTICLE{1974Sci...183.1307M,
       author = {{Murray}, Bruce C. and {Belton}, Michael J.~S. and
         {Danielson}, G. Edward and {Davies}, Merton E. and {Gault}, Donald and
         {Hapke}, Bruce and {O'Leary}, Brian and {Strom}, Robert G. and
         {Suomi}, Verner and {Trask}, Newell},
        title = "{Venus: Atmospheric Motion and Structure from Mariner 10 Pictures}",
      journal = {Science},
         year = "1974",
        month = "Mar",
       volume = {183},
       number = {4131},
        pages = {1307-1315},
          doi = {10.1126/science.183.4131.1307},
       adsurl = {https://ui.adsabs.harvard.edu/abs/1974Sci...183.1307M},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

Thanks,

Pat

**Comment by ladoramkershner** [comment]
Mariner 10 has been added as per your request, thank you for the suggestion! The changes will be available at our next public release (isis 3.9.1) in the next week or so.
