### ISSUE TITLE
Check on status of MESSENGER kernel databases

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3337]
**Description**  
Check to see if MESSENGER kernel db files are getting cleaned up. If not, add cleanup.

**Comment by krlberry** [comment]
(1) There are not many CKs, so I don't think any action needs to be taken there.
(2) There are 50 SPKs, so it does look like these aren't getting cleaned up _but_ there hasn't been a new SPK update since 2015, so might need to run cleanup once, by hand.

**Comment by kberryUSGS** [comment]
Update 2: There is no update script for Messenger kernels, which is why they aren't getting cleaned up. But how did the spk kernel db get all the way up to: `kernels.0184.db` without automated updates?

**Comment by krlberry** [comment]
Ended up doing a one-time cleanup of MESSENGER spk kernel directories.
