### ISSUE TITLE
spiceinit for Cassini can't find newest PCK

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#3340]
**ISIS version(s) affected: All at time of issue creation 3.7.1

**Description**  
I’ve been running into some trouble with the Spiceinit module in ISIS 3.6.2. I’m trying to process  data from the Cassini mission. I’m getting the following error:
“No existing files found with a date version matching [cpck{ddMMMyyyy}.tpc] in[.../isis3/data/cassini/kernels/pck]”
when running: 
`spiceinit from=v1637464787_1_ir
`

See discussion at: https://astrodiscuss.usgs.gov/t/spiceinit-error/171

**How to reproduce**  
With ISIS 3.7.1 or earlier and the bash shell
```
export LC_TIME=nl_NL.UTF-8
spiceinit from=v1637464787_1_ir FAILS

export LC_TIME=“en_US.UTF-8”
spiceinit from=v1637464787_1_ir SUCCEEDS
```

**Possible Solution**  
Find out why the setting of LC_ALL in the Application class constructor is not being honored.

**Additional context**  
spiceinit / kerneldb / filename / highestversion is searching for a kernel file that uses a date as the version number in: .../data/cassini/kernels/pck/cpckDDMMMYYYY.tpc
That search comes back empty when the LC_TIME locale is set to nl_NL.

**Comment by jlaura** [comment]
@scsides How far back does this going? Is this pre-conda transition? I ask just to try and figure out when to schedule (during the RC process or with support).

**Comment by scsides** [comment]
@jlaura Thought I answered this, but obviously not. This looks to be an old problem (pre conda). Previous versions of ISIS on new operating systems exhibit the same behavior. It is possible changes to LOCALE in the new OSs have triggered this.

**Comment by jessemapel** [comment]
This is being caused by the FileName class trying to convert dates with short months in them (E.G. 15Dec2017) when the system locale is set to a different language. For some reason, QT isn't picking up the updated system language correctly when it's overriden as in Application.cpp.
