### ISSUE TITLE
findfeatures multi algorithm fails for Galileo (sometimes)

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#3341]
**ISIS version(s) affected**: 3.7.1

**Description**  
findfeatures fails for Galileo images when using multiple algorithms, but is successful for other Galileo input images.  In the case of failure, findfeatures is successful when running each algorithm as a separate run.  When running with multiple algorithms, the debug log file is created and matches are made, but no other output files are created - it crashes and dumps a core.

**How to reproduce**  
Data Location: /work/users/lweller/Isis3Tests/FindFeatures/MultiAlgo/FailureImageList/

Necessary input files:  multi_algorithms.lis, s0440955239.lev1.cub, s0440955239_fromlist_ff.lis (full paths included)

Command:

> findfeatures algospecfile=multi_algorithms.lis maxthreads=7 match=s0440955239.lev1.cub fromlist=s0440955239_fromlist_ff.lis fastgeom=true geomtype=camera epitolerance=3.0 ratio=0.9 hmgtolerance=3.0 networkid=s0440955239 pointid='s0440955239_?????' onet=s0440955239_ff.net tolis=s0440955239_cubes_ff.lis tonotmatched=s0440955239_notmatched_ff.lis description='Create image-image control network' debug=true debuglog=s0440955239_ff.log

> terminate called after throwing an instance of 'std::out_of_range'
>   what():  vector::_M_range_check: __n (which is 7039) >= this->size() (which is 6740)
> ./runcmd: line 1: 45976 Aborted                 (core dumped) 

The command is contained in runcmd for easy execution/reference.  The output debug file is created and called s0440955239_ff.log.

Also under this directory (../FailureImageList/...) are two separate single algorithm runs (attempted in multi list) with their input and successful output files as reference - FastBrief/ and SiftSift/.  It is only when I try to use multi-algorithms with this set does it fail.

See /work/users/lweller/Isis3Tests/FindFeatures/MultiAlgo/SuccessfulImageList/ for a different set of Galileo images using multi algorithms where findfeatures was successful.  The command line is in runcmd.  I also ran the algorithms independently under separate directories to be sure the best output was being selected via the multi- run.  Looks good.

Nothing majorly different between failed and successful set that I can see.

**Additional context**  
In both the successful and failed cases there are images in the fromlist that will not be successful during the matching process.

**Comment by jlaura** [comment]
@paarongiroux @Kelvinrr Can you all update this issue with some info on what you all looked at and potential paths forward.

**Comment by paarongiroux** [comment]
findfeatures is using a function called `best` in the MatcherSolution class to determine which algorithm from the list to use. In the command provided by @lwellerastro, this method determines fast/brief to be the better of the two. 

The program fails in line 320 of main at the call :
`PvlGroup cnetinfo = matcher.network(cnet, *best, pointId);`

This network function in the matchmaker class has the following nested for loop: 
``` 
  MatchImage v_query = (*solution.begin()).query();
  QVector<ControlPoint *> points(v_query.size(), 0);
  int nMeasures(0);
  int nImages(0);
  MatcherSolution::MatchPairConstIterator v_pair = solution.begin();
  for ( ; v_pair != solution.end() ; ++v_pair) {
    if ( v_pair->size() > 0 ) { nImages++; }
    for (int m = 0 ; m < v_pair->size() ; m++) {
      int index = v_pair->match(m).queryIdx;
      nMeasures += addMeasure(&points[index], *v_pair,
                              (*v_pair).match(m), solution);
    }
  }
```

The actual failure message comes from the following assertion in the addMeasure function: 
```
  Q_ASSERT ( ( point.queryIdx >= 0) &&
             ( point.queryIdx < mpair.query().size() ) );
```

Based on the failure message as seen in @lwellerastro's original post, we can see that in this case, mpair.query().size() is returning 6740, which it should not be. When running the program with only one algorithm at a time, we can see that 6740 is the .query().size() for the sift/sift algorithm, while the fast/brief algorithm **_should_** return 26218 as its .query().size(). If the program were running correctly, the number 7039 from the failure message would be well within the range from the Q_ASSERT and would not cause a problem. 

We haven't found where or why these values are being swapped across the two algorithms in the code. 

Another interesting thing to note is that when the order of the algorithms in the list provided in the original post is swapped, the program seems to run perfectly fine.

**Comment by acpaquette** [comment]
I'm closing this as the bug should be fixed.
