### ISSUE TITLE
Is src folder missing when installing latest isis3 version via Anaconda?

### ISSUE THREAD

**Issue by victoronline** [DOI-USGS/ISIS3#3342]
**ISIS version(s) affected**: 3.7.1

**Description**  
When installing ISIS3 via Anaconda, the src folder is not included in the install (at least I can't find it).

**How to reproduce**  
Install the latest version via Anaconda

**Possible Solution**  
Include src folder as part of the install

**Comment by jessemapel** [comment]
With Anaconda we only distribute the binaries and what's required to run them. Is there a reason why you would need the source code too?

**Comment by rbeyer** [comment]
That reads funny out of context: 'why do you need the source code?"

Of course, Jesse means, "Is there a reason why you would need the source code distributed with the Anaconda packages, instead of just pulling it from GitHub when you need it."

I had this same initial issue.  At one point I reflexively went looking for the src/ directory, got miffed that it wasn't there, and then remembered that it was on GitHub, which satisfied the need.

**Comment by victoronline** [comment]
Haha.  I should have provided more context. To answer the question, our users probably refer to the source code more than the documentation when using ISIS. They do this to make sure they are using the software correctly, to verify the formulae used are what they are expecting, and to better understand the changes between software versions. Due to this, they like having the src code readily available. Of course, we can pull it down from Github. But I just wanted to know if excluding the src folder was part of making the install leaner (like excluding the documentation (80GB+ !!), or if there was another reason. I couldn't find any info in the install documentation as to why it was excluded. I asked Jay at the PDW and he stated it was an oversight and to open an issue to get it added back.

**Comment by victoronline** [comment]
So should I assume that the source folder going to not be added? I just need to know so I know what to do on my end.

**Comment by jlaura** [comment]
@victoronline Apologies for the late reply. At this time, yes, we are not going to be shipping the source with the release as the source is available on GitHub.

**Comment by victoronline** [comment]
No worries. Thanks for the reply.  Closing.

**Comment by jlaura** [comment]
@victoronline One thing I failed to add is that we anticipate the best way to see the source associated with the version is to use the associated Tag on GitHub. For a non-dev user this is likely not going to be at all intuitive. What can we do to assist users in finding the source associated with a release that they are using? Would this be something the users you are supporting would look for in the wiki? readme? Thanks!

**Comment by victoronline** [comment]
I think they would look for it in the ISIS application documentation (not on GitHub). I think somehow linking the source code on GitHub to this documentation would be helpful for non-dev users. For example, if a user needed information about lrowacpho, they will most likely search "usgs isis lrowacpho", which will ultimately take them to https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/lrowacpho/lrowacpho.html. It would be convenient if there was a link at the foot of the documentation to the GitHub repository containing the source code for that app.
