### ISSUE TITLE
Update spiceinit to optionally output a meta-kernel containing the kernels selected by ISIS.

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3345]
**Description**  
Update `spiceinit` to include an option to output a meta-kernel to a file (in addition to doing what it normally does to attach kernel information to the cube.) 

This would include adding a user-parameter to specify whether or not to generate an output metakernel (default = no) and, if yes, another user-parameter for the filename for the output metakernel. 

For meta-kernel information see:
https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/req/kernel.html#Path%20Symbols%20in%20Meta-kernels

The exported meta-kernel could look something like the following for a cube that has been spiceinited internally.

```
   \begindata
 
   PATH_VALUES  = ( '/usgs/cpkgs/isis3/data/base/kernels', '/usgs/cpkgs/isis3/data/tgo/kernels')
 
   PATH_SYMBOLS = ( '$base', $tgo' )
 
   KERNELS_TO_LOAD = ( '$base/naif0012.tls',
                       '$tgo/something.tsc',
.
.
.
.
.
.
)
 
   \begintext
```

**Comment by jessemapel** [comment]
This functionality is available via [ALE](https://github.com/USGS-Astrogeology/ale/blob/master/ale/util.py). @kberryUSGS is that sufficient to close this?

It may be moved somewhere else in the next few weeks. I will post here if that happens.

**Comment by krlberry** [comment]
Closed because functionality is available in ALE. I'm not sure where is best to document that this is available, but once things stabilize more, it's probably useful to do so.
