### ISSUE TITLE
CISSCAL update to 3.91

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#3351]
**Description**  

The released `cisscal` IDL routine was updated to 3.91 (current ISIS3 cisscal uses 3.8), with 3.9 having a significant upgrade in the calibration compared to 3.8 (at least it sounds like it).

A nice changelog and links to cisscal and docs can be found here, maintained by the Rings/Moons node:
https://pds-rings.seti.org/cassini/iss/index.html

**Comment by jlaura** [comment]
PR solicited to make this enhancement. I do not see the internal dev team making this upgrade in the short term.

**Comment by kaitlyndlee** [comment]
Hi @michaelaye ,

It looks like sensitivity vs time correction was added to the calibration steps and is on by default. It looks like there is no way for a user to turn on/off steps in the ISIS version of cisscal, but there is in the original cisscal (I might be completely wrong on this). Do we want ISIS to always try to do sensitivity vs time correction?

**Comment by michaelaye** [comment]
For compatibility between scientists and their analysis systems, my first recommendation would just be that the defaults should be the same. If CISSCAL 3.8 did something not while it's default in CISSCAL 3.9, I would recommend to do the same changes in ISIS' cisscal. Ideally, it really shouldn't happen that a science team is puzzling about differences after having made sure that they have used the same cisscal version to calibrate their data. The author's of IDL's cisscal are the people who know the instrument best, so whatever they recommend to you should be the best choice for the default. Of course it would be a plus if I _could_ switch on/off certain steps of the procedure, but certainly not required for all steps (it doesn't make sense to not do bias removal, otherwise I might as well just work with the raw data).
