### ISSUE TITLE
Conda install instructions are currently failing

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#3356]
**ISIS version(s) affected**: (3.6.0)+

Precise current version does not seem to be mentioned on Install Instructions website https://isis.astrogeology.usgs.gov/documents/InstallGuide/index.html

**Description**  

I followed all install instructions on 
https://isis.astrogeology.usgs.gov/documents/InstallGuide/index.html.

When getting to:

`conda install -c usgs-astrogeology isis3`

I get

```bash
$ conda install -c usgs-astrogeology isis3                                                     (isis3)
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - isis3 -> geos==3.5.1

Current channels:

  - https://conda.anaconda.org/usgs-astrogeology/osx-64
  - https://conda.anaconda.org/usgs-astrogeology/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
**How to reproduce**  

```bash 
conda create -n isis3 python=3.6
conda activate isis3
conda config --env --add channels conda-forge
conda config --env --add channels usgs-astrogeology
conda install -c usgs-astrogeology isis3
```

Here is my conda info:

```bash

     active environment : isis3
    active env location : /Users/klay6683/miniconda3/envs/isis3
            shell level : 2
       user config file : /Users/klay6683/.condarc
 populated config files : /Users/klay6683/.condarc
                          /Users/klay6683/miniconda3/envs/isis3/.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/klay6683/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/usgs-astrogeology/osx-64
                          https://conda.anaconda.org/usgs-astrogeology/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/klay6683/miniconda3/pkgs
                          /Users/klay6683/.conda/pkgs
       envs directories : /Users/klay6683/miniconda3/envs
                          /Users/klay6683/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 273771:2260
             netrc file : None
           offline mode : False

```

**Comment by jlaura** [comment]
That version of geos is currently available for [linux](https://anaconda.org/usgs-astrogeology/geos/files) and [osx](https://anaconda.org/conda-forge/geos/files?page=2).

Having said that, I am able to reproduce this on an OSX laptop, so not sure what is going on.

**Comment by michaelaye** [comment]
Platform is osx-64, as reported by `conda info`.

**Comment by michaelaye** [comment]
It looks like it's precisely the osx-64 branch only that is missing geos:

```bash
$ conda search 'geos[channel=usgs-astrogeology, subdir=linux-64]'                              (isis3)
Loading channels: done
# Name                       Version           Build  Channel
geos                           3.5.1      h6bb024c_1  usgs-astrogeology
klay6683@macl3886|~/D/src
$ conda search 'geos[channel=usgs-astrogeology, subdir=osx-64]'                                (isis3)
Loading channels: done
No match found for: usgs-astrogeology/osx-64::geos. Search: usgs-astrogeology/osx-64::*geos*

PackagesNotFoundError: The following packages are not available from current channels:

  - usgs-astrogeology/osx-64::geos

Current channels:

  - https://conda.anaconda.org/usgs-astrogeology/osx-64
  - https://conda.anaconda.org/usgs-astrogeology/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by michaelaye** [comment]
Also looks like on here, that only the linux version is being offered:

https://anaconda.org/usgs-astrogeology/geos

**Comment by jlaura** [comment]
Yes. 

As I already posted, I am able to reproduce on an OSX box. Also, as I already linked, the osx version of geos at 3.5.1 is available via Conda-forge and not the usgs-astrogeology anaconda repo. All of this is as expected currently. 

I have reproduced your issue on a clean OSX installation so we can go from there.

**Comment by michaelaye** [comment]
I think this is a conda bug. :( Otherwise I cannot explain why it would not see the 3.5.1 osx version in the conda-forge repo you linked.

**Comment by michaelaye** [comment]
Unfortunately, downloading and installing the tarball with conda is no work-around, because after that, conda still fails to resolve the dependency tree:

```bash
$ conda install /Users/klay6683/Downloads/geos-3.5.1-1.tar.bz2                                 (isis3)

Downloading and Extracting Packages
############################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
klay6683@macl3886|~/D/src
$ conda install -c usgs-astrogeology isis3                                                     (isis3)
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - certifi -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']
  - conda-forge/osx-64::python==3.6.7=h94afb7f_1005 -> openssl[version='>=1.1.1a,<1.1.2a']
  - conda-forge/osx-64::python==3.6.7=h94afb7f_1005 -> sqlite[version='>=3.28.0,<4.0a0']
  - isis3 -> cmake==3.9.1 -> curl -> krb5[version='>=1.16.3,<1.17.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - isis3 -> opencv[version='3.2.0|3.3.0'] -> numpy[version='>=1.8'] -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']
  - openssl
  - pip -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']
  - setuptools -> certifi[version='>=2016.09'] -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']
  - sqlite
  - wheel -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']

```

**Comment by michaelaye** [comment]
See https://github.com/conda/conda/issues/8875

**Comment by michaelaye** [comment]
So, the conda issue of not offering a listed package has been closed as a non-issue, b/c the package was on a different label. 
Labels are a conda feature I didn't use yet (apparently the USGS channel isn't either, looking at it?) that's why I didn't click there. 
In this case though, the Mac version of the package isn't even listed anywhere on the channel, so somebody did remove it? Because we had this working before...

**Comment by owenschris** [comment]
replace the line 
conda create -n isis3 python=3.6
with 
conda create -n isis3
Maybe the python version has been updated? This worked for me.

**Comment by michaelaye** [comment]
This shouldn't make any difference, because the isis3 package only has py36 builds anyway.
So, when you do `conda create -n isis3` all you do is creating an empty environment. What did you do after that? `conda install isis3`? On which operating system did this presumably work? Can you provide a complete list of commands that ended up with a working `isis3` environment?

**Comment by michaelaye** [comment]
So, if USGS for some reason or another isn't able to put the geos 3.5.1 OSX package back on their channel, the work around is to fish the correct package out of the conda-forge archive, using the label:

```bash
conda install conda-forge/label/cf201901::geos==3.5.1
conda install isis3
```
Note, I don't need to provide the channel again, because the usgs-astro channel is the only channel providing a package called `isis3`.

This only works if your sources look like given in the install instructions:

```bash
==> /Users/klay6683/.condarc <==
pinned_packages: []
report_errors: True
anaconda_upload: True

==> /Users/klay6683/miniconda3/envs/isis3/.condarc <==
channels:
  - usgs-astrogeology
  - conda-forge
  - defaults

```

**Comment by owenschris** [comment]
Oops, sorry about that. Removed to avoid confusion. On Ubuntu 16.04, have noticed that the resolve environment step that occurs after `conda install -c usgs-astrogeology isis3` fails immediately after updating conda, but completes without error after using the same command when conda has not been updated.

**Comment by jlaura** [comment]
I just pulled the Conda-forge geos and pushed it to our organization, but no joy. The errors are now:

```
  - certifi -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']
  - conda-forge/osx-64::python==3.6.7=h94afb7f_1005 -> openssl[version='>=1.1.1a,<1.1.2a']
  - conda-forge/osx-64::python==3.6.7=h94afb7f_1005 -> sqlite[version='>=3.28.0,<4.0a0']
  - isis3 -> cmake==3.9.1 -> curl -> krb5[version='>=1.16.3,<1.17.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - isis3 -> opencv[version='3.2.0|3.3.0'] -> numpy[version='>=1.8'] -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']
  - openssl
  - pip -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']
  - setuptools -> certifi[version='>=2016.09'] -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']
  - sqlite
  - wheel -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0']
```

Did something major change on the Conda-forge side in the last 30 days or so because installations were working with zero issue until this cropped up?

**Comment by michaelaye** [comment]
So, it's getting weird now.
I see indeed 2 different behaviors with this, depending on creating an empty environment and an environment that starts off with python=3.6.

This one works (on Mac):

```bash
conda create -n isis3_test
conda activate isis3_test
conda config --env --add channels conda-forge
conda config --env --add channels usgs-astrogeology
conda install isis3
```

This one fails:

```bash
conda create -n isis3_test python=3.6
conda activate isis3_test
conda config --env --add channels conda-forge
conda config --env --add channels usgs-astrogeology
conda install isis3
```

What changed in the last 30 days is the minor version update of `conda`, they are using quite a different solver, and I'm seeing GH issues where 4.7.x fails to resolve things that were solvable in 4.6.x
However, as the build version of isis3 of py36 will point all dependent packages to 3.6 anyway, maybe we should just take the working path as okay?
Would be nice if you guys could run the test suite on that install to see if it fully works.

**Comment by jlaura** [comment]
@michaelaye To confirm - the top block in your previous comment results in a successful installation (I realize no tests have been run) of isis3.7.1?

**Comment by michaelaye** [comment]
yep:

```bash
$ conda activate isis3                                                                       (py37)
klay6683@macl3886|~/D/src
$ conda list isis3                                                                          (isis3)
# packages in environment at /Users/klay6683/miniconda3/envs/isis3:
#
# Name                    Version                   Build  Channel
isis3                     3.7.1                    py36_0    usgs-astrogeology
klay6683@macl3886|~/D/src
```

**Comment by jlaura** [comment]
:+1: Great. I realize not a solid solution yet, but glad to see movement towards a resolution.

**Comment by owenschris** [comment]
At least qview and some of the basic things seem to be working, if there is a more specific test suite that I could run, I will if you point me in the right direction.

**Comment by jessemapel** [comment]
@owenschris Geos is used to work with latitude/longitude polygons, so programs like footprintinit, qmos, findimageoverlaps, equalizer, etc. would potentially be impacted by a change in the version of geos we use.

**Comment by michaelaye** [comment]
I don't think we changed or suggested to change the geos version anywhere?

**Comment by jessemapel** [comment]
@michaelaye Ah sorry, it looks like a potentially different build, not a different version. I thought conda-forge pushed a new build up under a different label?

**Comment by michaelaye** [comment]
yes but that's not coming in under any of above suggestions. If one removes the python=3.6 from the env creation, installing `isis3` still uses your requirements table with the correct version number, that's unavoidable.
So, my workaround exactly pulled the correct version from conda-forge's archive (now not necessary anymore b/c Jay put that version back onto the USGS channel.
Come to think of it, maybe you never had the OSX version on your channel, but at the time it was the correct version coming in via conda-forge. Then they removed that version from the `main` label, breaking the `isis3` requirements b/c it wasn't on your channel?

**Comment by jessemapel** [comment]
> Come to think of it, maybe you never had the OSX version on your channel, but at the time it was the correct version coming in via conda-forge. Then they removed that version from the `main` label, breaking the `isis3` requirements b/c it wasn't on your channel?

I think this is what happened.

**Comment by owenschris** [comment]
> yes but that's not coming in under any of above suggestions. If one removes the python=3.6 from the env creation, installing `isis3` still uses your requirements table with the correct version number, that's unavoidable.
> So, my workaround exactly pulled the correct version from conda-forge's archive (now not necessary anymore b/c Jay put that version back onto the USGS channel.

@michaelaye is this issue resolved then?

**Comment by jessemapel** [comment]
@owenschris No, we have a workaround right now. We probably need to update the environment file to have the new label automatically accounted for.

**Comment by jlaura** [comment]
@jessemapel We are going to discuss this issue at the standup this morning and see about getting 1-2 people onto it either this week or next week as we are inside an RC window and I would like to have our broader user community able to install 3.8.0 without every encountering any of these issues.

**Comment by michaelaye** [comment]
this looks like working now? I just did a fresh reinstall. Did you add a \ to the title on purpose though?

**Comment by jessemapel** [comment]
@michaelaye I'm working on this right now. I did not mean to add the slash! Right now we have it patched by adding geos to our channel. I'm testing on going back to conda-forge and either using the cf201901 label or using a new version of geos.

**Comment by jessemapel** [comment]
Updating geos is a no-go as we use the unstable C++ API so we're kind of hard pinned here.

**Comment by jessemapel** [comment]
The linux Geos 3.5.1 on conda-forge under cf201901 doesn't appear to be compiled with gcc7. I think we're going to have to continue serving geos 3.5.1 compiled with gcc7 ourselves.

**Comment by jlaura** [comment]
@jessemapel Since we are serving this, can/should this issue be closed? The install instructions are working as written now that we are hosting. The issue to open perhaps is to be able to install ISIS alongside GDAL. This is something we are targeting in FY20; that should obsolete our need to host a custom geos.

**Comment by Kun-Thapar** [comment]
Hi. I tried installing isis3 on my windows laptop using conda prompt and I get an error stating "The following packages are not available from current channels" and it lists isis3. Did anyone get any solution for this??

**Comment by michaelaye** [comment]
Windows isn't supported officially, see https://github.com/DOI-USGS/ISIS3/wiki/FAQ#how-do-i-install-isis-on-windows

**Comment by Kun-Thapar** [comment]
Okay. Thank you
