### ISSUE TITLE
Redundant Find Scripts in Cmake directory

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#3360]
**ISIS version(s) affected**: >= 3.6.1 (really all versions since the CMake refactor 🤷🏻)  

**Description**  

Originally brought up here: https://github.com/USGS-Astrogeology/ISIS3/pull/3359

There are a few find scripts in ISIS that are also offered by Cmake, at least in Cmake v3.10. 

* `FindBoost.cmake`
* `FindBullet.cmake`
* `FindGSL.cmake`
* `FindHDF5.cmake`
* `FindPNG.cmake`
* `FindProtobuf.cmake`
* `FindTIFF.cmake`
* `FindX11.cmake`
* `FindXercesC.cmake`

I imagine most of these were leftover from when CMake still used v007 libraries and we the built-in stuff didn't work nicely with the weird v007 versions. (e.g. v007 lib dir being added to the search directory for libraries but `gsl-config` not being added to `PATH`, causing the built-in FindGSL script to fail). Now with mostly standard installs, I imagine a lot of these can go. 

This only really creates problems with version reinforcement right now since our scripts do not check for version numbers. I wouldn't be surprised if some versions in CmakeLists are out of date, so we can probably disregard this if we simply want Conda to enforce dependency versions and let CMake just grab whatever is installed so we don't maintain two version lists.  

**How to reproduce**  

Pretty much anytime you run the configuration step for building ISIS with Cmake. 

**Possible Solution**  

Most of these can probably be deleted from the repo and Cmake should automatically use its own scripts. 

**Additional context**

**Comment by jlaura** [comment]
Is this also 3.7.x and 3.8.0_RC?

**Comment by jessemapel** [comment]
@jlaura Yes, this is every version since the cmake integration

**Comment by Kelvinrr** [comment]
closed with #3394
