### ISSUE TITLE
conda and cmake version

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#3361]
When I run

conda create -n isis3 python=3.6

based on 

https://github.com/USGS-Astrogeology/ISIS3

it installs cmake 3.9.1. But later when I want to build ISIS based on

https://github.com/USGS-Astrogeology/ISIS3/wiki/Developing-ISIS3-with-cmake#building-isis3

it asks for cmake 3.10. 

I am aware that the former is for using ISIS and the latter is for building ISIS, but even so it would be nice if the two could be kept in sync. Or maybe there is a reason for this that I am missing.

**Comment by jessemapel** [comment]
ISIS uses cmake 3.10+ because it has ctest/gtest integration for our new tests. So, 3.9 is fine for the runtime. Honestly, you don't even need cmake to run ISIS, so it can be completely removed from the runtime environment.

**Comment by jessemapel** [comment]
This has been resolved in #3549. We removed cmake from the install environment and now only have it in our build environment.
