### ISSUE TITLE
Add MRO SPKs from JPL Solar System Dynamics group

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3362]
**Description**  

ISIS only distributes the Navigation SPKs for MRO right now. JPL's SSD group has created higher quality SPKs from gravity modeling and we should use them when available.

**Example**  

This should automatically be picked up by spiceinit using the kernel.db files, so there's not really an example.

**Comment by jessemapel** [comment]
See https://astrodiscuss.usgs.gov/t/update-isis-data-area-to-use-jpl-dynamics-spks-for-mro/209 for more detailed discussion.

**Comment by jessemapel** [comment]
I'm tagging this as products because it's had an impact the CTX global mosaic processing.

**Comment by jlaura** [comment]
@jessemapel I believe this can be closed?
