### ISSUE TITLE
Library version

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#3365]
I see that ISIS is now at version 3.8, but the output built library still says 3.6: https://github.com/USGS-Astrogeology/ISIS3/blob/ef390cc4510b0c7ef677604f756372edf363c0c5/isis/CMakeLists.txt#L391

This could be on purpose. I just was surprised that after I built the freshest ISIS the library number was still the same.

**Comment by jlaura** [comment]
This is a bug. @all Can we get this slotted next week as well and then get the release docs updated.

**Comment by SgStapleton** [comment]
So, it looks like these are rm commands... This is clearly not correct, but I am not sure these lines would be responsible for the creation of the libisis3.6(.0).so files in the first place.

**Comment by oleg-alexandrov** [comment]
There is also this:

https://github.com/USGS-Astrogeology/ISIS3/blob/ef390cc4510b0c7ef677604f756372edf363c0c5/isis/cmake/CMakeLists.txt#L7

And this one, though it is likely unused but may need cleaning up: https://github.com/USGS-Astrogeology/ISIS3/blob/ef390cc4510b0c7ef677604f756372edf363c0c5/isis/cmake/cmake_install.cmake#L36

That file has some more libisis3.5 lines.

**Comment by oleg-alexandrov** [comment]
Now at isis 4.1.0, but the library is still named libisis3.6.0.so. There is also a sym link saying libisis3.so. I guess version 3 has staying power. :)

**Comment by jlaura** [comment]
@Kelvinrr It looks like #3992 closed this. I am going to close. Please reopen if this is still an issue.
