### ISSUE TITLE
hideal2pds feature, issue #2692, not in 3.7.0

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#3366]
**ISIS version(s) affected**: 3.8.0

**Description**  

The requested feature from issue #2692 did not get PRed into the dev branch for the 3.8.0 release

**How to reproduce**  

Run hideal2pds from a 3.8.0 install. The feature does not exist

**Possible Solution**  

**Additional context**  

@jlaura

**Comment by jlaura** [comment]
The issues here is that the feature missed the 3.8.0 release when it should have been included. We are currently doing a 2 week support sprint that is going to result in a 3.8.1 release. My current thinking on this is that we do the 2 week support sprint (resulting in a 3.8.1) release. At the end of next week we also merge in #2692 and peel off a 3.9.0_RC that includes the hideal2pds enhancement and all of the fixes from the previous 2 weeks.

The three things I am trying to avoid using this timeline are: (1) mixing the enhancement in with bug fixes in a 3.8.1 release; this breaks the semantic versioning requirement we have agreed to follow and generally makes things challenging, (2) immediately re-pushing a 3.8.0 release with the enhancement; this removes the entire RC process that we have agreed to follow, and (3) waiting until the 3.9.0 release time; we have committed to releasing the feature so I would like to do it as expeditiously as is responsible.

Thoughts?

@audiefen - how does that work for your team?

**Comment by audiefen** [comment]
@jlaura - That works for us. Thanks!

**Comment by jessemapel** [comment]
We're trying to wrap up some other changes and getting testing done, so we're going to have to push the release back to this Friday.

@audiefen If this is a problem for y'all please let us know.
