### ISSUE TITLE
Applying to have ISIS classified as a top level project of the Planetary Software Organization

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3367]
# The Planetary Software Organization Technical Steering Committee

As part of going to open source, the Astrogeology Science Center is handing off governance of the ISIS software project to the community. As we've been doing this, it has become clear that this is something that is more broadly useful to the community. As a result, the Astrogeology Science Center Technical Steering Committee has re-organized as the [Planetary Software Organization Technical Steering Committee](https://github.com/planetarysoftware/TSC). As part of this re-organization, we want ISIS to be an example of how the PSO TSC can help projects with and what the process of applying looks like.

# What this means for the ISIS project

So, we need to apply to be a top level project under [this document](https://github.com/planetarysoftware/TSC/blob/master/Project-Lifecycle.md). We will need to fill out [this application](https://github.com/planetarysoftware/TSC/blob/master/Applications/Template.md) in order to be considered.

# What this issue is for

I'd like this issue to be place where we can work on this application. If you are interested in helping out or being involved in the governance of ISIS going forward please post on this issue. From the PSO TSC meeting last month people who have already expressed interest are:

* @jessemapel 
* @jlaura 
* @rbeyer 
* @victoronline 
* @michaelaye

**Comment by jessemapel** [comment]
Here's the draft application so far

___

## Introduction
The ISIS software project is a collection of planetary image processing applications for data collected by a wide range of sensors.

## History & Metrics
Originating back in the 1970s, ISIS has a long history that is detailed [here](https://isis.astrogeology.usgs.gov/documents/IsisHistory/IsisHistory.html). Recently, the ISIS project has started transitioning to open source and is seeking greater community involvement.

Currently, ISIS has 34 code contributors on Github. The majority of them are employees or past employees of the Astrogeology Science Center (ASC). In the last year, a small number of non-ASC personnel have contributed to the project.

The ISIS software package has been downloaded from Anaconda cloud over a thousand times in the last year.

## Scope
The ISIS software project encompasses software used for photometric and photogramettric processing of planetary remote sensing data.

The ISIS working group will have sole responsibility and discretion over the Planetary Software
project in the following areas:

* Setting release dates.
* Release quality standards.
* Technical direction.
* Governance process and practices.
* Contribution process and practices.
* Maintaining the list of additional Collaborators.
* Development process and any coding standards.
* Mediating technical conflicts between Collaborators and Working Groups.

## Governance
The ISIS software project is currently governed by the Astrogeology Science Center and headed by Jay Laura(@jlaura). For large changes, requests for comment are made and posted on the Github Wiki.

## Contributions
Contributions are proposed via pull request on Github and then reviewed by software developers at the ASC. Bug reports are posted as Github issues.

## Tools
The ISIS software project uses a variety of tools:

- The source code is hosted on Github at https://github.com/USGS-Astrogeology/ISIS3
- Releases of the source code are provided via Github https://github.com/USGS-Astrogeology/ISIS3/releases
- Bug reports and enhancements are posted on Github issues https://github.com/USGS-Astrogeology/ISIS3/issues
- Changes to the software are made via Github pull requests https://github.com/USGS-Astrogeology/ISIS3/pulls
- Some developer documentation and governance documents are posted on the Github wiki https://github.com/USGS-Astrogeology/ISIS3/wiki
- Usage questions and general software announcements are posted on a Discourse forum https://astrodiscuss.usgs.gov/
- Documentation and some training/tutorials are hosted on a website https://isis.astrogeology.usgs.gov/
- Data and test data are hosted on an rsync server run by the ASC
- Git LFS is being investigated as a way to distribute the data and test data https://github.com/USGS-Astrogeology/ISIS3/wiki/RFC4---Migration-of-ISIS-Data-to-Git
- Building is done via cmake
- Third party dependencies are managed via Anaconda environments
- Releases are built and distributed via Conda Build and Anaconda Cloud
- Automated tests are written in a combination of GNU Makefiles and GoogleTest
- Tests are run by ctest
- A Jenkins CI server is currently being worked on astroservices.usgs.gov/jenkins

## IP
The ISIS software project is licensed under the UnLicense and committed to the public domain.

## TC Members
* @jessemapel 
* @jlaura 
* @rbeyer 
* @victoronline 
* @michaelaye

## Working Groups
The ISIS software project was previously run by a three person software architecture group.

## Provisional
This project is applying for provisional inclusion and incubation in the ASC Software Organization

**Comment by jessemapel** [comment]
I realized I forgot some tools like gtest, ctest, and jenkins.

**Comment by SgStapleton** [comment]
Was going to mention those. As far as jenkins, should that be included before actual implementation? (I know this should theoretically be in the next couple weeks anyhow, but...) And if that is the case, should we mention new hosting platform for data as well (since that should hopefully be accomplished this sprint)?

As far as history (or tools?), is it worth mentioning the make system changes (cmake)?

(There are just a handful of typos as well, but nothing glaring.)

**Comment by jessemapel** [comment]
Should I convert this to a document that people can directly edit?

**Comment by SgStapleton** [comment]
Might be useful.

**Comment by jessemapel** [comment]
I'm going to copy this over and officially "submit" the application today

**Comment by jessemapel** [comment]
This is now happening at https://github.com/planetarysoftware/TSC/pull/47
