### ISSUE TITLE
ImportPDSTable, brittle test causes MacOS Failures. 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#3376]
**ISIS version(s) affected**: > 3

**Description**  

This has been a repeated issue since starting at astro: ImportPdsTable mixes the case in the `ImportPdsTable/data/invalid*` files. Not really sure the motive, but it causes failures in MacOS since MacOS machines generally have the case-insensitive version of the Apple filesystem. This causes a false negative since the files are printed with a different case in the output for ImportPdsTable's unit test.   

**How to reproduce**  

Running ImportPdsTable on any mac with Apple's case-insensitive filesystem.  

**Possible Solution**  

The quick option is to update the `ImportPdsTable/data/invalid*` files so it doesn't use mixed case and is all lower case. Alternatively, converting the test over to a gtest would also solve the problem since gtest will be able to assert an exception was raised and not deal with the body of the exception message and whether it printed `.dat` vs `.DAT`.   

**Additional context**

**Comment by jlaura** [comment]
What are we talking about in terms of effort to get this ported to GTest? Seems like that is the better way to go, but I would not want to derail the current support efforts.

**Comment by Kelvinrr** [comment]
My take is that debugging tests and getting Jenkins going is more important, update files and move on (I already did this, PR will be up in a bit). We can port this sometime later, maybe if we burn through things fast and someone needs something to do or something.

**Comment by Kelvinrr** [comment]
Fixed with #3380
