### ISSUE TITLE
Update tests after MRO kernel updates 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#3377]
**ISIS version(s) affected**: 3.8.1

**Description**  

As part of the work on https://github.com/USGS-Astrogeology/ISIS3/issues/3363, new reconstructed kernels are available for MRO. This caused some tests to fail: 

* KernelDb unit test 
* mro_module_test_hirise module test 

and possibly: 

* spiceinit_app_test_ckConfigFile 
* hijitter_app_test_degault 

The latter 2 still need some investigation. 

**How to reproduce**  

Running ISIS tests with ISIS3DATA=/usgs/cpkgs/isis3/data internally, anytime after 8/5/2019.

**Possible Solution**  

These should just need updated test data to reflect new kernels. 

**Additional context**

**Comment by jlaura** [comment]
@Kelvinrr Can we close with #3380 merged?
