### ISSUE TITLE
cmake configure should default to release mode and type debug should be Og

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#3387]
**ISIS version(s) affected**: x.y.z
3.7.0 and up
**Description**  

The cmake configure should default to "release" mode with full optimization (O3). Debug mode should default to (Og). Currently the default looks to be no "-g" and no "O" resulting in very slow executions.
**How to reproduce**  

Run a new configure, make -vv, check compile lines for "-O" and/or "-g"

**Possible Solution**  

**Additional context**

**Comment by jessemapel** [comment]
The answer on this stackoverflow seems like a reasonable solution https://stackoverflow.com/questions/41361631/optimize-in-cmake-by-default

**Comment by scsides** [comment]
Yes that looks correct, except for CMAKE_CXX_FLAGS_DEBUG should be -Og for linux gnu g++, not sure about mac clang

**Comment by jessemapel** [comment]
I've at least updated the wiki to indicate you should build with `-DCMAKE_BUILD_TYPE=RELEASE`
