### ISSUE TITLE
Does isis3VarInit.py really need to write all those files?

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#3396]
**Description**  
The isis3VarInit.py script now writes six files (for three shells) into the conda environment, only two of which are actually needed by any one shell.  Is this really needed or best practice?

This could get out of control very quickly, surely this isn't the best approach?  Other packages only seem to include a bash shell script that sets the environment variables for the enclosing environment.  Do they know something we don't?

If there is no way to get around this with just one shell script, could we just write the activate and deactivate scripts in pure Python (something every conda install is guaranteed to have, regardless of user shell choice)?

**Comment by jessemapel** [comment]
I believe Python is unable to "export" environment variables outside of a script. So, I don't think we can use just a Python script. We could have an option on isis3VarInit.py to only write the script for the shell it is called from.

**Comment by rbeyer** [comment]
Seems like [os.putenv](https://docs.python.org/3.6/library/os.html#os.putenv) puts the environment variables into the actual environment.  There is a note about memory leaks on some systems, but surely that's been addressed?

**Comment by jessemapel** [comment]
That only puts the environment variables into the shell the script is running in. Once the script exits, they are not propagated up to the parent shell.

```
(isis3_dev) igswzawglt1183:build jmapel$ echo $ISIS3DATA
/usgs/cpkgs/isis3/data
(isis3_dev) igswzawglt1183:build jmapel$ python
Python 3.6.0 | packaged by conda-forge | (default, Feb 10 2017, 07:08:35) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.putenv('ISIS3DATA', 'hello')
>>> os.system('echo $ISIS3DATA')
hello
0
>>> exit()
(isis3_dev) igswzawglt1183:build jmapel$ echo $ISIS3DATA
/usgs/cpkgs/isis3/data 
```

**Comment by rbeyer** [comment]
Ah, a shame.  

So do other packages not provide the cornucopia of shell scripts because they are lazy, and just expect people to deal with it, or is there something else going on?

**Comment by jessemapel** [comment]
I'm not finding any cleaner solution to this. I am going to close this issue. If anyone finds a better solution please re-open and then cite this in a PR.
