### ISSUE TITLE
spiceinit fails on Voyager 2 images of Triton

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#3429]
**ISIS version(s) affected**: ISIS3.8.1

**Description**  
When running spiceinit on a "fresh" Voyager 2 image of Triton I receive the following error:

Error = “An unknown NAIF error has been encountered. The
short explanation provided by NAIF is
[SPICE(SPKINSUFFDATA)]. The Naif error is
[Insufficient ephemeris data has been loaded to
compute the state of 801 (TRITON) relative to 0
(SOLAR SYSTEM BARYCENTER) at the ephemeris epoch
1989 AUG 25 07:45:40.036.]”

**How to reproduce**  
Running ISIS3.8.1 on Astrovm4, download a fresh PDS Voyager 2 image of Triton. Perhaps (local)...

/pds_san/PDS_Archive/Voyager/vg_0011/triton/c1139xxx/c1139503.imq

From the command line run
voy2isis from=c1139503.imq to=c113503.cub
spiceinit from=c1139502.cub

A test cube can be found in /work/users/mbland/Triton-Voyager/spicetest-190823.

I've tested this on a few Triton images without success.

**Possible Solution**  
I'm assuming this is related to the change in kernels that happened in May of 2019. Spiceinit worked fine on these data back in March using ISIS3.6.0. 

**Additional context**  
This is related to my comment on astrodiscuss (https://astrodiscuss.usgs.gov/t/kernel-update-may-cause-internal-error/186). I decided to post an issue - if I can't use it, outside users can't either. This isn't an immediate block, but is hindering forward progress on a funded project.

**Comment by jessemapel** [comment]
I probably need to add all of the satellites to the list of targets to load the jupiter kernel for

**Comment by jessemapel** [comment]
Triton is a satellite of Neptune not Jupiter. I think this is really we need to add the satellite kernels for all of the major bodies and update the kernel db to load them for any satellite.

**Comment by jessemapel** [comment]
I've added the Saturn, Jupiter, and Neptune satellites for Voyager2 to the base SPK area, so this should now work:

```
spiceinit from=c1139503.cub
Group = Kernels
  NaifFrameCode             = -32101
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = $base/kernels/pck/pck00009.tpc
  TargetPosition            = ($base/kernels/spk/de430.bsp,
                               $base/kernels/spk/nep081.bsp)
  InstrumentPointing        = ($voyager2/kernels/ck/vg2_nep_version1_type2_is-
                               s_sedr.bc, $voyager2/kernels/fk/vg2_v02.tf)
  Instrument                = $voyager2/kernels/ik/vg2_issna_v02.ti
  SpacecraftClock           = $voyager2/kernels/sclk/vg200011.tsc
  InstrumentPosition        = $voyager2/kernels/spk//vgr2_nep081.bsp
  InstrumentAddendum        = $voyager2/kernels/iak/voyagerAddendum004.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
End_Group
```

**Comment by jessemapel** [comment]
I also checked voyager 1 and the Jupiter and Saturn satellites for it are covered too.
