### ISSUE TITLE
a bug in ProcessRubberSheet

### ISSUE THREAD

**Issue by yunfancui** [DOI-USGS/ISIS3#3435]
**ISIS version(s) affected**: 3.9.0

**Description**  
In some cases,the cam2map won't work

**How to reproduce**  
run cam2map with "defaultrange=map" and the range is smaller than the range from input cube

**Solution**  
modify ProcessRubberSheet to the previous version

**Comment by jlaura** [comment]
@yunfancui Thanks for the report. We are going to need more information than this. What exact command are you running? Using what data? What were the previous results that you were expecting to see?

**Comment by yunfancui** [comment]
I try to run an example of using Ames Stereo Pipeline with HiRISE data.The data is HiRISE images PSP_001513_1655. The command is "cam2map from=PSP_001513_1655_RED.mos_hijitreged.norm.cub to=PSP_001513_1655_RED.mos_hijitreged.norm.map.cub pixres=MPP resolution=0.27165816865522 defaultrange=MAP minlat=-14.78053510744 maxlat=-14.407359556607 minlon=175.44440406222 maxlon=175.55781944951"

**Comment by jessemapel** [comment]
@yunfancui What range are you expecting and what range are you getting in the output lvl2 cube? By explicitly setting the minimum/maximum latitude/longitude you are overriding any range computed from the input cube.

**Comment by yunfancui** [comment]
> @yunfancui What range are you expecting and what range are you getting in the output lvl2 cube? By explicitly setting the minimum/maximum latitude/longitude you are overriding any range computed from the input cube.

I can't get output cube,the progress bar is always 0%. By system monitor, it seems that the program stopped reading data after running for a few minutes.

**Comment by jlaura** [comment]
@scsides Is this closable with merge of #3497?

**Comment by scsides** [comment]
Yes, this is a duplicate issue fixed by #3497
