### ISSUE TITLE
libisis3.4.13.so: undefined symbol

### ISSUE THREAD

**Issue by deannerogers** [DOI-USGS/ISIS3#3436]
**ISIS version(s) affected**: 3.4.13.7091 

**Description**  
thm2isis fails. 

**How to reproduce**  
thm2isis from=/tmp/dv_4951/I41382002RDR.QUB to=/tmp/dv_4951/I41382002RDR.I3.cub
thm2isis: symbol lookup error: /data/isis3/isis/lib/libisis3.4.13.so: undefined symbol: _ZNK12QwtPlotCurve12updateLegendEP9QwtLegend
ERROR: thm2isis failed for file /tmp/dv_4951/I41382002RDR.QUB

**Possible Solution**  

**Additional context**  
We have not made any changes to our ISIS installation. Fails on any THEMIS IR image. Worked on this machine early last week, and then stopped working Friday. The command works fine on another machine running the same OS (Centos 7.6.1810).

**Comment by jlaura** [comment]
@deannerogers Are you able to upgrade to the current 3.8.1 release? We are not longer supporting 3.4.  Installation instructions for 3.8.1 are available [here](https://github.com/USGS-Astrogeology/ISIS3/#isis3-installation-with-conda). If not, let use know and we can go from there.

**Comment by jessemapel** [comment]
For reference here's the demangled symbol `QwtPlotCurve::updateLegend(QwtLegend*) const` it looks like a problem with your qwt installation. I expect updating to the Anaconda release will solve this.

**Comment by deannerogers** [comment]
Hello all,
Thank you so much for the advice. Jay, I was reluctant to upgrade because
of worry that davinci will not read ISIS-processed cubes with any later
versions.
I took a risk and deleted some of my more recent qwt-related library files,
to make the file list match another machine that was not affected by this
problem. That solved the issue and thankfully did not break anything else!
Thanks again for your quick responses.
