### ISSUE TITLE
Flipping Framelets in MARCI Data Breaks Several Things

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#3438]
**ISIS version(s) affected**: 3.8.x and earlier

**Description**  
After adding to Bug #2023, I did a lot of experimentation trying to get around the issue of calibration bugs dealing with FLIP=YES (or DataFlipped=1 in the cube labels).  For example, I was hoping that CAM2MAP knew enough to flip things, but that didn't work.  I then tried copying labels from unflipped to flipped, and then setting DataFlipped=1 or just preserving the copy of DataFlipped=0, but MARCICAL then erases most of the label information and you can't do anything with the cube.  That's why I decided to add a new bug report: There is a general issue with ISIS3 programs and dealing with flipping framelets, at least MARCI's.  So far, I have identified the following:

MARCIFLIP:  When using, it deletes the Kernels and Archive groups from the cube headers.

MARCICAL:  If data are flipped, regardless of whether the label says it's flipped, MARCICAL removes all "Group" header information, leaving just "Core".  That could be why I noted in Bug #2023 that QVIEW displays it as just a solid white image.

CAM2MAP and PIXEL2MAP:  If the data are flipped, regardless of whether the label says it's flipped, the map-projection programs have significant issues.  CAM2MAP utterly fails to delivery anything useful on even bands, but odd looks great.  PIXEL2MAP does a "decent" job on both, but there are still significant gaps.  See #3439 for details and screenshots, and next comment.

PHOTRIM:  Added per comment 2 below: If PHOTRIM is not run, on data that does not need to be flipped, the map projection works fine for odd and even bands.  If it is run, the output from PHOTRIM looks fine, but once map-projected, the same issues as in the first comment are present.

Those are the ones I've found, and I hope they have a root cause, which is why I posted them together rather than two separate bug reports.

**Comment by astrostu** [comment]
More detail on the map-projection issue.  Here is what the even-odd bands look like from CAM2MAP after the framelets have been flipped:
![Example](https://user-images.githubusercontent.com/50773625/64221257-6ad9a280-ce89-11e9-8545-062d3e8b5f9e.png)

And, here's what it looks like with PIXEL2MAP at 100% size:
![Screen Shot 2019-09-03 at 10 29 23 PM](https://user-images.githubusercontent.com/50773625/64225828-4f2ac800-ce9a-11e9-8a93-d1422cc8edaa.png)

So, the PIXEL2MAP actually does much better.  But, when mosaicking, there are gaps (that you can tell will be there from the even-odd bands).  Attached here is a straight-up mosaic and one that's had a low-pass 3x3 filter to fill in some of the missing data:
![Screen Shot 2019-09-03 at 10 32 02 PM](https://user-images.githubusercontent.com/50773625/64225916-ab8de780-ce9a-11e9-8ed6-5fdd35092a4a.png)

So @jessemapel appears to possibly be correct, that there might be a ProcessRubberSheet issue.  At least for the even-odd difference?  Though I'm not sure why that would affect just the even bands and not odd, for CAM2MAP.

**Comment by astrostu** [comment]
I'm not sure if this helps or hurts diagnosing this, or if it's a separate issue entirely (@jessemapel or @jlaura please feel free to split this out if it's a separate issue).  I tried a new image and let it process overnight, D09_030814_2689_MA_00N221W.  This image would not flip.  To my eye, the even-odd images when viewed needed to have the framelets flipped, but MARCI2ISIS with FLIP=AUTO or YES would not flip them, nor would MARCIFLIP.  At least, the header information said that DataFlipped still =0.

I went through my processing as before, without the flip apparently:  MARCI2ISIS, SPICEINIT, MARCICAL, PHOTRIM, CROPSPECIAL, CAM2MAP || PIXEL2MAP.  Got the same issue with map projection as before.

BUT, this time, I also ran CAM2MAP just after the MARCICAL.  And attached is the result (cropped to <-80° latitude) (R=band4=R, 2=G, 1=B).  Sure looks good.  But it took 2.5x longer to run (but if that's the price of a decent product, well, that's the price of a decent product!).

So now I'm wondering if there's and issue in PHOTRIM, as well, with the MARCI even bands?  The output (unprojected) from PHOTRIM for odd and even bands looks perfectly fine, but after map projection it's bad (see above).  I've added a note about this to the original comment above, but from this test, it looks as though there's a whole bunch of weird issues between several ISIS3 programs and MARCI data. ☹️
![Screen Shot 2019-09-05 at 11 13 30 AM](https://user-images.githubusercontent.com/50773625/64363998-37a12b80-cfcf-11e9-947f-3fe1b1da8aeb.png)

**Comment by jessemapel** [comment]
We've been looking a bit at MARCI the last few days and I have an idea about what could be causing this. When cam2map sets up the patch regions it takes into account the framelet size and if it's an even or odd image. For odd images it sets up patches on framelets 1, 3, 5, etc. and for even images it sets up patches on framelets 2, 4, 6, etc. This logic **does not** take into account flipping and that is causing the problem. When an image is flipped and it has an even number of framelets, the odd and even behavior needs to be flipped. Here's an example:

Assume an image with 4 framelets where each framelet is 4 lines.

### The unflipped case

The odd image has image data on lines 1-4 and 9-12 with nulls on 5-8 and 13-16.  Here's the patches cam2map makes for the odd image:
* lines 1-4
* lines 9-12
Each of these patches gets mapped down to the ground and the image data is mapped to the surface.

The even image has image data on lines 5-9 and 13-16 with nulls on 1-4 and 9-12. Here's the patches cam2map makes for the odd image:
* lines 5-9
* lines 13-16
Each of these patches gets mapped down to the ground and the image data is mapped to the surface.

### The Flipped Case

The odd image has image data on lines 5-9 and 13-16 with nulls on 1-4 and 9-12.  Here's the patches cam2map makes for the odd image:
* lines 1-4
* lines 9-12
Each of these patches gets mapped down to the ground and only the very edge of the image data is mapped to the surface. These patches contain mostly nulls.

The odd image has image data on lines 1-4 and 9-12 with nulls on 5-8 and 13-16. Here's the patches cam2map makes for the even image:
* lines 5-9
* lines 13-16
Each of these patches gets mapped down to the ground and only the very edge of the image data is mapped to the surface. These patches contain mostly nulls.

I'm going to test out a potential fix and see if this works better.

**Comment by jessemapel** [comment]
here's some ascii art I just made that helps explain this a bit better:

```
    //  Unflipped image with even number of framelets
    //
    // 1|########|   1|        |
    // 2|        |   2|########|
    // 3|########|   3|        |
    // 4|        |   4|########|
    //     odd           even
    //
    //  flipped image with even number of framelets
    //
    // 4|        |   4|########|
    // 3|########|   3|        |
    // 2|        |   2|########|
    // 1|########|   1|        |
    //     odd           even
    //
    //
    //  unflipped image with odd number of framelets
    //
    // 1|########|   1|        |
    // 2|        |   2|########|
    // 3|########|   3|        |
    // 4|        |   4|########|
    // 5|########|   5|        |
    //     odd           even
    //
    //  flipped image with odd number of framelets
    //
    // 5|########|   5|        |
    // 4|        |   4|########|
    // 3|########|   3|        |
    // 2|        |   2|########|
    // 1|########|   1|        |
    //     odd           even
```

**Comment by astrostu** [comment]
I'll note that this issue appears to have been fixed so long as marci2isis has the flag flip=no.  Even if stuff should be flipped, if you set "flip=no," then everything else appears to work.  As of ISIS v. 3.9.1.
