### ISSUE TITLE
CAM2MAP Issues with Even MARCI Bands

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#3439]
**ISIS version(s) affected**: 3.8.x (and earlier?)

**Description**  
I'm having issues with even bands from MARCI in map projection.  Despite the unprojected images looking fine, when map-projected the even bands are missing a lot of data.  This means when mosaicking the two after map-projection, data gaps are present.  I've copied my workflow below (requires GNU parallel), and I did try this the bare minimum, too (just MARCI2ISIS and SPICEINIT) and got the same issues.  This happened with the two completely different from different PDS release MARCI cubes I tried.

![Unprojected](https://user-images.githubusercontent.com/50773625/64221327-af653e00-ce89-11e9-9523-fad347ac9caa.png)
![Example](https://user-images.githubusercontent.com/50773625/64221257-6ad9a280-ce89-11e9-8545-062d3e8b5f9e.png)

```
parallel --no-notice marci2isis from='{}' to='{.}.cub' flip=no ::: *.IMG
parallel --no-notice spiceinit from='{}' cknadir=true ::: *.cub
parallel --no-notice marcical from='{}' to='{.}.cal.cub' ::: *.cub
parallel --no-notice marciflip from='{}' to='{.}.flip.cub' ::: *.cal.cub
parallel --no-notice copylabel source='{}' from='{.}.flip.cub' instrument=false bandbin=false kernels=true groups=archive blobs=Table:InstrumentPointing,Table:InstrumentPosition,Table:BodyRotation,Table:SunPosition ::: *even.cal.cub
parallel --no-notice copylabel source='{}' from='{.}.flip.cub' instrument=false bandbin=false kernels=true groups=archive blobs=Table:InstrumentPointing,Table:InstrumentPosition,Table:BodyRotation,Table:SunPosition ::: *odd.cal.cub
parallel --no-notice editlab from='{}' options=modkey grpname=Instrument keyword=DataFlipped value=1 ::: *flip.cub
parallel --no-notice explode from='{}' to='{.}' ::: *.cal.flip.cub
parallel --no-notice photrim from='{}' to='{.}.photrim.cub' maxphase=90 maxemission=90 maxincidence=90 ::: *band*.cub
parallel --no-notice cropspecial from='{}' to='{.}.crop.cub' null=true ::: *.photrim.cub
parallel --no-notice cam2map from='{}' to='{.}.l2.cub' map=AA_equatorial_48ppd.map pixres=map defaultrange=minimize ::: *_MA_*.crop.cub

```

**Comment by astrostu** [comment]
P.S. My map file:
```
Group = Mapping
  ProjectionName     = Equirectangular
  CenterLongitude    = 0.0
  CenterLatitude     = 0.0
  TargetName         = Mars
  EquatorialRadius   = 3396190.0 <meters>
  PolarRadius        = 3396190.0 <meters>
  LatitudeType       = Planetocentric
  LongitudeDirection = PositiveEast
  LongitudeDomain    = 180
  MinimumLatitude    = -90.0
  MaximumLatitude    = +90.0
  MinimumLongitude   = -180.0
  MaximumLongitude   = +180.0
  Scale              = 48.0 <pixels/degree> #1.235 kmpp
End_Group
End
```

**Comment by jessemapel** [comment]
@astrostu Can you try pixel2map on one of the even images? It'll take a while to run because it does pixel by pixel projection, but I'm curious if this is a problem with ProcessRubberSheet or the sensor model itself.

**Comment by astrostu** [comment]
@jessemapel On ... a map projected, or pre-map-projected?

**Comment by astrostu** [comment]
Ah, I just read the docs, on the pre-map-projected.

**Comment by jessemapel** [comment]
Yeah, pixel2map does a very slow map projection process and is largely used for spectrometers with big pixels and long exposure durations, but it uses very different logic from cam2map.

**Comment by astrostu** [comment]
That was worse for both even and odd, attached (@25% zoom).  (This time I cropped to just ±10° latitude to speed things up.)  That said, stay tuned, I may have been mistaken in my tracking of when this error happens.  I am re-running from the minimum processing step (MARCI2ISIS, SPICEINIT) and it looks like it's working, or at least not leaving unexpected gaps.  I'm going to trace this through each step and see where it breaks.
![Screen Shot 2019-09-03 at 9 09 48 PM](https://user-images.githubusercontent.com/50773625/64222992-5e584880-ce8f-11e9-8d45-7e6e61724b3d.png)

**Comment by astrostu** [comment]
Sigh. Okay, I was mistaken and didn't track things well enough.  Re-running, this is another manifestation of flipping framelets.  Until I get to that step, map-projecting looks as expected.  After it, the map projection is as I posted.  I'll go ahead and close this and edit my issue #3438.
