### ISSUE TITLE
Wiki - incorrect link for MAP-a-Planet

### ISSUE THREAD

**Issue by thareUSGS** [DOI-USGS/ISIS3#3440]
**Description**
The external address mapaplanet.org has been retired. 

**Suggested Edit**
The Map-a-Planet link on this page needs to updated to: https://astrogeology.usgs.gov/tools/map-a-planet-2

**Comment by jlaura** [comment]
One instance of this is available at https://github.com/USGS-Astrogeology/ISIS3/wiki/Introduction_to_ISIS

Do we have more?

**Comment by thareUSGS** [comment]
Yes - the original link to Wiki page was missed in the copy. That is the only instance I could fine (using a repository search).

**Comment by robotprogrammer22** [comment]
I fixed the link on the Introduction_to_ISIS page. I searched the markdown files and couldn't find any other locations that contained a link to Map-a-Planet.

**Comment by jlaura** [comment]
@thareUSGS This looks good from here. I am going to close. If we have another instance, we should reopen.
