### ISSUE TITLE
Wiki - Support Center Links

### ISSUE THREAD

**Issue by robotprogrammer22** [DOI-USGS/ISIS3#3443]
@jlaura @thareUSGS 

I was looking through the wiki and noticed that the link to the ISIS Support Center, https://isis.astrogeology.usgs.gov/projects/isis, returns a 404 error. I was wondering if there is another location I should change the link to?

**Comment by jessemapel** [comment]
I would either link to astrodiscuss or the issues page

**Comment by robotprogrammer22** [comment]
Okay, I updated the links to the issues page.
