### ISSUE TITLE
cisscal - generates output upon failure

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#3446]
**ISIS version(s) affected**: isis3.9.0-RC1 as well as 3.8.0, so not introduced via recent update

**Description**  
cisscal fails to calibrate the input images (tons of error messages) but creates an output file full of NULLs.  

**How to reproduce**  
cisscal from=N1605851822_1.cub to=N1605851822_1.cal.cub

Input/Output available here: /work/users/lweller/Isis3Tests/Cisscal/

Errors: 
>   Group = Error
>     Program = cisscal
>     Code    = 1
>     Message = "Unable to calibrate image. Dark current calculations failed"
>     File    = main.cpp
>     Line    = 208
>   End_Group
> 
>   Group = Error
>     Program = cisscal
>     Class   = "PROGRAMMER ERROR"
>     Code    = 3
>     Message = "Evaluate() - Unable to evaluate the function at the given
>                vector of points"
>     File    = NumericalApproximation.cpp
>     Line    = 939
>   End_Group
> 
>   Group = Error
>     Program = cisscal
>     Class   = "PROGRAMMER ERROR"
>     Code    = 3
>     Message = "EvaluateCubicNeighborhood() - Unable to evaluate the function
>                at the given vector of points using cubic neighborhood
>                interpolation"
>     File    = NumericalApproximation.cpp
>     Line    = 3016
>   End_Group
> 
>   Group = Error
>     Program = cisscal
>     Class   = "PROGRAMMER ERROR"
>     Code    = 3
>     Message = "Evaluate() - Invalid argument. Value entered, a =
>                1200.6993359375, is outside of domain = [0.0, 1200.0]"
>     File    = NumericalApproximation.cpp
>     Line    = 2831
>   End_Group

**Possible Solution**  
Don't create output if application fails. 

**Additional context**  
I was processing 19k Titan images and found images of this type because cisscal does generate a return value indicating failure, so I could capture the failed images into a list, but there was a mismatch between failures and the number of *.cal.cub files generated.  Low priority because there is a way to identify the failures despite the output image creation.

**Comment by lwellerastro** [comment]
I'd add some labels, but I completely forget how to do so!  Or the mechanism to do so is not exposed to me...what am I missing?

**Comment by blandoplanet** [comment]
I also seem unable to add labels all of a sudden. Can we also add the Products label?

**Comment by jlaura** [comment]
@blandoplanet and @lwellerastro I bet the label thing is when I was pushing buttons on collaborators vs. folks with merge rights. I'll take a look to see what's up with labels.
