### ISSUE TITLE
Photomet topo mode allows user to select DEM source

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3451]
**ISIS version(s) affected**: x.y.z
Was an issue in 2017.  I am not a technical user and can no longer run ISIS3 to verify it is still an issue.

**Description**  

When setting normname=topo, the algorithm must be applied to an ellipsoid shape model so a DEM can be calculated.  However, photomet allows the user to select anglesource=DEM.  

**How to reproduce**  

Open photomet gui.
Select normname=topo
Select anglesource=DEM
Observe that no error/warning given to the user.  
Can do the same from the command line if you prefer.  

**Possible Solution**  

Remove DEM as a valid value for the anglesource parameter when normname=topo.  
At least throw a warning to the user that the selected parameters are mutually incompatible and one of the who needs to be change.  

**Additional context**

**Comment by blandoplanet** [comment]
This seems to be true in ISIS3.9.0.

Test data in /work/users/mbland/Europa-data/Androgeos/
Lambert correction applied to cube 8600r_caltr.cub with a topographic normalization with anglesource=ELLIPSE (8600r_caltr_LL_topo.cub) and anglesource=DEM (8600r_caltr_LL_topo_DEM.cub). Results are idenitcal and no errors or warning are given. HOWEVER, the image does not specify a DEM in the image label so its probably just defaulting to the ellipse anyway.  

If it's true that anglesource=DEM and the topographic normalization (normname=topo) are incompatible we should at least update the docs to make that clear. I can't find anywhere in the docs that says these shouldn't be used together.
