### ISSUE TITLE
spiceinit web service shape models

### ISSUE THREAD

**Issue by rwatkins15** [DOI-USGS/ISIS3#3453]
**Description**  
I'd like to request a feature that allows the spiceinit web service to be used when the user specifies their own shape model (i.e., one not hosted by the web service). For example, I frequently process LROC NAC images using NAC DTMs as shape models, but right now the web service does not support this feature.

**Comment by jessemapel** [comment]
See https://astrodiscuss.usgs.gov/t/processing-nac-images-with-nac-dtm-and-spiceinit-web/274 for more context

**Comment by jessemapel** [comment]
I'm actually closing this as a duplicate of #1986
