### ISSUE TITLE
CASSINI VIMS SPICEINIT error

### ISSUE THREAD

**Issue by sriramsaran** [DOI-USGS/ISIS3#3457]
**ISIS version(s) affected**: 3.6.1

**Description**  
<Howdy, I am trying to process some CASSINI VIMS data acquired for the Moon during the mission's earth-bound phase. The ingestion (vims2isis) step was successful, but _spiceinit_ throws up errors related to instrument position kernels. I tried using different kernel options ("ckpredicted" and "spkpredicted"), and modified the Target Name in the data from “UNK” to “Moon” to get a proper shape model, and still  _spiceinit_ was not successful. The error message was: 

Group = Kernels
    NaifFrameCode             = -82371
    LeapSecond                = $base/kernels/lsk/naif0012.tls
    TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
$cassini/kernels/pck/cpck15Dec2017.tpc)
    TargetPosition            = $base/kernels/spk/de405.bsp
    InstrumentPointing        =  $cassini/kernels/ck/99228_99235ra.bc, 
$cassini/kernels/fk/cas_v40_usgs.tf)
    Instrument                = Null
    SpacecraftClock           = $cassini/kernels/sclk/cas00172.tsc
    InstrumentPosition        = Null
    InstrumentAddendum        =  $cassini/kernels/iak/vimsAddendum03.ti
    ShapeModel                =  $base/dems/ldem_128ppd_Mar2011_clon180_radius_pad.cub
    InstrumentPositionQuality = Unknown
    InstrumentPointingQuality = Reconstructed
    CameraVersion             = 1
    Error                     = "No instrument position available"
  End_Group

  Group = Error
    Program = spiceinit
    Code    = 1
    Message = "Unable to initialize camera model"
    File    = spiceinit.cpp
    Line    = 241
  End_Group
End_Object

Furthermore, I tried processing them using Instrument position spk kernel named **180628RU_SCPSE_09317_09339.bsp** (as seen in various threads in ISIS support forum), but it resulted in there a NAIF error  as below: 

Group = Kernels
    NaifFrameCode             = -82371
    LeapSecond                = $base/kernels/lsk/naif0012.tls
    TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
$cassini/kernels/pck/cpck15Dec2017.tpc)
    TargetPosition            = $base/kernels/spk/de405.bsp
    InstrumentPointing        = ($cassini/kernels/ck/99228_99235ra.bc,
                           $cassini/kernels/fk/cas_v40_usgs.tf)
    Instrument                = Null
    SpacecraftClock           = $cassini/kernels/sclk/cas00172.tsc
    InstrumentPosition        = /home/anaconda3/envs/isis3/data/cassini/kernels/spk/180628RU_SCPSE_09317_09339.bsp
    InstrumentAddendum        = $cassini/kernels/iak/vimsAddendum03.ti
    ShapeModel                = $base/dems/ldem_128ppd_Mar2011_clon180_radius_pad.cub
    InstrumentPositionQuality = Unknown
    InstrumentPointingQuality = Reconstructed
    CameraVersion             = 1
    Error                     = "An unknown NAIF error has been encountered. The short explanation provided by NAIF is [SPICE(SPKINSUFFDATA)]. The Naif error is [Insufficient ephemeris data has been loaded to compute the position of -82 (CASSINI) relative to 0 (SOLAR SYSTEM BARYCENTER) at the ephemeris epoch 1999 AUG 18 02:06:13.513.]"
  End_Group

  Group = Error
    Program = spiceinit
    Code    = 1
    Message = "Unable to initialize camera model"
    File    = spiceinit.cpp
    Line    = 241
  End_Group
End_Object

These are the data files I am trying to process: 
v1313633519_1.qub
v1313633580_1.qub
v1313633642_1.qub
v1313633704_1.qub
v1313633766_1.qub
v1313633828_1.qub
v1313633891_1.qub
v1313633953_1.qub
v1313634015_1.qub
v1313634077_1.qub
v1313634139_1.qub

How to resolve this issue?

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by jessemapel** [comment]
The ISIS data area is not setup for that part of the mission. The fix for this is likely just staging those kernels.

**Comment by sriramsaran** [comment]
Many thanks !  I was trying to process the files in the same fashion as described in this supplementary information of Clark 2009 (attached)
[Clark.SOM.pdf](https://github.com/USGS-Astrogeology/ISIS3/files/3629548/Clark.SOM.pdf)

**Comment by jlaura** [comment]
@sriramsaran Thanks for the response. Is this good to close?

**Comment by sriramsaran** [comment]
@jlaura Is there anyway to get those specific kernels? Are they available at NAIF ?

**Comment by jessemapel** [comment]
@sriramsaran It looks like the paper you attached processed the data without using the sensor model and hand registered them. You do not need SPICE data to do this.

If you want to try a different way to process them, you can find all of the cassini kernels on [NAIF's website](https://naif.jpl.nasa.gov/pub/naif/CASSINI/kernels/).

**Comment by jlaura** [comment]
@sriramsaran I am going to close this. Please reopen if you are seeing a bug related to processing VIMS data for kernels that are staged or if you are unsure if the kernels are/should be staged. 

It looks like you have a viable path forward and that the code is not the issue. Thanks!
