### ISSUE TITLE
Problem with cam2map when processing CTX data

### ISSUE THREAD

**Issue by 0dvaz0** [DOI-USGS/ISIS3#3466]
**ISIS version(s) affected**: 3.9.0 (running on Xubuntu 18.04 )

**Description**  
Hello,

I have recently upgrade ISIS and I started to have a problem when processing CTX data.
Cam2map does not run successfully when I define ground range latitude/longitude.
It seems to be running but the progress bar remains at 0% (even during a overnight run!).
There is no error messages and the cube that is created is all zeros.

However, if I run cam2map using all defaults, it returns a valid output.

Any idea why is that happening?
Am I doing something wrong?

Cheers
David

**How to reproduce**  

wget -c https://pds-imaging.jpl.nasa.gov/data/mro/mars_reconnaissance_orbiter/ctx/mrox_2174/data/F03_037038_1742_XI_05S227W.IMG

mroctx2isis from=F03_037038_1742_XI_05S227W.IMG to=F03_037038_1742_XI_05S227W.cub

spiceinit from=F03_037038_1742_XI_05S227W.cub

ctxcal from=F03_037038_1742_XI_05S227W.cub to=F03_037038_1742_XI_05S227W.lev1.cub

ctxevenodd from=F03_037038_1742_XI_05S227W.lev1.cub to=F03_037038_1742_XI_05S227W.lev1eo.cub

cam2map from=F03_037038_1742_XI_05S227W.lev1eo.cub to=F03_037038_1742_XI_05S227W.map.cub pixres=MPP resolution=5.4449133592799 defaultrange=MAP minlat=-5.0238176134696 maxlat=-3.1995325374047 minlon=131.92029413774 maxlon=132.75709469592

**Possible Solution**  

**Additional context**

**Comment by lwellerastro** [comment]
I can reproduce this.  Data under /work/users/lweller/CTX/git_3466/.

Running in default mode, the app takes about 13 minutes or so to run:

> cam2map from=F03_037038_1742_XI_05S227W.cal.eo.cub to=F03_037038_1742_XI_05S227W.lev2Def.cub

When getting specific, either as the OP has in their command or whittling the res, lat and lon to just 4 decimal places, cam2map doesn't budge.  After 10 minutes or so of 0% progress I killed it.

I ran similar steps against Galileo SSI data I am working with and encountered no problems with getting very specific about lat/lon range, so it appears there is something going on with this particular CTX image, though it is not clear why.  It looks pretty standard.

FYI - this is eerily similar to [#3435](https://github.com/USGS-Astrogeology/ISIS3/issues/3435)

**Comment by jessemapel** [comment]
@scsides Could this be related to the cam2map changes requested by LROC?

**Comment by scsides** [comment]
I'm looking into this now

**Comment by scsides** [comment]
Current tests are showing this behaviour when the lat/lon range only covers a portion of the input image.
