### ISSUE TITLE
Broken links in Tutorial on ISIS Wiki

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3473]
**Description**  
There are some broken links on the migrated ISIS Tutorial on the ISIS github wiki. 

**How to reproduce**  
Clicking on several links at: https://github.com/USGS-Astrogeology/ISIS3/wiki leads me to for example: https://usgs-astrogeology.github.io/ISIS3/gh-pages/Core_Base_and_Multiplier.html, https://usgs-astrogeology.github.io/ISIS3/gh-pages/Special_Pixels.html, which 404. In addition to the two broken links listed, the others should be checked, as there were several I came across this morning.

**Comment by lwellerastro** [comment]
Looks like some were recently documented via [#3441 ](https://github.com/USGS-Astrogeology/ISIS3/issues/3441)

**Comment by jlaura** [comment]
@lwellerastro Thanks! I am going to close this issue in favor of the original post.
