### ISSUE TITLE
"lronaccal" produce level 1 data of zero values

### ISSUE THREAD

**Issue by QIAN-Yuqi** [DOI-USGS/ISIS3#3474]
**ISIS version(s) affected**: 3.8.0 in WSL

**Description**  
Hi,
I find a really weird issue when I use "lronaccal" command in calculating IOF (after "lronac2isis" and "spiceinit"). The produced cub seems not correct. Every pixel is zero. I have checked tens of LRO NAC EDR images, and this issue happens every time. However, it seems everything is fine if I choose "radiance" option.

For example if I run "**lronaccal from=M107206533LE.lev0.cub to=M107206533LE.lev1_IOF.cub**". The values of all pixels of the produced level 1 cub are zero. However if I run "**lronaccal from=M107206533LE.lev0.cub to=M107206533LE.lev1_radiance.cub radiometrictype=radiance**", it seems the produced cub is fine and correct. 

Check this link of the screenshot and the data used [lev0.data after lronac2isis and spicenint](
https://1drv.ms/u/s!ApYmljTONvbCiJgkRfpmibxafsYeDQ?e=CDf2vT)

**How to reproduce**  
Run "**lronaccal from=example.lev0.cub to=example.lev1_IOF.cub**"

**Comment by jessemapel** [comment]
Hi @YuqiiQian,

Do you have the LRO data area local? You can run spiceinit without the LRO kernels. via the web service, but the calibration programs have to load local kernels to determine things like the distance to the sun.

You can check by seeing what is in `$ISIS3DATA/lro/kernels/spk` it should have a couple hundred files in it. Here's what I get:

```
[jmapel@astrovm4 ~]$ ls $ISIS3DATA/lro/kernels/spk/ | wc -l
222
```

**Comment by jessemapel** [comment]
This chunk of the [code](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/lro/apps/lronaccal/main.cpp#L198) loads the Moon position kernels if your calibrate to IoF. You can check your local data area for the listed kernels.

If you calibrate to radiance then it doesn't need the distance to the Sun which explains why that works.

**Comment by QIAN-Yuqi** [comment]
Thanks so much @jessemapel . I didn't realized that I need local kernels to calculate IOF. So I still need to download kernels to local machine even if I use ISIS3 SPICE web service if I want to calculate IOF? However, if I just want to calculate radiance then ISIS3 SPICE web service is enough.

For example, the code below doesn't work well because I don't have local kernels but works well for radiance (Yes, I retrieved map projected radiance map through web service):
```
lronac2isis from=EXAMPLE.IMG to=EXAMPLE.lev0.cub
spiceinit from=EXAMPLE.lev0.cub web=yes 
lronaccal from=EXAMPLE.lev0.cub to=EXAMPLE.lev1_cal.cub #or radiometrictype=radiance
lronacecho from=EXAMPLE.lev1_cal.cub to=EXAMPLE.lev1_echo.cub
cam2map from=EXAMPLE.lev1_echo.cub to=EXAMPLE.lev2.cub map=mapinfo.txt pixres=map
```

Thanks a lot!
Yuqi

**Comment by jessemapel** [comment]
> So I still need to download kernels to local machine even if I use ISIS3 SPICE web service if I want to calculate IOF? However, if I just want to calculate radiance then ISIS3 SPICE web service is enough.

Yes this is correct. Modifying the calibration programs to not require local kernels is something that has been talked about several time. See #1790 for example.
