### ISSUE TITLE
Backing out the ALE integration merge

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3476]
#3464 merged the new code that integrates [ALE](https://github.com/USGS-Astrogeology/ale) into spiceinit.

When this was merged, Jenkins was down and since has come back up. We have several test and build failures on Jenkins right now and it is not clear which are caused by the ALE integration and which are caused by changes in things like the docker image Jenkins slaves use.

I've spent about a day working on this and I think there's too much that needs to be addressed for this to be handled right now. So, I'm proposing we back out ALE until the ASC gets back on the project and these problems can be addressed.

**Comment by krlberry** [comment]
:+1: on backing out the changes to make it possible to see what is failing without the ALE changes. Do we know when we'll be able to get back on the project?

**Comment by jessemapel** [comment]
@kberryUSGS We have a software scheduling meeting tomorrow. Either way, I'd like to have at least 1 person work on this starting either next week or after the products work.

**Comment by jlaura** [comment]
:+1: Backing out and potentially addressing during the products sprint sounds like a fine idea here. Can we accomplish backing the PR out this week so that we start the products sprint with (potentially) passing builds?

**Comment by jessemapel** [comment]
I'm going to leave this up for the day, if there are no objection by tomorrow morning I'll back ALE out.

**Comment by jessemapel** [comment]
changes have been backed out and Jenkins builds are passing again.
