### ISSUE TITLE
ISIS3.9.0 release still indicates beta

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#3479]
**ISIS version(s) affected**: 3.9.0

**Description**  
The version file for 3.9.0 (release) still indicates beta.
https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/version#L3

This has caused some very justified confusion for our users: https://astrodiscuss.usgs.gov/t/getting-the-stable-version-of-isis-3-9-0/316

**How to reproduce**  

**Possible Solution**  
We need to update the version file __and__ the release procedure to make sure we are getting the version file updated. I wonder if this is something that we can set using CMake so that we are not having duplicative information?

**Additional context**

**Comment by jlaura** [comment]
I see that the docs reflect needing to do the update: https://github.com/USGS-Astrogeology/ISIS3/wiki/Public-Release-Process#step-2-set-up-the-local-and-remote-repositories

I suggest that this will be fixed when 3.9.1 is released, but still want to have this issue in to highlight the step.

**Comment by jessemapel** [comment]
This was my fault. I missed that when I went through the files to update. It is possible to make cmake render a file using cmake variables. So, we may be able to make cmake generate the version file.

**Comment by jessemapel** [comment]
Note this is still incorrect in 3.9.0, but should be fixed in future releases.
