### ISSUE TITLE
Kaguya TC/LISM distortion model doesn't account for the boresight

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3481]
**ISIS version(s) affected**: 3.7.0+ (seems like since TC support was added)

**Description**  

The Kaguya LISM distortion equations include an offset for the boresight. From the IK:

```
   Distortion coefficients information:
     INS<INSTID>_DISTORTION_COEF_X  = ( a0, a1, a2, a3)
     INS<INSTID>_DISTORTION_COEF_Y  = ( b0, b1, b2, b3),

   Distance r from the center:
     r = - (n - INS<INSTID>_CENTER) * INS<INSTID>_PIXEL_SIZE.

   Line-of-sight vector v is calculated as
     v[X] = INS<INSTID>BORESIGHT[X]
            +a0 +a1*r +a2*r^2 +a3*r^3 ,
     v[Y] = INS<INSTID>BORESIGHT[Y]
            +r +a0 +a1*r +a2*r^2 +a3*r^3 ,
     v[Z] = INS<INSTID>BORESIGHT[Z] .
```

The KaguyaTcCameraDistortionMap class does not include the boresight offsets in its calculations:

```
    // Apply distortion correction
    double dr_x = p_odkx[0] + p_odkx[1] * r + p_odkx[2] * r2 + p_odkx[3] * r3;
    double dr_y = p_odky[0] + p_odky[1] * r + p_odky[2] * r2 + p_odky[3] * r3;

    p_undistortedFocalPlaneX = x + dr_x; 
    p_undistortedFocalPlaneY = y + dr_y;
```

**How to reproduce**  

You can run camtest on a Kaguya TC image to see the distorted and undistorted focal plane coordinates and they do no appear to account for the offset.

**Possible Solution**  

We should add the boresight offsets to the distortion map.

**Comment by blandoplanet** [comment]
Should this be flagged as a "bug"? It seems like something that might be addressed in a future Product support sprint.

**Comment by jessemapel** [comment]
@blandoplanet I knew I forgot something!

**Comment by lwellerastro** [comment]
Should there be consideration in addressing this sooner than later due to the fact that there is a project dependent upon the KaguyaTC model that needs to have work completed in early 2020 (January/February time-frame)?

**Comment by jlaura** [comment]
I believe this is a rather quick fix, so having this as a candidate for next week might make sense?

**Comment by blandoplanet** [comment]
I agree with that. Given that we have a project using TC it is higher priority than some of the other tasks lower down on the list.

**Comment by lwellerastro** [comment]
I agree as well.  I guess we need to figure out where on the list it goes.

**Comment by jessemapel** [comment]
This is very small fix. I've already got a PR in USGSCSM for this, we just don't have time to do ISIS work under the current USGSCSM sprint.

**Comment by jessemapel** [comment]
Here's the USGSCSM fix https://github.com/USGS-Astrogeology/usgscsm/pull/246
