### ISSUE TITLE
Pluto and Charon not in pdsImageProjection.trn

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#350]
This isn't about the code in this repo, but about the contents of one of the files in $ISIS3DATA, specifically: $ISIS3DATA/base/translations/pdsImageProjection.trn

In the 'TargetName' group, neither Pluto nor Charon appear.  Its been three years since New Horizons flew by, maybe time for those to be in there.

**Comment by jessemapel** [comment]
Because this is not related to cmake support, I'm going to move this over to a redmine ticket so it can get prioritized. We're currently only using GitHub issues for build issues that external developers are encountering.

**Comment by jessemapel** [comment]
I've created a [redmine ticket](https://isis.astrogeology.usgs.gov/fixit/issues/5463) and all discussion of this should be moved over there.
