### ISSUE TITLE
BulletShapeModel unitTest uses local data

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3511]
BUlletShapeModel unitTest is failing on external Jenkins because it uses paths specific to the ASC network.

**Comment by ladoramkershner** [comment]
I updated /usgs/cpkgs/isis3/data/hayabusa/testData/st_2391934788_v.cub so that the Group=Kernels Keyword=ShapeModel is set using $hayabusa instead of an absolute path rooted in usgs/cpkgs
