### ISSUE TITLE
EmbreeShapeModel unitTest uses local data

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3512]
The EmbreeShapeModel unitTest uses local data at the ASC. This causes it to fail on the external Jenkins tests.

**Comment by ladoramkershner** [comment]
I updated /usgs/cpkgs/isis3/data/hayabusa/testData/st_2391934788_v.cub so that the Group=Kernels Keyword=ShapeModel is set using $hayabusa instead of an absolute path rooted in usgs/cpkgs
