### ISSUE TITLE
EmbreeTargetManager unitTest uses local data

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3513]
The EmbreeTargetManager unitTest uses local test data at the ASC. This causes it to fail on the external Jenkins tests.

**Comment by ladoramkershner** [comment]
I (and by 'I' I mean @acpaquette) am fairly confident that this failure is caused by the failure of the preceding tests (issue #3511 and #3512). I will close this for now, but it can be reopened if it continues to fail.

**Comment by ladoramkershner** [comment]
I was wrong. PR #3545
