### ISSUE TITLE
KaguyaTcCamera unitTest uses local data

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3516]
The KaguyaTcCamera unitTest uses local data paths at the ASC. This causes it to fail on the external Jenkins tests.

**Comment by ladoramkershner** [comment]
Re-spiceinited the two cubes used in the kaguya unit tests, so that they were using the new kaguya camera model (added distortion model, PR #3498)
/usgs/cpkgs/isis3/data/kaguya/testData/TC2W2B0_01_02735N583E3115.cub
/usgs/cpkgs/isis3/data/kaguya/testData/TC1S2B0_01_06691S820E0465.cub
