### ISSUE TITLE
makeflat app tests uses local data

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3518]
The makeflat app tests uses local data paths as the ASC. This causes the following tests to fail on the external jenkins:

* framing
* linescan
* pushframe

**Comment by Kelvinrr** [comment]
input file lists had hardcoded paths in them. All tests passing locally with updated paths, waiting for jenkins.

**Comment by jessemapel** [comment]
Looks like test data needs to be propagated still.

**Comment by Kelvinrr** [comment]
App is expanding the path and writing it into output, I'll put in a PR to patch it.
