### ISSUE TITLE
sumspice dawn app test uses local data

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3521]
sumspice dawn app test uses local data paths at the ASC. This causes it to fail in external Jenkins tests.

**Comment by AustinSanders** [comment]
I checked in new data, but I'm not sure if it will pass due to how the data is accessed by Jenkins.

**Comment by jessemapel** [comment]
Dawn test is still failing. Re-opening until test data gets pushed to the DMZ and tests pass on Jenkins

**Comment by jessemapel** [comment]
Fixed by this morning's rsync.
