### ISSUE TITLE
thmbasemap1 app tests are failing

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3526]
This is likely due to local data paths, but it is not clear. This failure is occurring external jenkins tests.

**Comment by jessemapel** [comment]
The following tests are failing:

* dayonly
* nightonly

**Comment by Kelvinrr** [comment]
input/prog.lis had hardcoded values for both tests.

**Comment by jessemapel** [comment]
Still failing. Looks like test data didn't make it over to the dmz?

**Comment by Kelvinrr** [comment]
As of https://astroservices.usgs.gov/jenkins/job/ISIS-Builds/job/CentOS/100/execution/node/39/log/ they seem to be passing.

**Comment by jessemapel** [comment]
Yep, looks like after this morning's rsyncs they are passing agin
