### ISSUE TITLE
ocam2isis app tests are failing

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3527]
The ocam2isis app tests are failing in external jenkins tests. This is likely due to path issues. Unlike other tests, this could be local paths at the ASC or the special paths for the local test data.

**Comment by jessemapel** [comment]
The following tests are failing:

* mapcam
* polycam
* samcam

**Comment by scsides** [comment]
ocams2isis is failing on the Jenkins because the local data directory is not available to the build. IT has been notified.

**Comment by scsides** [comment]
Copying the datalocal area to the Jenkins area fixed the issue
