### ISSUE TITLE
osirisrex module tests are failing

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3528]
osirisrex module tests are failing in external jenkins tests. Similar to #3527, this is likely due to data paths. The osirisrex test data is in a separate directory and the paths are likely not setup correctly for outside of the ASC network.

**Comment by jessemapel** [comment]
The following module tests are failing:

* mapcam
* polycam
* samcam

**Comment by Kelvinrr** [comment]
`$ISIS3DATA/../datalocal` needs to be added to Jenkin's mount.

**Comment by jessemapel** [comment]
local data has been added and this is now passing
