### ISSUE TITLE
Cassis module tests are failing

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3529]
This is likely due to data path issues. The following tests are failing in external jenkins tests:

* coloredMosaic
* mapProjectedReingested
* projSIngleStichedFrame
* singleColorMosaicReingest
* singleFrameletProjection
* stitchUnstitch
* unctrolledSingleColorMosaic

**Comment by jessemapel** [comment]
@kberryUSGS Do you know if the CaSSIS test data is proprietary?

**Comment by Kelvinrr** [comment]
Seems to have missing Kernels? 

```
1547: **ERROR** No existing files found with a numerial version matching [kernels.????.db] in [/isisData/data/tgo/kernels/ck].
```

maybe whatever copy of ISIS3DATA is on the jenkins machine is missing kernels?

**Comment by jessemapel** [comment]
That's really strange. CaSSIS uses a ck config and its kernel database files are called `cassis_kernels.####.db` and `tgo_kernels.####.db`.

**Comment by krlberry** [comment]
@jessemapel I don't think so. I think I've previously asked Laz about it, but might need to double-check.

**Comment by Kelvinrr** [comment]
Kernel config files exist too, not sure why it's not being caught. Test pass locally with ISIS3DATA set to Jenkin's ISIS3DATA

**Comment by jessemapel** [comment]
After @Kelvinrr updated the data area these are now passing.
