### ISSUE TITLE
Clean up the release process wiki page

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3546]
**Description**

We've made several changes recently to the recent process and the release process wiki page has gotten messy. 

**Suggested Edit**

The lines that actually describe what to do are mixed with lines that explain why you need to do it. We should separate these out, so that it is very clear when you need to do something.

We should also move the section about what to do after building off tarballs is supported to the end of the document. Right now, it just confuses readers.

The sections also need to be reformatted to a consistent style and edited to a consistent voice.

**Comment by jlaura** [comment]
@jessemapel Is this done?

**Comment by jessemapel** [comment]
Not quite, we still need to update the last 3 sections.

**Comment by jessemapel** [comment]
Done
