### ISSUE TITLE
Possible bug in marcical

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#3550]
**ISIS version(s) affected**: 3.9.1 

**Description**  

The calibration for MRO MARCI (marcical) may have a bug.

Before the main calibration processing loop maxOffset is set to the max of the padding vector. During the loop maxOffset is updated when the band changes to a new band, but only if the MARCI file was flipped during ingestion. This very well may be correct, but it looks suspect.

**How to reproduce**  

**Possible Solution**  

Read the calibration report and decide if this code is working as expected.

**Additional context**  

Coordinate this with any work to modify the flipping #3547

**Comment by dpmayerUSGS** [comment]
Adding the Products label because this issue is blocking support for MARCI in POW.

**Comment by acpaquette** [comment]
The maxoffset handles the framelette offset when a marci image is flipped on ingest. As it stands this doesn't seem to be a problem within the larger context of the marci calibration. However the calibration as a whole should be examined for correctness at some later date outside of a product support sprint.
