### ISSUE TITLE
Qmos grid broken for PosWest, Clon0 under isis3.9.1

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#3573]
**ISIS version(s) affected**: 3.9.1

**Description**  
The grid function does not draw properly under this version using a map having LongitudeDirection=PositiveWest and LongitudeDomain=180 (with clon=0).  This is not the case under isis3.9.0, so this appears to have been introduced when changes were made by way of #3417.

See attachments below for 3.9.1 (top) vs 3.9.0 (bottom) views.

**How to reproduce**  
Data are available under /work/users/lweller/Isis3Tests/Qmos/LonDirection/Clon0/

- Launch Qmos
- Open Cube List gll_lev1_sml.lis (data which covers all longitudes and nearly goes to both poles in latitude)
- Quick Load Map equi_PosWest180.map
- Enable Grid - broken at this point (no lines of longitude except at left end)
- Grid Options (to see if it fixes anything): Latitude increment 45, Longitude increment 60, Latitude/Longitude Range Read from map file (to get grid to extend to poles) - still broken (no lines of longitude except at left end), but clicking grid options, then apply seems to fix things.  This is the attachment view.

I get similar behavior if a different map is loaded first (PosEast/PosWest clon180 - see other map files in same directory), then try and redraw with equi_PosWest180.map.

Sometimes when redrawing using a new map, the grid won't always draw properly (might be shifted by 180 degrees of longitude, one way or the other) until I click on Grid Options, then apply.  That seems to draw the grid properly, though I have found I might have to hit apply a couple of times.  Maybe this is a separate issue?  It all seems related to me though.
![broken_GLL_PosWest180_I3 9 1](https://user-images.githubusercontent.com/34550733/70459689-eee78b80-1a71-11ea-9b5b-2bd86dc5922c.png)
![GLL_PosWest180_I3 9 0](https://user-images.githubusercontent.com/34550733/70459691-ef802200-1a71-11ea-8ec8-3caa3d09d246.png)

**Additional context**  
There is sort of a general problem with applying a new map file when a grid is already present.  It may or may not draw the grid properly.

**Comment by Kelvinrr** [comment]
Made some progress on this today, seems like the grid logic is fine, the issue lat/lon extents are not being updated correctly when you change them (e.g. loading a different map file). I'll do some reading on signals/slots and dig through ISIS's code to see where/how the projection update needs to happen.

**Comment by Kelvinrr** [comment]
Closed by #3714
