### ISSUE TITLE
cnetcombinept - request for new output file

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#3575]
**Description**  
The user has no way of knowing what points gained new measures when points that fall within the IMAGETOL value are combined.  It would be nice to know what points were affected for validation purposes, particularly when one is trying to decide on an appropriate tolerance value.

**Example**  
I'm thinking the most direct way to satisfy this request is the creation of a file containing the point id's which gained measures from the merging process.  A simple text file will do. A new parameter may be needed to name the output file (or files - allowing for possible add-ons in the future), something like PREFIX from cnetcheck (or whatever makes sense, I don't know at this point).

It might also be nice to know what points are being merged into new points (these will be set to ignore, then ultimately removed using the default cleannet setting).  

Trying to determine what's been merged is difficult for the most simplistic merges, so getting any detailed feedback on the process is welcome.

**Comment by lwellerastro** [comment]
I'll find a very small data set that can be combined in such a way that the points will be easy to track and post the location here.  This will help me remember what @jessemapel and I discussed as possible output and provide an example for testing that is easy to follow.

**Comment by lwellerastro** [comment]
This may be more complicated than I was hoping for a couple of reasons.

a) I'm really not sure how this new output file should be arranged
It would be easiest to create and parse through the output if it were CSV, but I am unsure on precisely what should be on a line.  I don't even know what to call the output file.

b) It requires a new parameter that would only be applicable to a true merger (associated with IMAGETOL).  
The parameter SETAPRIORIBEST has nothing to do with merging points and seems to be an add-on.  I just want to point this out ahead of time in case it poses an issue.  I'm not sure it's an issue at all, but I was trying to see how/where a new parameter might fit in.

I have small set of networks to be merged under /work/users/lweller/Isis3Tests/CnetCombinePt/Log/.  It is small enough that I can trace (with a lot of qnetting) what points have been merged.  The text file proc.scr describes what has been merged for later reference.

Command line:

> cnetmerge inputtype=list clist=connect_nets_2.lis onet=TestMerge.net networkid=Test description=Test

From visual tracking I know:

>   25ESGLOBAL01_G2ESPHOTOM01_10ESGLOBAL01_LWAdd_7 (4 measures) merged with 25ESGLOBAL01_C9ESGLOBAL01_LWAdd_17 (2 measures)
>   --> 25ESGLOBAL01_G2ESPHOTOM01_10ESGLOBAL01_LWAdd_7 (retained, 5 measures)
>   --> 25ESGLOBAL01_C9ESGLOBAL01_LWAdd_17 (deleted)
> 
>   25ESGLOBAL01_G2ESPHOTOM01_10ESGLOBAL01_LWAdd_1 (3 measures) merged with 25ESGLOBAL01_C9ESGLOBAL01_LWAdd_23 (2 measures) and LWTEST (3 measures)
>   --> 25ESGLOBAL01_G2ESPHOTOM01_10ESGLOBAL01_LWAdd_1 (retained, 4 measures)
>   --> 25ESGLOBAL01_C9ESGLOBAL01_LWAdd_23 (deleted)
>   --> LWTEST (deleted)
> 

What is most useful to me, at the most basic level, is which points were merged.    Maybe as a starting point an output csv file would have the final retained PointId, followed by the merged points PointId's on each line?

I can't really demo here because my PointId's are too long (this is real data so I'm not going to take the time to rename them, which you can't do readily anyway).

**Comment by jessemapel** [comment]
One potential approach is a CSV with 5 columns:
1. Point ID
1. Starting # measures
1. Ending # measures
1. Points which it gained measures from
1. Points which it lost measures to

We would be double book keeping things, but I think it provides the best info for a user.

**Comment by lwellerastro** [comment]
@jessemapel thanks so much for the feedback!

I like your idea.  Yeah, the double book keeping might come off as a bit much, but it would be a way to see how many measures all points involved in merging started with, which you wouldn't get with the first 4 bullets alone.

**Comment by jessemapel** [comment]
I completely skipped over that cnetcombinept only combines entire control points and not just measures. This makes the output quite a bit simpler.

Here's the new output file format I'm look at:

          A two column CSV file that contains which input control points were
          merged into output control points. The first column contains the
          ID of each output control point that had at least one input control
          point merged into it. The Second column contains a space separated
          list of the IDs of input control points that were merged into
          the output control point in the first column.

I'm adding a new parameter called `LOGFILE` that is the CSV log. If it's not entered, then the app won't log at all to maintain current performance with very dense networks.

**Comment by lwellerastro** [comment]
@jessemapel this sounds really good.  Is it too difficult to include the starting and ending number of measures for output point that gained measures, as you originally suggested?  That would be useful if it's not a taxing thing to trace and record.

Initially I wasn't sure about the second column being a space delimited list of ptids that were merged into the output point, but I think it makes sense.  If measure in/out counts were included than it would make most sense to make this the last column.  Makes it easier when cutting on columns to get all merged points in one go.

**Comment by jessemapel** [comment]
@lwellerastro Yeah I can do output point id, input measure count, output measure count, list of points merged in.

**Comment by lwellerastro** [comment]
> * Point ID
> * Starting # measures
> * Ending # measures
> * Points which it gained measures from

I think these bullets from your initial idea list are adequate, with the last column being a space delimited list of ptid's merged into the output pointid.  This will be really useful and I agree it should be an option a user has to deliberately turn on.

**Comment by lwellerastro** [comment]
Sorry, I should have checked other versions first. I'm working under isis4.0.0 because serial numbers are not available for Kaguya TC under newer versions and noticed cnetcombinept doesn't have a log parameter.  This functionality was added sometime after isis4.0.0 so I can't use it at the moment.  Bummer.
