### ISSUE TITLE
Modules exit without completing operation due to the absence of the file "CubeFormatTemplate.pft"

### ISSUE THREAD

**Issue by arozhok** [DOI-USGS/ISIS3#3592]
The program exits with the following notification:
```
mirror f=~/Downloads/Intro2isis.cub t=~/Downloads/Intro2flip.cub
libc++abi.dylib: terminating with uncaught exception of type Isis::IException: **I/O ERROR** Unable to open [/Users/andriirozhok/miniconda3/envs/isis3/data/base/templates/labels/CubeFormatTemplate.pft].
Abort trap: 6
```
The route /data/base/templates/labels/ does not exist indeed just as the file in the installation

**ISIS version(s) affected**: 3

**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by jessemapel** [comment]
Do you have your data area setup correctly?

https://github.com/USGS-Astrogeology/ISIS3#the-isis-data-area

**Comment by arozhok** [comment]
jessemapel - many thanks! I haven't done that, as I am a novice with ISIS. But thanks for the instruction link! Now everything works
