### ISSUE TITLE
Re-enable NGINX cache on Jenkins CI

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3603]
**ISIS version(s) affected**: dev

**Description**  

I disabled the NGINX Anaconda cache because it was slow to update and we were pushing one to two release of ALE a day. Now that we're not working on ALE anymore, we should re-enable the NGINX cache on Jenkins to speed up builds.

**Possible Solution**  

Uncomment the line in the build.groovy script.

**Additional context**  

The cache was disabled in #3591 and then merged into dev with #3590

**Comment by jlaura** [comment]
@jessemapel @Kelvinrr Is this making an appreciable difference in the speed? Are we intentionally keeping this disabled while working on the ISIS dependencies? Can we re-enable when @Kelvinrr is doing the groovy/jenkins work?

**Comment by jessemapel** [comment]
Time without the cache is 6:30-7:00 minutes
Time with the cache was 3:00-3:30 minutes

So we're looking a maximum of 4 minutes saved.

**Comment by jessemapel** [comment]
@evindunn Is this something that we need to turn back on? It's been off for months now.

**Comment by evindunn** [comment]
@jessemapel sorry, don't know how I missed this. I'm on it.

**Comment by jessemapel** [comment]
@evindunn Sorry, this isn't something that you need to do. We commented out the part of the Jenkins file that sets it to use the cache and it's been stable and fairly fast. I'm not looking for you to turn it back on, just asking if this is something that we need to turn back on. To me it looks like we don't need it.

**Comment by evindunn** [comment]
Ok, sounds good
