### ISSUE TITLE
Enlarge Reporting the final lines and samples backwards

### ISSUE THREAD

**Issue by AaronBoyd** [DOI-USGS/ISIS3#3659]
**ISIS version(s) affected**: 3.4.1(and probably before) through and including 3.9.1

**Description**  
Enlarge reports the OutputLines as the output samples and the OutputSamples as the output lines

**How to reproduce**  
run enlarge (and sscale and lscale)

view the results group generated to see the switch

**Possible Solution**  
this appears to be just a typo that needs to be corrected.

**Additional context**  

  Group = UserParameters
    FROM   = image1
    TO     = image2
    INTERP = nearest
    MODE   = SCALE
    SSCALE = 1
    LSCALE = 14
  End_Group

  Group = Results
    InputLines      = 78
    InputSamples    = 704
    StartingLine    = 1
    StartingSample  = 1
    EndingLine      = 78
    EndingSample    = 704
    LineIncrement   = 0.071428571428571
    SampleIncrement = 1.0
    OutputLines     = 704
    OutputSamples   = 1092
  End_Group

**Comment by jessemapel** [comment]
Yep, looks flipped https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/Enlarge/Enlarge.cpp#L144

**Comment by jlaura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enlarge Reporting the final lines and samples backwards](https://trello.com/c/7QOSiU5s/82-enlarge-reporting-the-final-lines-and-samples-backwards)

**Comment by acpaquette** [comment]
@ladoramkershner Can this be closed?
