### ISSUE TITLE
Change prime meridian of Dawn at Vesta mosaic?

### ISSUE THREAD

**Issue by jescully** [DOI-USGS/ISIS3#3664]
Hello,

I am trying to change the prime meridian of global mosaics of Vesta. The prime meridian of the mosaics archived on the PDS is different to the prime meridian of many of the mosaics made by the Dawn team. I am working on a ROSES-funded project and want all of the mosaics that I use to be defined wrt. the PDS prime meridian. 

I made a .tpc file that allows me to make my own local mosaics from Dawn Framing Camera images that align perfectly with the mosaics archived on the PDS: dawnfc2isis, spiceinit using the PCK file I made, cam2map etc. 

But, I am now trying to convert some global mosaics made by the Dawn team that were not archived on the PDS, e.g. the LAMO Clementine mosaic (only the HAMO version is archived on the PDS). These mosaics do not have the same prime meridian as the PDS-archived mosaics, and thus do not align with the mosaics I downloaded from the PDS nor with the local mosaics I made. 

I tried using map2map, with the global mosaic for which I want to change the prime meridian in the from field, a global PDS mosaic with the prime meridian I want in the map field, and matchmap=yes. After many hours of processing this returned a global mosaic that has the same prime meridian as the original file, neither of which match the PDS mosaics. I also tried using my .tpc file in the map field, but this failed.

It doesn't look like prime meridian information is included in map files, and thus I don't think that map2map will allow me to change the prime meridian of an already projected file. Is there some other program I can use? Or some other option in map2map that will allow me to change the prime meridian? I've looked through the list of ISIS applications and can't find anything obvious.

Thank you in advance for your help!

Jennifer

**Comment by jessemapel** [comment]
@jescully Hi, this is more of a how to use ISIS question which we host over on https://astrodiscuss.usgs.gov/

Can you repost your questions over there? We use github issues for bugs and feature requests.

**Comment by jescully** [comment]
Will do - thanks!

**Comment by jessemapel** [comment]
Conversation migrated to https://astrodiscuss.usgs.gov/t/change-prime-meridian-of-dawn-at-vesta-mosaic/355

@jescully Thank you
