### ISSUE TITLE
Add support for HRSC SRC images

### ISSUE THREAD

**Issue by Ethands123** [DOI-USGS/ISIS3#3665]
**ISIS version(s) affected**: x.y.z
Using isis3.9.1
**Description**  

When running spiceinit on a HRSC SRC image I get an error.
![Spice_error](https://user-images.githubusercontent.com/33068661/73581492-a384a480-4446-11ea-90d9-14bffd1e1683.png)

**How to reproduce**  

To reproduce the data is at /work/users/edsmith/Phobos/HRCS the SRC image is
HI837_0002_SR2.IMG
HI837_0002_SR2.cub
I took the .IMG file ran it through pds2isis then attempted spiceinit with the resulting .cub file. 
In the same area is a HRSC image from not the SRC I grabbed a nadir image seen below and I was able to ingest this with hrsc2isis and then spiceinit was successful. 
HI395_0000_ND2.IMG
HI395_0000_ND2.cub
**Possible Solution**  

**Additional context**  

I grabbed the images from https://archives.esac.esa.int/psa/#!Table%20View/Phobos=target

**Comment by krlberry** [comment]
Hi @Ethands123, As a quick initial response, `pds2isis` unfortunately doesn't provide the cube it outputs with all the information needed for `spiceinit` to run. `hrsc2isis` would normally add this information to the cube, but I see that it doesn't support SRC data. I don't have much experience with HRSC specifically, so maybe another developer could chime in with more information, but it looks to me like to fix this problem, `hrsc2isis` (and maybe the camera model) would need to be updated to support SRC data.

**Comment by kberryUSGS** [comment]
For what it's worth I went through and added the minimum necessary keywords for `spiceinit` to the `pds2isis` output cube's label via `editlab` (see below), but `spiceinit` still won't function because the HRSC camera model expects a `
LineScanTimes` table to be attached to the cube, and that's beyond what `editlab` can do.

```
   Group = Instrument
    SpacecraftName = "Mars Express"
    StartTime      = 2018-11-21T15:32:08.519
    InstrumentId   = HRSC
    TargetName     = Phobos
  End_Group

  Group = Kernels
    NaifIkCode = -41220
  End_Group
```

**Comment by blandoplanet** [comment]
This may be a blocker for the Phobos IAA task. I'll iterate with the PC.

**Comment by jessemapel** [comment]
@Ethands123 Did hrsc2isis fail on this image? The HRSC camera model requires some specific information that gets parsed during hrsc2isis, so spiceinit failing after using pds2isis to ingest HRSC data is expected.

**Comment by Ethands123** [comment]
@jessemapel hrsc2isis gives the error seen below which tells me to use pds2isis.
![image](https://user-images.githubusercontent.com/33068661/73681012-a5cf4480-467a-11ea-8fd5-3f247cbd0b19.png)

@kberryUSGS  Thanks for checking it out so fast.

**Comment by jessemapel** [comment]
I'm labeling this as an enhancement because the sensor and ingestion are not designed to support SRC images

**Comment by lwellerastro** [comment]
@Ethands123, I just looked at the documentation for hrsc2isis
 https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/hrsc2isis/hrsc2isis.html and that example uses data having the format RE2.IMG as opposed to SR2.IMG or ND2.IMG.  I think the R means it is radiometrically corrected.

I found an abstract by Kirk et. al.  https://elib.dlr.de/93867/1/2535.pdf involving this data and they said they used already calibrated images.  But it also looks like they were under ISIS2.  I'm assuming we converted that version of the program to ISIS3 but I honestly don't know.

Would you mind looking in the archive you pulled from and see if there are RE2 versions of the images you are interested in and running those through hrsc2isis.  I don't know how the archive is set up, so the files may be under another directory and they may refer to it as "Level 2" which used by the PDS to indicate it was specially processed (and is not the same as Level 2 in ISIS which means map projected - I know, totally confusing!).  Let us know how that goes.

It's also possible this is not data they bothered to clean up (I'm forgetting we're talking about Phobos and not Mars), so you might have grabbed the only data available.

**Comment by jlaura** [comment]
@scsides Can we close this after the HRSC SRC sensor model work?

**Comment by scsides** [comment]
'hrsc2isis' now works on 'src' data also.
Note, his specific file was not tested.
________________________________

**Comment by jessemapel** [comment]
Closing as this was reported as done. If this is not complete then please re-open.
