### ISSUE TITLE
Problem with Voyager 2 SPICEINIT

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#3672]
It looks like there's been some discussion of Voyager 2 SPICE-related issues over the years, but the issue that comes closest to my current issue is [this one over at GitMemory](https://gitmemory.com/issue/USGS-Astrogeology/ISIS3/3429/528619828).

Running the latest 3.9.x version of ISIS3, and I checked that my Voyager 2 kernels are updated.  Working on Miranda, SPICEINIT fails completely with errors like the one copied below.

Looking in my SPK directory, I don't actually have a de430.bsp file (again, I did just do another rsync and it says my V2 directory is fine).  I tried adding "tspk=/Users/stu/isis3/data/voyager2/kernels/spk/vgr2_ura083.bsp" to the SPICEINIT command based on the GitMemory post since that was the main difference in the SPICE kernels.  Same error.  So I'm wondering if the issue is that the USGS distribution accidentally removed the de430.bsp spacecraft kernel and that's the problem?  I'm working only on resolved Miranda images, like this from closest approach: c2684629.imq

The error on all the images I tried to process:
```Group = Kernels
  NaifFrameCode             = -32101
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = $base/kernels/pck/pck00009.tpc
  TargetPosition            = $base/kernels/spk/de430.bsp
  InstrumentPointing        = ($voyager2/kernels/ck/vg2_ura_version1_type2_is-
                               s_sedr.bc, $voyager2/kernels/fk/vg2_v02.tf)
  Instrument                = $voyager2/kernels/ik/vg2_issna_v02.ti
  SpacecraftClock           = $voyager2/kernels/sclk/vg200011.tsc
  InstrumentPosition        = $voyager2/kernels/spk//vgr2_ura083.bsp
  InstrumentAddendum        = $voyager2/kernels/iak/voyagerAddendum004.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
  Error                     = "An unknown NAIF error has been encountered. The
                               short explanation provided by NAIF is
                               [SPICE(SPKINSUFFDATA)]. The Naif error is
                               [Insufficient ephemeris data has been loaded to
                               compute the state of 705 (MIRANDA) relative to 0
                               (SOLAR SYSTEM BARYCENTER) at the ephemeris epoch
                               1986 JAN 23 01:04:04.349.]"
End_Group
**ERROR** Unable to initialize camera model.

**Comment by jessemapel** [comment]
The de430.bsp kernel is located in the base data area, `$ISIS3DATA/base`, did you look there or under the voyager directory, `$ISIS3DATA/voyager2`?

The issue looks like we don't have the Uranus satellite kernels available:

```
-bash-4.1$ ls base/kernels/spk/
aareadme.txt  jup310.cmt       mar097.bsp  nep090.cmt         SAVEde418.bsp
de118.bsp     kernels.0001.db  mar097.cmt  sat393.bsp         SAVEde421.bsp
de245.bsp     kernels.0002.db  nep081.bsp  sat393.cmt         SAVEde421.bsp.log
de405.bsp     kernels.0003.db  nep081.cmt  sat425.bsp
de430.bsp     kernels.0004.db  nep086.bsp  sat425.cmt
docs          mar080.bsp       nep086.cmt  SAVEde414.bsp
jup310.bsp    mar080.cmt       nep090.bsp  SAVEde414.bsp.log
```

[ura111](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/ura111.cmt) looks like it has Miranda in it. The fix here is likely for us to add the Uranus kernels from https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/ to the base spk kernel directory and update the kernel dbs.

@astrostu for right now try downloading [ura111.bsp](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/ura112.bsp) and passing it as an extra kernel.

**Comment by kaitlyndlee** [comment]
I added the satellite kernels matching ura###.bsp to the base area and updated the kerneldb file. Spiceinit should be able to pick up these kernels now.
