### ISSUE TITLE
Remove old LOLA/GRAIL SPK files 

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#3689]
**Description**  
The LRO/kernels/spk directory currently contains LOLA/GRAIL SPK files that use the older gravity model GRGM660. The newer LOLA/GRAIL SPK files use the newer gravity model GRGM900C. The older files should be removed to reduce confusion and data quantity.

**Comment by jessemapel** [comment]
@scsides Is there a location where the old SPKs are archived if users want to continue using them after this?

**Comment by scsides** [comment]
None that I've been able to find. The source site for these doesn't have a link, that I've found, for older versions.

**Comment by jlaura** [comment]
We have had no additional feedback on this in the last 3 weeks. I am going to move to close this RFC as accepted and remove the old LOLA/GRAIL SPK files. Any objections?

**Comment by lwellerastro** [comment]
Before you close this, could someone be more explicit in regard to the filenames.  There is a small chance that the data for Brent's LROC NAC polar mosaics may be pointing to some of these older files and would need to be re-spiced (some of the data will be active next FY because of their inclusion in an IAA proposal to get them delivered).  I'm interested from a heads-up perspective.  Some images may not have been spiced in several years so knowing they may have to be will be useful information.  Thanks!

**Comment by scsides** [comment]
@lwellerastro, Here is a list of old LOLA SPK followed by the new ones.
Old - to be removed ---------------------------
LRO_CO_201308_GRGM660PRIMAT270.bsp
LRO_ES_01_201308_GRGM660PRIMAT270.bsp
LRO_ES_02_201308_GRGM660PRIMAT270.bsp
LRO_ES_03_201308_GRGM660PRIMAT270.bsp
LRO_ES_04_201308_GRGM660PRIMAT270.bsp
LRO_ES_05_201308_GRGM660PRIMAT270.bsp
LRO_ES_06_201308_GRGM660PRIMAT270.bsp
LRO_ES_07_201308_GRGM660PRIMAT270.bsp
LRO_ES_08_201308_GRGM660PRIMAT270.bsp
LRO_ES_09_201308_GRGM660PRIMAT270.bsp
LRO_NO_01_201308_GRGM660PRIMAT270.bsp
LRO_NO_02_201308_GRGM660PRIMAT270.bsp
LRO_NO_03_201308_GRGM660PRIMAT270.bsp
LRO_NO_04_201308_GRGM660PRIMAT270.bsp
LRO_NO_05_201308_GRGM660PRIMAT270.bsp
LRO_NO_06_201308_GRGM660PRIMAT270.bsp
LRO_NO_07_201308_GRGM660PRIMAT270.bsp
LRO_NO_08_201308_GRGM660PRIMAT270.bsp
LRO_NO_09_201308_GRGM660PRIMAT270.bsp
LRO_NO_10_201308_GRGM660PRIMAT270.bsp
LRO_NO_11_201308_GRGM660PRIMAT270.bsp
LRO_NO_12_201308_GRGM660PRIMAT270.bsp
LRO_NO_13_201308_GRGM660PRIMAT270.bsp
LRO_SM_01_201308_GRGM660PRIMAT270.bsp
LRO_SM_02_201308_GRGM660PRIMAT270.bsp
LRO_SM_03_201308_GRGM660PRIMAT270.bsp
LRO_SM_04_201308_GRGM660PRIMAT270.bsp
LRO_SM_05_201308_GRGM660PRIMAT270.bsp
LRO_SM_06_201308_GRGM660PRIMAT270.bsp
LRO_SM_07_201308_GRGM660PRIMAT270.bsp
LRO_SM_08_201308_GRGM660PRIMAT270.bsp
LRO_SM_09_201308_GRGM660PRIMAT270.bsp
LRO_SM_10_201308_GRGM660PRIMAT270.bsp
LRO_SM_11_201308_GRGM660PRIMAT270.bsp
LRO_SM_12_201308_GRGM660PRIMAT270.bsp
LRO_SM_13_201308_GRGM660PRIMAT270.bsp
LRO_SM_14_201308_GRGM660PRIMAT270.bsp
LRO_SM_15_201308_GRGM660PRIMAT270.bsp
LRO_SM_16_201308_GRGM660PRIMAT270.bsp
LRO_SM_17_201308_GRGM660PRIMAT270.bsp
LRO_SM_18_201308_GRGM660PRIMAT270.bsp
LRO_SM_19_201308_GRGM660PRIMAT270.bsp
LRO_SM_20_201308_GRGM660PRIMAT270.bsp
LRO_SM_21_201308_GRGM660PRIMAT270.bsp
LRO_SM_22_201308_GRGM660PRIMAT270.bsp
LRO_SM_23_201308_GRGM660PRIMAT270.bsp
LRO_SM_24_201308_GRGM660PRIMAT270.bsp
LRO_SM_25_201308_GRGM660PRIMAT270.bsp
LRO_SM_26_201308_GRGM660PRIMAT270.bsp

NEW---------------------------------------------
LRO_CO_201311_GRGM900C_L600.BSP
LRO_ES_01_201311_GRGM900C_L600.BSP
LRO_ES_02_201311_GRGM900C_L600.BSP
LRO_ES_03_201311_GRGM900C_L600.BSP
LRO_ES_04_201311_GRGM900C_L600.BSP
LRO_ES_05_201311_GRGM900C_L600.BSP
LRO_ES_06_201311_GRGM900C_L600.BSP
LRO_ES_07_201311_GRGM900C_L600.BSP
LRO_ES_08_201311_GRGM900C_L600.BSP
LRO_ES_09_201311_GRGM900C_L600.BSP
LRO_ES_10_201311_GRGM900C_L600.BSP
LRO_ES_11_201311_GRGM900C_L600.BSP
LRO_ES_12_201311_GRGM900C_L600.BSP
LRO_ES_13_201311_GRGM900C_L600.BSP
LRO_ES_14_201406_GRGM900C_L600.BSP
LRO_ES_15_201406_GRGM900C_L600.BSP
LRO_ES_16_201406_GRGM900C_L600.BSP
LRO_ES_17_201406_GRGM900C_L600.BSP
LRO_ES_18_201406_GRGM900C_L600.BSP
LRO_ES_19_201406_GRGM900C_L600.BSP
LRO_ES_20_201406_GRGM900C_L600.BSP
LRO_ES_21_201406_GRGM900C_L600.BSP
LRO_ES_22_201411_GRGM900C_L600.BSP
LRO_ES_23_201411_GRGM900C_L600.BSP
LRO_ES_24_201411_GRGM900C_L600.BSP
LRO_ES_25_201503_GRGM900C_L600.BSP
LRO_ES_26_201503_GRGM900C_L600.BSP
LRO_ES_27_201503_GRGM900C_L600.BSP
LRO_ES_28_201503_GRGM900C_L600.BSP
LRO_ES_29_201503_GRGM900C_L600.BSP
LRO_ES_30_201503_GRGM900C_L600.BSP
LRO_ES_31_201503_GRGM900C_L600.BSP
LRO_ES_32_201508_GRGM900C_L600.BSP
LRO_ES_33_201508_GRGM900C_L600.BSP
LRO_ES_34_201508_GRGM900C_L600.BSP
LRO_ES_35_201508_GRGM900C_L600.BSP
LRO_ES_36_201602_GRGM900C_L600.BSP
LRO_ES_37_201602_GRGM900C_L600.BSP
LRO_ES_38_201602_GRGM900C_L600.BSP
LRO_ES_39_201602_GRGM900C_L600.BSP
LRO_ES_40_201602_GRGM900C_L600.BSP
LRO_ES_41_201602_GRGM900C_L600.BSP
LRO_ES_42_201602_GRGM900C_L600.BSP
LRO_ES_43_201604_GRGM900C_L600.BSP
LRO_ES_44_201604_GRGM900C_L600.BSP
LRO_ES_45_201604_GRGM900C_L600.BSP
LRO_ES_46_201608_GRGM900C_L600.BSP
LRO_ES_47_201608_GRGM900C_L600.BSP
LRO_ES_48_201608_GRGM900C_L600.BSP
LRO_ES_49_201612_GRGM900C_L600.BSP
LRO_ES_50_201612_GRGM900C_L600.BSP
LRO_ES_51_201612_GRGM900C_L600.BSP
LRO_ES_52_201612_GRGM900C_L600.BSP
LRO_ES_53_201706_GRGM900C_L600.BSP
LRO_ES_54_201706_GRGM900C_L600.BSP
LRO_ES_55_201706_GRGM900C_L600.BSP
LRO_ES_56_201706_GRGM900C_L600.BSP
LRO_ES_57_201706_GRGM900C_L600.BSP
LRO_ES_58_201706_GRGM900C_L600.BSP
LRO_ES_59_201708_GRGM900C_L600.BSP
LRO_ES_59_201801_GRGM900C_L600.BSP
LRO_ES_60_201708_GRGM900C_L600.BSP
LRO_ES_60_201801_GRGM900C_L600.BSP
LRO_ES_61_201801_GRGM900C_L600.BSP
LRO_ES_62_201801_GRGM900C_L600.BSP
LRO_ES_63_201801_GRGM900C_L600.BSP
LRO_ES_64_201801_GRGM900C_L600.BSP
LRO_ES_65_201801_GRGM900C_L600.BSP
LRO_ES_66_201805_GRGM900C_L600.BSP
LRO_ES_67_201805_GRGM900C_L600.BSP
LRO_ES_68_201805_GRGM900C_L600.BSP
LRO_ES_69_201805_GRGM900C_L600.BSP
LRO_ES_70_201809_GRGM900C_L600.BSP
LRO_ES_71_201809_GRGM900C_L600.BSP
LRO_ES_72_201809_GRGM900C_L600.BSP
LRO_ES_73_201809_GRGM900C_L600.BSP
LRO_ES_74_201809_GRGM900C_L600.BSP
LRO_ES_75_201902_GRGM900C_L600.BSP
LRO_ES_76_201902_GRGM900C_L600.BSP
LRO_ES_77_201902_GRGM900C_L600.BSP
LRO_ES_78_201902_GRGM900C_L600.BSP
LRO_ES_79_201905_GRGM900C_L600.BSP
LRO_ES_80_201905_GRGM900C_L600.BSP
LRO_ES_81_201905_GRGM900C_L600.BSP
LRO_ES_82_201910_GRGM900C_L600.BSP
LRO_ES_83_201910_GRGM900C_L600.BSP
LRO_ES_84_201910_GRGM900C_L600.BSP
LRO_ES_85_201910_GRGM900C_L600.BSP
LRO_ES_86_201910_GRGM900C_L600.BSP
LRO_NO_01_201311_GRGM900C_L600.BSP
LRO_NO_02_201311_GRGM900C_L600.BSP
LRO_NO_03_201311_GRGM900C_L600.BSP
LRO_NO_04_201311_GRGM900C_L600.BSP
LRO_NO_05_201311_GRGM900C_L600.BSP
LRO_NO_06_201311_GRGM900C_L600.BSP
LRO_NO_07_201311_GRGM900C_L600.BSP
LRO_NO_08_201311_GRGM900C_L600.BSP
LRO_NO_09_201311_GRGM900C_L600.BSP
LRO_NO_10_201311_GRGM900C_L600.BSP
LRO_NO_11_201311_GRGM900C_L600.BSP
LRO_NO_12_201311_GRGM900C_L600.BSP
LRO_NO_13_201311_GRGM900C_L600.BSP
LRO_SM_01_201311_GRGM900C_L600.BSP
LRO_SM_02_201311_GRGM900C_L600.BSP
LRO_SM_03_201311_GRGM900C_L600.BSP
LRO_SM_04_201311_GRGM900C_L600.BSP
LRO_SM_05_201311_GRGM900C_L600.BSP
LRO_SM_06_201311_GRGM900C_L600.BSP
LRO_SM_07_201311_GRGM900C_L600.BSP
LRO_SM_08_201311_GRGM900C_L600.BSP
LRO_SM_09_201311_GRGM900C_L600.BSP
LRO_SM_10_201311_GRGM900C_L600.BSP
LRO_SM_11_201311_GRGM900C_L600.BSP
LRO_SM_12_201311_GRGM900C_L600.BSP
LRO_SM_13_201311_GRGM900C_L600.BSP
LRO_SM_14_201311_GRGM900C_L600.BSP
LRO_SM_15_201311_GRGM900C_L600.BSP
LRO_SM_16_201311_GRGM900C_L600.BSP
LRO_SM_17_201311_GRGM900C_L600.BSP
LRO_SM_18_201311_GRGM900C_L600.BSP
LRO_SM_19_201311_GRGM900C_L600.BSP
LRO_SM_20_201311_GRGM900C_L600.BSP
LRO_SM_21_201311_GRGM900C_L600.BSP
LRO_SM_22_201311_GRGM900C_L600.BSP
LRO_SM_23_201311_GRGM900C_L600.BSP
LRO_SM_24_201311_GRGM900C_L600.BSP
LRO_SM_25_201311_GRGM900C_L600.BSP
LRO_SM_26_201311_GRGM900C_L600.BSP

**Comment by jlaura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove old LOLA/GRAIL SPK files](https://trello.com/c/YTmwvXfA/81-remove-old-lola-grail-spk-files)

**Comment by ladoramkershner** [comment]
For documentation:
I moved the old (LRO_\*_GRGM660\*.bsp) files into a temporary directory (/usgs/cpkgs/isis3/old_data/lro/kernels/spk/), to test whether not this will break any systems before we actually remove these files. Additionally, I removed these kernels from the kernels database makefile, so they should not be referenced by spiceinit.

**Comment by ladoramkershner** [comment]
I am going to close this issue for now, we will reopen if issues arise from this change.
