### ISSUE TITLE
MARCI Flatfiles in Data Area are Deprecated

### ISSUE THREAD

**Issue by dpmayerUSGS** [DOI-USGS/ISIS3#3690]
**ISIS version(s) affected**: 3.4-present

**Description**  
It was recently determined in #3504 that the calibration flatfiles for MARCI currently in the ISIS data area are not based on the most recent, canonical versions produced by the mission team at Malin Space Science Systems. In order to produce the highest radiometric quality MARCI products in ISIS, it is important to use the best flatfiles as determined by the mission team. 

**Possible Solution**  
Obtain the [latest flatfiles](https://pds-imaging.jpl.nasa.gov/data/mro/mars_reconnaissance_orbiter/marci/mrom_0033/calib/) from the MARCI archive, convert them from ddd to ISIS cube format, and perform additional raster arithmetic as necessary in order to make them compatible with `marcical`.

**Additional context**  
There is a possible bug in `marcical` (#3550 ) that may need to be addressed first before it is possible to know the most appropriate arithmetic operations (if any) to perform on the updated flatfiles in order to make them compatible with ISIS. 
#3504 contains information on how the legacy flatfiles were processed, but that procedure seems to deviate from the [official calibration documentation](https://pds-imaging.jpl.nasa.gov/data/mro/mars_reconnaissance_orbiter/marci/mrom_1148/calib/marcical.txt).

**Comment by acpaquette** [comment]
The visflat files in the data area have been updated along with their associated tests. However closing this issue is blocked by #3715, since the uvflat files can't be updated until that issue is closed.

**Comment by acpaquette** [comment]
The uvflat files in the data area have been updated accordingly!
