### ISSUE TITLE
CameraStatistics.cpp toPvl() "AspectRatioMaximun" typo

### ISSUE THREAD

**Issue by paarongiroux** [DOI-USGS/ISIS3#3697]
**ISIS version(s) affected**: x.y.z

**Description**  

See [CameraStatistics.cpp Line 444](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/CameraStatistics/CameraStatistics.cpp#L444). Just a small typo, outputs "AspectRatioMaximun" rather than "AspectRatioMaximum".
**How to reproduce**  

Run camstats, see output.
**Possible Solution**  

Change CameraStatistics.cpp Line444 to output "AspectRatioMaximum". Update truth data for all affected tests.
**Additional context**

**Comment by jessemapel** [comment]
This is already documented in #3605

**Comment by jessemapel** [comment]
Sorry, I forgot about that issue when reviewing your PR.
