### ISSUE TITLE
spiceinit web=yes fails with ISIS 4.0.0

### ISSUE THREAD

**Issue by foobarbecue** [DOI-USGS/ISIS3#3725]
**ISIS version(s) affected**: 4.0.0

**Description**  
I ran `spiceinit from=M1192901040LE.cub web=yes` (M1192901040LE.cub is an LROC NAC image produced from running `lronac2isis` on http://lroc.sese.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0024/DATA/ESM2/2015211/NAC/M1192901040LE.IMG ) and got this error:

`**ERROR** The Spice Server was unable to initialize the cube.  The error reported was: The SPICE server only supports Isis versions greater than or equal to 3.5.*.*.Your version:   [4.0.0  | 2020-02-07] is not compatible.`

**How to reproduce**  
See Description.

**Comment by foobarbecue** [comment]
Previously, https://github.com/USGS-Astrogeology/ISIS3/pull/780 . Looks like the fix wasn't general enough -- it only checks the minor version (y in x.y.z) .

**Comment by jlaura** [comment]
We will need to slot this into the next RC release (April 1) or get a more generalized fix in before hand time permitting.

@scsides Is it possible that @kaitlyndlee or @paarongiroux could take a look at this without causing issues during the clean up work? If this will cause a slippage on that work, we should defer fixing this.

**Comment by scsides** [comment]
Sure, lets talk with @jessemapel and @Kelvinrr about what implications this has for the ALE side (I don't know of any at this time.)

**Comment by jessemapel** [comment]
This shouldn't impact ALE. spice server just runs spiceinit on our server. The new table data is also compatible with the old table data and visa-versa. The main place that out of sync ISIS versions will be a problem is when camera model versions have changed. I think we've only really changed one or two camera model versions in the last few years so it shouldn't be a big concern.

**Comment by jlaura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [spiceinit web=yes fails with ISIS 4.0.0](https://trello.com/c/BKWOLODj/88-spiceinit-webyes-fails-with-isis-400)

**Comment by acpaquette** [comment]
@Kelvinrr Can this be closed?

**Comment by jessemapel** [comment]
This is still failing. @Kelvinrr Did the server get updated?

**Comment by michaelaye** [comment]
Still failing with 4.0.1:

> $ spiceinit from=/cabeus/maye/p4/ctx_data/P4_Ridges_joint_search1/T01_000885_1910_XI_11N335W/T01_000885_1910_XI_11N335W.cub web=true
**ERROR** The Spice Server was unable to initialize the cube.  The error reported was: The SPICE server only supports Isis versions greater than or equal to 3.5.*.*.Your version:   [4.0.1  | 2020-03-04] is not compatible.

Is there a quick work-around available?

**Comment by jessemapel** [comment]
@michaelaye Quick work around is to edit the version file located at $ISISROOT/version. If you change its version to 3.12.0 then it should work. You may get some weird side-effects with ASP and your cube history/print.prt will list the wrong version, but it should process correctly.

**Comment by volcanopele** [comment]
Can confirm that this is still an issue with ISIS 4.1.0

**Comment by AndrewAnnex** [comment]
just ran into this issue also

**Comment by AndrewAnnex** [comment]
@jessemapel what issues will ASP run into with this hack?

**Comment by rbeyer** [comment]
Should be none, ASP doesn't do anything with the contents of the version file.

**Comment by Kelvinrr** [comment]
spice server should be updated @foobarbecue try again and report if you get an error still.

**Comment by Kelvinrr** [comment]
I have not been able to replicate the issue since the update yesterday so I am going to consider this closed. If anyone discovers otherwise feel free to re-open.

**Comment by nschorgh** [comment]
Have the same problem with version 4.3.0.

> spiceinit from=M111675778LE.cub web=yes
**ERROR** The Spice Server was unable to initialize the cube.  The error reported was: No existing files found with a numerial version matching [moc_kernels.????.db] in [/work1/work2/isis3/isis/../data/lro/kernels/ck].

**Comment by jessemapel** [comment]
@nschorgh Your error is likely the same as #4179. We're working on a solution for it now.

**Comment by nschorgh** [comment]
This works now. Thanks!

> Have the same problem with version 4.3.0.
> 
> > spiceinit from=M111675778LE.cub web=yes
> > **ERROR** The Spice Server was unable to initialize the cube.  The error reported was: No existing files found with a numerial version matching [moc_kernels.????.db] in [/work1/work2/isis3/isis/../data/lro/kernels/ck].
