### ISSUE TITLE
Failing tests 

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#3788]
Dev

**Description**  
These four gtest tests fail when on a local build. They work on Jenkins

1622 - ThreeImageNetwork.FunctionalTestCnetstatsImageStats (Child aborted) 

1623 - ThreeImageNetwork.FunctionalTestCnetstatsPointStats (Child aborted) 

1673 - DefaultCube.FunctionalTestCamptSetGround (Child aborted) 

1675 - DefaultCube.FunctionalTestCamptCoordList (Child aborted) 

**How to reproduce**  
ctest

**Possible Solution**  

**Additional context**

**Comment by scsides** [comment]
@jlaura, As you suggested we should try and get these working.

**Comment by jessemapel** [comment]
These tests pass if you set the environment variable MALLOC_CHECK_=1

This is already defined in our Jenkins environment, hence they pass on Jenkins but not locally. This does indicate some deeper memory error though :(

**Comment by jlaura** [comment]
@scsides Is this still an issue?

**Comment by jessemapel** [comment]
Setting the malloc flag causes these to pass now.
