### ISSUE TITLE
Opening cubes outside of Process objects is error prone

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3805]
**Description**  

When opening input cubes using a command line argument outside of a Process object, like we will be doing for many of the app to callable conversions, the intuitive `Cube::open(ui.GetFilename("FROM"))` results in cube attributes being ignored. Similarly, `Cube::create(ui.GetFilename("TO"))` results in command line cube attributes being ignored. This recently popped up in #3798 and is a particularly insidious error because most app tests don't use cube attributes.

Instead, the correct way to open or create cubes from command line arguments is to make a Cube object, and then make a CubeAttributeInput or CubeAttributeOutput and set the approriate attributes on the Cube object prior to calling `Cube::open` or `Cube::create`. Logic for this can be found in `Process::SetInputCube` and `Process::SetOutputCube`

We should have a simple routine that properly opens an input or output Cube with all of its attributes from a command line argument. This could mean modifying UserInterface or even the Cube opening and creating interface to use FileName objects instead of QStrings.

**Example**  

I would really like the following to properly open a Cube from a command line argument:

```
Cube iCube(ui.GetFilename("FROM"));
```

Something like this would also work:

```
Cube iCube = openInputCube(ui, "FROM")
```

**Comment by jessemapel** [comment]
This hasn't gotten traction and hasn't recurred as an issue. I'm closing this for now, if it pops up again during app conversion I'll reopen.

**Comment by jessemapel** [comment]
Cropped back up in #4213

**Comment by scsides** [comment]
Thoughts: FileName already handles attributes, ~and the UI returns them with a getFilename()~. Cube open() ~and create()~ simply ignore the attributes. Is it reasonable to have open ~and create~ process the attributes and achieve @jessemapel goal above?

**Comment by Kelvinrr** [comment]
@scsides ~I imagine it is simple enough to just overload `Cube::Open` to allow the input attr object? I would assume one that accepts CubeInputAttrs and one for CubeOutputAttrs?~ EDIT: Seems like Cube::create does this? At least for output attrs, maybe an input attrs version is all that's needed for this.

**Comment by Kelvinrr** [comment]
Also, ` Process::SetInputCube(Cube *cube, int requirements)` and `Process::SetInputCube(Isis::Cube *inCube)` do not seem to apply input attrs.

**Comment by scsides** [comment]
~@Kelvinrr, I'm saying the attributes are being ignored inside cube::open. They are part of the file name that is passed in. All we need to do is not ignore them. As is, it is confusing to have what amounts to an argument be ignored. Yes we could add new functions to explicitly take atts as another arg, but why? That means the caller has to separate the name and att so they can be passed in separately. I believe, but might be wrong, the new SetInputCube(*Cube,...) are expecting the atts to be applied before they are called, like we do in the callable apps that do process the atts.~

**Comment by scsides** [comment]
This issue needs to be addressed sooner rather than later. A fair number of apps that have been converted to callable do not process the attributes at all. This has broken a long standing feature in ISIS that requires all apps that take cube parameter names to process the attributes.
