### ISSUE TITLE
How to cite ISIS in my paper/abstract?

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#3810]
**Description**
What is the preferred way to cite my use of ISIS in papers and abstracts that I publish?

**Background and Discussion**
I cannot seem to find an answer in the [FAQ](https://github.com/USGS-Astrogeology/ISIS3/wiki/FAQ) or in the repo.

The only "official" answer appears to be [this document](https://isis.astrogeology.usgs.gov/documents/References/References.html), last updated in 2013.

In my opinion, setting up a DOI-minting process through [Zenodo](https://zenodo.org/) for the ISIS software would be ideal, and would provide an automatic, consistent mechanism for a new DOI for each tagged release, and would also provide a citation style that academics can easily use and incorporate into their work, like any other reference.  We have this set up for ASP, for example.

The reference for our most recent release is:

> Ross Beyer, Oleg Alexandrov, & ScottMcMichael. (2019). NeoGeographyToolkit/StereoPipeline: ASP 2.6.2 (Version v2.6.2). Zenodo. http://doi.org/10.5281/zenodo.3247734

And there is also a DOI that will always point to the 'latest' version, whatever that is: https://doi.org/10.5281/zenodo.598174

In the meantime, I guess I'll continue to cobble together a reference that points to some URL and maybe the most recent LPSC abstract I can find?

Thanks!

**Comment by thareUSGS** [comment]
Funny I was just mentioning this to the team this morning. I understand there is one in the works (perhaps pushed into this [special issue](https://www.mdpi.com/journal/remotesensing/special_issues/planetary_3D_mapping_remote_sensing_machine_learning) - sorry self-plug) Besides the plethora of abstracts, the reference I normally see is:

Edmundson, K. L., Cook, D. A., Thomas, O. H., Archinal, B. A., and Kirk, R. L. (2012) Jigsaw: The ISIS3 bundle adjustment for extraterrestrial photogrammetry, International Annals of Photogrammetry, Remote Sensing, and Spatial Information Sciences, I-4, 203-208. doi:10.5194/isprsannals-I-4-203-2012, URL: [https://doi.org/10.5194/isprsannals-I-4-203-2012](https://doi.org/10.5194/isprsannals-I-4-203-2012)

or direct like this ( but I would also **prefer the Zenodo** idea @jlaura )
USGS Astrogeology Research Program (2020) Integrated Software for Imagers and Spectrometers (ISIS), URL: [http://isis.astrogeology.usgs.gov](http://isis.astrogeology.usgs.gov) (last date accessed: 27 March 2020)

**other related (at least ISIS3 mentions - somewhat random assortment of citations I had on hand):**

Bennett, C.A., DellaGiustina, D.N., Becker, K.J., Becker, T.L., Edmundson, K.L., Golish, D.R., Bennett, R.J., Burke, K.N., Cue, C.N.U., Clark, B.E., Contreras, J., Deshapriya, J.D.P., Drouet d'Aubigny, C., Fitzgibbon, G., Jawin, E.R., Nolan, T.Q., Porter, N.A., Riehl, M.M., Roper, H.L., Rizk, B., Tang, Y., Zeszut, Z.. Gaskell, R.W., Palmer, E.E., Weirich, J.R., Al Asad, M.M., Philpott, L., Daly, M.G., Barnouin, O.S., Enos, H.L., Lauretta, D.S. (2020) Icarus, doi:10.1016/j.icarus.2020.113690, URL: [https://doi.org/10.1016/j.icarus.2020.113690](https://doi.org/10.1016/j.icarus.2020.113690).

Laura, J.R., Mapel, J., Hare, T. (2020) Planetary Sensor Models Interoperability using the Community Sensor Model Specification, Earth and Space Science, doi:10.1029/2019EA000713, URL: [https://doi.org/10.1029/2019EA000713](https://doi.org/10.1029/2019EA000713)

Geng, X., Xu, Q., Xing, S., Lan, C. (2020) A Generic Pushbroom Sensor Model for Planetary Photogrammetry, Earth and Space Sciences, doi:10.1029/2019EA001014, URL: [https://doi.org/10.1029/2019EA001014](https://doi.org/10.1029/2019EA001014)

Hargitai H., Willner K., Hare T. (2019) Fundamental Frameworks in Planetary Mapping: A Review. In: Hargitai H. (eds) Planetary Cartography and GIS. Lecture Notes in Geoinformation and Cartography. Springer, Cha. doi:10.1007/978-3-319-62849-3_4, URL: [10.1007/978-3-319-62849-3_4](https://doi.org/10.1007/978-3-319-62849-3_4)

Bland, M.T., Becker, T.L., Edmundson, K.L., Roatsch, T., Archinal, B.A., Takir, D., et al. (2018) A New Enceladus Global Control Network, Image Mosaic, and Updated Pointing Kernels From Cassini's 13‐Year Mission, Earth and Space Science, doi:10.1029/2018EA000399, URL: [https://doi.org/10.1029/2018EA000399](https://doi.org/10.1029/2018EA000399)

DellaGiustina, D.N., Emery, J.P., Golish, D.R., Rozitis, B., Bennett., C.A., Burke, K.N., et al. (2018) Overcoming the challenges associated with image-based mapping of small bodies in preparation for the OSIRIS-REx mission to (101955) Bennu. Earth Space Sci. 5, 929–949. URL: [https://doi.org/10.1029/2018EA000382](https://doi.org/10.1029/2018EA000382)

Tao, Y., Muller, J., Sidiropoulos, P., Xiong, S.-t., Putri, A. R. D., Walter, S. H. G., Veitch-michaelis, J., and Yershov, V. (2018) Massive stereo-based DTM production for Mars on cloud computers, Planet. Space Sci., 154, 30–58, URL: [https://doi.org/10.1016/j.pss.2018.02.01](https://doi.org/10.1016/j.pss.2018.02.01)

Hare, T.M. Skinner Jr., J.A. Kirk, R.L. (2018) Cartography Tools, In: A.P. Rossi, S. van Gasselt (eds.), Planetary Geology, Springer Praxis Books, doi:10.1007/978-3-319-65179-8_4, URL: [https://link.springer.com/chapter/10.1007%2F978-3-319-65179-8_4](https://link.springer.com/chapter/10.1007%2F978-3-319-65179-8_4)

Kirk, R.L., Howington-Kraus, E., Edmundson, K., Redding, B., Galuszka, D., Hare, T., and Gwinner, K. (2017), Community tools for cartographic and photogrammetric processing of Mars Express HRSC images, Int. Arch. Photogramm. Remote Sens. Spatial Inf. Sci., XLII-3/W1, 69-76, doi:10.5194/isprs-archives-XLII-3-W1-69-2017, URL: [https://doi.org/10.5194/isprs-archives-XLII-3-W1-69-2017](https://doi.org/10.5194/isprs-archives-XLII-3-W1-69-2017)

Sutton, S. S., Boyd, A. K., Kirk, R. L., Cook, D., Backer, J. W., Fennema, A., Heyd, R., McEwen, A. S., and Mirchandani, S. D. (2017) Correcting Spacecraft Jitter in HiRISE Images, Int. Arch. Photogramm. Remote Sens. Spatial Inf. Sci., XLII-3/W1, 141–148, doi:10.5194/isprs-archives-XLII-3-W1-141-2017, URL: [https://doi.org/10.5194/isprs-archives-XLII-3-W1-141-2017](https://doi.org/10.5194/isprs-archives-XLII-3-W1-141-2017).

Fergason, R.L., Kirk, R.L., Cushing, G., Galuszka, D. M., Golombek, M. P., Hare, T. M., Howington-Kraus, E., Kipp, D. M., Redding, B. L., (2016) Analysis of Local Slopes at the InSight Landing Site on Mars, Space Sci Rev. doi:10.1007/s11214-016-0292-x, URL: [http://link.springer.com/article/10.1007/s11214-016-0292-x](http://link.springer.com/article/10.1007/s11214-016-0292-x)

Beyer, R.A. (2015) An introduction to the data and tools of planetary geomorphology. In: Geomorphology 240, pp 137–145. doi:10.1016/j.geomorph.2014.11.022, URL: [https://doi.org/10.1016/j.geomorph.2014.11.022](https://doi.org/10.1016/j.geomorph.2014.11.022)

McEwen, A.S. Maria E.Banks, M.E., Baugh, N., Becker, K. Boyd, A., Bergstrom, A.W., Ross, B., et al. (2010) The High Resolution Imaging Science Experiment (HiRISE) during MRO’s Primary Science Phase (PSP) Icarus, 205, 2. doi:10.1016/j.icarus.2009.04.023, URL: [https://doi.org/10.1016/j.icarus.2009.04.023](https://doi.org/10.1016/j.icarus.2009.04.023)

Edwards, C. S., K. J. Nowicki, P. R. Christensen, J. Hill, N. Gorelick, and K. Murray (2011) Mosaicking of global planetary image datasets: 1. Techniques and data processing for Thermal Emission Imaging System (THEMIS) multi‐spectral data, J. Geophys. Res., 116, E10008, doi:10.1029/2011JE003857, URL: [https://doi.org/10.1029/2011JE003857](https://doi.org/10.1029/2011JE003857)

Frigeri A, Hare T, Neteler M, Coradini A, Federico C, Orosei R (2011) A working environment for digital planetary data processing and mapping using ISIS and GRASS GIS. Planet Space Sci (PSS) 59:1265–1272, Special Issue: Planetary Mapping, doi:10.1016/j.pss.2010.12.008, URL: [https://doi.org/10.1016/j.pss.2010.12.008](https://doi.org/10.1016/j.pss.2010.12.008)

Kirk, R. L., Howington-Kraus, E., Rosiek, M. R., Anderson, J. A., Archinal, B. A., Becker, K. J., Cook, D. A., Galuszka, D. M., Geissler, P. E., Hare, T. M., Holmberg, I. M., Keszthelyi, L. P., Redding, B. L., Delamere, A. W., Gallagher, D., Chapel, J. D., Eliason, E. M., King, R., McEwen, A. S., and the HiRISE Team (2008) Ultrahigh resolution topographic mapping of Mars with MRO HiRISE stereo images: Meterscale slopes of candidate Phoenix landing sites, J. Geophys. Res., 113, E00A24, doi:10.1029/2007JE003000. URL: [https://doi.org/10.1029/2007JE003000](https://doi.org/10.1029/2007JE003000)

And of course your ASP reference above (and another for you -- w/ an ISIS mention):

Hepburn, A. J., Holt, T., Hubbard, B., and Ng, F. (2019) Creating HiRISE digital elevation models for Mars using the open-source Ames Stereo Pipeline, Geosci. Instrum. Method. Data Syst., 8, 293–313, doi:10.5194/gi-8-293-2019, URL: [https://doi.org/10.5194/gi-8-293-2019](https://doi.org/10.5194/gi-8-293-2019)

**Comment by jlaura** [comment]
Here is the existing Zenodo link: https://zenodo.org/record/3697255 with the associated DOI for 3.10.1 (https://doi.org/10.5281/zenodo.3697255) and 4.0.1 (https://doi.org/10.5281/zenodo.3697216).  We have DOIs all the way back to 3.6.1. Here is the [extra long link that might not work](https://zenodo.org/search?page=1&size=20&q=conceptrecid:%222563341%22&sort=-version&all_versions=True#).

This is not in the README.md at this point, so super understandable that no one other than me knew it existed.

**Comment by rbeyer** [comment]
@thareUSGS had some good comments in #3819 about the style of the citation on Zenodo.  It definitely needs some clean-up.

**Comment by thareUSGS** [comment]
Moving comments to here (sorry Ross).

In Zenodo title has "Releas". Author list is a little odd, e.g. isis3mgr. Perhaps list in alpha order or should we just use Astrogeology Team (or Science Center) and link to contributor page...

Currently the recommended cite is (very odd):
Tracie Sucharski, Jesse Mapel, jcwbacker, Kristin, Kaitlyn Lee, AgoinsUSGS, … Ross Beyer. (2020, March 4). USGS-Astrogeology/ISIS3: ISIS3.10.1 Public Releas (Version 3.10.1). Zenodo. http://doi.org/10.5281/zenodo.3697255

Can we also acknowledge NASA or funding opp.

I guess it is a good place to put release notes - or at least link to something. See ASP:
https://zenodo.org/record/3247734#.XoTAQohKgkk

nice location for citations too.

**Comment by jlaura** [comment]
> Moving here comments to here (sorry Ross).
> 
> In Zenodo title has "Releas". Author list is a little odd, e.g. isis3mgr. Perhaps list in alpha order or should we just use Astrogeology Team (or Science Center) and link to contributor page...

Fixed release. The authors were auto-pulling from the repo. I altered to be regular, current,  committers followed by external or retired committers.

> Can we also acknowledge NASA or funding opp.

Not from what I can see. Zenodo links to EU, NSF, etc., but not NASA. 


> I guess it is a good place to put release notes - or at least link to something. See ASP:
> https://zenodo.org/record/3247734#.XoTAQohKgkk

I would rather not unless it is 100% automated. We already post release notes so adding another step to a website that honestly, I was the only one that knew about seems redundant.

**Comment by jessemapel** [comment]
> I would rather not unless it is 100% automated. We already post release notes so adding another step to a website that honestly, I was the only one that knew about seems redundant.

If we move release notes into the repository itself, then we could easily do this. Maybe something to tackle as we look into moving docs around next year.

**Comment by jlaura** [comment]
After manually reordering the author list for 3.10.1, I see that that change did/does not propagate to 4.0.1, etc. 

Looks like we might need an Authors.rst a la [this one](https://github.com/zenodo/zenodo/blob/master/AUTHORS.rst). For now, I am not going to manually reorder.

**Comment by rbeyer** [comment]
Here is what Zenodo says about authors:

> Zenodo automatically extracts metadata about your repository from GitHub APIs. For example, the authors are determined from the repository's contributor statistics. The automatic extraction is _**solely a best guess**_. Add a `.zenodo.json` file the root of your repository to explicitly define the metadata. The format of file is the same as for our REST API.

They point to this example: https://github.com/geodynamics/aspect/blob/master/.zenodo.json

Yes, we need an AUTHORS file, but it is also likely that we need to maintain a `.zenodo.json` file.  I know that this may seem like fussy busy-work, but as an academic that wants to properly acknowledge ISIS in my published papers for posterity, I feel pretty strongly about getting this 'right' for ISIS (whatever we decide that means).

On the plus side, odds are good that we can probably automatically generate one from the other, and once someone commits an AUTHORS file, I'll write up something to make a `.zenodo.json' file from it.  Maybe we can even automate that on commit of a new AUTHORS file, but first things, first.

**Comment by jessemapel** [comment]
I am going to close this as the answer is cite the Zenodo version you use in your processing/the latest release.
