### ISSUE TITLE
stats crashes in batch mode after 1018 lines

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#3842]
**ISIS version(s) affected**: 4.1.0_RC1

**Description**  
stats fails with unable to open the FROM cube after 1018 lines of batch mode. lsof shows the input cubes are not being closed after each loop of the batch file processing.

See #3841 for a similar problem

**How to reproduce**  
Run ulimit -n to see what your open file limit is
Run stats with -batch=some_file with more lines than your limit of open files

**Possible Solution**  
Close all open files before returning

**Additional context**

**Comment by jessemapel** [comment]
stats has a memory leak at https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/apps/stats/stats.cpp#L26

It doesn't ever delete the cube object.

**Comment by scsides** [comment]
Unable to repeate
