### ISSUE TITLE
Add automatic env setup for multiple conda envs

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#3847]
PR upcoming.

Just a quick question:

Is use of pathlib.Path in the `isis3VarInit.py` not possible b/c your minimum requirement seems to indicate in the script that you still allow 3.2 and 3.3? That, despite the fact that the current conda install requirements asks for Python 3.6 ?

IIUC, as this script is run in a Python 3.6 environment if the instructions are followed, we could change this version check here:
https://github.com/USGS-Astrogeology/ISIS3/blob/7e8d228671a25c25a9c628627e09931eced521a0/isis/scripts/isis3VarInit.py#L60 
to change to a minimum Python 3.6 for consistency?

**Comment by michaelaye** [comment]
FYI, pathlib is available starting from Python 3.4, so I could settle for that? ;)

**Comment by jessemapel** [comment]
pathlib seems fine. The script requiring a minimum of 3.2 is just for the format calls. ISIS is really tied to 3.6+

**Comment by rbeyer** [comment]
If you were going to rewrite `isis3VarInit.py` today, I think you could certainly assume a Python 3.6 base level, since we *know* that the ISIS environment is tied to it.

**Comment by michaelaye** [comment]
i was afraid that the script is maybe being used outside conda somewhere and that's why it needs to support 3.3 to 3.5?

**Comment by rbeyer** [comment]
I don't think so.
