### ISSUE TITLE
Potential problem: name of env_vars conda script

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#3848]
I think we should rename the `env_vars.{sh|csh|fish}` scripts to `isis_env_vars.{...}` because other conda packages might have the same idea of calling their scripts like that.
Adding `isis` to the name makes a name clash very unlikely.

**Comment by rbeyer** [comment]
Other packages (GDAL and PROJ, for example) would seem to imply that they should be
```
isis-{activate|deactivate}.{sh|csh|fish}
```

Changing it is probably a good idea, but will require a thorough documentation sweep.

**Comment by michaelaye** [comment]
GitHub search through this repo (is it reliable?) only shows 2 appearences of `env_vars`, one in the script and one in the README.
