### ISSUE TITLE
Spiceinit segmentation fault on Voyager 2 images isis4.0.1

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#3849]
**ISIS version(s) affected**: 
isis4.0.1

This does not seem to affect isis3.10.0. I didn't check other versions.

**Description**  
Running spiceinit on Voyager 2 images of Triton in ISIS4.0.1 results in a segmentation fault for some cubes. It isn't obvious to me why certain cubes fail and it's not always the same cube (running in batch). Spiceinit runs fine on the same cubes in ISIS3.10.0.

**How to reproduce**  
Go to /work/users/mbland/Triton-Voyager/kernels/Bland_200421/Ground/test/

Spiceinit fails with 'Segmentation fault (core dumped)' on about the third image in the list. 

Note: I'm puttying into astrovm5.

run: 
spiceinit -batchlist=root.lis from=\$1.cub

**Possible Solution**  

**Additional context**  
For context, I was checking kernels that Ethan Smith made so I originally thought this was a problem with his kernels. However, the issue occurs with the defaults

**Comment by jessemapel** [comment]
@blandoplanet Have you be able to spiceinit the seg faulting cube by itself? We've had some other issues with files not being properly closed when running in batchlist.

**Comment by blandoplanet** [comment]
Thanks @jessemapel. You are correct. Running spiceinit on individual images (including the ones that failed) works.

**Comment by jessemapel** [comment]
See https://github.com/USGS-Astrogeology/ale/pull/358

**Comment by scsides** [comment]
The issue was in the ALE library and the PR has been merged. This issues looks to be isolated to the batch mode for spiceinit only. No other apps should see this problem.
