### ISSUE TITLE
Add Local Time band to phocube 

### ISSUE THREAD

**Issue by csedwar** [DOI-USGS/ISIS3#3850]
**Description**  
Add local time band output to phocube. hocube already calculates numerous photometric parameters, for non-local time loced SC or observations of smaller bodies (e.g. Phobos, Bennu) using SPICE to also return the local solar time on a per pixel basis would be valuable.

**Example**  
phocube from=test.cub to=test.pho.cub localtime=yes
https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/phocube/phocube.html

**Comment by lavalaz** [comment]
I too would use this option if it were available.
