### ISSUE TITLE
Qview Slowdown

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#3854]
**ISIS version(s) affected**: 4 and up

**Description**  
There is a noticeable slowdown when opening cubes in qview in versions of ISIS4 vs ISIS3, specifically when look at certain datasets (Notably Galileo data).

**How to reproduce**  
Grab these files:
/work/projects/EuropaBasemap/lweller/Galileo/FindFeatures/Island1/FindFeatures_ImprovedSpice/Observations/19ESREGMAP01/*cub (uncontrolled an controlled mosaic)

/work/projects/EuropaBasemap/lweller/Galileo/FindFeatures/Island1/FindFeatures_ImprovedSpice/Observations/19ESREGMAP01/12ESPWYCOL01_Island1V3.lis

While I was sitting in this directory, I ran qview in the following way from the command line:

qview *cub (to pop open the mosaics)
qview 12ESPWYCOL01_Island1V3.lis ( to pop open the level 1’s - included full path)
I typically open images from the command line when working with qview. I don’t know that the mosaics took any longer to load, but the level 1’s definitely did. Turns out these lev1’s are updated, but I’m not sure it matters. There is a list of spiced files (12ESPWYCOL01_Island1.lis) that opens just as slowly under isis4. Possibly even slower than the updated images.

**Possible Solution**  
¯\\\_(ツ)\_/¯

**Additional context**  
[Astro Discuss Post](https://astrodiscuss.usgs.gov/t/q-app-problems-under-isis4-1-0-rc2/397/5)

There has also been additional testing with Themis IR data and MRO CTX data, both do not seem to exhibit this problem. Both data sets only exhibit slight, insignificant changes in load times, maybe a few seconds difference when comparing ISIS versions.

**Comment by jessemapel** [comment]
I am concerned about ALE::load being called and attempting to load the updated data off of the cubes. We may need to check that all of the ISIS label ISIS spice drivers are properly erroring if the mission/instrument names don't match.

**Comment by lwellerastro** [comment]
Just for the record here, I tested both qview and qnet  (did a variety of things in both) under a temporary build and it all looks good.  Not only are loads fast, but I'm pretty sure they are faster than before.  Thanks!
