### ISSUE TITLE
map2cam with multiband level0 image

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3856]
**ISIS version(s) affected**: x.y.z
4.0.0

**Description**  

Attached error message when using band N as the match in map2cam, where N is greater than 1

**How to reproduce**  

- ingest LROC WAC image
- run spiceinit
- run map2cam to match a map/mosaic to the unprojected WAC image
- qview will show that output is aligned with the first band but not with the subsequent bands
- rerun map2cam with the +2 (or more) after the WAC image so the map will align with band 2 (or later).
- get error message

**Possible Solution**  

Note: map projecting the WAC image to match the map is not an option for me because I need the statistical distribution of DN values of the WAC image to be strictly preserved. Yes, NN interpolation will keep the DN values fixed, but the number of pixels with a given DN value will be altered. 

**Additional context**  

![image](https://user-images.githubusercontent.com/43523454/80843108-42d94500-8bb8-11ea-9c5c-a61db613db55.png)

**Comment by rbeyer** [comment]
>     * qview will show that output is aligned with the first band but not with the subsequent bands

So are you saying that map2cam only 'unprojects' the first band of a multiband image, and not the others?  Wild.

Although this requires an extra step, you could use the ISIS `explode` command to take your multi-band map-projected image and convert it into a pile of individual, 1-band cubes, and then `map2cam` just the one you need.  But if you need *all* of them, that's inconvenient (but could be scripted!).

**Comment by lavalaz** [comment]
Not exactly - the level0 cub is the one with multiple bands - and the geometry associated with each band is different.  cam2map uses the geometry from the first band without giving me a way to use the geometry from other bands.  Running 'explode' on the level0 cub will work but there is a geometric progression in the number of filenames I need to track in the script and expanding by a factor of 5 this early in the process means I probably need a script to write the script.

**Comment by jessemapel** [comment]
This looks like an issue where map2cam wants to set the *physical* band and the LROWAC sensor model wants to set the *virtual* band. Physical bands are the actual bands in the file and virtual bands are how many bands are you using. So, if your LROWAC image has 5 actual bands and you specify `.cub+3` it will have 5 physical bands and 1 virtual band.

The [band change function](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/lro/objs/LroWideAngleCamera/LroWideAngleCamera.cpp#L243) in the sensor model expects virtual bands, but the [band change function](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/apps/map2cam/map2cam.cpp#L125) in map2cam converts virtual bands to physical bands. I'm not sure which is correct. We need to check all of the band-dependent sensor models and see if they expect physical bands or virtual bands in their band change function.

**Comment by lavalaz** [comment]
Tried to use explode to get single band images.  No joy - see new ticket...

**Comment by jessemapel** [comment]
@lavalaz Can you specify which new ticket?

**Comment by jlaura** [comment]
#3858

**Comment by Kelvinrr** [comment]
@lavalaz that error seems to be an issue with map2cam not correctly using virtual bands, after applying the virtual bands map2cam attempts to use physical downstream. This means the image effectively has one band, therefore, if you attempt to use a band number greater than 2, you get that error.  

I'll try to verify this for a bit then PR in the change, but this fix should make it possible to process bands separately as expected.
