### ISSUE TITLE
output from map2cam garbled when used with LROC WAC

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3858]
**ISIS version(s) affected**: x.y.z
4.0.0
**Description**  

Output from map2cam is jumbled with adjacent pixels in the output not coming from adjacent pixels in the input
**How to reproduce**  

Get an EDR (like M1295467643CE.IMG)
ingest  (i.e., _lrowac2isis_ and _spiceinit_), calibrate (i.e., _lrowaccal_, but you probably can skip this step if you want), then _explode_ so you have single-band .cub files
take your favorite map projected .cub file
run _map2cam_ with from=map-projected.cub match=exploded.cub to=map2cam-output.cub
open in qview
If you are familiar with the input map-projected .cub, you should immediately see a problem. But if you want to dig in, use the finder tool and click on pixels going up or down a column in the output.  The corresponding pixel will move correctly for a few pixels, then jump in the opposite direction as if the order of the framelets is mixed up.  
**Possible Solution**  

**Additional context**  

Screen shots of qview of input, map, and output files.
![image](https://user-images.githubusercontent.com/43523454/80926899-ecead580-8d4e-11ea-812e-4981b9b3b5a9.png)

**Comment by jessemapel** [comment]
@lavalaz This appears to be an issue with how map2cam handles framelets from pushbroom sensors. What should the output image look like? Should it contain only the framelets present in the match cube? Should it contain all framelets? Should it spit out two files, one for even and one for odd?

**Comment by lavalaz** [comment]
It should have all the framelets in the match cub.  Definitely not split into even and odd - just match the match file.

**Comment by AustinSanders** [comment]
I borrowed some logic from cam2map and somehow made the garbling worse:

This image shows input | match | output
<img width="1243" alt="Screen Shot 2020-09-10 at 9 45 45 AM" src="https://user-images.githubusercontent.com/3751180/92765824-899b3080-f34a-11ea-972a-0e95765ae363.png">

**Comment by lavalaz** [comment]
I think something is off with the match file (explode.band0001.cub) with the individual framelets flipped?

**Comment by jessemapel** [comment]
@AustinSanders Can you be more specific about what you did. Did you just copy and paste that [block of code](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/apps/cam2map/cam2map.cpp#L380) we talked about and swap the input cube for the match cube?

**Comment by AustinSanders** [comment]
@jessemapel Yes --  the change just involved pulling the block of code into map2cam and swapping variables.  I changed input cube for match cube, and I replaced incam with outcam, where outcam is the camera from the match cube.


I'm not sure if it's important, but in terms of the processing pipeline, I created a map projected cube (lrowac2isis -> spiceinit -> lrowaccal -> cam2map) then tried to map2cam it using the pipeline that @lavalaz describes in the original issue.

I originally got a band error (I forget the exact text, but it was something about selecting a physical band (2) outside of the allowable 1 - 1 range).  This was resolved by using ```from=~/lrowac/proj.cub+1``` to select only the first band from the input.

**Comment by Kelvinrr** [comment]
@AustinSanders That band error should be fixed by https://github.com/USGS-Astrogeology/ISIS3/pull/4008 so try pulling from dev and trying a new build. 

Looking into this as well, I can't seem to replicate. 

Output seems correct? Both exploded and +1/+2 cases. 

Below is input | match | output 
![Screen Shot 2020-09-10 at 12 48 43 PM](https://user-images.githubusercontent.com/13245976/92794101-11416900-f364-11ea-9acc-45010c59c224.png)

**Comment by lavalaz** [comment]
Looks great to my eyes...!

**Comment by Kelvinrr** [comment]
I decided to revert #4008 locally to see if that changed fixed anything, still wasn't able to replicate. @AustinSanders @lavalaz, can you send me paths to the specific files you used?

**Comment by AustinSanders** [comment]
@Kelvinrr 
    
IMG used to make the projected cub, which served as input (from= in map2cam) : /pds_san/PDS_Archive/Lunar_Reconnaissance_Orbiter/LROC/EDR/LROLRC_0001/DATA/MAP/2009365/WAC/M116906393CE.IMG
    
match=
/pds_san/PDS_Archive/Lunar_Reconnaissance_Orbiter/LROC/EDR/LROLRC_0001/DATA/MAP/2009365/WAC/M116906354CE.IMG

**Comment by Kelvinrr** [comment]
@AustinSanders's example gave me nulls as they do not project onto each other. 

Attempted again with a DEM, as expected, the framlets seem to have garbled the output. 

input (mosaic) | match | output
![Screen Shot 2020-09-11 at 10 18 37 AM](https://user-images.githubusercontent.com/13245976/92954598-8c645700-f418-11ea-8486-4e74ff51ea99.png)

match | output 
![Screen Shot 2020-09-11 at 10 29 00 AM](https://user-images.githubusercontent.com/13245976/92955254-ac484a80-f419-11ea-870e-3b14a9655438.png)


@lavalaz The part I am still mixed on is what the expected behavior should be? It seems this is expected behavior for using a pushbroom camera as your match?

**Comment by lavalaz** [comment]
This looks good.  Thank you!

**Comment by Kelvinrr** [comment]
@lavalaz just to confirm, would an acceptable close out to this be better documentation in map2cam of what you can expect out of using pushbroom images?

**Comment by lavalaz** [comment]
No, the issue was not documentation.  But something very basic has been fixed and the output is no longer garbled.  That is the reason I think this can be closed.  Thank you!!!

**Comment by Kelvinrr** [comment]
@lavalaz closed as you seem happy with the outcome, but just to make it clear, my output did replicate the issue you were seeing initially: 

Changed the stretch to make it more obvious
![Screen Shot 2020-09-11 at 11 53 10 AM](https://user-images.githubusercontent.com/13245976/92962674-254d9f00-f426-11ea-923c-9b45a01caf8e.png)

I think there is reason to open a separate issue for adding specific pushbroom functionality in map2cam. Specifically, what to do with with framelets in pushbroom cameras (whether to work with even, odd, or all framelets in the image).
