### ISSUE TITLE
isis2ascii no space between values if a value is negative

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3859]
**ISIS version(s) affected**: x.y.z
4.0.0 and 3.9.x

**Description**  

isis2ascii uses spaces to delimit between output values.  there is no space between successive output real numbers if the number is negative

**How to reproduce**  

get a .cub with negative DN values.
run isis2ascii
try to ingest the output as a space-delimeted file
get fatal error message

**Possible Solution**  

**Additional context**  

Why would there be negative DN values in a .cub?  That is inconcievable!
![image](https://user-images.githubusercontent.com/43523454/80927046-0fc9b980-8d50-11ea-9de6-acb52b8bc799.png)

**Comment by jessemapel** [comment]
@lavalaz What bit type was the cube you saw this in?

**Comment by lavalaz** [comment]
Default. I think that means 32-bit...

László Kestay (Keszthelyi)
Research Geologist
USGS Astrogeology
________________________________

**Comment by jessemapel** [comment]
In the image labels what does it say under the Pixels ground? Here's a CTX label for example:

    Object = IsisCube
      Object = Core
        StartByte   = 65537
        Format      = Tile
        TileSamples = 500
        TileLines   = 512

        Group = Dimensions
          Samples = 5000
          Lines   = 8192
          Bands   = 1
        End_Group

        Group = Pixels
          Type       = Real
          ByteOrder  = Lsb
          Base       = 0.0
          Multiplier = 1.0
        End_Group
      End_Object

Under the Pixels group it specifies Real, which means 32-bit.

**Comment by lavalaz** [comment]
Object = IsisCube
  Object = Core
    StartByte   = 65537
    Format      = Tile
    TileSamples = 202
    TileLines   = 212

    Group = Dimensions
      Samples = 202
      Lines   = 212
      Bands   = 10
    End_Group

    Group = Pixels
      Type       = Real
      ByteOrder  = Lsb
      Base       = 0.0
      Multiplier = 1.0
    End_Group
  End_Object
