### ISSUE TITLE
lrowaccal outputs negative DN values

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3860]
**ISIS version(s) affected**: x.y.z
3.9.x and 4.0.0

**Description**  

Negative I/F values are physically impossible - they mean the surface is darker than a black hole. 

**How to reproduce**  

Take M102214493CE.IMG
ingest, run lrowaccal
you will find negative DN values

**Possible Solution**  

I suggest simply setting the negative values to 0.00000000 (they are small negative values)

**Additional context**

**Comment by jlaura** [comment]
This issue was worked on in the last support sprint and the LROC team was contacted. The result was no code change, but a documentation update. @scsides I think you worked on this? Are the docs updated or is this a candidate to slot at the end of this month?

**Comment by scsides** [comment]
Outside contributor is writing the text to be added to the program's description. We will add that to the documentation and close the issue when it is ready.
