### ISSUE TITLE
isis2ascii should just use spaces as the delimiter, even in the header

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3862]
**Description**  

Replace the colons (":") in the header output by isis2ascii.  
**Example**  

Reading in a space-delimited ascii file is pretty standard.  But the colons in the header portion that isis2ascii writes are not usually recognized by default as delimiters.  While one can find a number of solutions to this, it seems there is no reason to make the user have to jump through these hoops before using the output from isis2ascii.

**Comment by jessemapel** [comment]
The header of the output ascii file isn't columnar data, so it can really be any format. Do you have any suggestions for how the header should be handled? Just spaces?

**Comment by lavalaz** [comment]
Spaces is easiest for me. Thanks!

László Kestay (Keszthelyi)
Research Geologist
USGS Astrogeology
________________________________
