### ISSUE TITLE
cropspecial not quit while in -batchlist mode if a file has no valid pixels

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3863]
**Description**  

cropspecial will move on to the next file in -batchlist if a file has no valid pixels (and therefor no output is made)

**Example**  

Example: try to process 900 .cub files using the -batchlist option.  First file in the list is all NULL. Currently processing of all 900 images fails.  Would be nice if the processing would carry on looking through the full list instead of bailing.

**Comment by jessemapel** [comment]
The issue here is what should cropspecial do when there are no valid pixels in a cube? Batchlist by design fails on the first error, so to make this work cropspecial would need to not error when the input cube has no valid pixels.

Another option would be to implement a batchlist mode that continues on errors. I'm not sure how much work this would be, but it's another option.

**Comment by lavalaz** [comment]
Yes, that is the issue.
Either change works for me.  The latter option seems to open up more possibilities, both good and bad.

**Comment by lwellerastro** [comment]
@lavalaz, there is an option to continue on error for -batchlist.  Try -onerror=continue.

>  -onerror Parameter
> 
> This parameter can be used with all parameters, and the -batchlist and -errlist reserved parameters. If the continue option is selected, it allows the user to run the program on all the files in the batch list file without stopping until all the command lines are executed. Any errors that were encountered are reported to the error list file. If the abort option is selected or it is run without being set (the default is abort), the program will halt when the first error occurs.
> 
> highpass -batchlist=batchList.txt from=\$1\$2 to=\$1/hpf/\$2 lines=5 samples=5 -onerror=continue
> 
> In this example, any errors that occur will be printed out to the screen and the program will continue to the next command. The only record of the failures will be in the print.prt file. 

[https://isis.astrogeology.usgs.gov/documents/CommandLine/CommandLine.html#-onerror%20Parameter](url)

**Comment by lavalaz** [comment]
Sounds perfect!

László Kestay (Keszthelyi)
Research Geologist
USGS Astrogeology
________________________________
