### ISSUE TITLE
mappt with "usecoordlist" option like campt

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3872]
**Description**  

campt has a very useful option to use a list of coordinates so you don't need to call campt over and over to sample an area.  mappt does not have this option but it would be just as useful there.
**Example**  

"usecoordlist" option in campt is the example.

**Comment by jlaura** [comment]
@Kelvinrr Can we close?

**Comment by jessemapel** [comment]
This is in the 4.2.0 release. closing
