### ISSUE TITLE
Issues with point perspective projection "dist" parameter

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3873]
**Description**

Point perspective projections use the "dist" parameter.  This is supposed to be the distance from the center of the body.  But I cannot tell what the units are.  Units are not to be found in any of the documentation I can access.  When I try to project assuming either meters or kilometers I do not get results that allow me to tell which is correct.    
**Suggested Edit**

Add the units to the documentation associated with map template's discussion of parameters that go with different projections. 
Thanks!

**Comment by lavalaz** [comment]
When I run cam2map using point perspective with different values for dist, I get the most reasonably looking results if I assume that dist is actually the distance from the surface, not the center of the body.  However, not knowing what the units are, it is a bit hard to tell.  I hesitate to open another ticket based until this issue is solved, but, if you are in the code anyway, you might want to double check that the distance is indeed from the center of the body and not the surface (which is what the documentation very clearly says it is).

**Comment by jessemapel** [comment]
The point perspective template specifies this as distance to the center of the body and that it is in meters.

Can you provide data to reproduce the weird results you're seeing with distance to surface vs. distance to center?

**Comment by thareUSGS** [comment]
Jesse I'm not sure it is in meters from the center of the body. I actually think it is in kilometers from the center of the body. When we mapped ISIS's version of this projection to PROJ, often called Near-side Perspective, there needed to be a conversion from kilometers to meters and an offset from the distance from the center of the body to distance from the surface (as parameterized in [PROJ](https://proj.org/operations/projections/nsper.html) and [Arc](https://pro.arcgis.com/en/pro-app/help/mapping/properties/vertical-near-side-perspective.htm)). Note this currently simply uses the semi-major radius for the conversion to height from the surface (perhaps we might need an update to an elliptical calculation).

Just for reference here is current mapping from ISIS to PROJ. If this changes in ISIS we will need to update the PROJ/GDAL code.

mapping ISIS to PROJ: https://github.com/OSGeo/gdal/blob/691efac43e6f7c8f249b36c7d0d2dd5eeb101ae1/gdal/frmts/pds/isis3dataset.cpp#L1969

mapping PROJ to ISIS: https://github.com/OSGeo/gdal/blob/691efac43e6f7c8f249b36c7d0d2dd5eeb101ae1/gdal/frmts/pds/isis3dataset.cpp#L2936

**Comment by lavalaz** [comment]
I don't have examples handy at the moment.  But what I did was use _dist_=1.0 and I got an image that looked like I was about a kilometer above the surface (the horizon was a few kilometers away).  Then I put in a value for _dist_ that was the radius of the planet in meters + 1000.0 and in kilometers +1.0.  When I input those values, I seemed to be a good distance away from the surface - I could see most of the hemisphere that was facing me.  If _dist_ was the distance from the center of the body, in meters or kilometers, one of these two runs should have made it appear I was close to the surface.  But they both seemed to be far away.

**Comment by jessemapel** [comment]
Quickly glancing at the code, it looks like it's always in kilometers and is actually the distance to the surface of the planet.

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/PointPerspective/PointPerspective.cpp#L94

I don't think we're going to change what the value actually means, just better document it.

**Comment by lavalaz** [comment]
![image](https://user-images.githubusercontent.com/43523454/82353832-d088a300-99b4-11ea-803f-cec05b8c1c41.png)
Just FYI, this is where I was expecting to see units in the documentation and am not finding it.

**Comment by lavalaz** [comment]
Agreed, no need to change how the code works, just document correctly.  Thank you!

**Comment by Kelvinrr** [comment]
PR is up for the doc change. Just to double check @jessemapel how did you confirm that it's distance to target surface? KM is obviously correct, but the inline comment on the line you link seems to imply otherwise as well. If that comment is also incorrect I can include it in my changes.

**Comment by jessemapel** [comment]
Looking back at everything I don't know where I got distance to the surface from. Looking at the code and the template again, it looks like it is actually the distance to the center of the body.
