### ISSUE TITLE
Point Perspective latitude bug?

### ISSUE THREAD

**Issue by thareUSGS** [DOI-USGS/ISIS3#3874]
This feels like a bug.
https://github.com/USGS-Astrogeology/ISIS3/blob/2cac1bace2784e85ae322441f9a2dc3d5a8e0e96/isis/src/base/objs/PointPerspective/PointPerspective.cpp#L301
shouldn't it be...?
>     if (IsPlanetographic()) m_latitude = ToPlanetocentric(m_latitude);

**Comment by jessemapel** [comment]
I think this is correct. The math above that calculates a PlanetoGraphic latitude and if the projection is in planetocentric, then it needs to convert. The `IsPlanetographic` function is checking the system for the projection and not the system for the compute latitude.

**Comment by thareUSGS** [comment]
Ah I get the logic - thanks for checking and closing.
