### ISSUE TITLE
How did you set up issue templates chooser?

### ISSUE THREAD

**Issue by chbrandt** [DOI-USGS/ISIS3#3879]
@jlaura @jessemapel I would like to set up a issues template chooser like you had done on this repo:
![image](https://user-images.githubusercontent.com/482051/82891462-119d2c00-9f4e-11ea-8850-fadca31697b5.png)

But I couldn't find it. I found that infor on [github docs](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository), but doesn't look you have succh _config.yml_ ... so I'm a bit confused here.

Do you remember/have at hand those instructions?

**Comment by jlaura** [comment]
@chbrandt We have the templates setup in the .github folder [here](https://github.com/USGS-Astrogeology/ISIS3/tree/dev/.github). GitHub.com then knows how to render these.

**Comment by chbrandt** [comment]
Got it! Thanks @jlaura
