### ISSUE TITLE
Add "gears" to hist GUI to see what the computed min/max values are

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3880]
**Description**  

It would be helpful to see what the computed min and max values are from within the _hist_ GUI.  These values would help one pick a reasonable value for NBINS and also give an indication that there are some crazy outliers hiding in the data ready to mess things up.  
**Example**  

I'm thinking of the little clickable symbol that looks like a gear that we have in applications like _maptemplate_ or _cam2map_.

**Comment by jlaura** [comment]
@scsides Looks like this should be closed? Please re-open if not!
