### ISSUE TITLE
Cannot install ISISwith anaconda on windows 10

### ISSUE THREAD

**Issue by eldarnoe** [DOI-USGS/ISIS3#3884]
Hi,  I am following the install instructions on 

https://github.com/USGS-Astrogeology/ISIS3#installation

I can succesfully execute the instructions until the command 

conda install -c usgs-astrogeology isis

at which point I get:
_________________________________________________________________________
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - isis

Current channels:

  - https://conda.anaconda.org/usgs-astrogeology/win-64
  - https://conda.anaconda.org/usgs-astrogeology/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
_____________________________________________________________________________

when I run conda config --show channels
I get

(isis) PS D:\> conda config --show channels
channels:
  - usgs-astrogeology
  - conda-forge
  - defaults

So I'm not sure what is wrong.  Any suggestions?

Thanks

**Comment by jlaura** [comment]
@eldarnoe Thanks for the report!

We do not current support installation on windows. We do support a bunch of other OSes though. See [here](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#operating-system-requirements) for the listing.

Another option might be to try the windows subsystem. It is a community effort, i.e., we do have docs, etc. for installing on windows. You could checkout [this blog post](http://planetarygis.blogspot.com/2017/07/isis3-on-windows-10-bash.html) if you are interested in that approach. If you do go this route and want to submit a PR with improved docs for installation on the WSL, that would be amazing.
