### ISSUE TITLE
Overly strict 3.6 Python requirement

### ISSUE THREAD

**Issue by AndrewAnnex** [DOI-USGS/ISIS3#3885]
**ISIS version(s) affected**: 3.9.0, 3.8.1

**Description**  
The conda recipe for ISIS3 seems to specify a strict 3.6.0 python version requirement but 3.6.10 is now available. 

In the recipe I see: “   - python==3.6”

Which returns errors saying that 3.6 is required.
**How to reproduce**  
Make a new environment specifying any minor version newer than 3.6.0

**Possible Solution**  
`python>=3.6`
I claim no expertise with how ISIS3 works, but I doubt it would break anything to support newer and more secure versions of 3.6, possibly 3.7 and 3.8 as well. My impression was that conda was used to distribute ISIS3, not for runtime isis capabilities.
**Additional context**  
Ironically, in my various attempts to fix my now likely hosed conda environment, I saw conda refusing to install 36_5 isis 3 because of a dependency not provided for cspice-66-h470a237_3 needed by ISIS3-3.6.0-py36_5 which is listed as broken by conda forge.

**Comment by jessemapel** [comment]
The Python 3.6 requirement is there right now because of the handful of dependencies that we provide specifically for ISIS. I think easing up for 3.6+ would be good, especially as conda-forge is moving to largely 3.8

**Comment by AndrewAnnex** [comment]
@jessemapel interestingly I just noticed python has been removed from being explicitly listed in the dev branch recipe meta.yaml https://github.com/USGS-Astrogeology/ISIS3/blob/dev/recipe/meta.yaml. Does that mean this issue is fully resolved in that newer releases of ISIS don't depend on python or is the python dependency now transitive?

**Comment by jessemapel** [comment]
It is transitive because of the handful of dependencies that are specially built. ISIS itself never had an actual requirement for Python 3.6, just 3+.

**Comment by AndrewAnnex** [comment]
hmm, okay so it sounds like @jessemapel that this issue can be closed? If other dependencies required 3+ but the old yaml/the main readme still specify 3.6 then maybe we should close this issue, but also possibly update the readme installation instructions to say 3.8 or not include python at all.

**Comment by jessemapel** [comment]
I'm leaving this issue open because the problem is with the dependency builds, but those dependency builds don't have their own repo.

**Comment by rbeyer** [comment]
So Python 3.6 has an "End of Support" this December.  More importantly, all versions of ISIS (including the most recent 5.0.0) are pinned to Python 3.6.0, but the latest version of 3.6 is 3.6.13.  This means that there are 13 bug-and-security fixes to that version of Python that aren't accommodated.  One cannot install ISIS even with Python 3.6.1!

When is this pinning going to end?

**Comment by AndrewAnnex** [comment]
at the very least, updating the pin to allow 3.6.13 should be easy....

**Comment by jlaura** [comment]
@AndrewAnnex Want to give it a test and put in a PR?

**Comment by AndrewAnnex** [comment]
@jlaura I am not even sure where to begin because I can't even see where the 3.6 requirement is specified in the repository (https://github.com/USGS-Astrogeology/ISIS3/search?p=1&q=python%3D3.6). Ironically I see references to python 3.6.7, 3.7 and 3.8 within https://anaconda.org/usgs-astrogeology/isis/5.0.0/download/osx-64/isis-5.0.0-0.tar.bz2. Is the recipe updated dynamically during the build process?  Maybe this 3.6 requirement is only for older versions of ISIS that ASP depends on?

**Comment by jlaura** [comment]
https://github.com/USGS-Astrogeology/isis3_dependencies/blob/32353d323218a780951fa6f0347383a01ad1a035/meta/conda_build_config.yaml

It is because of the third party dependencies that ISIS has on packages that we have maintained and are working on not maintaining. This is why 'at the very least  updating the pin to allow 3.6.13 should be easy...' is not something that we know is all that easy. If it were, we would do it.

Feel free to attempt to pin in the ISIS repository environment.yml and report back the results.

**Comment by AustinSanders** [comment]
@acpaquette Can this be closed per the merge of #4634

**Comment by acpaquette** [comment]
@AustinSanders Yes, I believe this can be closed as of #4634
