### ISSUE TITLE
conda and isis headers

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#3892]
I installed the latest isis with conda, and I see that the isis headers are not shipped, but plenty of others are. Is there a reason for this? It would make the task of building Ames Stereo Pipeline easier if the isis headers were included as well. I can work around that, but I wonder what the plan is going forward.

**Comment by jessemapel** [comment]
The headers should be shipped with the library. This looks like a bug with how they are installed in cmake.

**Comment by jlaura** [comment]
Labelling as mission because ASP is a primary consumer of this library and we can slot it into the mission support sprints.
