### ISSUE TITLE
ISIS 4.1.0, spiceinit, and MGS MOC data

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#3908]
**ISIS version(s) affected**: 4.1.0

**Description**  

I hooked up ASP to ISIS 4.1.0. I am glad no APIs changed on the ISIS side, and I hope it continues being that way going forward.

Regretfully, I started getting bad results for a MGS MOC testcase that we use extensively. I did fetch (repeatedly) the latest MGS MOC and base isis data dirs.

The problem seems to be not in ISIS itself or in the kernels or in ASP, but in spiceinit.  The newest spiceinit in ISIS 4.1.0 (as fetched with conda) makes the .cub files have wrong pointing information. I think this is a potentially serious issue, and may be a bigger problem than just MOC perhaps. I also tested LRO NAC however, and there spiceinit performs well. 

Here's a testcase showing the cub files before and after spiceinit is applied: 

http://byss.arc.nasa.gov/oalexan1/moc_data.tar

Taking a diff between them, shows these changes that I don't understand:
<pre>
62c62
<     LeapSecond                = $base/kernels/lsk/naif0009.tls
---
>     LeapSecond                = $base/kernels/lsk/naif0012.tls
64c64,65
<     TargetPosition            = (Table, $base/kernels/spk/de405.bsp)
---
>     TargetPosition            = (Table, $base/kernels/spk/de430.bsp,
>                                  $base/kernels/spk/mar097.bsp)
73a75
>     Source                    = isis
101d102
< # Jigged = 2013-02-20T16:21:08
104,105c105,106
<   StartByte           = 13139969
<   Bytes               = 96
---
>   StartByte           = 13148797
>   Bytes               = 256
117a119,121
>   FrameTypeCode       = 3
>   Description         = "Created by spiceinit"
>   Kernels             = $mgs/kernels/ck/mgs_sc_map1.bc
120c124
<     Name = J2000Ang1
---
>     Name = J2000Q0
126c130
<     Name = J2000Ang2
---
>     Name = J2000Q1
132c136
<     Name = J2000Ang3
---
>     Name = J2000Q2
136d139
< End_Object
138,148c141,145
< # Jigged = 2013-02-20T16:21:08
< Object = Table
<   Name                 = InstrumentPosition
<   StartByte            = 13140225
<   Bytes                = 96
<   Records              = 4
<   ByteOrder            = Lsb
<   CacheType            = PolyFunction
<   SpkTableStartTime    = -20723097.688171
<   SpkTableEndTime      = -20723090.653368
<   SpkTableOriginalSize = 4865.0
---
>   Group = Field
>     Name = J2000Q3
>     Type = Double
>     Size = 1
>   End_Group
151c148
<     Name = J2000SVX
---
>     Name = AV1
157c154
<     Name = J2000SVY
---
>     Name = AV2
163c160,166
<     Name = J2000SVZ
---
>     Name = AV3
>     Type = Double
>     Size = 1
>   End_Group
> 
>   Group = Field
>     Name = ET
170,182c173,183
<   Name                = BodyRotation
<   StartByte           = 13140393
<   Bytes               = 128
<   Records             = 2
<   ByteOrder           = Lsb
<   TimeDependentFrames = (10014, 1)
<   CkTableStartTime    = -20723097.688171
<   CkTableEndTime      = -20723090.653368
<   CkTableOriginalSize = 2
<   Description         = "Created by spiceinit"
<   Kernels             = ($base/kernels/spk/de405.bsp,
<                          $base/kernels/pck/pck00009.tpc)
<   SolarLongitude      = 134.8112963459
---
>   Name                 = InstrumentPosition
>   StartByte            = 13149053
>   Bytes                = 168
>   Records              = 3
>   ByteOrder            = Lsb
>   CacheType            = HermiteSpline
>   SpkTableStartTime    = -20723097.688171
>   SpkTableEndTime      = -20723090.653368
>   SpkTableOriginalSize = 4865.0
>   Description          = "Created by spiceinit"
>   Kernels              = $mgs/kernels/spk/mgs_map1.bsp
185c186
<     Name = J2000Q0
---
>     Name = J2000X
191c192
<     Name = J2000Q1
---
>     Name = J2000Y
197c198
<     Name = J2000Q2
---
>     Name = J2000Z
200d200
<   End_Group

</pre>

**Comment by rbeyer** [comment]
> The problem seems to be not in ISIS itself or in the kernels or in ASP, but in spiceinit. The newest spiceinit in ISIS 4.1.0 (as fetched with conda) makes the .cub files have wrong pointing information.

So the LSK and SPK kernels have advanced, so it is understandable that the pointing might be different, but can you provide more of a description of how it is "wrong?"

**Comment by oleg-alexandrov** [comment]
Stereo gives wrong results. The triangulation error goes from a few meters to a few km. I still get a DEM, and it looks plausible, but with such a bad triangulation error it can't be trusted. 

I don't expect people to use ASP's stereo to figure this out. I guess ISIS has ways of taking a pixel in the camera, and seeing where the ray emanating from that pixel goes. For either the left or the right camera image (included in the above tarball) the ray must change drastically with the new kernels, and not in a way which is consistent between the left and right images.

**Comment by jessemapel** [comment]
@oleg-alexandrov Can you provide the actual table data using tabledump? The label differences are not very useful by themselves.

`tabledump from=moc.cub name=InstrumentPosition`
`tabledump from=moc.cub name=InstrumentPointing`
`tabledump from=moc.cub name=BodyRotation`
`tabledump from=moc.cub name=SunPosition`

**Comment by oleg-alexandrov** [comment]
Here it is. For the two old cubs, without redoing spiceinit, when things were good:

<pre>
/bin/cp -fv E0201461.old.cub moc.cub
'E0201461.old.cub' -> 'moc.cub'
tabledump from=moc.cub name=InstrumentPosition
J2000SVX,J2000SVY,J2000SVZ
1676.443108309,1984.6008537369,2798.1611581072
0.96519774245866,-2.8415882007041,1.4815831595591
-6.66003708005292e-04,-7.72075013728113e-04,-0.0010746455198785
38134460.335879,1.0,2.0
 
tabledump from=moc.cub name=InstrumentPointing
J2000Ang1,J2000Ang2,J2000Ang3
-0.40328824130186,2.6042566842566,-2.3069805924196
6.01242687098269e-05,-3.43419063191241e-05,8.72825036781766e-05
-7.35522753814166e-14,4.21884749357559e-14,-1.0680345496894e-13
38134462.156818,5.9999991580844,2.0
 
tabledump from=moc.cub name=BodyRotation
J2000Q0,J2000Q1,J2000Q2,J2000Q3,AV1,AV2,AV3,ET
0.81201859142046,-0.062096385437393,-0.31213302364746,0.48922675892865,3.16245961630695e-05,-2.87962041825841e-05,5.65238623185742e-05,38134456.448225
0.8121533745644,-0.062182396147756,-0.31211590018102,0.48900297611279,3.16245961630475e-05,-2.87962041828281e-05,5.65238623184622e-05,38134464.223534
 
tabledump from=moc.cub name=SunPosition
J2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET
188823690.43562,131513029.84653,55215605.267717,-15.517359648536,15.544616614778,7.5492712733104,38134456.448225
188823569.7833,131513150.71068,55215663.965615,-15.517374352126,15.544606374631,7.5492669740014,38134464.223534
 
/bin/cp -fv M0100115.old.cub moc.cub
'M0100115.old.cub' -> 'moc.cub'
tabledump from=moc.cub name=InstrumentPosition
J2000SVX,J2000SVY,J2000SVZ
1515.0951905588,2005.5940434163,2896.1948202045
1.0619163489541,-2.826303285048,1.4426313580959
-6.05689261341524e-04,-7.76671054538269e-04,-0.0011067888551395
-20723094.170769,1.0,2.0
 
tabledump from=moc.cub name=InstrumentPointing
J2000Ang1,J2000Ang2,J2000Ang3
-0.53817888177077,2.5337172529822,-2.4516683469833
-0.0061922043593906,0.0033436019580073,-0.0046605733974265
-7.08264396401814e-05,-3.18988375234142e-05,-1.29426132159161e-04
-20723094.350671,5.9999993294477,2.0
 
tabledump from=moc.cub name=BodyRotation
J2000Q0,J2000Q1,J2000Q2,J2000Q3,AV1,AV2,AV3,ET
0.83168591850523,-0.07502510869113,-0.30927049276649,0.454996184962,3.16247621411922e-05,-2.87943575336356e-05,5.65247101978296e-05,-20723097.688171
0.83179933280088,-0.075102214017499,-0.30925177781305,0.4547888139798,3.16247621411723e-05,-2.87943575338563e-05,5.65247101977283e-05,-20723090.653368
 
tabledump from=moc.cub name=SunPosition
J2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET
180856374.09936,139121675.31244,58920575.635375,-16.443863981071,14.864362971761,7.2624390809972,-20723097.688171
180856258.41997,139121779.88027,58920626.72519,-16.443876882293,14.86435304732,7.2624348777997,-20723090.653368
</pre>

For the two new cubs, after spice init, when things get bad:

<pre>
/bin/cp -fv E0201461.new.cub moc.cub
'E0201461.new.cub' -> 'moc.cub'
tabledump from=moc.cub name=InstrumentPosition
J2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET
1704.544205561,1999.954547168,2747.92062905,0.97037249322696,-2.8355737046958,1.4899332756894,38134456.448225
1708.3066268165,1988.9191033089,2753.6967543052,0.96519959013669,-2.8415938919549,1.4815859220792,38134460.335879
1712.0489163028,1977.8603213726,2759.4403954835,0.96001582203182,-2.8475800145836,1.473221866141,38134464.223534
 
tabledump from=moc.cub name=InstrumentPointing
J2000Q0,J2000Q1,J2000Q2,J2000Q3,AV1,AV2,AV3,ET
0.048615654993193,-0.59525618254843,-0.74223080776992,0.30397372127318,-9.17993886227721e-06,-5.99731887249541e-06,-3.541261756276e-06,38134456.156819
0.048615654993193,-0.59525618254843,-0.74223080776992,0.30397372127318,-7.11978939440194e-06,-6.66338966158452e-06,-6.21223608672837e-06,38134460.156818
0.048657297841995,-0.5952674683492,-0.74221046303521,0.30399463326335,-7.71475295365055e-06,-6.28017136093413e-06,-5.06436605523759e-06,38134464.156818
0.048657297841995,-0.5952674683492,-0.74221046303521,0.30399463326335,-8.86202883672622e-06,-6.86701328016172e-06,-5.46148015716577e-06,38134468.156817
 
tabledump from=moc.cub name=BodyRotation
J2000Q0,J2000Q1,J2000Q2,J2000Q3,AV1,AV2,AV3,ET
0.81201859142046,-0.062096385437393,-0.31213302364746,0.48922675892865,3.16245961630695e-05,-2.87962041825841e-05,5.65238623185742e-05,38134456.448225
0.8121533745644,-0.062182396147756,-0.31211590018102,0.48900297611279,3.16245961630475e-05,-2.87962041828281e-05,5.65238623184622e-05,38134464.223534
 
tabledump from=moc.cub name=SunPosition
J2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET
188823690.91677,131513028.65618,55215606.516169,-15.517359562954,15.544616622759,7.5492713366649,38134456.448225
188823570.26445,131513149.52034,55215665.214068,-15.517374266524,15.544606382667,7.5492670373699,38134464.223534
 
/bin/cp -fv M0100115.new.cub moc.cub
'M0100115.new.cub' -> 'moc.cub'
tabledump from=moc.cub name=InstrumentPosition
J2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET
1549.2997968408,2010.315926601,2830.7963660787,1.0661739808954,-2.8208303074042,1.4504129581651,-20723097.688171
1553.0424767944,2000.3842919908,2835.8843731872,1.0619180195063,-2.8263079373486,1.4426335409081,-20723094.170769
1556.7701694904,1990.4334391759,2840.9449936471,1.057652222388,-2.8317577826601,1.4348408909488,-20723090.653368
 
tabledump from=moc.cub name=InstrumentPointing
J2000Q0,J2000Q1,J2000Q2,J2000Q3,AV1,AV2,AV3,ET
0.0062172980477468,-0.58532253640439,-0.72826221745455,0.35636079499616,7.53292683524952e-04,4.85906423765291e-05,-4.52818086705038e-04,-20723100.350671
0.0049476960202623,-0.58596614640553,-0.72825839233244,0.35532929736812,7.45334384765778e-04,3.85441156921746e-05,-4.58020982371253e-04,-20723096.350671
0.0036476748986412,-0.5865843010415,-0.72827104720175,0.3542976630563,7.59133649205636e-04,5.72816838504204e-05,-4.53185580836367e-04,-20723092.350672
0.0023301585516565,-0.58718253717401,-0.72828722957278,0.35328310126613,7.69777003300161e-04,7.32231519405262e-05,-4.44651584012828e-04,-20723088.350672
 
tabledump from=moc.cub name=BodyRotation
J2000Q0,J2000Q1,J2000Q2,J2000Q3,AV1,AV2,AV3,ET
0.83168591850523,-0.07502510869113,-0.30927049276649,0.454996184962,3.16247621411922e-05,-2.87943575336356e-05,5.65247101978296e-05,-20723097.688171
0.83179933280088,-0.075102214017499,-0.30925177781305,0.4547888139798,3.16247621411723e-05,-2.87943575338563e-05,5.65247101977283e-05,-20723090.653368
 
tabledump from=moc.cub name=SunPosition
J2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET
180856374.6417,139121674.10537,58920576.909965,-16.44386390344,14.864362976167,7.2624391391605,-20723097.688171
180856258.96231,139121778.67321,58920627.99978,-16.443876804618,14.864353051762,7.2624349359582,-20723090.653368
</pre>

I guess one can save these side-by-side and compare them. Some things changed drastically but I don't understand the format. Of course one can also inspect the attached cubs directly.

**Comment by jessemapel** [comment]
It looks like you're before images have been bundle adjusted. `J2000SVX,J2000SVY,J2000SVZ` indicates that your InstrumentPosition tables are bundle adjusted polynomials. Same with `J2000Ang1,J2000Ang2,J2000Ang3` in your InstrumentPointing tables.

SunPosition has also changed very slightly, but that is to be expected going from de405 to de430

**Comment by rbeyer** [comment]
Yeah, wow, I just map-projected the cubes in the tarball, and the "old" pair line up right on top of each other, making a great stereo pair.  The "new" pair does indeed have an offset of a kilometer or so.  In addition, if you compare the "new" to the "old," the "new" versions are narrower in the cross-track direction, and have a different skew, but it seems to be consistent between them, such that a translation should line them up.

If the previous pair was bundle adjusted, then that would explain things.

**Comment by lwellerastro** [comment]
# Jigged = 2013-02-20T16:21:08

shows up a couple of times in the label comparison.  Presumably the older image?

**Comment by jessemapel** [comment]
> ```
> # Jigged = 2013-02-20T16:21:08
> ```
> 
> shows up a couple of times in the label comparison. Presumably the older image?

That also indicates that the old images have been bundle adjusted.

**Comment by oleg-alexandrov** [comment]
I am glad to know this is the explanation rather than something more sinister. I've ran in addition to LRO also a CTX pair, and that worked too. So things are good. Thank you for your help. You can close this issue when appropriate.
