### ISSUE TITLE
RFC to deprecate ApolloPanStitcher

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#3934]
**ISIS version(s) affected**: 4.2.0+

**Description**  

The Apollo Pan stitcher application can and probably should be deprecated. In order to deprecate the application we need to have an RFC drafted. This issue is to being the process of drafting the RFC to deprecate the app.

**Comment by AustinSanders** [comment]
Should this process be the same as the deprecation or edrget, or is there a distinction that would require us to draft an RFC?
