### ISSUE TITLE
Does ISIS have a "history" file?

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#3941]
**Description**
Many open source projects have a HISTORY file in the main level of the repository that provides a high-level overview of features and bug fixes in each release.  There appears to be no such file in the ISIS3 repo.  Maybe it is elsewhere in the hierarchy?

There does appear to be a [thread on AstroDiscuss](https://astrodiscuss.usgs.gov/c/ISIS/isis-release-notes) which contains this information, but it is separate from the repo, which seems odd.  It is easy enough to PR a HISTORY file into existence based on that thread, but I wondered if maybe there was something I was missing.

**Suggested Edit**
Create and maintain a HISTORY file in the main level of the repo.

Thanks!

**Comment by jessemapel** [comment]
ISIS does not have a release notes/change log/history file. We custom write changes as part of the release process, but they just live on the release announcements. It would be better if we had a change log that just grew as new things come in. This looks decent https://keepachangelog.com/en/1.0.0/

Note that we already have change logs for applications and the website documentation that are embedded in each file.

**Comment by jessemapel** [comment]
How much text do we want to have in such a changelog? Our PR template already has two sections about describing the change:

    

    ## Description
    

It seems like just copying these two sections into the changelog would be good. Is there a way we can automate that?

**Comment by rbeyer** [comment]
That's probably a good start.

I think the problem is that the text that you write into PR or Issue threads are not available in the repo if it is checked out.  They are a GitHub feature, not a `git` feature.  So you'd have to have something scrape the PR URLs for the info, which may get tricky.

If there was a changelog file, then having people modify it as part of their PR would also be a mechanism for adding to it.

We could try and get people in the habit of using something like the [Conventional Commits](https://www.conventionalcommits.org) pattern in their commit messages and then harvest a summary from the commits (and a variety of tools are listed on their site) at release time.  I think @michaelaye was using auto-changelog (there are a lot of things that alias to that name, I'm guessing it was [this one](https://github.com/Michael-F-Bryan/auto-changelog)) on some of his projects with some success.  I searched on "python changelog" and got a bunch of hits.
