### ISSUE TITLE
ISIS entry page

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#3948]
They main ISIS page seems to be:

  https://isis.astrogeology.usgs.gov/

I think it needs a bit of updates. It should have a longer introduction, note on the latest version, a prominent link to GitHub, a link to the history page. 

I think the link to ISIS2 should be under the one to ISIS3, and it should be made clear that ISIS2 is, for all extent and purposes, kept here for historical reference or it could go away altogether.

**Comment by jessemapel** [comment]
@oleg-alexandrov Can you be more specific about what you think should be changed? I agree that it's rather light.

What kind of information would you be looking for in the introduction?

Would a link to github under the popular destinations heading be sufficient?

Which history page are you referencing?

**Comment by oleg-alexandrov** [comment]
I would think of the following layout for that page:

# Welcome

This is the home page for ISIS, a digital image processing software package. The focus of the software is to manipulate imagery collected by current and past NASA and International planetary missions sent throughout our Solar System.

# Download

The latest version of ISIS is 4.1.0. Information regarding how to download, install, and use it is available on project's [GitHub repository](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md).

# Links 

 -  [ISIS 3 Application Table of Contents](https://isis.astrogeology.usgs.gov/Application/index.html) 
 - Visit the [Astro Discussion Board](https://astrodiscuss.usgs.gov/) for the  for the latest news and announcements.
 - [About ISIS](https://isis.astrogeology.usgs.gov/AboutIsis/index.html)
 - [ISIS 2 Home](http://isis.astrogeology.usgs.gov/Isis2/isis-bin/isis.cgi) &mdash; mainly for historical interest

This would have a prominent link to the GitHub repo, where all the action happens these days, and ISIS2 would be at the very bottom. 

There's probably more to be done, such as merging https://isis.astrogeology.usgs.gov/AboutIsis/index.html with the main page, as they are both very tiny pages (and at that location is the link to history I mention).

These are just some thoughts. The larger point I want to make is that I was a bit surprised ISIS2 figures so prominently.

**Comment by rbeyer** [comment]
@jessemapel I think this is also related to a long-standing ISIS TC action item: "Add landing at .gov website, can redirect to github. Jesse will ensure this gets assigned and scheduled (ASC)" (e.g. [April ISIS TC meeting ](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/meetings/2020-04-14.md))

**Comment by jessemapel** [comment]
@rbeyer #3916 already addressed some of those comments and will go live with the next release in August.

**Comment by rbeyer** [comment]
Sure, but Oleg's concern and the meat of the TC action item were about the contents of the .gov site, not the GitHub site.

**Comment by oleg-alexandrov** [comment]
There is some merit, I believe, in keeping the existing pages at usgs.gov, and their connections, rather than a straight redirect to GitHub, if that is what is meant. The GitHub page is getting a bit unwieldy I think. The installation is taking most real estate and the very important topic of ISIS data is way at the bottom.  Anyhow, I'll stop stirring the pot.

**Comment by jessemapel** [comment]
@oleg-alexandrov Those changes look good to me. I have to think a bit about if we want to directly reference the current release. Maybe we can scrape the ISIS Release Notes part of astrodiscuss and provide a listing of recent releases.

@rbeyer That PR changes both the github site and the .gov site https://github.com/USGS-Astrogeology/ISIS3/pull/3916/files#diff-d03d32dcc29b4d02ee9c6b70287b9507. The .gov site is built from the files in the docsys directory and we push the current state of it with each feature release.

**Comment by jessemapel** [comment]
I'm going to table this out of the ASC's support work because this is a part of a bigger redesign that needs to happen for the website. We could take the process step by step, but I think this is such an important page that I don't want to modify it without considering the rest of the website.

**Comment by oleg-alexandrov** [comment]
I think this issue got a little lost. It appears to have been part of the 4.3.1 milestone. 

I am sure there's a lot of more important work to do, it is just a bit amusing, to me at least, that now we've got ISIS 5, the main ISIS page still notes that ISIS 2 is a popular destination and has ISIS 3 as the state of the art.
