### ISSUE TITLE
What style should ISIS code follow?

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#3955]
**Description**

Should ISIS code follow a style, and if so, what style?

Currently all ISIS code is supposed to follow the style guide documented at: https://isis.astrogeology.usgs.gov/documents/CodingStandards/CodingStandards.html

There are good and bad things about having style guides. This issue is here to get a discussion started.

**Comment by krlberry** [comment]
Here are some examples of various C++ coding styles followed by other projects as applied to usgscsm (_not_ ISIS.)

Links are diffs between the result of running clang-tidy with the listed formatter and the "current usgscsm dev" which was updated to use the Google format. 

Google Style: https://github.com/USGS-Astrogeology/usgscsm/pull/307/files (special case: this one diffs against the original non-standardized code)
LLVM: https://github.com/USGS-Astrogeology/usgscsm/compare/dev...kberryUSGS:llvm
GNU: https://github.com/USGS-Astrogeology/usgscsm/compare/dev...kberryUSGS:gnu
Mozilla: https://github.com/USGS-Astrogeology/usgscsm/compare/dev...kberryUSGS:mozilla
Chromium: https://github.com/USGS-Astrogeology/usgscsm/compare/dev...kberryUSGS:chromium
WebKit: https://github.com/USGS-Astrogeology/usgscsm/compare/dev...kberryUSGS:webkit

Internal-only, these same examples are also available under: 
`/work/projects/isis/style_examples`

I could easily do this for ISIS as well. Is anyone interested in seeing this? 

Edit: Additional context: @scsides asked me to post these.

**Comment by rbeyer** [comment]
@scsides this is a great question.  

I think ISIS should have such a thing.

There should be no expectation that the codebase should turn on a dime and instantly transform, but instead once we settle on a new version, then enforce as new code is committed to the repo.

The document you link contains information about a couple of different categories of "style."  The Format category  could be programmatically checked with a linter (like the examples @kberryUSGS showed).  I don't have any recommendations, but it shouldn't be too difficult to settle on one, and it could even be integrated into the PR process.

Most of the other topics in that document are relevant to ISIS development and boil down to architecture decisions or required practices, and may be more difficult to enforce automatically (but that's what the PR/review process is for).

I think the document that you list would probably be a good place to start at (since that is theoretically where the code is "now" anyway).  Maybe we should just bring it into the repo, slap a "draft" label on it, and work it with Issues and PRs until we're happy with it what it says?

**Comment by jessemapel** [comment]
I like the idea of moving the style guide off of the website and into the repo or wherever the dev docs go. I don't have a preference for the formatting part of the style guide. I would keep the ISIS naming conventions from our current style guide. I would update the application naming standard for the new application style. I would also drop the part about std::string vs qstring. We probably want to move away from QT classes in the API and start moving towards standard library classes.

**Comment by michaelaye** [comment]
i'm a big fan of automatically applied styles through linting/formatters.
It matters less, IMHO, what style one settles on than to have one at all that will be automatically and reliably enforced.
Having a format applied throughout a code base helps tremendously in reading and fast browsing it, I'm convinced that once the grumbling of the ones that voted for "the other obviously better style", productivity is enhanced all around.

**Comment by jlaura** [comment]
I ran across a free restyler at https://restyled.io. I see that they support two different C++ stylers: [astyle](http://astyle.sourceforge.net/astyle.html) and [clang format](https://clang.llvm.org/docs/ClangFormat.html). The restyler is free to use for OS projects in public repos on GitHub. If some of those two stylers looks like it has potential, I would be happy to get an ASC repo wired up.

**Comment by scsides** [comment]
This hasn't been decided and should be. A good C++ linter seems like the best choice for appearance. If the API "style" isn't set and enforced, the code could get very difficult to read. @rbeyer is correct, it can't change overnight, but some effort should be put into getting everything using the same standard over time (e.g., the current mix of upper and lower camel case is a pain)

**Comment by rbeyer** [comment]
Still relevant.

**Comment by rbeyer** [comment]
This item is as relevant as ever, but doesn't seem to have gotten any attention.

**Comment by jlaura** [comment]
@rbeyer Do you use a linter or automatic code style tool on ASP that you like (or at least tolerate)?

**Comment by rbeyer** [comment]
We do not.

**Comment by AustinSanders** [comment]
[This](https://github.com/motine/cppstylelineup) repo provides a good comparison of cpp programming styles and links to the specs for each style.

Some styles (at least LLVM) are pretty relaxed with respect to things like brace placement / indentation, and mostly leave those things to the individual project while providing frameworks of best practices that support maintainability / readability etc.

In terms of tooling, it seems like the standard tools are (cpplint)[https://github.com/cpplint/cpplint] and (clang-tidy)[https://clang.llvm.org/extra/clang-tidy/].

Clang-tidy seems like an awesome tool with swappable styles, but, as the name suggests, it uses clang, and we use gcc.  I don't think this is too big of an issue, and I've seen some posts that suggest that it can be configured for gcc, but I had no such luck.  This might require some work, but it seems like it might be the best tool out there.

cpplint is a fairly light weight tool that just works out of the box.   It doesn't look like it can auto-correct the code according to the coding style, but it's super easy to set up.  The default tool uses Google C++ style, but it can be extended / forked to use a custom ruleset.  It appears that [this](https://github.com/isocpp/CppCoreGuidelines/blob/master/scripts/python/cpplint.py) fork provides an alternative rule set.

---------
Based on the information I've come across, my vote is for LLVM and clang-tidy tooling if we can afford the overhead of supporting it.
