### ISSUE TITLE
isis 4.2.0 installs wrong gsl version

### ISSUE THREAD

**Issue by AndrewAnnex** [DOI-USGS/ISIS3#3969]
**ISIS version(s) affected**: 4.2.0

**Description**  
it looks like following 

the install instructions conda picks the wrong libgsl version, I had to manually install and saw it upgraded libgsl thusly: 2.2.1-blas_openblas_3 --> 2.6-h294904e_0

**How to reproduce**  

conda create --name isis_4_2 python=3.6.0 -c defaults < I added the .0 and defaults were my addition, as I was running into issues there as well I decided to enforce some restrictions
conda activate isis_4_2
conda config --env --add channels conda-forge
conda config --env --add channels usgs-astrogeology
conda install -c usgs-astrogeology isis=4.2.0
python $CONDA_PREFIX/scripts/isis3VarInit.py < why is isisVarInt.py not available for 4.2.0?
qview > error about libgsl.so.25 

**Possible Solution**  

A suggested fix would be to add a CI test to the project using github actions to try installing various isis versions on a scheduled basis that may expose issues in conda land.

**Additional context**  

here is the output for conda list after I installed gsl myself, maybe something obvious will poke out here, I also ran conda clean --all before running any of the above steps.
[isis42condalist.txt](https://github.com/USGS-Astrogeology/ISIS3/files/5057405/isis42condalist.txt)

**Comment by krlberry** [comment]
This doesn't address your primary issue, but, to answer a small question: 

> python $CONDA_PREFIX/scripts/isis3VarInit.py < why is isisVarInt.py not available for 4.2.0?

The [PR](https://github.com/USGS-Astrogeology/ISIS3/pull/3945) that updated and renamed isis3VarInit.py to isisVarInt.py was merged after the new branch was created for the 4.2 RC (effectively a feature freeze.) Bug fixes that come in between the RC release and the official release are pulled into the release, but not new features.

**Comment by jessemapel** [comment]
Can you provide the exact error you got from qview? I wonder if this is a dependency of a dependency or a direct dependency problem.

**Comment by AndrewAnnex** [comment]
specific error is:
 `qview: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory`

**Comment by AndrewAnnex** [comment]
if I run `ldd` on the qview executable it looks like the shared lib is not found

**Comment by sriramsaran** [comment]
I am having a similar problem after installing ISIS 4.2.0 on Ubuntu 18.04.5 LTS. When I run qview (or any other program) I get this error : 
**qview: error while loading shared libraries: libarmadillo.so.9: cannot open shared object file: No such file or directory**

How to resolve this?

**Comment by sriramsaran** [comment]
I got the same error and I just did **conda update gsl**  after activating isis environment. It worked !

**Comment by AndrewAnnex** [comment]
I think the solution would be to pin a version for gsl and blas, or ensure that both blas and gsl are installed from the conda-forge

**Comment by jlaura** [comment]
@AndrewAnnex PR solicited!

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/recipe/meta.yaml
