### ISSUE TITLE
ISISDATA instructions improvement

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#3971]
**Description**

The current docs regarding the ISISDATA env variable don't make it abundantly clear that things only work when it points to the top most directory. Were a user point it at a mission folder below that, unexpected behavior results like the wrong metadata being found.

**Suggested Edit**

I suggest to expand the text in the env variable options for pyIsisVarInit docs.

Additionally, I was wondering if we should add a check against that setup failure?

I'll submit a PR for this for the docs part.

PS: why that discouraging icon for doc related issues?

**Comment by jlaura** [comment]
We can totally update the doc emoji. What are you thinking? 📄 or 📕 or 📚 or 📖 or 🍭

**Comment by michaelaye** [comment]
I like 
![](https://github.githubassets.com/images/icons/emoji/unicode/1f4d6.png)

and sorry I didn't add the `documentation` label, still getting used to my new `powers` ;)
