### ISSUE TITLE
hideal2pds outputs incorrect value of SAMPLE_BIT_MASK in label for all but 16 bit compression

### ISSUE THREAD

**Issue by audiefen** [DOI-USGS/ISIS3#3978]
**ISIS version(s) affected**: 3.9.0

**Description**  
With hideal2pds, when selecting any bit compression other than 16, the SAMPLE_BIT_MASK in the output label is incorrect. Below is an excerpt from an output label where bit=10 was selected.
[...
OBJECT = IMAGE
  DESCRIPTION                = "HiRISE mosaicked product, not map projected"
  LINES                      = 2500
  LINE_SAMPLES               = 5000
  SOURCE_LINE_SAMPLES        = 5000.0
  SOURCE_LINES               = 2500.0
  FIRST_LINE_SAMPLE          = 0.5
  FIRST_LINE                 = 0.5
  BANDS                      = 1
  OFFSET                     = 0.0037222964252952
  SCALING_FACTOR             = 3.14850405127014e-06
  SAMPLE_BITS                = 16
  SAMPLE_BIT_MASK            = 2#1111111111111111#
  SAMPLE_TYPE                = MSB_UNSIGNED_INTEGER
  FILTER_NAME                = "Red"
  CENTER_FILTER_WAVELENGTH   = 700 <NM>
  BAND_WIDTH                 = 300 <NM>
  BAND_STORAGE_TYPE          = BAND_SEQUENTIAL
  CORE_NULL                  = 0
  CORE_LOW_REPR_SATURATION   = 1
  CORE_LOW_INSTR_SATURATION  = 2
  CORE_HIGH_REPR_SATURATION  = 1023
  CORE_HIGH_INSTR_SATURATION = 1022
END_OBJECT = IMAGE
...]

Should be:
`SAMPLE_BIT_MASK 2#0000001111111111#`

**How to reproduce**  
hideal2pds max=0.006936919061642 to=ESP_057858_1410_RED.NOPROJ.img type=MANUAL version=1.0 min=0.003731741937449 from=PSP_009492_1280_RED.NOPROJ.cub bits=10

**Possible Solution**  

**Additional context**  
[PSP_009492_1280_RED.NOPROJ.lbl.gz](https://github.com/USGS-Astrogeology/ISIS3/files/5104979/PSP_009492_1280_RED.NOPROJ.lbl.gz)
[PSP_009492_1280_RED.NOPROJ.cub.gz](https://github.com/USGS-Astrogeology/ISIS3/files/5104990/PSP_009492_1280_RED.NOPROJ.cub.gz)

**Comment by jlaura** [comment]
@audiefen Thanks for the detailed reproduction steps! I just tested in 4.2.0 and am able to reproduce:

```
OBJECT = IMAGE
  DESCRIPTION                = "HiRISE mosaicked product, not map projected"
  LINES                      = 2500
  LINE_SAMPLES               = 5000
  SOURCE_LINE_SAMPLES        = 5000.0
  SOURCE_LINES               = 2500.0
  FIRST_LINE_SAMPLE          = 0.5
  FIRST_LINE                 = 0.5
  BANDS                      = 1
  OFFSET                     = 0.0037222964252952
  SCALING_FACTOR             = 3.14850405127014e-06
  SAMPLE_BITS                = 16
  SAMPLE_BIT_MASK            = 2#1111111111111111#
  SAMPLE_TYPE                = MSB_UNSIGNED_INTEGER
  FILTER_NAME                = "Red"
  CENTER_FILTER_WAVELENGTH   = 700 <NM>
  BAND_WIDTH                 = 300 <NM>
  BAND_STORAGE_TYPE          = BAND_SEQUENTIAL
  CORE_NULL                  = 0
  CORE_LOW_REPR_SATURATION   = 1
  CORE_LOW_INSTR_SATURATION  = 2
  CORE_HIGH_REPR_SATURATION  = 1023
  CORE_HIGH_INSTR_SATURATION = 1022
END_OBJECT = IMAGE
```

**Comment by audiefen** [comment]
@jlaura I might later regret saying this... but there is no rush on a fix. It is easily worked around by editing the label file. thanks!

**Comment by scsides** [comment]
@ audiefen, In your example for 10 bit output you show "SAMPLE_BIT_MASK 2#1111111111#". The PDS3 docs are not explicit, but I believe it would convey more information if it was: "SAMPLE_BIT_MASK 2#0000001111111111#". This explicitly shows that it is the low order 10 bits and not the high. Would you be ok with that?

**Comment by audiefen** [comment]
@scides Do you mean `SAMPLE_BIT_MASK 2#0000001111111111#` would convey more information? If so, yes that is better and that is what hideal2pds is putting in the label in ISIS 4.3.0 (I just re-confirmed). ~Looks like there was a typo in my original post. I meant to request "SAMPLE_BIT_MASK 2#0000001111111111#" for 10 bit output. Somehow I omitted the zeros.~

**Comment by audiefen** [comment]
Oh, I see what's happening. The display is removing the leading zeros in our posts. Argh!

**Comment by audiefen** [comment]
Should be `SAMPLE_BIT_MASK 2\#0000001111111111\#`.

**Comment by scsides** [comment]
Ok, it is doing it to both of us. Yes, your last example is what I believe it should be.

**Comment by tgiroux** [comment]
After PR 3998 SAMPLE_BIT_MASK has correct output as described above.
