### ISSUE TITLE
Update the Ceres PCK

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4001]
**Description**  

This is coming from a lot of discussion on an [astrodiscuss post](https://astrodiscuss.usgs.gov/t/update-ceres-shape-model-in-isis/388).

While making the HAMO Dawn mosaic, the team produced an updated PCK. We should switch over to using this in the data area. It can be found here: https://sbnarchive.psi.edu/pds3/dawn/fc/DWNCHSPG_2/GEOMETRY/

**Example**  

Running spiceinit on a DAWN FC image of Ceres pulls `dawn_ceres_v05.tpc` as its PCK right now. It should instead select `dawn_ceres_SPG20160107.tpc` as its PCK.

**Comment by jlaura** [comment]
Would making this change be breaking in any way for pipeline users? Or can we make this swap in the next few weeks?

**Comment by jessemapel** [comment]
We don't support an official Dawn pipeline. It should be safe to make this change. Another change that we do do is make this the "smithed" pck and that would maintain backwards compatibility. That is what we did with the Europa PCK.

**Comment by jessemapel** [comment]
Even though this is a data area change, I'm labeling this for 4.3.1 because we do push out kernel updates in between releases so this can go out whenever.

**Comment by kaitlyndlee** [comment]
@jessemapel Looking at the astrodiscuss post, it looks like updating the kernel without adding it as a smithed kernel would be the best solution since it aligns with new spice data. Do you agree?

**Comment by jessemapel** [comment]
I agree, because we default to the corresponding DEM, we should use this as the default PCK for Dawn observations of Ceres.

**Comment by kaitlyndlee** [comment]
@jessemapel Was there an image you tested this with? I found a few images with CERES as their target, but when I run spiceinit, it gives me an error saying there is no pointing information for that time. I've checked the start times of the images and they fall into one of the ranges defined by the ck kernels db file. I am not sure why I am getting this error.

**Comment by jessemapel** [comment]
I don't have a test image, you'll need to find one.

**Comment by jessemapel** [comment]
This is still something we need to do to improve the usability of Ceres datasets.

**Comment by jessemapel** [comment]
Still worth doing

**Comment by jlaura** [comment]
@AustinSanders This looks like it is low cost, high value. I suspect it has been lost in the shuffle though. Does it make sense to get this tracked somewhere? Or should we close with a 'will not fix' (since it is 2 years old and hasn't happened)?

**Comment by AustinSanders** [comment]
I can make a Q2 support board that we can use to track issues for next support sprint.  It can do double duty as a way to organize continuous support.

**Comment by tclark96** [comment]
@jessemapel the `downloadIsisData` script has been updated to include `dawn_ceres_SPG20160107.tpc` as well as an updated kernel.db to properly select it.
