### ISSUE TITLE
Further automate the generation of AUTHORS.rst from .zenodo.json

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#4019]
**Description**  
Right now, as part of the ISIS release process, a developer needs to run the script at
`$ISISROOT/scripts/zenodo_to_authors.py` to generate an updated `AUTHORS.rst` file from the `.zenodo.json` file. 
It would be even better if this were an automated process along the lines of "if the .zenodo.json file has been updated, run zenodo_to_authors.py to generate a new AUTHORS.rst and commit it to the repository." 

I'm not sure how best to do this (GitHub actions? another bot?)

This is a follow-on to #3950 and #3995. 

**Example**

**Comment by rbeyer** [comment]
This is still relevant.

**Comment by jessemapel** [comment]
We just added a github action for stale issues, this would be a good candidate for a new action.

**Comment by rbeyer** [comment]
Still relevant.

**Comment by jessemapel** [comment]
I'll ping this to keep it open, but also note that we need to generate the authors.xlsx file for the USGS release process.
