### ISSUE TITLE
fits2isis not including mission parameters in generated level 1 cub

### ISSUE THREAD

**Issue by gdmcdonald1** [DOI-USGS/ISIS3#4023]
Hi, I'm trying to ingest and reproject New Horizons LORRI images. When using the fits2isis program, the level 1 cube that is generated does not contain information about the mission in its header. Thus, when I then go and try to run spiceinit on the output level 1 cub, I get the error 

`**PROGRAMMER ERROR** No value or default value to translate for translation group [MissionName] in file [/home/george/anaconda3/envs/isis4/appdata/translations/MissionName2DataDir.trn]`

The images I am working with are the latest LORRI Pluto Calibrated Data v3.0 from the PDS Small Bodies Node ([https://pds-smallbodies.astro.umd.edu/holdings/nh-p-lorri-3-pluto-v3.0/dataset.shtml]). As an example, I have below the header for the lor_0299178961_0x630_sci.cub I generated using fits2isis on lor_0299178961_0x630_sci.cub, and have attached both the original .fit file (header to long to embed as text) as well as the .cub file I generated to this post. Notice missing parameters under "Group=Instrument" such as "SpacecraftName", "InstrumentId", "SpacecraftClockStartCount" etc:

[lor_0299178961_0x630_sci.cub.txt](https://github.com/USGS-Astrogeology/ISIS3/files/5242657/lor_0299178961_0x630_sci.cub.txt)
[lor_0299178961_0x630_sci.fit.txt](https://github.com/USGS-Astrogeology/ISIS3/files/5242659/lor_0299178961_0x630_sci.fit.txt)
[print.prt.txt](https://github.com/USGS-Astrogeology/ISIS3/files/5242662/print.prt.txt)

`Object = IsisCube
  Object = Core
    StartByte   = 65537
    Format      = Tile
    TileSamples = 512
    TileLines   = 512

    Group = Dimensions
      Samples = 1024
      Lines   = 1024
      Bands   = 1
    End_Group

    Group = Pixels
      Type       = Real
      ByteOrder  = Lsb
      Base       = 0.0
      Multiplier = 1.0
    End_Group
  End_Object

  Group = Instrument
    Target = PLUTO
  End_Group
End_Object

Object = Label
  Bytes = 65536
End_Object

Object = History
  Name      = IsisCube
  StartByte = 4259841
  Bytes     = 505
End_Object

Object = OriginalLabel
  Name      = IsisCube
  StartByte = 4260346
  Bytes     = 23261
End_Object
End
`

I've tried several different images (all from date of closest approach to Pluto), and also as a workaround using pds2isis on the corresponding .lbl file rather than the .fit file, but still get the same error from spiceinit (i.e. pds2isis also produces a level1 cub lacking mission info). I'm able to go through this same pipeline without issue for Galileo data, and have installed the New Horizons kernels in my $ISISDATA directory, which makes me think the issue is specific to New Horizons. I have not seen this exact issue filed previously. Thank you for any and all help!

**Comment by rbeyer** [comment]
There is a `lorri2isis` which you should use, not the generic `fits2isis`.

**Comment by gdmcdonald1** [comment]
Wow thank you... I think I had found that `lorri2isis` function in the documentation and took note not to use `pds2isis`, but then when I went on to do the testing I instinctually kept typing `fits2isis` instead. Just verified that seemed to have work so far in getting `spiceinit` to work. Thanks and sorry for not making sure my brain and typing were doing the same thing!
