### ISSUE TITLE
Error installing on Mac

### ISSUE THREAD

**Issue by SPIFdmZPonterio** [DOI-USGS/ISIS3#4033]
**ISIS version(s) affected**: 3

**Description**  
During the installation I got this error message:

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::bz2file-0.98-py_0'.
FileNotFoundError(2, "No such file or directory: '/Users/zponterio/anaconda3/envs/isis3/bin/python3.6'")

But I looked and that file is there, but there is no "scripts" folder in isis3 folder for setting up environment variables.

**How to reproduce**  

**Possible Solution**  
Should I erase everything and run the installation all over again?

**Additional context**

**Comment by jessemapel** [comment]
@SPIFdmZPonterio If you run `conda list bz2` in the environment you installed in, what do you get? It looks like Anaconda had a hicup while setting everything up. I would suggest removing the environment, clearing your cache, and then trying again. It could be you have a bad version of bz2file cached.

**Comment by SPIFdmZPonterio** [comment]
Thanks for responding! I cleared everything out and started over, and this time started with updating my version of conda. It looks like it all worked this time!

**Comment by jlaura** [comment]
@SPIFdmZPonterio Great to hear and thanks for opening the issue! Definitely reopen the issue if needed.
