### ISSUE TITLE
lrowaccal is nonfunctional on MacOS (Edit: On any system without kernels directory downloaded.)

### ISSUE THREAD

**Issue by rvwagner** [DOI-USGS/ISIS3#4038]
**ISIS version(s) affected**: 3.10.1 and 4.1.0 on MacOS 10.14.6, and 3.12.0 on a different MacOS 10.14.6 system.
EDIT: Just updated the 4.1.0 install to 4.2.0.  The issue persists.
EDIT: The "3.12.0" was probably 4.something, with the version edited to say "3.12.0" as a work-around for a web SPICE error, per https://github.com/USGS-Astrogeology/ISIS3/issues/3725#issuecomment-619091103. Ben Bussey may have more detail- it's his system.

**Description**  
When running a LROC WAC image through lrowaccal on MacOS, the. output values all end up as 0.0.  The exact same processing steps on ISIS 3.9.1 and 4.1.0 on Linux produce a properly-calibrated image.  All the calibration files listed in the Radiometry groups are identical (same MD5 checksum) between the two systems, so I suspect it's the executable file that's the problem.

**How to reproduce**  
    wget http://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0027/DATA/ESM2/2016163/WAC/M1220245217CE.IMG
    lrowac2isis from=M1220245217CE.IMG to=M1220245217CE
    lrowaccal from=M1220245217CE.vis.even.cub to=M1220245217CE.vis.even.cal.cub

UPDATE:
Skipping the radiometric calibration step causes the output to stop being 0, so that's probably where the problem is:
lrowaccal from=M1220245217CE.vis.even.cub+1 to=M1220245217CE.vis.even.cal.cub Radiometric=false

**Comment by rvwagner** [comment]
Update: It's not MacOS, it's not having the $Lro/kernels directory.  Both of the above computers were relying on web SPICE, while the Linux system had local kernels.  When I set up an Lro data directory without a kernels directory on that Linux system, I got the same 0 result.  EDIT: If I add the contents of kernels/tspk/ and the de421 files from kernels/pck/, the radiometry correction works correctly.

Not sure how this should be solved long-term, but it means there's a workaround of downloading ~20MB of kernels.

**Comment by jessemapel** [comment]
This is related to #1473 and was fixed for lronaccal in #3611 by first using the attached SPICE data on the cubes and then falling back to loading local kernels if that's not available. This is something the ASC is planning to address for all calibration programs this year. See: https://github.com/USGS-Astrogeology/softwaremanagement/tree/master/FY21#spice-calibration

**Comment by jessemapel** [comment]
Labeling as a bug. Behavior should be to error and not create an invalid cube. Making lrowaccal work without local kernels is #1473
