### ISSUE TITLE
Spiceinit not creating cube history entry on MacOS 

### ISSUE THREAD

**Issue by rvwagner** [DOI-USGS/ISIS3#4040]
**ISIS version(s) affected**: 4.2.0 (version number manually edited to be 3.420.0 to make web SPICE happy), 3.10.1 on MacOS 10.14.6.

**Description**  
spiceinit isn't putting an entry into the cube's history on the MacOS versions I've looked at.  Linux versions 3.9.1, 4.1.0 and 4.2.0_RC1 do put in history entries (both with and without web=true specified for 3.9.1, the later versions do not use web=true).

Other ISIS programs can put in history entries on the same cube file (editlab, lrowaccal tested).

Not terribly critical, but weird.

**How to reproduce**  
```
wget http://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0027/DATA/ESM2/2016163/WAC/M1220245217CE.IMG
lrowac2isis from=M1220245217CE.IMG to=M1220245217CE
spiceinit from=M1220245217CE.vis.even.cub web=true
cathist from= M1220245217CE.vis.even.cub
```

**Comment by jessemapel** [comment]
This is probably due to the spiceinit app conversion not properly adding a history entry. For reference here's the old code: https://github.com/USGS-Astrogeology/ISIS3/blob/53af27e53c06fb38d7cadcfc1b5754c1be3baf45/isis/src/base/apps/spiceinit/main.cpp

**Comment by kaitlyndlee** [comment]
When I run spiceinit without web=true, I get a history entry on both mac and linux, but when I run with web=true, I do not get a history entry on both. Is this the same behavior you are seeing?
