### ISSUE TITLE
Parallelize ImageOverlapSet

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#4048]
**Description**  
Currently ImageOverlapSet is only parallelized to calculate overlaps and write said overlaps to a file concurrently. This is a weird form of parallelization that might not result in any significant improvements in run time. 

We'll have more details when issue #4045 is complete. 

It would still be nice to actually parallelize the computation of the overlaps for a given set of images. Since any given set of images (n) will have to check all permutations of P(n, 1), P(n, 2), ... , P(n, n) it would significantly improve performance if this could be parallelized.

This change will likely be a somewhat significant rewrite to the ImageOverlapSet, and is somewhat necessary if this app is actually supposed to be using threads for faster computation times.

**Example**  
This can be done with either pthreads or qthreads. I have done a good bit of the boiler plate code to get a qthread implementation started, see [this branch](https://github.com/acpaquette/ISIS3/tree/image_overlap) for more details. The QThread child class is ImageOverlapThread. It's currently very bare bones and there is still a problem of needing to halt the parent process to wait for the child processes to come back before continuing.

**Comment by jlaura** [comment]
A likely even better approach would be to compute an [R-Tree](https://en.wikipedia.org/wiki/R-tree) and then query that data structure in parallel. The R-Tree can also be constructed in parallel, but I would suggest that the work doing that is likely a premature optimization. 

An R-Tree removes the need to check all permutations and should be significantly faster whether serial or parallel.

**Comment by jessemapel** [comment]
We already have an example R-Tree computation for geometries in cnetthinner. It is overly complex for this case, but you can use the same third party library for it.
