### ISSUE TITLE
Improve lronac2isis documentation

### ISSUE THREAD

**Issue by benmoseley** [DOI-USGS/ISIS3#4055]
**Description**  
I think it would be useful to state in the `lronac2isis` documentation (https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/lronac2isis/lronac2isis.html) that this script carries out decompanding of NAC images and is therefore only suitable for _raw NAC PDS EDR images_ and not for _calibrated NAC PDS CDR images_, which are also available on the LROC PDS archive to download (http://lroc.sese.asu.edu/data/).

The CDR images already have decompanding applied as part of the calibration routine (see Humm et al (2016). Flight Calibration of the LROC Narrow Angle Camera. Space Science Reviews, 200(1–4), 431–473. https://doi.org/10.1007/s11214-015-0201-8).

But, currently the documentation for this script says
`This program takes an image from the Lunar Reconnaissance Orbiter Narrow Angle Camera and produces an Isis cube containing the image data.` i.e. it is probably too ambiguous.

We have been mistakenly inputting CDR images into this routine until realising this was not correct. Perhaps the script name should also be changed to `lronac2isis_decompand` or similar, and further guidance given on how to import CDR images instead, e.g. through `pds2isis`.

**Comment by jessemapel** [comment]
We could also put a check in the program to ensure users do not run it on CDRs. and instead return an error message about using pds2isis for cdrs.

**Comment by jessemapel** [comment]
This is an excellent place for new contributors to add to the project.  The app documentation can be found [here](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/lro/apps/lronac2isis/lronac2isis.xml#L11). The main description text is under the `description` tag which is just html.

Adding an exception would be more complicated but that code is located [here](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/lro/apps/lronac2isis/main.cpp#L46). In fact it seems to already try and check if it's an RDR but isn't working correctly.

@victoronline In input on if this is checking the right value to indicate an RDR from the PDS archives?
