### ISSUE TITLE
dawnvir2isis requires pdsQube.trn

### ISSUE THREAD

**Issue by pedrohasselmann** [DOI-USGS/ISIS3#4063]
Hi,

**ISIS version(s) affected**: 
3.10.0 # Public version number
2020-02-04 # Release date
stable # Release stage (alpha, beta, stable)

**Description**
I'm trying to use ISIS3 command dawnvir2isis to convert DAWN data cubes, but I keep getting the following error:

****I/O ERROR** Unable to open [/home/phasselmann/miniconda3/envs/isis3/data/base/translations/pdsQube.trn].**

**How to reproduce** :
Download partials: rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/base .
conda activate isis3
type command: dawnvir2isis
Fill in the input box with DAWN VIR .LBL file and .QUB data file download from PDS NASA.

**Possible Solution**
It seems that the pdsQube.trn in the translation folder is necessary to complete the operation, however, this file is not available in the standard installation of the translation folder.

**Additional context** 
I see a similar issue here: [lronac2isis I/O Error #3292 ](https://github.com/USGS-Astrogeology/ISIS3/issues/3292)
I have downloaded the data base area and the issue remains, pdsQube.trn is not there.

I wonder where exactly I could download this specific file since nowhere is specified how. I propose that this file should be provided as a standard for new users.

**Comment by jessemapel** [comment]
@pedrohasselmann Can you reformat your bug report using our bug report template:

```
**ISIS version(s) affected**: x.y.z

**Description**  
<!-- A clear and concise description of the problem. -->

**How to reproduce**  
<!-- Code and/or config needed to reproduce the problem. -->

**Possible Solution**  
<!--- Optional: only if you have suggestions on a fix/reason for the bug -->

**Additional context**  
<!-- Optional: any other context about the problem: log messages, screenshots, etc. -->

```

Particularly, we need to know what version of ISIS you are running and if possible any public data you are working with.

**Comment by michaelaye** [comment]
Tip: Do `$ cat $ISISROOT/version` to get the version info.
Curiously, in a new 4.2 install, I see NO translations folder in $ISISDATA/base. Did something change there so that `dawnvir2isis` needs a change to reflect that?

**Comment by jessemapel** [comment]
@michaelaye The translation files are now distributed with the software. Check `$ISISROOT/appdata/translations` for its new home.

**Comment by michaelaye** [comment]
ok, then this really looks like an old version of `dawnvir2isis` b/c the current version looks at the correct folder: https://github.com/USGS-Astrogeology/ISIS3/blame/dev/isis/src/dawn/apps/dawnvir2isis/main.cpp#L87

**Comment by jessemapel** [comment]
Yeah, this is likely a miss-match between the software version and the data version.

**Comment by pedrohasselmann** [comment]
I got my hands into pdsQube.trn file, but now I get:

**QXcbConnection: XCB error: 3 (BadWindow), sequence: 960, resource id: 48234958, major code: 40 (TranslateCoords), minor code: 0
terminate called after throwing an instance of 'Isis::IException'
  what():  **I/O ERROR** Unable to open [/home/phasselmann/miniconda3/envs/isis3/data/base/templates/labels/CubeFormatTemplate.pft].**

It seems that DAWN base data has to be downloaded and updated to the new arranging of ISIS folders in full.

**Comment by jessemapel** [comment]
@pedrohasselmann That error isn't specific to Dawn data. It looks like you don't have the base data area downloaded. For ISIS <4.1 you need to have the base area downloaded. Here's the commands to do that:

```
cd $ISIS3DATA
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/base .
```

**Comment by pedrohasselmann** [comment]
Dear @jessemapel, if you look my issue again you will see that I stated in the original message that I have downloaded the data base area using the --partial command.

**Comment by jessemapel** [comment]
@pedrohasselmann There was a change made recently that moved many files in the base data area around. As a result we have two different data areas, one for before the change and one for after. Your version of ISIS requires the older one (it is under isis*3*data on our rsync) and this is the type of error we see when users are using the new data area with older software. So, can you check if `/home/phasselmann/miniconda3/envs/isis3/data/base/templates/labels/CubeFormatTemplate.pft` exists.
