### ISSUE TITLE
ISIS3 QNET error on Ubuntu

### ISSUE THREAD

**Issue by mrkirchoff** [DOI-USGS/ISIS3#4064]
I am getting this attached error when trying to load a file list in QNET. I am currently using ISIS 3.9.1 on Ubuntu 18.04. I also tried ISIS 3.10.2, which gave the same error. I cannot update to ISIS4 because a library is required that I cannot install on Ubuntu 18. note that the file list loads fine in QMOS and the cube file loads fine in QVIEW and CATLAB (note this is the first file in a list of ~200).

Thanks!
Michelle Kirchoff
![Screenshot from 2020-10-12 12-14-59](https://user-images.githubusercontent.com/54078869/95778085-9af69600-0c84-11eb-9ba7-ed3ab80ae152.png)

**Comment by rbeyer** [comment]
@mrkirchoff, wow, I must be getting old, because I really had to blow that image up.  However, the problem seems to be exactly what it says, there is a text file that it cannot find or open.  I can't tell if it is the image compression on that dialog box image, but is there a vertical pipe ("|") in that filename?  That could be the problem.  Or maybe that file isn't where you thought it was or there is some sort of permission problem with where the file is.  Or maybe the ".lis" file doesn't have a list of filenames in it that `qnet` needs?  Not sure.

**Comment by mrkirchoff** [comment]
Sorry about that. Hopefully this version is easier to read. The file is in the directory I'm working from and as I mentioned QMOS opens it fine. QNET seems to be complaining about a serial number?
![Screenshot from 2020-10-12 12-40-00](https://user-images.githubusercontent.com/54078869/95780099-84523e00-0c88-11eb-8fd6-bc260b2ca638.png)

**Comment by rbeyer** [comment]
Ah, okay, that's not a pipe, that's an "ell" (`l`).  Yeah, is that the first file in the list?  If you take it out, will the others be read?

I'll admit, the whole serial number thing with `qnet` has always mystified me, so maybe someone with more knowledge can help out.  Good luck.

**Comment by mrkirchoff** [comment]
It is first in the list. I have tried multiple files in the list as the first file. I have tried making the list smaller with only a few files (randomly selected from the list. I've tried other file lists (I have other groupings of files I am working on).

**Comment by jessemapel** [comment]
@mrkirchoff Can you check that `$ISIS3DATA/mro/translations/ctxSerialNumber0003.trn` exists on your machine? That file determines how CTX serial numbers are generated and it was moved out of the data area and into the repository in ISIS 4.1.

See the [README](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#versions-of-the-isis-data-area) for more information about the data area differences between ISIS4 and ISIS3.

**Comment by mrkirchoff** [comment]
So this is going to sound really dumb, but I forgot to re-download the mro data after my update... :P The file is there and all is working as it should now. Thanks, Jesse for the virtual "slap upside the head".

**Comment by jessemapel** [comment]
@mrkirchoff Glad it was an easy fix! The data area can be really easy to get mixed up so don't feel bad.
