### ISSUE TITLE
QMOS Errors Loading Lots of Images on macOS

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#4065]
**ISIS version(s) affected**: ≥3.9.x on macOS 10.15.x

**Description**  
When I try to open a "large" (several dozen or more) list - or select a "large" (several dozen or more) individual files at the same time - to open in QMOS, I get a large number of errors in the Terminal and footprints are not displayed.  This is odd behavior, so I'll explain a bit more:

When I select a few (say, 10) images, or a list of a few images to open, QMOS is fine, it displays the image names on the left and shows the footprints in the main window.  I can then add to that, and build up >100 images perfectly fine (so, open multiple files at a time, multiple times in the same QMOS session).

However, when I select a lot - where I have NOT done tests to figure out exactly what "a lot" means, but it's >few dozen* - it seems to start to load, and then a bunch of errors come into the terminal.  The result is that a partial list is loaded on the left side in QMOS, but no footprints are displayed.  The zoom is set to about 1.000xxxx m/px which is a separate bug in QMOS on the Mac, where the zoom gets locked there and you have to quit.

I can also try to open one image, which opens, then I try to open a large number, and I start to get errors in the Terminal and at that point I get an Abort Trap 6 in the Terminal and QMOS just quits.  Trying to open those exact same images all at once (so, the one PLUS the others), results in the error in the previous paragraph.

*If the errors below can be trusted as at what point "a lot" becomes "a lot," then it's anything >209 images.  Which is a weird number ... like, 256 I could understand, but I don't know where 209 would come from.

Here is an example of the Terminal output from the first situation:

```
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017465_2600_XN_80N120W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017467_2469_XN_66N166W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017478_2638_XN_83N124W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017517_2504_XN_70N092W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017518_2499_XN_69N120W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017531_2581_XN_78N120W.l1.cub].
**I/O ERROR** Could not read the footprint from cube [B20_017385_2565_XN_76N094W.l1.cub]. Please make sure footprintinit has been run.
**ERROR** Could not create camera or projection for [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017385_2565_XN_76N094W.l1.cub].
**ERROR** Unable to initialize cube projection from file [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017385_2565_XN_76N094W.l1.cub].
**ERROR** Unable to find PVL group [Mapping] in file [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017385_2565_XN_76N094W.l1.cub].
**I/O ERROR** Unable to open [/Users/stu/anaconda3/envs/isis3/lib/Camera.plugin].
**PROGRAMMER ERROR** Cube cannot be created.
[...]
```

I'll note, importantly, that those cubes are perfectly fine when opened just on their own, or even as a group but without the B01–B19 in my list first.  So there is no problem with those cubes, there is no problem with their projection.

For the case of the one image and then opening more:

```
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017465_2600_XN_80N120W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017467_2469_XN_66N166W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017478_2638_XN_83N124W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017506_2450_XN_65N150W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017518_2499_XN_69N120W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017531_2581_XN_78N120W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017532_2528_XN_72N144W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017533_2482_XN_68N168W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017544_2515_XN_71N111W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017545_2479_XN_67N137W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017546_2510_XN_71N166W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017552_2866_XN_73N136W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017557_2638_XI_83N124W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017559_2483_XN_68N158W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017564_2860_XN_74N101W.l1.cub].
**PROGRAMMER ERROR** Cube cannot be created.
**I/O ERROR** Unable to open [/Volumes/DataDrive_2TB_Fast/MC-01_06-10-14/Data_FlatFielded/B20_017583_2457_XN_65N092W.l1.cub].
libc++abi.dylib: terminating with uncaught exception of type Isis::IException: **I/O ERROR** Unable to open [/Volumes/MacintoshHD/Users/stu/isis3/data/base/translations/NaifErrors.trn].
Abort trap: 6
```

Again, importantly, those images open fine on their own when not at the end of my list.  Therefore, this is not a problem with my paths, it's not a problem with those cubes.

**How to reproduce**  
See above.

**Possible Solution**  
The only solution I have right now is to use this on macOS 10.14.x which I have still on another computer, or to use it in a virtual Linux environment which I have on two computers.  Where the lists and files I tested above work perfectly fine.  Or, open just a few dozen files at a time, repeatedly, and keep QMOS open after I spend a half hour doing that and hope things stay working!

**Additional context**  
None noted.

**Comment by jessemapel** [comment]
@scsides Could this be related to the lower limit on the number of open file handles on OSX? The ImageReader class does a threaded read and attempts to read up to 400 files at once.

@astrostu Can you try modifying `.Isis/qmos/Image\ Reader.config`; change the value after `safeFileOpen` to `true`. For example, mine would look like this after the change:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>defaultAlpha</key>
        <integer>60</integer>
        <key>openFilled</key>
        <true/>
        <key>safeFileOpen</key>
        <true/>
</dict>
</plist>
```

**Comment by astrostu** [comment]
@jessemapel Hey, that worked!  It actually didn't at first, but then I went back and realized that I had QMOS open, had modified the file, quit QMOS, and it must've over-written that file again with <false/> when I had quit.  Modifying the file and THEN opening QMOS and then opening my large list solved the problem, and I was even able to open my list of 2294 images, no probs.  Before the fix, I tested it on a different list and it failed on image 210 again.

**Comment by jessemapel** [comment]
There's also a more hardware level fix by modifying the ulimit (the number of files that can be open at once). For some reason, Mac sets this VERY low for modern operating systems. See [here](https://wilsonmar.github.io/maximum-limits/).

There's still a potential bug in here that ImageLoader isn't closing files at the proper time, but I'm not sure how high of a priority that is. Could be hairy because this involves threading.

**Comment by astrostu** [comment]
I set ulimit -Sn 98300 whenever I start running my ISIS code, but I have not thought that it would affect QMOS.  I guess because it involves threading, that's why it even becomes an issue?  Again, this didn't happen until the latest updates, so I'm not sure what you did or what Apple did to alter this and make it a bug.  Also, since the issue happened at file #210, I wasn't sure that was related to the 256 default in macOS.

Actually, in case it helps others, this is how I set the ulimit via Python near the top of my code:

```
if "Linux" in platform.system():
    MAX_OPENFILES_CURRENT = resource.getrlimit(resource.RLIMIT_NOFILE)
    MAX_OPENFILES = MAX_OPENFILES_CURRENT[1]-1
    MAX_OPENFILES_CURRENT = MAX_OPENFILES_CURRENT[1]
else:
    MAX_OPENFILES_CURRENT = 98300
    MAX_OPENFILES = MAX_OPENFILES_CURRENT-1
resource.setrlimit(resource.RLIMIT_NOFILE, (MAX_OPENFILES, MAX_OPENFILES_CURRENT))
```

The 98300 was determined empirically for the Mac and will change with your OS version based on hard, vs soft, limits.

**Comment by scsides** [comment]
Since this wasn't a problem in versions < 3.9.x, I wonder if something has happened to qmos or CubeManager (a quick search shows no sign of CubeManager in qmos). The CubeManager is supposed to keep this from happening when working with many cubes. CubeManager doesn't allow more than 60% of the ulimit. It will open and close cubes as necessary to keep under that number.

The reason it is not failing at 256 is because there are several other files open anytime any application is run. These include (as I remember): any library the app needs at run time, or plugins when called for. 

@astrostu, setting the open file limit to 98300 (very large) has the potential to cause problems. Each open file takes some amount of memory. If you ever actually open that many files it is possible you could start swapping much sooner than expected, or cause the OS to stop buffering thus slowing down everything. 

And to answer your question about threading: The two are mostly unrelated. The threading is being used to process the cubes/cube list many (dependant on the number of cpu cores) at a time. Many cube files can be open even if the core count is only one.

Possible fix: Make qmos use a CubeManager, but make sure it is thread safe, and works well with threads (i.e., avoids race conditions when multiple threads are opening cubes)

**Comment by astrostu** [comment]
@scsides Thanks for the info.  I'll note that when I do this, everything actually is closed when a thread with an open file finishes, but for some reason the OS doesn't recognize that.  So I don't anticipate (I haven't encountered) issues.

That aside, I am not 100% sure it's an ISIS issue.  As I noted, this happened more when I updated from macOS 10.14.x to 10.15.x and didn't touch ISIS.  So I suspect that Apple modified something that perhaps ISIS glossed over that it can't gloss over anymore.  In other words, I wouldn't suggest looking for a specific change in ISIS 3.8.x -> 3.9.x to try to find the issue.

**Comment by jessemapel** [comment]
After some discussion, we've decided that we are not going to address this in the code as it is expected for the program to open many file handles when you open many files. So, we recommend users set their ulimit appropriately based on the data set that they are working with. If anyone can identify a specific area in the code that this is occurring as a bug please post on here and re-open.
