### ISSUE TITLE
Difficulty replicating overlapstats/tsts/errors as gtest

### ISSUE THREAD

**Issue by tgiroux** [DOI-USGS/ISIS3#4076]
**ISIS version(s) affected**: dev

**Description**  

In overlapstats/tsts/errors, overlapstats is tested for it's ability to write errors to the user-specified file (given in the "ERRORS=" argument).

Within overlapstats, there is a very specific set of circumstances that trigger the type of error which would be written to the file. After many hours of tinkering with different overlap circumstances, I have been unable to trigger this error from a gtest.

The error is: "Unable to convert polygon from Lat/Lon to X/Y: *serial-numbers"

It has to fail at `geos::geom::MultiPolygon *mpXY = PolygonTools::LatLonToXY(*mpLatLon, proj);` in overlapstats.cpp,
then, within this call to PolygonTools, it needs to fail in a call to PolygonTools::Despike().

**How to reproduce**  

Attempt to force overlapstats to write an error "Unable to convert polygon from Lat/Lon to X/Y: *serial-numbers" to the file given in the "ERRORS=" argument.

**Possible Solution**  

Write an additional test in FunctionalTestsOverlapstats.cpp to test for the "ERRORS=" argument.
The error should be triggered by some overlaps.lis with particular geometry that breaks in Despike().
The overlaps need to be associated with cubes specified in the "FROMLIST=" argument.
See the geometry in overlapstats/tsts/errors/input/overlaps.lis for an example of an overlaps.lis that triggers the error.
I suspect the problem has something to do with the very last overlap listed (seems like it was baked in): MULTIPOLYGON(((180 90,180 -90,90 -90,179 0,180 90)))

**Additional context**

**Comment by jessemapel** [comment]
@tgiroux We discussed this briefly and it seems like some of these errors are impracticable to write tests for. Should we just not migrate these tests as they are such corner cases or do we just need to spend a little more time on this?

**Comment by jessemapel** [comment]
Also how does the GEOS migration impact this?

**Comment by tgiroux** [comment]
I think it's alright to close this issue - very much a corner case. GEOS migration shouldn't impact this, there are some code changes in dependencies for overlapstats but they should work the same.
