### ISSUE TITLE
MacOS jenkins failures only on github triggers

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#4079]
**ISIS version(s) affected**: dev 

**Description**  

MacOS fails to build on the org, but not on the nightly triggers

**How to reproduce**  

just look @ https://astroservices.usgs.gov/jenkins/job/USGS-Astrogeology/job/ISIS3/job/dev/76/execution/node/52/log/

every time a PR is merged, a build should start that will most likely fail to build for the same geos issue. 

**Possible Solution**  

Maybe the anaconda env being used in the build is different between org and nightly builds? 

**Additional context**

**Comment by jessemapel** [comment]
Looks fixed but there are other builds still hanging https://astroservices.usgs.gov/jenkins/job/USGS-Astrogeology/job/ISIS3/job/dev/113/flowGraphTable/
