### ISSUE TITLE
Ability for CAMPT to Return Limited List of Parameters

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#4092]
**Description**  
CAMPT computes a lot of information for every latitude/longitude or line/sample for a given image.  For a lot of applications, all of these data are not needed.  I think there should be some way to specify what data to include, or just return all (default behavior).  Not only would this make its output smaller, saving disk space, disk I/O, and RAM if reading those data in later, but it would save computation time (potentially A LOT) by not needing to calculate a lot of parameters the user likely does not need (which is my primary reason for asking).

**Example**  
I could envision this working as a .def file or as simply a command-line interface with various parameters set to false (so that default behavior, "true," would not change).

As an example of the former, one could simply add two inputs:  limitoutput=true deffile=myListOfParametersSetToTrue.def

As an example of the latter, one could do away with limitoutput=true, assume every parameter will be output (the behavior now), BUT, be able to specify parameters not to output.  For example, run CAMPT normally, but don't output any of the time data:  [commands to run it] ephemeristime=false utc=false localsolartime=false solarlongitude=false

**Comment by jessemapel** [comment]
This sounds similar to phocube. We can't have quite the same interface for compatibility reasons but is that what you're interested in @astrostu ?

**Comment by astrostu** [comment]
@jessemapel It is not.  PHOCUBE returns an actual cube of lots of different information at each pixel.  CAMPT returns data at a given location on the cube, not computing it for every pixel.  You can also feed it a list of lat/lon coordinates rather than sample/line.

Unless you mean specifying the options?  If you just mean in terms of the process of how it might operate, then sure.  My suggestions, though, were an attempt to keep it compatible, so that even if you change the application as I request, anyone who's using it now, as-is, would not need to change anything in their workflow.

**Comment by scsides** [comment]
Information: A large percentage of the work and time in campt is initializing the cube and camera model and then getting the initial lat(s)/lon(s) of requested line(s)/samp(s) or the opposite. Most of the other values come along for the ride or are simple calculations once the initial work is complete. There are a few values which have to go through one or two additional rounds of converting a line/samp to lat/lon (e.g. North Azimuth).  These more expensive values might be candidates for the ability you are requesting, but most others literally take micro seconds or less.

**Comment by astrostu** [comment]
I missed @scsides response, but I still think this is a good idea.  I think it would still speed some things up: Even if it would not necessarily be a huge improvement in speed of CAMPT, if you have an automated program reading a large CAMPT output file, it could be extremely RAM- and disk I/O-intensive.  I've run into that issue where I had to build a processes manager that watched RAM usage and slowed things down if needed, that parsed the output files for many images to make the reduced set of data I needed, and then read those reduced files in.

My exact situation is certainly rare, but given that this functionality is already built into some other ISIS programs, it seems like it should also be in this.

**Comment by jessemapel** [comment]
There's also some applications to CSM models here as there are values in campt that cannot be calculated with a CSM model.

**Comment by astrostu** [comment]
I still think this is a pretty good idea ...

**Comment by astrostu** [comment]
Gonna ping this one again ...

**Comment by astrostu** [comment]
*ping*

**Comment by jlaura** [comment]
@astrostu These have been pinged and re-pinged multiple times. We are not getting other community feedback on these so they are not percolating to the top of our priority list. Please reach out if you are interested in (1) opening a PR to address these or (2) opening a contract with us or someone else to have these addressed. If none of those options work, I would consider this to be a 'will not implement' request that should close on our issue close out schedule. Unfortunately, other issues have been a continued higher priority and intermittent 'ping' messages are not raising that priority.

**Comment by afrigeri** [comment]
This would be a significant enhancement.  Running campt pixel bt pixel on large files can take a long time.  It would be great to be able to select the parameters we are interested in from time to time.
