### ISSUE TITLE
Issues updating isis4 (isis4.0.1 to isis4.3.0)

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#4100]
Here is what I get when I fire up my conda:

**4.0.1 # Public version number
2020-03-04 # Release date
stable # Release stage (alpha, beta, stable)**

Next I try to update isis
**> conda update isis**

I get back:
**Collecting package metadata (repodata.json): done
Solving environment: done**

**All requested packages already installed.**

**4.0.1 # Public version number
2020-03-04 # Release date
stable # Release stage (alpha, beta, stable)**

I did some basic debugging:
**>conda config --show channels**
**channels:**
  **- usgs-astrogeology**
  **- conda-forge**
  **- defaults**

Looks OK so I tried to point straight to isis4.3.0
**>conda install isis4.3.0
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.**

**PackagesNotFoundError: The following packages are not available from current channels:**

  **- isis4.3.0**

**Current channels:**

  - https://conda.anaconda.org/usgs-astrogeology/linux-64
  - https://conda.anaconda.org/usgs-astrogeology/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

**To search for alternate channels that may provide the conda package you're
looking for, navigate to**

    **https://anaconda.org**

**and use the search bar at the top of the page.**

I also tried
**>conda install -c usgs-astrogeology isis=4.3.0**

with the same results.

I made sure my conda is the latest version.
I'm out of ideas...  have any for me?

If I do a fresh isis4 install, I wanted to confirm that you are still on python 3.6?

Thanks!
Laz

**Comment by lavalaz** [comment]
I did try to create a new conda environment as per the instructions and it barfs on python 3.6.

**Comment by lavalaz** [comment]
Issues are on Ubuntu 18.04.4
My mac can't connect to "http://ssb.stsci.edu/astroconda/osx-64..."  so no joy there either.  Maybe the problem is our servers...?

**Comment by jlaura** [comment]
@lavalaz Can you try `conda install -c usgs-astrogeology isis=4.3.0`

**Comment by lavalaz** [comment]
_It seems to be unhappy about the version of python, if I am reading the results correctly...
There are thousands of lines of "conflicts" but this is the first part._  

$ conda install -c usgs-astrogeology isis=4.3.0
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                               |

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - certifi -> python[version='3.7.*|3.9.*|3.8.*']

Your python: python==3.6.7=hd21baee_1002

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (icu):

  - isis=4.3.0 -> ale[version='>=0.8.4'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=7.2.0|>=9.3.0']
  - isis=4.3.0 -> ale[version='>=0.8.4'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=7.2.0|>=9.3.0']
  - isis=4.3.0 -> ale[version='>=0.8.4'] -> networkx
  - isis=4.3.0 -> ale[version='>=0.8.4'] -> numpy[version='1.11.*|1.12.*|1.13.*|>=1.9.3,<2.0a0']
  - isis=4.3.0 -> ale[version='>=0.8.4'] -> pvl[version='<=1.0']
  - isis=4.3.0 -> ale[version='>=0.8.4'] -> python-dateutil
  - isis=4.3.0 -> ale[version='>=0.8.4'] -> pyyaml
  - isis=4.3.0 -> ale[version='>=0.8.4'] -> scipy[version='>=1.2.0']
  - isis=4.3.0 -> ale[version='>=0.8.4'] -> spiceypy[version='>=2.3.0']
  - isis=4.3.0 -> armadillo[version='>=9.900,<10.0a0'] -> arpack[version='>=3.7.0,<3.7.1.0a0']
  - isis=4.3.0 -> armadillo[version='>=9.900,<10.0a0'] -> libblas[version='3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|>=3.8.0,<4.0a0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0',build='0_blis|0_openblas|2_blis|2_openblas|4_blis|4_mkl|5_blis|5_openblas|5_mkl|6_blis|6_openblas|6_mkl|6_h6e990d7_netlib|7_blis|7_mkl|8_blis|8_mkl|8_h6e990d7_netlib|9_mkl|10_openblas|10_mkl|10_h86c2bf4_netlib|11_blis|12_blis|12_openblas|12_mkl|13_blis|13_openblas|15_blis|15_mkl|16_blis|16_mkl|19_mkl|20_mkl|18_mkl|17_openblas|16_openblas|15_openblas|14_mkl|14_openblas|14_blis|13_mkl|11_h86c2bf4_netlib|11_mkl|11_openblas|10_blis|9_openblas|9_blis|8_openblas|7_h6e990d7_netlib|7_openblas|5_h6e990d7_netlib|4_h6e990d7_netlib|4_openblas|1_h6e990d7_netlib|0_h6e990d7_netlib']

**Comment by lavalaz** [comment]
My mac updated this morning without a hitch just using the came command I used before (up arrow, return, and it worked) so that part was apparently some server connection issue.  I'll retry linux shortly...

**Comment by lavalaz** [comment]
OK, I totally removed my isis and anaconda installs, and started from scratch.  
When I followed the isis installation instructions, it downloaded isis4.2.0...
I'm going to nuke that and try to force it to install isis4.3.0...

**Comment by lavalaz** [comment]
conda install -c usgs-astrogeology isis=4.3.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by jessemapel** [comment]
@lavalaz I've been looking at some related issues, can you share what's in your environment before you attempt to install isis4.3.0?

**Comment by lavalaz** [comment]
Finally had time to get back to this...  
Looks like it is working this time.  Only issue is that I don't seem to have permission to set permissions on symlinks in the data area, but have not done enough testing yet to see if that is an actual problem.  
Thank you!
Laz
