### ISSUE TITLE
IBM Power Architecture Support

### ISSUE THREAD

**Issue by chen-dimitry** [DOI-USGS/ISIS3#4119]
**Description**  
I am trying to build ISIS on CentOS7 with IBM Power8 CPUs. The required dependencies **embree** and **gmm** seeem to only work on Intel CPUs. Is there an option that I can do the compiling without these dependencies or will there be a seperate version for Power arch( and other non-intel arch) in the future?

**Comment by jessemapel** [comment]
@chen-dimitry embree and gmm are special builds that we are providing right now, so we're only providing them for Intel x86. We are working to move off of our special builds and onto generic conda-forge builds but it's a slow process.

For embree, you can try the [conda-forge 2.17.7 build](https://anaconda.org/conda-forge/embree/files?version=2.17.7). You can also try compiling it yourself, but it's actually Intel's software and uses some of their own special stuff to be as fast as possible so I'm not sure how well it will work on IBM processors.

Unfortunately conda-forge doesn't serve gmm or its parent package getFEM, but you can manually install it from the instructions [here](http://getfem.org/gmm/install.html). It's a header only library so you should only need to install the headers into `$CONDA_PREFIX/include/gmm` and cmake will find it.

**Comment by chen-dimitry** [comment]
@jessemapel Thanks for reply. Actually I've tried build both of them on my IBM machine but neither worked, e.g. Embree requires at least one of Intel-only extensions (like AVX).

Whatever I am not going to stick to this IBM stuff and try installing ISIS on other machine. Looking forward to updates on ISIS3's generalization 👍

**Comment by jessemapel** [comment]
I'm going to close this as won't fix because IBM architecture seems to be incompatible with our third party dependencies at this point. If someone wants to provide support, then there will likely be significant changes that will need further discussion.
