### ISSUE TITLE
Please provide a Restful interface...

### ISSUE THREAD

**Issue by adanecito** [DOI-USGS/ISIS3#4120]
Please provide a restful interface. Can be simple where a name is provided and a list of names with latitude and longitude is the response in JSON.
If it exists already please provide and example of the request and JSON.

Thanks!

**Comment by jlaura** [comment]
@adanecito Thanks for the post. We are going to need you to use the enhancement template which I am copying below. We are also going to need significantly more information. It looks like you are referencing a service that would return nomenclature? If so, we have a WFS available and I hope that @thareUSGS might reply with additional information about using the existing services.

What does the request look like that you are envisioning? What does the response look like? The more examples you can provide the better we are able to understand the use case and the user requirements.

Thanks!

```
**Description**  
<!-- A clear and concise description of the new feature. -->

**Example**  
<!-- A simple example of the new feature in action (include code, links to necessary data, etc.)
     If the new feature changes an existing feature, include a simple before/after comparison. -->
```

**Comment by thareUSGS** [comment]
While not restful our current WFS API should help. We are looking at upgrading the applications currently providing our WFS API (called Mapserver) to GeoServer. While GeoServer is not yet implemented for our nomenclature, but it does have the ability to support Restful calls, so this might be an eventual option.

Anyway, Mapserver, using the WFS API, can filter by a name or pattern. This page might help for now. It is not really meant to focus on our Nomenclature service, it does have several Nomenclature examples to pull from: https://github.com/USGS-Astrogeology/PDS-Pipelines/wiki/WFS-API-Introduction

For example (ask for all "A*" names on the Moon):

- [JSON output](https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/earth/moon_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MOON_POINT&REQUEST=getfeature&PropertyName=clean_feature&outputformat=application/json;%20subtype=geojson&Filter=%3CFilter%3E%3CPropertyIsLike%20wildcard=%27*%27%20singleChar=%27.%27%20escape=%27!%27%3E%3CPropertyName%3Eclean_feature%3C/PropertyName%3E%3CLiteral%3EA*%3C/Literal%3E%3C/PropertyIsLike%3E%3C/Filter%3E)  `https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/earth/moon_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MOON_POINT&REQUEST=getfeature&PropertyName=clean_feature&outputformat=application/json;%20subtype=geojson&Filter=%3CFilter%3E%3CPropertyIsLike%20wildcard=%27*%27%20singleChar=%27.%27%20escape=%27!%27%3E%3CPropertyName%3Eclean_feature%3C/PropertyName%3E%3CLiteral%3EA*%3C/Literal%3E%3C/PropertyIsLike%3E%3C/Filter%3E`

- More human readable but I can't link without the https XML codes, Json (copy and paste): `https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/earth/moon_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MOON_POINT&REQUEST=getfeature&PropertyName=clean_feature&Filter=<Filter><PropertyIsLike wildcard='*' singleChar='.' escape='!'><PropertyName>clean_feature</PropertyName><Literal>A*</Literal></PropertyIsLike></Filter>&outputformat=application/json;%20subtype=geojson`


- Example ask for all "[*Mons](https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/mars/mars_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MARS_POINT&REQUEST=getfeature&PropertyName=clean_feature&Filter=%3CFilter%3E%3CPropertyIsLike%20wildcard=%27*%27%20singleChar=%27.%27%20escape=%27!%27%3E%3CPropertyName%3Eclean_feature%3C/PropertyName%3E%3CLiteral%3E*Mons%3C/Literal%3E%3C/PropertyIsLike%3E%3C/Filter%3E&outputformat=application/json;%20subtype=geojson)" names on Mars):
`https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/mars/mars_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MARS_POINT&REQUEST=getfeature&PropertyName=clean_feature&Filter=<Filter><PropertyIsLike wildcard='*' singleChar='.' escape='!'><PropertyName>clean_feature</PropertyName><Literal>*Mons</Literal></PropertyIsLike></Filter>&outputformat=application/json;%20subtype=geojson`

**Comment by adanecito** [comment]
Thanks Trent I will take a close look and try them. As you mentioned I am not looking for the perfect solution just something good enough for people to use from within my app.
-Tony

    On Thursday, November 12, 2020, 9:15:03 AM PST, Trent Hare <notifications@github.com> wrote:  
 
 


While not restful our current WFS API should help. We are looking at upgrading the applications currently providing our WFS API (called Mapserver) to GeoServer. While GeoServer is not yet implemented for our nomenclature, it does have the ability to support Restful calls, so this might be an eventual option.

Anyway, Mapserver, using the WFS API, can filter by a name or pattern. This page might help for now. It is not really meant to focus on our Nomenclature service, it does have several Nomenclature examples to pull from: https://github.com/USGS-Astrogeology/PDS-Pipelines/wiki/WFS-API-Introduction

For example (ask for all "A*" names on the Moon):
   
   -    
JSON output https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/earth/moon_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MOON_POINT&REQUEST=getfeature&PropertyName=clean_feature&outputformat=application/json;%20subtype=geojson&Filter=%3CFilter%3E%3CPropertyIsLike%20wildcard=%27*%27%20singleChar=%27.%27%20escape=%27!%27%3E%3CPropertyName%3Eclean_feature%3C/PropertyName%3E%3CLiteral%3EA*%3C/Literal%3E%3C/PropertyIsLike%3E%3C/Filter%3E

   -    
More [human readable](https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/earth/moon_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MOON_POINT&REQUEST=getfeature&PropertyName=clean_feature&Filter=clean_featureA*&outputformat=application/json;%20subtype=geojson) (without the https XML codes, Json): https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/earth/moon_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MOON_POINT&REQUEST=getfeature&PropertyName=clean_feature&Filter=<Filter><PropertyIsLike wildcard='*' singleChar='.' escape='!'><PropertyName>clean_feature</PropertyName><Literal>A*</Literal></PropertyIsLike></Filter>&outputformat=application/json;%20subtype=geojson

   -    
Example (ask for all "[*Mons](https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/mars/mars_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MARS_POINT&REQUEST=getfeature&PropertyName=clean_feature&Filter=clean_feature*Mons&outputformat=application/json;%20subtype=geojson)" names on Mars):


https://wms.wr.usgs.gov/cgi-bin/mapserv?map=/var/www/html/mapfiles/mars/mars_nomen_wfs.map&service=WFS&version=1.1.0&&TYPENAME=MARS_POINT&REQUEST=getfeature&PropertyName=clean_feature&Filter=<Filter><PropertyIsLike wildcard='*' singleChar='.' escape='!'><PropertyName>clean_feature</PropertyName><Literal>*Mons</Literal></PropertyIsLike></Filter>&outputformat=application/json;%20subtype=geojson

**Comment by jlaura** [comment]
@adanecito I am going to close this issue on the ISIS repo since it sounds like you are looking for nomenclature. @thareUSGS Where do you suggest folks open issues related to the WMS?
