### ISSUE TITLE
Feature request for Rover and Drone positions

### ISSUE THREAD

**Issue by adanecito** [DOI-USGS/ISIS3#4122]
**Description**  (Feature Request)
I would like to see the Curiosity and other rovers and drones path in a gpx or other forms of information. Years ago I used ISIS info to draw the path for Curiosity and I have attached a screen capture from my Android app so you can understand the why and what I did with that ISIS info. The image is from the MRO 5m/pixel for the landing sites. I would love a wms for the whole planet but not your area.

**Example**  
![image](https://user-images.githubusercontent.com/13066342/99021658-ffbc3f00-2515-11eb-83ac-36ae0b0f3401.png)

Many Thanks!

**Comment by jlaura** [comment]
@adanecito Thanks for the detailed report. Unfortunately, ISIS is not a geographic information system (GIS). Additionally, we have very limited grounded sensor support (i.e., rovers). It looks like you are working on building a web application. I would expect to use ISIS for tasks like processing orbital image data that you are not able to locate processed already someplace else, applying a custom photometric correction, or perhaps even generating a regional mosaic.

I would suggest checking out this [MapBox blog post](https://blog.mapbox.com/tracking-mars-curiosity-rover-cf8bc090bbd0) where it looks like the authors have the same usage requirements and seeing where that leads. You might also check the [NASA Open APIs](https://api.nasa.gov/) to see if any available APIs fit your needs. Finally, it looks like a student might have worked on a [school project](https://proulxp.github.io/CS290-How-To-Guide/rover.html) to consume the curiosity rover API. Perhaps their work is something you can build off of.
