### ISSUE TITLE
qview measurement tool line option does not show line after releasing mouse button

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#4127]
**ISIS version(s) affected**: 4.0.0 and up

**Description**  

When using the measure tool with the line option on a Mac OS 10.14 system, the line disappears after the mouse button is released. This seems to work correctly on various Linux versions.

**How to reproduce**  

Load an image
Activate the measure tool
Activate the line option
Mouse over the image
Click and hold MB1
Drag (the line draws and follows the pointer)
Release MB1 (the line disappears and turns into a red X. It should stay visible until a new line is started)

**Possible Solution**  

**Additional context**  

Other measure options are working correctly

**Comment by kaitlyndlee** [comment]
I tested this on my mac on 10.14.6, and the line is still visible after I release MB1. Does this still happen on your machine?

**Comment by scsides** [comment]
Yes it is still a problem for me. Might be a 10.15. Might also explain why we haven't seen anyone else report it.

**Comment by kaitlyndlee** [comment]
@USGS-Astrogeology/developers Can anyone with a Mac try to reproduce this bug?

**Comment by scsides** [comment]
@kaitlyndlee, Just rebuilt and tried it again. The lines are now showing up. No idea what changed. Happy if it got closed as unreproducible.
