### ISSUE TITLE
de432s.bsp in isisdata/data/tgo/kernels/tspk/ is zero size (empty)

### ISSUE THREAD

**Issue by audiefen** [DOI-USGS/ISIS3#4131]
**ISIS version(s) affected**: 4.1.0 and 4.0.x

**Description**  
rsync'ing using either isis3data or isisdata modules results in an empty file being pulled over for /data/tgo/kernels/tspk/de432s.bsp

**How to reproduce**  
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/tgo/kernels/tspk/de432s.bsp .
or
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/tgo/kernels/tspk/de432s.bsp .

**Possible Solution**  
Replace the de432s.bsp on the rsync server with a fresh copy from NAIF.

**Additional context**  
The empty de432s.bsp causes spiceinit to fail with TGO CaSSIS images because the /data/tgo/kernels/tspk/kernels.0002.db file on the rsync server references it.

**Comment by jessemapel** [comment]
I've updated the file both locally at the ASC and on isisdist.astrogeology.usgs.gov with the file from https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/. I'm not sure how the file got truncated, but it should be fixed now.

@kberryUSGS I don't think the automated download scripts will cause problems here, but I wanted to double check with you before I close this.

**Comment by audiefen** [comment]
Thanks @jessemapel!

**Comment by jessemapel** [comment]
Fix is still there, I'm going to close this.
