### ISSUE TITLE
Improved documentation for Jigsaw's Target Body solution

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#4132]
**Description**
The Jigsaw application includes the capability to solve for target body parameters for global networks (pole RA/Dec, orientation, average/triaxial radii). This option is discussed briefly on the ISIS applications page (https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/jigsaw/jigsaw.html), which also points to a template for a pvl input file. However, I can't find a description of how jigsaw actually solves for these parameters. This results in at least three problems. 1) It's unclear what values several parameters should be in the pvl (especially the "sigma" values). 2) It's unclear what the uncertainties output by jigsaw mean (see below). 3) It's difficult to report the output in the peer-reviewed literature because the application is essentially a "black box".

**Suggested Edit**
Without knowing what the code is doing, I can't suggest specifics; however, I would like to see the following documented somewhere. 1) At least a qualitative description of how target body parameters are solved for. Presumably it's minimizing the residuals between the tie point lat/lon/radii values and an arbitrary ellipse/sphere, but given that there are potentially 6 unknowns (pole Ra/Dec, 3 radii, Wo) it would be nice to know the specifics. It's also not clear how the sigma values in the pvl file are used. Do these constrain the solution to be near the initial values? This would help the user better understand what values to use (in some cases it seems to work better to let sigma=0). Finally, I'd like to see a description of what the "Final Accuracy" reported by jigsaw actually means. For our Enceladus shape model, the final accuracy reported on the triaxial radii was ~25 cm. This clearly isn't the uncertainty in the shape. Perhaps it's just a simple sqrt(N) calculation? Otherwise it may be a bug.

Thanks!

**Comment by jessemapel** [comment]
I am struggling with how much of this should be specific to the target body solution.

The bundle adjust solves for the target body parameters the same way it solves for the image parameters, by minimizing the error between the measured control point locations and the back projected control point locations in each image. The difference between the two sets of parameters is just how the partial derivatives of that error are computed.

Similarly, the sigmas for the target body parameters are the exact same as the sigmas for the image parameters. They are the uncertainty in the adjusted value. Statistically, they are an estimate of the standard deviation of the random variable.
