### ISSUE TITLE
Need developer documentation on updating isis3mgr_scripts

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#4139]
**Description**
When the internal `isis3mgr_scripts` repo that contains the kernel update scripts is updated, it needs to get pulled down by-hand internally in a specific location to update the scripts run by cronjobs. This used to be an automated process prior to the move away from astrogit. (This could also probably be updated to be automated again, but if I remember correctly, there was some reason we didn't do this.) There should be docs describing this process. It's simple, but should be documented.

**Suggested Edit**
Write a wiki page or an internal astrodiscuss post on how to do this.

**Comment by jessemapel** [comment]
Maybe add a big warning on the isis3mgr_scripts repo readme or in PR templates that says this.
