### ISSUE TITLE
isisdist (phx) is out of space

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#4149]
**ISIS version(s) affected**: x.y.z
None

**Description**  

update of rsync servers failed due to full disk

**How to reproduce**  

**Possible Solution**  

Most of the dirs are identical on the local volume. The exception being TGO. Find out why. this is ~= 100GB

**Additional context**

**Comment by scsides** [comment]
found extra kernels director and deleted it (112GB). Did the same to the FLG server too.

**Comment by jessemapel** [comment]
@scsides What exactly did you remove? It looks like the isis3data also has some extra kernels in it. That's in term causing #4179
