### ISSUE TITLE
IsisPreference file not updated when ninja runs again after editing it

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#4152]
**ISIS version(s) affected**: x.y.z
All known

**Description**  

The IsisPreference file in an existing build, and likely others like it, are not being updated after being edited in the source code. 

**How to reproduce**  

Situation: 
Pull down dev and do a normal cmake and ninja.
Edit the IsisPreference file and save
Re-run ninja

Problem:
The IsisPreference file in the build does not get updated

**Possible Solution**  

Modify cmake rules to have IsisPreferences kept up to date. Check other files as well e.g. TestPreferences, scripts/, ...

**Additional context**

**Comment by jessemapel** [comment]
This is still frustrating when working on changes that require the preferences file.
