### ISSUE TITLE
pixel2map documentation picture is dead

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4168]
**Description**

The example picture at the end of the pixel2map documentation that show the fullfov option is missing.

See: https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/pixel2map/pixel2map.html

The image links to https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/pixel2map/assets/image/IFOV_vs_FFOV.png which 404s.

**Suggested Edit**

Figure out where the picture is and correct the link the documentation. This should be in the assets part of the code and copied into the doc tree when the docs are built.

**Comment by tgiroux** [comment]
I searched for this image in March and it seems it does not exist in any of our old versions of ISIS or anywhere else I looked. I remember speaking with someone who was willing to recreate an image / come up with a substitute for this issue. Can't remember who it was... @jessemapel @scsides any chance it was one of you two?

**Comment by jessemapel** [comment]
I can generate a new image for this. It'll take a minute but I can get it to you by the end of the week.

**Comment by jessemapel** [comment]
I definitely didn't do this but it still needs to be done.
