### ISSUE TITLE
spice server possibly failing to find moc_kernels.????.db

### ISSUE THREAD

**Issue by dbolan** [DOI-USGS/ISIS3#4179]
**ISIS version(s) affected**: 3.9.1

**Description**  
Sorry in advance for leaving this here as it might be a support question, but astrodiscuss suddenly isn't letting me log in from my IP address for some reason...
Me and a colleague have started running into an issue processing LROC images with spiceinit where we get the following error:
```
**ERROR** The Spice Server was unable to initialize the cube.  The error reported was: No existing files found with a numerial version matching [moc_kernels.????.db] in [/work1/work2/isis3/isis/../data/lro/kernels/ck].
```
I'm assuming that this is an issue with the spice server and not that we need MOC kernels to process LROC images. Though if something has changed and we do need them for whatever reason, I'd be very interested to learn why!
Thanks all.

**How to reproduce** 
```
wget http://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0022/DATA/ESM2/2015036/NAC/M1177762979RE.IMG
lronac2isis from=M1177762979RE.IMG to=M1177762979RE.cub
spiceinit from=M1177762979RE.cub web=true
```

**Comment by jessemapel** [comment]
@dbolan The MOC in the kerneldb name is not for the MOC instrument but just the prefix naming convention for the CKs that provide the orientation of the LRO spacecraft frame (ie moc42r_2020274_2020306_v01.bc).

I'm not sure why the spiceserver can't find this data anymore, it's there locally on our systems and on the rsync server. I'll take a look at where the server is mounting the data from.

**Comment by jessemapel** [comment]
Unfortunately, the spiceserver ran out of space to hold the data! We're working to get it upgraded with more storage now. It is highly likely that this will impact other users processing data from other missions.

**Comment by jessemapel** [comment]
This should be resolved now. I'm working to switch the spice server over to a system with more storage and there may be intermittent issues for the next few days but they shouldn't last more than a few minutes.
