### ISSUE TITLE
Credits page should redirect to authors/zenodo file

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4183]
**Description**

The [credits page](https://isis.astrogeology.usgs.gov/documents/Credits/Credits.html) on the website is likely out of date.

It is also very likely that people cited as contributors on the credits page are not listed in the authors or zenodo file.

**Suggested Edit**

The credits page should instead point to our new authors file or zenodo file. Alternatively, we could re-render it from the zenodo file.

Thanks!

**Comment by amystamile-usgs** [comment]
@jessemapel I need a better understanding on what I should do with the contributors currently listed on this credits page. It seems that our zenodo file is inconsistent with what is on our site in terms of who are USGS contributors versus outside contributors. There are also many contributors listed on the page that are not on our zenodo file. Should I just update the current list on the xml with any new authors from the zenodo file?

**Comment by jessemapel** [comment]
Let's the simplest approach and add all of the people on the credits page to the Zenodo file. Then, have the credits page just have a link to the zenodo latest release site.
