### ISSUE TITLE
References page should point to latest zenodo release

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4184]
**Description**

Our website has a page that says [how to cite ISIS](https://isis.astrogeology.usgs.gov/documents/References/References.html), unfortunately it was last updated in 2013.

**Suggested Edit**

The page should cite the zenodo for different releases of ISIS.

Thanks!

**Comment by amystamile-usgs** [comment]
@jessemapel For more clarification on this request. Should I replicate the wording from [Citing ISIS](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#citing-isis)? Also does this include removing all existing Reference information from Referrences.xml?

**Comment by jessemapel** [comment]
Modify the top text to

> The contributors to ISIS appreciate acknowledgement of their efforts in publications and data products that have used the ISIS software package in whole or in part. The following is the preferred way to acknowledge their contributions.

Leave the Acknowledgement section as is

Replace the content of the References section with a link to the ISIS zenodo page

**Comment by rbeyer** [comment]
I'm not sure what changes are planned for the ISIS documentation, but it would be nice to retain all of the entries in the References section by putting them in a "history of ISIS" section somewhere.

**Comment by jessemapel** [comment]
I think many of the references can be moved to specific application documentation. For example, `Analysis of Light Time and Stellar Aberration Corrections in ISIS Using Lunar Reconnaissance Orbiter Narrow Angle Camera Images` could be added to the lronac2isis docs.

**Comment by jessemapel** [comment]
For right now, the highest priority is to add a link to Zenodo on that page. How about moving all of the current references under a separate section and calling it related references?
