### ISSUE TITLE
AssertPvlGroupEqual comparison not failing when groups are not equal

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#4203]
**ISIS version(s) affected**: 4.1.0 (and upward)

**Description**  
The PVLGroup comparison assert correctly compares groups but fails to actually report the failure in the test. 

**How to reproduce**  
- Create a copy of a PVLGroup in some test
- Modify it in some capacity (Remove a keyword, add a keyword, change a keywords value etc.)
- Run the assert in the test
This should result in the two groups being different but the test should still pass.

**Possible Solution**  
Unsure, the solution will likely be through gtest or modifying how the assert is called. Currently it returns a `::testing::AssertionFailure()` which doesn't seem to actually result in a failed test.

**Additional context**

**Comment by jessemapel** [comment]
This is still bad as it means our tests are not actually catching failures in some very specific cases.

**Comment by jessemapel** [comment]
Closed by #4669
