### ISSUE TITLE
Thm2isis not properly propagating cube attributes

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#4213]
**ISIS version(s) affected**: 4.3.0 (and likely much older)

**Description**  
Thm2isis is not propagating cube attributes applied to the output cube. 

**How to reproduce**  
Take any Themis image, VIS or IR.

Run the following:
`Thm2isis from=/Path/to/input/Themis.img to=/Path/to/output/cube.cub+16bit`

The resulting output cube will have a Real bit type rather than a Signed Word bit type.

**Possible Solution**  
It's likely that the cube needs to have it's output attributes parsed from the direct string in the TO parameter of the UI.

**Comment by jessemapel** [comment]
Closed by #4504
