### ISSUE TITLE
Installation procedure: Copy conda activation/deactivation scripts to other envs

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#4231]
**Description**  

The instructions describe how one can  manually copy the init scripts to other conda envs.
This can be cumbersome and scary for new terminal users.
It would be good if this could be scripted.

**Comment by jlaura** [comment]
@michaelaye I realized after the fact that I just added comments onto the commit that you linked to the issue. I hope that that is okay with you. I thought I was on a PR to this repo!
