### ISSUE TITLE
Duplicate serial numbers for some data sets

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#4240]
**ISIS version(s) affected**: <=4.3.0

**Description**  
This a reporting of an issue original reported here: https://github.com/USGS-Astrogeology/PDS-Pipelines/issues/512#issuecomment-754951546

The issue is that two different Clementine (in this case) images produce the same ISIS serial number when serial numbers should be unique. 

Here is a pair of Clementine HiRes EDRs that yield the same serial number:

https://pdsimage.wr.usgs.gov/Missions/Clementine/cl_0077/lun328/lhxxxxxx/lhxxxxxj/lha1365j.328
https://pdsimage.wr.usgs.gov/Missions/Clementine/cl_0077/lun328/lhxxxxxx/lhxxxxxj/lha1366j.328

They both result in serial numbers of "Clementine1/HIRES/1994-04-29T08:48:21.170"

**How to reproduce**  
```
(isis4.3.0) -bash-4.2$ clem2isis from=lha1365j.328 to=lha1365j.cub
(isis4.3.0) -bash-4.2$ clem2isis from=lha1366j.328 to=lha1366j.cub
(isis4.3.0) -bash-4.2$ getsn from=lha1365j.cub
Clementine1/HIRES/1994-04-29T08:48:21.170
(isis4.3.0) -bash-4.2$ getsn from=lha1366j.cub
Clementine1/HIRES/1994-04-29T08:48:21.170
```
**Possible Solution**  
Make a modification to the clementine entry in the translation table to add another unique key to the serial generation process.

**Additional context**  
The original issue suggest that other missions exhibit the same behavior. @dpmayerUSGS can you please provide other examples? 

Also, I did not see this being reported previously, but I may have missed it. Searching for 'duplicate' generated, as expected, a lot of results.

**Comment by scsides** [comment]
@dpmayerUSGS, Proposed solution needs to be examined further. I could be missing something, but the labels of both images indicate they are from the HiRes camera. Unless there is an operating mode I'm not aware of, it is impossible for one instrument (as defined by ISIS) to take two images at the same time. That being said, looking at the labels suggests they are the same image, one is encoded as jpeg the other is encoded as N/A (possible PDS BSQ or something like that). If these are the same image, then by definition the SNs should match.

**Comment by dpmayerUSGS** [comment]
I [wasn't confident](https://github.com/USGS-Astrogeology/PDS-Pipelines/issues/512#issuecomment-754951546) that this was a reportable issue to ISIS in the first place.

This may be an error or undocumented "feature" of the Clementine archive. The 2 example products from HiRes have distinct PDS product IDs, and their labels indicate that they have different values for FRAME_SEQUENCE_NUMBER. According to the [SIS](https://pdsimage.wr.usgs.gov/Missions/Clementine/cl_0077/document/edrsis.asc), this latter keyword is *supposed* to differentiate between observations made during a particular orbit. Originally, I suspected that there was just an issue with lack of precision in START_TIME, but after looking at some other images with the same serial number, I think @scsides is right that these are from the same observation, but merely stored with different encoding.

**Comment by jlaura** [comment]
Given the discussion, I am going to close as not a bug.
