### ISSUE TITLE
PushFrame camera model needs GetLocalNormal calculation to stay within the correct framelet

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#4256]
**ISIS version(s) affected**: all, 4.3.0 and earlier.

**Description**  
The push frame camera model needs to be updated to keep the calculation of the local normal within the correct framelet. As part of the calculation, 4 points at (+/- 0.5 sample/line) are selected around the point to calculate the local normal at. For push frame imagers, the +/- 0.5 offset can result in a point outside of the framelet, which results in erroneous values for the calculated local normal. This issue was raised by issue #4018, and there are several examples on this issue illustrating the resulting problem. See below for a proposed solution.

PR #4214 fixes the issue described in #4018 for integer sample and line values, but the problem will persist when calling `GetLocalNormal` with non-integer sample and line values. Since phocube always uses the center of the pixel, PR #4214 will fix this problem for phocube runs on push frame images, but not fix the problem in general. 

**How to reproduce**  
This problem can be reproduced by trying to calculate a local normal near the edge of a line near the edge of a framelet. 

**Possible Solution**  
Our proposed solution is to extract the part of the `GetLocalNormal()` function that determines the four points to use to calculate the local normal, into a new function inside the `Camera` class, and then override this method in the `PushFrameCamera` class to include a check to make sure that all points used to calculate the local normal are within the same framelet. If they are not, there are a couple of options for how to proceed: 
    * Use the minimum distance to a pixel edge as the offset value for the points used to calculate the local normal (Possible failure mode: if the minimum distance is _very small_ this might not produce the best result.)
    * Do a right or left approximation, rather than an approximation with centers in the input value. 

**Additional context**

**Comment by jessemapel** [comment]
This is effectively a finite difference approximation of the surface. In that context, the correct solution would be to do a central difference unless one of your points would fall outside of the domain (e.g. a framelet); in that case you would a one-sided difference. Here's a more concrete example:

Let's say we have 16 line framelets, if we are finding the local normal at line 8, then we can easily just do +/- 0.5 lines. If we are instead doing the local normal at line 16.25 (16 is the *middle* of the line) then we can't do that because 16.75 is on the next framelet. So, we should instead do a left-difference using 16.25 and 15.25. Similarly if we are computing the local normal at line 0.6 we should do a right-difference using 0.6 and 1.6.

**Comment by victoronline** [comment]
Are we having anyone look into this? This could cause an issue on photometric sites with short exposure NAC observations for PAN sites.

**Comment by jessemapel** [comment]
@victoronline @scsides Did the fix in #4214 resolve this enough for current processing?

**Comment by victoronline** [comment]
That only fixed for pushframe cameras but not for others.

**Comment by jessemapel** [comment]
This is only an issue with push-frame cameras though. For non-pushframe cameras adjacent lines are assumed to be continuous on the ground by the camera model.

**Comment by victoronline** [comment]
@jessemapel After speaking with our science team, I was able to verify that pr#[4214](https://github.com/USGS-Astrogeology/ISIS3/pull/4214) fixes this issue for NAC and WAC processing.

**Comment by jessemapel** [comment]
The changes in #4214 are sufficient for current push frame models in ISIS. If we end up needing higher accuracy in future push frame models we can come back to this.
