### ISSUE TITLE
Remove ISIS3.6.0 from Anaconda Cloud

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#4262]
I am writing to start a discussion about removing ISIS 3.6.0 from Anaconda cloud in order to free up space for new file uploads. ISIS 3.6.0 was our first release via anaconda and included the full docs. Therefore, the Mac and linux builds are 212MB and 425MB, respectively. These release have generated a total of 127 downloads. I am not able to see when the most recent download of ISIS3.6.0 was, but do see that our most recent release under the isis3 name (3.9.1) has been downloaded a combined 676 times.

I would propose removing ISIS3.6.0 from anaconda cloud. This version will then no longer be publicly available though should be buildable if an interested party wanted to pull that release from this repository and seek out any dependencies that may no longer be available on anaconda (i.e., some of our third party dependencies from 2+ years ago may no longer be available from those package maintainers).

Thoughts?

**Comment by jessemapel** [comment]
ISIS 3.6.0 is in a weird spot because it is after the last rsync'able version (3.5.2) and before the last ISIS3 version (3.10.2). I think it can be safely removed from anaconda.

ISIS 3.6.1 and ISIS 3.6.2 are still available and have fairly minor changes compared to 3.6.0 if someone wants 3.6.X.

**Comment by AndrewAnnex** [comment]
Could an archive of the artifacts be hosted internally for history/emergency use, or until the USGS hosts their own channel (ie via [quetz](https://github.com/mamba-org/quetz)) In short I think it is a very bad practice for versions to disappear, even though the probability of this negatively effecting anyone is very low.

**Comment by jessemapel** [comment]
@AndrewAnnex We have copies of the conda-build tarballs from all of the builds from 3.6.0 on saved and backed up so if there is a need for it, we can provide the tarball. I doubt we would be able to host our own Conda package server specifically for this.

**Comment by AndrewAnnex** [comment]
Oh to be clear the reason to self host would be to avoid the space limitations of hosting on anaconda cloud and institutional independence, not just for hosting this specific version.

-Andrew Annex

**Comment by jlaura** [comment]
ISIS3.6.0 has been removed from anaconda cloud.
