### ISSUE TITLE
ISIS 4.4.0 installation issue

### ISSUE THREAD

**Issue by wterryf** [DOI-USGS/ISIS3#4271]
**ISIS version(s) affected**: 4.4.0

**Description**  
I'm having trouble installing ISIS 4.4.0 via conda.

**How to reproduce**  
I created a new anaconda environment and activated it. I did the usual conda install command:

conda install -c usgs-astrogeology isis

After solving the environment, it offers to install the 4.3.0 version. I've tried this off and on for the last week and on both Linux and MacOS platforms with the same results. If I ask for the 4.4.0 version specifically:

conda install -c usgs-astrogeology isis=4.4.0

I get a package not found error.

**Possible Solution**  

**Additional context**

**Comment by rbeyer** [comment]
https://astrodiscuss.usgs.gov/t/isis-version-4-4-release-delayed/600

**Comment by jessemapel** [comment]
As Ross pointed out, the 4.4.0 public release isn't out yet. If you are having issues installing it once it's release please re-open this issue.
