### ISSUE TITLE
Add unit test for OSIRIS-REx SamCam

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4280]
**Description**  

Now that the OSIRIS-REx mission has gone to Bennu and collected a sample, we should add a unit test for SamCam.

This is a continuation of work discussed under #4221 

**Example**  

This can match the existing PolyCam and MapCam instruments from #4221 and #4060

@KrisBecker Can you point us to a good SamCam image for this?

**Comment by KrisBecker** [comment]
Try this one: https://sbnarchive.psi.edu/pds4/orex/orex.ocams/data_calibrated/sample_collection/20200414T224222S022_sam_radL2pan5.fits

**Comment by KrisBecker** [comment]
Important note: The SamCam orientation (TRANS/ITRANS) and focal length from IAK v10 is updated. v10 may work OK for the SamCam in ISIS4. I can also provide some caminfo/phocube output for confirmation if needed.
