### ISSUE TITLE
hi2isis does not properly convert MRO:ADC_TIMING_SETTINGS label from .IMG to .cub file

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#4290]
**ISIS version(s) affected**: at least 3.9+

**Description**  
HiRISE EDR .IMG files have an `MRO:ADC_TIMING_SETTINGS` in their `INSTRUMENT_SETTING_PARAMETERS` group.

When ISIS `hi2isis` runs, the resulting value of `ADCTimingSetting` is always the value `-9999` regardless of the original value in the EDR file.

**How to reproduce**  
Pick any HiRISE EDR, run `hi2isis`.

**Possible Solution**  
I suspect the problem is with `$ISISROOT/appdata/translations/MroHiriseInstrument.trn` whose `ADCTimingSetting` group is looking for the `MRO:ADC_TIMING_SETTING` key which doesn't have the trailing "S" that the key in the PDS label actually has.

I'm not sure if the PDS labels perhaps changed over time (in which case either the singular or plural version of the key should be retained in the translation file) or if this has just always been broken.  I have a copy of the old version of the ISIS data area and it appears that there has been no trailing "S" since hiriseInstrument.trn.2006-03-30 (which was before launch).  I checked an "early" HiRISE EDR, and it has the "S" on the label and indicates that it was created with software from 2006, so this has probably always been a problem.

This means that every cube file `hi2isis` has ever written has a `ADCTimingSetting = -9999`.  Not sure if an "s" should be placed on the end of the label in the cube file or not when this is fixed.  Since it has always been -9999, nobody has *probably* been relying on it, but they might be?

**Comment by jessemapel** [comment]
This is also present in the test data for hi2isis. I suspect this is a case of it always being incorrect, but no one noticing.
