### ISSUE TITLE
qnet will not open a .lis

### ISSUE THREAD

**Issue by shawn-brueshaber** [DOI-USGS/ISIS3#4341]
**ISIS version(s) affected** 3.6. MacOS

**Description**  
Attempting to use qnet and it keeps throwing an error about the list:

Error processing cube list.  
**USER ERROR** Can't open or invalid file list [/Users/shawnrb/Desktop/Red_list.lis].
**USER ERROR** FileName [RED_A09.cub] can not be added to serial number list.
**USER ERROR** Invalid serial number [Unknown] from file [RED_A09.cub].

I have tried copying and pasting the location of the .lis and .cub files to the Desktop from their original location (Desktop/users/shawnrb/Juno_Orbit27/7/file.cub.  I've tried changing the names of the .lis and .cub files thinking maybe their original names were too long.  I've tried adding their complete file path to the list of cubs as well. Nothing works so far.  These cubs open just fine with qview no matter what so I'm very perplexed as to why qnet barfs and I'm dead in the water until I get this figured out.

list name:  Red_list.lis. 
lis contents:
 RED_A09.cub
 RED_B10.cub
 RED_C11.cub

**Comment by rbeyer** [comment]
I think I've run into something like this.  Does your Red_list.lis file end with the "b" in RED_C11.cub, or is there a "carriage return/linefeed" character after it?  If not, trying putting one there.  If you're creating this file programmatically, you might be putting and end-of-line characters between the elements, but not after the last one.

**Comment by shawn-brueshaber** [comment]
Hi,

No, this doesn’t appear to be the problem.  I literally created a new list file and made certain there were carriage returns after each entry.  No dice.

Thanks,

-Shawn

**Comment by lwellerastro** [comment]
> USER ERROR FileName [RED_A09.cub] can not be added to serial number list.
> USER ERROR Invalid serial number [Unknown] from file [RED_A09.cub].

Hi @shawn-brueshaber, qnet is specifically complaining about not being able to access/construct a serial number for your image.  Qview does not require this information but control network programs do.  This sounds like a problem with the data area.  Could you run the program getsn and let's us know what your results are.  If it is "Unknown" then key files are missing.  I won't be able to help you with data area setup issues, but when available one of the developers can.  You might poke around other similar posts in the meantime to do some trouble-shooting on your own.

**Comment by jessemapel** [comment]
It looks like it cannot create a serial number for the image, do you have your data area downloaded properly? Check that `$ISISDATA/juno/translations/junoSerialNumber0001.trn` exists. It could be that you downloaded the ISIS 4 data area which does not contain these translation files, they were moved into the distribution.

See the [Readme](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#versions-of-the-isis-data-area) for more information

**Comment by shawn-brueshaber** [comment]
Hi Jesse,

That file is there.  Contents are:

ObservationKeys = 4
Group = Keyword1
  Auto
  InputKey       = SpacecraftName
  InputGroup     = "IsisCube,Instrument"
  InputPosition  = (IsisCube, Instrument)
  OutputName     = Keyword1
  OutputPosition = (Group, SerialNumberKeywords)
  Translation    = (*, *)
End_Group

Group = Keyword2
  Auto
  InputKey       = InstrumentId
  InputGroup     = "IsisCube,Instrument"
  InputPosition  = (IsisCube, Instrument)
  OutputName     = Keyword2
  OutputPosition = (Group, SerialNumberKeywords)
  Translation    = (*, *)
End_Group

Group = Keyword3
  Auto
  InputKey       = StartTime
  InputGroup     = "IsisCube,Instrument"
  InputPosition  = (IsisCube, Instrument)
  OutputName     = Keyword3
  OutputPosition = (Group, SerialNumberKeywords)
  Translation    = (*, *)
End_Group

Group = Keyword4
  Auto
  InputKey       = FrameletNumber
  InputGroup     = "IsisCube,Instrument"
  InputPosition  = (IsisCube, Instrument)
  OutputName     = Keyword4
  OutputPosition = (Group, SerialNumberKeywords)
  Translation    = (*, *)
End_Group

Group = Keyword5
  Auto
  InputKey       = FilterName
  InputGroup     = "IsisCube,BandBin"
  InputPosition  = (IsisCube, BandBin)
  OutputName     = Keyword5
  OutputPosition = (Group, SerialNumberKeywords)
  Translation    = (*, *)
End_Group


End

**Comment by shawn-brueshaber** [comment]
Hello,

I got an “unknown” on running that command.  I do have the  file $ISISDATA/juno/translations/junoSerialNumber0001.trn right where it is supposed to be.

Thanks,

-Shawn

**Comment by jessemapel** [comment]
@shawn-brueshaber Can you post the label from the first image?

**Comment by shawn-brueshaber** [comment]
Hi Jesse,

The first is JNCE_2020154_27C00007_V01_RED_0007.cub and the second is JNCE_2020154_27C00007_V01_RED_0012.cub. I’ve tried using these names and tried simpler ones such as RED7 and RED12.

Both cubs are generated by junocam2isis on JNCE_2020154_27C00007_V01.LBL and then running spiceinit on them.  Here are the contents of said label file:

PDS_VERSION_ID                = PDS3

/* FILE CHARACTERISTICS */

RECORD_TYPE                   = FIXED_LENGTH
RECORD_BYTES                  = 1648
FILE_RECORDS                  = 10752

/* POINTERS TO DATA OBJECTS */

^IMAGE                        = "JNCE_2020154_27C00007_V01.IMG"

/* IDENTIFICATION DATA ELEMENTS */

FILE_NAME                     = "JNCE_2020154_27C00007_V01.IMG"
SPACECRAFT_NAME               = JUNO
MISSION_PHASE_NAME            = "SCIENCE ORBITS"
TARGET_NAME                   = "JUPITER"
INSTRUMENT_ID                 = "JNC"
INSTRUMENT_HOST_NAME          = "JUNO"
INSTRUMENT_NAME               = "JUNO EPO CAMERA"
PRODUCER_ID                   = JUNO_JUNOCAM_TEAM
DATA_SET_ID                   = "JUNO-J-JUNOCAM-2-EDR-L0-V1.0"
STANDARD_DATA_PRODUCT_ID      = "JUNOCAM-EDR"
PRODUCT_CREATION_TIME         = 2020-09-30T19:48:03
PRODUCT_VERSION_ID            = "01"
PRODUCT_ID                    = "JNCE_2020154_27C00007_V01"
SOURCE_PRODUCT_ID             = "3D-09001B0007-2020-154T12.50.00"
START_TIME                    = 2020-06-02T09:41:02.680
IMAGE_TIME                    = 2020-06-02T09:41:02.680
STOP_TIME                     = 2020-06-02T09:41:13.040
SPACECRAFT_CLOCK_START_COUNT  = "644363187:218"
SPACECRAFT_CLOCK_STOP_COUNT   = "N/A"

/* DESCRIPTIVE DATA ELEMENTS */

ORBIT_NUMBER                  = 27
SOFTWARE_NAME                 = "JUNOMAKEPDS.PY 0.9"
PROCESSING_LEVEL_ID           = "2"
FOCAL_PLANE_TEMPERATURE       = 255.7 <K>
INTERFRAME_DELAY              = 0.370 <s>
SUB_SPACECRAFT_LATITUDE       = 73.1077
SUB_SPACECRAFT_LONGITUDE      = 201.1509
SPACECRAFT_ALTITUDE           = 50165.1 <km>
SOLAR_DISTANCE                = 7.7362e+08 <km>
SAMPLE_BIT_MODE_ID            = "SQROOT"
EXPOSURE_DURATION             = 28.800000 <ms>
JNO:TDI_STAGES_COUNT          = 9
SAMPLING_FACTOR               = 1
FILTER_NAME                   = ('BLUE', 'GREEN', 'RED')
COMPRESSION_TYPE              = "INTEGER COSINE TRANSFORM"
RATIONALE_DESC                = "PJ27 Northern Circumpolar Cyclones (relative
time: PJ27-000T00:38)"

/* DATA OBJECT DEFINITIONS */

OBJECT                        = IMAGE
  LINES                       = 10752
  LINE_SAMPLES                = 1648
  SAMPLE_TYPE                 = UNSIGNED_INTEGER
  LINE_PREFIX_BYTES           = 0
  LINE_SUFFIX_BYTES           = 0
  SAMPLE_BITS                 = 8
  SAMPLE_BIT_MASK             = 2#11111111#
  MD5_CHECKSUM                = "e02500c0fe08e7223fd2d58c4f53a181"
END_OBJECT                    = IMAGE
END

**Comment by jessemapel** [comment]
Can you post the cube label from RED_A09.cub?

**Comment by shawn-brueshaber** [comment]
I’m not sure what you mean “post the cube label.”  Can you describe how to go about doing that?

Thanks,

Shawn

**Comment by jessemapel** [comment]
Run the catlab program on the Cube file to get the Cube label, we don't use the original PDS labels, we transfer most of keywords to a new label that we also add some extra data to.

**Comment by shawn-brueshaber** [comment]
Hi Jesse,

Ok, I ran catlab on the two cubes I mentioned.  The files are attached.

Thanks,

-Shawn

**Comment by jessemapel** [comment]
@shawn-brueshaber I can't see the attachments. You may need to respond on Github directly.

**Comment by shawn-brueshaber** [comment]
> @shawn-brueshaber Do I can't see the attachments. You may need to respond on Github directly.


[catlab_RED_0012.txt](https://github.com/USGS-Astrogeology/ISIS3/files/6101615/catlab_RED_0012.txt)
[catlab_RED_0007.txt](https://github.com/USGS-Astrogeology/ISIS3/files/6101616/catlab_RED_0007.txt)

**Comment by jessemapel** [comment]
Here's the issue:

```
Group = Keyword4
  Auto
  InputKey       = FrameletNumber
  InputGroup     = "IsisCube,Instrument"
  InputPosition  = (IsisCube, Instrument)
  OutputName     = Keyword4
  OutputPosition = (Group, SerialNumberKeywords)
  Translation    = (*, *)
End_Group
```

Is looking for the keyword FrameletNumber on the cubes, but they have FrameNumber. It looks like this was changed in https://github.com/USGS-Astrogeology/ISIS3/commit/556ca197336b495a1b3bcfd76b0147f50fe5c73e but the serialnumber translation didn't get changed.

@shawn-brueshaber For right now, replace 

```
  InputKey       = FrameletNumber
```

with 

```
  InputKey       = FrameNumber
```

in $ISISDATA/juno/translations/junoSerialNumber0001.trn

This is still present in dev, even though the bug was reported on 3.6.

**Comment by shawn-brueshaber** [comment]
Ok, made the change and I’m still getting the same error.

**Comment by jessemapel** [comment]
That was all I needed to do for getsn to work with your cube labels in 4.4.0. Can you double check that your translation file looks like the attached translation file (except with .trn as the extension). You can also try installing ISIS 4.4.0 and then modifying the same file at `$ISISROOT/appdata/translations/JunoJunoCamSerialNumber.trn`.
[JunoJunoCamSerialNumber.txt](https://github.com/USGS-Astrogeology/ISIS3/files/6102878/JunoJunoCamSerialNumber.txt)

**Comment by shawn-brueshaber** [comment]
The file name was the problem.  I took JunoJunoCamSerialNumber.trn and dropped it into the appropriate directory.  There was no such file name there, only JunoSerinalNumber0001.trn.  Qnet now allows me to select the list I want.
