### ISSUE TITLE
Vikcal gives different results based on OS 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#4345]
**ISIS version(s) affected**: 4.x.x

**Description**  

Vikcal produces several coefficients as part of the calibration routine and they differ between OSes. See: https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/viking/apps/vikcal/CalParameters.cpp#L341

Linux:
A: -8.6736173798840401e-18
B: -1.0740377771184499e-18
C: 1.1926223897340501e-18
D: 1.6872896309305699e-18

MacOS:
A: -1.73472347597681e-18
B: 6.6576789654188e-19
C: 1.26851654180804e-17
D: -1.02999206386123e-18

E Coeff matches on both OSes. 

Nothing about the method is different between OSes but still derive different results. 

**How to reproduce**  

run vikcal on any Viking cube (e.g. from the old ISIS test data area) and compare the [A-D]Coeff keywords in the `Radiometry` PvlGroup. 

**Possible Solution**  

I have not managed to dig too much into why they differ or how much it matters. It cropped up while making GTests for vikcal and the old Makefile tests did not catch it as `cubediff` does not compare labels. It's possible that I am just misunderstanding them and this is expected or inconsequential as the final DNs are not affected by this difference. Otherwise, this may be an interpolation difference between the two operating systems. 

**Additional context**

**Comment by jessemapel** [comment]
We should at least spend some time investigating this issue and see what the impact/extent is.

**Comment by tgiroux** [comment]
In CalParameters, `lsq.Solve();` runs `LeastSquares::SolveSVD()`. If we do `lsq.Solve(LeastSquares::QRD);` to instead run `LeastSquares::SolveQRD()`, Radiometry coefficients all match between OSX and linux. The results are different from either SVD outputs though.
