### ISSUE TITLE
Linking error on CentOS 7.x

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#435]
With the new cmake development environment linking fails on CentOS 7.x

commands:

```
cd ./isis
conda env create -n isis3 -f environment.yml
source activate isis3
mkdir build
cd build
cmake .. (cmake flags not included)
make
 
```

error:
 
```
[ 40%] Linking CXX shared library ../lib/libisis3.so
[ 40%] Built target isis3
Scanning dependencies of target voyager
[ 40%] Building CXX object objects/CMakeFiles/voyager.dir/voyager/objs/VoyagerCamera/VoyagerCamera.cpp.o
[ 40%] Linking CXX shared library ../lib/libvoyager.so
[ 40%] Built target voyager
Scannig dependencies of target voycal_app
[ 40%] Building CXX object objects/CMakeFiles/voycal_app.dir/voyager/apps/voycal/voycal.cpp.o
[ 40%] Linking CXX executable ../bin/voycal
../lib/libisis3.so: error: undefined reference to 'pcl::io::load(std::string const&, pcl::PolygonMesh&)'
../lib/libisis3.so: error: undefined reference to 'geos::io::WKTReader::read(std::string const&)'
../lib/libisis3.so: error: undefined reference to 'geos::io::WKTWriter::write(geos::geom::Geometry const*)'
../lib/libisis3.so: error: undefined reference to 'geos::geom::Coordinate::toString() const'
../lib/libisis3.so: error: undefined reference to 'geos::operation::valid::TopologyValidationError::toString()'
../lib/libisis3.so: error: undefined reference to 'google::protobuf::internal::fixed_address_empty_string'
../lib/libisis3.so: error: undefined reference to 'google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
../lib/libisis3.so: error: undefined reference to 'google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
../lib/libisis3.so: error: undefined reference to 'google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
../lib/libisis3.so: error: undefined reference to 'google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
../lib/libisis3.so: error: undefined reference to 'google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
../lib/libisis3.so: error: undefined reference to 'google::protobuf::Message::GetTypeName() const'
../lib/libisis3.so: error: undefined reference to 'google::protobuf::Message::InitializationErrorString() const'
../lib/libisis3.so: error: undefined reference to 'google::protobuf::internal::OnShutdownDestroyString(std::string const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [objects/CMakeFiles/voycal_app.dir/build.make:290: bin/voycal] Error 1
make[1]: *** [CMakeFiles/Makefile2:2806: objects/CMakeFiles/voycal_app.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by jessemapel** [comment]
This appears to a compiler issue, this is happening with gcc version 4.8.5. The new ISIS dependencies that astro is maintaining are being compiled with gcc 7. Currently, there are not plans to support older versions of gcc, but this could be done by modifying the recipes in https://github.com/USGS-Astrogeology/isis3_dependencies.

**Comment by jlaura** [comment]
Since the ISIS3 dependencies are being installed into a conda env, I wonder if it makes sense to test install GCC7 into the same conda env, activating that env, ensuring that CMake is aimed at the new updated compiler and then testing.  

I would suggest that this is safe as gcc7 is being installed into a sequestered env and should not pollute the system paths at all. The only potential issues that could crop up would be links to low level graphics libraries that conda chooses not to support. Someone trying this would want to run the test suite and then manually play with a few of the GUI apps.

**Comment by jessemapel** [comment]
Some additional background information:

This is an issue because with the new cmake system we are moving to supporting more recent Operating Systems for development. Currently, we are supporting Mac OS 10.13, Fedora 28, and Ubuntu 18 for development.

We are still supporting execution on older operating systems by deploying builds from newer systems on them and then running the regression test suite. We are also still supporting bug fixes on older systems, but expect fewer due to a more homogeneous development environment.

This is our current plan and we are open to taking input from the community on which systems people would like to develop on.

**Comment by jessemapel** [comment]
Everything I'm seeing says that gcc 7 v gcc 4 shouldn't matter. Maybe this is something different?

**Comment by jessemapel** [comment]
or not https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by jlaura** [comment]
@jessemapel Can we confirm that the build is trying to link against our PCL, GEOS, and protobuf and not a system install of these on the Centos Box?  Perhaps it makes sense to have @chrisryancombs fire up a clean Centos7 container and test a build inside of there?

**Comment by jessemapel** [comment]
See #465 for further developments on this issue.
