### ISSUE TITLE
spiceinit issues

### ISSUE THREAD

**Issue by csedwar** [DOI-USGS/ISIS3#4356]
I'm not sure why this isn't working. Is this an environment issue? the MissionName2DataDir.trn appears to have the appropriate data in it to make this translation.

[cedwards]$ wget http://static.mars.asu.edu/pds/ODTSDP_v1/data/odtir1_0006/i066xxrdr/I06638006RDR.QUB

[cedwards]$ pds2isis from=I06638006RDR.QUB to=I06638006.lev1.cub
pds2isis: Importing
100% Processed

[cedwards]$ spiceinit from=I06638006.lev1.cub web=yes
**PROGRAMMER ERROR** No value or default value to translate for translation group [MissionName] in file [/nfs/software/isis4/anaconda_isis4/appdata/translations/MissionName2DataDir.trn].

isis version 4.4.0

[print.prt.txt](https://github.com/USGS-Astrogeology/ISIS3/files/6133521/print.prt.txt)

**Comment by jessemapel** [comment]
Is there a reason why you are using pds2isis instead of [thm2isis](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/thm2isis/thm2isis.html)?

The general import programs like pds2isis and std2isis do not import all of the information required for camera models, which appears to be the issue you are running into here and in #4357

**Comment by csedwar** [comment]
I’ve always used pds2isis (I believe). I can try to reproduce w/thm2isis

**Comment by csedwar** [comment]
converting to using thm2isis fixed the error above but did not fix the webspice issue #4357 

cedwards@tinto:~/aaron_test$ spiceinit from=I06638006.lev1.cub web=yes
spiceinit: Requesting Spice Data
100% Processed
**ERROR** The server sent an unrecognized response [Group = Kernels
  NaifFrameCode             = -53031
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = $base/kernels/pck/pck00009.tpc
  TargetPosition            = ($base/kernels/spk/de430.bsp,
                               $base/kernels/spk/mar097.bsp)
  InstrumentPointing        = ($odyssey/kernels/ck/m01_sc_map6.bc,
                               $odyssey/kernels/fk/m01_v29.tf)
  Instrument                = Null
  SpacecraftClock           = $odyssey/kernels/sclk/ORB1_SCLKSCET.00265.tsc
  InstrumentPosition        = $odyssey/kernels/spk/m01_map6.bsp
  InstrumentAddendum        = $odyssey/kernels/iak/themisAddendum003.ti
  ShapeModel                = $base/dems/molaMarsPlanetaryRadius0005.cub
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 2
  Error                     = "The ck rotation from frame -53000 can not be
                               found due to no pointing available at requested
                               time or a problem with the frame"
End_Group
3c73706963655f646174613e0a20203c6170706c69636174696f6e5f6c6f673e0a343737323666373537303230336432303462363537323665363536633733306132303230346536313639363634363732363136643635343336663634363532303230323032303230323032303230323032303230323032303364323032643335333333303333333130613230323034633635363137303533363536333666366536343230323032303230323032303230323032303230323032303230323032303230336432303234363236313733363532663662363537323665363536633733326636633733366232663665363136393636333033303331333232653734366337333061323032303534363137323637363537343431373437343639373437353634363535333638363137303635323032303230323032303230323033643230323436323631373336353266366236353732366536353663373332663730363336623266373036333662333033303330333033393265373437303633306132303230353436313732363736353734353036663733363937343639366636653230323032303230323032303230323032303230323032303364323032383234363236313733363532663662363537323665363536633733326637333730366232663634363533343333333032653632373337303263306132303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303234363236313733363532663662363537323665363536633733326637333730366232663...........................................6974696f6e3e0a20203c2f7461626c65733e0a3c2f73706963655f646174613e0a]

**Comment by jessemapel** [comment]
@csedwar Can you post your cube label after thm2isis?

**Comment by csedwar** [comment]
```

Object = IsisCube
  Object = Core
    StartByte   = 65537
    Format      = Tile
    TileSamples = 320
    TileLines   = 368

    Group = Dimensions
      Samples = 320
      Lines   = 14352
      Bands   = 3
    End_Group

    Group = Pixels
      Type       = Real
      ByteOrder  = Lsb
      Base       = 0.0
      Multiplier = 1.0
    End_Group
  End_Object

  Group = Instrument
    SpacecraftName        = MARS_ODYSSEY
    InstrumentId          = THEMIS_IR
    TargetName            = MARS
    MissionPhaseName      = MAPPING
    StartTime             = 2003-06-14T00:02:35.872
    StopTime              = 2003-06-14T00:10:34.270
    SpacecraftClockCount  = 740016275.000
    GainNumber            = 16
    OffsetNumber          = 2
    MissingScanLines      = 0
    TimeDelayIntegration  = ENABLED
    SpacecraftClockOffset = 0.0 <seconds>
  End_Group

  Group = Archive
    DataSetId               = ODY-M-THM-3-IRRDR-V1.0
    ProducerId              = ODY_THM_TEAM
    ProductId               = I06638006RDR
    ProductCreationTime     = 2004-10-13T14:14:01
    ProductVersionId        = 1.1
    OrbitNumber             = 06638
    FlightSoftwareVersionId = 1.00
    CommandSequenceNumber   = 6638
    Description             = "systematic mapping"
  End_Group

  Group = BandBin
    OriginalBand = (1, 2, 3)
    Center       = (8.56, 12.57, 14.88)
    Width        = (1.16, 0.81, 0.87)
    FilterNumber = (4, 9, 10)
    BandNumber   = (4, 9, 10)
  End_Group

  Group = Kernels
    NaifFrameCode = -53031
  End_Group
End_Object

Object = Label
  Bytes = 65536
End_Object

Object = History
  Name      = IsisCube
  StartByte = 55177217
  Bytes     = 456
End_Object

Object = OriginalLabel
  Name      = IsisCube
  StartByte = 55177673
  Bytes     = 4270
End_Object
End
```

**Comment by csedwar** [comment]
To be clear the error i am seeing above is occurring on image ID I06638006, whereas if I run the same set of commands (including wget to download) and thm2isis I do not get an error on other images (e.g. I01237007)

To reproduce yourself, you can do:

Does not Work with webspice (but does work with local kernels)
wget http://static.mars.asu.edu/pds/ODTSDP_v1/data/odtir1_0006/i066xxrdr/I06638006RDR.QUB
thm2isis from=I06638006RDR.QUB to=I06638006.lev1.cub
spiceinit from=I06638006.lev1.cub web=yes

works with webspice and local kernels
wget http://static.mars.asu.edu/pds/ODTSDP_v1/data/odtir1_0002/i012xxrdr/I01237007RDR
thm2isis from=I01237007RDR.QUB to=I01237007.lev1.cub
spiceinit from=I01237007.lev1.cub

**Comment by csedwar** [comment]
any updates here?

**Comment by jessemapel** [comment]
Sorry, I haven't been able to figure out what's causing this issue yet. It seems to be related to #4044

**Comment by acpaquette** [comment]
@csedwar This should be fixed as of 4/20/2021. There was extraneous output making it into the response from the spiceserver. This extraneous output was piped to `/dev/null` so you should be able to spiceinit your themis image via the web!
