### ISSUE TITLE
findimageoverlaps issue with Apollo panoramic images (wrong instrument specification)

### ISSUE THREAD

**Issue by dsvolkov** [DOI-USGS/ISIS3#4359]
**ISIS version(s) affected**: 4.4.0

**Description**  
findimageoverlaps running with Apollo panoramic images gives an error:

```
**USER ERROR** FileName [***] can not be added to serial number list.
**USER ERROR** Invalid serial number [Unknown] from file [***].
```

**How to reproduce**  
```
std2isis from=AS15-P-9527.jp2 to=AS15-P-9527.cub
apollopaninit from=AS15-P-9527.cub microns=5 mission=apollo15 gmt="1971-08-01 11:30:09.762" \
	lon_nadir=40.2441147 lat_nadir=16.1111141  craft_altitude=113.149 lon_int=40.2441147 lat_int=16.0694441 \
	vel_azm=270 vel_horiz=1.61 vel_radial=0.1 
# next line - just for performance reasons
reduce from=AS15-P-9527.cub to=AS15-P-9527.x10.cub SSCALE=10 LSCALE=10	
camstats from=AS15-P-9527.x10.cub sinc=10 linc=10 attach=true 
footprintinit from=AS15-P-9527.x10.cub sinc=10 linc=10

# any other cube, I used LRONAC image
lronac2isis from=M108971316LE.IMG to=M108971316LE.cub
spiceinit from=M108971316LE.cub
camstats from=M108971316LE.cub sinc=10 linc=10 attach=true
footprintinit from=M108971316LE.cub

printf "AS15-P-9527.x10.cub\nM108971316LE.cub\n" > tmp.lis
findimageoverlaps fromlist=tmp.lis overlaplist=tmp.ovr
```

**Possible Solution**  
I suppose the issue is instrument specification in $ISISROOT/appdata/translations/Instruments.trn
When I changed PAN to APOLLO_PAN in InstrumentName group findimageoverlaps works fine.

Group = InstrumentName
  #Translation = (Panoramic, PAN)              
  Translation = (Panoramic, APOLLO_PAN)

**Comment by jessemapel** [comment]
Weirdly inconsistent with Apollo Metric which uses just Metric. Generally we use more descriptive names than "Metric" or "Pan" for this stuff so I think changing to "APOLLO_PAN" to match what apollopaninit is doing makes sense.

**Comment by jessemapel** [comment]
I would also caution if you are doing extensive processing of the apollo panoramic data. It's got a whole lot going on and the current version of the software does not account for many things. In particular, the way that it handles time is not correct. The Apollo panoramic cameras moved both along-track and cross-track at variable rates during exposure. The current software does not account for the actual variable cross-track movement which can actually vary quite sharply within an image.

See Ken Edmundson's paper on this topic for more information:

https://www.int-arch-photogramm-remote-sens-spatial-inf-sci.net/XLII-1/133/2018/

Unfortunately we were not able to complete work on the Apollo panoramic dataset and the updated software was not finished.

**Comment by dsvolkov** [comment]
@jessemapel thanks for the caution and the paper. 

Wondering do you have any plans to implement these things in the future and a specific timeline when these updates will be available? I checked https://astrodiscuss.usgs.gov but didn't find anything.

**Comment by jessemapel** [comment]
Unfortunately the project is dead in the water at the moment. Ken and Tammy Becker who were leading the effort have retired from the USGS and we haven't gotten a ton of community interest in updating the Apollo Pan software. I worked on the project as a student and have all of the project documentation, but it would take some work to get back to where we were. There has been some discussion of a potential PDART or similar project to complete the work but that would be several years off and other processing work has been designated as a higher priority here at the USGS.

So, if there is substantial community interest in rigorous handling of the dataset it's something that can happen, but we just haven't seen that.

**Comment by jessemapel** [comment]
We're not going to fix this bug as the software needs to be entirely re-written. If someone wants to patch this they are welcome to, but it is not a priority right now.
