### ISSUE TITLE
Handmos - A general question

### ISSUE THREAD

**Issue by shawn-brueshaber** [DOI-USGS/ISIS3#4369]
I'm working with JunoCam images and I've run into a problem with attempting to register one image to another.  Currently, I have been manually translating one image relative to the other to align a perceived center of rotation of vortices. 

However, I thought about using tie points to see if I can improve my approach and that lead me to trying qtie.  However, qtie requires a map-projected cub and an unprojected cub.  JunoCam images are really framelets, which restricts the ability to use tie points useful for my cloud tracking work.  I can make a nice map-projected mosaic cub that combines quite a few of the framelets together. However, is there a way I can make an unprojected mosaic for the other required cub for qtie?  Can I do that with handmos?  If so, how do I do this?  I've tried making a hand mosaic with this function starting with a cub.  But as soon as I try to add a second cub, it seems to "erase" the existing cub showing me only the second cub.  I was expecting to see both cubs stitched together. I'm not sure what I'm doing wrong here. 

Thanks,

-Shawn

**Comment by acpaquette** [comment]
@shawn-brueshaber Sorry to get to this so late, I don't know if this is still something you are working on but `junocam2isis` has a `fullccd` option which outputs the framelets as a single cube. I don't know if that will solve your problem but we can look into other options.

Typically for stitching images or ccds together from instruments is accomplished with a `stitch` program but this could also be achieved with something like handmos. Let me know if the `fullccd` option solves your problem or if we need to look into a better solution.
