### ISSUE TITLE
time strings may not be properly conditioned in things that use iTime

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#4370]
**ISIS version(s) affected**: All (tested with 4.2, but this is pervasive).

**Description**  
CSPICE's `str2et_c` function does not properly parse ISO 8601 time formats that use a trailing "Z" as their time zone specifier and will error (however, this feature will be included in the upcoming version of the NAIF SPICE toolkit, N0067, expected summer of 2021).

The [PDS3 specification](https://pds.nasa.gov/datastandards/pds3/standards/sr/Chapter12.pdf) (although not PVL and not ODL) says that "On output, a 'Z' will be appended to label times." (Section 12.3.2.3, PDS Implementation of Dates and Times).  This means that conformant PDS3 label writers should append a "Z" to all times, but many do not.  Anything that reads PDS3 PVL-text should be able to read times with and without the trailing "Z."

If there are functions in ISIS that are "parsing" PVL-text, they must strip the "Z" from any time before passing the string to the CSPICE `str2et_c` function or anything else that can't handle a trailing "Z."

The [iTime constructor](https://github.com/USGS-astrogeology/ISIS3/blob/b8517dc681c4c7365192fc2abdbb43b176c373fd/isis/src/base/objs/iTime/iTime.cpp#L49) seems to be one of these places.

Programs like `spiceinit` and others that may be reading PDS3 labels for a time value are therefore "PDS3 reader software", and must be able to handle the "Z" rather than passing the string onwards to something that is not a "PDS3 reader" (`str2et_c()`) and expecting it to do the right thing (which it doesn't, but will real soon now).

Alternately one could argue that `spiceinit` isn't a PDS "reader" it is just reading an ISIS label, which is just PVL-text that isn't conformant to the PDS3 spec.  Okay, sure.  In that case the various `*2isis` programs are the PDS "readers" and should properly read both kinds of times, and then write whatever kind of PVL that is acceptable in ISIS labels for programs that read them.

**How to reproduce**  
Get the files:
```
> wget https://sbnarchive.psi.edu/pds3/near/NEAR_A_MSI_3_EDR_EROS_ORBIT_V1_0/data/2000/287/iofdbl/m0146863556f4_2p_iof_dbl.lbl
> wget  https://sbnarchive.psi.edu/pds3/near/NEAR_A_MSI_3_EDR_EROS_ORBIT_V1_0/data/2000/287/iofdbl/m0146863556f4_2p_iof_dbl.fit
```

`spiceinit` works fine on these files:
```
> msi2isis from= m0146863556f4_2p_iof_dbl.lbl to= m0146863556f4_2p_iof_dbl.cub
> spiceinit from= m0146863556f4_2p_iof_dbl.cub
```

Set up for failure:
```
> cp m0146863556f4_2p_iof_dbl.lbl z.lbl
```
Edit the *z.lbl file and change 
```START_TIME                    = 2000-10-13T16:08:43.784``` to
```START_TIME                    = 2000-10-13T16:08:43.784Z```

Now:
```
> msi2isis from= z.lbl to= z.cub
> spiceinit from=z.cub
**ERROR** An time string that was either not a time(N/A) or incorrectly
formatted was passed into a naif routine. The short explanation provided
by NAIF is [SPICE(UNPARSEDTIME)]. The Naif error is [The input string
contains an unrecognizable substring beginning at the character marked
by <Z>: "2000-10-13T16:08:43.784<Z>"].
```

Why would some nut-job change the archived PDS3 label?  They wouldn't, I just couldn't find a handy example of a PDS3 label that actually has a time with a trailing "Z" although based on the PDS3 spec they could exist.

**Comment by jessemapel** [comment]
We have actually ran into some issues with this before. I can't remember which, but there is (or at least was) an ingestion app that had to strip the trailing "z" off a time string on ingestion. Also, in the CSM model we have to strip the "z" off and had to add some extra stuff to handle more of ISO 86001. See:

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/CSMCamera/CSMCamera.cpp#L104

and

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/iTime/iTime.cpp#L432

**Comment by krlberry** [comment]
PDS4 labels also use the trailing "Z" by default for UTC times and this has caused issues with ingesting PDS4-formatted imges.

**Comment by rbeyer** [comment]
I don't see a PR that closes this, so removing "inactive" label.

**Comment by scsides** [comment]
@rbeyer: I would agree with the argument that spiceinit is not a PDS reader. It is an ISIS cube label reader. I would also agree that the ingest applications are PDS readers and could handle this, and they do. See: ciss2isis, eis2isis, tgocassis2isis, kaguyami2isis, kaguyatc2isis, and hrsc2isis. I am not aware of any instances where the Z exists and the ISIS code does not remove it before passing it to iTime., only your contrived example.

Can you provide an example where this issue needs to be addressed? If not, I believe this issue should be closed and let any future issues with the Z be taken care of by the new version of the spice library.

**Comment by rbeyer** [comment]
I did provide an example, but what you're really asking is how prevalent or impactful this bug is.  I suspect that it is neither prevalent nor impactful.  However, the other posts on this issue indicate that it has come up.  This is certainly not an issue that is blocking me.  It came up in the course of some other PVL-related work I was doing.

The simple fact is that `spiceinit` incorrectly errors when given absolutely correct PVL.

Marking this as "do not fix" is a completely reasonable response.

**Comment by scsides** [comment]
My point is that spiceinit does not fail on any real data set and therefore there is no bug. The import applications are converting the PDS label to an ISIS label before spiceinit is run. If a PDS3 archive product doesn't meet the ISIS requirements it is up to the ingest program to fix it. This happens all the time. Example, instrument labels have the exposure duration in different units and the ingest or camera model handles it. 

Yes iTime could have handled the Z, and I believe most would say it would have been a better design to have it do so, but many of the ingest apps were written before iTime was, therefore it didn't need to handle the Z (i.e., no kitchen sink programming). It's not a bug to be fixed, it was a good/bad design/circumstance to have the apps deal with it instead of iTime. As you pointed out when ISIS updates to the new spice library, there will be no reason to consider this an issue. @jessemapel and @kberryUSGS where not pointing out bugs in production code. They were pointing out issues that came and passed during development of specific mission support.

As for spiceinit incorrectly erroring when given a correct PVL, I disagree. Correct PVL is not necessarily a correct ISIS cube label.
