### ISSUE TITLE
Error on spiceinit web = 'yes' from = image_cube

### ISSUE THREAD

**Issue by procton** [DOI-USGS/ISIS3#4383]
**ISIS version(s) affected**: x.y.z
4.3.0
**Description**  

Running spiceinit with web=yes from Python script I get the following error "An error occurred when talking to the server. The server closed the connection."
**How to reproduce**  

On any APollo15 image do the following:
apollo2isis from=<name.lbl> to=<cube_name.cub>
spiceinit from=<cube_name.cub> web=yes

**Possible Solution**  

**Additional context**

**Comment by shanebyrneonmars** [comment]
You beat me to it... I was just about to post this problem. (MDIS and CTX data in my case).
I have ISIS 3.10 and 4.1 installed in different conda environments - same behavior in each.

**Comment by jessemapel** [comment]
This is very likely impacting all ISIS versions as they all use the same server. We're working on figuring out what's going on with the server now.

**Comment by procton** [comment]
Any update on this ? Or any idea when the service will be available again ? 
Thank you

**Comment by jessemapel** [comment]
@procton The server is back up and I was able to use it remote. Go ahead and retry using the web=true option.

It appears to have gotten overloaded with requests and failed. We've tweaked some things to avoid this in the future.

**Comment by procton** [comment]
I still have problems, now the error on spiceinit is `The server sent an unrecognized response [3c73706963655f646174613e0a20203c6170706c69636174696f6e5f6c6f673e0a3437373236663735373032303364323034623635373236653635366337333061323032303.....]`

**Comment by procton** [comment]
Now it's working fine, thank you for your help.

**Comment by procton** [comment]
Sorry, the problem is still there again. On spiceinit the following error: `The server sent an unrecognized response [3c73706963655f646174613e0a20203c6170706c69636174696f6e5f6c6f673e0a3437373236663735373032303364323034623635373236653635366337333061323032303.....]`

**Comment by jessemapel** [comment]
It looks like you're running into #4044 

We don't have a fix for that yet but I'll spend some time looking back into it.

For right now, I'm close this and post over there.
