### ISSUE TITLE
ISIS3/cmake Binary Distribution Strategy

### ISSUE THREAD

**Issue by KrisBecker** [DOI-USGS/ISIS3#439]
Not entirely sure what the plans are for a binary distribution of ISIS3/cmake are (exclusively through Anaconda?) but it appears currently all the runtime library dependencies are linked to the Anaconda isis3 env install. Specifically, there are no runtime libraries or plugins in $ISISROOT/3rdParty. This may cause problems for system-wide distributions for ground data processing systems as the individual/account used to pull ISIS3 and install in a traditional setting may not be accessible in all situations causing runtime breakage.
 
I tested a potential solution on my Mac that moved aside the ~/miniconda/envs/isis3/lib to lib.org and then simlinked $ISISROOT/3rdParty/lib -> ~/miniconda/envs/isis3/lib.org (qview, after the move and before the simlink, failed as expected with a library load error). This worked great!  Which means adding a “make dist” or “make deploy” target that simply copies/installs all of ~/miniconda/envs/isis3/lib and plugins to 3rdParty like was done before, or something similar, appears to work just fine.

**Comment by jessemapel** [comment]
We are specifically trying to not copy around the 3rd party libraries and let Anaconda handle them completely.

Our plan for how a system-wide install will be handled is having an anaconda environment with ISIS3 and all of its dependencies installed into it. So, the directories would look like this

* /path/to/some/anaconda/install/envs/isis/
  * bin
    * All of the ISIS3 applications
    * xml
      * All of the ISIS3 application xmls
  * lib
    * The ISIS3 library
    * The ISIS3 3rd party dependencies

ISISROOT would be the root of the environment (so /path/to/some/anaconda/install/envs/isis) and the initIsis script would add the bin directory to the path (/path/to/some/anaconda/install/envs/isis/bin).

**Comment by jessemapel** [comment]
The way this would be setup is just having an anaconda install at a location available to everyone and then installing ISIS into it.

**Comment by jessemapel** [comment]
Tagging @scsides and @ihumphrey-usgs to clarify this if I missed something. All of this will be documented formally in the install documentation for 3.6.0

**Comment by KrisBecker** [comment]
How is $ISIS3DATA going to be distributed?

**Comment by jessemapel** [comment]
$ISIS3DATA will still be distributed through rsync, we are also planning to put the 3.6.0 $ISIS3TESTDATA up on rsync. We're investigating version control stuff like git lfs, but that's very preliminary.

**Comment by jessemapel** [comment]
#443 is working on the documentation for this.

**Comment by jessemapel** [comment]
I feel like we've answered as best we can at the moment so I am going to close this issue. If there's further questions please re-open this issue or make a new one.
