### ISSUE TITLE
Unexpected "nan" in caminfo output

### ISSUE THREAD

**Issue by dpmayerUSGS** [DOI-USGS/ISIS3#4393]
**ISIS version(s) affected**: >=3.10.2 

**Description**  
`caminfo` produces values of "nan" for the `SubSpacecraftGroundAzimuth`, `ParallaxX`, and `ParallaxY` keywords on certain images, even though `caminfo` is still able to compute other angles and even project a footprint onto the target body. I have only found this to affect specific MOC EDRs, THEMIS IR EDRs, and THEMIS VIS EDRs.

**How to reproduce**  
```
moc2isis/thm2isis from=infile to=outfile.cub    #program depends on which image being input, obvs 
spiceinit from=outfile.cub
caminfo from=outfile.cub to=outfile_caminfo.pvl geometry=yes isislabel=yes statistics=yes camstats=yes polygon=yes inctype=vertices numvertices=40

grep "nan" outfile_caminfo.pvl
#    SubSpacecraftGroundAzimuth = nan
#    ParallaxX                  = nan
#    ParallaxY                  = nan

```

**Additional context**  
Complete list of the affected images:
[/pds_san/PDS_Archive/Mars_Global_Surveyor/MOC/mgsc_1029/m03003/m0300359.imq](https://pdsimage.wr.usgs.gov/Missions/Mars_Global_Surveyor/MOC/mgsc_1029/m03003/m0300359.imq)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10066/data/odtie1_0066/r723xxedr/R72340029EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10066/data/odtie1_0066/r723xxedr/R72340029EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10071/data/odtie1_0071/r782xxedr/R78241001EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10071/data/odtie1_0071/r782xxedr/R78241001EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10009/data/odtie1_0009/r094xxedr/R09436025EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10009/data/odtie1_0009/r094xxedr/R09436025EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10008/data/odtve1_0008/v080xxedr/V08090001EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10008/data/odtve1_0008/v080xxedr/V08090001EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10011/data/odtve1_0011/v121xxedr/V12120008EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10011/data/odtve1_0011/v121xxedr/V12120008EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10014/data/odtve1_0014/v148xxedr/V14802004EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10014/data/odtve1_0014/v148xxedr/V14802004EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10017/data/odtve1_0017/v183xxedr/V18386001EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10017/data/odtve1_0017/v183xxedr/V18386001EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10017/data/odtve1_0017/v187xxedr/V18763010EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10017/data/odtve1_0017/v187xxedr/V18763010EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10022/data/odtve1_0022/v236xxedr/V23662019EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10022/data/odtve1_0022/v236xxedr/V23662019EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10024/data/odtve1_0024/v263xxedr/V26315022EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10024/data/odtve1_0024/v263xxedr/V26315022EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10024/data/odtve1_0024/v267xxedr/V26737030EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10024/data/odtve1_0024/v267xxedr/V26737030EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10026/data/odtve1_0026/v280xxedr/V28061017EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10026/data/odtve1_0026/v280xxedr/V28061017EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10030/data/odtve1_0030/v327xxedr/V32776005EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10030/data/odtve1_0030/v327xxedr/V32776005EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10033/data/odtve1_0033/v365xxedr/V36572024EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10033/data/odtve1_0033/v365xxedr/V36572024EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10036/data/odtve1_0036/v399xxedr/V39981004EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10036/data/odtve1_0036/v399xxedr/V39981004EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10042/data/odtve1_0042/v457xxedr/V45719019EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10042/data/odtve1_0042/v457xxedr/V45719019EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10042/data/odtve1_0042/v463xxedr/V46394001EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10042/data/odtve1_0042/v463xxedr/V46394001EDR.QUB)

**Comment by jessemapel** [comment]
@dpmayerUSGS We have a little bit of support time slotted right now. We're primarily focusing on various clean-up issues. Is this a high priority issue for PDS-Pipelines or can it wait until the full support sprint in June?

**Comment by dpmayerUSGS** [comment]
@jessemapel It is impacting PDS project work, so sooner is better than later. I have no idea how simple/difficult it will be to fix this (because I have no idea what's causing it), so I can't speak to whether it makes more sense to tackle during a cleanup sprint or the full support sprint in June.

**Comment by jessemapel** [comment]
It sounds like we should slot it now and at least get an idea of how much there is here @acpaquette

**Comment by acpaquette** [comment]
@jessemapel Sounds good. The only issue is that this is going into ISIS 5.0.1 and I know that @dpmayerUSGS is on an older version of ISIS. Should we be planning to back port a potential fix?

**Comment by jessemapel** [comment]
Let's see how big the fix is before we do that. The ISIS 3 development and testing environment is quite old and may not be fully functionally anymore.
