### ISSUE TITLE
spiceinit error

### ISSUE THREAD

**Issue by fede98765** [DOI-USGS/ISIS3#4395]
Hello,I'm a student at his first experience using ISIS.I'm trying to execute spiceinit command but this error occur:"**ERROR** No existing files found with a numerial version matching [kernels.????.db] in [/home/federico/anaconda3/envs/isis/data/base/kernels/lsk]."
I've downloaded the MRO data following the instruction given by the ISIS document, but the lsk kernel folder didn't occur.
What can I do to risolve this?
Thanks in advance

**Comment by jessemapel** [comment]
You need to also download the base kernels:

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#partial-download-of-isis-base-data

that should fix your problem.

**Comment by fede98765** [comment]
> You need to also download the base kernels:
> 
> https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#partial-download-of-isis-base-data
> 
> that should fix your problem.

Thanks a lot. Now it works perfectly fine.
