### ISSUE TITLE
isis3testData rsync module is failing

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#4397]
**ISIS version(s) affected**: all

**Description** 
Following the instructions in the [wiki](https://github.com/USGS-Astrogeology/ISIS3/wiki/Test-Data-Obtaining,-Maintaining,-and-Submitting), I cannot appear to access or download the isis3testData collection.

**How to reproduce**  
```
$ rsync isisdist.astrogeology.usgs.gov::isis3testData

===============================================================================

                               ISIS SYNC SERVER

-------------------------------------------------------------------------------
   Use of this system constitutes consent to security monitoring and testing.
           All activity is logged with your host name and IP address.
-------------------------------------------------------------------------------

NOTE: For future releases (isis3.6.0 and above), this rsync server will NOT be
      hosting isis3 binaries. Please see the ISIS instal guide at:
             https://github.com/USGS-Astrogeology/ISIS3

      ISIS2 and ISIS3.5.2 will still be available here.
      The data and test data will still be hosted here.

For support and new release notifications please join our discussion forum at:
               https://astrodiscuss.usgs.gov

===============================================================================

@ERROR: chroot failed
rsync error: error starting client-server protocol (code 5) at main.c(1834) [Receiver=3.2.3]
```

**Comment by jlaura** [comment]
@rbeyer Thanks for the heads up. We are working on getting the data shifted over to S3 and to get the download instructions posted. Right now, this is going through a mandatory internal review process. The rsync servers is also just about full as far as I know (I did not check just before writing this), so the behavior that you are seeing is not unexpected.

Is getting access to the test data causing you to be unable to get some work done? If so, we can coordinate an interim solution while the review process is underway.

It looks like we should get the docs updated on the repo so that other users do not experience the same issue AND spend time searching here to ensure that we are aware.

**Comment by rbeyer** [comment]
No, it isn't a blocker.  I was finally actually playing around with compiling ISIS my own self, and I was just following the instructions and came across this error.

**Comment by jessemapel** [comment]
When I checked, we had about 20 GB of space left on the rsync server. It would be enough for the test data, but just barely and we would likely run out of space as new kernels come in.

**Comment by AndrewAnnex** [comment]
@jessemapel is there any way to get the test data currently? I would like to see if I can follow the isis building tutorial as an ASC external user.

**Comment by jessemapel** [comment]
@AndrewAnnex I'm not sure as I'm not working on this thing right now. @jlaura May have an update on where this is at.

**Comment by AndrewAnnex** [comment]
I got an email over the weekend about this from @jlaura so for me this problem is resolved 

-Andrew Annex

**Comment by steo85it** [comment]
I got stuck at the same point: an update on this on the wiki (or even a link on this open issue) would be greatly appreciated. In alternative, a line about how NOT to include tests in the build+install process would also work for me. Thanks!

**Comment by jessemapel** [comment]
@jlaura Is working to update the docs for how to do this. @steo85it To not build the tests add `-DBUILD_TESTS=OFF` to your cmake command.

**Comment by jlaura** [comment]
@Kelvinrr Do you want to post the instructions to the wiki and/or README? All the release requirements are done on my side.

**Comment by steo85it** [comment]
@jlaura while you are at it, it could be worth mentioning how to set the install dir to, e.g., `ISIS3/install` (for consistency with the rest of the tutorial where that folder is created and left empty). Right now, excutables and libraries would just be available in build/ and in `$CONDA_PREFIX`. Adding `-DCMAKE_INSTALL_PREFIX=${ISISROOT}/install` seems to work. 
Just a thought ;)

**Comment by jlaura** [comment]
Please see the updated README with instructions on downloading the test data from AWS S3 using the `rclone` tool.
