### ISSUE TITLE
ISIS3/cmake PostgreSQL Missing

### ISSUE THREAD

**Issue by KrisBecker** [DOI-USGS/ISIS3#440]
It appears the PostgreSQL library is not installed in the Anaconda isis3 environment. This means database access in ISIS3 (and this environment) to PostgreSQL databases may be broken. Specifically, the runtime dependencies for the Qt SQL PostgreSQL driver are:
 
```bash
zion[326]: otool -L ~/miniconda3/envs/isis3/plugins/sqldrivers/libqsqlpsql.dylib
~/miniconda3/envs/isis3/plugins/sqldrivers/libqsqlpsql.dylib:
        @rpath/../plugins/sqldrivers/libqsqlpsql.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/libQt5Sql.5.dylib (compatibility version 5.9.0, current version 5.9.6)
        /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        @rpath/libQt5Core.5.dylib (compatibility version 5.9.0, current version 5.9.6)
        **@rpath/libpq.5.dylib (compatibility version 5.0.0, current version 5.10.0)**
        @rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
 ```
The highlighted PostgreSQL library (libpq) is nowhere to be found in the Python isis3 env.  Looks like simply installing PostgreSQL will solve this problem.
 
FYI, Sqlite and MySQL looks to be intact.

**Comment by jessemapel** [comment]
@ihumphrey-usgs Do you know what's going on with this?

**Comment by KrisBecker** [comment]
Oh, and it would be really great if the Postgis extension is also included in the PostgreSQL install! 

Looks like postgis 2.4.3+9.6.3 may be compatible with Qt 5.9.

**Comment by jlaura** [comment]
Is our ISIS deploy shipping with a QT that is built to support PostGreSQL or is it shipping with PostGreSQL? If the latter, can someone fill me in on why.

**Comment by ihumphrey** [comment]
As @KrisBecker pointed out, when looking at our isis3 dependencies anaconda environment, ldd on the libsqlpsql.so in the environment shows ```libpq.so``` as not found. According to [Qt5's sql driver documentation](http://doc.qt.io/qt-5/sql-driver.html) (for reference):

> To build a driver plugin you need to have the appropriate client library for your Database Management System (DBMS). This provides access to the API exposed by the DBMS, and is typically shipped with it. Most installation programs also allow you to install "development libraries", and these are what you need. These libraries are responsible for the low-level communication with the DBMS.

During the initial part of our Qt5.9.6 build, when resolving dependencies, conda _does_ grab the ```postgresql``` package from the conda-forge channel, which includes ```libpq.so``` as well as the PostgreSQL development headers. 

We will need to figure out why the MySQL and SQLite libraries are part of our isis3 dependencies anaconda environment and why the PostgreSQL is missing from that environment. (The fact that it is missing also exposes that we may need to write a test to check for our "supported" sql drivers with Qt).

@jlaura Right now, afaik Qt is building the sql driver plugins for MySQL, PostgreSQL, and SQLite, which require the appropriate DBMS development package to build. From what I can tell (see above quote regarding "Qt5's sql driver documentation"), the client library is _typically_ shipped with the plugin (I'm not sure if this is the correct interpretation). So it seems like we should ship with the dependencies of the plugin as part of the isis3 dependencies environment?

**Comment by jlaura** [comment]
@ihumphrey-usgs Thanks for the info. I agree with shipping with the client lib, but not necessary with the full DB server implementation. I got the impression from the request for PostGIS (an extension to PostGreSQL that the request was to ship a full Postgres install).

**Comment by ihumphrey** [comment]
@KrisBecker For the isis3.6.0 release, we are looking to get the minimally required dependencies through conda channels and provide our own when need be in order to get a functional stable release published. We will be open to re-evaluating our dependencies for future releases, including reducing unused dependency use, reducing use of custom builds, and extending our environment as need be.  We can look into and discuss extending our environment file with common extensions that aren't strictly "required", but that are used throughout the planetary community.

It does look like postgis is hosted on anaconda.org on the conda-forge channel, so it would be possible to do a ```conda install -c conda-forge postgis``` into a isis3 / isis3 dependencies environment. Once a conda environment is set up, it's the user's discretion how they may want to extend it with supplemental tools and packages.

**Comment by KrisBecker** [comment]
@ihumphrey-usgs Thanks for your reply. Your suggestion for adding functionality, including PostgreSQL extensions will work just fine. Perhaps the only tricky part is installing the proper version that will not alter (i.e., upgrade or downgrade) existing packages.

It appears the Anaconda libpq package provides the necessary runtime requirements for the PostgreSQL Qt plugin. It looks to also provide the bare minimum build requirements for the Qt plugin as well.

Note that the MySQL configuration in the isis3 dev environment includes the server as well as the client, albeit with what looks like different versions of the client libraries. I think the mysql-connector-c package would provide requirements for the MySQL plugin that are equivalent to the libpq package for PostgreSQL.

Thanks...

**Comment by chrisryancombs** [comment]
I have made changes to the meta.yaml for qt on the isis_dependencies repo. This is mostly adding the database packages as run dependencies for qt. A new qt build for mac (including libpq.dylib) is up on usgs-astrogeology, and a linux build should be expected soon.

**Comment by celbal** [comment]
The release candidate is on anaconda. @KrisBecker Can you confirm that the new release fixes this problem?

**Comment by jessemapel** [comment]
I'm marking this as closed as the problem has been resolved, if the problem persists please re-open the issue.
