### ISSUE TITLE
Running ISIS cube file via spiceinit application

### ISSUE THREAD

**Issue by sehajpunjabi** [DOI-USGS/ISIS3#4406]
I am facing the following error while using the Spice toolbox when running cube files in spiceinit application

![spiceinit_error_box](https://user-images.githubusercontent.com/74244924/115190065-18ec9b80-a105-11eb-91c1-359c7d32dd9e.png)

It says that a default value for the mission name is not specified. I checked the MissionData2Dir.trn file and I was able to see that there is actually a specified default value. I have attached the contents of that file in this email as a text file.

Maybe I am making a very naive mistake.

I would be grateful to you if you could kindly guide me to solve this error.

**Comment by jessemapel** [comment]
The attachment is not showing up on here. Can you re-post the image label and what processing you did prior to running spicenit?

**Comment by sehajpunjabi** [comment]
Thanks for consideration. I have converted MARCI RAW .img files to .cub files. Following am attaching screenshot of error again:
![spiceinit_error](https://user-images.githubusercontent.com/74244924/115270885-66dfbe80-a15a-11eb-9a9b-ec0a68e3998b.png)

Is it due to spice kernel files? If yes, in which directory do I have to save these spice kernels?

**Comment by jessemapel** [comment]
@sehajpunjabi I need the image label and the exact commands you ran. Can you run `catlab` on your cube and post results. Can you also run cathist with `mode=brief` on your cube and post the results.

**Comment by sehajpunjabi** [comment]
@jessemapel I got following after running catlab, while got empty file when ran cathist application.
![catlab](https://user-images.githubusercontent.com/74244924/115276244-6d713480-a160-11eb-8d11-b636d7b2660f.png)

**Comment by jessemapel** [comment]
Your cube label has no instrument information in it because it looks like you ingested it with pds2isis. You need to use the sensor specific ingestion application, [marci2isis](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/marci2isis/marci2isis.html).

You will get two cubes out, one with even frames and one with odd frames. You will need to duplicate your processing on both cubes.

**Comment by sehajpunjabi** [comment]
I have ran marci2isis only and got the two frames as you said. I want to generate global mosaic of Mars for a particular days. This is part of one of my objectives of studying the seasonal dynamics for my Masters thesis. Due to covid pandemic, a lot of time has been lost. Kindly help me in processing MARCI data as I have spent months learning ISIS and about the dataset. 
Thank you in anticipation.

**Comment by sehajpunjabi** [comment]
@jessemapel Can you tell me where will be the role of spice kernel files?  in which directory do I have to save these spice kernels? And how to use them? Because I believe MARCI processing is somewhat similar like MGS MOC processing. And MGS MOC processing is steps are available on this platform? But same doubt, where is the use of spice kernel files there also?

**Comment by jessemapel** [comment]
Where to download the SPICE kernel files is listed in our [README](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#The-ISIS-Data-Area), specifically the Mars Reconnaissance Orbiter section.

Once you have downloaded the base data areas and MRO data areas, ISIS will handle all of the kernel loading/reading/etc.

I am not very familiar with MARCI, but the general process for generating mosaics like you've described is:

1. Ingest images - marci2isis
2. Spiceinit images - spiceinit
3. Calibrate images - marcical
4. Create your map file - maptemplate
5. map project each individual image - cam2map
6. mosaic all of the images together - automos

If you have specific questions about anything feel free to ask.

**Comment by jessemapel** [comment]
I am going to close this issue for our bug tracking as this isn't a bug in spiceinit.

You can keep. responding on here even when it's closed.
