### ISSUE TITLE
Qview Statistics Tool Error

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#4414]
**ISIS version(s) affected**: 4.4.0 (also seen in isis5.0.0-RC1)

**Description**  
While clicking in low dn areas x-number of times, the following error message appears:

![QviewStatsToolError](https://user-images.githubusercontent.com/34550733/115627668-4166c800-a2b4-11eb-8f13-c58a278d0561.png)

It's nearly always the same line of code (212 for isis4.4.0 and 196 for isis5.0.0), but the bin range start value will vary depending where in the image you are clicking (based on dn's).

**How to reproduce**  
See /work/users/lweller/Isis3Tests/Qview/StatisticsTool/TC1W2B0_01_01207S888E3572.lev1.cub 

- Open Statistics tool, 
- uncheck Hide Display (or not, doesn't matter but nice to see things), 
- set Box Samples=Box Lines=9 (or 11, 13 anything really), 
- and click in a shadowed area having very low dn's (<1), Error will eventually appear.  

There doesn't seem to be any pattern to how many clicks before it pops up - sometimes a couple, other times many more.  Does not seem to be a problem in areas where dn's >> 1. Though it seems if I click in high dn areas then go to low dn's, I can't get the message to reappear.  But if I close the Statistics display window, reopen and go to a low dn area, it doesn't take too long for it to reappear.

**Comment by acpaquette** [comment]
@lwellerastro I will have some time this week since I am on a release sprint and the release will likely be out tomorrow to go over this. I have been able to reproduce the error but it seems like it manifests when transitioning from dns > 1 to dns < 1. I would like to narrow this down further to provide context to anyone that decides to tackles this ticket.

**Comment by jessemapel** [comment]
This is likely caused by the Histogram changes. Previously Histograms with a single value in them would "bound" that value. Now Histograms with a single value error. Changing the StatisticsTool to use an ImageHistogram will likely fix this.

**Comment by acpaquette** [comment]
Unfortunately this is not the error. `ImageHistogram` and `Histogram` differ in how the bins are structured and how the percentiles work. 

The error is happening when the Histogram object is being constructed before it is even populated with any data. Here is the line that errors: `ImageHistogram hist(p_stats.BestMinimum(), p_stats.BestMaximum());`

In looking into this the `p_stats.Best[Max/Min]imum()` is likely failing to some degree.

**Comment by lwellerastro** [comment]
This is broken under isis5.0.1.
I just checked isis5.0.0 and I don't get the pop up box there no matter how hard I try which seems odd to me.

**Comment by jessemapel** [comment]
This bug fix was also not cherry-picked to 5.0.1, so we'll be putting this out in 5.0.2.

**Comment by lwellerastro** [comment]
I'm going to close this issue since there appears to be a fix in place under 5.0.2.
