### ISSUE TITLE
BandnormByNumber Test Failures

### ISSUE THREAD

**Issue by tgiroux** [DOI-USGS/ISIS3#4416]
**ISIS version(s) affected**: latest / dev

**Description**  

I've noticed SmallCube.BandnormByNumber is failing on Jenkins across multiple PRs.

**How to reproduce**  

I am unable to reproduce outside of Jenkins builds . In my testing, all Bandnorm tests pass with no issues when run locally on Mac and Linux.
I've identified 3 places where this issue can be seen, though:
See PR4402 build 7 for Ubuntu.
See PR4412 build 3 for Ubuntu.
See PR4385 build 5 for Mac.

**Possible Solution**  

Three different tests in FunctionalTestBandnorm.cpp use temp directory structure outside of the convention:
`QString pencilPath = "/tmp/pencil.txt";`
I suspect that changing these to use `tempDir.path()` could resolve the issue.

**Additional context**

**Comment by jessemapel** [comment]
This appears to be fixed? Is this an intermittent failure?

**Comment by tgiroux** [comment]
The instances that I pointed out were happening intermittently across random builds. When I was looking for instances to put in this issue I found this test failure in about 1/4 of failed builds.

**Comment by scsides** [comment]
No test should use something like "QString pencilPath = "/tmp/pencil.txt";". The possibility of a race between two instances of the same test exists. The fix suggested is likely needed even if the error doesn't show up often.

**Comment by jessemapel** [comment]
This error just poped up on a PR from last night, so definitely still a thing.

**Comment by AustinSanders** [comment]
I'm not able to find any related test failures following #4501.
