### ISSUE TITLE
deltack error: Unable to find Instrument group in (filename.cub) for comparing target

### ISSUE THREAD

**Issue by shawn-brueshaber** [DOI-USGS/ISIS3#4426]
Hello,

I'm attempting to run deltack on some JunoCam images. I have run spiceinit with attach=true and am attempting to execute deltack on JunoCam mosaic I created with automos but this error comes up. What do I need to run to remove this error and get deltack to work?  Is JunoCam a supported instrument for a deltack operation?  Do I need to run deltack framelet by framelet rather than on a mosaic?

Thanks

**Comment by jessemapel** [comment]
You cannot use deltack with a projected image, you will need to adjust each framelet prior to mosaicing

**Comment by jessemapel** [comment]
We're also planning to work on some limb fitting software next fiscal year that may be helpful for working with JunoCam images.

https://astrodiscuss.usgs.gov/t/fy22-limb-fitting/582

**Comment by shawn-brueshaber** [comment]
Thanks for the information.  I'm excited to hear about the work on limb fitting!  :-)

As for deltack, if I run this on a framelet and assign a new lat/long coordinate to a sample/line coordinate, should I expect to see the images shift relative to each other when using qview's blink viewer with the two images linked in the viewport?

**Comment by jessemapel** [comment]
You should see them shift when you link them and use the find tool to zoom to a ground point. It could be a very small shift.

**Comment by jessemapel** [comment]
Closing as this is expected behavior for deltack.
