### ISSUE TITLE
Init script echos to stdout needs to be filtered for interactive sessions only

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#4434]
**ISIS version(s) affected**: 4.x

**Description**  

When a shell is not interactive, it shall NEVER echo anything to stdout, otherwise it can break functionality (like SSH and other things where a shell is opened for scripted functionality of an executable).
Currently, if someone were to activate ISIS for every new shell by copying the shell scripts into some of their shell init scripts, the echo always would occur. (This might only be a problem for fish, but I'm not sure).

**How to reproduce**  

Follow the instructions on how to activate the ISIS env at shell login.

**Possible Solution**  

For fish:
```
if status is-interactive
   echo ISIS Config:
   ...
end
```

**Comment by scsides** [comment]
This is a problem for most shells. "NEVER" write to stdout in a script that may be executed inside a shell startup file.

**Comment by rbeyer** [comment]
OP title indicates "init script" is the problem, which implies that the concern is with the created `isis-activate.\*` scripts, but could also implicate `isisVarInit.py`.

The `isis-activate.\*` scripts have a "cat" placed in them that writes to STDOUT.

The `isisVarInit.py` has *print* statements that also write to STDOUT.

**Comment by jessemapel** [comment]
I think this is only pertaining to the activate scripts as the installation I would not expect to be done in such a situation.
