### ISSUE TITLE
Update gllnims2isis docs

### ISSUE THREAD

**Issue by thareUSGS** [DOI-USGS/ISIS3#4439]
**Description**
Based on this [forum topic](https://astrodiscuss.usgs.gov/t/gllnims2isis-does-not-work-with-recent-release/688), the gllnims2isis documentation should be updated to (1) state it only works with the [original PDS3 archive](https://pds-imaging.jpl.nasa.gov/data/galileo/galileo_orbiter/), and (2) this routine was created to restore the NIMS tube/gcube data and migrate to PDS4 which has been released [here](https://pdsimage2.wr.usgs.gov/Individual_Investigations/multi_galileo_nims_tube.gcube_cahill_2019/).

Perhaps a note can be added:

Now that the data has been migrated to PDS4, this routine should not be needed for ingesting Galileo NIMS tube/gcube data.  The PDS4 migrated files are stored in a "raw" ISIS3+ cube format with a PDS4 label. Thus applications which have support for ISIS3+ cube format or the PDS4 format should be able to directly use them.  For more about how the data was migrated, please see the [readme.pdf](**url**) from the new archive or the Cahill et al., 2017 LPSC abstract.

Cahill, J. T. S., K. Becker, R. Espiritu, C. Isbell, and F. P. Seelos (2017), Galileo NIMS:
New ISIS3 tools for modernized data set handling and PDS4 re-archival, Planetary Data
Workshop, 3, [abs. 7071](https://www.hou.usra.edu/meetings/planetdata2017/pdf/7071.pdf).

**Comment by amystamile-usgs** [comment]
~~@thareUSGS What is the link for the readme.pdf? Seems that there is no link attached in your comment above.~~

I am guessing this is the link (https://pdsimage2.wr.usgs.gov/Individual_Investigations/multi_galileo_nims_tube.gcube_cahill_2019/document/) but I am having timeout issues when trying to access the site.
