### ISSUE TITLE
Relevant comment dropped from image label

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#4442]
**ISIS version(s) affected**: isis5.0.0

**Description**  
When an image is updated by jigsaw a comment is added to the image label specifying when the image was updated, typically right before the InstrumentPointing and InstrumentPosition Objects.

For example:
  `# Jigged = 2021-05-07T11:06:11`

The comment no longer appears in the image label of a jigsaw updated image as of isis5.0.0.  This is the only difference between the labels of an image updated via isis4.4.0 and isis5.0.0.

This comment has been included in our labels for at least over 10 years.  I use it extensively to determine if and when my images have been updated, particularly when looking at large volume of data. 

**How to reproduce**  
Run jigsaw setting update=true in a prior version and the latest version.  Compare labels.

See /work/users/lweller/Isis3Tests/Jigsaw/Label/ for catlab ouput and updated image from isis4.4.0 vs isis5.0.0.  
See /work/users/lweller/Isis3Tests/Jigsaw/Label/Network/ for a small network and jigsaw command for updating if you need test data.

**Possible Solution**  
Recover the lost comment!

**Additional context**  
The same problem occurs for images updated by deltack

`# deltackDirectAdjusted = 2021-05-07T11:28:45`

It's possible there is a similar issue for qtie updated images, but I have not checked this.

**Comment by jessemapel** [comment]
This is a bug, when we moved to the new Table logic, we only copy over keywords to the BLOB label and didn't add logic to copy over comments. Should be a simple fix.

**Comment by scsides** [comment]
NOTE: ISIS PVL attaches comments to keywords or groups or objects (what ever immediately follows them). At one time reading a keyword and writing it should have copied the comment too.

**Comment by jessemapel** [comment]
jigsaw attaches the jigged comment directly to the Table's Label, not any of the keywords. So, copying over the keywords doesn't catch these comments.

**Comment by lwellerastro** [comment]
this is still a problem under 5.0.1

**Comment by jessemapel** [comment]
#4496 also missed the cherry-pick over to 5.0.1 same as #4375. I'm going to open a new issue to collect these so that we have a full record of what needs to be moved over for 5.0.2.

**Comment by lwellerastro** [comment]
@jessemapel wondering what version of ISIS this and the other missed posts will be available.  I haven't seen any announcements for 5.0.2 and don't see it listed under the local conda envs.  Are we going straight to 6.0?

**Comment by jessemapel** [comment]
I've put out a 5.0.2 build with all of the bug fixes in it. It's already available internally if you want to try it. The release announcement will go out today.
