### ISSUE TITLE
Where do I find the cheatsheet for procedures/functions that used to be at http://isis.astrogeology.usgs.gov/

### ISSUE THREAD

**Issue by geokramer** [DOI-USGS/ISIS3#4467]
We use Github issues solely for discussing bugs, documentation issues, and new features.

For
questions about using ISIS or other ASC software, please use
any of the support alternatives: https://astrodiscuss.usgs.gov or https://gitter.im/USGS-Astrogeology/IAA

A great resource about asking high quality questions that generate high quality answers is available from the StackOverflow community: [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)

Thanks!

**Comment by geokramer** [comment]
This is out of my comfort zone, and I am probably not behaving properly. Please forgive me. But where do I find the cheatsheet for procedures/functions that used to be at http://isis.astrogeology.usgs.gov/ ?

**Comment by jessemapel** [comment]
The software manual can be found here:

https://isis.astrogeology.usgs.gov/Application/index.html

All questions should be opened up on astrodiscuss per the template.

**Comment by geokramer** [comment]
@jessemapel can you tell me why the same link was telling me isis.astrogeology.usgs.gov has been decommissioned, that is until _after_ receiving your response?

**Comment by jessemapel** [comment]
We could have had a temporary outage on our website. We have no plans to decommission the website.
