### ISSUE TITLE
Some Kaguya TC cubes fail spicinit

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#4471]
**ISIS version(s) affected**: x.y.z
I tried on 3.9.0, 4.0.0, and 4.4.0 

**Description**  

When running spiceinit on certain cubes InstrumentPosition is Null and causes "No instrument position available" Error

**How to reproduce**  

in /scratch/kaguya/jaxa_FEB2021 run:
`spiceinit from=cub_stereo/TC2W2B0_01_00770N885E2374.cub spksmithed=true shape=user model=/work/projects/kaguya/TOPO/Lunar_LRO_LOLAKaguya_DEMmerge_60N60S_512ppd_radius.cub`

**Possible Solution**  

**Additional context**  

`grep -l 'error' logs/* | xargs head -1` 
will give the product IDs of 106 other cubes which fail spiceinit

**Comment by jessemapel** [comment]
Tentatively, labeling as products since we're planning to work on kaguya control after the support sprint.

**Comment by lwellerastro** [comment]
@ladoramkershner Taking a quick look at the filenames using your grep command above, they all appear to be a part of the same REVOLUTION_NUMBER: 770 (00770 is embedded in the filename).

Do all images in this revolution fail?  I don't think this keyword gets propagated to the isis cube upon ingestion, but it's a part of the filename and in the .lbl file, so it's part of the original label information (if you used catoriglab on the isis cube you could see it)

It could be an oversight that this rev's spk information was left out, either by us or the mission.  I'm assuming Lisa helped acquire the spacecraft kernels via her Kaguya PDART, or even earlier collaborative work.  Maybe some things were left out at the time.

**Comment by jessemapel** [comment]
> It could be an oversight that this rev's spk information was left out, either by us or the mission. I'm assuming Lisa helped acquire the spacecraft kernels via her Kaguya PDART, or even earlier collaborative work. Maybe some things were left out at the time.

This is my guess for the problem. I'm not sure where we get the kernels from though.

**Comment by ladoramkershner** [comment]
Looking at the very bottom of: $ISISDATA/kaguya/kernels/Main_orbit_kernel_readme.txt
```
----- Gaps due to altitude manoeuvres -----
The spacecraft was three-axis stabilised and its altitude was
maintained by doing periodical correction manoeuvres. According
to the Mission Working Group Meeting documents, mission instruments
were turned off during these manoeuvres. Since it is difficult to
do precise orbit determination without good thrustering information
during these events, the processing was stopped, resulting in some
gaps in the orbits. The times of the gaps are:

07.12.11 02:30 - 16:50
08.02.04 20:30 - 08.02.05 04:15
08.03.29 16:30 - 08.03.30 00:15
08.05.24 15:00 - 20:43
08.07.16 07:30 - 15:30
08.09.10 05:30 - 13:30
08.11.03 00:30 - 09:00
08.12.26 21:00 - 08.12.27 05:30
09.02.20 20:00 - 23:45
09.03.19 18:00 - 22:00
09.04.16 19:00 - 21:30
```

The start time of one Failed Observation is  `2007-12-11T15:42:34.811840` and all the rest of the start times of the failed lbls are between the 14th and 15th hour of 2007-12-11. So ISIS is working as expected, it is just confusing that data that does not have kernel coverage is still being served.

**Comment by lwellerastro** [comment]
`it is just confusing that data that does not have kernel coverage is still being served.`
Not everyone interested in the data want or need kernels, plus it behooves the mission to put everything they have out there whether spice is complete or even good.  

Hopefully we don't need these images because I'm not sure there is a work around for this issue.  I tried spicing your image setting spkreconstructed=true but that failed as well.  I'm not sure I was expecting it to work but I thought it was worth a try. 

It's awesome we have this readme and have something to compare to.  I wonder what other nuggets are in that file.

**Comment by ladoramkershner** [comment]
That is a really good point @lwellerastro. I am hoping even if the lack of these data cause gaps, the near global nature will make the product worth while. I am going to close as expected behavior!

**Comment by jlaura** [comment]
What SPK are we using? I heard back from Hiro and he provided a link to Dr. Goossen's update SPK file: https://data.darts.isas.jaxa.jp/pub/pds3/sln-l-spice-6-v1.0/slnsp_1000/data/spk/spkinfo.txt with a linked publication: https://europepmc.org/backend/ptpmcrender.fcgi?accid=PMC7243822&blobtype=pdf

Do the results change if this SPK is used?

I also see that the linked SPK README has identified time gaps if that is relevant.
