### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by lsantorii** [DOI-USGS/ISIS3#4484]
Where can I find a tutorial for creating mosaics with LRO NAC images?

**Comment by jessemapel** [comment]
Hi,

We do not currently have a LRO NAC specific tutorial. We use GitHub issues for tracking bugs and enhancement requests. If you have a general usage questions we encourage users to use our discourse forum at https://astrodiscuss.usgs.gov/

Robert Wagner mentioned having a tutorial for this here: https://astrodiscuss.usgs.gov/t/adding-tutorials-to-isis-github-wiki/513 I would try reaching out to him.
