### ISSUE TITLE
Update CaSSIS kernel update script to use ESA SPICE FTP for CaSSIS rotation mechanism kernel

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#4535]
**Description**  
Right now, the CaSSIS rotation mechanism kernel provided with ISIS is obtained from a private server, but these kernels are now available from a public source via the ESA SPICE FTP. The internal kernel update script for CaSSIS (`downloadTGOCassisKernels`) should be updated to fetch CKs of the form: em16_tgo_cassis_tel_20160407_20211231_s20210602_v01.bc from ftp://spiftp.esac.esa.int/data/SPICE/ExoMars2016/kernels/ck/, and the internal script and associated cronjob named ` downloadExoMarsTGOData` can be deleted.

**Comment by jlaura** [comment]
@AustinSanders Do you know if this was merged last week so that CaSSIS is now using 100% public kernels?

**Comment by AustinSanders** [comment]
@jlaura I believe @kberryUSGS made these changes to the kernel update script, but I don't think there was anything to merge in on the ISIS codebase.

**Comment by krlberry** [comment]
I can confirm that nothing needed to be updated in the ISIS codebase. I updated the internal cronjob before I left to stop pulling down the private kernel, as well as putting up an internal PR with the script update that Austin mentioned to pull down the public kernel instead. As long as that PR was merged and someone did a git pull from the internal clone of the scripts repo that the kernel update scripts are actually run from, in theory it should be all set, but @AustinSanders it might be a good idea to go in to the kernels area and check that everything is working and the new public CKs are getting pulled down before closing this ticket.

**Comment by AustinSanders** [comment]
TGO CKs are being pulled down, but I'm not sure how to figure out where they're coming from, i.e. if they're coming from the new, public source or if they're still coming from the old source.  The kernel does indicate that it was created by the ESA spice service, so I suspect that it's coming from ESA Spice FTP, but I don't have much experience with this.

**Comment by krlberry** [comment]
@AustinSanders File names of the form `em16_tgo_cassis_tel_20160407_20211231_s20210602_v01.bc` are only used for the CKs that come from the ESA SPICE FTP, so if there are CK kernels being pulled down with a filename of that form, then they're coming from the right place! The CKs from the CaSSIS internal server had a different naming convention.
