### ISSUE TITLE
Installation documentation for isis3.6.0 via conda

### ISSUE THREAD

**Issue by ihumphrey** [DOI-USGS/ISIS3#454]
_This issue can be worked on by multiple people. Tyler is currently iterating on the user-oriented installation guide (PR #443 )._

Update and review installation documentation for developers (in-house & external) and users.

The developer documentation is located on this GitHub's wiki.

The user documentation is our install guide hosted on our website (https://isis.astrogeology.usgs.gov)

User documentation:
- [ ] Describes supported operating systems
- [ ] Describes how to download isis3.6.0
- [ ] Describes how to download isis3.6.0 data
- [ ] Describes how to set up Linux/macOS environment for running isis3 applications

Developer documentation:
- [ ] Describes operating systems supported for development
- [ ] Describes how to download isis3.6.0 and dependencies for development
- [ ] Describes how to download isis3.6.0 data for development
- [ ] Describes how to download isis3.6.0 test data
- [ ] Describes how to build and test isis3.6.0 (using cmake)
- [ ] Describes PR process and expectations (CONTRIBUTING.md)

**Comment by ihumphrey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Installation documentation PR'd and ready for release candidate](https://trello.com/c/kz42NOWv/147-installation-documentation-prd-and-ready-for-release-candidate)

**Comment by jessemapel** [comment]
@twilson271828 I think this is done. Any issues with the install instructions can be their own issue like #590
