### ISSUE TITLE
qview's UI bug？

### ISSUE THREAD

**Issue by Hidariuma** [DOI-USGS/ISIS3#4541]
**ISIS version(s) affected**: 3.10.0

**Description**  

Hello,

I'm building an environment on MacOS.

I was able to launch qview, but the vertical bar where the Tool is displayed is displayed in an unusual place, and some icons are outside the window and cannot be selected.

I tried reinstalling the base data and redoing the installation with conda, but the result was the same.

The command prompt shows a warning like the following. Is there a solution for this?
`qt.qpa.cocoa.window: Window position outside any known screen, using primary screen`

**How to reproduce**  

**Possible Solution**  

**Additional context**  

I'm a Japanese university student and not very good at English, so I'm sorry if I didn't convey what I wanted to say.
<img width="1052" alt="スクリーンショット 2021-06-19 4 33 51" src="https://user-images.githubusercontent.com/63413579/122608680-9a39bd80-d0b7-11eb-8074-f339ed8f7c5c.png">

**Comment by jessemapel** [comment]
Can you provide some information about your setup. How many displays are you using and at what resolution. Also try deleting the `.Isis` directory in your home directory.

**Comment by Hidariuma** [comment]
Thank you for reply. I use 2 monitors, and resolutions are 2560x1600(primary monitor) and 1920x1080(sub-monitor)

**Comment by Hidariuma** [comment]
I deleted the `.Isis` directory and the display returned to normal. Thank you very much.
