### ISSUE TITLE
ISIS and python

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#4544]
ISIS version 4.4.0 links to libpython3.6m.so. This opens a big can of worms when it comes to shipping the binaries of Ames Stereo Pipeline, as libpython wants its environment reproduced. It should not be a problem for a conda installation though, as ISIS gets shipped.

I am curious if this is on purpose. Does ISIS actually need a python runtime?

**Comment by oleg-alexandrov** [comment]
Actually upon closer inspection it appears that libpython3.6m.so being shipped with ISIS is not a new thing, and ASP never complained so far, so something else is triggering it. I'll withdraw this to sort things out on my side.

**Comment by jessemapel** [comment]
Related to #3885

**Comment by oleg-alexandrov** [comment]
For the record, something is quirky here, but I don't know if it is worth looking into. If I run with a couple of decent cubes (which i got from Trent for the CSM work):

stereo M1121188383LE.lev1.8bit.cub M1121202582LE.lev1.8bit.cub run1/run

I get the ISIS error:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

If, however, I do spiceinit web = true on them, then ASP runs fine.

Now, it does make sense that the cubes before spiceinit have this error, as ISIS tries to look up a shape model which is not on my disk but which presumably was on Trent's disk (/ser/data1/Lunar_DEM).

What confuses me is why the error is not about missing data, but rather some weirdness about Python.  Anyhow, I'll leave it at that.

**Comment by jessemapel** [comment]
@oleg-alexandrov Can you post your conda environment?

**Comment by jessemapel** [comment]
I'm also curious if this is from the way ISIS decides what to link against. It does a whole-sale search of all the variables that could be libraries and links everything against all of them. It could be that ALE's target import linking is somehow going through that.

**Comment by oleg-alexandrov** [comment]
I get this error when I don't have a conda environment at all. We ship ASP either with conda or as a standalone tarball, and issues come up when such a tarball is used on a system not having conda. 

Since the error does not show up when a self-contained .cub file is queried, but it shows up when that .cub file is not spiceinit-ed properly, it does look that it is no mere linking artifact, some functionality which actually does make use of Python gets called from ISIS in some circumstances, maybe some parsing or lookup logic. 

Hopefully you folks aren't embedding intentionally a whole Python within ISIS. Or if you do, I guess it is something one has to deal with, and any system must have the needed runtime.

**Comment by jessemapel** [comment]
We are embedding Python inside of spiceinit as we're moving that functionality to ALE. It currently falls back to the old functionality if ALE fails, but not if you can't even get Python. We could possibly add the ability to compile without using ALE in spiceinit but that wouldn't work forever and could cause some problems down the road.

**Comment by oleg-alexandrov** [comment]
That makes sense. Thanks. I'll have to consider this into how ASP gets packaged.

**Comment by AndrewAnnex** [comment]
@jessemapel what version of ISIS was this introduced? I am running into this issue and maybe there is an older version of isis I can use to avoid it

**Comment by oleg-alexandrov** [comment]
I just added the full Python 3.6 runtime to ASP, which, in my tests, took care of it. I will write to you separately with more details.

**Comment by jessemapel** [comment]
@AndrewAnnex This was added in ISIS 4.0 with the SPICE migration.
