### ISSUE TITLE
building isis following tutorial steps, cmake error boost_atomic cannot be found

### ISSUE THREAD

**Issue by AndrewAnnex** [DOI-USGS/ISIS3#4548]
**ISIS version(s) affected**: 5.0.0

**Description**  
Attempting to follow the building isis instructions to build the current state of the dev branch results in a cmake error relating to boost: 

```
(isis_dev) ➜  build git:(dev) cmake -DJP2KFLAG=OFF -GNinja ../isis
Detected Operating System: Linux_x86_64_Ubuntu20_04
Writing test data folders to = /home/andrew/Projects/ISIS3/build/testOutputDir
CONFIGURATION
        BUILD STATIC CORE: OFF
        BUILD TESTS: ON
        BUILD CORE: ON
        BUILD MISSIONS: ON
        JP2K SUPPORT: OFF
        PYTHON BINDINGS: OFF
        ISISDATA: /mnt/common/isis3/data
        ISISTESTDATA: /mnt/common/isis3/testdata
        TEST OUTPUT DIR: /home/andrew/Projects/ISIS3/build/testOutputDir
        INSTALL PREFIX: /home/andrew/anaconda3/envs/isis_dev
CONDA PREFIX: /home/andrew/anaconda3/envs/isis_dev
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_atomic"
  (requested version 1.71.0) with any of the following names:

    boost_atomicConfig.cmake
    boost_atomic-config.cmake

  Add the installation prefix of "boost_atomic" to CMAKE_PREFIX_PATH or set
  "boost_atomic_DIR" to a directory containing one of the above files.  If
  "boost_atomic" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /home/andrew/anaconda3/envs/isis_dev/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:236 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/andrew/Projects/ISIS3/build/CMakeFiles/CMakeOutput.log".
```

output of mamba list is in attached text file:
[envlist.txt](https://github.com/USGS-Astrogeology/ISIS3/files/6797809/envlist.txt)

**How to reproduce**  
```
"git clone isis"
mamba env create -n isis_dev -f environment.yml
mkdir install 
mkdir build 
cd build
cmake -DJP2KFLAG=OFF -GNinja ../isis
```

**Additional context**  
the how to build docs could be updated to say that the user should CD into the build directory. Also consider adding cmake outputs in the root isis source directory to gitignore for when you forget to cd into build first.

**Comment by jessemapel** [comment]
It looks like you are using a version of CMake outside of your anaconda environment and that's causing weird find errors.

```
/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake
```

Should be in your anaconda environment `lib` directory and the boost version number doesn't match the boost version from your mamba list file.

**Comment by AndrewAnnex** [comment]
@jessemapel  I am just using standard conda/mamba and I activated the environment so I don't know why that is happening. Is there a step missing from the docs for ensuring the build is isolated to the conda environment or is this a bug with conda?

**Comment by jlaura** [comment]
@AndrewAnnex Does cmake get installed into that env? Sometimes I have packages getting found further down the PATH. - naive comment coming in from a third party watcher on the issue.

**Comment by AndrewAnnex** [comment]
@jlaura yes it does, in the envlist.txt file I have above it shows cmake 3.16.0 hc9558a2_0 from conda forge is being installed and running which cmake seems to point to the one installed into the conda environment and I get the same error if I manually point to the conda environment's cmake. I don't see any environment variables that include the /usr/lib dir.

**Comment by AndrewAnnex** [comment]
oh, you are saying it searches the PATH too... yeah not sure but maybe there should be some hard set cmake variables to ensure that the isis_dev cmake only looks in the right places, although I don't know what those would be
