### ISSUE TITLE
Merge bundle xyz into dev

### ISSUE THREAD

**Issue by ihumphrey** [DOI-USGS/ISIS3#455]
_Prerequisites_:
- [x] dev merged into bundle xyz
- [x] bundle xyz is approved (by Debbie/Ken)

_Requirements_:
- [x] bundle xyz merged into cmake
- [x] builds and tests successfully on Fedora28, Ubuntu18.04, and macOS10.13

**Comment by jessemapel** [comment]
builds and testing are happening at /work/users/jmapel/ISIS3

**Comment by dcookastro** [comment]
I believe all tests are running successfully now except for spiceserver.  I think all it needs it to update the truth data.  It changed because I added a keyword to NaifKeywords.  I will be in Cottonwood on Monday.  Let me know if you see any problems when you run the tests again.  I did not mean to close this thread.

**Comment by jessemapel** [comment]
@dcookastro I was seeing a few issues with the bundleXYZ test, but It was small enough to just need tolerance tweaks. On the pole-ra-dec-w0-wDot-triaxial-radii test, I am seeing multiple degree differences. I'm worried that's not just within tolerances.

**Comment by jessemapel** [comment]
issues are now resolved. I have a small amount of truth data to check in for mac 10.13. Once dev is clean we're ready to go in.

**Comment by dcookastro** [comment]
Were you able to resolve the differences with the triaxial radii pole test?
Do I need to do anything to the data? Thanks for fixing the remaining test
data issues..

**Comment by jessemapel** [comment]
@dcookastro The issues were due to bad test data. The mac 10.13 test data was incorrect, so I just regenerated it. It turns out it's much closer to the regular data.
