### ISSUE TITLE
libjpeg version in environment.yml

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#4553]
I fetched isis 5.0.1 with conda. It depends on jpeg 9d, yet the environment here, https://github.com/USGS-Astrogeology/ISIS3/blob/c24b57bd224e5862cead3f7ca21462b9df2724b1/environment.yml#L31 says jpeg 9b.

**Comment by AustinSanders** [comment]
This appears to be addressed in #4547.

**Comment by AndrewAnnex** [comment]
@AustinSanders #4547 does not address this issue/question directly. I think that recent versions of ISIS must have been deployed using a non public yaml file to end up using 9d

**Comment by jessemapel** [comment]
the libjpeg version in the environment.yml is a hold over from when we hard pinned every dependency. The actual pin used in the build is `jpeg >=9b,<10a` which you can see specified in the recipe:

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/recipe/meta.yaml#L135

**Comment by oleg-alexandrov** [comment]
It is not clear what "pin_compatible" does though, and the recipe you point to still says jpeg==9b: https://github.com/USGS-Astrogeology/ISIS3/blob/f471eb3cc83fb4d736910cc8db10b707526600a8/recipe/meta.yaml#L81

No big deal of course. But it seems like something which may need a bit of tuning.

**Comment by jessemapel** [comment]
`{{ pin_compatible('jpeg', max_pin='x') }}` makes it so the runtime environment installs a version of jpeg that is the same major version as the build environments, 9b. It's a way to enforce ABI compatibility in the runtime environment. So, the 9d in the runtime is completely okay and expected behavior.

**Comment by oleg-alexandrov** [comment]
Shouldn't one just use jpeg>=9b, <= 9d all over then?

**Comment by jessemapel** [comment]
We could do that for the build pin, but we want to keep the pin_compatible for the run so that we have a flexible environment.
