### ISSUE TITLE
mvic frame transfer crash

### ISSUE THREAD

**Issue by drschenk** [DOI-USGS/ISIS3#4561]
**ISIS version(s) affected**: x.y.z
3.9.1

**Description**  
mvic frame transfer mode images run mvic, spiceinit, deltack just fine but crash on qnet, grid, cam2map 

**How to reproduce**  

image numbers from pdf small bodies node 0299175045, 0299175093, etc.

**Possible Solution**  

**Additional context**  

libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::domain_error> >
Abort trap: 6

a friend can get them to work on his 3.9.1 machine

**Comment by jessemapel** [comment]
copying from astrodiscuss:

What OS are you running where this happens? Can you also provide the output of `conda list`

**Comment by drschenk** [comment]
10.15.7

# packages in environment at /opt/miniconda3/envs/isis3:
#
# Name                    Version                   Build  Channel
armadillo                 8.200.0         blas_openblas_200  [blas_openblas]  conda-forge
arpack                    3.6.2           blas_openblash26a2512_200  [blas_openblas]  conda-forge
blas                      1.1                    openblas    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bullet                    2.86.1                        0    usgs-astrogeology
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cspice                    66                h0b31af3_1007    conda-forge
curl                      7.60.0                        0    conda-forge
doxygen                   1.8.14                        0    conda-forge
eigen                     3.3.3                         0    conda-forge
embree                    2.14.0                        0    conda-forge
ffmpeg                    3.2.4                         3    conda-forge
flann                     1.9.1                         0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
geos                      3.5.1                         1    usgs-astrogeology
geotiff                   1.4.2                hb54a4aa_1    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.2.1                h0b31af3_1    conda-forge
glib                      2.51.4                        0    conda-forge
gmm                       5.0                  h6aef312_0    usgs-astrogeology
gmp                       6.1.2             h0a44026_1000    conda-forge
gsl                       2.2.1           blas_openblas_3  [blas_openblas]  conda-forge
harfbuzz                  1.3.4                         2    conda-forge
hdf5                      1.8.18                        3    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
isis3                     3.9.1                    py36_0    usgs-astrogeology
jama                      125                           0    usgs-astrogeology
jasper                    1.900.1                       4    conda-forge
jpeg                      9b                   he5867d9_2  
kakadu                    1                             0    usgs-astrogeology
krb5                      1.14.2                        0    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libffi                    3.2.1                h475c297_4  
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libllvm9                  9.0.0                h770b8ee_3    conda-forge
libopenblas               0.3.6                hdc02c5d_2  
libpng                    1.6.37               h2573ce8_0    conda-forge
libprotobuf               3.5.2                hd28b015_1    conda-forge
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13              h1de35cc_1002    conda-forge
libxml2                   2.9.7                         0    conda-forge
llvm-tools                9.0.0                         3    conda-forge
llvmdev                   9.0.0                h770b8ee_3    conda-forge
m4                        1.4.18            h1de35cc_1001    conda-forge
mesalib                   17.2.0                        0    conda-forge
metis                     5.1.0             h6de7cb9_1004    conda-forge
mysql                     5.7.20            h0a44026_1001    conda-forge
mysql-connector-c         6.1.6                hfc679d8_1    conda-forge
nanoflann                 1.2.2                         0    conda-forge
ncurses                   5.9                          10    conda-forge
nn                        1.86.0            h1de35cc_2003    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
opencv                    3.3.0           py36_blas_openblas_200  [blas_openblas]  conda-forge
openssl                   1.0.2n                        0    conda-forge
pcl                       1.8.1                         1    usgs-astrogeology
pcre                      8.41              h0a44026_1003    conda-forge
pip                       9.0.1                    py36_1    conda-forge
pixman                    0.34.0            h1de35cc_1003    conda-forge
postgresql                9.6.3                         3    conda-forge
proj4                     4.9.3                h01d97ff_9    conda-forge
protobuf                  3.5.2            py36hd28b015_0    conda-forge
pthread-stubs             0.4               h1de35cc_1001    conda-forge
python                    3.6.0                         2    conda-forge
qhull                     7.2.0                         0    usgs-astrogeology
qt                        5.9.6                         0    usgs-astrogeology
qwt                       6.1.3                         0    usgs-astrogeology
readline                  6.2                           0    conda-forge
setuptools                38.5.1                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.14.0                   py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
suitesparse               4.5.4           blas_openblas_200  [blas_openblas]  conda-forge
superlu                   5.2.1             hbced767_1205    conda-forge
tbb                       4.4                  hf7780a4_0    usgs-astrogeology
tk                        8.5.19                        2    conda-forge
tnt                       126                           0    usgs-astrogeology
wheel                     0.30.0                   py36_2    conda-forge
x264                      20131218                      0    conda-forge
xalan-c                   1.11                 h1922a5c_0    usgs-astrogeology
xerces-c                  3.1.4                h10f7eb2_0    usgs-astrogeology
xorg-fixesproto           5.0               h1de35cc_1002    conda-forge
xorg-inputproto           2.3.2             h1de35cc_1002    conda-forge
xorg-kbproto              1.0.7             h1de35cc_1002    conda-forge
xorg-libice               1.0.10               h01d97ff_0    conda-forge
xorg-libsm                1.2.3             h01d97ff_1000    conda-forge
xorg-libx11               1.6.4                         6    conda-forge
xorg-libxau               1.0.9                h1de35cc_0    conda-forge
xorg-libxdmcp             1.1.3                h01d97ff_0    conda-forge
xorg-libxext              1.3.4                h01d97ff_0    conda-forge
xorg-libxfixes            5.0.3             h01d97ff_1004    conda-forge
xorg-libxi                1.7.10               h01d97ff_0    conda-forge
xorg-xextproto            7.3.0             h1de35cc_1002    conda-forge
xorg-xproto               7.0.31            h1de35cc_1007    conda-forge
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3

**Comment by jessemapel** [comment]
It looks like there's something going wrong in the distortion model, the legendre polynomial functions are getting an input outside of their domain [-1,1] and that's raising an exception. There is suppose to be a try catch to handle this and just return non-intersection, but that doesn't seems to be catching it as it's looking for a std::exception, not a boost exception.

**Comment by drschenk** [comment]
Any recommendation?

Sent from my iPhone!  Typing erratic.

On Jul 20, 2021, at 11:14 AM, Jesse Mapel ***@***.***> wrote:

﻿
        CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


It looks like there's something going wrong in the distortion model, the legendre polynomial functions are getting an input outside of their domain [-1,1] and that's raising an exception. There is suppose to be a try catch to handle this and just return non-intersection, but that doesn't seems to be catching it as it's looking for a std::exception, not a boost exception.

**Comment by rbeyer** [comment]
What Jesse described sounds like a programming bug that needs to be fixed (or perhaps has been already?).  

Paul and I did some tests, and I do *not* get this error.  It works for me in ISIS 5.0.1, but also in my old version of ISIS 3.9.0, so still not sure what's going on.  Why are the polynomials getting an input beyond their domain in the first place?  Not entirely sure.

**Comment by drschenk** [comment]
any ideas on how to fix this or which code to update (and how)?  thanks, p

**Comment by drschenk** [comment]
to complicate matters I found an MVIC framing transfer file of Callisto (0035126515) and ran it through mvic2isis and spiceinit (no parameters) and it works just fine (grid, cam2map, etc).  so tried one of the Pluto frames reran it in mvic2isis and spiceinit (no parameters also) and still get same errors.  compared distortions in information in both image labels and they are identical except for planet shape.

**Comment by jessemapel** [comment]
The input to the legendre polynomials is the focal plane coordinate scaled so that one end of the CCD is -1 and the other is +1. So, if there's a focal plane coordinate outside of the CCD then you could run into this issue. I'm confused why this is cropping up in just Paul's version.

**Comment by drschenk** [comment]
this is what is in the labels.  it seems to be identical to what is in the Callisto FT image, which does work.

Object = NaifKeywords
  BODY_CODE                              = 999
  BODY999_RADII                          = (1188.3, 1188.3, 1188.3)
  BODY_FRAME_CODE                        = 10019
  INS-98903_FOCAL_LENGTH                 = 657.5
  INS-98903_PIXEL_PITCH                  = 0.013
  CLOCK_ET_-98_0299175047:14600_COMPUTED = e1f9590df636bd41
  INS-98903_TRANSX                       = (0.0, -0.013, 0.0)
  INS-98903_TRANSY                       = (0.0, 0.0, 0.013)
  INS-98903_ITRANSS                      = (0.0, -76.923076923077, 0.0)
  INS-98903_ITRANSL                      = (0.0, 0.0, 76.923076923077)
  INS-98900_DISTORTION_COEF_X            = (-2.184e-05, 3.2911e-04, -2.43e-06,
                                            7.444e-05, -1.9201e-04, -2.18e-06,
                                            6.86e-06, -5.02e-06, -0.0014441,
                                            6.62e-06, -1.94e-06, 5.37e-06,
                                            -8.43e-06, 2.01e-06, -2.89e-06,
                                            -1.53e-06, -2.09e-06, -6.7e-07,
                                            -4.9e-06, -1.2455e-04)
  INS-98900_DISTORTION_COEF_Y            = (0.0019459, 0.0016936, 1.1e-05,
                                            -3.5e-05, 0.0060964, -4.3e-05,
                                            4.0e-06, -0.002871, -0.001149,
                                            -5.1e-05, 3.36e-04, -4.14e-04,
                                            -3.88e-04, -0.001225, 3.73e-04,
                                            4.15e-04, 4.5e-05, 1.13e-04,
                                            -6.0e-04, 4.09e-04)
End_Object

**Comment by jessemapel** [comment]
@drschenk Those are the coefficients the polynomials are multiplied by, not the values the polynomials are evaluated at. So, it is expected that they will be the same for all MVIC framing images. The values that are potentially causing issue are the focal plane coordinates being computed for a given ground point or image pixel.

**Comment by drschenk** [comment]
where would those be hiding?

**Comment by jessemapel** [comment]
@drschenk They are not available to users as they are not saved off during computations. During runs of programs these will get computed potentially millions of times.

**Comment by drschenk** [comment]
how do we get around this?   
I dont want to go from 3.9 to 5.0 until I have no choice, as it usually results in major headaches during the upgrade.  what would be the proper commands to execute an upgrade and what changes would happen to program parameters and execution?  can you confirm these files work in 5.0 for you?

**Comment by jlaura** [comment]
> I dont want to go from 3.9 to 5.0 until I have no choice, as it usually results in major headaches during the upgrade.

@drschenk The way that we are versioning now, you should not see the same version headaches that you may have previously encountered. The changes from 3.9 to 5.0 are relatively small. They are API changes though (see the [change logs](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md)) which is why the version number ticked with the speed that it did.

**Comment by drschenk** [comment]
can someone suggest the proper upgrade command, given im already in the conda envr?  ross suggested something but would like to confirm it.   
I still want to try and get a workaround in 3.9 if possible.

**Comment by jessemapel** [comment]
Since you are using ISIS 3.9 and the old isis3 package, you will need to create a new isis environment to install into. You can follow the install instructions in the README and specify isis=5.0.1 to get the latest version.

**Comment by jlaura** [comment]
@jessemapel To ensure that @drschenk get back to 3.9 if needed, would you suggest creating a new env named something like `isis5.0.1` and then **also** having a new ISIS data area?

**Comment by jessemapel** [comment]
You can use the old data area with new versions of ISIS, so you don't need a new data area. The problem is using new data with old versions.

**Comment by drschenk** [comment]
can you send me the link to correct REEADME and sources so I get the correct one for my needs?

**Comment by jessemapel** [comment]
Installation can be found here:

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#Installation

**Comment by drschenk** [comment]
additional test images show that any frame with target wholy within the frame can be used normally.  
only the 5 frames that cover a part of Pluto fail.
also, those 5 frames crash out of qview when I try to read the bottom line (but read correct coordinates on lines 1-127).

**Comment by drschenk** [comment]
found workaround of 'pad'ding 2500 lines to the bottom of the frames on the assumption that this does not corrupt the camera distortion center of reference (at least I can use some programs that dont require that until a more permanent fix is made)

**Comment by jessemapel** [comment]
> found workaround of 'pad'ding 2500 lines to the bottom of the frames on the assumption that this does not corrupt the camera distortion center of reference (at least I can use some programs that dont require that until a more permanent fix is made)

This will dramatically impact your distortion as the size of the image is queried and not hard coded. So, you are "stretching" the distortion in the line direction.

I would not recommend this.

**Comment by drschenk** [comment]
I did not plan to use this for mapping or camera kernels, but need to start work some on some prep tasks until someone can fix this...   is it not possible?

**Comment by rbeyer** [comment]
Paul, they aren't going to fix something that's wrong in ISIS 3.9.  That ship has sailed.  If you have installed ISIS 5, and you're still encountering this problem, that's a different story.  Is that what's happening?

**Comment by drschenk** [comment]
was able to install 5.0 without apparent problem and mvic frame issues have (so far) not returned. . .

**Comment by drschenk** [comment]
got a new 'problem' after successfully installing 5.0.1.  jigsaw gets a convergence solution but it tries to write to the labels it crashes out with 
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Input vector must have 6 entries.
Abort trap: 6
jigsaw completes when cksolve=yes and spsolve=no but fails when spsolve=yes and update=yes.  (it solves for spsolve=yes but only fails when writing to the labels).  it is also fine when using Lorri only but crashes when the mvic frame images included.

# packages in environment at /opt/miniconda3/envs/isis:
#
# Name                    Version                   Build  Channel
ale                       0.8.5            py36hc61eee1_3    conda-forge
armadillo                 9.200.4           hcb88e47_1205    conda-forge
arpack                    3.6.3             h06d5271_1005    conda-forge
blas                      1.1                    openblas    conda-forge
boost                     1.68.0          py36h9888f84_1001    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bullet                    2.86.1                        0    usgs-astrogeology
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2021.5.30            h033912b_0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2021.5.30        py36h79c6626_0    conda-forge
csm                       3.0.3.3                       0    conda-forge
cspice                    66                h0d85af4_1014    conda-forge
curl                      7.64.0               heae2a1f_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
eigen                     3.3.9                h926bf3e_1    conda-forge
embree                    2.16.0               h6834224_0    usgs-astrogeology
expat                     2.4.1                he49afe7_0    conda-forge
ffmpeg                    3.4.1                         0    conda-forge
flann                     1.9.1                         0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
geos                      3.7.3                h4a8c4bd_0    conda-forge
geotiff                   1.4.3             h113155d_1001    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.51.4                        0    conda-forge
gmm                       5.0                  h6aef312_0    usgs-astrogeology
gmp                       6.2.1                h2e338ed_0    conda-forge
gsl                       2.7                  h93259b0_0    conda-forge
harfbuzz                  1.3.4                         2    conda-forge
hdf5                      1.8.18                        3    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
inja                      3.2.0                h1c7c35f_0    conda-forge
isis                      5.0.1                         0    usgs-astrogeology
jama                      125                           0    usgs-astrogeology
jasper                    1.900.1           h636a363_1006    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
kakadu                    1                             0    usgs-astrogeology
krb5                      1.16.3            h24a3359_1000    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.64.0               h76de61e_0    conda-forge
libcxx                    12.0.1               habf9029_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10               h0794777_0  
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     10.6              hbe1e24e_1000    conda-forge
libprotobuf               3.9.2                hfbae3c0_0    conda-forge
libssh2                   1.8.0             hf30b1f0_1003    conda-forge
libtiff                   4.0.10            ha78913b_1005    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13              h35c211d_1003    conda-forge
libxml2                   2.9.9                hd80cff7_2    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
mesalib                   18.0.0               hb6cfc13_1    conda-forge
metis                     5.1.0             h2e338ed_1006    conda-forge
mpfr                      4.0.2                h72d8aaf_1    conda-forge
mysql                     5.7.20            h0a44026_1001    conda-forge
mysql-connector-c         6.1.11            had4e77e_1002    conda-forge
nanoflann                 1.3.2                h694c41f_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
networkx                  2.5                        py_0    conda-forge
nlohmann_json             3.9.1                he49afe7_1    conda-forge
nn                        1.86.0            h1de35cc_2003    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
opencv                    3.2.0           np113py36_blas_openblas_203  [blas_openblas]  conda-forge
openssl                   1.0.2u               h0b31af3_0    conda-forge
pcl                       1.9.1             hdd77166_1002    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pip                       21.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.34.0            h1de35cc_1003    conda-forge
postgresql                10.6              ha1bbaa7_1000    conda-forge
proj4                     5.2.0             h6de7cb9_1006    conda-forge
protobuf                  3.9.2            py36h6de7cb9_1    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pvl                       1.2.1              pyhd8ed1ab_0    conda-forge
python                    3.6.7             h4a56312_1002    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36h20b66c6_0    conda-forge
qhull                     7.2.0                         0    usgs-astrogeology
qt                        5.9.6                         7    usgs-astrogeology
qwt                       6.1.3                         0    usgs-astrogeology
readline                  7.0               hcfe32e1_1001    conda-forge
scipy                     1.2.1            py36hbd7caa9_1    conda-forge
setuptools                49.6.0           py36h79c6626_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spiceypy                  2.3.2                      py_0    conda-forge
sqlite                    3.28.0               h9721f7c_0    conda-forge
suitesparse               5.10.1               h68a9093_0    conda-forge
superlu                   5.2.1             hbced767_1205    conda-forge
tbb                       2020.2               h940c156_4    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tnt                       126                           0    usgs-astrogeology
tzcode                    2021a                h0d85af4_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
x264                      20131218                      0    conda-forge
xerces-c                  3.1.4                h10f7eb2_0    usgs-astrogeology
xorg-fixesproto           5.0               h0d85af4_1002    conda-forge
xorg-inputproto           2.3.2             h35c211d_1002    conda-forge
xorg-kbproto              1.0.7             h35c211d_1002    conda-forge
xorg-libice               1.0.10               h0d85af4_0    conda-forge
xorg-libsm                1.2.3             h0d85af4_1000    conda-forge
xorg-libx11               1.7.2                h0d85af4_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xorg-libxext              1.3.4                h0d85af4_1    conda-forge
xorg-libxfixes            5.0.3             h0d85af4_1004    conda-forge
xorg-libxi                1.7.10               h0d85af4_0    conda-forge
xorg-xextproto            7.3.0             h35c211d_1002    conda-forge
xorg-xproto               7.0.31            h35c211d_1007    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.9                h582d3a0_0    conda-forge

**Comment by jessemapel** [comment]
This is a known bug with 5.0.1, see #4545, the fix will go out in 5.0.2 which I'm putting out right now. I'll provide update instructions once it's out.

**Comment by jessemapel** [comment]
For future reference, you can update by running `conda install -c usgs-astrogeology -c conda-forge isis=x.y.z` and replace x.y.z with the version you want to update to.
