### ISSUE TITLE
EDRGET Issue

### ISSUE THREAD

**Issue by dons83** [DOI-USGS/ISIS3#4577]
I am getting EDRGET errors any idea how to solve this in my installation? Think I need an update somewhere but don't know where!

edrget \
url=https://pds-imaging.jpl.nasa.gov/data/mro/mars_reconnaissance_orbiter/ctx/mrox_3668/data/N06_064898_1129_XN_67S119W.IMG
Cannot mix incompatible Qt library (version 0x50701) with this library (version 0x50906)
Aborted (core dumped)

**Comment by AustinSanders** [comment]
Hi @dons83,

I'm having trouble reproducing this error on OSX.  Can you provide your ISIS version and a list of packages in your conda environment as given by ```conda list```?

**Comment by dons83** [comment]
> Hi @dons83,
> 
> I'm having trouble reproducing this error on OSX. Can you provide your ISIS version and a list of packages in your conda environment as given by `conda list`?

When I next opened Ubuntu it said i had 97 updates to do. After running these the edrget command works although it saves way into the depths of my C: drive. How do you specify where it should save?

C:\Users\admin\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\dandydons

I would prefer it just save where isis3 is installed:

C:\Users\admin\unix\isis3

I am on ubuntu 20.04.2 LTS via a windows PC. ISIS3 appears to be version 3.9.1 is this the latest version or should I upgrade it somehow?

My conda list is:

# packages in environment at /root/anaconda3/envs/isis3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
armadillo                 8.200.0         blas_openblas_200  [blas_openblas]  conda-forge
arpack                    3.6.2           blas_openblash26a2512_200  [blas_openblas]  conda-forge
blas                      1.1                    openblas    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bullet                    2.86.1                        0    usgs-astrogeology
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2021.5.30        py36h5fab9bb_0    conda-forge
cspice                    66                h7f98852_1014    conda-forge
curl                      7.60.0                        0    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
doxygen                   1.8.14               hd1b7508_1    conda-forge
eigen                     3.3.3                         0    conda-forge
embree                    2.14.0                        0    conda-forge
expat                     2.4.1                h9c3ff4c_0    conda-forge
ffmpeg                    3.4.1                         0    conda-forge
flann                     1.8.4                         0    usgs-astrogeology
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
geos                      3.5.1                h6bb024c_1    usgs-astrogeology
geotiff                   1.4.2                hb54a4aa_1    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.51.4                        0    conda-forge
gmm                       5.0                           0    usgs-astrogeology
gmp                       6.1.2             hf484d3e_1000    conda-forge
gsl                       2.2.1           blas_openblas_3  [blas_openblas]  conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
harfbuzz                  1.3.4                         2    conda-forge
hdf5                      1.8.18                        3    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
isis3                     3.9.1                    py36_0    usgs-astrogeology
jama                      125                           0    usgs-astrogeology
jasper                    1.900.1                       4    conda-forge
jpeg                      9b                   h024ee3a_2
kakadu                    1                             0    usgs-astrogeology
krb5                      1.14.2                        0    conda-forge
ld_impl_linux-64          2.35.1               h7274673_9
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libffi                    3.3                  he6710b0_2
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.3.0               h5101ec6_17
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.5.0               h14aa051_19    conda-forge
libgfortran4              7.5.0               h14aa051_19    conda-forge
libgomp                   9.3.0               h5101ec6_17
libiconv                  1.15              h516909a_1006    conda-forge
libllvm12                 12.0.1               hf817b99_0    conda-forge
libopenblas               0.3.10               h5a2b251_0
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.5.2                h6bb024c_0    usgs-astrogeology
libssh2                   1.8.0                h9cfc8f7_4
libstdcxx-ng              9.3.0               hd4cf53a_17
libtiff                   4.0.9                he6b73bb_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.7                         0    conda-forge
llvm-tools                12.0.1               hf817b99_0    conda-forge
llvmdev                   12.0.1               hf817b99_0    conda-forge
mesalib                   17.2.0                        0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mysql                     5.7.20            hf484d3e_1001    conda-forge
mysql-connector-c         6.1.6                         0    conda-forge
nanoflann                 1.2.2                         0    conda-forge
ncurses                   5.9                          10    conda-forge
nn                        1.86.0            h14c3975_2003    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
opencv                    3.2.0           np113py36_blas_openblas_203  [blas_openblas]  conda-forge
openssl                   1.0.2n                        0    conda-forge
pcl                       1.8.1                h6bb024c_1    usgs-astrogeology
pcre                      8.45                 h9c3ff4c_0    conda-forge
pip                       9.0.1                    py36_1    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
postgresql                9.6.3                         3    conda-forge
proj4                     4.9.3                h516909a_9    conda-forge
protobuf                  3.5.2            py36h6bb024c_0    usgs-astrogeology
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
python                    3.6.0                         2    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
qhull                     7.2.0                         0    usgs-astrogeology
qt                        5.9.6                         7    usgs-astrogeology
qwt                       6.1.3                         0    usgs-astrogeology
readline                  6.2                           0    conda-forge
setuptools                38.5.1                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
suitesparse               4.5.4           blas_openblas_200  [blas_openblas]  conda-forge
superlu                   5.2.1             hfe2efc7_1208    conda-forge
tbb                       4.4                           0    usgs-astrogeology
tk                        8.5.19                        2    conda-forge
tnt                       126                           0    usgs-astrogeology
wheel                     0.30.0                   py36_2    conda-forge
x264                      20131218                      0    conda-forge
xalan-c                   1.11                          0    usgs-astrogeology
xerces-c                  3.1.4                         0    usgs-astrogeology
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.6.4                         6    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3


Now the following command has stopped working! Have  you seen this error? It worked ok before I updated ubuntu. Do I need to update ISIS3 now that Ubuntu has been updated fully?

(isis3) root@DESKTOP-RIN1FVK:/home/dandydons/isis3# mroctx2isis from=/mnt/c/Users/admin/unix/isis3/isis/N06_064874_1458_XN_34S191W.IMG to=/mnt/c/Users/admin/unix/isis3/isis/N06_064874_1458_XN_34S191W.cub
**I/O ERROR** Unable to open [/root/anaconda3/envs/isis3/data/base/translations/pdsImage.trn].

Totally new to UNIX, Ubuntu and ISIS3 just trying to figure out how to access the MRO images and start programming with them!

**Comment by AustinSanders** [comment]
By default, the edrget program downloads the files to your current working directory, so if you first navigate to your desired output directory (```cd C:\Users\admin\unix\isis3```) then you should be able to run edrget the same way you've been running it.  Otherwise, you can specify a "topath" argument, e.g.:

```
edrget url=https://pds-imaging.jpl.nasa.gov/data/mro/mars_reconnaissance_orbiter/ctx/mrox_3668/data/N06_064898_1129_XN_67S119W.IMG topath=C:\Users\admin\unix\isis3\images
```

although you will likely need to ensure that the full path (C:\Users\admin\unix\isis3) exists before running the command.


As for the new I/O error, I haven't seen this directly.  Can you verify that the translation file exists at /root/anaconda3/envs/isis3/data/base/translations/pdsImage.trn ?  If you recently updated your linux distribution, I would not be surprised if something broke along the way, and it may entail a reinstallation of ISIS.

**Comment by AndrewAnnex** [comment]
on a aside, maybe edrget should be deprecated in favor of using wget/curl? 

ie instead of the command above you would just run `wget https://pds-imaging.jpl.nasa.gov/data/mro/mars_reconnaissance_orbiter/ctx/mrox_3668/data/N06_064898_1129_XN_67S119W.IMG`

**Comment by rbeyer** [comment]
@AndrewAnnex see #3313

**Comment by dons83** [comment]
Hi got edrget to work with the topath added although I notice that sometimes it says100% complete but nothing has saved. Is the wget a better way to go would you say? Does it take the same topath so I can specify where the files download to? In any case I could use Python to download IMG files or a multitude of other ways so I am not too worried about it working through ISIS3.

I did a complete reinstall using some instructions someone had posted for windows ubuntu installation and mroctx2isis has worked so far. I have got as far as creating a map.cub file but I am not completely sure I have used the optimum settings at each stage. I might post my install steps so anyone can critique them where would be the best place? Next I am going to streamline them with variables so that I can run the final file creation for a downloaded IMG file to map.cub in one go. It does seem to take a little time. SO far I have just used qview to view but not sure if there is a better viewer.

**Comment by AustinSanders** [comment]
@dons83 The wget command is built directly into your unix/linux system, so it's completely independent of ISIS.   It can be used to grab files from URLs, but again, it will default to your current working directory.  You can specify a directory prefix using the -P option.  You can find very detailed information about wget and its usage [here](https://linux.die.net/man/1/wget)

As for getting feedback on your specific usage/parameterization of the programs, you're likely to find better help at https://astrodiscuss.usgs.gov/.   This channel is better suited to development questions, bug reports, etc., whereas astrodiscuss is better suited for general usage questions.

**Comment by dons83** [comment]
Ok thanks for your help I will try over there.
