### ISSUE TITLE
Merge isis3_mosaic_tracking into cmake

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#458]
- [x] Merge dev into isis3_mosaic_tracking
- [x] Run tests on isis3_mosaic_tracking build
- [x] Merge dev into cmake
- [x] Merge isis3_mosaic_tracking into cmake
- [x] Run tests on cmake build

**Comment by ihumphrey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Merge dev into mosaic tracking, then mosaic tracking into cmake](https://trello.com/c/VdertsIy/133-merge-dev-into-mosaic-tracking-then-mosaic-tracking-into-cmake)
