### ISSUE TITLE
Zenodo has not minted a new DOI since ISIS 4.2.0 ... a year ago

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#4583]
The Zenodo [super-link](https://doi.org/10.5281/zenodo.2563341) indicates that the most recent DOI is for ISIS 4.2.0, which was a year ago.  There have been additional GitHub Releases since then that should have triggered a new DOI.  Whomever has access to the Zenodo account that manages the ISIS DOI (Jay?) needs to dive into the Zenodo account and see if they can unblock the problem.

**Comment by jlaura** [comment]
I can confirm - build problems on the Zenodo side.

<img width="887" alt="Screen Shot 2021-08-05 at 12 53 49 PM" src="https://user-images.githubusercontent.com/2105468/128412693-be66e680-400d-49df-ba69-3d26cba4927b.png">


Looks like the problem might be with the author list. That is the thread I am going to pull at: 

```
{
    "errors": "{'metadata': {'creators': {0: {'orcid': ['Not a valid ORCID identifier.']}, 112: {'orcid': ['Not a valid ORCID identifier.']}}}}"
}
```
