### ISSUE TITLE
Is There a Basic Hapke Photometry Model in ISIS?

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#4587]
I'm trying to do some basic photometric corrections to MARCI data.  In the past, with other wide-angle Mars data, I've had good success with the HAPKEHEN model in PHOTOMET.  My method has been to guess-and-check-and-iterate on the various parameters until I get a fairly flat-looking median image at multiple longitudes over a wide range of latitudes.  However, MARCI data are too large to do this sort of guess-and-check parameter pace search due to the time needed to process them in PHOTOMET.

Instead, I designed a basic program that uses the 2002 iteration of Hapke's model with the Henyey-Greenstein scattering functions.  4.5 million parameter tests in 20 minutes, versus 1 test in 15 minutes.  I got parameters that do well and that look like they should be reasonable, but then when I try to put them back into the PHOTOMET program, I get horrible results for the parameters that should work.

I think the issue lies with the "extra" parameters that ISIS has: NORMNAME, INCREF, INCMAT, THRESH, ALBEDO.  The Hapke equations don't have those parameters (so far's I can tell), so I'm trying to figure out if there's a "more basic" version, or perhaps there are values I can put into those parameters that effectively make them do nothing so's to effectively reduce things to Hapke's equations?  My alternative is to get the backplane data and take things into GDAL to do my own version, but it seems like there should be a way to do this more "simply" in ISIS.

**Comment by AndrewAnnex** [comment]
there is this one: https://github.com/USGS-Astrogeology/ISIS3/blob/aab0e63088046690e6c031881825596c1c2cc380/isis/src/base/objs/Hapke/Hapke.cpp, but I assume it is the same one you ran into issues with in photomet. In that case there doesn't appear to be a more simplistic version in ISIS currently but it should be possible to modify that file to include more variants

**Comment by astrostu** [comment]
So, that's interesting that that exists.  How is it called?  In PHOTOMET, "Hapke" is not one of the listed valid parameters for the photometric model.  The two variations of Hapke then list these other, non-Hapke parameters as required inputs.

**Comment by AndrewAnnex** [comment]
looking at the isis docs it looks like https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/phoemplocal/phoemplocal.html may use use it but I have no first hand experience using it. However in re-reading the issue/docs for photomet I think that photomet is using this version of Hapke and those extra parameters you noted are part of the normalization step for photomet and have nothing to do with the hapke model: 

> The surface photometric function model type that describes the planetary surface. Any one of the surface photometric functions can be used in combination with any of the normalization type models and optionally an atmospheric photometric model.

**Comment by lwellerastro** [comment]
`How is it called? In PHOTOMET, "Hapke" is not one of the listed valid parameters`

@astrostu, many things in photomet are driven by the FROMPVL input file.  There are templates available based on past work and possibly publcations (you'd have to look at the comments in the pvl file) under $ISISROOT/appdata/templates/photometry/.  Check out the *mdim*hapken*pvl files for an idea of what's available.  You can also load these directly via the gui using the helper Select File icon to the right of the FROMPVL input window.  Sorry if I'm relaying something you already know.

I'm not sure what is considered a simple basic version of the hapke model, but this is something we used for the Messenger global mosaic (these were filter dependent):
```
Object = NormalizationModel 
  Group = Algorithm 
    Name = Albedo 
    PhotoModel = HapkeHen 
    Incref=30.0
    Thresh=10E30
    Incmat=0.0
    Albedo=1.0
  EndGroup 
EndObject 
Object = PhotometricModel 
  Group = Algorithm 
    Name = HapkeHen 
    ZeroB0Standard = false
    Wh=0.180850485
    Hh=0.075
    B0=2.3
    Theta=8.325333223
    HG1=0.269202201
    HG2=0.556319739
  EndGroup 
EndObject 
```

I think @AndrewAnnex is correct in that the extra parameters that don't pertain to the model are simply not used.  But don't hold me to that - I have limited experience with photomet under more current versions of isis (have mostly used pre-isis3 photom/photompr).

**Comment by astrostu** [comment]
@AndrewAnnex and @lwellerastro — Thanks.  I'm not a photometrist (is that a thing?) so I'm learning a bit as I go, and I think Lynn's post drove the point home to me that it is doing the basic Hapke correction, and that all those other parameters I was trying to figure out are ISIS's attempt to normalize the result.  For instance, if your photometric model were perfect, and you just subtracted it from the image, then the mean value of the new image would be 0 meaning you have negative reflectivities.  So, you have to bring it back up and normalize in some way, and it's ISIS's normalization now that is giving me the headache.

So, thanks for the clues to solving (or at least advancing) on my situation/problem/issue.  I'm going to go ahead and close this because the original question I asked is basically answered.
