### ISSUE TITLE
Combine existing import/export applications

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#4606]
**Description**  
Combine existing import/export apps into one import, and one export app

Place all comments regarding RFC 7 - [Redesign Import Export programs](https://github.com/USGS-Astrogeology/ISIS3/wiki/RFC-7---Redesign-Import-Export-programs) in this issue

**Example**  
`isisimport from=tgocassis.img to=tgocassis.cub`
`isisexport from=tgocassis.cub to=tgocassisrdr`

**Comment by lwellerastro** [comment]
- Users will be able to modify templates without recompiling ISIS

Will every camera have a template covering all of the current keywords currently translated?  As you know missions do not tend to use the same keywords for identical information and there are always those mission specific keywords. 

Will templates be available under the data area to point to and modify if there are keywords of interest missing?

What about those handful of ingestion programs (kaguyatc2isis being one) that has parameters beyond from and to?

It would be helpful to see specific examples when they become available.

I'm sure I'll have more questions in the future as I don't fully understand the scope of what's laid out in the RFC.

**Comment by scsides** [comment]
> * Users will be able to modify templates without recompiling ISIS
> 
> Will every camera have a template covering all of the current keywords currently translated? As you know missions do not tend to use the same keywords for identical information and there are always those mission specific keywords.

Because of the reasons you listed we expect each camera to have its own template. Some may be able to be combined, but we plan to do that only if they are identical or can be easily tweaked using the template capabilities.

> 
> Will templates be available under the data area to point to and modify if there are keywords of interest missing?

All of the templates will be distributed with ISIS. The current thinking is that if someone wants to use their own or a modified version of the one in ISIS, all they would have to do is supply the new template file name on the command line. This would override the automatic template name.

> 
> What about those handful of ingestion programs (kaguyatc2isis being one) that has parameters beyond from and to?

There are plans to allow some keywords that are used regularly to be overridden (e.g., TargeName). More complex apps may not be able to be converted to this method. 
> 
> It would be helpful to see specific examples when they become available.
There is one for tgo now in the system  (appdata/import and appdata/export)
> 
> I'm sure I'll have more questions in the future as I don't fully understand the scope of what's laid out in the RFC.
