### ISSUE TITLE
LRO SCLK files are being cycled out of the data area too quickly

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4609]
**ISIS version(s) affected**: ISIS 4.1+

**Description**  

We are only keeping the 10 newest LRO SCLKs around. When a new one is added, the oldest is removed. This is causing the ObservationPair fixture, likely some user's images, to fail to generate a camera model because they can't find the SCLK to load for clock conversions.

**How to reproduce**  

All tests that use the ObservationPair fixture on nightly are failing because they are looking for `$lro/kernels/sclk/lro_clkcor_2021159_v00.tsc` but the oldest SCLK we have in the current data area is `$lro/kernels/sclk/lro_clkcor_2021167_v00.tsc`.

**Possible Solution**  

A couple options are:

1. Keep more SCLK files around, they are around 2MB each and released weekly. So the entire missions would be ~1.25 GB of data. That's a fair amount for SCLKs but maybe okay. We could also cut that down by keeping the last from each month or year.
2. Add the ability to always use the latest SCLK file. Most SCLK files are backwards compatible and will produce the same conversions as previous files but cover a wider range. My understanding is that the LRO SCLKs are this way, but the TGO SCLKs are not.

**Comment by jessemapel** [comment]
Revert changes to observation pair tests in #4666 when this is done.

**Comment by gsn9** [comment]
Would it be better to keep all of the SCLK files around or would it be better to add the ability to use the latest SCLK file and just keep the 10 most recent SCLK files like we are currently doing?  Or could we just up the file count that we are keeping from 10 to like ~25?

**Comment by jessemapel** [comment]
It depends on how large the SCLK files are. If they are not very large, it would be best to just keep all of them around. If we instead kept 25, then we'd just be pushing this problem out farther instead of actually fixing it.

**Comment by gsn9** [comment]
Do we just want to keep all of them around then? There's only ~18mb of space being used currently for 10 SCLK files
![Screen Shot 2021-11-09 at 4 39 10 PM](https://user-images.githubusercontent.com/78241862/141022985-471475a2-25cd-4dbe-9091-524c026e704d.png)

**Comment by jessemapel** [comment]
@gsn9 There are many many more on the lro server that we are not serving. If we served all of those how big would it be?

**Comment by scsides** [comment]
@jessemapel , @gsn9: The sclk files are updated weekly. The current size is 1.8M each with tiny increases. Total size for all existing sclk files is 647M.

**Comment by jessemapel** [comment]
So we'd be expecting ~1 GB total within the next several years. That doesn't seem consequential to me. I'd say we just don't clean out the SCLKs and serve all of them.

**Comment by scsides** [comment]
Sounds reasonable.

**Comment by gsn9** [comment]
@jessemapel @scsides if we want to server all of them I just need to update the [`updateLroKernels` file](https://code.chs.usgs.gov/gnelson/isis3mgr_scripts/-/blob/master/updateLroKernels) to not clean up all the LRO SPK kernels and then push my changes? One thing I'm worried about is testing this since I don't have access the the ASU servers to verify this is working.

**Comment by jessemapel** [comment]
@gsn9 For right now just start working on the change. We will likely review the change for anything obvious and then merge it. If there's problems we can easily revert it.

**Comment by gsn9** [comment]
I opened up a merge request on git lab, here's the [link](https://code.chs.usgs.gov/asc/isis3mgr_scripts/-/merge_requests/19)

**Comment by jessemapel** [comment]
Merged, I'll check back in the morning to see if we picked up more sclks.

**Comment by jessemapel** [comment]
This has been fixed. We're now distributing the entire set of SCLKs.
