### ISSUE TITLE
install ISIS: solving environment forever!

### ISSUE THREAD

**Issue by mengtingpan** [DOI-USGS/ISIS3#4616]
Hi

I'm installing ISIS 5.0.2 using anaconda according to the installation guide (https://github.com/USGS-Astrogeology/ISIS3#installation). 

When I type: conda install -c usgs-astrogeology isis=5.0.2, it kept solving environment. 

Some people said it is due to the low version of conda (my conda is 4.5.11). However, after I conda upgrade -n base -c defaults --override-channels conda, it said the environment is inconsistent...

What's the problem?

the conda info:

(isis) pmo@XPS:~$ conda info

     active environment : isis
    active env location : /home/pmo/anaconda3/envs/isis
            shell level : 2
       user config file : /home/pmo/.condarc
 populated config files : /home/pmo/.condarc
                          /home/pmo/anaconda3/envs/isis/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /home/pmo/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/usgs-astrogeology/linux-64
                          https://conda.anaconda.org/usgs-astrogeology/noarch
                          https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/main/noarch
          package cache : /home/pmo/anaconda3/pkgs
                          /home/pmo/.conda/pkgs
       envs directories : /home/pmo/anaconda3/envs
                          /home/pmo/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/5.4.0-42-generic ubuntu/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by mengtingpan** [comment]
I tried on another machine, and the results are the same, kept solving environment.

**Comment by jlaura** [comment]
Hello @mengtingpan, 

I would try: `mamba install -c usgs-astrogeology isis=5.0.2`.  [Mamba](https://github.com/mamba-org/mamba) has been significantly faster for me than Conda, solving when conda is stuck spinning.

Let us know how that goes!

**Comment by mengtingpan** [comment]
> Hello @mengtingpan,
> 
> I would try: `mamba install -c usgs-astrogeology isis=5.0.2`. [Mamba](https://github.com/mamba-org/mamba) has been significantly faster for me than Conda, solving when conda is stuck spinning.
> 
> Let us know how that goes!

Hi jlaura,

Thanks for your reply. I have made it right. Thanks for the recommandation of mamba. It is interesting!

**Comment by jessemapel** [comment]
We should probably change all of the installation instructions to use mamba.
