### ISSUE TITLE
Review outstanding PR's into dev and determine if targeted for release

### ISSUE THREAD

**Issue by ihumphrey** [DOI-USGS/ISIS3#463]
There a some outstanding PR's into dev.

We should review these and see which ones should be isis3.6.0.

- [x] Add the PR's that can go into isis3.6.0 to the isis3.6.0 milestone

**Comment by jessemapel** [comment]
#94 is waiting on test data. I'm working with OREX to get it still. Once it has test data, I will write tests for it and it can go in. If I get to that before 3.6.0 .... we'll see.

**Comment by ihumphrey** [comment]
@jessemapel Thanks Jesse :+1:

**Comment by ihumphrey** [comment]
All of the appropriate PR's have been either marked with the isis3.6.0 or merged.
