### ISSUE TITLE
libarmadillo.so.9 missing on CI builds, what pin to use?

### ISSUE THREAD

**Issue by AndrewAnnex** [DOI-USGS/ISIS3#4630]
**ISIS version(s) affected**: 4.4.0

**Description**  
I have ci tests that are failing when using ISIS due to a missing dynamic library, libarmadillo.so.9, similar to #4165 
It looks like armadillo 10.6.2 was released a few weeks ago and my CI is installing that version instead of an older version 9, however I don't know which version 9 minor/patch version to pin to, to fix my ci job.

**How to reproduce**  
this conda yaml should reproduce the environment
```
name: isis_for_asap
channels:
  - usgs-astrogeology
  - conda-forge
  - defaults
dependencies:
  - isis=4.4.0
```

and then if you run `ldd qview` from that environment you should see the missing library

**Possible Solution**  
A suggestion on a particular version to pin to would be great, as I don't know if `armadillo=9` is sufficient.

**Additional context**  
relevant logs can be found in the logs for these github action runs: https://github.com/AndrewAnnex/asap_stereo/actions/workflows/ci-test-notebook.yml

relevant line from conda info:
`armadillo                 10.6.2               h7c03176_0    conda-forge`

**Comment by jessemapel** [comment]
We already added a pin to armadillo for 4.4+ on Mac and 5.0+ on Linux that restricts it to armadillo 9. The Linux 4.4.0 build looks like the last one with out the new pin. So, you can either update to 5.0 or add an armadillo pin, here's the 5.0 pin for example `  - armadillo >=9.900,<10.0a0`

**Comment by jessemapel** [comment]
Labeling this as a question because it's a known issue with an old version that is not supported and has been fixed in more recent versions.

**Comment by jessemapel** [comment]
Also related to #4103

**Comment by AndrewAnnex** [comment]
okay closing the issue
