### ISSUE TITLE
Running ISIS with Dawn data

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#4638]
**ISIS version(s) affected**: 5.0.1

**Description**  

I cannot spiceinit a Dawn mission cub file

**How to reproduce**  

First I fetched the latest ISIS data as:

 rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/dawn ~/projects/isis3data 

then set up the ISISDATA value. 

I verified that the desired kernels are where they should be (in this case, dawn/kernels/ik/dawn_fc_v10.ti). 

Then I fetched the .IMG from PDS and tried to create the .cub file:

wget https://sbib.psi.edu/data/PDS-Vesta/Survey/img-1B/FC21B0004011_11224024300F1E.IMG.gz
gunzip FC21B0004011_11224024300F1E.IMG.gz
dawnfc2isis from=FC21B0004011_11224024300F1E.IMG to = FC21B0004011_11224024300F1E.cub
spiceinit from = FC21B0004011_11224024300F1E.cub

I get the errors:

Group = Kernels
  NaifFrameCode             = -203121
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = $base/kernels/pck/pck00009.tpc
  TargetPosition            = $dawn/kernels/tspk/de421.bsp
  InstrumentPointing        = ($dawn/kernels/ck/dawn_sc_110808_110814.bc,
                               $dawn/kernels/fk/dawn_v15.tf,
                               $dawn/kernels/fk/dawn_fc_v3.bc)
  Instrument                = $dawn/kernels/ik/dawn_fc_v10.ti
  SpacecraftClock           = $dawn/kernels/sclk/DAWN_203_SCLKSCET.00091.tsc
  InstrumentPosition        = $dawn/kernels/spk/dawn_rec_110802-110831_110922-
                              _v1.bsp
  InstrumentAddendum        = $dawn/kernels/iak/dawnfcAddendum002.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 2
  Error                     = "An unknown NAIF error has been encountered. The
                               short explanation provided by NAIF is
                               [SPICE(SPKINSUFFDATA)]. The Naif error is
                               [Insufficient ephemeris data has been loaded to
                               compute the state of 2000004 (VESTA) relative to
                               0 (SOLAR SYSTEM BARYCENTER) at the ephemeris
                               epoch 2011 AUG 12 02:44:06.668.]"
End_Group
**ERROR** Unable to initialize camera model.

**Comment by AustinSanders** [comment]
Hi @oleg-alexandrov -- I think I've found the problem, but it's not yet clear to me _why_ we're running into this problem.  The TSPK found by spiceinit (isis_data/dawn/kernels/tspk/de421.bsp) does not include Vesta.  I was able to run spiceinit with:

```spiceinit from= FC21B0004011_11224024300F1E.cub TSPK='(/usgs/cpkgs/isis3/isis_data/dawn/kernels/tspk/sb_vesta_110211.bsp, /usgs/cpkgs/isis3/isis_data/dawn/kernels/tspk/de421.bsp)' ```

I'll continue looking into the problem on the spiceinit side, but in the meantime, you should be able to process dawn data by providing it with the necessary TSPKs.

**Comment by jlrizos** [comment]
I am experiencing a similar error:

Error                     = "No pointing available at requested time
                               [484127469.19564] for frame code [10101]"
End_Group
**ERROR** Unable to initialize camera model.

I understand I can solve it attaching the correct kernels, right? Do you know how can I identify the needed kernels by hand? I tried running the above command but does not work.

spiceinit from=FC21B0036778_15125195001F1F.cub TSPK='($dawn/kernels/tspk/sb_vesta_110211.bsp, $dawn/kernels/tspk/de421.bsp)'

Thanks

**Comment by jlrizos** [comment]
Hi, I just want to let you know that the solution did not work for Dawn
mission data. After wasting a lot of time, the solution was installing
Ubuntu 14.04 in a Virtual Machine, the old ISIS version 3.5 and now it
works. I run spiceinit without any problem. I think you should work on
these data because people are wasting a lot of time on this issue. Thanks.

**Comment by jlrizos** [comment]
Hi, I just want to let you know that the solution did not work for Dawn mission data. Providing it with the necessary TSPKs does not work. After wasting a lot of time, the solution was installing Ubuntu 14.04 in a Virtual Machine, the old [ISIS version](https://isis.astrogeology.usgs.gov/documents/LegacyInstallGuide/index.html) and now it works. I run spiceinit without any problem. I think you should work on these data because people are wasting a lot of time on this issue. Thanks.

**Comment by oleg-alexandrov** [comment]
This was closed without an explanation. The explanation is here: https://github.com/USGS-Astrogeology/ISIS3/issues/4684.

I can confirm that:

dawnfc2isis from=FC21B0004011_11224024300F1E.IMG to = FC21B0004011_11224024300F1E.cub target=VESTA

spiceinit from = FC21B0004011_11224024300F1E.cub 

works (so, add target=VESTA), and the resulting images are usable with stereo. Now, creating a CSM file from .cub does not work, but that's a different story.
