### ISSUE TITLE
isis.astrogeology.usgs.gov not working

### ISSUE THREAD

**Issue by audiefen** [DOI-USGS/ISIS3#4640]
Looks like the cert has expired. Tried Chrome and Safari.

NET::ERR_CERT_DATE_INVALID
Subject: isis.astrogeology.usgs.gov

Issuer: DigiCert SHA2 High Assurance Server CA

Expires on: Sep 16, 2021

Current date: Sep 17, 2021

**Comment by AustinSanders** [comment]
@audiefen Thanks for the heads up -- we've notified IT, and it looks like this is in the process of being resolved.

**Comment by audiefen** [comment]
Thanks @AustinSanders!

**Comment by AustinSanders** [comment]
@dsvolkov That's correct, and we apologize for the inconvenience.  We're still in the process of resolving the issue, but the problem exists outside the control of our immediate department.

I will update this issue as more information is made available.

**Comment by jlaura** [comment]
The site is back up now. Thanks for the heads up. We should see a < 24 hour turn around should we have another issue.

**Comment by audiefen** [comment]
I think something is still not quite right. Several people here at HiRISE still cannot connect using Chrome, Safari and Firefox. I was able to connect (Chrome and Safari) yesterday to the site and still can from the computer I was using yesterday. I can inspect the new certificate and the expiration is Thursday, September 22, 2022. I tried connecting from a different system this morning (using Chrome) and was still getting the NET::ERR_CERT_DATE_INVALID with the old certificate expiration date. On that different system, I cleared the cached SSL certificate by going into Chrome settings,  and clearing "Site Settings". Now I get the following error:

isis.astrogeology.usgs.gov didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by jlaura** [comment]
@audiefen I looked back with my IT team yesterday and they rechecked whatever it is that they are rechecking. Can you confirm that the site is back and working? It is for me, and the site [https://downforeveryoneorjustme.com/isis.astrogeology.usgs.gov](https://downforeveryoneorjustme.com/isis.astrogeology.usgs.gov) is showing that the site is working, but I also don't want to assume it is fixed because of two data points.

Thanks!

**Comment by audiefen** [comment]
@jlaura It's working for me too now. I'm checking with others at HiRISE just to make sure. I'll let you know if I hear back in the negative. Thanks!
