### ISSUE TITLE
cnetcheck not excluding ignored measures resulting in false positives

### ISSUE THREAD

**Issue by KrisBecker** [DOI-USGS/ISIS3#4649]
**ISIS version(s) affected**: All

**Description**  
cnetcheck is not properly excluding ignored measures when, at a minimum, checking for invalid latitude/longitudes and islands. These situations occur rather frequently when using feature matching, which does find points on limbs.

The net effect of this bug is reports of bad points and islands than don't actually exist.

Below are processing steps that provide the evidence of these problems, but it is in an older version of ISIS (~3.6). However, I have reviewed the code in the current version and have concluded the problem exists there as well (i.e., the code is identical in both versions).

Its possible ignored points are part of the problem as well.

**How to reproduce**  
The following processing sequence shows the steps used to demonstrate the bug. I have only included pertinent output between runs for brevity:

```
cnetcheck cnet=05_osinac_m26_registered.net fromlist= 04_network_cubes.lis prefix=05_osinac_m26_check_ ignore=true
Group = Results
  Islands       = 137
  NoLatLonCubes = 108
  LowCoverage   = 478
  SingleCube    = 5
End_Group

cnetcombinept cnetbase=05_osinac_m26_registered.net onet=05_osinac_m26_registered_clean.net imagetol=0 cleannet=true cleanmeasures=true minmeasures=0
Group = Summary
  TotalCubes        = 478
  TotalInputPoints  = 152297
  TotalOutputPoints = 62535
  PointsMerged      = 0
  PointsEvaluated   = 0
  TotalMeasures     = 536917
  MeasuresMerged    = 0
  MeasuresDeleted   = 2673285
  MinimumMeasures   = 0
End_Group

cnetcheck cnet=05_osinac_m26_registered_clean.net fromlist=04_network_cubes.lis prefix=05_osinac_m26_clean_check_ ignore=true
Group = Results
  Islands       = 19
  NoLatLonCubes = 77
  LowCoverage   = 478
  SingleCube    = 5
End_Group
```

**Possible Solution**  
There needs to be additional tests that check for ignored measures added to the lat/lon and island functions. A more thorough review of cnetcheck might be indicated as well.

Clearly you can work around this problem by cleaning first, but there are certainly cases where you may want to run additional processing to attempt to salvage the data as much as possible. Its still a bug, nonetheless.

**Additional context**  
None

**Comment by KrisBecker** [comment]
**Alternative: How to reproduce**

The traditional alternative to cnetcombinept is cnetedit. Here is the result using this approach:

```
cnetedit cnet=05_osinac_m26_registered.net onet=05_osinac_m26_registered_cne.net 

cnetcheck cnet=05_osinac_m26_registered_cne.net fromlist=04_network_cubes.lis prefix=05_osinac_m26_clean_cne_check_ ignore=true
Group = Results
  Islands       = 19
  NoLatLonCubes = 77
  LowCoverage   = 478
  SingleCube    = 5
End_Group

```

**Comment by acpaquette** [comment]
@KrisBecker Could you send over the files to reproduce this error? 

Also I am not exactly sure what the problem here is, should we be seeing no islands in the second output? I understand that we may be seeing islands that don't exist but I don't understand what you mean by bad points

**Comment by KrisBecker** [comment]
I can pretty much guarantee that the files I send you would not be sufficient to reproduce this problem. I have made significant changes to the Rosetta OSIRIS camera model that is incompatible with the current version.

I can point you to the code where I think the problem is.

Note that there is no check for a valid measure in the [noLatLonCheck()](https://github.com/USGS-Astrogeology/ISIS3/blob/bd43b627378c4009c6aaae8537ba472dbefb2152/isis/src/control/apps/cnetcheck/cnetcheck.cpp#L610-L661) method. Specifically, this [loop](https://github.com/USGS-Astrogeology/ISIS3/blob/bd43b627378c4009c6aaae8537ba472dbefb2152/isis/src/control/apps/cnetcheck/cnetcheck.cpp#L638-L657) on measure checks associated with serial numbers (cubes) tests for ignored points, but I don't see any such check for an ignored measure, which would prevent testing the point associated with it - a false positive.

Hopefully this is enough information to verify the problem. 

Also, if you could, please run a quick check of the rest of code for similar issues.
