### ISSUE TITLE
Support CentOS 7 for development

### ISSUE THREAD

**Issue by ihumphrey** [DOI-USGS/ISIS3#465]
See #435 for some discussion about CentOS 7.

**Comment by jessemapel** [comment]
I think that we can support this by just using the pre-5 ABI in the compilation of the dependencies. See https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by jessemapel** [comment]
recompiling the dependencies on CentOS7 seems to fix this. I still need to check that it doesn't break builds on newer linux systems. It shouldn't, but it's worth testing.

**Comment by jessemapel** [comment]
Recompiling protobuf, pcl, geos, and flann on a CentOS 7 box fixes the problem, but these builds are not compatible with gcc 5+. So, CentOS7 will need a separate environment file that uses these pre gcc 5 builds. I'll get these builds pushed up to our anaconda cloud with special gcc4 labels and the new environment file setup, then put up a PR to support CentOS7.

**Comment by jessemapel** [comment]
- [x] Update CentOS 7 specific test data
- [x] Push up builds
- [x] Create new environment_gcc4.yml
- [x] Update build documentation

**Comment by jessemapel** [comment]
A test environment is at https://github.com/jessemapel/ISIS3/tree/centos7

The main difference is that the gcc4 builds are on my anaconda cloud and not the main usgs-astrogeology channel.
