### ISSUE TITLE
I am getting permission denied error in bash shell while using hi2isis command in isis3 build version.

### ISSUE THREAD

**Issue by Faom13** [DOI-USGS/ISIS3#4650]
I am using ISIS3 in ubuntu 14.10 which is running on VM Ware Workstation 14 pro (14.1.3 build-9474260)
While running hi2isis command in bash shell, permission denied error is prompted. 
I am getting no error while using mroctx2isis command, but for most of the commands, I am getting the same error. 
Please have a look at the attached snapshot.
![Error_hi2isis](https://user-images.githubusercontent.com/92035133/136213382-175e8660-4cba-49ee-9813-22b2b86c958a.JPG)
.

**Comment by jlaura** [comment]
@Faom13 What version of ISIS are you running? It looks like you are running a pre-conda version of ISIS since you are using `export ISISROOT` instead of `conda activate isis`.

Also, how did you install isis? Using conda it should be installed into a user location that does not need any elevated permissions.

**Comment by Faom13** [comment]
I am using ISIS version 3. and i used legacy method for building the ISIS Environment on LINUX. so, yes it is a pre-conda version.

**Comment by jlaura** [comment]
@Faom13 - I would strongly advocate that you install using the supported installation method, using conda, as described in the README. 

If that does not work for some reason, my other suggestion is to check that you have not installed using `su` or as a privileged account. I would check the ownership of the executable and the data areas as this appears to be permissions related. Unfortunately, it is not possible to provide much more good support (honestly, unsupported older version on an unsupported OS) for a permissions issue that is local to your machine.

If you can provide more information about how you installed and what the permissions inside your machine (VM?) look like, you might get some more traction on this issue. My first step would be to install a recent version of the code though.

**Comment by AustinSanders** [comment]
@Faom13 I'm going to mark this issue as 'closed' under the assumption that the previous guidance resolved this issue.  If you have any further questions or would like to provide more information, feel free to reopen the issue.
