### ISSUE TITLE
Is it possible to convert a Curiosity's(MSL) single MASTCAM image into an orthophoto？

### ISSUE THREAD

**Issue by SherryCampbell** [DOI-USGS/ISIS3#4660]
Hello,
Recently I am thinking whether it's possible to convert a Curiosity's(MSL) single MASTCAM image into an orthophoto.

I've made the following attempts but failed:
1. Using ISIS's applications such as cam2map, pds2isis. It seems it's unable to convert Curiosity's .lbl files(PDS3) to .cub;

2. Trying to write the orthographical correction program myself. Theoretically,  an image can be geometrically corrected with it's interior and exterior orientation parameters. The MASTCAM image do provide the SITE_FRAME coordinate system and CAHVOR camera model, but unfortunately I don't know whether it could be transformed into the latitude and longitude of the location where the photo was taken

Might be a strange question but look forward to you reply!

**Comment by jessemapel** [comment]
ISIS does not support MSL Mastcam as a sensor and it is unlikely to be added. I have done some research into what would be required to support it or even just a generic CAVHOR model using our new CSM tooling, but it's not currently on our roadmap.

My understanding is that the Mastcam data is processed using [VICAR](https://www-mipl.jpl.nasa.gov/external/vicar.html), so I would look into that. If you absolutely must use ISIS, you can try to use external tools to generate lat/lon backplanes for the images and use [nocam2map](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/nocam2map/nocam2map.html) to project the data into an orthoimage.
