### ISSUE TITLE
Need help installing ISIS on MacOS Big Sur

### ISSUE THREAD

**Issue by captainrlkirk** [DOI-USGS/ISIS3#4662]
**ISIS version(s) affected**: 6.0.0

**Description**  
I am trying to install the current ISIS on a Mac that was wiped and given a clean install of Big Sur .  Please set aside that ISIS has not been built on this OS and MAY not work; I'll take my chances.  The problem is a failure to complete the installation process outlined on the ISIS github main page.  I installed Anaconda, created an environment for isis, and installed Mamba successfully.  Step 7 (mamba command to install current ISIS) gives the error message included under Additional Context.

**How to reproduce**  
MacBook Pro 16" 2019, MacOS Big Sur 11.6, current versions of Anaconda (Individual edition for Mac python 3.8 64 bit) and Mamba.  Both were installed 10/26/21
Follow ISIS installation steps on https://github.com/USGS-Astrogeology/ISIS3

**Possible Solution**  

**Additional context**  
Mamba command and output (lightly edited)
(isis) IGSWZAWGLT00023:~ rkirk$ mamba install -c usgs-astrogeology isis
                    [Mamba logo char art deleted to save space]
        mamba (0.4.2) supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

usgs-astrogeology/noarch [====================] (00m:00s) Done
usgs-astrogeology/osx-64 [====================] (00m:00s) Done
pkgs/main/osx-64         [====================] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/r/osx-64            [====================] (00m:00s) Done
conda-forge/noarch       [====================] (00m:01s) Done
conda-forge/osx-64       [====================] (00m:04s) Done

Looking for: ['isis']

Encountered problems while solving.
Problem: package python-3.6.13-h88f2d9e_0 requires openssl >=1.1.1j,<1.1.2a, but none of the providers can be installed

(isis) IGSWZAWGLT00023:~ rkirk$

**Comment by acpaquette** [comment]
@captainrlkirk This is an issue with creating an environment with a general python 3.X install where ISIS likely needs python 3.10. We should likely remove the step in the install guide of making the environment then installing ISIS into it. Rather we should just make the environment with the first install being ISIS.

Best fix for this particular issue is to run the following:
`mamba install -c usgs-astrogeology isis python=3`

**Comment by captainrlkirk** [comment]
Sounds good, thanks.  I will try that, but...do I need to delete the "isis" environment I already created first, or will this command overwrite the python version already in that environment?  If delete (as distinct from deactivate), I could use instruction how to do this as I have not done it before.
Keeping documentation up to date is a never-ending and rather thankless task. I'll say thanks that the ISIS install instructions are so detailed and explicit, even though it means the details may need to be changed more often.  The explicitness really helps those of us who don't have previous experience with these kinds of installation processes.

**Comment by jlaura** [comment]
I would delete the environment, just to be safe. Conda does some caching that, while very helpful most of the time, can be an issue. To try and keep things really clean, I would run:

```
conda remove --name myenv --all. # where my env is likely isis
conda clean --all. # to clean out any cached packages / data
```

Then recreate as @acpaquette suggested.

```
conda create -n isis6.0.0. # Note no python here, just make the env
conda activate isis6.0.0. # I like to have the version in the env name so I can test different versions on the same machine
mamba install -c usgs-astrogeology isis python=3
```

**Comment by captainrlkirk** [comment]
: (  I ran the commands above to delete my current isis environment, create a new one, and install current ISIS.  Mamba gave the following error message:

Looking for: ['isis', 'python=3']

Encountered problems while solving.
Problem: nothing provides armadillo 8.200.0 needed by isis-3.10.0-py36_0

**Comment by jessemapel** [comment]
It looks like it's trying to install 3.10

Try this for the last line `mamba install -c usgs-astrogeology isis=6 python=3`

**Comment by captainrlkirk** [comment]
This changed the error generated to a different package:

(isis6.0.0) IGSWZAWGLT00023:~ rkirk$ mamba install -c usgs-astrogeology isis=6 python=3
[omitting mamba char art, etc.]
Looking for: ['isis=6', 'python=3']

Encountered problems while solving.
Problem: nothing provides ale >=0.8.5,<1.0a0 needed by isis-6.0.0-0

**Comment by captainrlkirk** [comment]
This changed the error generated to a different package:

(isis6.0.0) IGSWZAWGLT00023:~ rkirk$ mamba install -c usgs-astrogeology isis=6 python=3
[omitting mamba char art, etc.]
Looking for: ['isis=6', 'python=3']

Encountered problems while solving.
Problem: nothing provides ale >=0.8.5,<1.0a0 needed by isis-6.0.0-0

**Comment by acpaquette** [comment]
@captainrlkirk There are definitely versions of ale==0.8.5 built against python 3.6. This may be an issue of not adding the conda-forge channel that ale is being distributed on.

Similar to @jessemapel suggestion, try:
`mamba install -c usgs-astrogeology -c conda-forge isis=6 python=3`
as the last line in the previous installation recommendation from @jlaura

**Comment by captainrlkirk** [comment]
Combining these suggestions definitely made the lights blink and the wheels spin!  The mamba installation appears to have completed successfully.  I then followed step 7.1 of the installation instructions (set up environment variables by running isisVarInit.py script and re-activating the environment).  However, an attempt to run a simple ISIS program shows that something is still missing:

(isis) IGSWZAWGLT00023:~ rkirk$ crop
dyld: Library not loaded: @rpath/libavresample.3.dylib
  Referenced from: /opt/anaconda3/envs/isis/lib/libopencv_videoio.3.2.0.dylib
  Reason: image not found
Abort trap: 6

Did I miss a step, or is this an indication that ISIS isn't going to work under Big Sur (yet)?

**Comment by Kelvinrr** [comment]
@captainrlkirk This is basically where I am at with getting ISIS running on Big Sur, it's very similar to the build problem (#4667). @acpaquette has had luck after updating core libraries via brew, I'll test this out hopefully soon (I am waiting for IT, RIP) and see if I can get past this error.

**Comment by captainrlkirk** [comment]
@Kelvinrr Thanks!  I realize this is cutting edge at the moment.  The USGS dumped a lot of us into the heavy surf of the Big Sur at once...but I'm the guy who can't swim so I rely on the rest of you for help. :^ D  Please alert me when there's progress that I can use (bearing in mind that you will have to hold my hand with any additional tools like brew that end up being needed).

**Question:**  I currently have temporary admin access to (re)install software after transition to Big Sur.  Should I install Homebrew now so I will have it later when I don't have admin privileges?  If so, any gotchas about versions?  I have already installed Xcode, which I see is a prerequisite.

**Comment by Kelvinrr** [comment]
@captainrlkirk 

fix was simpler than I thought, the version being picked up for ffmpeg renamed the libavresample lib, try: `mamba install ffmpeg=3.4.1`


It's been a long time since I have done much with homebrew, so I personally don't think I can answer that question atm.

**Comment by captainrlkirk** [comment]
@Kelvinrr I tried installing ffmpeg 3.4.1 after conclusion of the previous installs and it was not found.

(isis) IGSWZAWGLT00023:~ rkirk$ mamba install ffmpeg=3.4.1
...
Looking for: ['ffmpeg=3.4.1']

Encountered problems while solving.
Problem: nothing provides requested ffmpeg 3.4.1**

**Comment by Kelvinrr** [comment]
@captainrlkirk try `mamba install -c conda-forge ffmpeg=3.4.1`, I forget I have several channels in my .condarc so I don't usually have to enter them manually.

**Comment by captainrlkirk** [comment]
SWEET!  The install worked and I am now able to run qview indicating ISIS is set up and knows how to display.

I plan to leave this thread open for 24 hours or so in case I run into other problems, but I think my problem is solved. Thanks to all who helped!

**Comment by AlanHoward** [comment]
This works on MacOS Monterey

**Comment by captainrlkirk** [comment]
Closing thread.  Many thanks to all.
