### ISSUE TITLE
edrget Deprecate 

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#4665]
In https://github.com/USGS-Astrogeology/ISIS3/pull/4641 a deprecation warning was added to `edrget`. According to our [wiki](https://github.com/USGS-Astrogeology/ISIS3/wiki/Deprecation), we can remove the application no earlier than 6 months after the release with the deprecation warning. I believe that the deprecation warning will go out in 6.1 which should be released at the conclusion of the current support sprint. Therefore, we should be working to remove `edrget` sometime in mid- to late-May of 2022.

- [x] remove edrget application
- [x] remove edrget tests
- [x] remove edrget documentation

**Comment by jessemapel** [comment]
We're holding this open until we tick the major version for another reason.
