### ISSUE TITLE
Add ingest for KaguyaTC SP Support Data

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#4668]
**Description**  
The kaguyatc2isis application is performing checks to determine the release of different TC data sets. Right now, the SP Support data are not supported because 'SLN-L-TC-3-SP-SUPPORT-LEVEL2B0-V1.0' is not included in the list of supported data types. Simply modifying the KaguyaTC label to alter that string to be a supported data type allows ingest. 

I believe that the above string simply needs to be added to [the list of ids](https://github.com/USGS-Astrogeology/ISIS3/blob/aab0e63088046690e6c031881825596c1c2cc380/isis/src/kaguya/apps/kaguyatc2isis/kaguyatc2isis.cpp#L47) that can be processed by kaguyatc2isis.

It also does not look like we are testing all of the different ingest flavors in [our tests](https://github.com/USGS-Astrogeology/ISIS3/blob/aab0e63088046690e6c031881825596c1c2cc380/isis/tests/FunctionalTestsKaguyatc2isis.cpp). This change should probably also include a test update for the SP Support data.

Here is an example label (the img is at the same URL, just saw lbl for img): https://data.darts.isas.jaxa.jp/pub/pds3/sln-l-tc-3-sp-support-level2b0-v1.0/20071207/data/TC1S2B0_01_00721S200E1414.lbl

**Comment by ladoramkershner** [comment]
@jlaura can this issue be closed with the merging of #4688 ?

**Comment by jlaura** [comment]
Yup! Closed by #4688 and available in ISIS7.0
