### ISSUE TITLE
RHEL 8.4 libjasper.so.1 not found

### ISSUE THREAD

**Issue by AlanHoward** [DOI-USGS/ISIS3#4675]
Apparently just successfully installed most recent isis in RHEL 8.4 following installation instructions.  But when invoking any command there is failure with libjasper.so.1 not found.  Trying to install jasper in RHEL 8.4 reports that jasper-libs-2.0.14-4.el8.x86_64 is already installed.  Any solution to this?

**Comment by acpaquette** [comment]
@AlanHoward This is likely due to previous issues with ISIS installing into "unclean" anaconda environments thanks to anaconda/conda caching packages. Could you post the exact output from your terminal?

**Comment by AlanHoward** [comment]
Well, I have abandoned trying the RHEL 8.4 environment and will be using either a MacOS version or a minimal Ubuntu in a VirtualBox in the RHEL computer, both of which installed and opened Qview flawlessly.  The culprit on RHEL may be my Intel OneAPI installation that also has Python. Libraries on Linux are a hellhole. Thanks for responding.

**Comment by jessemapel** [comment]
RHEL isn't officially supported so I'm going to close this as will not fix. If someone wants to work on this and put in a PR that is very much welcome.
