### ISSUE TITLE
ISIS image procesing- generic name issue

### ISSUE THREAD

**Issue by sathya-lab** [DOI-USGS/ISIS3#4701]
The fit and FITS Image is not being read by isis, not able to locate the image in pc even after providing the information of the loaction.

**Comment by jessemapel** [comment]
Can you provide more details about what's happening. Please fill out the bug report template with what version of ISIS you are using, what command you are running, and if possible the contents of any error or print.prt logs.

**Comment by AustinSanders** [comment]
Until more information is made available, this does not appear to be a workable issue.  I'm closing this issue for now, but feel free to reopen with additional context.
