### ISSUE TITLE
Update LidarControlPoint and Control classes for LiDAR

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4703]
**Description**  

Update the [LidarControlPoint](https://github.com/USGS-Astrogeology/ISIS3/tree/LroLidar_Infrastructure/isis/src/control/objs/LidarControlPoint) class to get it compiling under current dev.

This will require porting the changes to the ControlPoint and ControlMeasure classes too. See #75, #236, #408 #3172 #3250 #3252 #3253

**Example**

**Comment by jessemapel** [comment]
There's some strange logic to check for "Lidar" in the point ID when working with Lidar points. Maybe this can be changed such as here:

https://github.com/USGS-Astrogeology/ISIS3/blob/LroLidar_Infrastructure/isis/src/control/objs/ControlPoint/ControlPoint.cpp#L935

Instead we can just flag lidar points as constrained.

For right now, I'm just taking this as is but I want to make a note for potential changes.

**Comment by ladoramkershner** [comment]
@jessemapel I think I agree with you that Lidar should maybe just be a constrained point. Especially since pointid is an optional input in lrolola2isis, so if the user provides anything but pointid=Lidar??? (which is not the default) then this logic breaks.

**Comment by ladoramkershner** [comment]
I think that is the only comment I have, it is a small comment with possibly large implications, so I don't mean to minimize it.
