### ISSUE TITLE
Figure out why jigsaw test is giving different output on the same OS

### ISSUE THREAD

**Issue by kaitlyndlee** [DOI-USGS/ISIS3#471]
The jigsaw test pole-ra-dec-w0-wDot-triaxial-radii is giving different output on different machines that are running MacOS 10.13. Prog27 and algol are giving the same output, while my machine is different.
Currently, a README.md file exists in the input saying that we know of this problem, however, it would be nice to know why this is happening. See the files below to see output.

Other output: 
[pole-ra-dec-w0-wDot-triaxial-radii_bundleout.txt](https://github.com/USGS-Astrogeology/ISIS3/files/2452611/pole-ra-dec-w0-wDot-triaxial-radii_bundleout.txt)

Prog27: 
[prog27Output.txt](https://github.com/USGS-Astrogeology/ISIS3/files/2452606/prog27Output.txt)

**Comment by jessemapel** [comment]
This has been resolved, it was due to rounding numbers close to 0 with sed producing 0.0000 and -0.00000
