### ISSUE TITLE
Change ISIS DOI and mechanism for pulling a DOI

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#4715]
**Description**
As an official USGS software release, ISIS is required to have a DOI with a 10.5066 prefix. Right now, Zenodo is being used to mint a DOI which is not in compliance with USGS federal software release requirements.

**Suggested Change**
We have to update the DOI on the project because the project is, to this point, being solely released by USGS employees. Looking at the DOI FAQ, it does not appear to be explicitly prohibited to mint two DOIs for the same piece of work, but (a) I could be missing that prohibition and (b) it does not really make much sense to me to have two DOIs pointing to the same piece of code.

Here is a [link to the policy](https://www.usgs.gov/survey-manual/im-osqi-2019-01-review-and-approval-scientific-software-release). Please see subsection F or ctrl-f and search for DOI.

**Comment by rbeyer** [comment]
I think I come to the same conclusion.  There is a little wiggle room on the [USGS Data Management page](https://www.usgs.gov/products/data-and-tools/data-management/digital-object-identifiers?qt-science_support_page_related_con=0#qt-science_support_page_related_con) about data (software) published elsewhere:

> USGS data that are published on Federal servers managed by other agencies may be assigned a DOI managed by the 
> hosting agency, if required as a condition for publishing the data; 

But this is still pretty restrictive and proscriptive overall.

Is the USGS capable of minting DOIs at the rate that you need them for ISIS?  You should explore the process, if it is ... involved ... maybe they don't want you making a request every three months and might give you an exception.

**Comment by jlaura** [comment]
@rbeyer Right now we are working under a 'we will let it slide' exception for now. I do not know how that exception is going to fly and so we need to get into compliance.

The process of minting a DOI is neither onerous nor automated. I will follow up with the software team for USGS (where these policies are coming from) to see how they envision a setup where non-USGS personnel might be the ones doing a release. Zenodo, being automated, covers this use case quite nicely. 

The policies and regulations surrounding the release of software by federal entities is fortunately well documented. Unfortunately, it does not seem to leave very much room for environments where the contribution team has broad affiliations.

**Comment by rbeyer** [comment]
> The policies and regulations surrounding the release of software by federal entities is fortunately well documented. Unfortunately, it does not seem to leave very much room for environments where the contribution team has broad affiliations.

Agreed.  That's why I think the future is making software projects like ISIS and ASP and whatever else truly community projects, so that they are not "software released by federal entities" but software that is contributed to by federal workers.  So each contribution is constrained by who the worker is, but the process of release and governance is not a "federal" process, because "the software" is not owned/controlled by a U.S. Government entity.  I'm still not sure exactly how to do that, but those are the kinds of things on my mind when this sort of thing comes up.

**Comment by rfergason** [comment]
Do we need to mint a DOI for every single ISIS release?  To be compliant with the USGS software release guidelines (understanding that there is discussion above about whether that is the appropriate release process), we must mind a DOI for every major version release (i.e., 3.0.0, 4.0.0, etc.), which to me is a pretty minimal manual load given how often we release a major version.  Do we need to mint a DOI for minor releases?  If we can determine our true need on the frequency of DOIs, then the conversation can be constrained, I think.

**Comment by jlaura** [comment]
I have some wonderful additional guidance from the USGS software release team. As the lead organization for the ISIS project we (USGS) need to ensure that we are following the USGS fundamental science practices, including minting a DOI with the appropriate prefix. The process of performing a release needs to include at least one USGS employee who has access to the systems necessary to meet our Fundamental Science Practices (FSP). Meeting the FSPs ensures that we are in compliance with federal requirements.

If, at some point, this project is lead under the auspices of some other organization, we, as a group, would need to be in compliance with whatever those regulations are (and the individual contributors would need to ensure compliance with their own organizational requirements).

What does this mean? To comply with the USGS implementation of the federal software release policy, I need to have our next release tagged with an approved DOI. I have taken care of all other USGS release requirements during a previous release. Those requirements are largely opaque to the external contributor base in that they do not need to file the necessary paperwork. That is not to say that the contributor community is not participating in the official release. Code reviews, for example, are how we ensure that our software is provisionally released and compliant as we check for security issues, code quality, and efficacy during every review. In other words, all submissions to this repository will be considered provisional software releases (which are approved because we have appropriate controls in place to ensure the quality of the code base). The incremental reviews make the official USGS review quite straightforward. 

What is the impact to users? The impact that users should expect to see is a change in the DOI and the deprecation of being able to use Zenodo to mint a DOI assuming we want to go to a single DOI per some version.

We need to discuss @rfergason's post a bit more and determine the cadence for minting DOIs. 

Options as I see them:
 - Major version, mint a new DOI. All minor versions and bug fixes are defined under the major version DOI.
 - Major and minor version, mint a new DOI. All bug fixes are defined under the associated minor version DOI.
 - Any version change, mint a new DOI. I do not know how tractable this is until I hear whether an automated method to mint a USGS approved DOI exists.

I am very happy to hear thoughts, concerns, etc. as we all navigate the federal code release requirements for this project. Hopefully the lessons we are learning are valuable for other federally funded and/or led projects.

**Comment by rbeyer** [comment]
If we expect users to "do science" and cite ISIS with a minor rev version that isn't a x.0.0 version, then minor revs (and patch revs) need DOIs.  That is what the philosophy that Zenodo supports allows for, and I think we need it.

I suppose having one "DOI authority" for majors, and another for minors and patches would be ... fine, but could be really messy and hard for users to follow or require lots of documentation on our end to make things clear.  There are no great answers here given the new constraint (majors must have USGS DOIs).

**Comment by jlaura** [comment]
I think that we can close this out by updating the release docs to indicate that, when peeling a release that ticks the major or minor version, the USGS software release process must be undertaken including the generation of a DOI. The docs will enumerate the steps required to get that completed. It must be completed by an ASC developer. Then we can remove all Zenodo hooks from the repository so that new DOIs are not minted on releases.

Without any objections, we will pull the release at the end of this month using the above approach.

**Comment by jessemapel** [comment]
It sounds like we need to pull the zenodo hooks now then?

**Comment by jlaura** [comment]
We need to pull them before the tag and pull the next release so that we do not generate a Zenodo DOI. Instead, we will generate a USGS approved DOI.

**Comment by rbeyer** [comment]
We currently use the .zenodo.json file as the authoritative "author list" that gets pulled into the DOI creation process, and from which our AUTHORS.rst file is created.  What is the DOI DOI (awkward acronym collision) process going to be?

**Comment by jlaura** [comment]
We can switch to an Authors.md or similar file since we no longer have a reason to parse a zenodo formatted file. The DOI generation process is publicly described [here](https://www.usgs.gov/software-management/additional-guidance-review-and-approval-scientific-software). The tool to create the DOI is not publicly available.

**Comment by jessemapel** [comment]
We now generate DOIs through the USGS software release process. All that needs to happen is we need to change the DOI link on the README

**Comment by rbeyer** [comment]
There is also a "generated by" phrase at the bottom of AUTHORS.rst that probably needs to be removed.
