### ISSUE TITLE
cam2map error with Mini RF monostatic cubes and user defined shapemodel

### ISSUE THREAD

**Issue by campharris** [DOI-USGS/ISIS3#4717]
**ISIS version(s) affected**:
3.10.0

**Description**  
I am trying to map project Mini RF monostatic cubes with a user defined shapemodel instead of the default LOLA DEM (in this case the SLDEM2015).  Spiceinit seems to work fine but when I go to map project cam2map throws the error:

*PROGRAMMER ERROR* angle cannot be non null special pixel

I've tried this with several randomly selected Mini RF cubes (monostatic) with the same result.

**How to reproduce**  
mrf2isis from=<level_1>.lbl to= <level_1>.cub
spiceinit from=<level_1>.cub shape=user model=<SLDEM2015_pad>.cub
cam2map from=<level_1>.cub to=<level_2>.cub map=<map_template>.map

**Additional context**  
The process works fine using the base LOLA DEM, but this project specifically calls for testing alternative shapemodels so simply reverting back to using the base DEM is the least preferable option.

**Comment by jessemapel** [comment]
What DEM are you using with? We've seen some strange errors with polar DEMs being discontinuous around the pole causing weird behavior in the DEM intersection algorithm, #4420.

**Comment by campharris** [comment]
It's the SLDEM2015_256_60S_60N_000_360_FLOAT.IMG (available through: http://imbrium.mit.edu/DATA/SLDEM2015/GLOBAL/FLOAT_IMG/), and the cubes I've been testing are all roughly equatorial so well within the coverage of the DEM.

**Comment by jessemapel** [comment]
Can you provide the product ID or a link to the archive for one of the images that this is happening with, or is it happening with every image?

**Comment by lwellerastro** [comment]
@thareUSGS is the expert and can fill in gaps, but maybe try running the isis program demprep on <SLDEM2015_pad>.cub (what does _pad mean?).

In order to use a radius shape file via spiceinit, the cube needs to have ShapeModelStatistics on the label and demprep will do that.  This might not be problem, or only part of getting an external DEM into isis properly, but it's a pretty easy thing to try.

**Comment by campharris** [comment]
Sorry about the generic labels.  I have already run demprep on the aforementioned SLDEM2015_256_60S_60N_000_360_FLOAT.IMG after converting it into a cube.

The product ID for one of the images I'm working with is is lsz_03305_1cd_xku_17n015_v1.img (also the accompanying label file) which can be found on the PDS: https://pds-geosciences.wustl.edu/lro/lro-l-mrflro-4-cdr-v1/lromrf_0002/data/sar/03300_03399/level1/

I've tried with perhaps a dozen other cubes from the monostatic campaign chosen at random and this error seems to crop up across the board.

**Comment by thareUSGS** [comment]
@campharris Without testing this first, I would **_guess_** there are some PDS3 label oddities which don't play well during import. If you look at the original PDS3 label (SLDEM2015_256_60S_60N_000_360_FLOAT.LBL), it has 

```
   MAXIMUM               = 10.781
   MINIMUM               = -8.717
   UNIT                  = KILOMETER
   SCALING_FACTOR        = 1
   OFFSET                = 1737.4
```

That is fine, but I'm not sure ISIS is importing it correctly (such that it can be used for a shapemodel). I would try this update and it might help. First update that label to:

```
   UNIT                  = METER
   SCALING_FACTOR        = 1000.0
   OFFSET                = 1737400.0
```

Now re-import into ISIS and once again run demprep. With the elevations in floating point meters for the radius, it might make ISIS happy. I will test myself, but these files take a while to download and test. If this helps, I will post back here.

**Comment by thareUSGS** [comment]
Yes that appears to be the issue. When reporting the statistics during demprep, ISIS thinks the values are in meters. So the tweak to the PDS3 label above should fix it for ISIS. I tested on the 256ppd SLDEM version (with the label tweak applied) and you should get values like:

```
ast{209}> demprep from=sldem2015_256ppd.cub to=sldem2015_256ppd_pad.cub
Group = Results
  MinimumRadius = 1728682.5 <meters>
  MaximumRadius = 1748181.25 <meters>
End_Group
```

**Comment by jlaura** [comment]
@thareUSGS Is this a data issue that ISIS should be handling or an oddity where the label is out of compliance with some specification?

**Comment by thareUSGS** [comment]
@jlaura Until Goddard started to distribute their lunar elevation products in 32bit floating point (from scaled 16bit), it was rare to see kilometers used. It is a valid label, although the use of "UNIT = anything" can be rare to find in other labels (although commonly present in Goddard topographic-based labels). 

It would be great to support recognizing the UNIT keyword in ISIS. Currently, I'm not even sure if is there a place to store it in the ISIS cube? We support wavelengths but I forget if we have a place for units?

Perhaps as a check in demprep, instead of assuming meters, the pixel DN range could be compared to the defined radius. If it is not close, a warning could be issued stating to make sure the DNs are meters.

**Comment by scsides** [comment]
Reasonably sure ISIS requires all DEMs to be in meters. The offset and scale are fully supported on all bit types other that 32 bit float. There are no supported pixel units.

First guess for a good place to have ISIS support this:
  1) pds2isis - have it save the PDS units in either the Cube Dimensions, or a Band Bin
  2) demprep - have it adjust the the scale and offset so the pixels are meters

**Comment by jessemapel** [comment]
I second Stuart's options and would lean towards demprep being the place to handle this. It is already a part of the ISIS DEM ingestion workflow and makes sense as a good place to add this functionality.
