### ISSUE TITLE
combine the "building isis3 with cmake" and "testing with cmake" into one wiki page

### ISSUE THREAD

**Issue by ihumphrey** [DOI-USGS/ISIS3#472]

**Comment by ihumphrey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Combine "build" and "test" wiki pages on isis3 github](https://trello.com/c/7Q7mnXo1/149-combine-build-and-test-wiki-pages-on-isis3-github)

**Comment by kaitlyndlee** [comment]
The old "Building with cmake" page has been changed to "Developing ISIS3 with cmake" and includes both the building and testing information.
