### ISSUE TITLE
jigsaw command line wrong in gui mode

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#4725]
**ISIS version(s) affected**: 6.0.0 and up

**Description**  
When running jigsaw in GUI mode, after any parameter is modified the command line text at the bottom of the GUI shows "csmsolveset=" even if csmsolveset was not modified.

Additionally, if the command line is then cut and pasted into a script, it will cause an error.

**How to reproduce**  
run jigsaw in gui mode
set the input cube list parameter to any string
see the current command line at the bottom of the GUI

**Possible Solution**  

**Additional context**

**Comment by kledmundson** [comment]
Think this should be reopened, I'm still seeing the exact same thing happen in the latest version of dev (caused me just a bit of grief). 

line 1460    group name="Community Sensor Model Options"
line 1461      parameter name="CSMSOLVESET"
**line 1462        internalDefault>none</internalDefault**

I think the solution is to remove line 1462 (though I'm not sure of any ramifcations).
