### ISSUE TITLE
Should we move the ISIS3 recipe into this repository? 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#473]
It seems it would make a bit more sense to leave isisdeps to dependencies and move the recipe to build ISIS3 into this repo under a `conda` folder.

**Comment by jessemapel** [comment]
I agree, the build recipe for ISIS should be in the ISIS repo.

**Comment by jlaura** [comment]
@Kelvinrr @jessemapel Is this done? If not, can we get a PR in? Seems this should be a super quick addition.

**Comment by jlaura** [comment]
One other thought that is maybe a little more radical. Does it make sense *not* to do this, but to open a PR into conda-forge and get ISIS releasing there. Then we can use a recipe in here only for CI/CD releases?

**Comment by jessemapel** [comment]
I'd rather we maintain the recipe in the repository for a few more releases before we push it to conda-forge.

**Comment by Kelvinrr** [comment]
Technically doing what you are suggesting also involves completing this ticket (petty detail, I know). I would argue it makes sense to have ISIS on Conda-Forge eventually, but if I recall we still depend on other recipes on our own channel, as long as that is true, I imagine a Conda-Forge recipe wouldn't make much sense, or at least make a messy situation messier.
