### ISSUE TITLE
GUI history arrows do not work in ISIS 6.0.0 under Big Sur

### ISSUE THREAD

**Issue by captainrlkirk** [DOI-USGS/ISIS3#4740]
**ISIS version(s) affected**: 6.0.0

**Description**  
I recently migrated to MacOS Big Sur and did a clean install of the (then) current ISIS 6.0.0.  I now find that the up arrow button in the GUI for various apps does not restore parameter values from previous runs of the same app.  This was working under MacOS Mojave and much older (3.x) ISIS.

**How to reproduce**  
Presumably depends on details of my MacOS and ISIS installations, but then it's easy: run any app, exit, start GUI for that app again. Click up arrow icon.  Nothing happens.

**Possible Solution**  
I wonder if the location where history is stored was not created, is not defined as a logical name, or I don't have authorization to read/write from it.
I exchanged emails with Jay Laura who suggested instead that the history arrow icon function in GUI is built on the shell command history that is accessed with keyboard arrows.  This is working as I remember it always working (up arrow steps through all previous commands in order).  Jay suggests that the up arrow should fill out a partial ISIS command to the last executed command that starts with the same text.  This does not work now but I was unaware of this functionality so can't say if it worked under Mojave.

**Additional context**  
This may be crucial.  To use GDAL and ISIS simultaneously I am activating a Conda environment for GDAL and then rather than trying to layer the ISIS environment on this, I am defining $ISISROOT and $ISISDATA in .tcshrc  (I have the default login shell for terminal set to tcsh, which is what I have used in the past when the history function worked under Mojave.)

**Comment by KrisBecker** [comment]
Hi @captainrlkirk...

I can reproduce the same behavior on my Mac. Turns out the ISIS history directory may not exist. Take a look in `~/.Isis` for a `history` directory. If its not there, create it using `mkdir ~/.Isis/history` and try it again.

**Comment by captainrlkirk** [comment]
@KrisBecker  Creating the history directory fixed the problem.  Thanks!
