### ISSUE TITLE
Logical Cube Format Docs use wrong PVL end format

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4745]
**Description**

The [logical cube format guide](https://isis.astrogeology.usgs.gov/documents/LogicalCubeFormatGuide/LogicalCubeFormatGuide.html) uses the incorrect end keywords for the end of groups and objects in its Cube label PVL examples. Instead of using `EndGroup` and `EndObject` it should use `End_Group` and `End_Object`. For example:

```
  Object = IsisCube
    Object = Core
      StartByte   = 65537
      Format      = Tile
      TileSamples = 128
      TileLines   = 128

      Group = Dimensions
        Samples = 2468
        Lines   = 11499
        Bands   = 1
      EndGroup

      Group = Pixels
        Type       = Real
        ByteOrder  = Lsb
        Base       = 0.0
        Multiplier = 1.0
      EndGroup
    EndObject
  EndObject
End
```

should instead be

```
  Object = IsisCube
    Object = Core
      StartByte   = 65537
      Format      = Tile
      TileSamples = 128
      TileLines   = 128

      Group = Dimensions
        Samples = 2468
        Lines   = 11499
        Bands   = 1
      End_Group

      Group = Pixels
        Type       = Real
        ByteOrder  = Lsb
        Base       = 0.0
        Multiplier = 1.0
      End_Group
    End_Object
  End_Object
End
```

See the [cube format template](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/appdata/templates/labels/CubeFormatTemplate.pft) for the proper end keywords in a cube label.

This was first reported on [astrodiscuss](https://astrodiscuss.usgs.gov/t/gdal-conversion-tips/101/7?u=jessemapel)

**Comment by rbeyer** [comment]
Maybe this should be a separate issue, but in order to follow the PVL / ODL / PDS3 spec, the GROUP, END_GROUP, OBJECT, and END_OBJECT keywords should also be in ALL CAPS.  However, this would require that the parts of ISIS that output PVL-text be fixed to do that, and that all of the parts that consume PVL-text recognize that, which will likely have a large impact on the codebase.

**Comment by jessemapel** [comment]
I agree that ISIS doesn't follow any actual PVL format and it would be good to change that. This is more about internal consistency as the docs don't currently match what the actual software produces right now.
