### ISSUE TITLE
junocam2isis multi-band full CCD cube 

### ISSUE THREAD

**Issue by BrianSwift** [DOI-USGS/ISIS3#4748]
**Description**  
Modify `junocam2isis` to enable creation of multi-band full CCD cubes.
This would be similar to the current FULLCCD=YES functionality, but the data from each filter would be in a separate cube band. The current implementation places the data from all filters into one cube band.

Could implement as a 3rd value for the FULLCCD parameter (eg, NO, YES, COLOR) or as additional parameter (eg COLORFULLCCD=YES/NO that is only allowed when FULLCCD=YES and defaults to NO). Either of these would maintain backward compatibility with any existing scripts.

This request motivated by discussion at https://astrodiscuss.usgs.gov/t/should-junocam2isis-fullccd-yes-produced-single-band-cubes/797

**Example**  
junocam2isis FULLCCD=COLOR fr=JNCE_2021158_34C00001_V01.LBL to=PJ34_01.cub

**Comment by jessemapel** [comment]
I don't think we can add an extra option to FULLCCD as it's currently a boolean parameter which can use yes/no or true/false for its values. So, it would have to be an additional exclusive option like COLORCCD or something.
