### ISSUE TITLE
Qmos - Latitude Constructor Error

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#4754]
**ISIS version(s) affected**:5.0.2

**Description**  
The following error is encountered when loading a map file asking for Planetographic LatitudeType and grid modifications the first time grid options is chosen (it is super specific and described below).
![qmosError](https://user-images.githubusercontent.com/34550733/150215425-2ea0f999-977b-4e62-b44e-84e86de0b150.png)

**How to reproduce**  
Data and map files files available under my work area /Isis3Tests/Qmos/GridMapCombo

- launch qmos
- open cubelist cubs.lis
- quick load map (lightening bolt icon) - choose moon_spole_ographic.map
- click grid icon (if not there right click on window somewhere and start turning on tools)
- select grid options - error appears, ok but will come back with every grid option select

Make the problem go away
- quick load map moon_spole_ocentric.map
- select grid options - works
- quick load map moon_spole_ographic.map
- select grid options - works this time

**Possible Solution**  
Current work around is to use to ocentric latitude type.  In fact, once an ocentric map file is loaded (before or after the ographic error message), loading an ographic based map file works without error when trying to adjust the grid.

**Comment by jessemapel** [comment]
I think this is solvable by passing the mapping group from the projection to Latitude constructors in MosaicGridTool::onProjectionChaned.

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/qisis/objs/MosaicSceneWidget/MosaicGridTool.cpp#L810

Similar to how they are handled in MosaicGridTool::setLatExtents

Related to #3714

**Comment by jessemapel** [comment]
@AustinSanders This is a good small ticket for the support sprint. Biggest overhead will be doing the GUI testing.

**Comment by blandoplanet** [comment]
This still needs addressed.
