### ISSUE TITLE
Modify tgocassisrdrgen to include browse keyword information

### ISSUE THREAD

**Issue by AustinSanders** [DOI-USGS/ISIS3#4760]
**Description**  
A new 'browse' keyword has been added to the CaSSIS label archive group, which captures the list of derived browse products for the image.  tgocassisrdrgen should be updated in order to export these references to the respective xml labels.

**Example**  
The browse keyword is captured as a list in the following format:
 Browse                       =
(MY36_016957_031_0_RPBwPAN_browse,
MY36_016957_031_0_NPB_browse,
MY36_016957_031_0_NPBwPAN_browse,
MY36_016957_031_0_NRB_browse,
MY36_016957_031_0_RPB_browse,
MY36_016957_031_0_RGBwPAN_browse,
MY36_016957_031_0_BLU_browse,
MY36_016957_031_0_NPBwPAN_annotated_browse
MY36_016957_031_0_NRBwRED_browse,
MY36_016957_031_0_RGB_browse)

**Comment by acpaquette** [comment]
@AustinSanders Is there an example RDR that can be used to test this?

**Comment by AustinSanders** [comment]
@acpaquette https://pirlwww.lpl.arizona.edu/~rod/sample_cubes_b/ contains some sample data
