### ISSUE TITLE
Compile warning on Big Sur

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#4765]
**ISIS version(s) affected**: 7.0.0

**Description**  
Some compile warnings are present in the DEV branch (and others) for builds on Big Sur

isis/src/base/objs/Ransac/unitTest.cpp:11:
/Users/ssides/repos/ISIS3/isis/src/base/objs/Ransac/Ransac.h:140:18: warning: overlapping comparisons always evaluate to false [-Wtautological-overlap-compare]
    if (flag < 1 && flag > 3)

A few more related to the one above:

isis/src/base/objs/OriginalXmlLabel/OriginalXmlLabel.cpp:65:50: warning: variable 'errorLine' is uninitialized when passed as a const reference argument here [-Wuninitialized-const-reference]
                    "Error at line [" + toString(errorLine) +

A few more like the one above:

isis.dir/qisis/objs/TrackTool/TrackTool.cpp.o
/Users/ssides/repos/ISIS3/isis/src/qisis/objs/TrackTool/TrackTool.cpp:289:3: warning: non-void function does not return a value in all control paths [-Wreturn-type]
  }

**How to reproduce**  
Compile ISIS from scratch and look for warnings

**Possible Solution**  
Fix the errors

**Additional context**

**Comment by jessemapel** [comment]
I also see these issues on Ubuntu18.

we should enable warnings as errors and get all the warnings squashed out when resolving this.

**Comment by scsides** [comment]
I agree, although some may not.
