### ISSUE TITLE
JunoCam SPICE-Image Mismatch in Qview

### ISSUE THREAD

**Issue by shawn-brueshaber** [DOI-USGS/ISIS3#4768]
ISISv3 running on MacOS Big Sur, Ubuntu 20.04, and Red Hat OS.

**Description**  
When attaching SPICE data to JunoCam images via Junocam2isis followed by spiceinit, we have noticed that the backplane data (e.g., lat., long.) as viewed in qview vanish 7-8 pixels away from the image limb boundary.  We don't know if this is an issue within qview or something to do with the SPICE attachment to the image pixels.  As an example, image JNCE_2021052_32C00023_V01, green filter, framelet number 25 shows this problem.  

**How to reproduce**  
Run junocam2isis then spiceinit on JNCE(R)_2021052_32C00023_V01.  Open the green filter, framelet number 25.  Open this cube in qview and move the cursor from the center of the image down towards the limb.  Monitor the backplane data in qview.  The lat/long data vanishes 7-8 pixels from the edge.  MSSS conducted a limb-fitting correction to this image so we expect that any such mismatch would be 1-2 pixels at most.  

**Additional context**  
![image001](https://user-images.githubusercontent.com/80118828/152207785-30fd05ea-611f-41c7-9592-7ee7bd172c1a.png)
![image002](https://user-images.githubusercontent.com/80118828/152207806-27d97dde-4711-477c-97e8-f03238e72b65.png)

NOTE:  If the attached images do not show up on this page, contact me and I will email them.

**Comment by jessemapel** [comment]
Thanks for the bug report, I've got a handful of questions to hopefully dig down on this.

Can you run phocube to generate lat lon back planes on the image to see if this is a qview bug or a camera issue?

Can you also post the label of the spiceinit'd cube so that we can see which SPICE kernels it's pulling in?

Do you see the same or different offsets between filters?

There are 2 likely sources for this error. First, would be the SPICE data just being slightly off in either the body definition or the sensor ephemerides. Second, would be the hard-coded filter offsets in the JunoCam model. We had a bunch of questions during development about what the exact offsets are and ended up just going with what seemed best in our test cases.

**Comment by shawn-brueshaber** [comment]
I ran phocube on JNCR_2021052_32C00023_V01 framelet 25 green filter, on framelet 27 blue filter, and framelet 24 red filter as the lat/long coordinates overlap somewhat between these framelets.  The offset is about the same in all three filters. Interestingly, after running phocube on the green filter, the vanishing back planes improved so that the vanishing info is only 1-2 pixels from the edge in qview.  However, the problem persists in the blue and red filtered framelet.  I'm attaching the output of catlab for these framelets.

[JNCR_2021052_32C00023_V01_Green_0025_Catlab.docx](https://github.com/USGS-Astrogeology/ISIS3/files/7995629/JNCR_2021052_32C00023_V01_Green_0025_Catlab.docx)
[JNCR_2021052_32C00023_V01_Blue_0027_catlab.docx](https://github.com/USGS-Astrogeology/ISIS3/files/7995631/JNCR_2021052_32C00023_V01_Blue_0027_catlab.docx)
[JNCR_2021052_32C00023_V01_Red_0024_catlab.docx](https://github.com/USGS-Astrogeology/ISIS3/files/7995800/JNCR_2021052_32C00023_V01_Red_0024_catlab.docx)
.

**Comment by jessemapel** [comment]
@shawn-brueshaber Can you outline how the limb correction was done and how it was applied to the images? It's not unusual for the a-priori image geometry to be off by this much.

**Comment by shawn-brueshaber** [comment]
Hi Jesse,

The details are a bit muddy.  From what I have gathered from MSSS, is they use an in-house software written by Mike Caplinger (?).  I think they visually adjust the limb in one of the framelets to the expected location based on SPICE kernels.   Of coruse, a limb needs to be visible to do so, and in this particular case, it is.  That being said, my contact at MSSS (Danny; dkrysak@msss.com) *might* be able to get more technical details but he is not entirely clear on the limb-fitting algorthim either.

**Comment by jessemapel** [comment]
If you can just confirm that the correction was done to this image and that it is included in the kernels used by spiceinit. This error looks like normal a-priori pointing error to me.

**Comment by shawn-brueshaber** [comment]
Yes.  Their correction was conducted on this image.  We (JPL) then processed the image via ISIS, which, of course, pulls in the spice kernels.  Are you asking if they (MSSS) used the same kernels to help do the limb fitting?

**Comment by jessemapel** [comment]
I'm interested in which kernels spiceinit used for the image. Can you post the kernel group from the image label?

**Comment by shawn-brueshaber** [comment]
Group = Kernels
    NaifFrameCode             = -61500
    LeapSecond                = $base/kernels/lsk/naif0012.tls
    TargetAttitudeShape       = $juno/kernels/pck/pck00010.tpc
    TargetPosition            = ($juno/kernels/tspk/jup363.bsp,
                                 $juno/kernels/tspk/de440s.bsp,
                                 $juno/kernels/tspk/juno_struct_v04.bsp)
    InstrumentPointing        = ($juno/kernels/ck/juno_sc_rec_210221_210227_v-
                                 01.bc, $juno/kernels/fk/juno_v12.tf)
    Instrument                = $juno/kernels/ik/juno_junocam_v03.ti
    SpacecraftClock           = $juno/kernels/sclk/jno_sclkscet_00119.tsc
    InstrumentPosition        = $juno/kernels/spk/juno_rec_210127_210321_2103-
                                29.bsp
    InstrumentAddendum        = $juno/kernels/iak/junoAddendum005.ti
    ShapeModel                = Null
    InstrumentPositionQuality = Reconstructed
    InstrumentPointingQuality = Reconstructed
    CameraVersion             = 1
