### ISSUE TITLE
Improvements and bug fixes for findfeatures

### ISSUE THREAD

**Issue by KrisBecker** [DOI-USGS/ISIS3#4771]
**ISIS version(s) affected**: all
findfeatures has FastGeom performance issues as well as a matrix inversion failure that will cause runtime failures

**Description**  

findfeature has several bugs that cause runtime failures.

Issues with findfeatures FastGeom may at times cause an invalid matrix which results in an attempt to invert an empty matrix (#4639). The error is trapped and causes the program to abort. This is typically caused by FastGeom correspondence mapping between MATCH and FROM/FROMLIST images. 

The FastGeom process was being deferred to the ImageSource class which impeded the ability to parameterize and constrain the grid-based algorithm. This would either exit early with insufficient corresponding valid latitude/longitude points between the images or it would run unbounded when correspondence wasn't possible. This resulted in ineffective matrix for warp/perspective transformations or matrices that could not be inverted.

**How to reproduce**  

It is difficult to reproduce as the application would abort without reporting the problem image. An exception is thrown with the message `Can't invert empty matrix.` or run for a very long time and then report `Failed to get geometry mapping for...` the images in ImageSource.

**Possible Solution**  

The matrix inversion error needs to be properly identified and properly handled while processing FROM/FROMLIST images. The FastGeom process needs to be improved.

A PR is forthcoming to address these issues.

**Additional context**

**Comment by KrisBecker** [comment]
[Additional information](https://github.com/USGS-Astrogeology/AstroDiscussions/discussions/4#discussioncomment-2078881) related to this problem exists in the Astrodiscuss forum ([#4](https://github.com/USGS-Astrogeology/AstroDiscussions/discussions/4)) which also includes an analysis report ([findfeatures_analysis_improvements.pdf](https://github.com/USGS-Astrogeology/AstroDiscussions/files/7968021/findfeatures_analysis_improvements.pdf)) on the issues.

**Comment by AustinSanders** [comment]
Still active.  To be resolved by #4772

**Comment by AustinSanders** [comment]
Still active.  To be resolved by #4772
