### ISSUE TITLE
Modify Colors in QNET

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#4777]
**Description**  

It just occurred to me that the colors in QNET of points, crosshairs, selected points, etc. are green or red.  Green/red is the most common form of colorblindness, so a very simple change that would potentially be more inclusive of people who want to use the tool to be able to tell differences between things would be to modify the green to something like a lighter blue, and the red to be a bit of a darker red.  This would be a cosmetic change, only.

Alternatively / and/or, there might be a preferences option across ISIS for the GUI applications for a "colorblindness setting" which would modify the colorscheme to remove red/green and make it more like a red/blue or blue/yellow (I haven't researched what's the most visible, extensively, but I know that there are plenty of guides out there).

**Comment by lwellerastro** [comment]
Not in disagreement here, but if colors are changed in qnet, then they need to be changed in qmos as well since the colors in that app for point (and point type in particular) are identical to qnet settings.

Off the top of my head, colors are as indicated below for qnet and qmos
green - valid Free point
yellow - ignored Free point
fuscia - constrained point
?? - fixed point
red - selected point, qnet only

At one point there was mismatch between qnet and qmos colors, with qmos having blue=valid Free point.
Maybe swapping green for a blue would work?  It could be blue=fixed points though.

**Comment by astrostu** [comment]
As I noted, something to think about, at least, especially as many (several?) of us are trying hard to be better about it when making figures in papers, awareness for this issue is growing.  That's why I was thinking that it might affect all the ISIS GUI applications, though really probably only QNET and QMOS.

There are a gagillion colorscales out there for colorblindness, usually variations on blue/yellow for the most severe.  So one could have bright yellow, cyan, darker blue, brown, and there you have the 4 needed colors.  As I said (I guess now a few times), something to think about that I wouldn't expect would be too hard to modify (as in, it's not a bug, not a coding enhancement, it's changing a few color settings).  That's also why it might be something that could be set in ISIS Preferences, there could be two built-in color schemes that the user could choose between and the GUI application would read that upon startup: I like the more contrast that more colors allow, but I also wouldn't want to have people who are colorblind have issues using ISIS.

**Comment by lwellerastro** [comment]
`That's also why it might be something that could be set in ISIS Preferences, there could be two built-in color schemes that the user could choose between and the GUI application would read that upon startup`

I would prefer something like this as I have been working the current colors for well over a decade and have depended on the fact that yellow means ignored, etc..  Plus we have countless publications that have many figures using those colors.  That being said, I am not color blind but know folks who are and use these applications and have simply lived with the lack of choice.  We need to fix that for sure.

**Comment by astrostu** [comment]
*ping*

Obviously not mission-critical, but I think this is important moving forward with inclusivity.

**Comment by blandoplanet** [comment]
This may be a section 508 compliance issue. Even if it's not, it should be fixed.
