### ISSUE TITLE
Documentation on building ISIS3 don't match reality

### ISSUE THREAD

**Issue by chbrandt** [DOI-USGS/ISIS3#480]
I'm trying to build ISIS3 following the instructions in https://github.com/USGS-Astrogeology/ISIS3/wiki/Developing-ISIS3-with-cmake . At some point you say:
```
Set your ISISROOT to /the/path/to/your/build:
    setisis .
```
But there is no command `setisis` in my current environment.

I *could* assume you are trying to say `$ set ISISROOT .`, and considering the reader is using *csh*, but to this point, I learned that *assuming* may not be a good idea.

So, what should I do with this

**Comment by jessemapel** [comment]
@chbrandt `setisis` is an alias that we use internally. We need to update the docs to the correct docs for everyone. For right now, you should set your ISISROOT to your build directory as you guessed. Then you can run one of the isis3Startup scripts to setup your data area and path.

**Comment by ihumphrey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [update the building isis3 with cmake wiki page to have instructions for outside devs (e.g. setisis is for internal)](https://trello.com/c/6PFavcY6/181-update-the-building-isis3-with-cmake-wiki-page-to-have-instructions-for-outside-devs-eg-setisis-is-for-internal)

**Comment by celbal** [comment]
@chbrandt We've updated the instructions. They should work for an external developer.

**Comment by chbrandt** [comment]
Cool! I'll get back to it during the next days. Thanks.
