### ISSUE TITLE
keywords.lis differences from socetlinescankeywords in ISIS 6.0

### ISSUE THREAD

**Issue by artmathgirl** [DOI-USGS/ISIS3#4800]
**ISIS version(s) affected**: 6.0.0 

**Description**  
We are testing ISIS 6.0.0 and have noticed some differences in the keywords.lis files that socetlinescankeywords generates, compared to those from ISIS 4.3.0. See attached for examples. Almost all the values are different, but we note that most differences are less than 10e-8 in magnitude. Is that small enough to be considered insignificant? 

The attached keywords.lis files demonstrate the output from ISIS 4.3.0 (ESP_071006_2345_RED_DEJITTERED_keywords.lis) and ISIS 6.0.0 (ESP_071006_2345_RED_DEJITTERED_keywords_ISIStest.lis) except I had to change the extension to .txt to upload them here.

**How to reproduce**  
This is the code snippet from the version of hi4socet.pl that calls socetlinescankeywords: 

 $keyFile = $core_name . "mos_hijitreged_keywords.lis";

    $cmd = "socetlinescankeywords from=$mosCube to=$keyFile";
    system($cmd) == 0 || ReportErrAndDie ("socetlinescankeywords failed on command:\n$cmd");

[ESP_071006_2345_RED_DEJITTERED_keywords_ISIStest.txt](https://github.com/USGS-Astrogeology/ISIS3/files/8064424/ESP_071006_2345_RED_DEJITTERED_keywords_ISIStest.txt)
[ESP_071006_2345_RED_DEJITTERED_keywords.txt](https://github.com/USGS-Astrogeology/ISIS3/files/8064425/ESP_071006_2345_RED_DEJITTERED_keywords.txt)

**Comment by AustinSanders** [comment]
@artmathgirl  These differences are very small, and they are small enough that they could potentially be considered insignificant, but it's still somewhat odd that we're seeing them.

They might be insignificant, but it's something that I'd like to look into just to verify that there's nothing weird going on.  Can you supply the .cub files used up to this stage in the pipeline?

**Comment by artmathgirl** [comment]
Here is a link where you can download the .cub file and the .prt file if that helps. https://pirlwww.lpl.arizona.edu/~ssutton/keywords/

**Comment by blandoplanet** [comment]
I'd like to keep this open. I agree with @AustinSanders that it may be an insignificant difference, but it's also possible it's hinting at a larger issue.

**Comment by artmathgirl** [comment]
Thanks for keeping it active. We'll keep an eye out for any updates!
