### ISSUE TITLE
rsync fails to connect to isisdist.astrogeology.usgs.gov

### ISSUE THREAD

**Issue by FrejaThoresen** [DOI-USGS/ISIS3#4804]
**ISIS version**: 4.4.0
**rsync version**: 3.1.3

**How to reproduce**  
> rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/chandrayaan1 .

rsync: failed to connect to isisdist.astrogeology.usgs.gov (184.164.152.106): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

**More info**: The installation with mamba failed, so I have installed ISIS with conda instead.

**Comment by jessemapel** [comment]
Not reproducing right now both on and off the VPN.
