### ISSUE TITLE
Noproj doesn't clean up all files

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#4813]
**ISIS version(s) affected**: 6.0.0 and Up

**Description**  
As initial pointed out by @KrisBecker in #4808 there are various files that the Noproj application doesn't clean up after completion. This is likely due to not every file being accounted for when we go to remove various files that are created.

**How to reproduce**  
The behavior seems to stem from auxiliary tables that are created by the match cube since it is created with an exploded/detached label (Where all tables and the label of the cube are detached from the cube).

**Possible Solution**  
Solution provided by @KrisBecker
"This is an issue we also ran into when running noproj in the same directory. Stuart is right on about using the temporary name generation method in FileName and temporary directory.

The other problem we encountered was that some object files remained after processing. This is because noproj is very HiRISE specific in its cleanup. Here is some new code that shows how this can be generically handled using the match cube label:" - Kris Becker

Section of code that needs to be added to `noproj` along with the function referenced in the code

```
//  Cleanup by deleting the match files
QStringList detfiles = findAllDetachedFiles( label );
detfiles.append(matchLbl);

// Now actually remove the files
foreach (const QString &dfile, detfiles ) {
  std::string  dtf = dfile.toStdString();
  remove ( dtf.c_str() );
}
```

```
// Find all detached filenames specified in objects in the label
QStringList findAllDetachedFiles(const PvlObject &object) {

  // Check this object for a detached file spec
  QStringList detfiles;
  QString dfilename = "^" + object.name();
  if ( object.hasKeyword(dfilename) ) {
    QString detname = object[dfilename];
    detfiles.append(detname);
  }

  // Now check all objects contain in this object
  for (int i_obj = 0; i_obj <  object.objects(); i_obj++) {
    const PvlObject &obj = object.object(i_obj);
    QStringList files = findAllDetachedFiles(obj);
    if ( files.size() > 0 ) {
      detfiles.append(files);
    }
    
  }
  
  return ( detfiles );

}
```

**Comment by acpaquette** [comment]
This is still an issue

**Comment by acpaquette** [comment]
Still active

**Comment by jlaura** [comment]
@acpaquette This issue is being bumped with no other action. When does this issue stop getting bumped and start getting meaningful action?

**Comment by acpaquette** [comment]
When we can get it scheduled as a somewhat high priority issue. I will check if it is on the next support agenda and if not add it to the next one
