### ISSUE TITLE
hrsc2isis does not propagate original label to output for summed images

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#4816]
**ISIS version(s) affected**: 5.0.2

**Description**  
catoriglab fails for HRSC CCD line detector images which contain the keyword MACROPIXEL_SIZE in the IMG file which is translated to the Summing keyword when ingested into ISIS.  These are images having Detector Id's similar to MEX_HRSC_NADIR and MEX_HRSC_RED and so on.

On the other hand, catoriglab run successfully for HRSC SRC images which do not contain the MACROPIXEL_SIZE in the IMG file and no Summing keyword in the isis cube upon ingestion. These are images having DETECTOR_ID = MEX_HRSC_SRC.

**How to reproduce**  
See data (IMG and isis cubes) under /work/users/lweller/Isis3Tests/CatOrigLab/.

catoriglab from=H0756_0000_ND2.lev0.cub to=ND2_lab.pvl
```
  Group = Error
    Program = catoriglab
    Class   = "USER ERROR"
    Code    = 2
    Message = "Could not find OriginalLabel or OriginalXmlLabel in input file
               [H0756_0000_ND2.lev0.cub]"
    File    = main.cpp
    Line    = 81
  End_Group
```
H0756_0000_RE2.lev0.cub in the same directory produces similar results.

The SRC image H0748_0003_SR2.lev0.cub will run successfully:
`catoriglab from=H0748_0003_SR2.lev0.cub to=SR2_lab.pvl`

**Additional context**  
Oddly, caminfo runs without errors or warnings when originallabel=true when passing it one of the HRSC CCD line detector images but there is no original label information in the output file.  I think that is also bug and will report that in another post.

**Comment by Kelvinrr** [comment]
Seems you hit the nail on the head with the DETECTOR_ID distinction. The original label was not attached unless the ID was anything other than `MEX_HRSC_SRC`, PR is up with the change.
