### ISSUE TITLE
Protobuf 3.9.1 error while installing ISIS

### ISSUE THREAD

**Issue by Anirbanm0101** [DOI-USGS/ISIS3#4820]
While installing ISIS, I am encountering a protobuf error. I already have protobuf installed in my system. A screenshot of the error message is pasted below.
![Capture8](https://user-images.githubusercontent.com/99262949/156303821-ba968191-8028-4513-a668-0cc68a4a80ce.JPG)
In the screenshot, one can see that protobuf 3.9.1 is already available in my system but I am still getting this error.

**Comment by jessemapel** [comment]
Make sure that you pass conda-forge as channel in your install command `mamba install -c usgs-astrogeology -c conda-forge isis` We're also seeing a lot of discrepancy between mamba and conda solves which is concerning. So if that doesn't resolve it, also try `conda install -c usgs-astrogeology -c conda-forge isis`

**Comment by Anirbanm0101** [comment]
Thanks a lot. I tried to install it again using mamba while passing the conda-forge as channel but I was still getting the same error. But I was able to install it using conda while passing conda-forge as channel.
So, I am closing this issue as it is resolved.
