### ISSUE TITLE
Error in cam2map while processing MARCI images

### ISSUE THREAD

**Issue by Anirbanm0101** [DOI-USGS/ISIS3#4822]
I am trying to process MARCI image using ISIS. I downloaded a single MARCI image from PDS to check whether ISIS was properly working or not. I wrote a simple c shell script for this processing (available here:https://github.com/Anirbanm0101/marci_isis/blob/main/marci_all.csh). I encountered some errors there. So, I decided to check the functions one by one to find the check the error.

At first, I converted the .img file to an ISIS cub file (screenshot attached below). I encountered a warning but the program was successfully able to split the image into 2 cub files.
![marci2isis](https://user-images.githubusercontent.com/99262949/156578360-0f5b0337-981e-4943-865a-0db4d7b222af.JPG)

Next, I added SPICE data to the odd cub file from the web by running spiceinit (I don't have enough space in my system to download all the kernels. So, I am downloading them from the web).
![spiceinit](https://user-images.githubusercontent.com/99262949/156578897-8e0afe44-da38-4f51-8863-767bf242e892.JPG)

Next, I ran marcical for radiometric calibration of the cub file.
![marcical](https://user-images.githubusercontent.com/99262949/156579276-ca8f8019-d001-49cc-8de4-15293c5a75f6.JPG)

Up to this point, everything was okay. But, when I tried cam2map to generate a map projected cub file, I got error saying that 'spice file doesn't exist'.
![cam2map](https://user-images.githubusercontent.com/99262949/156589441-dfdf1301-0178-4bdc-9d1a-f1c32e5360fc.JPG)

Any suggestion on how to solve this?

**Comment by jessemapel** [comment]
You're going to need to download some of the MARCI spice data to make this work. It's mostly the smaller files and not the big SPKs and CKs so it should be small. It's <1 GB of data total.

So, to get the variable exposure duration table run this

```
cd $ISISDATA
rsync -azv --exclude='kernels' --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/mro .
```

Next we need to grab the kernels we want

```
cd $ISISDATA/mro
mkdir kernels
cd kernels
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/mro/kernels/fk .
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/mro/kernels/iak .
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/mro/kernels/ik .
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/mro/kernels/sclk .
```

That should solve you're problem.

I'm surprised the camera model is trying to load the kernels as it shouldn't need them after spiceinit has been ran. Can you post the label of the spiceinit'd cube?

**Comment by Anirbanm0101** [comment]
I already had the mro specific data before beginning the image processing by running the first command. Still, I was getting the warning. I think the exposure duration per framelet was constant and thus the program didn't find any variable exposure. 

I thought that all of the kernels from SPICE system were needed. So, I mentioned the total size of the data. When I grabbed only the selected kernels, I was able to run cam2map. 

Before downloading the selected kernels I gave a try on a ctx image file with the same workflow. I just replaced the marci specific functions with the ctx specific functions. I got no error and was able to get a level 2 cub file by running cam2map. So, I am also a bit confused why it is asking for spice data for marci. I am attaching the label file I obtained by running catlab for the odd cub file for reference.
[label.txt](https://github.com/USGS-Astrogeology/ISIS3/files/8186149/label.txt)

**Comment by jessemapel** [comment]
MARCI and CTX use very different camera models, so I'm not surprised that the CTX data didn't require any extra spice. Most camera models do not require local SPICE kernels, but there are a handful that require things like local instrument kernels to do certain operations. I'm not very familiar with the MARCI camera model so I can't explain why, but that's just how it was written. We're currently working to abstract out a lot of the SPICE collection that happens in spicenit and we'll likely encounter these scenarios where a camer model requires some type of local SPICE. So, there may be changes in the future to improve the usability of web spice.

For now, I'm going to close this issue as the software is working as expected right now, we can't guarantee that all operations will work with web SPICE, but we do our best to cover as much as we can.
