### ISSUE TITLE
Outdated Environment and Preference Setup

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#4830]
**Description**
isis/src/docsys/documents/EnvironmentAndPreferencesSetup/EnvironmentAndPreferencesSetup.xml is out of date
See:
https://github.com/USGS-Astrogeology/ISIS3/blob/47c3ea41960669e2ce4b4761cb59dea1b0d301c5/isis/src/docsys/documents/EnvironmentAndPreferencesSetup/EnvironmentAndPreferencesSetup.xml

Thanks!

**Comment by ladoramkershner** [comment]
- 'Unix Setup' Section needs to get deleted
- Needs to include a high level explanation of the IsisPreference files
- Needs to include a description of how the tiered preference files work 
- For all other details point to ISIS Preference Dictionary

**Comment by jessemapel** [comment]
Still important
