### ISSUE TITLE
ISIS Preference Dictionary should be updated with CSM information

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#4831]
**Description**
https://github.com/USGS-Astrogeology/ISIS3/blob/47c3ea41960669e2ce4b4761cb59dea1b0d301c5/isis/src/docsys/documents/PreferenceDictionary/PreferenceDictionary.xml is out of date and needs to be updated with what's been added to the preferences file.

Thanks!

**Comment by ladoramkershner** [comment]
Still relevant

**Comment by acpaquette** [comment]
Still relevant

**Comment by Kelvinrr** [comment]
bump

**Comment by amystamile-usgs** [comment]
Preference dictionary docs have been updated and moved here: https://astrogeology.usgs.gov/docs/concepts/isis-fundamentals/preference-dictionary/
