### ISSUE TITLE
Release Schedule is out of date

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#4845]
**Description**

https://github.com/USGS-Astrogeology/ISIS3/wiki/Release-Schedule
Only goes up to 5.2.0 and as of today we are on isis7.0.0_RC additionally, I think we slowed down the release process as requested by the ISIS TC? (Do not quote me on that). 

**Suggested Edit**

Thanks!

**Comment by jessemapel** [comment]
I've updated the release schedule and added a step to the release process to update that page each release.
