### ISSUE TITLE
Learn About Map Projections page is missing interactive demonstrations

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#4854]
**Description**

All demonstrations are missing on https://github.com/USGS-Astrogeology/ISIS3/wiki/Learning_About_Map_Projections 

See: 
https://github.com/USGS-Astrogeology/ISIS3/wiki/Learning_About_Map_Projections#Interactive-Planetary-Radii-Demonstration-
https://github.com/USGS-Astrogeology/ISIS3/wiki/Learning_About_Map_Projections#Interactive-Planetocentric-and-Planetographic-Demonstration-
https://github.com/USGS-Astrogeology/ISIS3/wiki/Learning_About_Map_Projections#Interactive-Longitude-Direction-of-Domain-Demonstration-
https://github.com/USGS-Astrogeology/ISIS3/wiki/Learning_About_Map_Projections#Interactive-Ground-range-demonstration-
https://github.com/USGS-Astrogeology/ISIS3/wiki/Learning_About_Map_Projections#Interactive-Exle-of-pixel-resolutions-
**Suggested Edit**

Thanks!

**Comment by jessemapel** [comment]
These are still broken
