### ISSUE TITLE
Isis Cube Format Repeat Information

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#4857]
**Description**

I get "ISIS Cube Format" page is an introduction to cubes, but the ["Bit Type Basics" section](https://usgs-astrogeology.github.io/ISIS3/ISIS_Cube_Format.html#Bit-Type-Basics) is a duplicate of the information on the "Understanding Bit Types" page ["Bit Type Basics" section](https://github.com/USGS-Astrogeology/ISIS3/wiki/Understanding_Bit_Types#Bit-Type-Basics-). Same thing with the ISIS Cube Format page ["Core Base and Multiplier Basics" section](https://usgs-astrogeology.github.io/ISIS3/ISIS_Cube_Format.html#Core-Base-and-Multiplier-Basics) and the "Core Base and Multiplier" page ["Core Base and Multiplier Basics" section](https://usgs-astrogeology.github.io/ISIS3/Core_Base_and_Multiplier.html#Core-Base-and-Multiplier-Basics). 

**Suggested Edit**

I think the ISIS Cube Format should have a high level explanations with links to the more in depth information on the specific pages.

Thanks!

**Comment by jessemapel** [comment]
Still an issue
