### ISSUE TITLE
Shape Model section in SPICE documentation needs to be completed

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#4858]
**Description**

https://github.com/USGS-Astrogeology/ISIS3/wiki/SPICE#Shape-Model- is empty

**Suggested Edit**

**Comment by jessemapel** [comment]
There are several keywords that simply not used and there needs to be more documentation on how different ray tracing models can be selected and switched between.

**Comment by jessemapel** [comment]
There is some good information here:

https://astrodiscuss.usgs.gov/t/how-to-properly-use-the-bullet-ray-tracing-engine/854/6

**Comment by jessemapel** [comment]
Updated.
