### ISSUE TITLE
Spiceinit error when used on JIRAM cub files

### ISSUE THREAD

**Issue by cgoodma8** [DOI-USGS/ISIS3#4868]
Version affected: 6.0.0

**Description**  

I am looking to add SPICE data to cub files from JIRAM to be able to stitch together a mosaic. When I attempt to do so through spiceinit it returns the error
`**Error** No existing files found with a numerical version matching [kernels.????.db] in [/home/cgoodma8/anaconda3/envs/isis/data/base/kernels/lsk].`

**How to reproduce**  

To create the cub file I used the pds2isis command with both the LBL and corresponding IMG file in the same directory,
`pds2isis FROM=JIR_IMG_EDR_2017033T114541_V02.LBL TO=JIR_IMG_EDR_2017033T114541_V02.cub`

I then run spiceinit,
`spiceinit FROM=JIR_IMG_EDR_2017033T114541_V02.cub`

**Additional context**  

I have downloaded the mission specific data with rsync, manually attempted to download the kernels.????.db files for the corresponding kernels, and made sure that they were all correctly located in their kernel directories in `./home/cgoodma8/anaconda3/envs/isis/data/base/kernels`.

**Comment by jessemapel** [comment]
Hi JIRAM is unfortunately not a supported instrument in ISIS, so you won't be able to do any processing with a camera model. The only Juno instrument we support is JunoCam.

**Comment by cgoodma8** [comment]
That is unfortunate. Thank you for the quick response!
