### ISSUE TITLE
Installation Issue 6.0.0 libgsl

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#4877]
**ISIS version(s) affected**: 6.0.0

**Description**  

When installing ISIS6.0.0 on a CentOS system using mamba, libgsl 2.7.1 was installed. None of the ISIS apps would run then (e.g., `spiceinit -h`) due to linking errors (ldd was showing undefined for libgsl).

**How to reproduce**  

mamba install isis=6.0.0 into a clean environment.

**Possible Solution**  

I downgraded libgsl:  `mamba install libgsl=2.7.0` and everything works as expected.

**Additional context**  

I mainly want to get this documented for folks that might also run into this issue. Perhaps we need to pin libgsl? It is weird that a bug fix version would break the link though. Is this something we did at build time?

**Comment by jessemapel** [comment]
Looks like we need to further restrict our GSL pin to x.y.z in the recipe

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/recipe/meta.yaml#L131

**Comment by jlaura** [comment]
Is the change here?

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/recipe/meta.yaml#L69

with a >=2.6 <=2.7.0? That then propagates through to the `pin_compatible`? I'm not finding great docs on pin_compatible.

**Comment by jessemapel** [comment]
`pin_compatible` basically takes whatever version the build resolves to and then pins a range based on that. Since we are pinning libgsl to `x.x` if the build uses 2.7.0, then it will pin `>=2.7 < 2.8` for the install. I'm not terribly surprised that 2.7.1 and 2.7.0 are not ABI compatible

**Comment by michaelaye** [comment]
I'm maximally confused, I wasn't aware of different linux systems having different dependency solutions?? I'm on Ubuntu and only have `gsl` installed, after a full ISIS6 install with mamba:

```
❯ mamba list gsl
# packages in environment at /home/maye/miniconda3/envs/isis6:
#
# Name                    Version                   Build  Channel
gsl                       2.7                  he838d99_0    conda-forge
```
How is there a `libgsl` in the CentOS build and only a `gsl` package in the Ubuntu build? Is there indeed a precise OS identification happening somewhere?
I checked that `spiceinit -h` works fine here.
Also note my documentation efforts started in #4891 .

**Comment by jessemapel** [comment]
There is no libgsl in Anaconda, it is just called gsl. libgsl is the name of the actual library file, it seems there's some name aliasing happening somewhere.

**Comment by michaelaye** [comment]
Ah make sense. Then, how did I get 2.7 on my linux box? Did you already change something in the dependencies? Could it be because Jay had it in the cache already and I didn’t? I saw somewhere else that Jay has the experience that locally cached packages influence the solver?

**Comment by michaelaye** [comment]
By the way, it’s a fascinating difference of level in thinking: the computer scientist Jay thinks about the libgsl because that’s what he gets installing the package. I know nothing about the contents of packages and just rely on the package names for a consistent setup. Dangerous maybe but that’s all I got. :)

**Comment by jessemapel** [comment]
It is likely the otherway around, you had 2.7.0 cached locally and Jay didn't have anything cached locally. Conda is "lazy" when it does its solve and first looks in its local cache for packages that satisfy the environment before it goes back out to the web. So, if it finds a caches GSL 2.7.0 and that works, it won't look for a new one and see that 2.7.1 is also out.

It is a big pain in the rear for getting consistent solutions with very complex dependencies and not using very hard pins.

**Comment by michaelaye** [comment]
You're right, it was the other isis env that had a 2.7 gsl! But now you are saying that `conda` is lazy as well (or is that a typo and you meant mamba?), because then switching to conda should not change anything for this situation, right?
But, also, WTH why does a patch change to 2.7.1 break everything? SMH :(

**Comment by jessemapel** [comment]
My understanding is that both conda and mamba are lazy when searching for packages and check your local cache before attempting to update it.

The patch release likely broke the ABI but not the API. Most packages do not consider an ABI break sufficient for a major version tick.
