### ISSUE TITLE
Compile warnings on Ubuntu build

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#4911]
**ISIS version(s) affected**: dev 2022/04/16

**Description**  

There are several compiler warnings on the Ubuntu build of dev

**How to reproduce**  

Compile ISIS on the Ubuntu prog machine

**Possible Solution**  

**Additional context**  
[866/3612] Building CXX object objects/CMakeFiles/isis.dir/base/apps/isisimport/isisimport.cpp.o
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/src/base/apps/isisimport/isisimport.cpp: In lambda function:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/src/base/apps/isisimport/isisimport.cpp:136:12: warning: variable ‘foundfilter’ set but not used [-Wunused-but-set-variable]
       bool foundfilter = false;
            ^~~~~~~~~~~
[3498/3612] Building CXX object tests/CMakeFiles/runISISTests.dir/FunctionalTestsCkwriter.cpp.o
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsCkwriter.cpp: In member function ‘virtual void DefaultCube_FunctionalTestCkwriterDefault_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsCkwriter.cpp:68:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < newKernelRotation->TimeBasedMatrix().size(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsCkwriter.cpp:73:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < newKernelRotation->AngularVelocity().size(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsCkwriter.cpp: In member function ‘virtual void DefaultCube_FunctionalTestCkwriterFromlist_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsCkwriter.cpp:137:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < newKernelRotation->TimeBasedMatrix().size(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsCkwriter.cpp:142:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < newKernelRotation->AngularVelocity().size(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[3518/3612] Building CXX object tests/CMakeFiles/runISISTests.dir/FunctionalTestsFootprintinit.cpp.o
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp: In member function ‘virtual void DefaultCube_FunctionalTestFootprintinitDefault_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp:37:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < coordArray.getSize(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp: In member function ‘virtual void DefaultCube_FunctionalTestFootprintinitLincSinc_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp:59:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < coordArray.getSize(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp: In member function ‘virtual void DefaultCube_FunctionalTestFootprintinitVertices_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp:81:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < coordArray.getSize(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp: In member function ‘virtual void DefaultCube_FunctionalTestFootprintinitCamera_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp:103:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < coordArray.getSize(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp: In member function ‘virtual void DefaultCube_FunctionalTestFootprintinitTestXY_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp:125:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < coordArray.getSize(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp: In member function ‘virtual void DefaultCube_FunctionalTestFootprintinitPrecision_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsFootprintinit.cpp:153:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < coordArray.getSize(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~
[3542/3612] Building CXX object tests/CMakeFiles/runISISTests.dir/FunctionalTestsJigsaw.cpp.o
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsJigsaw.cpp: In member function ‘virtual void ApolloNetwork_FunctionalTestJigsawApollo_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsJigsaw.cpp:174:15: warning: ‘outputPoint’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       measure = outputPoint->GetMeasure(csvLine[2]);
               ^
[3569/3612] Building CXX object tests/CMakeFiles/runISISTests.dir/FunctionalTestsSpkwriter.cpp.o
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsSpkwriter.cpp: In member function ‘virtual void DefaultCube_FunctionalTestSpkwriterDefault_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsSpkwriter.cpp:49:11: warning: variable ‘newCamera’ set but not used [-Wunused-but-set-variable]
   Camera *newCamera = nullptr;
           ^~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsSpkwriter.cpp: In member function ‘virtual void DefaultCube_FunctionalTestSpkwriterFromlist_Test::TestBody()’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/FunctionalTestsSpkwriter.cpp:108:11: warning: variable ‘newCamera’ set but not used [-Wunused-but-set-variable]
   Camera *newCamera = nullptr;
           ^~~~~~~~~
[3605/3612] Building CXX object tests/CMakeFiles/runISISTests.dir/TestUtilities.cpp.o
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/TestUtilities.cpp: In function ‘QString Isis::fileListToString(QVector<QString>)’:
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/TestUtilities.cpp:284:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < fileList.size(); i++) {
                        ~~^~~~~~~~~~~~~~~~~
/usgs/cpkgs/isisTest/isisHRSCSRC/ISIS3/isis/tests/TestUtilities.cpp:288:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (i != fileList.size() - 1) {
           ~~^~~~~~~~~~~~~~~~~~~~~~

**Comment by AustinSanders** [comment]
This issue should be resolved as of #5050
