### ISSUE TITLE
Apps converted to a callable no longer log in real time

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4914]
**ISIS version(s) affected**: varies by app. Conversion started at 3.7, so 3.7+

**Description**  

Apps that have been converted to a callable function no longer log directly to the application, instead they log to a PVL object and then upon completion log its whole contents to the application.

**How to reproduce**  

This is most notable with jigsaw. If you run jigsaw in ISIS 4.4 or later it won't log until it reaches the very end of the process.

**Possible Solution**  

One possible solution is to create a logger object that logs things, if possible, as we add to it. This would be similar to the current Application::log function, but it would be an object passed into function calls similar to our process objects.

**Comment by lwellerastro** [comment]
This doesn't seem to be an issue for most programs that run quickly, but it's very noticeable with jigsaw which can take > 1 hour to run even a single iteration on some networks.  It makes it hard to see what is happening particularly with cluster runs when you are already in the dark.

**Comment by Kelvinrr** [comment]
The best approach to this might be to subclass Pvl and have a log object that reports as things are added with Applcation::Log even without an iApp instance. That way we can still return the results as PVL and not have to update every callable.

**Comment by Kelvinrr** [comment]
idk why I thought a new class was gonna be easier, it required updating way more stuff manually. Decided to make a new function instead which made things way easier to update.
