### ISSUE TITLE
moccal error：The attempt to load "/home/xr/anaconda3/envs/isis/data/mgs/kernels/sclk/MGS_SCLKSCET.00061.tsc" by the routine FURNSH failed

### ISSUE THREAD

**Issue by luoflu** [DOI-USGS/ISIS3#4915]
**ISIS version(s) affected**: 6.0.0

**Description**  
Hi, I am proccessing MOC image. While moc2isis and spiceinit worked successfully,  moccal returns the error as below:
**ERROR** An unknown NAIF error has been encountered. The short explanation provided by NAIF is [SPICE(NOSUCHFILE)]. The Naif error is [The attempt to load "/home/xr/anaconda3/envs/isis/data/mgs/kernels/sclk/MGS_SCLKSCET.00061.tsc" by the routine FURNSH failed. It could not be located.].

**How to reproduce**  

**Possible Solution**  
Because the size of kernels is so big, i downloaded mgs data files without kernels. Hence, I try to mannually download mgs_sclkscet_00061.tsc from https://naif.jpl.nasa.gov/pub/naif/pds/data/mgs-m-spice-6-v1.0/mgsp_1000/data/sclk/, and put it under the path /mgs/kernels/sclk/, but it returns the same error when running moccal again.

**Additional context**  
![%( 0)8F92@_QKW~588J0U D](https://user-images.githubusercontent.com/103924277/163950577-96939ee1-e11b-4f4e-8a60-e8399216e7c4.png)
![QQ图片20220419153950](https://user-images.githubusercontent.com/103924277/163951275-9de5e9d6-3c70-47a3-869a-7e52e6169b18.png)

**Comment by astrostu** [comment]
That certainly looks like an issue with your paths and where the kernels are (does that file exist on your system)?  But you should be aware that I have found that many thousands of MOC (at least wide-angle) images fail to process through the MOCCAL step, with fewer having issues with SPICEINIT ... the kernels and calibrations that USGS provides don't quite account for everything.

**Comment by jessemapel** [comment]
Can you post the contents of your data directory located at `$ISISDATA`? This looks like an issue with how you have the data staged, you should be able to successfully run moccal on the spiceinit'd cube. You will likely need the calibration data donwloaded too.

**Comment by luoflu** [comment]
> That certainly looks like an issue with your paths and where the kernels are (does that file exist on your system)? But you should be aware that I have found that many thousands of MOC (at least wide-angle) images fail to process through the MOCCAL step, with fewer having issues with SPICEINIT ... the kernels and calibrations that USGS provides don't quite account for everything.

Thanks for your reply and you remind me that the file i downloaded online is named as  mgs_sclkscet_00061.tsc, while MGS_SCLKSCET.00061.tsc is autually mentioned in the error. I wonder if these two imply the same file, so I rename the file i downloaded online as MGS_SCLKSCET.00061.tsc which is required in the error, and it worked unexpectedly. By the way, the calibration process works well as the figure below shows.
![image](https://user-images.githubusercontent.com/103924277/164416144-2b906ff5-5262-46d3-9c30-1cfbf485857e.png)
![image](https://user-images.githubusercontent.com/103924277/164416155-d1a2bf86-2f80-409d-8e4f-cea821bc432d.png)

**Comment by luoflu** [comment]
> Can you post the contents of your data directory located at `$ISISDATA`? This looks like an issue with how you have the data staged, you should be able to successfully run moccal on the spiceinit'd cube. You will likely need the calibration data donwloaded too.

If i do not misunderstand, my data directory is located at /home/xr/anaconda3/envs/isis/data. And i have downloaded calibration data of mgs mission. But whatever, i have sovled the problem as described in my last reply, thanks for your help sincerely.

**Comment by jessemapel** [comment]
Yeah there are some uppercase vs lowercase file naming pitfalls. Glad you could get this resolved.
