### ISSUE TITLE
PVL error while running mocproc

### ISSUE THREAD

**Issue by luoflu** [DOI-USGS/ISIS3#4916]
**ISIS version(s) affected**: 6.0.0

**Description**  
When i try to run mocproc. it returns the error as below:
**ERROR** PVL Keyword [Class] does not exist in [Group = Error].
Continuing ......
**ERROR** PVL Keyword [Class] does not exist in [Group = Error].
Continuing ......
**ERROR** Running Isis program [mocevenodd] failed with return status [4].
**I/O ERROR** Unable to open [./sp125703.lev1.cub].
Continuing ......
**ERROR** Running Isis program [cam2map] failed with return status [4].
**I/O ERROR** Unable to open [./sp125703.evenodd.cub].
Continuing ......

**How to reproduce**  

**Possible Solution**  
I have checked the similar issue "**ERROR** PVL keyword [class] does not exist in [Group=Error] #4848" by ldx119, but i have downloaded the base data area and moc2isis works well. 

**Additional context**  
![0W$W( SBJAL(%S5PM(NICYP](https://user-images.githubusercontent.com/103924277/163974613-fe520d43-c5db-4c33-997f-f52a4cd2fe30.png)
![8IFF2}`KFALKF~8_9 3OW B](https://user-images.githubusercontent.com/103924277/163973204-8c0a3a98-f8b0-4217-85c5-80e93dd8b4f0.png)

**Comment by jessemapel** [comment]
This is likely being caused by #4915 as it runs cmoccal as part of mocproc.

**Comment by luoflu** [comment]
> This is likely being caused by #4915 as it runs cmoccal as part of mocproc.

Thanks for your attention. I can run moccal successfully now, but mocproc still returns the same error.

**Comment by acpaquette** [comment]
@luoflu Apologies for only getting to resolve this now, I pulled the same image you are working with and it runs mocproc fine. What data have you downloaded, and have you tried running spiceinit on the ingested image?

**Comment by luoflu** [comment]
> @luoflu Apologies for only getting to resolve this now, I pulled the same image you are working with and it runs mocproc fine. What data have you downloaded, and have you tried running spiceinit on the ingested image?
As I know, running mocproc needs only one command line, "mocproc from=xx.img to=xx.cub", but I tried running spiceinit as you suggested.  It didn't work, either. By th way, I wonder what is the "data" you refer to?
![image](https://user-images.githubusercontent.com/103924277/177746726-3aa43748-1acd-4fa5-a8c0-f596dedfac91.png)

**Comment by luoflu** [comment]
> @luoflu Apologies for only getting to resolve this now, I pulled the same image you are working with and it runs mocproc fine. What data have you downloaded, and have you tried running spiceinit on the ingested image?

As I know, running mocproc needs only one command line, "mocproc from=xx.img to=xx.cub", but I tried running spiceinit as you suggested. It didn't work, either. By th way, I wonder what is the "data" you refer to?
![image](https://user-images.githubusercontent.com/103924277/177770088-d3544096-760b-46c0-98fb-5ba3461dabd9.png)

**Comment by acpaquette** [comment]
It looks like your first run of `spiceinit` from the output you provided ran correctly. The data is in reference to the ephemeris data needed for `spiceinit` and other applications to actually run them. For instance, `moc2isis` needs the leap second kernel to generate times to use in `spiceinit`. Can you try running `spiceinit` with web disabled, or `web=false`? If you have set ISISDATA, can you give me the output from `echo $ISISDATA`?

Let me know if I need to clarify anything!

**Comment by jessemapel** [comment]
We're seeing this error here:

https://astrodiscuss.usgs.gov/t/problems-while-installing-isis/

**Comment by luoflu** [comment]
> It looks like your first run of `spiceinit` from the output you provided ran correctly. The data is in reference to the ephemeris data needed for `spiceinit` and other applications to actually run them. For instance, `moc2isis` needs the leap second kernel to generate times to use in `spiceinit`. Can you try running `spiceinit` with web disabled, or `web=false`? If you have set ISISDATA, can you give me the output from `echo $ISISDATA`?
> 
> Let me know if I need to clarify anything!

I don't download the data needed for spiceinit locally, as it is so large that it always interrupted while downloading. That is, I can only use spiceinit with web=yes. Attached is the output for echo $ISISDATA.
![RPL%0ST{2RYGU7B6B81QF%F](https://user-images.githubusercontent.com/103924277/185310201-8c96a398-4007-44fc-8509-0565c3dbc4f5.png)

**Comment by luoflu** [comment]
> We're seeing this error here:
> 
> https://astrodiscuss.usgs.gov/t/problems-while-installing-isis/

I've tried running the command lines you listed which contained in the mocproc program, and they worked well except that I skipped the mocnoise50 as the image I'm  working with is Wide Angle image. Maybe I should run those command lines instead of mocproc directly.
