### ISSUE TITLE
How to project ground point into camera

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#4920]
I spent quite a lot of time on this and can't seem to get it right. 

Given an ISIS camera made from a cub file and a point on the planet surface, having latitude, longitude, and radius in meters, I am trying to find where it projects in the camera. I tried to create an Isis::SurfacePoint with these, then call the Isis::Camera's SetGround() (also tried SetUniversalGround()), and then use camera's Sample() and Line() functions. 

I am however getting good answers only if close to the datum (the shape in the .cub file is the datum, and my example is on the moon, with the radii being 1.7374e+06). When the ground point is 1000 m above the datum, the returned pixel projection in the camera is wrong. 

Any thoughts?

**Comment by jessemapel** [comment]
Unfortunately, this is just how ISIS sensors work. The first step in the `SetGround` function is to use the ground map to map the ground point onto the surface model and get a local radius value.

@scsides or @KrisBecker may have more insight, but I don't think what you want is currently possible. It is certainly something we'll want to consider doing in the future to support things like bundle adjustment close to the limb and bundle adjustment with a very bad apriori shape model.
