### ISSUE TITLE
building with CentOS gcc4.yml environment results in conda stuck at solving environment

### ISSUE THREAD

**Issue by steo85it** [DOI-USGS/ISIS3#4921]
**ISIS version(s) affected**: dev

**Description**  

Following the instructions [here](https://github.com/USGS-Astrogeology/ISIS3/wiki/Developing-ISIS3-with-cmake) for building ISIS on CentOS results in conda `Solving environment...` running forever.

**How to reproduce**  

Run `conda env create -n isis3_centos -f environment_gcc4.yml` and wait...

**Possible Solution**  

One notable element missing from the .yml file is `python` itself. Googling around, this might cause the env solving to look around the system forever. However, I get conflicts when I try to add a python version to the yml file.

**Additional context**  

It might be related to my system or installation, I'm not 100% sure, but I tried to `conda clean -a` to no effect. When using the regular `environment.yml`, then everything works as expected, but `ninja install` finds a compiler error (which is the reason for the different yml for CentOS systems, I guess). Thanks for any help/check on this!
@jessemapel

**Comment by jessemapel** [comment]
@steo85it Unfortunately, we don't support the GCC4 environment any more. We've needed to update our dependencies for various reasons and conda-forge, where we get our dependencies from, has moved wholesale away from GCC4 support.

Can you post the error you encountered when compiling with the environment from the normal`environment.yml` file? I may be able to help you if it's not related to your compiler.

**Comment by steo85it** [comment]
Ah, really? Then it's just the wiki that needs to be updated? Good to know, thanks, then I'll dig a bit more into the "gcc-related" error message that I got: I thought CentOS was meant not to work with that yml and didn't try too hard. :) Your help will be appreciated if I can't solve it, thanks!
(still, I'd suggest to remove the [wiki](https://github.com/USGS-Astrogeology/ISIS3/wiki/Developing-ISIS3-with-cmake/548eb59b424e3ee1057c684b8bfdbde7c5ad674d) line
```
For CentOS7:

conda env create -n <environment-name> -f environment_gcc4.yml
```
)

**Comment by jessemapel** [comment]
I've updated the wiki page, thank you for pointing that out. You're welcome to just post your error message here and I can take a look at it.

**Comment by steo85it** [comment]
No problem and thanks: I'm still struggling with it but I think it's our anaconda environment that is somehow messy (some issue with qt libraries differing between the env and conda installation is what's blocking me now). Unfortunately not something you can probably help much with. ;) :(
And never mind, in the end the regular conda installation of 6.0.0 worked fine for me. I just need to remember to go this way next time.
