### ISSUE TITLE
The ZeroDarkRate example configuration file for hical is not present in the data area

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#4927]
**ISIS version(s) affected**: 6.0.0

**Description**  
The ISIS 6.0.0 version of hical has a new ZeroDarkRate correction.  The CHANGELOG and app documentation discuss a `$ISISDATA/mro/calibration/hical.0023_darkrate.conf` but it does not appear to be present in the rsync data area.

**How to reproduce**  
`rsync isisdist.astrogeology.usgs.gov::isisdata/data/mro/calibration/ | grep rate` returns nothing.

**Possible Solution**  
One can devise the proper incantations and create a working file that can be passed to hical, but the promised example file would be best.

**Comment by jessemapel** [comment]
The file is now available.
