### ISSUE TITLE
Missing LRO kernel data

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#4930]
I fetched the ISISDATA file named lro/kernels/mk/lro_2018.tm. Its content is:

\begindata
  KERNELS_TO_LOAD = (
   '/usgs/cpkgs/isis3/data/lro/kernels/tspk/moon_pa_de421_1900-2050.bpc'
   '/usgs/cpkgs/isis3/data/lro/kernels/tspk/de421.bsp'
   '/usgs/cpkgs/isis3/data/lro/kernels/spk/fdf29r_2018152_2018182_v01.bsp'
   '/usgs/cpkgs/isis3/data/lro/kernels/ck/lrolc_2018151_2018182_v01.bc'
   '/usgs/cpkgs/isis3/data/lro/kernels/ck/moc42r_2018151_2018182_v01.bc'
   '/usgs/cpkgs/isis3/data/lro/kernels/fk/lro_frames_2014049_v01.tf'
   '/usgs/cpkgs/isis3/data/base/kernels/pck/pck00009.tpc'
   '/usgs/cpkgs/isis3/data/lro/kernels/pck/moon_080317.tf'
   '/usgs/cpkgs/isis3/data/lro/kernels/pck/moon_assoc_me.tf'
   '/usgs/cpkgs/isis3/data/lro/kernels/ik/lro_lroc_v18.ti'
   '/usgs/cpkgs/isis3/data/lro/kernels/iak/lro_instrumentAddendum_v04.ti'
   '/usgs/cpkgs/isis3/data/base/kernels/lsk/naif0012.tls'
   '/usgs/cpkgs/isis3/data/lro/kernels/sclk/lro_clkcor_2019198_v00.tsc'
   'data/lroc_nac_lt.ti'
   )

All the paths above are not correct on my file system. The last file, data/lroc_nac_lt.ti, is missing altogether. Loading of SPICE data then fails.

**Comment by jessemapel** [comment]
One of the issues with metakernels is that you cannot use portable paths in them. So, any user will need to update the `/usgs/cpkgs/isis3/data/` portion of the paths to point to their data area.

For the last kernel, I'm not sure where it came from. I'll do some digging and see what's going on.

**Comment by oleg-alexandrov** [comment]
Somehow cam2map works with such metadata but the ale tools don't.

**Comment by jessemapel** [comment]
ISIS does not use the metakernels in the data area, they are purely extra. ISIS has it's own complex kernel selection logic that we're working to make available in ALE.

**Comment by oleg-alexandrov** [comment]
I guess the metakernels could use instead the hard-coded /usgs/cpkgs/isis3/data/lro/kernels the string $lro/kernels and then do some faux variable expansion the way ISIS does in other cases.

**Comment by jessemapel** [comment]
The problem is that SPICE doesn't have that sort of capability. We could update it when it gets downloaded, we're currently working on getting off the rsync servers and just using scripts to download and setup the data area. It wouldn't be too hard to do some template expansion int he meta kernel files in those scripts. @Kelvinrr Do you have an idea of how much work this would be?

**Comment by jessemapel** [comment]
I've removed these meta kernel files for now. We can eventually come back add some extra functionality to create them if we want, but with work on-going on SpiceQL that seems like a tangential solution.
