### ISSUE TITLE
ISIS install failed on new Mac OS 12.3

### ISSUE THREAD

**Issue by cneish** [DOI-USGS/ISIS3#4932]
**ISIS version(s) affected**: 6.0.0 (whatever is current today!)

**Description**  
I just bought a new Mac laptop (OS 12.3.1), and I am trying to install ISIS on it. I downloaded and installed Anaconda today, and then tried to download and install ISIS. I didn't receive any errors, but when I tried to run any program like "qview" or "isis2std" I received the following error:

(isis) Catherines-MacBook-Pro:~ cneish$ isis2std
dyld[19044]: Library not loaded: @rpath/libavresample.3.dylib
  Referenced from: /Users/cneish/opt/anaconda3/envs/isis/lib/libopencv_videoio.3.2.0.dylib
  Reason: tried: '/Users/cneish/opt/anaconda3/envs/isis/lib/libavresample.3.dylib' (no such file), '/Users/cneish/opt/anaconda3/envs/isis/lib/libavresample.3.dylib' (no such file), '/Users/cneish/opt/anaconda3/envs/isis/lib/libavresample.3.dylib' (no such file), '/Users/cneish/opt/anaconda3/envs/isis/lib/libavresample.3.dylib' (no such file), '/Users/cneish/opt/anaconda3/envs/isis/bin/../lib/libavresample.3.dylib' (no such file), '/Users/cneish/opt/anaconda3/envs/isis/bin/../3rdParty/lib/libavresample.3.dylib' (no such file), '/usr/local/lib/libavresample.3.dylib' (no such file), '/Users/cneish/opt/anaconda3/envs/isis/bin/../lib/libavresample.3.dylib' (no such file), '/Users/cneish/opt/anaconda3/envs/isis/bin/../lib/libavresample.3.dylib' (no such file), '/Users/cneish/opt/anaconda3/envs/isis/bin/../3rdParty/lib/libavresample.3.dylib' (no such file), '/usr/local/lib/libavresample.3.dylib' (no such file), '/Users/cneish/opt/anaconda3/envs/isis/bin/../lib/libavresample.3.dylib' (no such file), '/usr/local/lib/libavresample.3.dylib' (no such file), '/usr/lib/libavresample.3.dylib' (no such file)

I do not appear to have the required "libavresample" files in my anaconda library. Do you know how I might remedy this problem?

Thanks, Catherine

**Comment by jessemapel** [comment]
Can you share your Anaconda environment. Just run conda list and copy/paste the output.

**Comment by cneish** [comment]
Sure thing. The list is below.

(isis) Catherines-MacBook-Pro:~ cneish$ conda list
# packages in environment at /Users/cneish/opt/anaconda3/envs/isis:
#
# Name                    Version                   Build  Channel
ale                       0.8.5            py36hc61eee1_3    conda-forge
armadillo                 9.200.4           hcb88e47_1205    conda-forge
arpack                    3.6.3             h06d5271_1005    conda-forge
blas                      1.1                    openblas    conda-forge
boost                     1.68.0          py36h9888f84_1001    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bullet                    2.86.1                        0    usgs-astrogeology
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2021.5.30        py36h79c6626_0    conda-forge
csm                       3.0.3.3                       0    conda-forge
cspice                    66                h0d85af4_1015    conda-forge
curl                      7.64.0               heae2a1f_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
eigen                     3.4.0                h940c156_0    conda-forge
embree                    2.16.0               h6834224_0    usgs-astrogeology
ffmpeg                    3.4                  h8a2ae75_0  
flann                     1.9.1                         0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
geos                      3.7.3                h4a8c4bd_0    conda-forge
geotiff                   1.4.3             h113155d_1001    conda-forge
gettext                   0.19.8.1          haf92f58_1004    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.51.4                        0    conda-forge
gmm                       5.0                  h6aef312_0    usgs-astrogeology
gmp                       6.2.1                h2e338ed_0    conda-forge
gsl                       2.7                  h93259b0_0    conda-forge
harfbuzz                  1.3.4                         2    conda-forge
hdf5                      1.8.18                        0    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
inja                      3.3.0                he49afe7_0    conda-forge
isis                      6.0.0                         0    usgs-astrogeology
jama                      125                           0    usgs-astrogeology
jasper                    1.900.1           h636a363_1006    conda-forge
jpeg                      9e                   h5eb16cf_1    conda-forge
kakadu                    1                             0    usgs-astrogeology
krb5                      1.16.3            h24a3359_1000    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libcurl                   7.64.0               h76de61e_0    conda-forge
libcxx                    12.0.0               h2f01273_0  
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libopenblas               0.3.18               h9a5756b_0  
libopus                   1.3.1                hc929b4f_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     10.6              hbe1e24e_1000    conda-forge
libprotobuf               3.9.2                hfbae3c0_0    conda-forge
libssh2                   1.8.0             hf30b1f0_1003    conda-forge
libtiff                   4.0.10            ha78913b_1005    conda-forge
libvpx                    1.7.0                h378b8a2_0  
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.9                hd80cff7_2    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
mesalib                   17.1.4                        2    conda-forge
metis                     5.1.0             h2e338ed_1006    conda-forge
mpfr                      4.1.0                h0f52abe_1    conda-forge
mysql                     5.7.20            h0a44026_1001    conda-forge
mysql-connector-c         6.1.11            had4e77e_1002    conda-forge
nanoflann                 1.4.2                h694c41f_0    conda-forge
ncurses                   6.3                  hca72f7f_2  
networkx                  2.5                        py_0    conda-forge
nlohmann_json             3.10.5               he49afe7_0    conda-forge
nn                        1.86.0            h1de35cc_2003    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
opencv                    3.2.0           np113py36_blas_openblas_203  [blas_openblas]  conda-forge
openssl                   1.0.2u               h0b31af3_0    conda-forge
pcl                       1.9.1             hdd77166_1002    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pip                       21.2.2           py36hecd8cb5_0  
pixman                    0.34.0            h1de35cc_1003    conda-forge
postgresql                10.6              ha1bbaa7_1000    conda-forge
proj4                     5.2.0             h6de7cb9_1006    conda-forge
protobuf                  3.9.2            py36h6de7cb9_1    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pvl                       1.3.1              pyhd8ed1ab_0    conda-forge
python                    3.6.7             h4a56312_1002    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36hfa26744_1    conda-forge
qhull                     7.2.0                         0    usgs-astrogeology
qt                        5.9.6                         7    usgs-astrogeology
qwt                       6.1.3                         0    usgs-astrogeology
readline                  7.0               hcfe32e1_1001    conda-forge
scipy                     1.2.1            py36hbd7caa9_1    conda-forge
setuptools                58.0.4           py36hecd8cb5_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
spiceypy                  2.3.2                      py_0    conda-forge
sqlite                    3.28.0               h9721f7c_0    conda-forge
suitesparse               5.10.1               h7aff33d_1    conda-forge
superlu                   5.2.1             hbced767_1205    conda-forge
tbb                       2021.5.0             h940c156_0    conda-forge
tk                        8.6.11               h7bc2e8c_0  
tnt                       126                           0    usgs-astrogeology
tzcode                    2022a                h5eb16cf_0    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
x264                      20131218                      0    conda-forge
xerces-c                  3.1.4                h10f7eb2_0    usgs-astrogeology
xorg-fixesproto           5.0               h0d85af4_1002    conda-forge
xorg-inputproto           2.3.2             h35c211d_1002    conda-forge
xorg-kbproto              1.0.7             h35c211d_1002    conda-forge
xorg-libice               1.0.10               h0d85af4_0    conda-forge
xorg-libsm                1.2.3             h0d85af4_1000    conda-forge
xorg-libx11               1.7.2                h0d85af4_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xorg-libxext              1.3.4                h0d85af4_1    conda-forge
xorg-libxfixes            5.0.3             h0d85af4_1004    conda-forge
xorg-libxi                1.7.10               h0d85af4_0    conda-forge
xorg-xextproto            7.3.0             h35c211d_1002    conda-forge
xorg-xproto               7.0.31            h35c211d_1007    conda-forge
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                h0d85af4_2    conda-forge
zlib                      1.2.12               h4dc903c_2  
zstd                      1.4.9                h582d3a0_0    conda-forge

**Comment by jessemapel** [comment]
It looks like the openCV package isis6.0.0 is using has the wrong ffmpeg pin and it's installing the Main channel ffmpeg instead of the conda-forge ffmpeg on osx.

Run `conda install -c conda-forge ffmpeg=3.4.1`. It will say it's going to replace a few packages, enter `y` and then try again.

This should be resolved with 7.0.0 as we completely updated the dependency environment.

**Comment by cneish** [comment]
That did the trick! Thanks so much @jessemapel!

**Comment by jessemapel** [comment]
I'm going to close this as a "won't fix" because we generally don't go back and address these types of issues if there is a work around and a new release is coming out shortly.

If you have any further issues with this, or if anyone else encounters this issue and installing ffmpeg off conda-forge does not fix it, please post here.
