### ISSUE TITLE
Update lrowaccal to add a radiance units label to the output cube and refactor for testability

### ISSUE THREAD

**Issue by cordellmichaud** [DOI-USGS/ISIS3#4939]
**Description**  

Lrowaccal needs an update to add a radiance units label of "W/m2/sr/um" to the radiometry group of the output cube label to more clearly indicate the radiance units and accompany a change to the radiance calibration coefficients which makes the radiance units match those of the NAC. The units label should only be added when the RadiometricType parameter is Radiance, not IOF.

Lrowaccal also needs an update to be brought in line with the newer testing process for ISIS by refactoring lrowaccal to be callable and adding tests to cover changes.

**Example**  

Before
```
Group = Radiometry
    TemperatureFile    = /path/to/calibration/sometempconstants.pvl
    DarkFiles          = (/path/to/calibration/wac_darks/somedark.cub,
                          /path/to/calibration/wac_darks/somedark.cub)
    FlatFile           = /path/to/calibration/wac_flats/someflatfield.cub
    RadiometricType    = AbsoluteRadiance
    ResponsivityValues = (0.3144246, 0.3284464, 0.3624166, 0.3794062, 0.4931532)
    SolarDistance      = 1.01
    SpecialPixelsFile  = /path/to/calibration/wac_masks/somespecialpixels.cub
End_Group
```

After
```
Group = Radiometry
    TemperatureFile    = /path/to/calibration/sometempconstants.pvl
    DarkFiles          = (/path/to/calibration/wac_darks/somedark.cub,
                          /path/to/calibration/wac_darks/somedark.cub)
    FlatFile           = /path/to/calibration/wac_flats/someflatfield.cub
    RadiometricType    = AbsoluteRadiance <W/m2/sr/um>
    ResponsivityValues = (0.3144246, 0.3284464, 0.3624166, 0.3794062, 0.4931532)
    SolarDistance      = 1.01
    SpecialPixelsFile  = /path/to/calibration/wac_masks/somespecialpixels.cub
End_Group
```

**Comment by AustinSanders** [comment]
Closed via #4940.  Huge thanks to @michaudcordell for identifying this issue and coming in with a PR.  We really appreciate the contribution!
