### ISSUE TITLE
Unable to run isis3Startup.csh

### ISSUE THREAD

**Issue by mblancor** [DOI-USGS/ISIS3#4941]
Hi everyone! 

I just downloaded isis on my Mac (OS Big Sur), and I am hoping to use it to help me with band-to-band registration of Cassini ISS imagery. However, when running source $ISISROOT/scripts/isis3Startup.csh I am getting the following error message: 

/Users/mblancor/opt/anaconda3/envs/isis/scripts/isis3Startup.csh:71: parse error near `\n'

I was exploring the forum to see if I could find an answer, but so far I haven't been able to find any possible solutions. Does anyone have any ideas? Thank you! 

Extra information: The GUI window pops up when running the qview command.

**Comment by jessemapel** [comment]
What shell are you running? What version of ISIS did you install?

**Comment by mblancor** [comment]
Hi! I'm running a zsh shell and I downloaded isis 6.0.0.

> What shell are you running? What version of ISIS did you install?

**Comment by jlaura** [comment]
I am also using zsh on a Mac with 6.0.0. I used the following (step 7 in the installation section of the README):

`conda env config vars set ISISROOT=$CONDA_PREFIX ISISDATA=[path to data directory]`

The snipped you used above it a sheet script for c-shell. I would not expect it to work on zsh. Does running the above command, with your ISISDATA path inserted, work?

**Comment by mblancor** [comment]
Yup it works!! Thank you. I tried using qview to visualize the test image they gave in exercise 1 (Peaks.cub)but still no image seems to pop up on the GIU window... could it be that I set my environment wrong?

**Comment by jessemapel** [comment]
Can you provide a screenshot or snip of what you're seeing/not seeing?

**Comment by mblancor** [comment]
This is what I'm seeing... I am very new to isis, so any help is welcome!
<img width="908" alt="Screen Shot 2022-05-05 at 1 20 36 PM" src="https://user-images.githubusercontent.com/105002107/166978177-ea645008-4040-45f0-bad4-6d41fdefe44d.png">

**Comment by jessemapel** [comment]
What command did you run to view the cube? You should also be able to click on the "open Cube" icon in the top left to open a file dialogue for opening cubes.

**Comment by mblancor** [comment]
Ah I didn't know I could use the icon on the top left! I originally used qview Peaks.cub, but the opening it right from the GUI worked perfectly. Thank you so much! 

I was also wondering where the best place to ask questions is, I have a couple of questions about opening cassini data (I'm getting an error reading the input file saying: 'This image does not contain a pds label.' even though i'm inputting the lbl file...). Is there a place where I could ask these questions directly? I don't want to spam the forum if its not necessary! 😁😁

**Comment by jessemapel** [comment]
Try https://astrodiscuss.usgs.gov/ more of our user community is over there. The GitHub issues are more watched by devs
