### ISSUE TITLE
Missing isolated pixels in LRO WAC images

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#4944]
**ISIS version(s) affected**: 6.0.0

**Description**  

LRO WAC images come split into "even" and "odd" images, which are then combined with the new *framestitch* tool. 

The *lrowaccal* tool removes what seem to be perfectly good good isolated pixels (and sometimes two pixels in a row). Here's a screenshot of an even image, odd image, and the combined stitched image, after lrowaccal. The image id is M119923055ME.

![image](https://user-images.githubusercontent.com/1325676/167226825-e51c7a84-0b54-4a6c-a260-07f1a0813ab1.png)

This results in artifacts in stereo.

Here's a screenshot before and after using lrowaccal:

![image](https://user-images.githubusercontent.com/1325676/167228583-81d54915-dbdf-4026-8f7b-b7046df64d61.png)

Using  lrowaccal with the option specialpixels = false, solves this, but then junk is left on left and right image edges. 

I don't know what their source is or how these are handled in the existing WAC pipeline.

One solution here may be to fine-tune the special pixel removal. Maybe only the ones on left and right edges should be removed, or have a threshold for removal (such as amount of disagreement with neighbors) with would be less strict.

Another solution would be to stitch the images with missing isolated pixels, then fill those with neighbors with some weighted average of neighbors.

**Comment by AustinSanders** [comment]
I was able to reproduce this behavior via
``` 
curl http://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0002/DATA/MAP/2010035/WAC/M119929852ME.IMG -o M119929852ME.IMG
lrowac2isis from= M119929852ME.IMG to = M119929852ME.cub 
lrowaccal from= M119929852ME.vis.even.cub to= M119929852ME.vis.even.cal.cub
lrowaccal from= M119929852ME.vis.odd.cub to= M119929852ME.vis.odd.cal.cub
framestitch even= M119929852ME.vis.even.cal.cub odd= M119929852ME.vis.odd.cal.cub to= M119929852ME.vis.stitched.cal.cub
```

If this isn't resolved as part of the LROWAC work during the ongoing CSM/ALE sprint, we'll get it slotted for either continuous support or a dedicated support sprint.

**Comment by oleg-alexandrov** [comment]
This is resolved by https://github.com/USGS-Astrogeology/ISIS3/pull/4950.

**Comment by gengxun-henu** [comment]
> I was able to reproduce this behavior via
> 
> ```
> curl http://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0002/DATA/MAP/2010035/WAC/M119929852ME.IMG -o M119929852ME.IMG
> lrowac2isis from= M119929852ME.IMG to = M119929852ME.cub 
> lrowaccal from= M119929852ME.vis.even.cub to= M119929852ME.vis.even.cal.cub
> lrowaccal from= M119929852ME.vis.odd.cub to= M119929852ME.vis.odd.cal.cub
> framestitch even= M119929852ME.vis.even.cal.cub odd= M119929852ME.vis.odd.cal.cub to= M119929852ME.vis.stitched.cal.cub
> ```
> 
> If this isn't resolved as part of the LROWAC work during the ongoing CSM/ALE sprint, we'll get it slotted for either continuous support or a dedicated support sprint.

Which ISIS version contains 'framestich' App? Please tell me. Thanks a lot!

**Comment by jessemapel** [comment]
The framestitch app will be available in the next public release of ISIS. If you want access to it earlier, you can download the current source and build it locally.
