### ISSUE TITLE
Artifacts in stitching WAC images

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#4945]
**ISIS version(s) affected**: bleeding edge from the repo, so version > 6.0.0

**Description**  

The new *framestitch* tool for stitching together WAC images creates images with artifacts at edges of the framelets being stitched. 

Here are stitched images  M119923055ME.cub and M119929852ME.cub. I zoomed in to the center of the Tycho crater.  

![image](https://user-images.githubusercontent.com/1325676/167448719-44f810dc-3183-49c7-8bd7-713d5083e329.png)

As it can be seen, there are linear artifacts, going from left to right, and for each image they are in different places.

Doing mapprojection makes them go away, to the correspondence between pixels and ground is good, so the camera knows how to compensate for this, but the artifacts just look bad in the pictures and create stereo artifacts.

The solution may be to shift the framelets vertically and perhaps horizontally when stitching them, I guess, by an integer or subpixel amount, and adjust the camera modeling accordingly.

**Comment by jessemapel** [comment]
These artifacts are likely in the original images. There is a small amount of overlap between sequential frames to ensure that the entire ground swath is covered. We could try adding a trimming option that cuts out the overlapping pixels in one frame.

**Comment by oleg-alexandrov** [comment]
This is not fully resolved yet. The .cub file created by framestitch cannot be used to create a CSM camera model file as it lacks kernel info. An original cub file cannot be used either because that one is lacking the variable written by framestitch which accounts for how many lines get removed from each framelet on stitching.

As such, the process of using ISIS and CSM with WAC is in limbo. Hopefully a decision for how to proceed is made soon, before this is forgotten.

**Comment by jessemapel** [comment]
As of #4972 this is completed. Users will still need to determine an accurate trim setting. If a more automated approach is required a separate enhancement request can be opened.

**Comment by oleg-alexandrov** [comment]
> Users will still need to determine an accurate trim setting. If a more automated approach is required a separate enhancement request can be opened.

I don't think there is a good trim setting which will work even for a single dataset. Framelets should overlap more in lower-lying visible terrain than in higher one, as then rays have a longer distance to travel and to diverge, and end up seeing more surface, and hence neighboring framelets end up seeing more shared data. Also, for more oblique shots, the framelets at a more oblique angle should overlap more.

This will require some careful investigation at some point.  Likely only stereo with mapprojected images is feasible, when the framelets merge.
