### ISSUE TITLE
Building ISIS with tests off

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#4946]
**ISIS version(s) affected**: latest

The base ISIS CMakeLists.txt has both BUILD_TESTS and buildTests variables, and there is a lot of logic in there for building tests which is not conditional upon any of these. And building ISIS with either these on or off fails, with no explanation except for 

No rule to make target 'ISIS3/gtest/googlemock/src/gmock-all.cc'

at compile time. So at cmake time there are no checks which should ensure testing functionality needed later actually exists.

**Comment by jessemapel** [comment]
> building ISIS with either these on or off fails, with no explanation except for
> 
> No rule to make target 'ISIS3/gtest/googlemock/src/gmock-all.cc'
> 
> at compile time.

This is usually an issue with your gtest submodule. Make sure that it's properly initialized

**Comment by oleg-alexandrov** [comment]
The BUILD_TESTS/buildTests issue is addressed in https://github.com/USGS-Astrogeology/ISIS3/pull/4957.

As to gtest, apparently that one is set up properly if one runs buildCondaRelease.sh from the repo, as that sets up everything. 

BTW, the build was failing with my local compiler, which is GCC 4. I did not pursue this in detail. It may be helpful to spell out a compiler in meta.yaml which conda will then install and use, rather than relying on what the user has on their own machine.
