### ISSUE TITLE
Too much work is happening when building

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#4958]
I am tweaking the new tool framestitch.cpp, which has little to do with anything else in the repo. Yet, changing one line in it results in "ninja install" doing 800 relinking jobs, including for libisis.so and lots of tools and unit tests.

Why are things so tied together? All this takes time to run.

**Comment by AustinSanders** [comment]
This is a "nice to have" that I think should remain open.
