### ISSUE TITLE
MARCI Variable Exposure Table "varexp.tab" Needs to Be Updated

### ISSUE THREAD

**Issue by dpmayerUSGS** [DOI-USGS/ISIS3#4969]
**ISIS version(s) affected**: >= 3.4.9

**Description**  
`marcical` references a file in the ISIS data area, "varexp.tab" which contains variable exposure times of MARCI observations. This file is updated in the PDS with each (quarterly) MARCI data release, but there is as of yet no automated process of updating the file in the ISIS data area with the latest one from the PDS. 

The copy of "varexp.tab" in the ISIS data area was last updated in December 2021 to bring it up to date with MRO release 59. The latest date release was 1 June 2022, thus the ISIS data area is 2 releases behind the latest version from the PDS, so `marcical` won't have correct variable exposure times if a user tries to process data delivered since that time.

**Possible Solution**  
Add the latest (MRO release 61) version of the MARCI variable exposure table and label to the ISIS data area:

- https://pds-imaging.jpl.nasa.gov/data/mro/marci/mrom_1343/index/varexp.tab
- https://pds-imaging.jpl.nasa.gov/data/mro/marci/mrom_1343/index/varexp.lbl

**Additional context**  
cf. #4710  for the last time this file was updated, and #3489 some discussion of some ways this file could be updated automatically in the future. I forgot to open an issue after MRO release 60, but the tables are cumulative, so grabbing the varexp table linked above will cover the whole mission to date.

**Comment by jessemapel** [comment]
I wonder if this can be automated using the tooling from #4937

**Comment by jessemapel** [comment]
I downloaded the new table and it appears to be exactly the same as the one we have right now. There's still the issue of needing to automatically update it, but it looks like they haven't commanded any new variable exposure marci images.
