### ISSUE TITLE
Issues initializing camera model

### ISSUE THREAD

**Issue by cneish** [DOI-USGS/ISIS3#4970]
**ISIS version(s) affected**: 6

**Description**  
We have been attempting to get the Ames Stereo Pipeline back up and running on an Ubuntu 14 machine, in order to produce CTX DEMs. Previously, you helped me upgrade ISIS from ISIS 3 to the most recent version, ISIS 6. Now, when we run "parallel_stereo" we get errors related to ISIS being unable to find the shape model file (error message below). It almost seems like it cannot file the data directory.

**How to reproduce**  

> parallel_stereo D17_033814_1526_XI_27S046W.map.cub D18_034091_1526_XI_27S046W.map.cub results/out

Error: **ERROR** Unable to initialize camera model from group [Instrument].
**PROGRAMMER ERROR** Unable to create a shape model from given target and pvl.
**I/O ERROR** Invalid shape model file [$base/dems/molaMarsPlanetaryRadius0005.cub] in Kernels group.
**ERROR** The given shape model file is not a valid ISIS DEM. Unable to open as an ISIS cube.
**I/O ERROR** Unable to open [$ISIS3DATA/base/dems/molaMarsPlanetaryRadius0005.cub].
**ERROR** The given shape model file is not a valid NAIF DSK file. Unable to construct a NAIF DSK shape model.
**USER ERROR** NAIF DSK file [$base/dems/molaMarsPlanetaryRadius0005.cub] does not exist.

**Possible Solution**  
As I mentioned earlier, I wonder if ISIS is no longer able to find the data directory, after my recent update of the software. However, when I type "echo $ISISDATA", it directs me to the correct folder.

Any help you could provide would be appreciated!

Thanks, Catherine

**Comment by jessemapel** [comment]
The real error here is the last one:

> file [$base/dems/molaMarsPlanetaryRadius0005.cub] does not exist.

Check that you have your environment variables set correctly and that the file does exist where your environment and the kernels group says it does.

**Comment by rbeyer** [comment]
So your `*.map.cub` files are now made with your new ISIS 6 version.  What version of ASP are you using?  You can run `parallel_stereo -v` to find out.

It might also be useful to walk through what processing steps you used to make those `*.map.cub` files.

However, these messages do really seem like the programs can't find the files they need.  Is $ISISDATA set correctly in the ASP conda environment, or whatever environment that you're running `parallel_stereo` from?  Are there permissions problems?  Maybe the environment variable is set, but the files are read-only to some other user?  Not entirely sure.  This is a head-scratcher.

**Comment by cneish** [comment]
@jessemapel, yes, we checked that the file exists in the $ISISDATA directory.

@rbeyer I am not at the computer right now, but I will take a look as soon as I can, and let you know what version of ASP we are using. I expect it is a very old one. Perhaps it is time to update that as well?

**Comment by cneish** [comment]
@rbeyer Here are the results from parallel_stereo -v. I believe we installed this in 2018, so it is well out of date.

NASA Ames Stereo Pipeline 2.6.1
  Build ID: 4672278

Built against:
  NASA Vision Workbench 2.2.0_post
    Build ID: 072d83f
  USGS ISIS 3.5.0
  Boost C++ Libraries 105900
  GDAL 2.0.2 | 20160126
  Proj.4 480

**Comment by rbeyer** [comment]
That might be the problem?  ASP uses ISIS libraries, and that version of ASP is using ISIS 3.5.0.  That older version of ISIS has a slightly different data directory structure and needs, so the "new" files that you built with the new ISIS, can't be operated on by the old ASP which is using the old ISIS, maybe?  Not sure.

Although it still looks like a "can't find a file" problem, so that's confusing, too.

**Comment by cneish** [comment]
@rbeyer So is the solution to install the new version of the ASP? We had to upgrade ISIS, as version 3.5.0 was not processing CTX files correctly.

**Comment by jessemapel** [comment]
Try also setting $ISIS3DATA to $ISISDATA and see if that fixes the problem.

**Comment by rbeyer** [comment]
Yeah, maybe upgrading ASP will address the problem, but I'm not sure.

**Comment by cneish** [comment]
Upgrading ASP seemed to do the trick! We just successfully ran a pair of CTX images through the processor. Thanks all.
