### ISSUE TITLE
Cnetcombinept log file logs everything, not just merged points

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#4973]
**ISIS version(s) affected**: tested under 5.0.2 but also broke in newer versions of isis

**Description**  
The log includes an entry for all points in the output network when it should only include entries for points that were merged.
It makes it very difficult to identify which points have new measures that require registration for extremely large networks.

**How to reproduce**  
See my work users area directory Isis3Tests/CnetCombinePt/Log

```
cnetcombinept cnetlist=nets.lis onet=TestCombinePt10.net logfile=TestCombinePt10.log networkid=Island25 description="GLL SSI Merge Island25 to Island1, 8 and 9" imagetol=10

  Group = Summary
    TotalCubes        = 29
    TotalInputPoints  = 43
    TotalOutputPoints = 40
    PointsMerged      = 3
    PointsEvaluated   = 3
    TotalMeasures     = 99
    MeasuresMerged    = 2
    MeasuresDeleted   = 0
    MinimumMeasures   = 0
  End_Group
```
I expect the log to include information on the 2 measures that were merged, at least according documentation.

```
wc -l TestCombinePt10.log
41 TestCombinePt10.log
```

**Additional context**  
I came across this while combining two very large networks that have a few hundred overlapping images but many hundreds of thousands of points each.  The newly combined network has >750k points but only 5500 points were merged.  I need to register measures only for the newly merged points and that will go quicker if I can identify those points, extract them, then register them.  This is for the Kaguya TC project and a working log will be much easier to work with to generate a list of points register, than say running cnetstats on the input and output networks and making comparisons and differences of the point statistics files to identify those same points (or some other similar yet cumbersome way).

**Comment by AustinSanders** [comment]
Closed via #4984
