### ISSUE TITLE
How to set up an ISIS3 cmake Project in Qt Creator?

### ISSUE THREAD

**Issue by xwc2016** [DOI-USGS/ISIS3#4977]
We use Github issues solely for discussing bugs, documentation issues, and new features.

For
questions about using ISIS or other ASC software, please use
any of the support alternatives: https://astrodiscuss.usgs.gov or https://gitter.im/USGS-Astrogeology/IAA

A great resource about asking high quality questions that generate high quality answers is available from the StackOverflow community: [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)

Thanks!

**Comment by AustinSanders** [comment]
Hi @xwc2016 ,

Have you followed the steps listed in the Qt Creator [documentation](https://doc.qt.io/qtcreator/creator-project-cmake.html)?  ISIS3 uses Ninja as a build generator, so you might also reference the [documentation](https://doc.qt.io/qtcreator/creator-build-settings-cmake.html#using-ninja-as-a-cmake-generator) for build settings.

If you've worked through the documentation and are stuck on a particular step or would like clarification, feel free to post your specific issue here.  Unfortunately, given my inexperience with your particular development and build system, I cannot provide guidance on the general setup process, but I will try to make myself available for specific questions.
