### ISSUE TITLE
Installation under CentOS 7.9.2009 throws UnsatisfiableError

### ISSUE THREAD

**Issue by swalterfub** [DOI-USGS/ISIS3#4998]
**ISIS version(s) affected**: 7.0.0

**Description**  
Installation by strictly following the Readme throws an error under conda.

**How to reproduce**  
CentOS 7.9.2009, Anaconda3/2021.11 via EasyBuild framework

**Possible Solution**  

**Additional context**  
[isis-install-conda.log](https://github.com/USGS-Astrogeology/ISIS3/files/9121125/isis-install-conda.log)

**Comment by jessemapel** [comment]
Can you post your channel config from `conda config --show channels`.

**Comment by swalterfub** [comment]
``` $ conda config --show channels
channels:
  - usgs-astrogeology
  - conda-forge
  - defaults

**Comment by swalterfub** [comment]
This problem has been solved using the latest mambaforge instead of EasyBuild.
