### ISSUE TITLE
ISIS version 4.4.0 having error on web spiceinit 

### ISSUE THREAD

**Issue by ndhverma** [DOI-USGS/ISIS3#5022]
**ISIS version(s)

[](url) 4.4.0 # Public version number
2021-02-04 # Release date
stable # Release stage (alpha, beta, stable)
Hi, 
I am processing the LRO biststic Mini-RF images. 
The following are steps i am following
mrf2isis
spiceinit

but when running the spiceinit I am getting the following error

![image](https://user-images.githubusercontent.com/43364419/182809651-c5866e63-c4d5-4f2d-b086-9521f7ec20cb.png)

**Comment by jessemapel** [comment]
Hi @ndhverma, please stop opening duplicate issues. We are aware of the issue you are encountering in #5005  and will look into it as our time allows
