### ISSUE TITLE
downloadIsisData not in path after setting ISISROOT

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#5027]
**Description**
After finishing the install of 7.0.0, and confirmed other ISIS apps like qview being in the path, I tried to use `downloadIsisData` but it was not in the path.
There is no other info in the instructions on how to obtain `downloadIsisData.py`.

**Suggested Edit**
Put sufficient info on where to get or find `downloadIsisData.py` into the installation instructions.

**Comment by jlaura** [comment]
This is a link to the current README: https://github.com/USGS-Astrogeology/ISIS3/#how-do-i-access-the-isisdata-download-script-with-isis-700-or-earlier

What additional information would you like to see?

**Comment by michaelaye** [comment]
* Isn't that in the wrong section? As this is the new download script, I was not looking in a section called "Installing older versions of ISIS".
* The language needs to be cleaned up, is it an application or a script, using both is confusing to the non-programmer that isn't aware that people throw this vocab around without consideration.
* I suggest a cross-link from the first time it is written about (like at https://github.com/USGS-Astrogeology/ISIS3/#full-isis-data-download) to https://github.com/USGS-Astrogeology/ISIS3/#how-do-i-access-the-isisdata-download-script-with-isis-700-or-earlier, or even earlier in its own paragragh. As there will be veteran ISIS users knowing about data downloads, to change rsync to that script earns its own section/paragragh.

I can work on this and submit a PR.

**Comment by Kelvinrr** [comment]
@michaelaye The fact that the script didn't show up is concerning, maybe an issue with how the library is packaged for anaconda as the install seems to work just fine locally. I'll look into it. The instructions that Jay linked are more about using an older version. 

I agree that removing the .py might be a bit confusing. Although, I do prefer leaving it without the .py. Maybe we can update the docs to remove using the python interpreter directly and instead doing a `chmod +x`?

**Comment by jessemapel** [comment]
> @michaelaye The fact that the script didn't show up is concerning, maybe an issue with how the library is packaged for anaconda as the install seems to work just fine locally. I'll look into it. The instructions that Jay linked are more about using an older version.

I think Michael download 7.0 which does not have the script in it.

**Comment by michaelaye** [comment]
that is correct, this was with isis7. so, how does one get ISISDATA in v7 then?

**Comment by michaelaye** [comment]
i just installed isis v6 and the script isn't in the path there either. (Linux)

**Comment by michaelaye** [comment]
Related question: the `rclone.conf` one receives via the link pointed to by Jay has 0 bytes size?
ah, and the curl command downloads the python script as html... harrrrrr
update: i guess because https://github.com/USGS-Astrogeology/ISIS3/raw/dev/isis/scripts/downloadIsisData.py actually 404s. :(

**Comment by michaelaye** [comment]
the curl command needs these options:
`curl -LJO ...`

**Comment by Kelvinrr** [comment]
@michaelaye 7.1RC_1 is the first version with the script. #5025 also fixes some issues that were in that version.

**Comment by foobarbecue** [comment]
looks like https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/scripts/downloadIsisData.py is a 404 because the .py was removed in 5e3f64f21ad98aaa05f517ba085b7d621c65a0ff , so https://github.com/USGS-Astrogeology/ISIS3/#how-do-i-access-the-isisdata-download-script-with-isis-700-or-earlier needs updating (maybe best to put a specific commit in the link)

**Comment by foobarbecue** [comment]
Also `python downloadIsisData.py sync <mission> $ISISDATA --config rclone.conf` is wrong. There doesn't seem to be a `sync` option.

**Comment by wterryf** [comment]
I'm working with the 7.1 RC1 distribution and have had some success in working with the downloadIsisData command. I'm wondering if there is some way to pass other config options to the rclone command. In particular, we maintain our own repositories for some of the kernels for MRO and TGO, so our current rsync scripts use --exclude clauses to skip these during the downloads.
