### ISSUE TITLE
Support for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by nschorgh** [DOI-USGS/ISIS3#5031]
Any chance to update the ISIS installation to work with Ubuntu 22.04 LTS rather than 18.04 LTS?

(I had some library conflicts with 22.04 and 20.04, so can confirm that it doesn't already work with those.)

**Comment by jessemapel** [comment]
I don't know if Ubuntu 22.04 is approved by the USGS for us to use yet. I'll look into what Ubuntu LTS versions we're allowed to use.

**Comment by jlaura** [comment]
@jessemapel As we transition to using more AWS infrastructure, we can get access to an ubuntu 22.04 build machine, so I do not believe that that will be an issue. The win here for us is that the build machine is both ephemeral and inside our VPC, so the security concerns are minimal as far as I am away. The larger issue is probably the linked QT update (which would be great to see completed).

**Comment by acpaquette** [comment]
Bump, Ubuntu 18.04 is reaching it's end of support in April which would likely be a good window to get this done

**Comment by amystamile-usgs** [comment]
@nschorgh What version of ISIS are you trying to install? Also what library conflicts are you running into?

I tested this and was able to build version 7.2.0 on Ubuntu 22.04 LTS.

**Comment by nschorgh** [comment]
> 
> I tested this and was able to build version 7.2.0 on Ubuntu 22.04 LTS.

Thanks! 
I'm currently on 22.04.2 LTS. It's been eight months since I tried last; I'll have to try again.

**Comment by amystamile-usgs** [comment]
@nschorgh I will go ahead and closed this issue for now. Please reopen if you still have issues installing on Ubuntu 22.04 LTS.
