### ISSUE TITLE
'galileo' missing from list of supported missions

### ISSUE THREAD

**Issue by mikebramble** [DOI-USGS/ISIS3#5038]
**ISIS version(s) affected**: 7.1.0

**Description**  
I'm attempting to install the Mission Specific Data Download for the Galileo mission and I receive a warning that 'galileo' is not found in the list of supported missions.

Error report:
```
Traceback (most recent call last):
  File "/Users/ ... /downloadIsisData", line 208, in <module>
    main(args.mission, args.dest, os.path.expanduser(args.config), args.dry_run, args.num_transfers)
  File "/Users/ ... /downloadIsisData", line 159, in main
    raise LookupError(f"{mission} is not in the list of supported missions: {supported_missions.keys()}")

LookupError: galileo is not in the list of supported missions: dict_keys(['apollo15', 'apollo16', 'apollo17', 'base', 'cassini', 'chandrayaan1', 'clementine1', 'dawn', 'hayabusa2', 'hayabusa', 'juno', 'kaguya', 'legacybase', 'lro', 'mariner10', 'messenger', 'mex', 'mgs', 'mro', 'near', 'newhorizons', 'odyssey', 'osirisrex', 'rolo', 'rosetta', 'smart1', 'tgo', 'viking1', 'viking2', 'voyager1', 'voyager2'])
```

As with issues #5024, #5027, and #5033, I was having an issue with the missing downloadIsisData utility. I updated to the release candidate which fixed that issue, but now I cannot use it to install the galileo mission specific data. It worked for the Partial Download of ISIS Base Data though.

**How to reproduce**  
New install of ISIS 7.1.0 on MacOS 12.5 using miniconda.
Using
`downloadIsisData galileo $ISISDATA`
returns the above error.

**Possible Solution**  
As the downloadIsisData utility is working for the base data, my guess would be that a data base issue omitted the galileo data somehow.

**Comment by Kelvinrr** [comment]
I've updated internally, I'll probably have a PR before the end of the week if everything goes well. Also noticed `lo` and `mer` were missed somehow too so those will be included.

**Comment by Kelvinrr** [comment]
closed by https://github.com/USGS-Astrogeology/ISIS3/pull/5042 

To can get the new script from dev:

```
# download the script and rclone config file
curl -LJO https://github.com/USGS-Astrogeology/ISIS3/raw/dev/isis/scripts/downloadIsisData

curl -LJO https://github.com/USGS-Astrogeology/ISIS3/raw/dev/isis/config/rclone.conf
```

feel free to reopen if you still are having issues.

**Comment by mikebramble** [comment]
I believe the issue still persists but now it is because 'galileo' is spelled incorrectly in the 'list of supported missions'. 

I get an error that returns the following as part of the error message:
`LookupError: galileo is not in the list of supported missions: dict_keys(['apollo15', 'apollo16', 'apollo17', 'base', 'cassini', 'chandrayaan1', 'clementine1', 'control', 'dawn', 'gallileo', 'hayabusa2', 'hayabusa', 'juno', 'kaguya', 'legacybase', 'lro', 'mariner10', 'mer', 'messenger', 'mex', 'mgs', 'mro', 'near', 'newhorizons', 'odyssey', 'osirisrex', 'rolo', 'rosetta', 'smart1', 'tgo', 'viking1', 'viking2', 'voyager1', 'voyager2'])
`

`gallileo` should be `galileo`

Also, while not related to the galileo issue, I see that `lo` is remains not on this list.
