### ISSUE TITLE
How  to start a new mission in ISIS3?

### ISSUE THREAD

**Issue by xwc2016** [DOI-USGS/ISIS3#5040]
We use Github issues solely for discussing bugs, documentation issues, and new features.

For
questions about using ISIS or other ASC software, please use
any of the support alternatives: https://astrodiscuss.usgs.gov or https://gitter.im/USGS-Astrogeology/IAA

A great resource about asking high quality questions that generate high quality answers is available from the StackOverflow community: [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)

Thanks!

**Comment by jessemapel** [comment]
Hi, we you will need to provide more information about what you are trying to do for us to help you. It sounds like you want to open an enhancement request to add a new mission. Please open a new issue with that template.

**Comment by jlaura** [comment]
@xwc2016 Feel free to email me at jlaura@usgs.gov if you are part of a mission team and looking to have your mission supported.
