### ISSUE TITLE
kernels downloaded with downloadIsisData out of date?

### ISSUE THREAD

**Issue by wterryf** [DOI-USGS/ISIS3#5041]
**ISIS version(s) affected**: 7.1.0_RC1

**Description**  
multiple mission kernels obtained with downloadIsisData seem to be out of date with respect to those downloaded via the current rsync method.

**How to reproduce**  
download data with downloadIsisData and with rsync and compare the files.

**Possible Solution**  

**Additional context**  
As one example, the most recent LRO CK moc42 kernel is from late last year (moc42r_2021304_2021335.bc), while rsync downloads a fairly recent one (moc42r_2022151_2022182.bc)

**Comment by Kelvinrr** [comment]
hmmm, the isis_data store we use internally (updated nightly using the same script) seems to contain both. 

```
(base) [ec2-user~]$ ls efs_prod/isis_data/lro/kernels/ck/moc42r_2021304_2021335_v02.bc 
efs_prod/isis_data/lro/kernels/ck/moc42r_2021304_2021335_v02.bc
(base) [ec2-user@~]$ ls efs_prod/isis_data/lro/kernels/ck/moc42r_2022151_2022182_v01.bc 
efs_prod/isis_data/lro/kernels/ck/moc42r_2022151_2022182_v01.bc
```

I can try lro with a fresh download and see if I can replicate. It maybe possible something is being clobbered on a fresh download.

**Comment by wterryf** [comment]
There is one other oddity, I get this error during TGO downloads:

ERROR : kernels/fk/kernels.0003.db/kernels.0003.db: Failed to copy: mkdir /data/isis3data/tgo/kernels/fk/kernels.0003.db: not a directory.

That file is definitely not a directory, there must be something odd on the remote side.

**Comment by Kelvinrr** [comment]
@wterryf Nothing odd looking at the remote right now. Can you send me the command you used? 

also, I believe #5042 might fix your other kernel issue. After that's merged I can send download instructions.

**Comment by Kelvinrr** [comment]
try redownloading the new scripts and config with: 

```
# download the script and rclone config file
curl -LJO https://github.com/USGS-Astrogeology/ISIS3/raw/dev/isis/scripts/downloadIsisData

curl -LJO https://github.com/USGS-Astrogeology/ISIS3/raw/dev/isis/config/rclone.conf
```

**Comment by wterryf** [comment]
OK, I'm running the new downloadIsisData script with the command:

downloadIsisData lro /tmp

It looks like it's going to take several more hours to run, I can let you know later how it comes out.

**Comment by wterryf** [comment]
OK, this took quite a while for the initial copy, but it looked like it worked, so that's great! Subsequent update runs go through quite quickly.

I also noticed the kwargs inclusion in the new version of the script and was able to pass some rclone exclude clauses from on end of the command line to exclude certain SPICE kernel directories.

So, I think this fixes all the issues I had with the downloadIsisData script, thanks so much for your help.

**Comment by jlaura** [comment]
@wterryf Thanks for being one of the first users/tester external to the dev group on this! We appreciate you taking the time to test this, open the issue, and iterate with us!

**Comment by Kelvinrr** [comment]
@wterryf good to hear the changes worked!
