### ISSUE TITLE
Expecting as many mapprojected images as cameras, and also a DEM

### ISSUE THREAD

**Issue by ldx119** [DOI-USGS/ISIS3#5044]
**ISIS version(s) affected**: x.y.z
ISIS version 7.0.0 
**Description**  

I want to run bundle_adjust for the some images with 'mapprojected-data' .  Here is my workflow command which are followed by the tutorial of '12.8 SfS with big illumination changes and comparison with LOLA': 
(1) parallel_stereo A_crop_sub4.cub B_crop_sub4.cub
run_stereo_noba_sub4/run --subpixel-mode 3
(2)point2dem --stereographic --proj-lon -5.7113 --proj-lat -85.0003 \
run_stereo_noba_sub4/run-PC.tif --tr 4
(3)for f in A B C D; do
        mapproject --tr 4 run_stereo_noba_sub4/run-DEM.tif \
        ${f}_crop_sub4.cub ${f}_crop_sub4.noba.tif
        --tile-size 1024
done
(4)mapped_images=$(echo {A,B,C,D}_crop_sub4.noba.tif)
dem=run_stereo_noba_sub4/run-DEM.tif
(5)bundle_adjust A_crop_sub4.cub B_crop_sub4.cub C_crop_sub4.cub
D_crop_sub4.cub
--mapprojected-data "$mapped_images $dem"
--num-iterations 100 --save-intermediate-cameras
--min-matches 1 --max-pairwise-matches 1000
-o run_ba_sub4/run

However the last step, it reports the error : Expecting as many mapprojected images as cameras, and also a DEM. 
[run-log-bundle_adjust-08-29-1148-47134.txt](https://github.com/USGS-Astrogeology/ISIS3/files/9441752/run-log-bundle_adjust-08-29-1148-47134.txt)

How should I solve the issue?  Tanks  :)

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by jessemapel** [comment]
This looks like an ASP error and not an issue with ISIS.

Glancing at your log it looks like you passed in A_crop_sub4.noba.tif instead of A_crop_sub4.noba.cub

bundle_adjust **A_crop_sub4.noba.tif** B_crop_sub4.cub C_crop_sub4.cub D_crop_sub4.cub --mapprojected-data "A_crop_sub4.noba.tif B_crop_sub4.noba.tif C_crop_sub4.noba.tif D_crop_sub4.noba.tif run_stereo_noba_sub4/run-DEM.tif" --num-iterations 100 --save-intermediate-cameras --min-matches 1 --max-pairwise-matches 1000 -o run_ba_sub4/run

**Comment by jessemapel** [comment]
Closing as not an ISIS issue, feel free to keep discussing it here if you would like though. Ross and Oleg sometimes watch the ISIS issues, but you'll get better traction on their support methods.

**Comment by ldx119** [comment]
> This looks like an ASP error and not an issue with ISIS.
> 
> Glancing at your log it looks like you passed in A_crop_sub4.noba.tif instead of A_crop_sub4.noba.cub
> 
> bundle_adjust **A_crop_sub4.noba.tif** B_crop_sub4.cub C_crop_sub4.cub D_crop_sub4.cub --mapprojected-data "A_crop_sub4.noba.tif B_crop_sub4.noba.tif C_crop_sub4.noba.tif D_crop_sub4.noba.tif run_stereo_noba_sub4/run-DEM.tif" --num-iterations 100 --save-intermediate-cameras --min-matches 1 --max-pairwise-matches 1000 -o run_ba_sub4/run

Thanks , jessemaple . I change from the A_crop_sub4.noba.tif to A_crop_sub4.noba.cub , it runs well .

**Comment by ldx119** [comment]
> ep di

Sorry  jessemaple ，I would like to ask a question about the latest version 0.8.7 ale  compilation by the way . I follow the step by the 'https://github.com/USGS-Astrogeology/ale' of Buliding Ale . However , it  appears some problem in the last step which is '
<img width="365" alt="error-when-make" src="https://user-images.githubusercontent.com/100507049/187324085-cea1d8fd-55de-4109-91b1-0dd657cd469a.png">' 

Previous step is " cmake .. "
<img width="397" alt="cmake-ale(0 8 7)" src="https://user-images.githubusercontent.com/100507049/187325308-4a785f77-3ec1-4bae-8d13-57b2380f3dcd.png">

I've also searched for some blogs to fix this problem, but none of them worked .
I know this question is stupid , but it really bothered me for a long time, thank you very much for your reply .

**Comment by jessemapel** [comment]
It looks like you need to initialize the gtest sub-module. Run `git submodule update --init --recursive` and then re-run cmake and build.

You can also build it without tests by setting `ALE_BUILD_TESTS=OFF` at the cmake step. So, it would be `cmake -DALE_BUILD_TESTS=OFF ../`

**Comment by ldx119** [comment]
> It looks like you need to initialize the gtest sub-module. Run `git submodule update --init --recursive` and then re-run cmake and build.
> 
> You can also build it without tests by setting `ALE_BUILD_TESTS=OFF` at the cmake step. So, it would be `cmake -DALE_BUILD_TESTS=OFF ../`

Thanks very much for your advice .  I have chosen the second command build without tests. I have built target ale successfully .
However ,  I want to use csm camera models , and then create ".json"  files use the script named gen_json.py . 
Firstly , I use the command "isd_dict=load"(/home/ldx/StereoPipeline-3.1.1-alpha-2022-07-22-x86_64-Linux/examples/LRO/WAC_Original_Image/M119923055ME)" and ''isd_string=loads"(/home/ldx/StereoPipeline-3.1.1-alpha-2022-07-22-x86_64-Linux/examples/LRO/WAC_Original_Image/M119923055ME)" 
then I use "python gen_json.py M119923055ME.vis.even.cub"

![nosuchD](https://user-images.githubusercontent.com/100507049/187706725-6d0d9a9e-9fc9-4da6-87d2-f979c8ca432f.png)

![py_json](https://user-images.githubusercontent.com/100507049/187707510-f69064b0-af8b-4c97-af89-25a95c89ac93.png)

it reports: "Exception: No Such Driver for Label"

How should I fix this problem? Thanks a lot for your help :) :)
