### ISSUE TITLE
'galileo' spelled incorrectly on the list of supported missions 

### ISSUE THREAD

**Issue by mikebramble** [DOI-USGS/ISIS3#5045]
**ISIS version(s) affected**: 7.1.0

**Description**  
This issue builds off of troubleshooting for Issue #5038. I am unable to install the galileo mission data using DownloadIsisData. Previously this is because galileo was accidentally dropped from the list of supported missions. Now it appears to be because 'galileo' spelled incorrectly on the list of supported missions 

**How to reproduce**  
Running `downloadIsisData galileo $ISISDATA` returns the following:

```
Traceback (most recent call last):
  File ".../envs/isis/bin/downloadIsisData", line 208, in <module>
    main(args.mission, args.dest, os.path.expanduser(args.config), args.dry_run, args.num_transfers)
  File ".../envs/isis/bin/downloadIsisData", line 159, in main
    raise LookupError(f"{mission} is not in the list of supported missions: {supported_missions.keys()}")
LookupError: galileo is not in the list of supported missions: dict_keys(['apollo15', 'apollo16', 'apollo17', 'base', 'cassini', 'chandrayaan1', 'clementine1', 'control', 'dawn', 'gallileo', 'hayabusa2', 'hayabusa', 'juno', 'kaguya', 'legacybase', 'lro', 'mariner10', 'mer', 'messenger', 'mex', 'mgs', 'mro', 'near', 'newhorizons', 'odyssey', 'osirisrex', 'rolo', 'rosetta', 'smart1', 'tgo', 'viking1', 'viking2', 'voyager1', 'voyager2'])
```

**Possible Solution**  
`gallileo` should be `galileo` on the list of supported missions for `DownloadIsisData.`

Also, while not related to the galileo issue, I see that `lo` remains not on this list.

**Comment by Kelvinrr** [comment]
This is what happens when a lot of changes go into something on a short period of time. Should be taken care of now.
