### ISSUE TITLE
Phobos kernels no longer available

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5049]
**ISIS version(s) affected**: isis7.1.0-RC1

**Description**  
What worked yesterday no longer works today.  After ingestion, spicing a Phobos SRC image results in the following:

```
  Group = Error
    Program = spiceinit
    Code    = 1
    Message = "No existing files found with a numerical version matching
               [kernels.????.db] in
               [/usgs/cpkgs/isis3/isis_data/mex/kernels/ik]"
    File    = FileName.cpp
    Line    = 669
  End_Group
```

**How to reproduce**  
Run spiceinit (all defaults) on Phobos SRC image.
See my work users area Isis3Tests/MEX_SRC/tmp for a file and failure.

Spicinit also fails on Phobos HRSC images.

There is an SRC (H0715_0004_SR2.cub) and HRSC (HI418_0000_ND2.cub) in that directory.

**Comment by Kelvinrr** [comment]
Should be fixed. Check again when you get the chance.

**Comment by lwellerastro** [comment]
@Kelvinrr, I'm getting a similar, but different error (ik above, iak now):

    Message = "No existing files found with a numerical version matching
               [kernels.????.db] in
               [/usgs/cpkgs/isis3/isis_data/mex/kernels/iak]"

This is the problem:
 ls /usgs/cpkgs/isis3/isis_data/mex/kernels/iak
ls: cannot access /usgs/cpkgs/isis3/isis_data/mex/kernels/iak: No such file or directory

There is a directory with no name under kernels/, was that suppose to be iak/?
ls -l /usgs/cpkgs/isis3/isis_data/mex/kernels/
total 84
-rwxr-xr-x 1 1000 1000 11913 Dec 31  1969 ．
drwxr-xr-x 2 1000 1000 22528 Sep 17 05:15 ck
drwxr-xr-x 2 1000 1000  6144 Sep 15 10:38 fk
drwxr-xr-x 2 1000 1000  6144 Sep 15 11:18 ik
drwxr-xr-x 2 1000 1000  6144 Sep 15 11:23 sclk
drwxr-xr-x 2 1000 1000 43008 Sep 17 05:50 spk

**Comment by Kelvinrr** [comment]
I was able to solve the problem. The second comment by Lynn was the iak being ignored by the command I used because of the path being butchered before being fed into rsync.
