### ISSUE TITLE
Unable to spiceinit Kaguya TC data using new data area

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5053]
**ISIS version(s) affected** :isis7.0.0

**Description**  
Errors are thrown by spiceinit for Kaguya TC images that have previously succeeded.  I believe this is due to changes made to the new isis data area 

**How to reproduce**  
spiceinit from=TC1S2B0_01_05568S715E1334.cub

Error                     = "No pointing available at requested time
                                 [284580999.02509] for frame code [31001]"

    Message = "Unable to initialize camera model"

However, when pointing to isis3_old/isis_data the program works as expected. 

Please let me know if you need data to apply this to.
 
**Possible Solution**  
Confirm all kernels and directories have been transferred properly to the cloud and back to local directories. 

**Additional context**

**Comment by Kelvinrr** [comment]
I can try to replicate and see what is happening, but from peaking at the new data area, the new area is actually a superset of what is in `isis3_old`. So i dont think this is a missing data issue.

**Comment by lwellerastro** [comment]
Well, the old area has tspk/ directory but the new area does not:

ls ../isis3_old/isis_data/kaguya/kernels/
ck  fk  iak  ik  pck  sclk  spk  tspk

ls ../isis3/isis_data/kaguya/kernels/
ck  fk  iak  ik  pck  sclk  spk

**Comment by Kelvinrr** [comment]
When I saw pointing I only imagined ck might have been an issue. The command I used to copy over kernels wasn't recursively going over missing folders, just files. re-running the nightly job with the missing folders so some of these should be cleared up sometime today or tomorrow, depending on how long it takes.

**Comment by Kelvinrr** [comment]
nightly completed, try again when you get the chance

**Comment by lwellerastro** [comment]
Spiceinit now works and matches old_isis output.  Thanks!
