### ISSUE TITLE
spiceinit error with Galileo data

### ISSUE THREAD

**Issue by criggall** [DOI-USGS/ISIS3#5054]
**ISIS version(s) affected**: 7.0.0

**Description**  
Running spiceinit locally, having downloaded both the base and Galileo ISIS datasets, results in the following error:
`Spice file does not exist [$ISISDATA/galileo/kernels/spk/s000131a.bsp]`
After downloading the s000131a.bsp file from here: [Index of /pub/naif/GLL/kernels/spk](https://naif.jpl.nasa.gov/pub/naif/GLL/kernels/spk/), the following error is encountered when spiceinit is run: 
`An unknown NAIF error has been encountered. The short explanation provided by NAIF is [SPICE(DAFBEGGTEND)]. The Naif error is [Beginning address (151385833) greater than ending address (151385832).]`

**How to reproduce**  
`spiceinit from=image.cub`

**Comment by lwellerastro** [comment]
Please also refer back to this astrodiscuss post for further information: https://astrodiscuss.usgs.gov/t/adding-spice-data-to-galileo-ssi-images-of-europa/896

**Comment by Kelvinrr** [comment]
@criggall There was a bug with the old version of the script where Galileo kernels were not downloaded. Can you try again using the latest version of the script from the dev repo? The new script should come with the next release but you can get it now with: 

```
# download the script and rclone config file
curl -LJO https://github.com/USGS-Astrogeology/ISIS3/raw/dev/isis/scripts/downloadIsisData

curl -LJO https://github.com/USGS-Astrogeology/ISIS3/raw/dev/isis/config/rclone.conf**
```

**Comment by Kelvinrr** [comment]
Looking more into it, I think this is the same as https://github.com/USGS-Astrogeology/ISIS3/issues/5056, should be handled now. Let me know if its still a problem after updating the Galileo data.

**Comment by criggall** [comment]
After downloading the script and new rclone config file, how do I update the Galileo data? I tried `python downloadIsisData galileo $ISISDATA --config rclone.conf**` but received an error, so I assume I did this incorrectly. Thank you so much!

**Comment by Kelvinrr** [comment]
@criggall can you post the error? Preferably with the complete call stack.

**Comment by criggall** [comment]
It runs for about a minute and outputs the same error for each file. The final message says "Failed to copy with 443 errors: last error was: mkdir /home/ccrig/rclone.conf**: not a directory."

**Comment by jlaura** [comment]
@criggall What are the `**` characters at the end of the command? If you remove those, does this work as expected?

**Comment by criggall** [comment]
I redownloaded the files from the script above and tried without the ** and it worked. Thank you!
