### ISSUE TITLE
Unable to spiceinit Galileo images using new data area

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5056]
**ISIS version(s) affected**: isis7.0.0

**Description**  
Errors are thrown by spiceinit for Galileo SSI images that have previously succeeded. I believe this is due to changes made to the new isis data area

**How to reproduce**  
```
spiceinit from=5000r.cub

    Error                     = "An unknown NAIF error has been encountered.
                                 The short explanation provided by NAIF is
                                 [SPICE(DAFBEGGTEND)]. The Naif error is
                                 [Beginning address (151385833) greater than
                                 ending address (151385832).]"
  End_Group

  Group = Error
    Program = spiceinit
    Code    = 1
    Message = "Unable to initialize camera model"
    File    = spiceinit.cpp
    Line    = 262
  End_Group
```
This runs successfully when pointing to the old data area.

There is a file under my work user area Isis3Tests/Spiceinit/NewDataArea/Galileo/ that can be used for testing.

**Comment by Kelvinrr** [comment]
This one is weird. There was no missing kernel but there was a difference in one CK compared to the archive. It's a USGS CK, not a naif one, I think at some point got corrupted along the way? I restored it and spiceinit went fine. Try again when you get the chance.

**Comment by lwellerastro** [comment]
This looks good @Kelvinrr.  I also tested our smithed kernels (cksmith=true) and those work as expected as well.  Thank you!
