### ISSUE TITLE
spiceinit requests LRO clock kernel not in isisdata

### ISSUE THREAD

**Issue by tllogan** [DOI-USGS/ISIS3#5058]
Hi,
**Description** 
spiceinit is requesting an LRO clock correction file (lro_clkcor_2022263_v00.tsc) that appears to be unavailable from isisdata.
**Possible Solution** 
Please add the new clock correction kernel to isisdata, or rollback the spiceinit library to the previous clock file.
**Error Messages**
rsync: link_stat "/data/lro/kernels/sclk/lro_clkcor_2022263_v00.tsc" (in isisdata) failed: No such file or directory 
Command '['rsync', '-lptgoD', 'isisdist.astrogeology.usgs.gov::isisdata/data/lro/kernels/sclk/lro_clkcor_2022263_v00.tsc', '/home/tllogan/.spice_cache/lro/kernels/sclk/lro_clkcor_2022263_v00.tsc']' returned non-zero exit status 23.
Thank you,
Tom Logan

**Comment by jessemapel** [comment]
Can you check that your local data area is up to date? When I look for the kernel with rclone it appears to be available:

```
jmapel$ rclone --config config/rclone.conf ls asc_s3:asc-isisdata/usgs_data/lro/kernels/sclk/lro_clkcor_2022263_v00.tsc
  1954590 lro_clkcor_2022263_v00.tsc
```

**Comment by tllogan** [comment]
Hi Jesse,
Just to be sure my local data kernels are up-to-date, I downloaded them all again from:

isisdist.astrogeology.usgs.gov::isis3data/data/lro

I can confirm that the desired file (sclk/lro_clkcor_2022263_v00.tsc) is not provided. The last one is dated 2022208.

How do files in the s3 bucket get moved to the isis data download site?

I also discovered that the “/iak/lro_instrumentAddendum_v05.ti” kernel is also missing.

What’s the next step?

Thank you,


From: Jesse Mapel ***@***.***>
Reply-To: USGS-Astrogeology/ISIS3 ***@***.***>
Date: Tuesday, October 11, 2022 at 8:19 AM
To: USGS-Astrogeology/ISIS3 ***@***.***>
Cc: "Logan, Thomas L (US 398E)" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [USGS-Astrogeology/ISIS3] spiceinit requests LRO clock kernel not in isisdata (Issue #5058)


Can you check that your local data area is up to date? When I look for the kernel with rclone it appears to be available:

jmapel$ rclone --config config/rclone.conf ls asc_s3:asc-isisdata/usgs_data/lro/kernels/sclk/lro_clkcor_2022263_v00.tsc

  1954590 lro_clkcor_2022263_v00.tsc

**Comment by jlaura** [comment]
@tllogan It looks like you are attempting to pull data from the rsync server. The rsync server is no longer being updated and will be officially deprecated at the end of November 2022. Please see the [ISIS Data Area](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#the-isis-data-area) section of the README for instructions on using the new download script and #5026 for a discussion related to the announcement.

You will also see that @jessemapel used a straight `rclone` command to check for the kernel in question and that was targeting the new data download location (in this case, an S3 bucket).

**Comment by jessemapel** [comment]
I'm going to close this for now. If you you have further issues withe download script please reply here and we can re-open this issue.
