### ISSUE TITLE
Add kernels for MSL MastCam to ISiS Data

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#5059]
**Description**  

We are working add add support for MSL MastCam to USGSCSM and we want to use ISIS for image processing and generating panoramas. So, it would be much easier for us, if we could use the existing ISIS data download tools to download the MSL kernels required to generate an ISD for MastCam imagery.

**Example**  

Add a new target to the DownloadIsisData rclone config that will download the required kernels for processing MSL MastCam imagery into `$ISISDATA/MSL/kernels`. This does not require kernel.db files as we will not be using spiceinit, but it would be helpful if there was a way to more easily specify the kernels to use with Ale.load(s).

**Comment by amystamile-usgs** [comment]
Kernels added to isis data area. This includes a metakernel with the list of kernels associated to the msl test data.
