### ISSUE TITLE
Add surface point centered cylindrical projection

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#5060]
**Description**  

In grounded imagery, it is often useful to work in a camera or rover centered azimuth/elevation projection. This allows for easy generation of mosaics from multiple images taken from the same position.

See, 5.2.12.3 of the [MER SIS](https://pds-geosciences.wustl.edu/mer/mer1-m-pancam-2-edr-sci-v1/mer1pc_0xxx/document/camera_dpsis.pdf) for more specifics of this projection.

**Example**  

I would like for this to be added to ISIS's existing projection engine so that we can make use of the existing cam2map, automos, etc. applications. The projection should require the surface point to center the projection on, and the angular resolution in both azimuth and elevation. It would also be helpful to allow users to define where the azimuth and elevation are relative to, but it is also acceptable to use North as the azimuth relative direction and the local ellipsoid tangent as 0 elevation.

**Comment by AustinSanders** [comment]
This is in line with ongoing CSM work and should remain active
