### ISSUE TITLE
Embree ray tracing does not recognize file extension

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5064]
**ISIS version(s) affected**: isis7.1.0

**Description**  
Applications throw the following error for DSK initialized MEX HRSC and SRC images when trying to use the embree ray tracing engine:

`[pcl::io::load] Don't know how to handle file with extension .BDS`

This was discovered for already spiced data with the shape model, but as demonstrated below will also occur when running spiceinit.  In that case, spiceinit runs, the error/warning is thrown and the shape model is written to label, but not the ray tracing engine keyword.  It seems other applications run as well, but I did have a case where one outright failed, but I'll need to find that.

What's not clear is if embree is being used or not.  I can't tell.

**How to reproduce**  
An ingested (and now spiced) SRC image, DSK shape model and preference file are available under my work users directory in Isis3Tests/RayTracing/Embree. 

The error can be reproduced by running spiceinit in the following manner:

`spiceinit from=H0748_0003_SR2.lev0.cub shape=user model=PHOBOS_K275_DLR_V02.BDS -preference=IsisPreferences_Embree`

**Comment by jessemapel** [comment]
It looks like the embree code is not doing a case insensitive comparison here:

https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/EmbreeTargetShape/EmbreeTargetShape.cpp#L282

It's also catching the PCL exception somewhere else as that try catch block is only catching and IException.

**Comment by lwellerastro** [comment]
`It looks like the embree code is not doing a case insensitive comparison here:`

I changed the DSK filename to PHOBOS_K275_DLR_V02.bds in a subdirectory and ran spiceinit again and it ran, and RayTracingEngine = embree

This particular DSK was pulled directly from an ESA archive so having the software be case insensitive is probably a good idea.
