### ISSUE TITLE
ISIS7.1.0 libgsl linking issue

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#5067]
**ISIS version(s) affected**: 7.1.0

**Description**  
Post install, using any ISIS codes results in a linking error to libgsl.so.27.

**How to reproduce**  
Install on a linux machine and run something like `spiceinit -h`

**Possible Solution**  
`mamba install -c conda-forge gsl=2.7=he838d99_0`

**Additional context**

**Comment by jessemapel** [comment]
What version of gsl are you getting when you do an install? Can you also post the specific linking error? It is pinned to gsl 2.7 already:

```
cbash-4.2$ conda search -c usgs-astrogeology isis=7.1 --info
Loading channels: done
isis 7.1.0 0
------------
file name   : isis-7.1.0-0.tar.bz2
name        : isis
version     : 7.1.0
build       : 0
build number: 0
size        : 15.7 MB
license     : CC0-1.0
subdir      : linux-64
url         : https://conda.anaconda.org/usgs-astrogeology/linux-64/isis-7.1.0-0.tar.bz2
md5         : 2a314aab62da47801b7e9ac33532c951
timestamp   : 2022-09-23 02:39:58 UTC
dependencies: 
  - ale >=0.8.6,<1.0a0
  - aom >=3.4.0,<3.5.0a0
  - armadillo >=11.4,<12.0a0
  - blas
  - boost >=1.72.0,<1.73.0a0
  - boost-cpp >=1.72.0,<1.73.0a0
  - bullet >=2.86.1,<2.87.0a0
  - bz2file
  - bzip2 >=1.0.8,<2.0a0
  - csm
  - cspice
  - curl
  - eigen
  - embree
  - ffmpeg >=4.4,<5.0a0
  - ffmpeg >=4.4.2,<5.0a0
  - geos >=3.7,<3.8.0a0
  - geotiff >=1.7.1,<1.8.0a0
  - gmp >=6.2.1,<7.0a0
  - gsl >=2.7,<2.8.0a0
  - hdf5 >=1.12.2,<1.12.3.0a0
  - icu >=70.1,<71.0a0
  - inja
  - jama
  - jasper >=2.0.33,<2.1.0a0
  - jpeg >=9e,<10a
  - kakadu >=1,<2.0a0
  - krb5 >=1.19.3,<1.20.0a0
  - libcxx
  - libopenblas
  - libopencv >=4.6.0,<4.7.0a0
  - libpng >=1.6.38,<2.0a0
  - libprotobuf >=3.21.5,<3.22.0a0
  - libsqlite >=3.39.3,<4.0a0
  - libtiff
  - libxml2 >=2.9.14,<2.10.0a0
  - libzlib >=1.2.12,<1.3.0a0
  - mesalib
  - mysql
  - mysql-connector-c >=6.1.11,<6.1.12.0a0
  - nanoflann
  - nlohmann_json
  - nn
  - opencv >=4.6.0,<4.7.0a0
  - openssl >=1,<1.2.0a0
  - pcl
  - protobuf >=4.21.5,<4.22.0a0
  - qhull >=2020.2,<2020.3.0a0
  - qt >=5.15.4,<5.16.0a0
  - qwt >=6.2.0,<6.3.0a0
  - suitesparse >=5.10.1,<6.0a0
  - superlu
  - tnt
  - x264 >=1!164.3095,<1!165
  - x265 >=3.5,<3.6.0a0
  - xerces-c >=3.2.3,<3.2.4.0a0
  - xerces-c >=3.2.3,<3.3.0a0
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxi
```

**Comment by jlaura** [comment]
Here is the linking error: `spiceinit: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory`. I'll have to create a new env and installation to see what version is going in. I would bet that it is version 2.7.1 (which only provides libgsl.so.27) and not 2.7.0 which provides libgsl.so.25.

**Comment by AustinSanders** [comment]
@jlaura  I'm not able to reproduce this error with a fresh conda environment / build of ISIS from dev.  I'm on MacOS 12.6.1 (Monterey).  I'm not sure if that makes a difference, but I do recall you being on a different version of OS.

Can you dump the contents (or relevant portion of contents) of a ```conda list```?

**Comment by jlaura** [comment]
I fixed it locally with the command above hard coding the libgsl version. I bet the package was fixed upstream. Since you can't reproduce and I have a modified environment, I am going to close. This can reopen if needed in the future.

**Comment by acpaquette** [comment]
This has become an issue on the isis7.2.0-RC1 builds that I thought I had fixed
