### ISSUE TITLE
Updates to ISIS main page

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#5073]
The site https://isis.astrogeology.usgs.gov/ does not mention latest ISIS, which is version 7, but only version 6 and below. (See left sidebar.)

It is also about time it stops mentioning ISIS 2 (20 years too late?). Or at least it should add the word "historical" before mentioning it in the sidebar. Otherwise folks may think that there's something called ISIS, and version 2 is latest and greatest.

**Comment by acpaquette** [comment]
:+1: We largely keep ISIS 2 prevalent as it has features that were never ported to ISIS 3+, but it could be made more obvious that it is a legacy verison
