### ISSUE TITLE
ISIS 7.0.0 and above cannot find libcpsice.so.66

### ISSUE THREAD

**Issue by Hyradus** [DOI-USGS/ISIS3#5080]
**ISIS version(s) affected**: 7.0.0 and above (probably also 6.0.0 and above)

**Description**  
Installed ISIS 7.0.0+ in a fresh conda environment with python 3.7+, installation and initialization is working correctly but is not possible to execute any isis command because of missing **libcspice.so.66** error.
The same happens if using docker.

**How to reproduce**  
Following the guidelines in the main repository readme.
```
conda create -n isis
conda activate isis
conda config --env --add channels conda-forge
conda config --env --add channels usgs-astrogeology
conda config --env --add channels usgs-astrogeology
conda install -c usgs-astrogeology isis=7.0.0
python $CONDA_PREFIX/scripts/isisVarInit.py
```
Then launching any ISIS command (e.g. lronaccal) results in libcspice.so.66 missing error.

**Possible Solution**  
This is a temporary solution that I have found.
In **/opt/conda/envs/isis/lib/** there is a **libcspice.so** so I have renamed in **libcspice.so.66** with:
```
mv /opt/conda/envs/isis/lib/libcspice.so /opt/conda/envs/isis/lib/libcspice.so.66 
```
Now all ISIS commands works flawlessly both in normal conda env and in docker with custom envs.

**Additional context**  
Tested on Ubuntu 22.04, Arch Linux, latest kernels, conda, and docker versions.

**Comment by jlaura** [comment]
Just installed 6.0.0 on a machine and can confirm. I see libcspice.67.so being install, but not 66.

`spiceinit: error while loading shared libraries: libcspice.so.66: cannot open shared object file: No such file or directory`

Non-destructive work around is: `ln -s <envpath>/lib/libcspice.so <envpath>/lib/libcspice.so.66`

**Comment by jlaura** [comment]
This broke because of a downstream update to [cspice](https://github.com/conda-forge/cspice-feedstock/issues/33). If the maintainers over there won't re-release, I think we are going to have to re-release with a version pinned or release pointing to the updated cspice lib. :-1:

**Comment by Hyradus** [comment]
Oh, ok, so as far as I have understood this is a problem related to cpsice package that is creating libcspice.so or libcpsice.so.67, instead of libcspice.so.66, right?

And the main solutions are:
* Re-releasing all ISIS versions, pointing to any of those 3 versions of libcspice.so (cumbersome)
* Have a fix from cpsice-side, right? (best one)
* Create a symbolic link between libcspice.so/.67 to libcspcie.so.66 (temporary and not automated)

Anyway, thanks for looking for this!

**Comment by AndrewAnnex** [comment]
@Hyradus @jlaura I lay out three solutions in https://github.com/conda-forge/cspice-feedstock/issues/33, the last solution I think is the more correct solution and wouldn't actually require new versions to be released (just new builds via the build number increment). I don't think that solution is all that cumbersome, but I also laid out an option where I make a new build for cspice with an additional symlink created just for libcspice.so.66, which to be clear would still be n67 cspice as it has been for the better part of a year now. I'll make the pr for this latter change in the meantime but I think that ISIS should release new builds to pin to older versions of cspice which I don't think would be too difficult as they technically aren't releases.

**Comment by jlaura** [comment]
@AndrewAnnex  Thanks for the symbolic link on the cspice side! I'll get with the other devs and see what we can do to increment the build number and get versions pushed. We are still going to have to create these builds and push them (which is the time consuming part), but I'll if we can do this in the coming week or so.

Again, thanks for the release with the (erroneous) symbolic link.

**Comment by Hyradus** [comment]
@AndrewAnnex @jlaura many thanks!

Since the solution has been found and needs only to be implemented, I'll close this issue.
