### ISSUE TITLE
Error in downloading MRO kernals

### ISSUE THREAD

**Issue by nayamas** [DOI-USGS/ISIS3#5084]
I was trying to download the mro kernels by using the following code
rsync -azv --delete --partial [isisdist.astrogeology.usgs.gov](http://isisdist.astrogeology.usgs.gov/)::isis3data/data/base/kernels/spk
It shows an error such as "rsync: failed to connect to [isisdist.astrogeology.usgs.gov](http://isisdist.astrogeology.usgs.gov/) (184.164.152.106) : connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Reciever=3.1.0]

How can I solve this problem?
Please help me out with this. Its really urgent for me to continue my work

**Comment by jlaura** [comment]
@nayamas It looks like you are attempting to use the rsync servers which either have been shut down or will be shutting down by the end of the month. Please take a look at the README which contains instructions on [downloading the ISIS data area](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#The-ISIS-Data-Area) using the `downloadIsisData` script.

For MRO and versions of ISIS greater than 4.1.0 you will need to use: `downloadIsisData mro $ISISDATA` where you have set the ISISDATA environment variable to the location where you want the kernels.

**Comment by nayamas** [comment]
thank you so much

**Comment by jlaura** [comment]
Looks like this is solved. I am going to close. If you have additional issues with downloading MRO please reopen.
