### ISSUE TITLE
Spiceinit on Rosetta OSIRIS NAC images

### ISSUE THREAD

**Issue by abhinav-s-jindal** [DOI-USGS/ISIS3#5093]
**ISIS version(s) affected**: 6.0.0

**Description**  
I am trying to use spiceinit on Rosetta OSIRIS NAC images using the “Use the ISIS SPICE Web Service” for the SPICE Data. this works perfectly for images from early in the mission (~Sept 2014), but seems to fail for images from later (~June 2016). I get the following error:
“ERROR The Spice Server was unable to initialize the cube. The error reported was: No Camera Kernel found for the image [/tmp/spice_web_service/q_mQsBXwx3].”

If I enable CKPREDICTED & SPKPREDICTED, it does seem to find kernels to attach, however, these seem inaccurate. The lat/lon values generated are completely off, while they match perfectly for different images from 2014 (such that I can use cam2map and see perfect alignment).

Is there a way to update the ISIS SPICE Web Service to have the latest kernels? Alternatively is it possible to add more than one kernel per category using override of system kernels?

The original .IMGs files (for both images from 2014 and 2016) were downloaded from the [Rosetta PSA](https://archives.esac.esa.int/psa/#!Table%20View/Rosetta=mission) and converted to cubs using rososiris2isis.

**How to reproduce**  
> rososiris2isis from=N20160613T181907795ID30F22.IMG to=N20160613T181907795ID30F22.cub
> spiceinit from=N20160613T181907795ID30F22.cub web=yes shape=user model=~ISISDATA/rosetta/kernels/dsk/ROS_CG_M003_OSPCLPS_N_V1.bds

Output:
>spiceinit: Requesting Spice Data
>QIODevice::write (QTcpSocket): device not open
>100% Processed
>**ERROR** The Spice Server was unable to initialize the cube.  The error reported was: No Camera Kernel found for the image [/tmp/spice_web_service/P6_Jk7JqRI].

**Possible Solution**  
Seems like ISIS SPICE Web Service needs to be update to have the latest kernels for Rosetta.

**Additional context**  
Posted on [Astrodiscuss](https://astrodiscuss.usgs.gov/t/spiceinit-on-rosetta-osiris-nac-images/920)

**Comment by jlaura** [comment]
@abhinavjindal93  Have you tried downloading the kernels locally? What is the result of that test?

**Comment by lwellerastro** [comment]
I have reproduced the error on a local system using isis7.1.0.  

I also ran spice pointing to the isis3_old/isis_data/ data location and the file is properly initialized (nNo serial number though, which relates to another post by the same author). Maybe something didn't get migrated to the new data area?

**Comment by abhinav-s-jindal** [comment]
Yes, I downloaded the most up to date SPICE kernels from: http://spiftp.esac.esa.int/data/SPICE/ROSETTA/kernels/, and attempted to use "User Override of System Kernels"  in "spiceinit" for the "N20140916T150900365ID30F22" OSIRIS NAC image. Here is a list of kernels I use:

>Group = Kernels
 > NaifFrameCode             = -226111
 > LeapSecond                = kernels/lsk/naif0012.tls
 > TargetAttitudeShape       = kernels/pck/ROS_CG_RAD_V10.TPC
 > TargetPosition            = kernels/spk/CORB_DV_257_03___T19_00345.bsp
 > InstrumentPointing        = (kernels/ck/ROS_SC_REC_140801_141231_V01.BC,
 >                              kernels/fk/ROS_V38.tf)
 > Instrument                = kernels/ik/ROS_OSIRIS_V17.ti
 > SpacecraftClock           = kernels/sclk/ROS_160929_STEP.TSC
 > InstrumentPosition        = kernels/spk/RORB_DV_257_03___T19_00345.BSP
 > InstrumentAddendum        = kernels/iak/osi_nacAddendum_v004.ti
 > ShapeModel                = kernels/dsk/cg-dlr_spg-shap7-v1.0_4Mfacets.-
                              bds
 > InstrumentPositionQuality = Unknown
 > InstrumentPointingQuality = Unknown
 > CameraVersion             = 2
 > Error                     = "The ck rotation from frame -1000012000 can not
 >                              be found due to no pointing available at
 >                              requested time or a problem with the frame"
>End_Group

However, this ends up giving an error: 

"The ck rotation from frame -1000012000 can not be found due to no pointing available at requested time or a problem with the frame"

Alternatively, when I enable “Use the ISIS SPICE Web Service” for this same image, it initialises some extra kernels and works (note that using the SPICE Web Service still fails for OSIRIS NAC images from Late 2016). However, "spiceinit" does not seem to allow multiple pointing kernels, so I am not sure how I can add these extra kernels while having  "User Override of System Kernels" enabled.
