### ISSUE TITLE
Questions when generate geometric projection for THEMIS IR image 

### ISSUE THREAD

**Issue by SherryCampbell** [DOI-USGS/ISIS3#5096]
I am trying to project THEMIS IR-RDR data so that it could have the same projection information as VIS-LOC.

I tried to generate geometric projection using  ISIS7.0.0,  through command thm2isis, spiceinit, maptemplate and cam2map, but the spiceinit reported" I/O ERROR unable to open [.cub]" or "No existing files found with a numerial version matching [kernels.????.db]"(qview could open the .cub image)
I also tried to use  command thmpro, another error occurred as "PVL Keyword[Class] does not exist in [Group = Error]"

 People on ASC said that might be a problem with ISIS  setup due to issue with the data area, how can I solve this?

**Comment by AustinSanders** [comment]
Hi @SherryCampbell,

I'm not able to reproduce this issue, and I agree that it may be an issue with the ISIS setup / data area.

Do you have a copy of all relevant kernels downloaded locally?  Instructions for cloning the data area can be found [here](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#the-isis-data-area).

Alternatively, you might try using the "web" option in spiceinit.  It will use the spice web server and attach the relevant spice information to the resulting .cub.  Documentation for the web option can be found [here](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/spiceinit/spiceinit.html)
