### ISSUE TITLE
lronaccal in ISIS 7.1.0

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#5097]
The lronaccal program in ISIS 7.1.0 produces a black image. I managed to make it be non-black only by running this command as:

~/miniconda3/envs/isis7/bin/lronaccal from=run/M120168714LE.cub to=run/M120168714LE.lronaccal.cub -verbose dark = false masked=false flatfield=false radiometric=false Nonlinearity=false 

There is no warning and no other message about what is going on. Any thoughts?

**Comment by lwellerastro** [comment]
I can confirm lronaccal no longer works properly under isis7.1.0.  Output looks ok under isis7.0.0 so I compared the Radiometry Group information for both and saw a couple of differences, namely the DarkFile used and the SolarDistance which makes no sense under 7.1.0.

I've removed the front end of the expanded pathnames.

isis7.0.0:
```
    DarkColumns               = (2525, 2524, 2523, 2522, 2521, 2520, 2519,
                                 2518, 2517, 2516, 2515, 2514, 8, 7, 6, 5, 4,
                                 3, 2, 1)
    DarkFile                  = isis_data/lro/calibration/N-
                                ACR_AverageDarks_Summed.0006.cub
    NonlinearOffset           = isis_data/lro/calibration/N-
                                ACR_LinearizationOffsets_Summed.0006.cub
    LinearizationCoefficients = isis_data/lro/calibration/N-
                                ACR_LinearizationCoefficients.0007.txt
    FlatFile                  =isis_data/lro/calibration/N-
                                ACR_Flatfield_Summed.0006.cub
    RadiometricType           = IOF
    ResponsivityValue         = 15058.0
    SolarDistance             = 1.0001282142168

```

isis7.1.0:
```
    DarkColumns               = (2525, 2524, 2523, 2522, 2521, 2520, 2519,
                                 2518, 2517, 2516, 2515, 2514, 8, 7, 6, 5, 4,
                                 3, 2, 1)
    DarkFileType              = NearestDarkFilePair
    DarkFiles                 = (isis_data/lro/calibration/-
                                 nac_darks/NACR_AverageDarks_621820869T_Summed-
                                 .0001.cub,
                                 isis_data/lro/calibration/n-
                                 ac_darks/NACR_AverageDarks_624412869T_Summed.-
                                 0001.cub)
    NonlinearOffset           =isis_data/lro/calibration/N-
                                ACR_LinearizationOffsets_Summed.0006.cub
    LinearizationCoefficients = isis_data/lro/calibration/N-
                                ACR_LinearizationCoefficients.0007.txt
    FlatFile                  = isis_data/lro/calibration/N-
                                ACR_Flatfield_Summed.0006.cub
    RadiometricType           = IOF
    ResponsivityValue         = 15058.0
    SolarDistance             = 2.83593680712876e-321
```
 This is not the same image that @oleg-alexandrov referenced, but one I had available locally.  I can let a dev know where via chat or email.

**Comment by lwellerastro** [comment]
@oleg-alexandrov, I just found this in the change log after searching for lronaccal (under the latest release section).  I missed it the first time I looked but found it when I used my browser's search tool:

`Added changes to lronaccal to use time-dependent dark files for dark correction and use of specific dark files for images with exp code of zero. Also added GTests for lronaccal and refactored code to make callable. Added 3 truth cubes to testing directory. PRhttps://github.com/USGS-Astrogeology/ISIS3/pull/4520`

**Comment by lwellerastro** [comment]
I have found I get the expected results from lronaccal under isis7.1.0 if I first run spiceinit on the image.  Under isis7.0.0 my image did not need spiceinit run on it to get reasonable results from lronaccal.  Running spiceinit before calibration is required by many datasets but did not seem to be a requirement for LRO NAC images until the recent updates to the program.

@oleg-alexandrov, you did not indicate your processing steps in your original post.  Did you pass lronaccal a spiced image?  If not, could you try that?  If you did spice first, you might update your data area per information discussed in #5113. It could be some critical files were missing and are available now.

**Comment by antonhibl** [comment]
seems like @lwellerastro's solution will work, ping us if you get the chance @oleg-alexandrov after trying with a spiceinited image. like Lynn was saying you might have to update data as per #5113 if some files were missing in that step.

**Comment by acpaquette** [comment]
Just to add to this, on a local build lronaccal is working as expected without needing to spiceinit. It seems like there is something wrong with the 7.1.0 build. It seems like either a data or dependency issue

**Comment by victoronline** [comment]
We've tested this using the internal copy that we submitted for merge and we aren't able to reproduce the error. I am comparing the two to see what is different or if there is a data or resource dependency issue.

**Comment by antonhibl** [comment]
@victoronline any updates on this?

**Comment by antonhibl** [comment]
closing this as we cannot seem to reproduce the issue without further information and the conversation has gone stale
