### ISSUE TITLE
Potentially including rclone with the conda distribution

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#5098]
ISIS needs its data to be able to function. Recently a tool named downloadIsisData is included, which is the only way to get the data. This tool fails saying that 'rclone' is missing. 

Since this program is pretty much a required dependency, I would think having it installed and shipped with ISIS would likely make sense. The user can install it separately, of course, but conda is slow to use and takes a while to fetch, and looks like it should be simpler to just have it fetched with the rest of the package.

**Comment by Kelvinrr** [comment]
I think this makes sense. I think the scripts are kinda treated as second class so at the time wasn't sure whether or not to include it as a dep and increase the ISIS deps. PR #5091 basically does this so we should also add rclone.

**Comment by antonhibl** [comment]
@Kelvinrr I believe this has been addressed as environment.yml now requires rclone, just checked out dev to double check.
