### ISSUE TITLE
MRO pck kernels not found, even using downloadIsidData.

### ISSUE THREAD

**Issue by Hyradus** [DOI-USGS/ISIS3#5103]
**ISIS version(s) affected**: 7.1.0 (probably all versions are affected)  - ASP version 3.1.0

**Description**  

I am trying to process HiRISE EDR using hiedr2mosaic.py but i get errors related to missing kernels
"**ERROR** No existing files found with a numerical version matching [pck?????.tpc] in [/isis/data/mro/kernels/pck]."
$ISISDATA synced using:
```
downloadIsisData mro $ISISDATA
```
Looking inside my $ISISDATA/mro/kernels/pck I can find only a file named kernels.0001.db

**How to reproduce**  

edit: hiedr2mosaic.py is bundled with [Ames Stereo Pipeline](https://github.com/Hyradus/StereoPipeline/blob/8a9f782b0a00d9742d3368a4ffecf4ee04d21b0f/src/asp/Tools/hiedr2mosaic.py#L120) 
Execute:
```
hiedr2mosaic.py *.IMG
```

**Possible Solution**  

Trying to perform hiedr2mosaic.py commands step-by-step and using:
```
spiceinit --web yes
```
seems to work, so probably only the **downloadIsisData** script is affected

**Additional context**

**Comment by Kelvinrr** [comment]
where is hiedr2mosaic.py coming from? I don't think that is part of ISIS?

**Comment by Kelvinrr** [comment]
Checking our data which is updated nightly using the same script, the area seems to be full of kernels. The PCK folder has a single PCK in it which I think is accurate. Running it just now with 

```
downloadIsisData mro /tmp/isisdata
```

seems to also be downloading everything. Do you know the command you originally used to download the kernels?

**Comment by Hyradus** [comment]
Hi, sorry for not mentioning (I'll edit also the issue).
hiedr2mosaic.py is part of the [Ames Stereo Pipeline](https://github.com/Hyradus/StereoPipeline/blob/8a9f782b0a00d9742d3368a4ffecf4ee04d21b0f/src/asp/Tools/hiedr2mosaic.py#L120) that just execute most of the ISIS HiRISE commands for each CCD and then reconstruct the complete image (e.g., hi2iss, spiceinit, etc). If I manually change it to use spiceinit --web it works, but is not the ideal solution.

The original isisdata was created using the rsync command but I have also tested with a new isisdata folder to avoid possible conflicts so I have used the downloadIsisData script bundled with ISIS v7.1.0.

I have also tried with different HiRISE images, with the same results.

**Comment by rbeyer** [comment]
@Hyradus, do you get this same behavior if you manually run `hi2isis` and then `spiceinit` on one (or both) of your HiRISE files?  Truly our `hiedr2mosaic.py` just runs ISIS programs, so I suspect that it would, but this would cement the problem as being a problem with your ISISDATA download, and not something odd with ASP.

**Comment by Hyradus** [comment]
@rbeyer I have tried the following on two different HiRISE EDR:

A = ESP_076649_1650_RED
B = ESP_068426_1985_RED

**1. non edited hiedr2mosaic.py:**
* fails on A and B (missing pck kernels)

**2. seprate commands (hi2isis, hical, spiceinit, etc):**
* fails only on A

**3. hiedr2mosaic with spiceinit web enabled:**
* fails on A (missing pck kernels)
* <s>fails on some CCDs of B (hijitreg -> **ERROR** Unable to find PVL group [Archive] in file ... )</s> EDIT: occurred only once

**4. I have also tested using kalasiris separate commands:**
* <s>fails on A and B, on hical step with status code 2.</s> EDIT: seems fixed, I had duplicated declaration of ISISDATA

So this error seems related to ISISDATA and potetially something else.

I'll try to re-download ISISDATA and additional HiRISE

**Comment by Hyradus** [comment]
Temporary solution is to use spiceinit web, so I have opened an issue also on the StereoPipeline repository [here](https://github.com/NeoGeographyToolkit/StereoPipeline/issues/389) and related pull request to integrate spiceinit web [here](https://github.com/NeoGeographyToolkit/StereoPipeline/pull/390)

**Comment by audiefen** [comment]
We ran into the same problem of _spiceinit_ not finding the correct pck here at HiRISE when we switched away from the previous rsync method for downloading the ISIS data. I don't really understand why _spiceinit_ is looking for the pck kernel in /isis/data/**mro**/kernels/pck (underneath the mro directory). The correct kernel is $base/kernels/pck/pck00009.tpc. To fix this on our system, we deleted the /isis/data/mro/kernels/pck directory (we tried this because that directory didn't used to be there before) and _spiceinit_ automatically found the correct kernel. Of course, now we have to ensure that the offending pck directory doesn't reappear when we refresh the ISIS data area.

**Comment by okaragoz** [comment]
I have the same problem, after updating ISIS. I did the synchronization with `downloadIsisData mro $ISISISDATA`. 
However, I try to process CTX EDR using `spiceinit` but got errors about missing kernels.

`**ERROR** No existing files found with a numerical version matching [kernels.????.db] in [/isis/mro/kernels/pck].`

ISIS version is 7.1.0
ASP version 3.2.0

After synchronizing two times using `downloadIsisData mro $ISISDATA`, when I look inside my ISISDATA/mro/kernels/pck file, I can only find a kernel file _kernels.0001.db._

**Comment by Hyradus** [comment]
@okaragoz you can try the temporary solution of @audiefen.

Is it mroctx2isis to give that error or spiceinit?

I don't remember exactly how mroctx2isis (and also hi2isis) works, in theory it should not need the kernels but I may be wrong.
Usually kernels are required from spiceinit (for which you can use spiceinit --web yes as a temporary solution)

**Comment by okaragoz** [comment]
@Hyradus Sorry yes you are right, I created a combined batch file with `spiceinit`, I get it online in the spiceinit step. 

 I tried @audiefen solution and it works so far. Thanks for the advice on spiceinit --web.

**Comment by swalterfub** [comment]
Maybe it helps debugging it, I had the same problem and could solve it by using the method mentioned at the very end of the ISIS3 readme: [https://github.com/USGS-Astrogeology/ISIS3#user-content-how-to-download-the-isis-test-data-with-rclone](https://github.com/USGS-Astrogeology/ISIS3#user-content-how-to-download-the-isis-test-data-with-rclone)

**Comment by Kelvinrr** [comment]
> I have the same problem, after updating ISIS. I did the synchronization with `downloadIsisData mro $ISISISDATA`. However, I try to process CTX EDR using `spiceinit` but got errors about missing kernels.
> 
> `**ERROR** No existing files found with a numerical version matching [kernels.????.db] in [/isis/mro/kernels/pck].`
> 
> ISIS version is 7.1.0 ASP version 3.2.0
> 
> After synchronizing two times using `downloadIsisData mro $ISISDATA`, when I look inside my ISISDATA/mro/kernels/pck file, I can only find a kernel file _kernels.0001.db._

Last I looked at this I was seeing the same thing. ~~Trying to track down where this kernel.db file is coming from since it is not in our buckets.~~ managed to find it. So I imagine the problem isn't that data is missing, but that there is a ghost kernel.db being downloaded.

**Comment by Kelvinrr** [comment]
The ghost PCK is deleted, delete your PCK folder locally and try to update your MRO area. The PCK folder should't come back. Hopefully that fixes the problem. Since this was a data change, you shouldn't have to get any new code.

**Comment by Kelvinrr** [comment]
There is a PCK file in NAIFs source (https://naif.jpl.nasa.gov/pub/naif/MRO/kernels/pck/), which we do not want to download. Gonna poke for a clean solution to this. Might have to get #5109 merged first.

**Comment by astrostu** [comment]
Just a corroboration that this is still a bug.  Using ISIS 7.1, ASP 3.2, completely new installs on a new Mac.  Per the above thread, I found the easiest work-around to be to change the /mro/kernels/pck directory to /mro/kernels/no_pck .

**Comment by Kelvinrr** [comment]
PCK directory now has a kernels.db and https://github.com/DOI-USGS/ISIS3/pull/5335 should fix this in the next release.
