### ISSUE TITLE
Some way to generate a table of kernel sizes for the current ISIS Data Area. 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#5105]
**Description**

There seems to be some stuff being downloaded nightly that are either not kernels, in order to find every instance and make this easier to diagnose in the future, might be worth creating some summary of the sizes of every mission category to get an idea of what is happening at a glance that can be generated with the nightly downloads. This is something that can be documented internally in the isis3mgr scripts repo. 

**Suggested Edit**

Before trying to write some custom script to do this, AWS probably has something we can leverage via cloud watch and/or log groups to get an idea of what is happening nightly and what the changes are over time (https://docs.aws.amazon.com/efs/latest/ug/logging-monitoring.html). If it's "go to the AWS and press these buttons", it's still worth writing down.

**Comment by foobarbecue** [comment]
I found `rclone ncdu` works really well for this. You can get something like this, and when you press enter on a row it goes into it and gives you sizes:

![image](https://user-images.githubusercontent.com/854789/224862014-d516f420-99e4-4012-80b9-2d252d7c27ad.png)

To use, set up your rclone config file so it looks like this:

```
(isis) aacurtis@MT-405357:~$ cat /home/aacurtis/.config/rclone/rclone.conf
[isis]
type = s3
provider = AWS
region = us-west-2
location_constraint = us-west-2
```
and then run ` rclone ncdu isis:asc-isisdata/usgs_data/`

**Comment by Kelvinrr** [comment]
I have some work to redo the way S3 files are synced being done, we can incorporate that rclone command into those and publish them somehow.
