### ISSUE TITLE
Missing LROC NAC night files

### ISSUE THREAD

**Issue by mtmUSGS** [DOI-USGS/ISIS3#5107]
Do you know if there are missing dark files for LROC in isis? I am radiometrically calibrating the LROC NAC images, (lronaccal) and a handful of images, there isn't a dark file available and the command fails.
here is the error 
**USER ERROR** Could not find a pair of dark files within 45 day range that includes the image [NACL_AverageDarks_*T_Summed]. Check to make sure your set of dark files is complete.
I redownloaded all of ISIS calibrations files, (isisDataDownload) but I had no change. All my images are at located near the south pole.
Any advice? 
Thanks!

**Comment by mtmUSGS** [comment]
Hi kris, Do you have any advice on the status of LROC data? I was looking to use your command in the page you linked but it isn't in my isis installment.

**Comment by KrisBecker** [comment]
Hi @mtmUSGS, the application _isisdataeval_ is not distributed in any ISIS release as it is a new application that has been submitted in #5111.

However, I was able to run my copy of the app on the full ISISDATA install and found 164 NACL darks that fit your description. Successful matching of these files is made based upon the the name of the file. The last file I have in my ISISDATA install is `$lro/calibration/nac_darks/NACL_AverageDarks_719107269T_Summed.0001.cub` created on 2022-11-18. The earliest file is `$lro/calibration/nac_darks/NACL_AverageDarks_300931266T_Summed.0001.cub` created on 2022-08-12. 

What is the name of the file are you trying to process? That should provide us a timeline to determine if a calibration file exists for that image.

I am not sure how these file are maintained for ISIS distribution. There is potentially a co-op with USGS and the LRO team on maintaining a distribution to users. You may need to contact them to fully resolve this issue if the appropriate file is not available in the current ISISDATA install.

**Comment by mtmUSGS** [comment]
Hi Kris, 

Thanks for the response! 

The images I am having trouble with are for all acquisitions between M1406786871LE.IMG and M1414386054RE.IMG.

I just looked in my calibration folder and I am showing only 157 dark files. I have listed them below.  

Should I redownload the isis data? Is there a force reinstall option that you know of? I download isis LROC data into an empty directory a few days ago using the following command:
downloadIsisData lro $ISISDATA/.
Any idea how I missed these files?

Thanks for the help!


Here is the list of the night files I found in my calibration directory. 

NACL_AverageDarks_300931266T_Summed.0001.cub
NACL_AverageDarks_303609666T_Summed.0001.cub
NACL_AverageDarks_306288066T_Summed.0001.cub
NACL_AverageDarks_308880066T_Summed.0001.cub
NACL_AverageDarks_311558466T_Summed.0001.cub
NACL_AverageDarks_314150466T_Summed.0001.cub
NACL_AverageDarks_316828866T_Summed.0001.cub
NACL_AverageDarks_319507266T_Summed.0001.cub
NACL_AverageDarks_321926466T_Summed.0001.cub
NACL_AverageDarks_324604866T_Summed.0001.cub
NACL_AverageDarks_327196866T_Summed.0001.cub
NACL_AverageDarks_329875266T_Summed.0001.cub
NACL_AverageDarks_332467266T_Summed.0001.cub
NACL_AverageDarks_335145666T_Summed.0001.cub
NACL_AverageDarks_337824066T_Summed.0001.cub
NACL_AverageDarks_340416066T_Summed.0001.cub
NACL_AverageDarks_343094466T_Summed.0001.cub
NACL_AverageDarks_345686466T_Summed.0001.cub
NACL_AverageDarks_348364866T_Summed.0001.cub
NACL_AverageDarks_351043266T_Summed.0001.cub
NACL_AverageDarks_353462466T_Summed.0001.cub
NACL_AverageDarks_356140866T_Summed.0001.cub
NACL_AverageDarks_358732866T_Summed.0001.cub
NACL_AverageDarks_361411266T_Summed.0001.cub
NACL_AverageDarks_364003266T_Summed.0001.cub
NACL_AverageDarks_366681666T_Summed.0001.cub
NACL_AverageDarks_369360066T_Summed.0001.cub
NACL_AverageDarks_371952066T_Summed.0001.cub
NACL_AverageDarks_374630466T_Summed.0001.cub
NACL_AverageDarks_377222466T_Summed.0001.cub
NACL_AverageDarks_379900866T_Summed.0001.cub
NACL_AverageDarks_382579266T_Summed.0001.cub
NACL_AverageDarks_385084866T_Summed.0001.cub
NACL_AverageDarks_387763266T_Summed.0001.cub
NACL_AverageDarks_390355266T_Summed.0001.cub
NACL_AverageDarks_393033666T_Summed.0001.cub
NACL_AverageDarks_395625667T_Summed.0001.cub
NACL_AverageDarks_398304067T_Summed.0001.cub
NACL_AverageDarks_400982467T_Summed.0001.cub
NACL_AverageDarks_403574467T_Summed.0001.cub
NACL_AverageDarks_406252867T_Summed.0001.cub
NACL_AverageDarks_408844867T_Summed.0001.cub
NACL_AverageDarks_411523267T_Summed.0001.cub
NACL_AverageDarks_414201667T_Summed.0001.cub
NACL_AverageDarks_416620867T_Summed.0001.cub
NACL_AverageDarks_419299267T_Summed.0001.cub
NACL_AverageDarks_421891267T_Summed.0001.cub
NACL_AverageDarks_424569667T_Summed.0001.cub
NACL_AverageDarks_427161667T_Summed.0001.cub
NACL_AverageDarks_429840067T_Summed.0001.cub
NACL_AverageDarks_432518467T_Summed.0001.cub
NACL_AverageDarks_435110467T_Summed.0001.cub
NACL_AverageDarks_437788867T_Summed.0001.cub
NACL_AverageDarks_440380867T_Summed.0001.cub
NACL_AverageDarks_443059267T_Summed.0001.cub
NACL_AverageDarks_445737667T_Summed.0001.cub
NACL_AverageDarks_448156867T_Summed.0001.cub
NACL_AverageDarks_450835267T_Summed.0001.cub
NACL_AverageDarks_453427267T_Summed.0001.cub
NACL_AverageDarks_456105667T_Summed.0001.cub
NACL_AverageDarks_458697667T_Summed.0001.cub
NACL_AverageDarks_461376067T_Summed.0001.cub
NACL_AverageDarks_464054467T_Summed.0001.cub
NACL_AverageDarks_466646467T_Summed.0001.cub
NACL_AverageDarks_469324867T_Summed.0001.cub
NACL_AverageDarks_471916867T_Summed.0001.cub
NACL_AverageDarks_474595267T_Summed.0001.cub
NACL_AverageDarks_477273667T_Summed.0001.cub
NACL_AverageDarks_479692867T_Summed.0001.cub
NACL_AverageDarks_482371267T_Summed.0001.cub
NACL_AverageDarks_484963267T_Summed.0001.cub
NACL_AverageDarks_487641667T_Summed.0001.cub
NACL_AverageDarks_490233668T_Summed.0001.cub
NACL_AverageDarks_492912068T_Summed.0001.cub
NACL_AverageDarks_495590468T_Summed.0001.cub
NACL_AverageDarks_498182468T_Summed.0001.cub
NACL_AverageDarks_500860868T_Summed.0001.cub
NACL_AverageDarks_503452868T_Summed.0001.cub
NACL_AverageDarks_506131268T_Summed.0001.cub
NACL_AverageDarks_508809668T_Summed.0001.cub
NACL_AverageDarks_511315268T_Summed.0001.cub
NACL_AverageDarks_513993668T_Summed.0001.cub
NACL_AverageDarks_516585668T_Summed.0001.cub
NACL_AverageDarks_519264068T_Summed.0001.cub
NACL_AverageDarks_521856068T_Summed.0001.cub
NACL_AverageDarks_524534468T_Summed.0001.cub
NACL_AverageDarks_527212868T_Summed.0001.cub
NACL_AverageDarks_529804868T_Summed.0001.cub
NACL_AverageDarks_532483268T_Summed.0001.cub
NACL_AverageDarks_535075268T_Summed.0001.cub
NACL_AverageDarks_537753669T_Summed.0001.cub
NACL_AverageDarks_540432069T_Summed.0001.cub
NACL_AverageDarks_542851269T_Summed.0001.cub
NACL_AverageDarks_545529669T_Summed.0001.cub
NACL_AverageDarks_548121669T_Summed.0001.cub
NACL_AverageDarks_550800069T_Summed.0001.cub
NACL_AverageDarks_553392069T_Summed.0001.cub
NACL_AverageDarks_556070469T_Summed.0001.cub
NACL_AverageDarks_558748869T_Summed.0001.cub
NACL_AverageDarks_561340869T_Summed.0001.cub
NACL_AverageDarks_564019269T_Summed.0001.cub
NACL_AverageDarks_566611269T_Summed.0001.cub
NACL_AverageDarks_569289669T_Summed.0001.cub
NACL_AverageDarks_571968069T_Summed.0001.cub
NACL_AverageDarks_574387269T_Summed.0001.cub
NACL_AverageDarks_577065669T_Summed.0001.cub
NACL_AverageDarks_579657669T_Summed.0001.cub
NACL_AverageDarks_582336069T_Summed.0001.cub
NACL_AverageDarks_584928069T_Summed.0001.cub
NACL_AverageDarks_587606469T_Summed.0001.cub
NACL_AverageDarks_590284869T_Summed.0001.cub
NACL_AverageDarks_592876869T_Summed.0001.cub
NACL_AverageDarks_595555269T_Summed.0001.cub
NACL_AverageDarks_598147269T_Summed.0001.cub
NACL_AverageDarks_600825669T_Summed.0001.cub
NACL_AverageDarks_603504069T_Summed.0001.cub
NACL_AverageDarks_605923269T_Summed.0001.cub
NACL_AverageDarks_608601669T_Summed.0001.cub
NACL_AverageDarks_611193669T_Summed.0001.cub
NACL_AverageDarks_613872069T_Summed.0001.cub
NACL_AverageDarks_616464069T_Summed.0001.cub
NACL_AverageDarks_619142469T_Summed.0001.cub
NACL_AverageDarks_621820869T_Summed.0001.cub
NACL_AverageDarks_624412869T_Summed.0001.cub
NACL_AverageDarks_627091269T_Summed.0001.cub
NACL_AverageDarks_629683269T_Summed.0001.cub
NACL_AverageDarks_632361669T_Summed.0001.cub
NACL_AverageDarks_635040069T_Summed.0001.cub
NACL_AverageDarks_637545669T_Summed.0001.cub
NACL_AverageDarks_640224069T_Summed.0001.cub
NACL_AverageDarks_642816069T_Summed.0001.cub
NACL_AverageDarks_645494469T_Summed.0001.cub
NACL_AverageDarks_648086469T_Summed.0001.cub
NACL_AverageDarks_650764869T_Summed.0001.cub
NACL_AverageDarks_653443269T_Summed.0001.cub
NACL_AverageDarks_656035269T_Summed.0001.cub
NACL_AverageDarks_658713669T_Summed.0001.cub
NACL_AverageDarks_661305669T_Summed.0001.cub
NACL_AverageDarks_663984069T_Summed.0001.cub
NACL_AverageDarks_666662469T_Summed.0001.cub
NACL_AverageDarks_669081669T_Summed.0001.cub
NACL_AverageDarks_671760069T_Summed.0001.cub
NACL_AverageDarks_674352069T_Summed.0001.cub
NACL_AverageDarks_677030469T_Summed.0001.cub
NACL_AverageDarks_679622469T_Summed.0001.cub
NACL_AverageDarks_682300869T_Summed.0001.cub
NACL_AverageDarks_684979269T_Summed.0001.cub
NACL_AverageDarks_687571269T_Summed.0001.cub
NACL_AverageDarks_690249669T_Summed.0001.cub
NACL_AverageDarks_692841669T_Summed.0001.cub
NACL_AverageDarks_695520069T_Summed.0001.cub
NACL_AverageDarks_698198469T_Summed.0001.cub
NACL_AverageDarks_700617669T_Summed.0001.cub
NACL_AverageDarks_703296069T_Summed.0001.cub
NACL_AverageDarks_713836869T_Summed.0001.cub
NACL_AverageDarks_716515269T_Summed.0001.cub
NACL_AverageDarks_719107269T_Summed.0001.cub

**Comment by KrisBecker** [comment]
Based upon the names of the files, the issue may be that they were acquired before any of the currently available dark files. Please try running `lronaccal` with `darkfiletype=nearest` to see if it can find the closest one. That might help.

**Comment by MimSinha** [comment]
Do you know if there are missing dark files for LROC in isis? I am radiometrically calibrating the LROC NAC images, (lronaccal) and a handful of images, there isn't a dark file available and the command fails.
here is the error
**USER ERROR** Could not find any dark file of type NACL_AverageDarks_*T.*. Check to make sure your set of dark files is complete.
I redownloaded all of ISIS calibrations files, (isisDataDownload) but I had no change. 

from where i can get the dark files? 
i have download the dark file from https://pds.lroc.asu.edu/data/LRO-L-LROC-3-CDR-V1.0/LROLRC_1033/CALIB/ but still getting same error.
