### ISSUE TITLE
Web SPICE out-of-date for public LROC data

### ISSUE THREAD

**Issue by rvwagner** [DOI-USGS/ISIS3#5113]
**ISIS version(s) affected**: All

**Description**  
The USGS Web SPICE server only appears to have kernels for the LROC instruments through mid-Sept 2022.  The most recent public data release from LROC goes out to 15 Oct 2022, and those images cannot be processed with Web SPICE.

Since LROC has a monthly public release cadence, the Web SPICE server needs to be synced at least monthly to the kernel directories hosted by the LROC team to be able to support the publicly-released images.  It would be nice if it was synced daily, which would allow the LROC science team to use Web SPICE for unreleased images.

**How to reproduce**  
```
curl https://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0053A/DATA/ESM5/2022288/NAC/M1420517656RE.IMG > M1420517656RE.IMG
lronac2isis from= M1420517656RE.IMG to= M1420517656R.cub
spiceinit from= M1420517656R.cub web=true
```
Output:
```
spiceinit: Requesting Spice Data
100% Processed
**ERROR** The Spice Server was unable to initialize the cube.  The error reported was: No Camera Kernel found for the image [/tmp/spice_web_service/3Oy_ulfQnH] in SpiceClient.cpp at 588.
```

**Comment by victoronline** [comment]
Has anyone been able to look at this yet?

**Comment by Kelvinrr** [comment]
Looking into it, it seems the server is failing to copy new kernels since the drive has maxed out. In touch with IT to give it more storage. Will post updates here.

**Comment by Kelvinrr** [comment]
storage was bumped up, kernels are updating, might take several hours

**Comment by rvwagner** [comment]
Just tested on a couple LROC images (both the one listed above and a not-yet-released one from a couple days ago), and both processed fine.  Hopefully you've also set up some sort of alert so that this doesn't recur in [some] years when the disk fills up again.

Thanks for getting this fixed up!

**Comment by Kelvinrr** [comment]
I agree on the notifications, the cron is supposed to email us but I can figure out why it hasn't. Closing this as running the example worked for me right now.
