### ISSUE TITLE
LibGL.1.dylib not found

### ISSUE THREAD

**Issue by cefer95** [DOI-USGS/ISIS3#5115]
**ISIS version(s) affected**: 7.1.0

**Description**  

Launching qview or lowpass: got error below:
dyld[41342]: Library not loaded: '/opt/X11/lib/libGL.1.dylib'
  Referenced from: '/Applications/anaconda3/envs/isis/bin/lowpass'
  Reason: tried: '/opt/X11/lib/libGL.1.dylib' (no such file), '/usr/local/lib/libGL.1.dylib' (no such file), '/usr/lib/libGL.1.dylib' (no such file)
Abort trap: 6

**How to reproduce**  
$qview or $lowpass

**Possible Solution**  

**Additional context**  
On Mac OS X 12.5.1, Apple M1 Max

**Comment by acpaquette** [comment]
This is likely an issue with the GL versions being pulled by anaconda. Could you provide the output from `conda env list` from your ISIS install?

**Comment by sassarini** [comment]
Hi,
i'm having the very same issue. When trying to open an app (i.e. lowpass) I get the following:

"dyld[9416]: Library not loaded: '/opt/X11/lib/libGL.1.dylib'
  Referenced from: '/Users/username/opt/anaconda3/envs/isis/bin/lowpass'
  Reason: tried: '/opt/X11/lib/libGL.1.dylib' (no such file), '/usr/local/lib/libGL.1.dylib' (no such file), '/usr/lib/libGL.1.dylib' (no such file)
zsh: abort      lowpass"

When I run conda env list, instead, I obtain the following:

"conda environments:

base                     /Users/username/opt/anaconda3
isis                  *  /Users/username/opt/anaconda3/envs/isis "

Thanks!

**Comment by KrisBecker** [comment]
I think this issue can be resolved by installing [XQuartz](https://www.xquartz.org). This library does exist on my M1 Mac after install XQuartz. 

Give that a try and let us know if it fixes the issue.

**Comment by antonhibl** [comment]
@sassarini  @cefer95 just bumping this to see if you were able to fix this with @KrisBecker's solution. If not, can you provide the output for `conda list` from your ISIS environment?

**Comment by AustinSanders** [comment]
Installation of XQuartz is included in the installation instructions for m1 mac as of #5166 .  This solution was tested alongside the PR, and appears to have solved this issue.
