### ISSUE TITLE
Allow ale drivers to calculate nadir pointing during spiceinit

### ISSUE THREAD

**Issue by AustinSanders** [DOI-USGS/ISIS3#5117]
**Description**  
Spiceinit currently does not allow ale drivers to calculate nadir pointing despite ALE containing the logic to do so.

**Example**  
``` spiceinit cknadir=yes from= fsb_00720_1cd_xhu_84n209_v1.ale.cub ``` (along with the chandrayaan1_mrffr driver) should allow spiceinit with ale drivers

**Comment by acpaquette** [comment]
Still active
