### ISSUE TITLE
spiceinit server script

### ISSUE THREAD

**Issue by tllogan** [DOI-USGS/ISIS3#5122]
Hi. Around 08FEB2023 I began getting the following error (below) with spiceinit. Has something changed in the last couple of weeks that would cause this?
Thanks.
spiceinit   from=xxctx_a.cub web=true
**ERROR** An error occurred when talking to the server. The spice server script was not found (404).

**Comment by tllogan** [comment]
This problem has been resolved. My CTX processing jobs are running. Thank you for your support!

**Comment by acpaquette** [comment]
Hi @tllogan, from the dev teams understanding not much has been done by us on this but our IT department may have resolved this in the background.

Just to confirm with you, you are able run `spiceinit` with `web=true` and get the expected result back?

**Comment by tllogan** [comment]
Yes, spiceinit is currently running fine.
Thank you.

From: acpaquette ***@***.***>
Reply-To: USGS-Astrogeology/ISIS3 ***@***.***>
Date: Tuesday, February 21, 2023 at 10:26 AM
To: USGS-Astrogeology/ISIS3 ***@***.***>
Cc: "Logan, Thomas L (US 398E)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [USGS-Astrogeology/ISIS3] spiceinit server script (Issue #5122)


Hi @tllogan<https://urldefense.us/v3/__https:/github.com/tllogan__;!!PvBDto6Hs4WbVuu7!NK8rcRFvBRBUEYNNu3Butmd73GtlwnKGnClnUOCZf9jVyjKgqD4Ar9QSj5-sce3znXElaUgAeV0vAYwRYgnGBe7Xr77-QE1j7A$>, from the dev teams understanding not much has been done by us on this but our IT department may have resolved this in the background.

Just to confirm with you, you are able run spiceinit with web=true and get the expected result back?
