### ISSUE TITLE
Spiceinit fails for MEX SRC

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5123]
**ISIS version(s) affected**: 7.2.0-RC1 and 7.1.0 though it had worked for the latter at one point
I'm running local versions of isis via astrovm machines.

**Description**  
spiceinit fails with the following error on MEX SRC images of Phobos:

```
    Error                     = "An unknown NAIF error has been encountered.
                                 The short explanation provided by NAIF is
                                 [SPICE(FILEREADFAILED)]. The Naif error is
                                 [Attempt to read from file
                                 '$ISISDATA/mex/kernels/ck/A-
                                 TNM_MEASURED_040101_050101_V03.BC' failed.
                                 IOSTAT = -1.]"
  End_Group

  Group = Error
    Program = spiceinit
    Code    = 1
    Message = "Unable to initialize camera model"
    File    = spiceinit.cpp
    Line    = 262
  End_Group
```
Note that I replaced the leading path information for the filename above with the environment variable.  
The file does exist.

**How to reproduce**  
Run spiceinit with defaults on SRC isis cube file under either of the versions mentioned above.  
A file can be found under my user work area: Isis3Tests/Spiceinit/NewDataArea/7.2.0RC1/MEX

`spiceinit from=H0715_0004_SR2.cub`

This file and others like it had already been successfully ingested and spiced various times (to access different shape models) since summer of 2022 with no errors.  The last time spice was successfully run was on December 19, 2022 under isis7.1.0.

When spiceinit is passed a MEX HRSC image it runs successfully. The SRC camera model was improved/updated this summer and released via isis7.1.0.

**Additional context**  
I changed my data area to point to a frozen/old version of the data area and spiceinit runs successfully on the SRC image.
I tested this under isis7.2.0-RC1 and pointed to isis3_old/isis_data/ which was captured early September before the data area was moved to the cloud.

**Comment by acpaquette** [comment]
@lwellerastro Yup, data problem. For whatever reason those files are completely empty
<img width="935" alt="Screen Shot 2023-02-17 at 6 21 42 PM" src="https://user-images.githubusercontent.com/17728237/219824074-5eea689d-85ed-498e-b853-569a5b3a522f.png">

**Comment by amystamile-usgs** [comment]
I updated the 4 empty MEX ck kernels in the isis data area and was able to spiceinit the SRC image.

@lwellerastro when you get a change, could you test spiceinit using the current isis data area?

**Comment by lwellerastro** [comment]
Thanks @amystamile-usgs - SRC can now be spiced.
I'll report back if I run into any other problems .

**Comment by acpaquette** [comment]
@lwellerastro Lets call this closed, and reopen if issues return
