### ISSUE TITLE
kernels produced by ckwriter do not produce the expected geometry (Voyager 2 example)

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#5124]
**ISIS version(s) affected**: Isis7.0.0

**Description**  
This is almost certainly related to @lwellerastro's issue [4942](https://github.com/USGS-Astrogeology/ISIS3/issues/4942). I've posted in a new issue in case it isn't related or in case this is simply user error. 

Problem: SPICE ck kernels created from images updated with jigsaw do not produce the expected geometry. 

Background: Back in 2020 I controlled 41 Voyager 2 images of Triton, generated a mosaic, and wrote ck kernels using ckwriter. I recently applied those kernels to a "fresh" set of the same 41 images (i.e., spiceinit from=foo.cub ck=foo.bc), created a mosaic with the same list I had used previously, and noticed that the image positions had shifted slightly. Because I was concerned that changes in ISIS may have occurred since 2020, I then confirmed this behavior by starting "from scratch" with a clean set of images, bundling them using the 2020 network to update their positions, writing ck kernels with ck writer, and applying the new kernels to a freshly downloaded image. You can compare the two using the "point picker" tool in ISIS (not sure what that's actually called). The same lat/lon position is at different line/sample in the images. This was all performed under isis7.0.0.

**How to reproduce**  
The cleanest place to see this is my work directory under Triton-Voyager/2023/. There is an 'aaREADME' file that explains what each directory contains. A side-by-side comparison of 1. an images with positions updated in the bundle, and 2. an image that was spiceinited with ck kernels derived from image 1 can be found in /Triton-Voyager/2023/respice/kernels/check/side-by-side/ 

**Possible Solution**  
See [4942](https://github.com/USGS-Astrogeology/ISIS3/issues/4942) for more detail. Either ckwriter or jigsaw isn't performing as expected.

**Additional context**  
I ONLY updated image cks in this case (e.g., not spk). Note that I couldn't start my recent "from scratch" test with default kernels because the SPICE is so bad for Voyager that the 2020 network wouldn't bundle (points off the body). So I had to apply the 2020 kernels even in my recent test. Note that I have a simple work arounds for this, so it's not critical. However, I was hoping to release the updated kernels at some point.

**Comment by blandoplanet** [comment]
A bit of additional info... To make the difference easier to evaluate I've run campt on both images letting it default to the center line/sample of the image (thanks for the suggestions @lwellerastro). The results are under /Triton-Voyager/2023/respice/kernels/check/side-by-side/campt.txt. The *updated.cub had it's pointing updated via jigsaw. The *newck .cub was spiceinited with kernels generated from *updated.cub. The lat/lons should be identical but are not:

Filename,Sample,Line,PlanetocentricLatitude,PositiveEast360Longitude
c1139623_updated.cub,400.0,400.0,21.402102299165,6.074312893159
c1139623_newck.cub,400.0,400.0,21.418984916955,6.0447319621461

**Comment by amystamile-usgs** [comment]
I do not believe this issue is related to #4942. We determined that that issue was directly related to jigsaw not writing instrument position velocities back into the label.

**Comment by amystamile-usgs** [comment]
Hmm strange. I ran tabledump on both images for InstrumentPointing and they are identical. So seems like ckwriter is writing correctly and spiceinit is properly applying the ck kernel. Luckily this is not an issue associated with ale. I will continue to dig around.

```
c1139623_updated.cub
J2000Q0,J2000Q1,J2000Q2,J2000Q3,AV1,AV2,AV3,ET
0.29434660378561,0.71565277606477,-0.5897766043628,-0.23100809054434,0.0,0.0,0.0,-326689821.40827

c1139623_newck.cub
J2000Q0,J2000Q1,J2000Q2,J2000Q3,AV1,AV2,AV3,ET
0.29434660378561,0.71565277606477,-0.5897766043628,-0.23100809054434,0.0,0.0,0.0,-326689821.40827

**Comment by blandoplanet** [comment]
Seeing @amystamile-usgs's message and looking at this with fresh eyes - this is not a jigsaw or ckwriter problem. This is an issue with ISIS' findrx application. Namely, findrx changes the geometry of the image. I became aware of this in the spring but wasn't aware it was affecting the example I provided here. However, looking at the two cubes I compared above you'll see that the "updated" cube has had findrx run on it after the jigsaw update. To confirm this, I just created a new copy of the "newck" cube in a subdirectory named 'findrx" and ran the findrx application on it. Running campt shows that the "newck+findrx" cube matches the "jigsaw+findrx cube" (but not the original "newck" cube). 

Unless I'm not understanding findrx, this is not desirable behavior. Findrx should just be refining the position of the reseaus in the Voyager images using some basic registration and writing the updated line/samples as a blob in the cube (it doesn't even have a "to=" option - it just overwrites. I have no idea why it's changing the geometry of the images (tweaking the distortion model based on the new reseau locations??). I think it would be best to close this issue and open a new one that specifically describes the findrx problem. Thoughts?

**Comment by blandoplanet** [comment]
Actually. Before I close this, please let me confirm that an jigsaw-update image (without findrx) matches a newly spiced image using the ck kernel

**Comment by amystamile-usgs** [comment]
I think you are right about this being an issue with findrx. I ran findrx on the newly ingested/spiceinit'd cube and the points now align with the jigsawed(updated) cube. 
![image](https://github.com/DOI-USGS/ISIS3/assets/74275278/95461581-0c26-44a5-a302-b137cdde3012)

**Comment by blandoplanet** [comment]
I have confirmed that a "clean" ingest with the smithed ck applied DOES match the geometry of the jigsaw imaged from which the kernels were derived. Closing this and opening a findrx issue.
