### ISSUE TITLE
Add filename prefix option for tgocassisstitch

### ISSUE THREAD

**Issue by AustinSanders** [DOI-USGS/ISIS3#5125]
**Description**  
tgocassissitch currently produces filenames according to a timestamp rather than preserving the observation-framelet name that is commonly found on TGO images.  This is inconvenient and makes it difficult to determine which input and output images correspond.

Instead, it would be nice to have a prefix and/or suffix specification that preserves the original filename and simply adds the specified text to the filename.

**Example**  
tgocassisstitch from= stitch_001.lis outputprefix=stitch 

for stitch_001.lis containing:
MY36_018816_356_1_001_PAN00-C1.cub 
outputs:
stitch-MY36_018816_356_1_001.cub

**Comment by antonhibl** [comment]
#5132 has been opened to address this

**Comment by antonhibl** [comment]
should be addressed by #5132

**Comment by AustinSanders** [comment]
We should leave this issue open until the PR is merged

**Comment by AustinSanders** [comment]
@antonhibl It looks like I didn't fully capture the request in the original issue.  I updated the issue after re-reading the email with the issue description.

The other part of this issue (alongside the prefix/suffix specification) is to switch the filename to that of the input e.g. stitch-MY36_018816_356_1_001.cub as opposed to the timestamp e.g. stitch-2022-02-10T12:29:55.286.cub.

**Comment by antonhibl** [comment]
@AustinSanders gotcha, that makes sense; I'll take another look.

**Comment by antonhibl** [comment]
bumping this, should be good to go @AustinSanders
