### ISSUE TITLE
Add support for embree3

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#5127]
**Description**  
A new version of embree has been released and updating ISIS to support it would be ideal.

**Comment by Kelvinrr** [comment]
We should probably pin for now. 

Do we know if this is an interface issue? Or do we need to simply update the cmake chain to look for 3+?

**Comment by acpaquette** [comment]
If I remember correctly is was both, @chkim-usgs and I got the find script to actually find it. After that we ran into further build errors. Pinning for now is fine but getting it back ported to other builds would be good as well.
