### ISSUE TITLE
Failing to install 7.1.0 on Mac

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#5142]
**ISIS version(s) affected**: 7.1.0

**Description**  
On Mac, I am failing to install isis 7.1.0 due to a package being unable to verify.

**How to reproduce**  
Run the following on a Mac machine:
mamba/conda create -n isis7.1.0 -c conda-forge -c usgs-astrogeology isis=7.1.0

**Possible Solution**  
This may be an issue on opencv's side but opencv 4.6 has been out for 2 months and I don't see any discussion on the package being corrupt on the github repo. Might be worth making an issue over there as well?

**Additional context**  
I am on Mac OSX 12.6 with an Intel CPU

**Comment by antonhibl** [comment]
@acpaquette To add to this, I just tested on my machine which is running MacOS Ventura 13.2.1 and it seemed to build the environment, cmake ran correctly, and ninja also worked for rebuilding ISIS with this version. It might be a problem with that version of MacOS, what was the specific error message?

**Comment by antonhibl** [comment]
would this also imply we could close #5106 as ISIS 7.+ is working on MacOS 13 now?

**Comment by acpaquette** [comment]
@antonhibl This is related to installing ISIS via conda where a user shouldn't have to rebuild ISIS, just install it off of anaconda.

If we started actually releasing builds using MacOSX 13, which we may do so. We have actually run a conda-build on a MacOSX 13 platform and confirmed that we can install from there then yes, #5106 could be closed

**Comment by antonhibl** [comment]
Makes sense, thanks for explaining that. I did test the command you listed on my machine and it worked without errors though if that's relevant. @acpaquette

**Comment by acpaquette** [comment]
Fair, it didn't seem like that was the path taken w.r.t. running cmake, and ninja to rebuild ISIS. Let me see if I can replicate on my machine. May have just been a erratic issue with anaconda.

**Comment by antonhibl** [comment]
@acpaquette did you ever get a chance to check this out again?
