### ISSUE TITLE
ISISDATA: MRO NAV spacecraft kernels are being downloaded and contributing to data bloat

### ISSUE THREAD

**Issue by dpmayerUSGS** [DOI-USGS/ISIS3#5143]
**ISIS version(s) affected**: >=4.x

**Description**  
The current config for downloading SPICE kernels to the ISIS data area grabs many irrelevant files, leading to bloat in the data area. See #5110 for a summary of the broader issue. 

More narrowly, the rclone config is downloading MRO spacecraft trajectory kernels (SPKs) produced by the MRO NAV team. These kernels either cover future time periods, which means that they serve no practical purpose for ISIS users, or they are early version of reconstructed kernels which are aggregated into the SPKs named like `mro_psp??.bsp` that are already being downloaded or superseded by refined reconstructed kernels named like `mro_psp??_ssd_*.bsp` that are also already being downloaded. 

Historically, these kernels were not included in the ISIS data area. Downloading the original NAV kernels to the data area is contributing to the general problem of data bloat. 

**How to reproduce**  

Run `downloadIsisData mro $ISISDATA` and notice that `$ISISDATA/mro/kernels/spk` includes (dozens of) NAV kernels and their labels. These kernels are named like `spk_psp_recJJJJJ_IIIII_MMMMM_K-vV`. From [documentation at NAIF](https://naif.jpl.nasa.gov/pub/naif/MRO/kernels/spk/archived.txt):

> Each of these files provides reconstructed trajectory for orbits "JJJJJ" through "IIIII" and predicted trajectory for                      orbits "IIIII" through "MMMMM". If the file contains only reconstructed data, then K is set to "r", otherwise it is set to "p". "V" is the file version.

**Possible Solution**  
Update rclone.conf with exclude flags to prevent the NAV kernels from being downloaded as part of the MRO data kernels.

**Additional context**  
Related to pull request #5109

**Comment by antonhibl** [comment]
@dpmayerUSGS I believe we are aiming to add exclude patterns for rclone to the exclude_list that #5109 adds which would allow filtering of these files by default so I can look into adding this pattern(If I understand right the pattern to filter would be `kernels/spk/spk_psp_*` or something similar) into that PR, which would address this.

**Comment by dpmayerUSGS** [comment]
@antonhibl Sounds good. The pattern to exclude would be `kernels/spk/spk_psp_rec*`

**Comment by AustinSanders** [comment]
Closed via #5109
