### ISSUE TITLE
ISIS LTS Requirements

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#5146]
**Description**  
Here are the requirements for what needs to be done under the releases project for the ISIS LTS / ISIS releases. These are provided in order of importance, so it is not necessary to start work on OS specific testing before CD is setup for merged changes to the project.

- [x] ISIS8.0.x is the LTS version. Therefore, the next major release adopts the LTS model.
- [ ] Cherry pickings bugs from main/dev back into the LTS.
  - [ ] Process documentation / automation for cherry picking
  - [ ] Process documentation / automation for issue labeling as a bug (to indicate that it needs to be cherry picked)
- [ ] Continuous deploy (LTS)
  - [ ] LTS versions with a merged bug fix needs to have the patch version incremented and a release made via anaconda.
  - [ ] Automated CD of the LTS on merge of a bug
- [ ]  Continuous deploy (dev/main)
  - [ ] Automated CD of dev/main on merge of a PR with appropriate incrementing of the major/minor version number
- [ ] Improved testing of OS specific installations using the CI/CD pipeline, e.g., a nightly conda install test of the library across supported OSes.

**Comment by AustinSanders** [comment]
This should remain open

**Comment by jlaura** [comment]
@AustinSanders 👍 

In the initial issue, can we check off any other sub-items as completed?
