### ISSUE TITLE
An unknown NAIF problem has been encountered when process the MRO HiRISE data

### ISSUE THREAD

**Issue by ldx119** [DOI-USGS/ISIS3#5148]
When I used the ASP python script hiedr2mosaic.py to process the MRO HiRISE data, near Zhurong Rover Landing Site, the image is, ESP_077168_2055. I encountered an unknown NAIF error when the script ran the program spiceinit, I am sure that the MRO spice kernel and base data should be fine.
How should this problem be solved?  Thanks.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/100507049/224340963-1010f308-2d59-4aa5-b6d0-05ed59436a95.png">

**Comment by audiefen** [comment]
Might be related to this issue #5103. It looks like it is picking up the wrong pck. We solved the problem on our system by deleting $mro/kernels/pck/ directory. (I think _spiceinit_ defaults to looking there first.) It looks like others solved it by using _spiceinit --web_.

**Comment by ldx119** [comment]
I delete the $mro/kernels/pck/ directory, but it didn't work out. Then I use the spiceinit on the ESP_077168_2055 using web=yes, it reported: the spice server was unable to initialize the cub. .My isis version is 7.1.0  .

**Comment by acpaquette** [comment]
Just tested this locally to try and produce the issue and it seems solved(?)

Main difference was the sclk that was pulled, seems like it may have solved the issue

<img width="730" alt="Screen Shot 2023-03-20 at 5 05 12 PM" src="https://user-images.githubusercontent.com/17728237/226491295-a4dde25e-0aac-4ed1-910e-9716d391904e.png">

**Comment by ldx119** [comment]
> Just tested this locally to try and produce the issue and it seems solved(?)
> 
> Main difference was the sclk that was pulled, seems like it may have solved the issue
> 
> <img alt="Screen Shot 2023-03-20 at 5 05 12 PM" width="730" src="https://user-images.githubusercontent.com/17728237/226491295-a4dde25e-0aac-4ed1-910e-9716d391904e.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/100507049/226503991-c6d90c54-093a-4f3b-9bf4-fb9dda674783.png">
Sorry to disturb you again. This time it looks all the same as yours, but it still reports this error.

**Comment by acpaquette** [comment]
So weird, @ldx119 could you double check that there is actually data in the Instrument position kernel as well as the target position kernels? Just running `ls -lah /Path/to/Kernel` should tell you if it contains data. We had a weird problem before with some of the data where files were just empty, so I would like to check that.

**Comment by ldx119** [comment]
> So weird, @ldx119 could you double check that there is actually data in the Instrument position kernel as well as the target position kernels? Just running `ls -lah /Path/to/Kernel` should tell you if it contains data. We had a weird problem before with some of the data where files were just empty, so I would like to check that.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/100507049/226775820-e12812df-855f-4b9b-826d-0a51f6dac9f0.png">
I also check /path/to/mro/kernels/ck and /path/to/mro/kernels/spk is not empty for the ESP_077168_2055 which are mro_sc_psp_230110_230116.bc and mro_psp_rec.bsp.

**Comment by acpaquette** [comment]
Right, sorry. I should have been more specific, can you check the kernels themselves? Like `ls -lah /path/to/mro/kernels/ck/mro_sc_psp_230110_230116.bc` and `ls -lah /path/to/mro/kernels/spk/mro_psp_rec.bsp`. 

We have had instances where the files have been copied over but the files themselves are empty

**Comment by ldx119** [comment]
> Right, sorry. I should have been more specific, can you check the kernels themselves? Like `ls -lah /path/to/mro/kernels/ck/mro_sc_psp_230110_230116.bc` and `ls -lah /path/to/mro/kernels/spk/mro_psp_rec.bsp`.
> 
> We have had instances where the files have been copied over but the files themselves are empty

<img width="466" alt="image" src="https://user-images.githubusercontent.com/100507049/226778646-786fd676-337c-4e8d-9491-2ded528d4f34.png">
OK, they are not empty.

**Comment by acpaquette** [comment]
Hmmm, I am stumped at this point. I think getting others to try and reproduce would be the key here. Just to confirm @ldx119, how did you download the data you are using?

**Comment by ldx119** [comment]
> Hmmm, I am stumped at this point. I think getting others to try and reproduce would be the key here. Just to confirm @ldx119, how did you download the data you are using?

At first, I fully obey the command from the website to access the ISISDATA https://github.com/DOI-USGS/ISIS3#how-do-i-access-the-isisdata-download-script-with-isis-700-or-earlier. However it lacks some of the spk and ck files which is the ck and spk files related to ESP_077168_2055, and then I manually download them from the website of https://naif.jpl.nasa.gov/pub/naif/MRO/kernels/.

**Comment by audiefen** [comment]
The error you are getting looks to me like maybe the mro_psp_rec.bsp on your system is not the latest? That kernel is ever growing and updated periodically. The error seems to indicate it doesn't cover the observation in question, which was taken fairly recently.

**Comment by ldx119** [comment]
> The error you are getting looks to me like maybe the mro_psp_rec.bsp on your system is not the latest? That kernel is ever growing and updated periodically. The error seems to indicate it doesn't cover the observation in question, which was taken fairly recently.

Thanks a lot. I use the spk/mro_psp_rec.bsp which is the latest, it works out.

**Comment by acpaquette** [comment]
@audiefen Thanks for the assist! @ldx119 I am guessing this has resolved your issue?

**Comment by ldx119** [comment]
> 



> @audiefen Thanks for the assist! @ldx119 I am guessing this has resolved your issue?
yeah. The issue that I encountered is I used the old version of spk/mro_psp_rec.bsp.I really appreciate your advice.
However, if I want to process the latest MRO HiRISE data, is there a convenient way to update my spice data? Because the MRO 
 spice data is really large.

**Comment by acpaquette** [comment]
@ldx119 The isisdata download scripts "should" avoid downloading already present data is nothing has changed. Ideally when you run the ISIS data download script, you would only update/download files that have been added or changed relative to the data you have local.

**Comment by ldx119** [comment]
> 

ok, I understand. Thank you very much for your patient explanation.
best wishes.
