### ISSUE TITLE
web=yes not working for LRO spiceinit (fixed?)

### ISSUE THREAD

**Issue by foobarbecue** [DOI-USGS/ISIS3#5150]
**ISIS version(s) affected**: I checked ISIS4 and ISIS7.1 and found the problem on both (but it probably has to do with the server rather than the client)

**Description**  
Trying to spiceinit LRO cubes using `https://services.isis.astrogeology.usgs.gov/cgi-bin/spiceinit.cgi` gives error:

`**ERROR** The Spice Server was unable to initialize the cube.  The error reported was: Unable to initialize camera model.`

If I use a machine with the kernels downloaded and remove `web=yes`, then `spiceinit` succeeds.

**How to reproduce**  
```
$ wget https://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0013/DATA/ESM/2012281/NAC/M1104273380RE.IMG
...
$ lronac2isis from= M1104273380RE.IMG to= M1104273380RE.cub
$ spiceinit from= M1104273380RE.cub web=yes
**ERROR** The Spice Server was unable to initialize the cube.  The error reported was: Unable to initialize camera model.
```

**Additional context**  
I have encountered this when starting with M1104273380RE.IMG, M1180855200RE.IMG, and M1192901040LE.IMG

I tried building and running spiceinit with the qtcreator debugger (fancy gdb), set a breakpoint in `SpiceClient::replyFinished` and I can see that the response contains `The ck rotation from frame -85600 can not be found due to no pointing available at requested time or a problem with the frame` as well as `Unable to initialize camera model` in different parts of the returned PVL.

**Comment by dlecorre387** [comment]
I'm also getting the same error when using `web=true` for ISIS 3.10.2. In fact I looped `spiceinit` over 50 LROC NAC images and received the error every time. Although admittedly I haven't tried `spiceinit` with the LRO kernels downloaded because I'm trying to avoid having to do that as much as possible!

**Comment by foobarbecue** [comment]
> Although admittedly I haven't tried spiceinit with the LRO kernels downloaded because I'm trying to avoid having to do that as much as possible!

Yeah... it's a 277.6 gigabyte download these days... I'm really hoping to avoid that :-p

**Comment by foobarbecue** [comment]
Also, at AWS standard rate of 9 cents per GB for that download, that would cost the USGS (and me, the taxpayer) $25!!

**Comment by dlecorre387** [comment]
Ouch... Good thing I'm not a US taxpayer then!

**Comment by foobarbecue** [comment]
Just gave up and downloaded it all. Only took an hour.

You know, this really would be the perfect use of distributed filesharing. Maybe I will set up a bittorrent tracker for spacecraft kernels. I guess USGS wouldn't support that, since the orthodoxy has determined that peer-to-peer is evil and giving all the data to a megacorp is the righteous path... but we can dream...

**Comment by foobarbecue** [comment]
Hunh, out of curiosity I tried moving the kernels out of isisdata and tried web=true and it worked on the same NACs it was failing on before. So, I assume the data has been fixed. @dlecorre387 is it working for you too?

**Comment by dlecorre387** [comment]
Yeah exactly, just to not have one single point of failure if you don't have >270 GB of storage available would be nice. To be fair though I did also just end up downloading the kernels too, but it took me more like 10 hours thanks to UK broadband speeds!

That's strange, I'll try and use `web=true` again and let you know if it works. I'll probably still use the local kernels in future since I can't use the web service AND specify a user DEM with my ISIS version (3.10.2) and I'm afraid that everything will break if I update to >4.4.0!

**Comment by dlecorre387** [comment]
Yep, looks like the web service is working for me now too. Strange...

**Comment by acpaquette** [comment]
This was a local data store issue that we had to handle internally. It should be fixed with more direct action coming to prevent it in the future.

Also @dlecorre387, what are your concerns regrading isis 4+?

**Comment by dlecorre387** [comment]
@acpaquette no particular concerns, it's just I have ISIS installed on my Windows laptop via an Ubuntu WSL w/anaconda. The instructions that I could find for doing this (where both the command line and GUI would work) was only for ISIS 3. I may try upgrading in future but for what I need right now 3.10.2 is more than sufficient it seems

**Comment by acpaquette** [comment]
@foobarbecue Can this be closed and reopened if the issue returns?

**Comment by foobarbecue** [comment]
@acpaquette sounds good.
