### ISSUE TITLE
: in filenames prevents cloning this repository on windows (NTFS)

### ISSUE THREAD

**Issue by foobarbecue** [DOI-USGS/ISIS3#5151]
**ISIS version(s) affected**: versions since Sep 2, 2021

**Description**  
Two filenames in this repository contain colons, and they cause `git clone` to fail when targeting NTFS or other filesystems that don't allow colons in filenames. The files are cubes for a test of TGO Cassis unstitch (I don't know what that is). They are here: https://github.com/DOI-USGS/ISIS3/tree/dev/isis/tests/data/tgoCassis/tgocassisunstitch

**How to reproduce**  
```
C:\Users\aacurtis>git clone git@github.com:DOI-USGS/ISIS3.git isis7
Cloning into 'isis7'...
Warning: Permanently added the ECDSA host key for IP address '192.30.255.113' to the list of known hosts.
remote: Enumerating objects: 154299, done.
remote: Total 154299 (delta 0), reused 0 (delta 0), pack-reused 154299
Receiving objects: 100% (154299/154299), 337.69 MiB | 14.19 MiB/s, done.
Resolving deltas: 100% (81678/81678), done.
error: invalid path 'isis/tests/data/tgoCassis/tgocassisunstitch/stitched-spice-2016-11-26T22:50:27.381_crop.cub'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Possible Solution**  
Rename these files and all references to them.

**Comment by acpaquette** [comment]
@foobarbecue I am only seeing the one file you pointed out. There are two files in the `isis/tests/data/tgoCassis/tgocassisunstitch/` directory but only one seems to be causing the issue.

**Comment by foobarbecue** [comment]
Whoops, you're right, it's just the one file.
