### ISSUE TITLE
README.md refers to decommissioned isisdist.astrogeology.usgs.gov

### ISSUE THREAD

**Issue by foobarbecue** [DOI-USGS/ISIS3#5152]
**Description**  

ISIS [has switched ](https://astrodiscuss.usgs.gov/t/replacing-the-usgs-isis-rsync-server/924)from distributing kernels using rsync modules at isisdist.astrogeology.usgs.gov to hosting in data sources specified in rclone.conf, primarily an Amazon S3 bucket called `asc-isisdata`. isisdist.astrogeology.usgs.gov was disabled in November 2022, but it's still referred to on the ISIS3 README.md:

https://github.com/DOI-USGS/ISIS3/blob/c3d975e1866567bb4a459679be942941691a4f9d/README.md?plain=1#L415-L425

**Possible Solution**  

Replace outdated information with a historical note explaining that isisdist.astrogeology.usgs.gov is no more . Better, bring isisdist.astrogeology.usgs.gov back up and set it up so that if a user tries to use it they get a notice pointing to the new data source (S3 bucket). The are references to isisdist.astrogeology.usgs.gov in all sorts of software (some of mine!) and documentation all over the web.

**Comment by ellequelle** [comment]
I was just about to open an issue about this! I can remove the rsync references from the readme.

**Comment by foobarbecue** [comment]
This appears fixed.
