### ISSUE TITLE
Offset occurred between RED HiRISE images.

### ISSUE THREAD

**Issue by luoflu** [DOI-USGS/ISIS3#5156]
**ISIS version(s) affected**: 6.0.0

**Description**  

I downloaded HiRISE RDR data of PSP_008871_1880_RED and ESP_020211_1880_RED from Planetary Data System, but their boundary is not matching (shown below).
![RCGL@O 44{58 RU4%E3Y_5](https://user-images.githubusercontent.com/103924277/225717831-0feb24b8-cc47-4117-b743-7a5f7fa4fc8b.png)

So I follow the standard routine suggested by ISIS online workshops to perform mosaic by using EDR data of these two images. The same problem still exists, though the offset is not quite the same (shown below). I also note that ISIS online workshops provide tutorials about HiRISE-to-HiRISE geometric control. The offset decreased slightly after registration, but the mismatch is still distinct.
![@@L)NMW5G0CYL4X%66P)QTT](https://user-images.githubusercontent.com/103924277/225717855-3bdd4ff5-1da4-4819-921e-cf44a3bf75ef.png)

**How to reproduce**  

The data can be obtained on the Planetary Data System (https://ode.rsl.wustl.edu/mars/productsearch), and they are all routinely processed by following the tutorials provided by ISIS online workshops (https://github.com/DOI-USGS/ISIS3/wiki/Working_with_Mars_Reconnaissance_Orbiter_HiRISE_Data).

**Comment by acpaquette** [comment]
@jlaura Any insight here with regard to processing the HiRise RDRs?

**Comment by jlaura** [comment]
Yes, the RDRs are not photogrammetrically controlled. Therefore, they have a priori pointing error on the order of 100-300m or so. I am looking for a reference now. I am not seeing these reported in [McEwen, et al. 2010](
https://www.sciencedirect.com/science/article/pii/S0019103509001808), but I might be missing them.

See [page 18 of the SIS](https://hirise-pds.lpl.arizona.edu/PDS/DOCUMENT/HIRISE_RDR_SIS.PDF). 


> The error is less than the accuracy of the camera pointing, approximately 100m...

They are really good products, but they will not have perfect alignment without relative (inter-image) or absolute (inter-image and MOLA) control.

**Comment by jlaura** [comment]
@luoflu I am going to close. Please re-open if you run into an offset related bug! Thank you for posting the issue with the great images.

**Comment by luoflu** [comment]
> Yes, the RDRs are not photogrammetrically controlled. Therefore, they have a priori pointing error on the order of 100-300m or so. I am looking for a reference now. I am not seeing these reported in [McEwen, et al. 2010](https://www.sciencedirect.com/science/article/pii/S0019103509001808), but I might be missing them.
> 
> See [page 18 of the SIS](https://hirise-pds.lpl.arizona.edu/PDS/DOCUMENT/HIRISE_RDR_SIS.PDF).
> 
> > The error is less than the accuracy of the camera pointing, approximately 100m...
> 
> They are really good products, but they will not have perfect alignment without relative (inter-image) or absolute (inter-image and MOLA) control.

Sorry for the late reply. I have attempted to remove the offset between two observations using HiRISE-to-HiRISE geometric control, which is not very effective. Therefore, I wonder if there is any other effective method capable of solving this problem or any suggestions for enhancement while performing HiRISE-to-HiRISE geometric control.

**Comment by jlaura** [comment]
@luoflu I do not know how you have attempted to geometrically control the images, so can not offer any suggestions on the effectiveness of your method. One option would be to use the [ASP bundle adjust](https://stereopipeline.readthedocs.io/en/latest/tools/bundle_adjust.html) tools as described [here](https://groups.google.com/g/ames-stereo-pipeline-support/c/m2GFMSUiCmc). Another option would be to use the ISIS tools as described [here](https://github.com/DOI-USGS/ISIS3/wiki/Working_with_Mars_Reconnaissance_Orbiter_HiRISE_Data#HiRISE-to-HiRISE-Geometric-Control-)
