### ISSUE TITLE
setisis /usgs/cpkgs/isis3/isis3mgr_scripts/initIsisCmake.sh 

### ISSUE THREAD

**Issue by YannChemin** [DOI-USGS/ISIS3#5157]
**Description**
https://github.com/DOI-USGS/ISIS3/wiki/Developing-ISIS3-with-cmake mentions a file in a hardcoded directory /usgs/cpkgs/isis3/isis3mgr_scripts/initIsisCmake.sh 

**Suggested Edit**
Make the /usgs/cpkgs/isis3/isis3mgr_scripts/initIsisCmake.sh available within the https://github.com/DOI-USGS/ISIS3/ tree somewhere

Thanks!

**Comment by Kelvinrr** [comment]
~~I think these docs are out of date, the updated instructions for that step spec are on the README. Under "Using the provided isisVarInit.py script"  https://github.com/DOI-USGS/ISIS3#isis-installation-with-conda~~

EDIT: Never mind, looking at it more I see what is happening.  Normally a file like that should be under scripts. Probably worth adding that script and updating the docs. Or simply put the command inline in the docs with the typical CMAKE args we use to build ISIS.

**Comment by Kelvinrr** [comment]
The script in question in on the internal gitlab's isis3mgr scripts repo. Probably tied to internal systems as part of an old build process. So maybe updating those docs to not mention the script and describe the current CMake process as it is now seems like the play. We are linking them in the readme so this seems like something to fix soon.
