### ISSUE TITLE
Installing ISIS on open SUSE 15.4

### ISSUE THREAD

**Issue by cartrite** [DOI-USGS/ISIS3#5168]
We use Github issues solely for discussing bugs, documentation issues, and new features.

For
questions about using ISIS or other ASC software, please use
any of the support alternatives: https://astrodiscuss.usgs.gov or https://gitter.im/USGS-Astrogeology/IAA

A great resource about asking high quality questions that generate high quality answers is available from the StackOverflow community: [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)

Thanks!

**Comment by cartrite** [comment]
Hi,
I used ISIS3 a few years back before it became ISIS 4. Anyhow, I tried to install with anaconda which failed because my glibc version was 2.3.1. So I tried miniconda3 and was successful in installing ISIS 7.2. Trouble started with the Data area. I used the downloadIsisData script and configured rclone. I ran into a few issues. I started by downloading the base folder which may have worked fine. I haven't checked yet. Next came the mro folder. My internet connection failed several times. I was able to restart but files that started downloading were skipped and the download started again with files that had not yet started their download. So I had a lot of incomplete downloaded files. After a day, the script said it was finished. The properties tab reported a folder with 6667 files at 305 gib. But when I tried running the downloadIsisData script again for any updates, the script tried downloading another 200+ gib's. I tried to modify the downloadIsisData script to replace the rclone command copy with sync. It is currently about 38% finished. The partion I have isis installed is 1tib. That partition has about 280 gib free. I also have lro and mex installed too. The properties tab for the mro folder says it has 7235 files at 307.2 gib's. This is what it also said before I started. Does this sound right?
cartrite

**Comment by cartrite** [comment]
Sorry, this is new to me and closed it by mistake.

**Comment by jlaura** [comment]
Hello @cartrite, 

Thanks for the question! I moved this over to [discussions](https://github.com/DOI-USGS/ISIS3/discussions/5170) and tagged it as a question. I hope that that is okay!  Perhaps @Kelvinrr you could offer some thoughts over there?
