### ISSUE TITLE
QT Concurrent Error for LROC NAC images

### ISSUE THREAD

**Issue by kbauck-usgs** [DOI-USGS/ISIS3#5169]
**ISIS version(s) affected**: 6.0.0, 7.1.0

**Description**  
When using Plurmy and LROC NAc image data, after some images process, isis programs fail with the following errors:
```
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
terminate called after throwing an instance of 'Isis::IException'
  what():  **I/O ERROR** Writing to the file [M1096293460LE.raw.cub] failed with writing [864256] bytes at position [378609664].
```

The above error continues for several different image files. Each time the original command it run a couple more image files finish processing. The process as a while seems to work better on isis6.0.0 than isis7.1.0.

**How to reproduce**  
Image files are downloaded from [here](https://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0005/DATA/SCI/2010287/NAC/) into a local directory. Images are then put into an images.lis script, then staged and processed using plurmy, example of command being run is below.

```
plurmy process -j preproc_lroc -t '01:00:00' -n 40 lrocnac_kirsten -e /caldera/projects/usgs/hazards/astro/apps/miniconda3/envs/isis6.0.0 "/home/kbauck/projects/lrocnac_control/bin/preprocess_lrocnac.sh"
```

The preprocess_lrocnac.sh script can be found in [GitLab](https://code.chs.usgs.gov/jlaura/lrocnac_control/-/blob/main/bin/preprocess_lrocnac.sh)

**Comment by Kelvinrr** [comment]
What ISIS application was running that created that exception?

**Comment by jlaura** [comment]
`lronac2isis` No logic before this other then activating the ISIS env and some basic bash string manipulation (e.g., basename).

**Comment by Kelvinrr** [comment]
Hmmmm, I don't think that lronac2isis is using the QT thread library? Maybe somewhere in the Cube writing process? 

The link to the script 404's, maybe permissions are closing off access? 

Until we get a chance to replicate, maybe a good workaround for now is to try changing your IsisPreferences to limit the number of threads:

```
Group = Performance
  CubeWriteThread = Never
  GlobalThreads = 1
EndGroup
```

**Comment by kbauck-usgs** [comment]
You should have permissions to the script now, sorry about that, and I will try your suggestion, thank you!

Before that script all we do is call a query to the database using postgressql, in a complete different bash file command, that seems to be working well. [script before preprocess_lrocnac.sh](https://code.chs.usgs.gov/jlaura/lrocnac_control/-/blob/main/bin/create_filelist.sh)
