### ISSUE TITLE
Change jigsaw cholmod calls from 32bit to 64bit

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#5176]
**ISIS version(s) affected**: At least 3.7.0 and up (probably older versions too)

**Description**  
jigsaw fails for some large networks with a cholmod error indicating "problem too large." See instance of this in [#5173](https://github.com/DOI-USGS/ISIS3/issues/5173) and [#3871](https://github.com/DOI-USGS/ISIS3/issues/3871). A photogrammetrist and former employee suggested changing the cholmod calls from 32bit to 64bit. This is a simple test that should be pursued.

**How to reproduce**  
See [#5173](https://github.com/DOI-USGS/ISIS3/issues/5173) and [#3871](https://github.com/DOI-USGS/ISIS3/issues/3871) for details.

**Possible Solution**  
According to the cholmod docs (a copy is located in my work users under ISIS, see page 37) simply replace calls to cholmod_* with cholmod_l_*. So for example, cholmod_super_symbolic becomes cholmod_l_super_symbolic.

One could imagine future implementations in which the user indicates at run time whether to use 32 or 64bit.

**Additional context**  
This is not an enhancement. This is a suggested solution for a bug that has been plaguing us for some time. It may be a long shot, but unless this is more difficult then we've been lead to believe, it seems worth trying. The solution was proposed in [#5173](https://github.com/DOI-USGS/ISIS3/issues/5173) and I wanted to call it out as it's own issue.

**Comment by lwellerastro** [comment]
There is a small Kaguya TC 21 image network available for simple testing under my work users area Isis3Tests/Jigsaw/Cholmod64/.  See network KTC_small.net and associated images KTC_small.lis which points to images under a Lev0/ directory.  The images take up <1G of space.

I ran jigsaw on this network using the following parameters (output in directory):
```
jigsaw fromlist=KTC_small.lis cnet=KTC_small.net \
onet=JigOut_KTC_small.net \
radius=yes \
sigma0=1.0e-10 maxits=10 \
camsolve=accelerations twist=yes overexisting=yes \
spsolve=position overhermite=yes \
spacecraft_position_sigma=1000 \
camera_angles_sigma=0.25 camera_angular_velocity_sigma=0.1 camera_angular_acceleration_sigma=0.01 \
point_radius_sigma=100 file_prefix=RadAccelTwist_SpkPos

```

**Comment by lwellerastro** [comment]
A handful of updates:

- The above data set used for initial tests demonstrated the results for cholmod 64 bit matches those for 32 bit (run under 8.0.0 LTS).
- The network and images referenced in #5173 have successfully bundled using the cholmod 64 updates
This jigsaw run only required 75G of memory
Additional tests are currently running on larger versions of the Kaguya TC dataset (latitudes +/-60 data; no poles) - TBD

- Jigsaw segfaults when errorprop=yes
Believed to have missed some 64 bit changes to that bit of code - that is being looked into and will require more testing

Large, previously successful networks for other datasets have also been run under the cholmod 64 version of jigsaw with success.  In nearly every case the results are identical to the 32 bit version.  Differences so far have only been noted for Cassini ISS (titan) and those are not concerning but need a little more scrutiny.

Intend on testing the LROC NAC south pole network that originally surfaced this issue as well.

Update: The errorprop seg fault has been addressed - just a missed call that needed to be updated to the 64 bit version.

**Comment by lwellerastro** [comment]
Final update - A global Kaguya TC control network (90S-90N, 0-360E) has bundled successfully! 
42 hours, 167G of memory, solving for radius, camera accelerations and spacecraft position.

    Number of Images = 168154
    NumberOfPoints   = 11786686
    NumberOfMeasures = 45916089
