### ISSUE TITLE
rsync - server does not work

### ISSUE THREAD

**Issue by jlrizos** [DOI-USGS/ISIS3#5179]
**ISIS version(s) affected**: x.y.z
3.5.2.0 and earlier

**Description**  
I am trying to make an ISIS installation using the classic approach:
https://isis.astrogeology.usgs.gov/documents/LegacyInstallGuide/index.html. 

However, the server is not responding. 

**How to reproduce**  
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::x86-64_darwin_OSX/isis .

rsync error: error in socket IO (code 10) at /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/rsync/rsync/clientserver.c(106) [receiver=2.6.9]

**Comment by jlaura** [comment]
The rsync server is not longer available. Please see https://github.com/DOI-USGS/ISIS3#full-isis-data-download and use the new datadownload script. 

Also, please consider upgrading to a newer version of ISIS.

**Comment by ericepalmer** [comment]
Please fix your main documentation.
Your USGS main website continues to provide this as a valid means of installation.  All links should be updated to correct information.
https://isis.astrogeology.usgs.gov/7.0.0/documents/LegacyInstallGuide/index.html
