### ISSUE TITLE
Anaconda/ISIS 3.6.0 installation issue

### ISSUE THREAD

**Issue by wterryf** [DOI-USGS/ISIS3#518]
I had the same issue with having to add the conda-forge channel, but once past that, the install step fails with a dependency conflict:

```
bash-3.2$ conda install -c usgs-astrogeology isis3
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - isis3 -> armadillo==8.200.0 -> arpack -> *[track_features=blas_openblas]
  - qtconsole
Use "conda info <package>" to see the dependencies for each package.
```

Not sure how to proceed. This is on MacOS 10.13.6 (High Sierra)

**Comment by ihumphrey** [comment]
@wterryf Could you run the following command?

```bash
conda config --show channels
```
If `conda-forge` is above `usgs-astrogeology`, you will need to run:

```bash
conda config --add channels usgs-astrogeology
```

This should put the `usgs-astrogeology` channel at the top, making it the first place to look for dependencies. (the release candidate announcement previously had `--append` instead of `--add`)

**Comment by wterryf** [comment]
thanks! I moved the usgs-astrogeology channel to the top of this list with that command, but I'm still getting exactly the same error.

**Comment by ihumphrey** [comment]
We have re-uploaded a macOS isis3 conda package, and here are some instructions to reconfigure your conda that should hopefully fix the issue.

First, clean the package cache.

```bash
conda clean --all
```

After running this command, you will get a few prompts that say ` Proceed ([y]/n)? `. Type in `y` and hit enter after each one.

Next reset the channel priorities.

```bash
conda config --add channels conda-forge --add channels usgs-astrogeology
```

This will force the channel priority to be usgs-astrogeology at the top, followed by conda-forge, followed by defaults. This will ensure that we are getting the correct dependencies.

For the next command, make sure the environment you created is active (either `source activate environmentname` or `conda create -n environmentname; source activate environmentname`, with the name of the environment you created or want to create)

```bash
conda install -c usgs-astrogeology isis3
```

This will grab the updated isis3 package and should grab the correct dependencies and install them into the active environment.

**Comment by wterryf** [comment]
Hi Ian:

Thanks bunches, this worked! I had to fiddle around a bit with my environment because I also have a 3.5.3 version installed, but once I set ISISROOT correctly, I was able to run qview and load a HiRISE cube, and also was able to run cubenorm.

**Comment by celbal** [comment]
@wterryf If your problem was solved could you please close this issue? Thank you

**Comment by wterryf** [comment]
thanks very much for all the help, I'll close this.
