### ISSUE TITLE
Command Line Reference documentation link for ISIS3 is bad

### ISSUE THREAD

**Issue by meganhenriksen** [DOI-USGS/ISIS3#5180]
**Description**

Under 'Explore in More Detail' page (https://isis.astrogeology.usgs.gov/7.0.0/UserExplore/index.html), the link to the Command Line Reference currently links to:
https://usgs-astrogeology.github.io/ISIS3/ISIS_Cube_Format.html

This is both a bad link and doesn't seem like it would have been correct.

**Suggested Edit**

Thanks!

**Comment by antonhibl** [comment]
@meganhenriksen Hi Megan, looks like that link needs to be updated in our documentation; here is the correct link for that: [ISIS Cube Format](https://doi-usgs.github.io/ISIS3/ISIS_Cube_Format.html). Thanks for opening up an issue!

**Comment by lwellerastro** [comment]
The Special Pixels and Base/Multiplier links are broken as well. The Map Definition link sources back to that page's index.html.
Might be worth running through them all.

**Comment by meganhenriksen** [comment]
I was actually trying to get to the Command Line Reference, not the ISIS Cube Format, so the Command Line Reference was linking to the wrong thing as well.

**Comment by antonhibl** [comment]
@meganhenriksen well in any of these broken link cases what you can typically do is replace the usgs-astrogeology in the url with doi-usgs. We will be going through to fix these links for the next release of ISIS.

**Comment by meganhenriksen** [comment]
It's difficult to replace without knowing what the correct bad link (if that even makes sense) is. The command line reference probably should link to something like 'Command_Line_Reference.html' and not Isis_Cube_Format.html? (Note: this is not correct even with the doi-usgs). But that would just be me guessing. 

In additional several of the links on that page still work and link to something like: [Preference Dictionary](https://isis.astrogeology.usgs.gov/7.0.0/documents/PreferenceDictionary/PreferenceDictionary.html) in which case maybe the correct link is something like: https://isis.astrogeology.usgs.gov/7.0.0/documents/CommandLineReference/CommandLineReference.html (though this doesn't work, I tried)

I know I'm being pendantic, but you can't just do a find/replace with usgs-astrogeology and doi-usgs to fix this so I want to make sure both aspects of this (broken link and wrong thing being linked) are being addressed.

**Comment by antonhibl** [comment]
@meganhenriksen These issues are going to be addressed in the next release of ISIS. It seems the site you are looking for is https://isis.astrogeology.usgs.gov/documents/CommandLine/CommandLine.html.

**Comment by AustinSanders** [comment]
@antonhibl Is this closable as of #5182 ?

**Comment by antonhibl** [comment]
@AustinSanders yes this should be good to close, all the links I was aware of are addressed now.
