### ISSUE TITLE
Issue with spiceinit on Galileo SSI image and data pool (USGS updated kernels)

### ISSUE THREAD

**Issue by steo85it** [DOI-USGS/ISIS3#5196]
**ISIS version(s) affected**: 7.2.0

**Description**  

I am trying to process/calibrate several Galileo SSI images of Europa and I'm getting some trouble with `spiceinit` and kernels availability.
When I run spiceinit on Galileo SSI image `7200r` (aka, `11ESCOLORS01-01_GalileoSSI_Equi-cog`), I get an error 
```
Group = Kernels
  NaifFrameCode             = -77001
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = $base/kernels/pck/pck00009.tpc
  TargetPosition            = ($base/kernels/spk/de430.bsp,
                               $base/kernels/spk/jup310.bsp)
  InstrumentPointing        = $galileo/kernels/ck/CKmerge_type3.plt.bck
  Instrument                = Null
  SpacecraftClock           = $galileo/kernels/sclk/mk00062b.tsc
  InstrumentPosition        = ($galileo/kernels/spk/s980326b.bsp,
                               $galileo/kernels/spk/jup310.bsp)
  InstrumentAddendum        = $galileo/kernels/iak/ssiAddendum005.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
  **Error                     = "Spice file does not exist
                               [$base/kernels/galileo/kernels/spk/s980326b.bsp]"**
End_Group
```
which makes sense since kernel "s980326b" does not exist in the $ISISDATA area, only the "s980326a" version. Symlinking `a` to `b` seems to work, when checking the result of `cam2map`, but I don't think that's the normal behaviour. 
Any suggestions? Thanks!

Also, I wonder where the new USGS kernels mentioned in #4254 and  [Bland et al, 2021](https://doi.org/10.1029/2021EA001935) are stored, as I only get the NAIF kernels downloaded to my $ISISDATA. Thanks!

**How to reproduce**  

Download image [7200r](https://pdsimage2.wr.usgs.gov/archive/go-j_jsa-ssi-2-redr-v1.0/go_0020/e11/europa/c042061/7200r.lbl), then
```
gllssi2isis from=7200r.lbl to=7200r.cub
spiceinit from=7200r.cub spksmithed=false cksmithed=false # (same with *smithed=True)
```

**Comment by lwellerastro** [comment]
Hi @steo85it, I've run a couple of tests against your test file and find that I can not reproduce the "Spice file does not exist" error you encountered.  The kernels group for my run appears identical to what you provided and galileo/kernels/spk/s980326b.bsp exists where expected.

It sounds like a problem with your data area - have you tried to download that particular directory again? In theory, the data area I access should be identical to what the public can access.  Maybe the download script has an omission? I'm not sure how one checks on this though.

`Also, I wonder where the new USGS kernels mentioned in https://github.com/DOI-USGS/ISIS3/issues/4254 and [Bland et al, 2021](https://doi.org/10.1029/2021EA001935) are stored, as I only get the NAIF kernels downloaded to my $ISISDATA. Thanks!`

The kernels produced by the Bland et al work should be available by setting cksmithed=true in the spiceinit command line.  The kernels.db file will apply the new camera and pck kernels to the image (and that image is in the kernel).  Here's what your label should look like when run successfully:

```
spiceinit from=7200r.cub cksmithed=true

Group = Kernels
    NaifFrameCode             = -77001
    LeapSecond                = $base/kernels/lsk/naif0012.tls
   TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
                                 $galileo/kernels/pck/pck00010_msgr_v23_europa-
                                 2020.tpc)
    TargetPosition            = ($base/kernels/spk/de430.bsp,
                                 $base/kernels/spk/jup310.bsp)
    InstrumentPointing        = $galileo/kernels/ck/galssi_eur_usgs2020.bc
    Instrument                = Null
    SpacecraftClock           = $galileo/kernels/sclk/mk00062b.tsc
    InstrumentPosition        = ($galileo/kernels/spk/s980326b.bsp,
                                 $galileo/kernels/spk/jup310.bsp)
    InstrumentAddendum        = $galileo/kernels/iak/ssiAddendum005.ti
    ShapeModel                = Null
    InstrumentPositionQuality = Reconstructed
    InstrumentPointingQuality = Smithed
    CameraVersion             = 1
    Source                    = isis
  End_Group
```
The new kernels are TargetAttitudeShape $galileo/kernels/pck/pck00010_msgr_v23_europa2020.tpc and InstrumentPointing $galileo/kernels/ck/galssi_eur_usgs2020.bc. You probably should make sure those are available in your download before you try this (and after you recover the missing kernel in your post).

**Comment by steo85it** [comment]
> galileo/kernels/spk/s980326b.bsp exists where expected.
It sounds like a problem with your data area - have you tried to download that particular directory again?

Hi @lwellerastro, thanks for the check and feedback! I'm a bit surprised, I actually did try to redownload my data-area for Galileo (and other missions) several times and on several different machines, and I always end up with the `xxxa.bsp` kernels, never with `xxxb.bsp` ones (which is also what I can see on the [NAIF website](https://naif.jpl.nasa.gov/pub/naif/GLL/kernels/spk/)  ).

>You probably should make sure those are available in your download before you try this (and after you recover the missing kernel in your post).

That's good, those kernels worked as expected, thanks for confirming those `ck` and `pck` are indeed the "only updates" (I thought the orbit `spk` had been updated, too, but I couldn't find any new file).

**Comment by lwellerastro** [comment]
Hi @steo85it, you still might need a hand from one of our developers to figure out what's going on with s980326b.bsp.  Just a basic diff between the a and b version shows there is something different, but I don't know what:
`Binary files galileo/kernels/spk/s980326a.bsp and galileo/kernels/spk/s980326b.bsp differ`

I just confirmed that when I created the smithed kernels for Europa, s980326b.bsp was one of the kernels applied to the images and the new kernels are based upon that.  You might not get truly "smithed" kernels with the "a" version of that spk file.  When working with multiple images you might see mis-matches among overlapping features. We did not update the orbits due to lack of ground points.  We just made sure the prime meridian defining crater Cilix was where it needed to be which is what was tweaked in the pck file. You can see the adjustment by comparing the updated pck to what's in the /base/kernels/pck00010_msgr_v23.tpc - just a little nudge.

I honestly don't know what the pedigree is of s980326b.bsp, but I can see in "frozen" old data areas that it has been around since 2005.  However, I don't see it in the galileo naif pds archive [here](https://naif.jpl.nasa.gov/pub/naif/GLL/kernels/spk/).  You could take your chances with "a" until you hear from someone in our dev group.

**Comment by steo85it** [comment]
Thanks for the additional check! When I check ortho-images based on the "smithed" and "reconstructed" kernels, I clearly see a huge improvement in alignment between images (thanks for those products!), but indeed I also noticed some residual (minor) differences w.r.t. the mosaics attached to the Bland et al, 2021 paper ... maybe using the "a" vs "b" kernels might be the cause?

Is there someone specific from the dev group that I could "tag" in this issue? It would indeed be nice to also have the "b" kernels available, if those are the "reference ones" for those smithed ck and pck. Thanks!

**Comment by lwellerastro** [comment]
I'll let someone know, but a time frame for assistance isn't possible provide.

**Comment by Kelvinrr** [comment]
A few weird things here.

1. The path is a little weird in your spiceinit output. .`$base/kernels/galileo/kernels/spk/s980326b.bsp` should be `$galileo/kernels/spk/s980326b.bsp`. Maybe something about your data install? 

2. more importantly, it does seem that kernel is just gone. 
NAIF records don't have it: https://naif.jpl.nasa.gov/pub/naif/GLL/kernels/spk/
Neither do ours on the buckets s3://asc-isisdata/isis_data/galileo/kernels/spk/

so idk where this kernel is supposed to come from. I could just add it from the existing internal repository to the bucket, but it would be nice to know where it is supposed to come from.

**Comment by steo85it** [comment]
Hi @Kelvinrr , thanks for the quick feedback! 
1. that's ok, I modified that line by hand to replace my "local path" (and got the replacement wrong);
2. interesting! on the other hand I don't see any notable differences when testing the "b" kernel on a few images, so I'm wondering if there are significant differences between the trajectories (other than, say, in the headers). I could try a spkdiff for a relevant time period, just to make sure, but indeed it would be nice to trace their "history".

That said, even if the `a` and `b` kernels turn-out to be the same, it would be good to update which kernel `spiceinit` looks for, to avoid manually having to create a symlink.

**Comment by lwellerastro** [comment]
@Kelvinrr, I see what you see as far as s980326b.bsp not being present in the naif archive, but I'm honestly not sure we can just ditch it.  For one thing spiceinit expects its existence and at least locally loads the kernel just fine.  More concerning though is that kernel has been available for a very long time and our Europa smithed kernels are dependent upon it.  I'm not sure what the outcome would be if the kernel no longer existed and someone used cksmith=true for the Europa data.

The OP's file and various tests are available under my work area at Isis3Tests/Spiceinit/GalileoSSI.  The PublicData/ directory has a run where I set my isisdata area to isis3_efs/isis_data/ which I thought was the same as what the public sees, but apparently not.  You can see in each test case the image picks up s980326b.bsp.  I think we have to supply this kernel to all users.

**Comment by steo85it** [comment]
>  I'm not sure what the outcome would be if the kernel no longer existed and someone used cksmith=true for the Europa data.

I suppose that "that someone" would get an error message such as the one I got. ;) 

And agreed, it would be good to have the "b" out and available (also, I just checked a few cases, and those kernels might differ somewhere else) and even better to know "why" this different kernel exists (not easy to reconstruct, I know...). Thanks again!

**Comment by lwellerastro** [comment]
`I suppose that "that someone" would get an error message such as the one I got. ;)`

lol - yes of course!  But I meant in terms of the smithiness of the geometry.  If we were to have "b" point to "a" and call it good, would the results be the same?  If they are identical, yes, but I doubt it.  We don't have funding or time to reproduce the kernels (input would have to be updated) and recreate all the level 2 products. We need to get the "b" kernel back out to the public which is easy, but determining why that file no longer exists in the online archive is probably a lost cause. I'm not sure it matters though - we used it and it's baked into our products and the software, we need it back.

**Comment by Kelvinrr** [comment]
I'll add it to the S3 buckets for now, it would be possible to open the kernels via the toolkit and see concrete differences in the segments, but I feel the bigger question is why was it there to begin which and who is responsible for hosting it, if it is NAIF, why did it disappear? Seems the NAIF archive for the SPKs was edited in 2022 so I imagine it was removed for a reason. 

This is a bigger problem to solve when/if we get to doing some kernel accounting in the future, short term I'll add the kernel to the buckets and we'll host it until we know more.

**Comment by steo85it** [comment]
That sounds good to solve this specific issue, thanks! And there are indeed a couple new Galileo's `spk`s produced by JPL (I just quickly checked the `lbl` the other day), which seemed unrelated to Bland et al, 2021's effort. Probably a good idea to ask someone at NAIF about what happened there...

**Comment by Kelvinrr** [comment]
the following files were missing from the NAIF galileo SPK archive:

```
s000407a.bsp
s000615a.bsp
s020128a.bsp
s021119a.bsp
s030129a.bsp
s980326b.bsp
s990114a.bsp
```

I copied these to the usgs_data/ folder of our public S3 buckets so we're hosting these for now at s3://asc-isisdata:/usgs_data/galileo/kernels/spk/, so they should be downloadable via script/rclone again. 

@steo85it try re-downloading via script and they should be there now.

**Comment by steo85it** [comment]
Done! I confirm that the kernels are now available, thank you for your help!
