### ISSUE TITLE
ISIS3 support for RedHat 8

### ISSUE THREAD

**Issue by sanwar0asu0edu** [DOI-USGS/ISIS3#5199]
I am looking to install ISIS3 on a RedHat 8 linux machine, but don't see that as an option. Is a RedHat 8 release planned? Thanks.

**Comment by Kelvinrr** [comment]
I don't think we support it or have any plans to support it. Are there specific issues you are running into that you think are specific to redhat8? If it's a large pain a dockerized install might be an option.

**Comment by sanwar0asu0edu** [comment]
We want to run it on our local cluster to process data in bulk. I can't see how a docker container would work for this situation.

**Comment by jlaura** [comment]
Assuming that you have docker installed on your cluster (and you are allowing the containers to run with root privileges; the containers require root), you can mount a host directory containing data into the container, and run your processing in the container. Output can then go to the same or a different host to container mounted directory. 

There is no plan to support RH8 at this time. If you are having specific installation issues using conda, please re-open and post those.
