### ISSUE TITLE
Reminder to update Zenodo DOI for each LTS (or maybe RC) release

### ISSUE THREAD

**Issue by thareUSGS** [DOI-USGS/ISIS3#5200]
**Description**
Simply a reminder that which each release, a Zenodo version should be tagged. I don't really have a preference if a new DOI version is needed for each LTS or for every RC release. 

last version tagged I think is ([Version 7.2.0_RC1](https://zenodo.org/record/7644616))

**Comment by AustinSanders** [comment]
The zenodo json file was updated for 8.0.0_RC1 via https://github.com/DOI-USGS/ISIS3/pull/5191 -- is there a separate step to trigger a push to zenodo.org?  I was responsible for the 2 most recent releases that are missing from zenodo.  I must have missed that step, but the release process docs don't seem to include anything, so I figured this would be performed automatically when a new version was tagged on the repo.

What did I miss?

**Comment by AustinSanders** [comment]
Could this be the result of moving from 
https://github.com/USGS-Astrogeology/ to https://github.com/DOI-USGS/ ? 

The resource is still listed as ``` Related identifiers:
Supplement to
https://github.com/USGS-Astrogeology/ISIS3/tree/7.2.0_RC1```

**Comment by rbeyer** [comment]
Could be.  Zenodo can be set (and was in this instance, I would imagine) to watch a repo, and to trigger Zenodo DOI-minting every time a GitHub repo signals a "Release."  So moving the content to a different repo, means that Zenodo is still probably watching for changes to the old repo, which will never happen.

I also thought that there was some kerfuffle that the USGS itself needed to issue DOIs for ISIS, and that the easy, convenient mechanism via the GitHub/Zenodo integration wasn't good enough for the Department of the Interior.

**Comment by jlaura** [comment]
FYI - If this is a USGS software release (which it should be), then the DOI **can not** be minted by Zenodo. The DOI has to be minted by the USGS DOI tool. Since a new DOI is being minted, it is necessary to step through the DOI software release process. Any ASC employee that needs help with this, just ping me on teams.
