### ISSUE TITLE
lronaccal fails for 3.10.2

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5201]
**ISIS version(s) affected**: 3.10.2 and possibly older

**Description**  
Versions of isis prior to 4.0.0 can no longer ingest LRO NAC images due missing translation file (due to data are re-structure).

**How to reproduce**  
See file under my work area Isis3Tests/Spiceinit/LROC/I3.10.2 

```
lronac2isis from=M1287791450RE.IMG to=M1287791450RE.cub

  Group = Error
    Program = lronac2isis
    Class   = "I/O ERROR"
    Code    = 4
    Message = "Unable to open
               [$ISIS3DATA/base/translations/pdsImage.trn]"
    File    = Pvl.cpp
    Line    = 86
  End_Group
```
Note that I removed the leading path in the error message and added $ISIS3DATA.

**Possible Solution**  
The problem here is the the referenced ISIS3DATA location no longer exists. I'm not sure how to resolve this.

**Additional context**  
The reason I am going back to this older version is to have spiceinit access the isis driver instead of the ALE driver which is picked up for all versions of isis starting with 4.0.0. 

There are also errors (again looking for files that exist in a new location) for the situation where an isis4.4.0 spiced image (or simply ingested) is copied into my working area and has spiceinit run on it under 3.10.2:

```
spiceinit from=isis4.4.0_M1287791450RE.cub spksmithed=true
terminate called after throwing an instance of 'Isis::IException'
  what():  **I/O ERROR** Unable to open [$ISIS3DATA/base/templates/labels/CubeFormatTemplate.pft] in Pvl.cpp at 86.
Abort (core dumped)
```
Again, I replaced the leading path information with $ISIS3DATA. Going backwards like this might not be expected to work though, but it's not clear to me how to work with LRO NAC data and avoid using the ALE driver if desired.

I think this is somewhat related to #4966

**Comment by AustinSanders** [comment]
This should be resolved in later versions of ISIS, and ISIS 3.10 does not receive regular backports or bugfixes. I'm closing as a "wont fix" for now, but this can be revisited if there's significant need.
