### ISSUE TITLE
Spiceinit for "other" images

### ISSUE THREAD

**Issue by ldx119** [DOI-USGS/ISIS3#5206]
**ISIS version(s) affected**: x.y.z

**Description**  

**How to reproduce**  

**Possible Solution**  

When I wanted to process the other exploration data which may not ingested by NASA. I currently have made some CK and SPK  related to the image（According to the tutorial of NAIF）. Simply loading CK and SPK files may not solve the problem, it reports an error(please see the attachment). Please ask how to make Spiceinit can run this kind of image data. Or is there another way or suggestion to make it successful? Thank you very much!
**Additional context**  
![74a1d42fd63b66e9f561113b27c87ed](https://github.com/DOI-USGS/ISIS3/assets/100507049/f71eaafe-92ac-453e-b661-30359c3fb05a)

**Comment by AustinSanders** [comment]
Hi @ldx119 , thanks for submitting this issue.  In order to resolve this issue, we'll need some additional information about how to reproduce the error.

It appears that the file you are attempting to process is missing the "MissionName" keyword -- are you processing a valid ISIS .cub file?  For which mission are you attempting to run spiceinit?  If the image that you are attempting to process is public, you might consider posting a link to the data source.

**Comment by ldx119** [comment]
> Hi @ldx119 , thanks for submitting this issue. In order to resolve this issue, we'll need some additional information about how to reproduce the error.
> 
> It appears that the file you are attempting to process is missing the "MissionName" keyword -- are you processing a valid ISIS .cub file? For which mission are you attempting to run spiceinit? If the image that you are attempting to process is public, you might consider posting a link to the data source.

The mission is TianWen1. The .cub should be valid,I use raw2isis to the 2B data from High-Resolution Imaging Camera (HiRIC), and then use spiceinit to the .cub , it reports the error.
https://moon.bao.ac.cn/web/zhmanager/mars1


</body>
</html>

**Comment by ldx119** [comment]
> 



> Hi @ldx119 , thanks for submitting this issue. In order to resolve this issue, we'll need some additional information about how to reproduce the error.
> 
> It appears that the file you are attempting to process is missing the "MissionName" keyword -- are you processing a valid ISIS .cub file? For which mission are you attempting to run spiceinit? If the image that you are attempting to process is public, you might consider posting a link to the data source.

I confirm the image that I process is public.The way to obtain data is to download only by registering (there is no restriction on registration, anyone can register)

**Comment by ldx119** [comment]
> > Hi @ldx119 , thanks for submitting this issue. In order to resolve this issue, we'll need some additional information about how to reproduce the error.
> > It appears that the file you are attempting to process is missing the "MissionName" keyword -- are you processing a valid ISIS .cub file? For which mission are you attempting to run spiceinit? If the image that you are attempting to process is public, you might consider posting a link to the data source.
> 
> The mission is TianWen1. The .cub should be valid,I use raw2isis to the 2B data from High-Resolution Imaging Camera (HiRIC), and then use spiceinit to the .cub , it reports the error. https://moon.bao.ac.cn/web/zhmanager/mars1

2B data is from https://moon.bao.ac.cn/web/zhmanager/kxsj?missionName=HX1&zhName=HiRIC&grade=2B

**Comment by jlaura** [comment]
@ldx119 ISIS has neither a sensor model nor an ingestion program for that sensor. Are the SPICE kernels and a Software Interface Specification publicly available for those data? If so, would you please link them in your response.

**Comment by ldx119** [comment]
> @ldx119 ISIS has neither a sensor model nor an ingestion program for that sensor. Are the SPICE kernels and a Software Interface Specification publicly available for those data? If so, would you please link them in your response.

I don't think there is a complete set of SPICE kernels at present. I just made some ck and spk kernels according to NAIF's SPICE tutorial. I want to use Spiceinit to add geographic information to the original image(.cub). So is there any way to make it a success?
