### ISSUE TITLE
Running findrx changes the geometry of Voyager images

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#5208]
**ISIS version(s) affected**: 7.0.0

**Description**  
The findrx application is intended to refine the position of reseaux in images and update their locations in the cube label (see https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/findrx/findrx.html). However, running findrx also modifies the cube geometry in an unknown way. These changes are not inconsequential: in the example I looked at the longitude changed by almost a full degree! (that's 23 km on the surface!). This is either a bug or extremely poor documentation.

**How to reproduce**  
1. Grab a fresh Voyager 2 image
2. Run voy2isis to ingest
3. run spiceinit (default kernels are fine)
4. run campt (I let it default to the center pixel)
5. run findrx
6. run campt again (same pixel as step 4)
7. compare the results 

I have provided such a comparison in my work directory under /Triton-Voyager/2023/findrx-issue/

**Possible Solution**  
I think its imperative to understand what findrx is actually doing. I took a look at the code and I don't see where/how it could be affecting image geometry - seems to be the expected pattern matching. However, I don't have nearly enough experience with ISIS or C++ to understand all that's going on.

**Additional context**  
I was using findrx for Voyager 2 images of Triton. I don't know if the same thing happens for other data sets with reseaux (if there are any). This was done in the context of building a "global" control network, and I actually found that my results were "better" if I rand findrx. This makes me wonder if, in addition to identifying the reseaux locations, ISIS is updating the image distortion using those locations (that's what reseaux are for, right?). If that's what happening (and this is wild speculation) then the documentation needs to say that and findrx should use a "to=" parameter so that the original cube is not overwritten.

**Comment by amystamile-usgs** [comment]
@blandoplanet So I took a look at findrx and it looks like it is only updating the cube label's Reseau group with the updated positions of the Reseau points. I confirm that the findrx documentation does specify that the label is being updated with these new points. But when you have an image that has spice data and you run applications like campt or qview, it will create a camera model and within the camera model it does in fact grab the new reseau information from the label and runs ReseauDistortionMap which updates the image distortion using these new locations.

**Comment by blandoplanet** [comment]
Thanks, @amystamile-usgs. That makes perfect sense, but I'm not sure this is desirable behavior. Well, it is and it's not - obviously one wants to remove the distortion in the best way possible, but at the moment it's kind of hidden from the user and that can lead to several problems (below). At a minimum it needs to be documented better. 

Problems with the current implementation:
1. It's not obvious from the documentation that running findrx has the practical effect of changing the distortion. The current documentation gives the impression that findrx simple provided better information for remrx. Since removing the reseaux is a cosmetic change, users may or may not use either program. This was how I first discovered the "issue." I specifically wanted to create a mosaic that included the reseaux but had identical geometry to one that had them removed. Thus I intentionally did not run either findrx or remrx. 
2.  Similarly, if I release updated ck kernels (we can debate elsewhere whether that's a good idea), a user that applies those kernels and then runs findrx could potentially unknowingly change the geometry (in practice).
3. findrx simply overwrites the existing cube label. This makes it difficult to tell that something significant has changed.

Possible Solutions:
1. At a minimum a warning should be added to the user documentation (https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/findrx/findrx.html) that says something like: "The user should be aware that refining the reseaux locations will modify the image distortion once applications that utilize the camera model (campt, qveiw, etc) are used. Thus findrx has the practical affect of changing the geometry of the image." This change would be very easy.
2. Because findrx has a significant impact on images, it would be better if it utilized a "to=" parameter rather than simply overwriting the existing cube label. This hopefully makes it clearer to the user that something significant has changed and it also facilitates direct comparison because the user has access to both the pre- and post-findrx cubes. I have no idea whether such a change is difficult or not. This may also not be standard ISIS practice, since applications that change image geometry but don't actually modify pixel values don't seem to have a "to" parameter (e.g., spiceinit, or jigsaw with update=true).

**Comment by amystamile-usgs** [comment]
I am hesitant to change the parameters since this could break existing pipelines and applications such as [vikclean](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/vikclean/vikclean.html).  I don't believe there is a standard in isis of whether to include the `to` parameter based on overwriting existing cubes. But I think the least we could do here is provide better documentation.

**Comment by amystamile-usgs** [comment]
There may also be something wrong with how the reseaus are being updated specific to voyager 2 images. I tested findrx on a viking image and it did make some changes to the geometries(differences in campt) but not enough to change the lat/lons and see a shift in qview. So I keep looking into if there is something else going on.

**Comment by amystamile-usgs** [comment]
> There may also be something wrong with how the reseaus are being updated specific to voyager 2 images. I tested findrx on a viking image and it did make some changes to the geometries(differences in campt) but not enough to change the lat/lons and see a shift in qview. So I keep looking into if there is something else going on.

I spoke too soon. There is an offset with the viking image as well but not as significant as we are seeing with voyager. 
![image](https://github.com/DOI-USGS/ISIS3/assets/74275278/4a134dda-f5ab-4186-a6dd-523c2a20629d)
