### ISSUE TITLE
Spiceinit NAIF error for MEX HRSC/SRC - data area issue

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5211]
**ISIS version(s) affected**:7.1.0, 7.2.0, 8.0.0-RC etc.

**Description**  
Spiceinit throws errors on SRC images when using the default ISISDATA area, but works as expected when changed to the local cpkgs/isis3_old/isis_data/ area.

```
hrsc2isis from=H2151_0005_SR2.IMG to=H2151_0005_SR2.cub

spiceinit from=H2151_0005_SR2.cub
terminate called after throwing an instance of 'Isis::IException'
  what():  **ERROR** An unknown NAIF error has been encountered. The short explanation provided by NAIF is [SPICE(DAFNOSUCHHANDLE)]. The Naif error is [There is no file open with handle = 0] in NaifStatus.cpp at 100.
Abort (core dumped)
```
Discovered this while reprocessing data.  A network already exists for this dataset and the reprocessing had numerous failures for images that are already in my network.  Not all images failed, so it may be a certain time frame affected. Troubleshooting got me here.

**How to reproduce**  
See img/cub file under my work area Isis3Tests/Spiceinit/NewDataArea/MEX/ExceptionError/

Here's the Kernels Group for the successful run using the old data area:
```
  Group = Kernels
    NaifIkCode                = -41220
    LeapSecond                = $base/kernels/lsk/naif0012.tls
    TargetAttitudeShape       = $base/kernels/pck/pck00009.tpc
    TargetPosition            = ($base/kernels/spk/de430.bsp,
                                 $base/kernels/spk/mar097.bsp)
    InstrumentPointing        = ($mex/kernels/ck/ATNM_MEASURED_050101_060101_-
                                 V03.BC, $mex/kernels/fk/MEX_V16.TF)
    Instrument                = $mex/kernels/ik/MEX_HRSC_V09.TI
    SpacecraftClock           = $mex/kernels/sclk/MEX_220810_STEP.TSC
    InstrumentPosition        = $mex/kernels/spk/ORMM__050901000000_00165.BSP
    InstrumentAddendum        = $mex/kernels/iak/hrscsrcAddendum002.ti
    ShapeModel                = Null
    InstrumentPositionQuality = Reconstructed
    InstrumentPointingQuality = Reconstructed
    CameraVersion             = 2
    Source                    = isis
  End_Group
```
Note that the old data area was frozen around September 2022 and processing logs for the above image show I ingested/spiced it originally in December of 2022, picking up a different SpacecraftClock kernel $mex/kernels/sclk/MEX_221214_STEP.TSC. That's probably ok and just wanted to make a note of that.

HRSC reprocessing has similar failures for a subset of the data.

**Comment by dpmayerUSGS** [comment]
For what it's worth, I confirmed that all of the kernels listed in the example that used the old data area also exist in the new data area. I only tested existence of the files using `ls`.

**Comment by lwellerastro** [comment]
Thanks for mentioning that @dpmayerUSGS since I failed to do so.  I also checked the directories to see if any of the files were empty since that had been a problem for other missions, but I didn't see any 0's for file size.  

The one thing I did notice is the current mex/kernels area contains a pck dircectory, but the isis3_old area does not. Either way, the images that did run successfully picked up the proper pck file from the /base/kernels/pck directory and doesn't appear to be part of the problem. In fact, now that I look again, there are a lot of extra directories under the mex/kernels area when compared to what we had locally last September.

```
ls $ISISDATA/mex/kernels/
aareadme.txt  ck  dsk  ek  fk  iak  ik  lsk  mk  orbnum  pck  sclk  spk

 ls isis3_old/isis_data/mex/kernels/
ck  fk  iak  ik  sclk  spk
```

**Comment by acpaquette** [comment]
I was able to check against the kernels in the S3 bucket from AWS and the cubes provided by @lwellerastro spiceinit'd correctly. It seems like the copied data inside of astro is out of date with the data in AWS.

**Comment by lwellerastro** [comment]
Ah, I should have tried that sooner.  But, I changed my data area to point to isis3_efs/isis_data/ and am still waiting for my test image to spiceinit - it's been >7 minutes and I still haven't got my prompt back. (it appears the process is dead and just consuming memory - nearly 5G for some reason; weird)
Update - it took 15 minutes to spice one image using the cloud storage, but it worked. There's good reason why I rather use a sync'd copy - it should only take seconds to run. Slightly different sclk kernel, but I don't think that's an issue. 

I thought we have fairly regular sync's to the local area, weekly maybe?  Is this an IT issue and do I need to poke them @acpaquette ?

**Comment by acpaquette** [comment]
@lwellerastro I think bumping this to IT is the right call. feel free to CC me on that email in case they need the devs to do something.

**Comment by acpaquette** [comment]
@lwellerastro I think it's a poke IT issue? I 100% agree with using the local area for speed and it takes a bit on my machine as well.

**Comment by acpaquette** [comment]
Doing some further digging on this. The CK file provided via the AWS S3 bucket is 469 MB but the same CK is only 307 MB internally to astro. Looks like the file was munged/not completely downloaded.

**Comment by lwellerastro** [comment]
IT confirmed this was a local data area sync/mount issue and got it back up to date.
I reran my jobs and all ran as expected.
