### ISSUE TITLE
cmake fails to detect OSX version (typo in cmake file?)

### ISSUE THREAD

**Issue by afrigeri** [DOI-USGS/ISIS3#5219]
**ISIS version(s) affected**: dev branch

**Description**  

cmake fails to detect OSX version, resulting in:

```
CMake Error at cmake/Utilities.cmake:174 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:58 (get_os_version)
```

**How to reproduce**  

```
cmake -DJP2KFLAG=OFF -GNinja  ../isis/
```
in the build directory 

**Possible Solution**  

add double quotes to the `${version}` variable

```
diff --git a/isis/cmake/Utilities.cmake b/isis/cmake/Utilities.cmake
index 513668a63..0687d5f0d 100644
--- a/isis/cmake/Utilities.cmake
+++ b/isis/cmake/Utilities.cmake
@@ -171,7 +171,7 @@ function(get_os_version text)
     # Format the string
     string(REGEX MATCH "[0-9]+.[0-9]+.[0-9]+" version "${result}")
     string(REGEX MATCH "^[0-9]+.[0-9]+" version "${version}")
-    string(REPLACE "." "_" version ${version})
+    string(REPLACE "." "_" version "${version}")
 
     set(name   "MacOSX")
     set(prefix "Darwin_x86_64_")
```

**Additional context**

**Comment by acpaquette** [comment]
@afrigeri Could you post the MacOS version you are running? Does the possible solution you posted fix the problem?

**Comment by afrigeri** [comment]
hi @acpaquette,  OS version:
```
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
```
over `x86_64`architecture.  The solution above fixes the problem: without the double quotes, the `${version}` variable was empty.

**Comment by afrigeri** [comment]
@acpaquette, adding a proper  `isis/make/config.darwin-MacOSX13_4` will make the original `${version}` (no quotes) working, so cmake completes without the error reported above.
