### ISSUE TITLE
Multiple links on FAQ broken

### ISSUE THREAD

**Issue by briley-lewis** [DOI-USGS/ISIS3#5220]
I've been trying to solve some issues getting spiceinit to work, but a majority of links (e.g. to base and mission specific instructions) are broken, and seem necessary for troubleshooting, on this page under "Why is spiceinit failing": https://github.com/DOI-USGS/ISIS3/wiki/FAQ#why-is-spiceinit-failing

**Comment by dpmayerUSGS** [comment]
Thanks for catching the broken links. The current links for information on installing the base data and mission-specific data are in the [README](https://github.com/DOI-USGS/ISIS3#the-isis-data-area) at the top of the repo.

- [Partial Download of Base Data](https://github.com/DOI-USGS/ISIS3#partial-download-of-isis-base-data)
- [Partial Download of Mission-Specific Data](https://github.com/DOI-USGS/ISIS3#partial-download-of-mission-specific-data)

**Comment by jlaura** [comment]
These should all be updated now. This was a product of the organization migration. I changed 100+ links over 40 pages, so if anyone finds any missed links, please re-open and let me know!
