### ISSUE TITLE
'ISIS Cube Format' Wiki page is broken

### ISSUE THREAD

**Issue by ishan-mishra** [DOI-USGS/ISIS3#5221]
The following link does not work: https://usgs-astrogeology.github.io/ISIS3/ISIS_Cube_Format.html

**Comment by jlaura** [comment]
Thanks for opening! I just fixed it. This was a bi-product of our organization migration. Apologies for any inconvenience. The new link is https://doi-usgs.github.io/ISIS3/ISIS_Cube_Format.html.
