### ISSUE TITLE
Unable to open Intro2isis.cub file with qview

### ISSUE THREAD

**Issue by ishan-mishra** [DOI-USGS/ISIS3#5222]
**ISIS version(s) affected**:  7.0.0

**Description**  
I am following the wiki and trying to perform the exercises with the [Intro2isis.cub file](https://github.com/DOI-USGS/ISIS3/wiki/Introduction_to_ISIS#bonus-). However, I am unable to open this file in qview. Qview quits with the following message:

`dyld[96618]: missing symbol called
zsh: abort      qview`

**Additional context**  

Qview works fine with other .cub files that I downloaded. I installed ISIS via Anaconda.

**Comment by AustinSanders** [comment]
Hi @ishan-mishra, sorry for missing this issue for so long.

Can you run ```conda list``` and paste the output here?
