### ISSUE TITLE
When using spiceinit : Error: dyld[]: missing symbol called

### ISSUE THREAD

**Issue by mashenghan** [DOI-USGS/ISIS3#5225]
**ISIS version(s) affected**: x.y.z
7.1.0
**Description**  

when I want to use spiceinit 
(isis) ➜  vims spiceinit from=v1490951542_2_ir.cub
dyld[1207]: missing symbol called
[1]    1207 abort      spiceinit from=v1490951542_2_ir.cub

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by AustinSanders** [comment]
Hi @mashenghan, I'm not able to reproduce this error on my machine, and I'll need some more information before I'm able to offer any help.  What operating system are you using, and how did you install ISIS?

**Comment by mashenghan** [comment]
Thanks for your reply.
I use the MacOS to install the ISIS, and this MacOS is intel core.
I follow the instructions on this page(https://github.com/DOI-USGS/ISIS3) by using MacOS to install ISIS.
And I can use the vims2isis to convert the qub file to the cube file, and use qview to browser the cube file.
But when I want to use the spiceinit to calibrate the cube file. I met this problem.
And I also install the ISIS on WSL(Linux under the Windows10). But I also met a similar problem. Both of these problem indicates that my dynamic library went wrong.
So I don't know how to solve this problem. Maybe my steps of installation went wrong? But I don't know exactly where is wrong?

**Comment by AustinSanders** [comment]
@mashenghan I was just able to reproduce this error on a local build!  Unfortunately it's not clear to me what's causing this problem, but I'm looking into it now. I'll try to keep you updated as I make progress

**Comment by AustinSanders** [comment]
I was able to rectify my symbol error by updating ale, but I suspect that that's a different issue.  Can run `conda list` in your terminal and paste the output here?

**Comment by mashenghan** [comment]
@AustinSanders 
This is my output (conda list)
# packages in environment at /Users/mashenghan/mambaforge/envs/isis:
#
# Name                    Version                   Build  Channel
ale                       0.9.1            py39h8ee36c8_0    conda-forge
aom                       3.4.0                hb486fe8_1    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
armadillo                 11.4.4               hffeb596_0    conda-forge
arpack                    3.7.0                hefb7bc6_2    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
blas                      2.117                  openblas    conda-forge
blas-devel                3.9.0           17_osx64_openblas    conda-forge
boost                     1.72.0           py39hb64e6f8_1    conda-forge
boost-cpp                 1.72.0               h179ae3a_7    conda-forge
brotli                    1.0.9                hb7f2c08_8    conda-forge
brotli-bin                1.0.9                hb7f2c08_8    conda-forge
bullet                    2.86.1                        0    usgs-astrogeology
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.19.1               h0dc2134_0    conda-forge
ca-certificates           2023.5.7             h8857fd0_0    conda-forge
cairo                     1.16.0            h904041c_1014    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7                    pypi_0    pypi
csm                       3.0.3.3                       0    conda-forge
cspice                    67                   hb7f2c08_4    conda-forge
curl                      7.86.0               h57eb407_1    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cyrus-sasl                2.1.27               ha724b88_5    conda-forge
debugpy                   1.6.7            py39h7a8716b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
eigen                     3.4.0                h940c156_0    conda-forge
embree                    2.16.0               h6834224_0    usgs-astrogeology
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hf0c8a7f_1    conda-forge
ffmpeg                    4.4.2           gpl_h5a1d76f_107    conda-forge
flann                     1.9.1             h56de9e4_1011    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h5bb23bf_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.40.0                   pypi_0    pypi
freetype                  2.12.1               h3f81eb7_1    conda-forge
geos                      3.7.3                h4a8c4bd_0    conda-forge
geotiff                   1.7.1                he29fd1c_4    conda-forge
gettext                   0.21.1               h8a4c099_0    conda-forge
giflib                    5.2.1                hb7f2c08_3    conda-forge
glib                      2.76.3               h7d26f99_0    conda-forge
glib-tools                2.76.3               h7d26f99_0    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
gnutls                    3.7.8                h207c4f0_0    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
gsl                       2.7                  h93259b0_0    conda-forge
gst-plugins-base          1.21.3               h37e1711_1    conda-forge
gstreamer                 1.21.3               h1d18e73_1    conda-forge
harfbuzz                  5.3.0                h08f8713_0    conda-forge
hdf5                      1.12.2          nompi_hc782337_100    conda-forge
icu                       70.1                 h96cf925_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.7.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0                   pypi_0    pypi
importlib_metadata        6.7.0                hd8ed1ab_0    conda-forge
inja                      3.3.0                he49afe7_0    conda-forge
ipykernel                 6.23.3             pyh5fb750a_0    conda-forge
ipython                   8.14.0             pyhd1c38e8_0    conda-forge
isis                      7.1.0                         0    usgs-astrogeology
jama                      125                           0    usgs-astrogeology
jasper                    2.0.33               h7c6fec8_1    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hb7f2c08_3    conda-forge
jupyter_client            8.3.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.1            py39h6e9494a_0    conda-forge
kakadu                    1                             0    usgs-astrogeology
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.3               hb49756b_0    conda-forge
lame                      3.100             hb7f2c08_1003    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libblas                   3.9.0           17_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                hb7f2c08_8    conda-forge
libbrotlidec              1.0.9                hb7f2c08_8    conda-forge
libbrotlienc              1.0.9                hb7f2c08_8    conda-forge
libcblas                  3.9.0           17_osx64_openblas    conda-forge
libclang                  15.0.3          default_h20dc2f0_0    conda-forge
libclang13                15.0.3          default_hc4b5f92_0    conda-forge
libcurl                   7.86.0               h57eb407_1    conda-forge
libcxx                    16.0.5               hd57cbcb_0    conda-forge
libdeflate                1.14                 hb7f2c08_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libevent                  2.1.10               h815e4d9_4    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           11_3_0_h97931a8_31    conda-forge
libgfortran5              12.2.0              he409387_31    conda-forge
libglib                   2.76.3               hc62aa5d_0    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
libidn2                   2.3.4                hb7f2c08_0    conda-forge
liblapack                 3.9.0           17_osx64_openblas    conda-forge
liblapacke                3.9.0           17_osx64_openblas    conda-forge
libllvm15                 15.0.3               hb04caa8_0    conda-forge
libnghttp2                1.51.0               h0dd9d14_0    conda-forge
libntlm                   1.4               h0d85af4_1002    conda-forge
libogg                    1.3.4                h35c211d_1    conda-forge
libopenblas               0.3.23          openmp_h429af6e_0    conda-forge
libopencv                 4.6.0            py39h743a0d3_4    conda-forge
libopus                   1.3.1                hc929b4f_1    conda-forge
libpng                    1.6.39               ha978bb4_0    conda-forge
libpq                     14.5                 h4aa9af9_3    conda-forge
libprotobuf               3.21.12              hbc0c0cd_0    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsqlite                 3.42.0               h58db7d2_0    conda-forge
libssh2                   1.10.0               h7535e13_3    conda-forge
libtasn1                  4.19.0               hb7f2c08_0    conda-forge
libtiff                   4.4.0                h6268bbc_5    conda-forge
libunistring              0.9.10               h0d85af4_0    conda-forge
libvorbis                 1.3.7                h046ec9c_0    conda-forge
libvpx                    1.11.0               he49afe7_3    conda-forge
libwebp                   1.2.4                hfa4350a_0    conda-forge
libwebp-base              1.2.4                h775f41a_0    conda-forge
libxcb                    1.15                 hb7f2c08_0    conda-forge
libxml2                   2.9.14               hea49891_4    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               16.0.5               hff08bdf_0    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
macports-legacy-support   1.0.10               h0dc2134_0    conda-forge
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mesalib                   23.1.2               hb59017c_0    conda-forge
metis                     5.1.0             h2e338ed_1006    conda-forge
mpfr                      4.2.0                h4f9bd69_0    conda-forge
mysql                     8.0.32               h57ddcff_0    conda-forge
mysql-client              8.0.32               hbbbc359_0    conda-forge
mysql-common              8.0.32               h7ebae80_0    conda-forge
mysql-connector-c         6.1.11            h0f02589_1007    conda-forge
mysql-devel               8.0.32               h7ebae80_0    conda-forge
mysql-libs                8.0.32               hc37e033_0    conda-forge
mysql-server              8.0.32               ha134c4c_0    conda-forge
nanoflann                 1.4.2                h694c41f_0    conda-forge
ncurses                   6.4                  hf0c8a7f_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
nettle                    3.8.1                h96f3785_1    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nlohmann_json             3.11.2               hbbd2c75_0    conda-forge
nn                        1.86.0            h1de35cc_2003    conda-forge
nspr                      4.35                 hea0b92c_0    conda-forge
nss                       3.89                 h78b00b3_0    conda-forge
numpy                     1.24.3           py39h892e69a_0    conda-forge
openblas                  0.3.23          openmp_hbefa662_0    conda-forge
opencv                    4.6.0            py39h6e9494a_4    conda-forge
openh264                  2.3.0                hb486fe8_0    conda-forge
openssl                   1.1.1u               h8a1eda9_0    conda-forge
p11-kit                   0.24.1               h65f8906_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.2            py39h11b3245_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcl                       1.11.1               h7984e4d_1    conda-forge
pcre2                     10.40                h1c4e4bc_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.5.0                    pypi_0    pypi
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
platformdirs              3.5.3              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
proj                      9.1.0                hcbd9701_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
protobuf                  4.21.12          py39h7a8716b_0    conda-forge
psutil                    5.9.5            py39ha30fb19_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pvl                       1.3.2              pyhd8ed1ab_0    conda-forge
py-opencv                 4.6.0            py39h71a6800_4    conda-forge
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
pysis                     0.6.0                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.15          h531fd05_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39ha30fb19_5    conda-forge
pyzmq                     25.1.0           py39hdac9eea_0    conda-forge
qhull                     2020.2               h940c156_2    conda-forge
qt                        5.15.6               h93fa01e_0    conda-forge
qt-main                   5.15.6               he0d2461_1    conda-forge
qt-webengine              5.15.4               h1d4dd28_3    conda-forge
qwt                       6.2.0                h86624fb_5    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
scipy                     1.10.1           py39hded996c_3    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spiceypy                  5.1.2              pyhd8ed1ab_0    conda-forge
sqlite                    3.42.0               h2b0dec6_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
suitesparse               5.10.1               h7aff33d_1    conda-forge
superlu                   5.2.2                h1f0f902_0    conda-forge
svt-av1                   1.2.1                hbbd2c75_0    conda-forge
tbb                       2021.9.0             hb8565cd_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tnt                       126                           0    usgs-astrogeology
tornado                   6.3.2            py39hdc70f33_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.6.3                hd8ed1ab_0    conda-forge
typing_extensions         4.6.3              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.3              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h775f41a_2    conda-forge
x265                      3.5                  hbb4e6a2_3    conda-forge
xerces-c                  3.2.3                hf5b2a72_5    conda-forge
xorg-damageproto          1.2.1             h0d85af4_1002    conda-forge
xorg-fixesproto           5.0               h0d85af4_1002    conda-forge
xorg-glproto              1.4.17            h0d85af4_1002    conda-forge
xorg-inputproto           2.3.2             h35c211d_1002    conda-forge
xorg-kbproto              1.0.7             h35c211d_1002    conda-forge
xorg-libice               1.1.1                h0dc2134_0    conda-forge
xorg-libsm                1.2.4                h0dc2134_0    conda-forge
xorg-libx11               1.8.5                hbd0b022_0    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdamage           1.1.5                h0d85af4_1    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xorg-libxext              1.3.4                hb7f2c08_2    conda-forge
xorg-libxfixes            5.0.3             h0d85af4_1004    conda-forge
xorg-libxi                1.7.10               h0d85af4_0    conda-forge
xorg-libxrandr            1.5.2                h0d85af4_1    conda-forge
xorg-libxrender           0.9.10            h0d85af4_1003    conda-forge
xorg-randrproto           1.5.0             h0d85af4_1001    conda-forge
xorg-renderproto          0.11.1            h0d85af4_1002    conda-forge
xorg-util-macros          1.19.3               h35c211d_0    conda-forge
xorg-xextproto            7.3.0             hb7f2c08_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h0d85af4_1002    conda-forge
xorg-xproto               7.0.31            h35c211d_1007    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h8a1eda9_5    conda-forge
zstd                      1.5.2                hbc0c0cd_6    conda-forge

**Comment by AustinSanders** [comment]
@mashenghan Interesting -- I'm wondering if we're running into the same issue after all.  I'm using ISIS 8.0 and had to upgrade ALE from 0.8.x to 0.9.1.  Since you're using ISIS 7.1.0, you may have to _downgrade_ ale to 0.8.x

Try `conda install ale=0.8.8`.  You might have to run `conda remove ale` before reinstalling

**Comment by lwellerastro** [comment]
Hi - be careful using `conda remove ale`.

When I was tinkering with installing a newer version of ale into an existing install of isis using that particular command it completely removed isis. It happened to say so in the "the following packages will be REMOVED verbiage, but it was a long list and I missed that isis was in it.  It took a bit to figure out what was going on.

This is what worked instead on linux OS:
```
conda remove --force ale
conda install -c conda-forge ale=0.8.8 --force
```
I'm going to add _I think_ this worked because it's been a while, lots of balls in the air, and I'm a novice.  
At the very least, make sure ISIS isn't in the list of packages to remove if you go with `conda remove ale`!

**Comment by mashenghan** [comment]
Thanks so much！
It worked well. I can use the spiceinit to process the example data(v1490951542_2_ir.cub).
But when I want to process Jupiter data(v1356904960_4_ir.cub). I met some new problem: 
<details><summary>Details</summary>
```
spiceinit from=v1356904960_4_ir.cub

Group = Kernels
  NaifFrameCode             = -82371
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
                               $cassini/kernels/pck/cpck30Sep2004_jupiter.tpc)
  TargetPosition            = ($base/kernels/spk/de430.bsp,
                               $base/kernels/spk/jup310.bsp)
  InstrumentPointing        = ($cassini/kernels/ck/00364_01008ra.bc,
                               $cassini/kernels/fk/cas_v40_usgs.tf)
  Instrument                = Null
  SpacecraftClock           = $cassini/kernels/sclk/cas00172.tsc
  InstrumentPosition        = $cassini/kernels/spk/010420R_SCPSE_EP1_JP83.bsp
  InstrumentAddendum        = $cassini/kernels/iak/vimsAddendum04.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
  Error                     = "Isis cannot process images with a SamplingMode
                               = "UNDER" (or NYQUIST)"
End_Group

Group = Kernels
  NaifFrameCode             = -82371
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
                               $cassini/kernels/pck/cpck30Sep2004_jupiter.tpc)
  TargetPosition            = ($base/kernels/spk/de430.bsp,
                               $base/kernels/spk/jup310.bsp)
  InstrumentPointing        = ($cassini/kernels/ck/00275_01001rc.bc,
                               $cassini/kernels/fk/cas_v40_usgs.tf)
  Instrument                = Null
  SpacecraftClock           = $cassini/kernels/sclk/cas00172.tsc
  InstrumentPosition        = $cassini/kernels/spk/010420R_SCPSE_EP1_JP83.bsp
  InstrumentAddendum        = $cassini/kernels/iak/vimsAddendum04.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
  Error                     = "Isis cannot process images with a SamplingMode
                               = "UNDER" (or NYQUIST)"
End_Group

Group = Kernels
  NaifFrameCode             = -82371
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
                               $cassini/kernels/pck/cpck30Sep2004_jupiter.tpc)
  TargetPosition            = ($base/kernels/spk/de430.bsp,
                               $base/kernels/spk/jup310.bsp)
  InstrumentPointing        = ($cassini/kernels/ck/001229_010103ra.bc,
                               $cassini/kernels/fk/cas_v40_usgs.tf)
  Instrument                = Null
  SpacecraftClock           = $cassini/kernels/sclk/cas00172.tsc
  InstrumentPosition        = $cassini/kernels/spk/010420R_SCPSE_EP1_JP83.bsp
  InstrumentAddendum        = $cassini/kernels/iak/vimsAddendum04.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
  Error                     = "Isis cannot process images with a SamplingMode
                               = "UNDER" (or NYQUIST)"
End_Group
**ERROR** Unable to initialize camera model.
```

**Comment by AustinSanders** [comment]
@mashenghan Glad to hear that helped!

One of the limitations of the current VIMS driver is that it is not able to process images with a sampling mode of "UNDER."  This is not a bug or something that I can help work around at the moment.  If you're interested in processing that data, then you might consider putting in an issue marked with "enhancement request."
