### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#5227]
**Description**
On https://isis.astrogeology.usgs.gov/7.0.0/UserExplore/index.html in the section "Specialized Method References" there's a supposed link to "Map Definition Reference", but the actual link is just linking to its own page. (https://isis.astrogeology.usgs.gov/7.0.0/UserExplore/index.html)

**Comment by AustinSanders** [comment]
I'm not sure where this used to link or should link.  Does [this](https://github.com/DOI-USGS/ISIS3/wiki/Learning_About_Map_Projections#Defining-a-Map-in-ISIS3-) seem like the right location?

**Comment by antonhibl** [comment]
@AustinSanders if that is the correct link, my PR should fix this issue
