### ISSUE TITLE
qview measure area of a polygon

### ISSUE THREAD

**Issue by aero924a** [DOI-USGS/ISIS3#5232]
I'm attempting to measure the areal size of a cloud feature in a JunoCam image using qview.  I've created a nice map-projected image and can easily measure distances but I can't figure out what combination of keyboard and mouse buttons I need to use to draw a polygon and obtain the area contained by said polygon.  I'm using a macOS machine.

Thanks,

-Shawn

**Comment by lwellerastro** [comment]
Hi @aero924a, I am not a mac user, but these are the steps I would take via a linux OS:
- select measure tool (ruler)
- select Polygon in the drop down menu (default is line) that should be at the top of the qview window in its own pane
- I suggest opening the Table that will display various values at time (button at end of tool pane) (you might have to show/hide some columns)
- draw a polygon by dropping vertices using the left mouse button and double click to finish the polygon

I don't know how one left clicks via a mac, but maybe it's just click, click, click to build up the polygon and click-click to finish it.
I hope this helps some.

**Comment by Kelvinrr** [comment]
@aero924a did Lynn's instructions help? It should work just as well on mac.

**Comment by aero924a** [comment]
Yes, this issue is resolved.
