### ISSUE TITLE
campt reports PixelValue from the first band always

### ISSUE THREAD

**Issue by afrigeri** [DOI-USGS/ISIS3#5235]
**ISIS version(s) affected**: 7.0.0

**Description**  

campt reports PixelValue from the first band even when asking for band != 1

**How to reproduce**  

download 10 by 10 pixel Chandrayaan-1 M3 sub-cube [M3_10x10.cub.zip](https://github.com/DOI-USGS/ISIS3/files/11900429/M3_10x10.cub.zip)

```
unzip M3_10x10.cub.zip
campt from=M3_10x10.cub+1 sample=1 line=1  | grep PixelValue
PixelValue                 = -18.618536
```

```
campt from=M3_10x10.cub+25 sample=1 line=1  | grep PixelValue
PixelValue                 = -18.618536
```
should be: 16.72398

**Possible Solution**  
**explode**-ing the cube then reassemble it, as a workaround.

**Additional context**

**Comment by AustinSanders** [comment]
I suspect that this is related to #5234.  We're experiencing a bug in which cube attributes are not being identified, which would mean that the "+25" that is appended to the filename is being skipped, which could very well lead to the behavior you've described.

I'll do some testing and update this issue as I make progress.
