### ISSUE TITLE
Where is qview

### ISSUE THREAD

**Issue by wjadler123** [DOI-USGS/ISIS3#5239]
I am a UNIX SA who has been asked to install ISIS so a few people can use qview.  I went through the installation instructions with MINICONDA and there is no qview program in my ISIS installation.    I have qview on my machines from
ISIS -3.10 which was installed in 2020, but those qviews have missing libraries.

I would guess I am missing some obvious step.
Does anyone have any idea where qview should be or what I may have missed?

thanks

**Comment by Kelvinrr** [comment]
Following the conda instructions, they would be installed into $CONDA_PREFIX/bin/ 

Where $CONDA_PREFIX is the root of the conda environment. 

If they do not show up when you try to run it, it might be because the env is not activated, or otherwise, $CONDA_PREFIX/bin/ is not in $PATH if you choose not to activate the env directly.

**Comment by wjadler123** [comment]
KelvinThank you for responding
I will look, There is no qview anywhere in the tree. I use the find
command and there is no qview. Is qviewstill part of conda?
I have two installs running which have been running for 8 hours
I run into channel errors when install from home instead of frommy
work
Thanks
Bill

	-----------------------------------------From: "Kelvin Rodriguez" 
To: "DOI-USGS/ISIS3"
Cc: "Bill Adler aka Dad", "Author"
Sent: Thursday July 13 2023 6:56:08PM
Subject: Re: [DOI-USGS/ISIS3] Where is qview (Issue #5239)

	Following the conda instructions, they would be installed into
$CONDA_PREFIX/bin/ 

	Where $CONDA_PREFIX is the root of the conda environment. 

	If they do not show up when you try to run it, it might be because
the env is not activated, or otherwise, $CONDA_PREFIX/bin/ is not in
$PATH if you choose not to activate the env directly. 

	—
 Reply to this email directly,  view it on GitHub [1], or  unsubscribe
[2].
 You are receiving this because you authored the thread.Message ID:  

Links:
------
[1]
https://github.com/DOI-USGS/ISIS3/issues/5239#issuecomment-1635149048
[2]

**Comment by Kelvinrr** [comment]
when you say the tree, the tree from where? The build directory? source directory? or the install directory? 

qview is an application that is distributed via conda. yes. 

What are the commands you are using to install ISIS?

**Comment by wjadler123** [comment]
I install ISIS using 

conda install -c usgs-astrogeology isis

I had some complete installations earlier this week intomy directory
~/miniconda3 . But using the UNIXfind command there is no qview
anywhere
I started two installations this afternoon between 2 and 4 (PST) and
they are still running
Thanks
BIll

	-----------------------------------------From: "Kelvin Rodriguez" 
To: "DOI-USGS/ISIS3"
Cc: "Bill Adler aka Dad", "Author"
Sent: Thursday July 13 2023 9:57:41PM
Subject: Re: [DOI-USGS/ISIS3] Where is qview (Issue #5239)

	when you say the tree, the tree from where? The build directory?
source directory? or the install directory? 

	qview is an application that is distributed via conda. yes. 

	What are the commands you are using to install ISIS? 

	—
 Reply to this email directly,  view it on GitHub [1], or  unsubscribe
[2].
 You are receiving this because you authored the thread.Message ID:  

Links:
------
[1]
https://github.com/DOI-USGS/ISIS3/issues/5239#issuecomment-1635271907
[2]

**Comment by Kelvinrr** [comment]
So if ~/miniconda3 is your conda install location, check `~/miniconda/envs/<env name>/bin/qview`, is it not there?

**Comment by wjadler123** [comment]
The path is
/home/wadler/miniconda3/envs/isis/conda-metaand in there is a history
file.
Those 2 installs from yesterday are still runningThey are both at my
work (JPL) 

The script I should be running is 

	Miniconda3-py39_23.5.2-0-Linux-x86_64.sh

	 correct?

	I am going to try that again on my Ubuntu machine

	Bill

	-----------------------------------------From: "Kelvin Rodriguez" 
To: "DOI-USGS/ISIS3"
Cc: "Bill Adler aka Dad", "Author"
Sent: Friday July 14 2023 10:50:42AM
Subject: Re: [DOI-USGS/ISIS3] Where is qview (Issue #5239)

	So if ~/miniconda3 is your conda install location, check
~/miniconda/envs//bin/qview, is it not there? 

	—
 Reply to this email directly,  view it on GitHub [1], or  unsubscribe
[2].
 You are receiving this because you authored the thread.Message ID:  

Links:
------
[1]
https://github.com/DOI-USGS/ISIS3/issues/5239#issuecomment-1636189625
[2]

**Comment by wjadler123** [comment]
FYI - I am a UNIX SA - since 1993. I have 200 UNIX boxes and550 unique
users to support. I have a little help, but not much 
ON my home ubuntu machine I just di
sh MIni...
it created a new miniconda3
I then typed bashconda create -n isis conda config --env --add
channels conda-forgeconda config --env --add channels
usgs-astrogeology

	conda config --show channels

	channels:

	 - usgs-astrogeology

	 - conda-forge

	 - https://conda.anaconda.org

	 - http://astroconda.gemini.edu/public

	 - http://ssb.stsci.edu/astrocondaconda config --remove channels

	 - defaults

	*** COULD ThE ExTRA CHANNELS Becausing a problem?

	now I do the conda install -c usgs-astrogeology isis 

	I got 404 errors, I was able to 

	conda config --remove channels

	for the first two httpd, butnot the http;//ssd.stsci.edu 

	conda install isis -gets a 404 error on that channel

	bill

	-----------------------------------------From: "Kelvin Rodriguez" 
To: "DOI-USGS/ISIS3"
Cc: "Bill Adler aka Dad", "Author"
Sent: Friday July 14 2023 10:50:42AM
Subject: Re: [DOI-USGS/ISIS3] Where is qview (Issue #5239)

	So if ~/miniconda3 is your conda install location, check
~/miniconda/envs//bin/qview, is it not there? 

	—
 Reply to this email directly,  view it on GitHub [1], or  unsubscribe
[2].
 You are receiving this because you authored the thread.Message ID:  

Links:
------
[1]
https://github.com/DOI-USGS/ISIS3/issues/5239#issuecomment-1636189625
[2]

**Comment by wjadler123** [comment]
Kelvin .. more info

	I removed .bashrc and .condarc and .conda and startedover

	and I got through the 404 problems. I now have ISIS isntalls running,

	2 at work at one at home (I have a very nice Ubuntu machine

	at home)

	If we can get this going so I can install ISIS it would be awesome.
ISIS has always been a thorn in my side because it is so difficult

	to install.

	thanks

Bill

	I 

	—

	 Reply to this email directly,  view it on GitHub [1], or 
unsubscribe [2].
 You are receiving this because you authored the thread.Message ID:  

Links:
------
[1]
https://github.com/DOI-USGS/ISIS3/issues/5239#issuecomment-1636189625
[2]

**Comment by Kelvinrr** [comment]
Sorry I am trying to understand, so you have successfully installed ISIS? But still cant find qview? 

The extra channels might have been causing the 404's, yeah 

Semi-related, but if you want faster install you can also try mamba-forge. You can download mamba-forge from their github: https://github.com/conda-forge/miniforge#mambaforge

**Comment by wjadler123** [comment]
Thank YOu Kelvin
Someone managed to get it installed with qview. There were
someundocumented steps
I am trying to come up with a common install in a public area now.It
is not a high priority , the two people using it are summer
internsfrom Caltech and they will be gone by mid August.
conda and isis are very fragile pieces of software. If you are
runningpython 3.6.1.2.3.4 instead of 3.6.1.2.3.4a the whole thing
crashes like a house of cards .
I will remain in touch.. I really want the next round of ISIS usersto
be plug-and-play 
BIll

	-----------------------------------------From: "Kelvin Rodriguez" 
To: "DOI-USGS/ISIS3"
Cc: "Bill Adler aka Dad", "Author"
Sent: Wednesday July 19 2023 8:20:02AM
Subject: Re: [DOI-USGS/ISIS3] Where is qview (Issue #5239)

	Sorry I am trying to understand, so you have successfully installed
ISIS? But still cant find qview? 

	The extra channels might have been causing the 404's, yeah 

	Semi-related, but if you want faster install you can also try
mamba-forge. You can download mamba-forge from their github: 
[1]https://github.com/conda-forge/miniforge#mambaforge [2] 

	—
 Reply to this email directly,  view it on GitHub [3], or  unsubscribe
[4].
 You are receiving this because you authored the thread.Message ID:  

Links:
------
[1] https://github.com/conda-forge/miniforge#mambaforge
[2] https://github.com/conda-forge/miniforge#mambaforge
[3]
https://github.com/DOI-USGS/ISIS3/issues/5239#issuecomment-1642290622
[4]

**Comment by Kelvinrr** [comment]
Anaconda can be super fickle for sure, I would still consider using mamba forge in the future, if only to speed up install times as conda's default resolver takes forever. So it's faster to resolve environment issues. I'll close this for now, feel free to repoen if you continue to have issues
