### ISSUE TITLE
`gaussstretch` Segmentation Fault

### ISSUE THREAD

**Issue by dpmayerUSGS** [DOI-USGS/ISIS3#5240]
**ISIS version(s) affected**: All public versions 4.1.0-7.2.0

**Description**  

Running `gausstretch` in ISIS versions 4.1.0-7.2.0 on Linux exits with a segmentation fault. Strangely, the program still _appears_ to create a correct output cube. 

**How to reproduce**  

```
user@host:~/$: gaussstretch from=input.cub to=output.cub gsigma=3.0
Segmentation fault (core dumped)
user@host:~/$: echo $?
139
```

**Comment by acpaquette** [comment]
@dpmayerUSGS This was fixed in #5262
