### ISSUE TITLE
downloadIsisData not working

### ISSUE THREAD

**Issue by alexwuttig** [DOI-USGS/ISIS3#5242]
I am new to using linux and I am having some trouble downloading Isis data. When I attempt to use $ downloadIsisData all $ISISDATA it returns "downloadIsisData: command not found...". I am running CentOS Linux. Any help would be greatly appreciated.

**Comment by AustinSanders** [comment]
Hi @AlexBankss , which version of ISIS are you running?

**Comment by AlexBankss** [comment]
Hi @AustinSanders, how do I check what version I am running?
