### ISSUE TITLE
convert isis3 cube to isis2 format (non-tiled) 

### ISSUE THREAD

**Issue by swoodwa** [DOI-USGS/ISIS3#5253]
Is there a way (in ISIS3) to convert a map-projected (tiled) ISIS3 image cube into an ISIS2 cube format (non-tiled)? 

Alternatively, if I wanted to create a map-projected ISIS2 image cube file (using Matlab to write out data to a file - data that I obtained by importing an ISIS3 image cube into Matlab), how should I format the label header?  The core object label info in the ISIS3 cube (see below) says "Format = Tile", then gives the values for TileSamples and TileLines, but I'm not sure what the value of the "Format" field should be for an ISIS2 cube , where the core data is just a single 2-D array of values (with dimensions of Samples by Lines). 

(Example ISIS3 cube label portion):
Object = IsisCube
  Object = Core
    StartByte   = 65537
    Format      = Tile
    TileSamples = 433
    TileLines   = 128

    Group = Dimensions
      Samples = 1732
      Lines   = 2558
      Bands   = 1
    End_Group

    Group = Pixels
      Type       = Real
      ByteOrder  = Lsb
      Base       = 0.0
      Multiplier = 1.0
    End_Group
  End_Object

**Comment by JohnVV** [comment]
you might have to use GDAL to convert the isis3 cub to an isis2 file 

using gdal_translate to make a geo-tif then convert to a isis2 cub
