### ISSUE TITLE
voycal error

### ISSUE THREAD

**Issue by cneish** [DOI-USGS/ISIS3#5254]
**ISIS version(s) affected**: 6.0.0 (on an Apple M1 Pro)

**Description**  

I am trying to calibrate a Voyager 2 NAC image of Neptune (c1124426.imq). I ran "voy2isis" with no problems and produced a .cub file (which looks correct when I open it in qview). When I try to calibrate it:

>voycal from=c1124426.imq.cub to=c1124426.imq.cal.cub

I get the following error message: 

**ERROR** Unable to initialize camera model in Camera Factory.
**ERROR** PVL Keyword [TargetPosition] does not exist in [Group = Kernels].

I have the voyager2 data installed in $ISISDATA. The "Group = Kernels" for this image states:

Group = Kernels
    NaifFrameCode = -32101
End_Group

Clearly, "TargetPosition" is missing, but I'm not sure how to add that information in. Any ideas? The full header is pasted below.

Thanks, Catherine

--------------------
Object = IsisCube
  Object = Core
    StartByte   = 65537
    Format      = Tile
    TileSamples = 800
    TileLines   = 800

    Group = Dimensions
      Samples = 800
      Lines   = 800
      Bands   = 1
    End_Group

    Group = Pixels
      Type       = UnsignedByte
      ByteOrder  = Lsb
      Base       = 0.0
      Multiplier = 1.0
    End_Group
  End_Object

  Group = Instrument
    SpacecraftClockCount = 1124426
    SpacecraftName       = VOYAGER_2
    TargetName           = Neptune
    StartTime            = 1989-08-20T07:15:09
    InstrumentId         = NARROW_ANGLE_CAMERA
    ScanModeId           = 5:1
    ShutterModeId        = BOTSIM
    GainModeId           = LOW
    EditModeId           = 1:1
    ExposureDuration     = 23.0400 <seconds>
    CameraState1         = 5
    CameraState2         = 0
  End_Group

  Group = Archive
    MissionPhaseName = NEPTUNE_ENCOUNTER
    ProductId        = 0242N2-005
  End_Group

  Group = BandBin
    FilterName   = ORANGE
    FilterNumber = 3
    Center       = 0.615000 <micrometers>
    Width        = 0.050000 <micrometers>
  End_Group

  Group = Kernels
    NaifFrameCode = -32101
  End_Group
End_Object

Object = Label
  Bytes = 65536
End_Object

Object = History
  Name      = IsisCube
  StartByte = 705537
  Bytes     = 479
End_Object

Object = OriginalLabel
  Name      = IsisCube
  StartByte = 706016
  Bytes     = 2019
End_Object
End

**Comment by acpaquette** [comment]
@cneish Some instruments require that you run `spiceinit` on them before calibration as they need to know about things like `TargetPosition`. Try running `spiceinit from=c1124426.imq.cub`, that should populate your kernels group with the expected keyword.

**Comment by cneish** [comment]
Yes, that worked! Thank you.

**Comment by acpaquette** [comment]
Sweet!
