### ISSUE TITLE
The phocube program of ISIS is running too slowly

### ISSUE THREAD

**Issue by zhaofei2048** [DOI-USGS/ISIS3#5271]
The _phocube_ program of ISIS is running **too slowly**. I noticed in the system monitor that **its CPU usage is very low, and the memory usage is only around 30-50 MB**. However, my actual system has plenty of CPU and memory resources (I'm using virtualbox+ubuntu). **Is it possible to modify the configuration to make _phocube_ utilize the system resources more efficiently and run faster?** (I have already tried changing the GlobalThreads parameter in the preference file without success). I'm grateful for any insights you can offer.

**Comment by AustinSanders** [comment]
@zhaofei2048 I haven't personally developed much of phocube, but I suspect that many of its operations are IO bound, which is likely exacerbated by the fact that you're running on a virtual machine.  I suspect that there is nothing nothing on the configuration side that can be done to increase performance.

I'll bring this up with the team and see if other perspectives shed any light on the situation, but I suspect that this is simply the nature of the program and the environment in which it is run.
