### ISSUE TITLE
cam2map output only cover a portion of the overlay of input and shapemodel

### ISSUE THREAD

**Issue by 99YyLi** [DOI-USGS/ISIS3#5282]
**ISIS version(s) affected**: 4.4.0

**Description**  
I use a NAC DEM as the user shapemodel in spiceinit. The shapemodel is within the input Mini-RF data but do not cover the whole Mini-RF data. I just want to get the overlaying Mini-RF data projected, but the cam2map output only cover about half portion of the DEM, not fill with it. Is this because the data is close to 180 degree longitude?

**How to reproduce**  
pds2isis from=NAC_DTM_CHANGE4_E458S1775.img  to=NAC_DTM_CHANGE4_E458S1775.cub

fx f1=NAC_DTM_CHANGE4_E458S1775.cub equation="f1+1737400" to=NAC_DTM_CHANGE4_E458S1775.radius.cub

demprep from=NAC_DTM_CHANGE4_E458S1775.radius.cub to=NAC_DTM_CHANGE4_E458S1775.demprep.cub

mrf2isis f=lsz_03149_1cd_xku_39s178_v1.lbl t=lsz_03149_1cd_xku_39s178_v1.cub

spiceinit from=lsz_03149_1cd_xku_39s178_v1.cub web=yes  spksmithed=true shape=user 

model=NAC_DTM_CHANGE4_E458S1775.demprep.cub spksmithed=true

maptemplate map=lsz_03149_1cd_xku_39s178_v1.map projection=equirectangular clat=-45.5 clon=180

cam2map from=lsz_03149_1cd_xku_39s178_v1.cub map=lsz_03149_1cd_xku_39s178_v1.map \ to=lsz_03149_1cd_xku_39s178_v1_map.cub pixres=mpp resolution=7.5

**Possible Solution**  

**Additional context**  
The gray image is the processed Mini-RF data, and the pseudocolor image is the DEM data.
![image](https://github.com/DOI-USGS/ISIS3/assets/143617462/8d6223ce-ad0e-446e-9da1-94b11c4ba9b8)

**Comment by acpaquette** [comment]
@99YyLi Could you provide either the file or a link to `NAC_DTM_CHANGE4_E458S1775.img`? I was able to find the mini-rf image, but if you have a custom DTM it would be useful to have to reproduce the error

**Comment by 99YyLi** [comment]
Thanks for your reply! @acpaquette
The DTM can be downloaded here:
https://pds.lroc.asu.edu/data/LRO-L-LROC-5-RDR-V1.0/LROLRC_2001/DATA/SDP/NAC_DTM/CHANGE4/NAC_DTM_CHANGE4_E458S1775.IMG
And the Mini-RF data can be downloaded here:
https://pds-geosciences.wustl.edu/lro/lro-l-mrflro-4-cdr-v1/lromrf_0002/data/sar/03100_03199/level1/lsz_03149_1cd_xku_39s178_v1.img
https://pds-geosciences.wustl.edu/lro/lro-l-mrflro-4-cdr-v1/lromrf_0002/data/sar/03100_03199/level1/lsz_03149_1cd_xku_39s178_v1.lbl

**Comment by acpaquette** [comment]
@99YyLi Sorry for the late reply, I did some digging and it looks like the miniRF driver in our other package, ALE, has a bug that needs to be fixed. The translation elements in the driver `focal2pixel_lines` and `focal2pixel_samples` both have all zeros, causing issues with projection in ISIS
