### ISSUE TITLE
Legacy isisdist server not responding

### ISSUE THREAD

**Issue by ericepalmer** [DOI-USGS/ISIS3#5283]
**ISIS version(s) affected**: x.y.z

**Description**  
I'm trying to download the base data for hayabusa and hayabusa2 missions.  I try to rsync to the isisdist servers, but they do not connect.

**How to reproduce**  
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/hayabusa2 data/

**Possible Solution**  

**Additional context**  
Error that I get

rsync: failed to connect to isisdist.astrogeology.usgs.gov: Operation timed out (60)
rsync error: error in socket IO (code 10) at /AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/rsync/rsync/clientserver.c(106) [receiver=2.6.9]

**Comment by jlaura** [comment]
Please see: https://github.com/DOI-USGS/ISIS3/issues/5179
or https://github.com/DOI-USGS/ISIS3#full-isis-data-download

The rsync server has been shutdown since November, 2022.
