### ISSUE TITLE
Missing LRO Radiometric calibration files (lronaccal)

### ISSUE THREAD

**Issue by yanping1129** [DOI-USGS/ISIS3#5284]
My question is the same as casinsar commented on 6/26,
I use lronaccal perform radiometric calibration, The error I received was:
error no existing files found with a numerical version matching [NACL_LinearizationCoefficients.????.txt in [Isisdata/lro/calibration
My version of ISIS is 8.0.0_RC2, 
I checked Isisdata/lro/calibration and there is no NACL_LinearizationCoefficients.????.txt files
I download the full packages about LROC NAC again. The NACL_LinearizationCoefficients.????.txt is still missing.
How to fix it.

**Comment by KrisBecker** [comment]
Hi @yanping1129, this appears to be the same problem as described in #5272 with [csv](https://github.com/DOI-USGS/ISIS3/issues/5272#issuecomment-1686731425) files in that the [donwloadIsisData](https://github.com/DOI-USGS/ISIS3/blob/dev/isis/scripts/downloadIsisData) script is also excluding files ending in `.txt`.

To fix this issue, you need to edit your copy of dowloadIsisData and remove the [line](https://github.com/DOI-USGS/ISIS3/blob/1ba60d684f6f53a397f03c074265665853949cfe/isis/scripts/downloadIsisData#L38) that contains `- *.txt` and rerun the script.

**Comment by yanping1129** [comment]
@KrisBecker  Thanks, The solution you've given me is very useful, successsfullly  solved my problem!

**Comment by chkim-usgs** [comment]
Looks like problem was solved, will close issue.
