### ISSUE TITLE
conda isis install not finding repository?

### ISSUE THREAD

**Issue by rrherrick** [DOI-USGS/ISIS3#5285]
I have no experience with using Anaconda but have been walking my way through the directions on https://github.com/DOI-USGS/ISIS3#installation.  I have a Linux box with Centos 8 as the operating system.  I have Python 3.11.4 installed, if that matters.  When I run "conda config --show channels" I see the three channels in the correct order.  I successfully executed setting the channel_priority to flexible.  However, when I run "conda install -c usgs-astrogeology isis" I get a bunch of messages that I think means that the repository for ISIS is not being found, and then it says "Solving environment:  " and goes into never-never land with a rotating line and nothing happening.  Below is the printout from my terminal.  I am doing this as root, and I have put anaconda3 in /opt.  I'm not sure what is going wrong, but I feel like it's probably something simple that I am missing.  Any help would be appreciated.  

[root@waco ~]# conda install -c usgs-astrogeology isis
Collecting package metadata (current_repodata.json): \ DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
- DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/linux-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/current_repodata.json HTTP/1.1" 200 None
\ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/linux-64/current_repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/noarch/current_repodata.json HTTP/1.1" 200 None
- DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /usgs-astrogeology/linux-64/current_repodata.json HTTP/1.1" 404 None
\ DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /usgs-astrogeology/noarch/current_repodata.json HTTP/1.1" 404 None
- DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /usgs-astrogeology/linux-64/repodata.json HTTP/1.1" 304 0
| DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /usgs-astrogeology/noarch/repodata.json HTTP/1.1" 304 0
done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
/ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/linux-64/repodata.json HTTP/1.1" 304 0
- DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/linux-64/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/noarch/repodata.json HTTP/1.1" 200 None
\ DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /usgs-astrogeology/linux-64/repodata.json HTTP/1.1" 304 0
/ DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /usgs-astrogeology/noarch/repodata.json HTTP/1.1" 304 0
done
Solving environment:  (rotating /, nothing happening)

**Comment by acpaquette** [comment]
@rrherrick I think this is correct behavior but the solve may take a good chunk of time. I would suggest trying to install using mamba. To install mamba run:

`conda install -c conda-forge mamba`

Then rerun your command but using mamba instead of conda:

`mamba install -c usgs-astrogeology isis`

**Comment by rrherrick** [comment]
Hi, 
Okay I tried that and the installation of mamba did not work.  I then went back and tried the conda install again.  In both cases it looks now like it is unhappy with glibc.  Here is the end of the output from conda install -c usgs-astrogeology isis:  
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                           

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - isis -> python==3.6

Your python: python=3.11

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - feature:|@/linux-64::__glibc==2.28=0
  - isis -> mesalib -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.28

The tail end of the output from trying to install mamba is as follows:

The following specifications were found to be incompatible with your system:
  - feature:/linux-64::__glibc==2.28=0
  - feature:/linux-64::__linux==4.18.0=0
  - feature:/linux-64::__unix==0=0
  - feature:|@/linux-64::__glibc==2.28=0
  - feature:|@/linux-64::__linux==4.18.0=0
  - feature:|@/linux-64::__unix==0=0
  - _anaconda_depends -> gst-plugins-base -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - _anaconda_depends -> ipython -> __linux
  - _anaconda_depends -> ipython -> __osx
  - _anaconda_depends -> ipython -> __win
  - _anaconda_depends -> sympy -> __unix
  - abseil-cpp -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - aiohttp -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - argon2-cffi -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - argon2-cffi-bindings -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
...
  - xxhash -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xz -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - y-py -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - yaml -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - yaml-cpp -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - yarl -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - zeromq -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - zfp -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - zlib -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - zlib-ng -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - zope.interface -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - zstandard -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - zstd -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.28

**Comment by Kelvinrr** [comment]
You might be running into conflicts due to installing in an existing environment? Isis's dependencies are very complicated and you can run into problems pretty fast doing that. I would suggest putting it in it's own env. 

```
# instead of conda install, create a new env 
conda create -n isis -c usgs-astrogeology isis 
```


Mamba sometimes fails for the same reason, suggest to install it via mamba-forge: https://github.com/conda-forge/miniforge#mambaforge-pypy3

**Comment by rrherrick** [comment]
Okay, I started over from scratch and used the Miniconda installer.  This eliminated all the Debug and incompatibility messages and whatnot, but then when I tried either conda install -c usgs-astrogeology isis or conda create -n isis -c usgs-astrogeology isis things just hang at "Solving environment".  Here's the full printout from trying each of these:

conda install -c usgs-astrogeology isis
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 

conda create -n isis -c usgs-astrogeology isis 
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /

**Comment by ldx119** [comment]
> Okay, I started over from scratch and used the Miniconda installer. This eliminated all the Debug and incompatibility messages and whatnot, but then when I tried either conda install -c usgs-astrogeology isis or conda create -n isis -c usgs-astrogeology isis things just hang at "Solving environment". Here's the full printout from trying each of these:
> 
> conda install -c usgs-astrogeology isis Collecting package metadata (current_repodata.json): done Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve. Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source. Collecting package metadata (repodata.json): done Solving environment: /
> 
> conda create -n isis -c usgs-astrogeology isis Collecting package metadata (current_repodata.json): done Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source. Collecting package metadata (repodata.json): done Solving environment: /

have you solved the problem? I encountered the same thing.

**Comment by ldx119** [comment]
> You might be running into conflicts due to installing in an existing environment? Isis's dependencies are very complicated and you can run into problems pretty fast doing that. I would suggest putting it in it's own env.
> 
> ```
> # instead of conda install, create a new env 
> conda create -n isis -c usgs-astrogeology isis 
> ```
> 
> Mamba sometimes fails for the same reason, suggest to install it via mamba-forge: https://github.com/conda-forge/miniforge#mambaforge-pypy3
![image](https://github.com/DOI-USGS/ISIS3/assets/100507049/3610ebc5-552a-42ac-bad5-f9063975a297)

Do you know how I solved the problem? Thanks.

**Comment by AustinSanders** [comment]
Unfortunately, environments are somewhat delicate, and there's no one-size-fits-all answer for these types of issues.  Another process that you might try is as follows:

```
conda clean --all
conda create -n isis
conda activate isis
conda install mamba
mamba env update -f environment.yml
```

This will ensure that your environment starts off clean and empty then installs mamba to perform the rest of the setup process.

**Comment by ldx119** [comment]
> Unfortunately, environments are somewhat delicate, and there's no one-size-fits-all answer for these types of issues. Another process that you might try is as follows:
> 
> ```
> conda clean --all
> conda create -n isis
> conda activate isis
> conda install mamba
> mamba env update -f environment.yml
> ```
> 
> This will ensure that your environment starts off clean and empty then installs mamba to perform the rest of the setup process.

Thanks for your suggestions. The first four commands seem very well, but when executing "mamba env update -f environment.yml", it gets stuck here:
![image](https://github.com/DOI-USGS/ISIS3/assets/100507049/a5381f3f-8e30-4dcb-a03a-5561ad317444)
is there a way to solve it?

**Comment by AustinSanders** [comment]
@ldx119 That output looks how I'd expect -- is the process hanging?  I've seen instances where the solver takes several hours to complete.  The tough part is knowing how long is reasonable to wait -- how long have you let it run?

**Comment by ldx119** [comment]
> @ldx119 That output looks how I'd expect -- is the process hanging? I've seen instances where the solver takes several hours to complete. The tough part is knowing how long is reasonable to wait -- how long have you let it run?

About two days have passed and the situation is still the same.

**Comment by ldx119** [comment]
> @ldx119 That output looks how I'd expect -- is the process hanging? I've seen instances where the solver takes several hours to complete. The tough part is knowing how long is reasonable to wait -- how long have you let it run?

I'm still trying "conda install -c usgs-astrogeology isis"
![image](https://github.com/DOI-USGS/ISIS3/assets/100507049/0f33756e-00a3-4bd1-b762-16da0e09372b)
so, I'm very confused about the installation instructions, what I've done was completely follow the steps on the website

**Comment by lwellerastro** [comment]
Hi @ldx119, I have found explicitly asking for a version of isis has worked best for me.  In theory you shouldn't have to, but it's worth a try if you feel like starting over yet again.

I have anaconda installed (and kept up to date) and very few environments (including an isis env) that are all kept separate from each other and I recommend doing the same if possible.  My steps for the latest isis install (LTS 8.0.1) are as follows (note that I'm naming my install to myisis8.0.1 (I have reasons to be explicit):

While sitting in my top level conda install directory:
```
conda deactivate 
conda create -n myisis8.0.1
conda activate myisis8.0.1
conda config --env --add channels conda-forge
conda config --env --add channels usgs-astrogeology
conda install -c "usgs-astrogeology/label/LTS" isis=8.0.1
```
I haven't watched it closely, but the install typically takes 1-2 hours I think.  I will try solving a couple times, but I just ignore and it eventually installs.  I have a very good connection at work and that might help.

I have also had some problems setting up the isis environment variables in the past using the online instructions and my notes say to do the following right after the instructions above:
```
cd envs/myisis8.0.1/scripts/
python isisVarInit.py -d isis3/isis_data
```
After this I open a new shell and check that my environments are as expected (I don't have to download the data area as instructed because it already exists for me locally, I just have to point to it; I am also deliberately removing leading path information for privacy,; except I missed something and now it's been quoted elsewhere - sorry):
```
conda activate myisis8.0.1
printenv |egrep ISIS
ISISROOT=/anaconda3/envs/myisis8.0.1
ISISTESTDATA= anaconda3/envs/myisis8.0.1
ISISDATA=/isis3/isis_data
```
Please let us know if any of this works for, we might consider updating instructions based on your results.  Thanks and good luck!

**Comment by ldx119** [comment]
> Hi @ldx119, I have found explicitly asking for a version of isis has worked best for me. In theory you shouldn't have to, but it's worth a try if you feel like starting over yet again.
> 
> I have anaconda installed (and kept up to date) and very few environments (including an isis env) that are all kept separate from each other and I recommend doing the same if possible. My steps for the latest isis install (LTS 8.0.1) are as follows (note that I'm naming my install to myisis8.0.1 (I have reasons to be explicit):
> 
> While sitting in my top level conda install directory:
> 
> ```
> conda deactivate 
> conda create -n myisis8.0.1
> conda activate myisis8.0.1
> conda config --env --add channels conda-forge
> conda config --env --add channels usgs-astrogeology
> conda install -c "usgs-astrogeology/label/LTS" isis=8.0.1
> ```
> 
> I haven't watched it closely, but the install typically takes 1-2 hours I think. I will try solving a couple times, but I just ignore and it eventually installs. I have a very good connection at work and that might help.
> 
> I have also had some problems setting up the isis environment variables in the past using the online instructions and my notes say to do the following right after the instructions above:
> 
> ```
> cd envs/myisis8.0.1/scripts/
> python isisVarInit.py -d /usgs/cpkgs/isis3/isis_data
> ```
> 
> After this I open a new shell and check that my environments are as expected (I don't have to download the data area as instructed because it already exists for me locally, I just have to point to it; I am also deliberately removing leading path information for privacy):
> 
> ```
> conda activate myisis8.0.1
> printenv |egrep ISIS
> ISISROOT=/anaconda3/envs/myisis8.0.1
> ISISTESTDATA= anaconda3/envs/myisis8.0.1
> ISISDATA=/isis3/isis_data
> ```
> 
> Please let us know if any of this works for, we might consider updating instructions based on your results. Thanks and good luck!

The insatllation problem has been solved according your suggestions,Thanks a lot.

**Comment by lwellerastro** [comment]
Awesome! Thank you so much for letting us know @ldx119.

@AustinSanders, we should consider adding some of this to the installation instructions. I think we had some other post this past summer that experienced something similar and were able to get isis installed by explicitly asking for a version instead of just asking for "isis".

**Comment by AustinSanders** [comment]
@lwellerastro I'll make a new issue to get the instructions updated on the repo.

**Comment by ldx119** [comment]
> > Hi @ldx119, I have found explicitly asking for a version of isis has worked best for me. In theory you shouldn't have to, but it's worth a try if you feel like starting over yet again.
> > I have anaconda installed (and kept up to date) and very few environments (including an isis env) that are all kept separate from each other and I recommend doing the same if possible. My steps for the latest isis install (LTS 8.0.1) are as follows (note that I'm naming my install to myisis8.0.1 (I have reasons to be explicit):
> > While sitting in my top level conda install directory:
> > ```
> > conda deactivate 
> > conda create -n myisis8.0.1
> > conda activate myisis8.0.1
> > conda config --env --add channels conda-forge
> > conda config --env --add channels usgs-astrogeology
> > conda install -c "usgs-astrogeology/label/LTS" isis=8.0.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I haven't watched it closely, but the install typically takes 1-2 hours I think. I will try solving a couple times, but I just ignore and it eventually installs. I have a very good connection at work and that might help.
> > I have also had some problems setting up the isis environment variables in the past using the online instructions and my notes say to do the following right after the instructions above:
> > ```
> > cd envs/myisis8.0.1/scripts/
> > python isisVarInit.py -d /usgs/cpkgs/isis3/isis_data
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After this I open a new shell and check that my environments are as expected (I don't have to download the data area as instructed because it already exists for me locally, I just have to point to it; I am also deliberately removing leading path information for privacy):
> > ```
> > conda activate myisis8.0.1
> > printenv |egrep ISIS
> > ISISROOT=/anaconda3/envs/myisis8.0.1
> > ISISTESTDATA= anaconda3/envs/myisis8.0.1
> > ISISDATA=/isis3/isis_data
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please let us know if any of this works for, we might consider updating instructions based on your results. Thanks and good luck!
> 
> The insatllation problem has been solved according your suggestions,Thanks a lot.

when I use "shadowtau" for the HRSC image , I completely follow the instruction from https://isis.astrogeology.usgs.gov/7.0.0/Application/presentation/Tabbed/shadowtau/shadowtau.html . However it reports"failed 
 to convert string[] to a double"
![image](https://github.com/DOI-USGS/ISIS3/assets/100507049/a232592e-2e99-4cfb-8a4d-86b8097c2395)
I want to know what cause this? and how to solve it? Thanks a lot

**Comment by AustinSanders** [comment]
Hi @ldx119,

Please create a new issue to report this behavior.  This thread should be reserved for discussing the original issue.

**Comment by michaelaye** [comment]
> Unfortunately, environments are somewhat delicate, and there's no one-size-fits-all answer for these types of issues. Another process that you might try is as follows:
> 
> ```
> conda clean --all
> conda create -n isis
> conda activate isis
> conda install mamba
> mamba env update -f environment.yml
> ```
> 
> This will ensure that your environment starts off clean and empty then installs mamba to perform the rest of the setup process.

Careful here! It is "illegal" to install mamba in anything else than the base environment! it will lead to unsolvable mysterious errors:
https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html#mamba-should-be-installed-to-the-base-environment

I am also seeing installation probs at the moment, not sure yet if it's from the new conda using libmamba under the hood. investigating...
