### ISSUE TITLE
Hi all, I have been installing ISIS3 software in Ubuntu. I am getting error "cannot connect to a distribution server". Can anyone please help me to resolve this.

### ISSUE THREAD

**Issue by Hplanet** [DOI-USGS/ISIS3#5290]
**ISIS version(s) affected**: x.y.z

**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by Kelvinrr** [comment]
@Hplanet Can you fill out the contents of the issue with additional context? What commands were you running? What were the outputs for those commands?

**Comment by Hplanet** [comment]
@Kelvinrr I am trying to install isis3 in ubuntu using the command to run installation script as below
./isisInstall.sh
the message i get after few minute is
"Cannot connect to a distribution server"

**Comment by Hplanet** [comment]
Hi Kelvin,

Thank you so much for the response.
I tried running installation script on Ubuntu in windows based system as
under:

./isisInstall.sh

error i got is:

Cannot connect to a distribution server

later i tried running rsync command as under:

 rsync -azv --delete --partial
isisdist.astrogeology.usgs.gov::x86-64_linux_UBUNTU/isis
.

error i got:

rsync: [Receiver] failed to connect to isisdist.astrogeology.usgs.gov
(184.164.152.106): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(137)
[Receiver=3.2.3]

Please help as early as possible.
Thank you so much.

Best Regards,
Henal V. Bhatt, Ph.D.,
Post Doctoral Associate
Department of Geosciences,
Stony Brook University,
Stony Brook, NY, 11794 2100

Email: ***@***.***

**Comment by Hplanet** [comment]
@Kelvinrr I could install isis3. a step were i get some error is here.

command:
/isis3$ python3 $CONDA_PREFIX/scripts/isisVarInit.py

error:
python3: can't open file '/miniconda3/envs/isis/scripts/isisVarInit.py': [Errno 2] No such file or directory

**Comment by Hplanet** [comment]
@Kelvinrr I installed isis3 successfully. Thank you.

**Comment by Hplanet** [comment]
while running downloadIsisData script, I got this error.

./downloadIsisData.txt
usage: usage: downloadIsisData mission dest [-h] [-v] [-n NUM_TRANSFERS] [--config CONFIG] [rclone flags]
downloadIsisData.txt: error: the following arguments are required: mission, dest

can anyone suggest the soluiton?

**Comment by AustinSanders** [comment]
@Hplanet The downloadIsisData script requires some input from the user -- there are no default values for the "mission" and "dest" arguments.  If you want to download the entire data area, you can use something like:
`downloadIsisData all $ISISDATA`, which requires $ISISDATA to be defined on your system.  This step (and other documentation that might help) can be found [here](https://github.com/DOI-USGS/ISIS3#full-isis-data-download).

Please be aware that the full data area is fairly large.  If you are working with a single mission (such as LRO), then you may benefit from specifying the particular mission with which you are working, e.g. `downloadIsisData lro $ISISDATA`

**Comment by Hplanet** [comment]
@AustinSanders yes i tried that way only. I require one data only i.e. LRO and i am going to download that one only. when i type downloadIsisData all $ISISDATA. it shows me error: command not found. Pls help with this. I checked out scripts also may there is some directory arrangement where this script should be in.

**Comment by AustinSanders** [comment]
The scripts may not be included in your path.  It may be easiest to just navigate to the scripts directory and use `./downloadIsisData lro $ISISDATA`
