### ISSUE TITLE
Mosaicking behavior acting odd on Ubuntu 22.04 with AMD Threadripper processor

### ISSUE THREAD

**Issue by aero924** [DOI-USGS/ISIS3#5301]
**ISIS version(s) affected**: 8.0.0

**Description**  
I'm using linux scripting to process JunoCam images.  These scripts work well on my Ubuntu 20.04 desktop, and on three MacOS laptops. They have worked fine for several years.  However, using the same scripts on an Ubuntu 22.04 with an AMD threadripper machine, the results are very odd.  Mosaicking leaves out some framelets on the new Ubuntu 22.04 machine but works flawlessly on the Ubuntu 20.04 and MacOS (ventura) machines. 

**How to reproduce**  
I can send the scripts I'm using and a description of how to run them, but first I want to know if there is a known issue with Ubuntu 22.04 and/or a Threadripper processor.  Also, I'm assuming an anaconda x86 installation package for linux should work fine.  I'm about to uninstall isis and try reinstalling although I dread doing so because it takes forever to solve environments.

**Comment by swalterfub** [comment]
You can speed up conda environment solving by using the libmamba solver:
[https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community)

**Comment by Kelvinrr** [comment]
@aero924 can you send those scripts on how to reproduce? We have a thread ripper machine, I'll try to automos some random JunoCam but would be nice to have similar data as you.

**Comment by Kelvinrr** [comment]
Can't seem to replicate using a thread ripper and same version of Ubuntu. @aero924 when you say framelets are missing, are they also missing from the output image list after mosaicking?

**Comment by Kelvinrr** [comment]
Closing this until I here more back
