### ISSUE TITLE
Mosrange Test Failures

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#5302]
**ISIS version(s) affected**: dev

**Description**  
Recently added tests from #3606 introduced three new mosrange tests, but didn't include the cubes need to run them. @kledmundson I am tagging you here as the tests came in your PR, but it looks like we failed to catch the missing cubes in a review. If you could provide the cubes or steps to recreate the cubes that would be ideal, thank you for any help/files you can provide.

**How to reproduce**  
Check current nightly builds

**Possible Solution**  
Add or remake the cubes, we will lilely only want to add the labels then build the cubes in a fixture. Likely we don't need the DNs just the image size to produce the same lat/lon bounding box

**Additional context**

**Comment by kledmundson** [comment]
Will do.
