### ISSUE TITLE
Qview find tool bug

### ISSUE THREAD

**Issue by lsantorii** [DOI-USGS/ISIS3#5304]
**ISIS version(s) affected**: ISIS3

**Description**  
I have created some DTM. I have noticed that some of the created DTM's the Find tool in Qview works for some and not others. The find tool allows you to link the geo-reference between a DTM and .cub image, an trace along the .cub image and the DTM. It does this by placing a red-dot on the DTM and .cub.

For some DTM, it does not allow me to place the red dot in the DTM but it does on the .cub image. However, since there are still like as I move along the .cub image image, the DTM in linked to it also shift around. When I shift through the .cub image the way the DTM shift appear correct, but it wont allow me to compare each pixel respectively.

**How to reproduce**  
DTM are created using AMES stereo pipeline.

**Possible Solution**  

**Additional context**  

![Screenshot from 2023-10-03 11-10-35](https://github.com/DOI-USGS/ISIS3/assets/84150620/f8ecee3c-c324-40da-b215-e2fd84f19aef)
![Screenshot from 2023-10-03 11-11-16](https://github.com/DOI-USGS/ISIS3/assets/84150620/ceb49334-6c1d-4e44-9116-5f80a756a794)
![Screenshot from 2023-10-03 11-11-48](https://github.com/DOI-USGS/ISIS3/assets/84150620/904597b5-3413-40c9-be40-db537470ea43)

**Comment by acpaquette** [comment]
@lsantorii I have run into this before, specifically here #5282. It seems like it may be the same or similar issue.

**Comment by chkim-usgs** [comment]
Hi @lsantorii, there have been some recent updates to ALE that may have fixed this issue as I was able to follow your steps above with a DTM outputted from the AMES stereo pipeline. If the issue still occurs, please send us your data files or links to data so we can reproduce the bug.
