### ISSUE TITLE
Depricate `PvlObject` classes `addLogGroup` function

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#5310]
Given the current ISIS core work, there is a coupling between `PvlObject` and the `Application` class. Where the `PvlObject` accesses the `Application` static function `Log` to place output into an applications terminal.

This is a poor coupling and should be up to the `Application` class to log data to the application terminal and add any relevant PVL data to a `Pvl` object.

Ideally, we would deprecate the `PvlObject` function `addLogGroup` for a new function on to `Application` called something like `appendAndLog`, with two inputs the `PvlGroup` to log and the output `Pvl` object. Where it would log to the application terminal and if a `Pvl` object were passed in, add the results group to the `Pvl` object.

Function signature
```
appendAndLog(PvlGroup &results, Pvl &log)
```

**Comment by antonhibl** [comment]
@acpaquette is this closeable? #5347 seems to add the depreciation notice, is there a set date we will be depreciating the function completely by?
