### ISSUE TITLE
trimfilter ignores high and low parameters

### ISSUE THREAD

**Issue by rvwagner** [DOI-USGS/ISIS3#5311]
**ISIS version(s) affected**: At least 8.0.1, but I think this bug goes back to the very beginning of ISIS3.

**Description**  
The HIGH and LOW parameters of trimfilter don't seem to have any effect 

**How to reproduce**  
```
makecube l=100 s=100 b=1 to=t.cub
fakecube f=t.cub t=gradient.cub
trimfilter from=gradient.cub to=trimfiltered.cub low=75 high=125 minopt=count minimum=9 lines=3 samples=3
```

Expected result: Everything but a diagonal line from lower-left to upper-right getting nulled out.
Actual result: `**USER ERROR** Your selected parameters did not trim any data from the cube in main.cpp at 48.`

Workaround to get expected result:
```
mask from=gradient.cub mask=gradient.cub to=mask.cub mini=75 maxi=125
trimfilter from=mask.cub to=maskfiltered.cub minopt=count minimum=9 lines=3 samples=3
```

**Possible Solution**  
Looking at the source code, it looks like the LOW and HIGH input parameters are never actually read in; it should be trivial to add them in using whatever the standard syntax is for optional arguments and get everything working, assuming the back-end code functions as expected.

**Comment by AustinSanders** [comment]
@rvwagner Thanks for the report and solution.  We're in the process of scheduling a support sprint, and this will likely be resolved during that time.
