### ISSUE TITLE
failed to convert string [] to a double

### ISSUE THREAD

**Issue by ldx119** [DOI-USGS/ISIS3#5315]
**ISIS version(s) affected**: x.y.z

**Description**  

I use the "shadowtau" for HRSC to estimate tau.I have exactly follow the instruction from https://isis.astrogeology.usgs.gov/7.0.0/Application/presentation/Tabbed/shadowtau/shadowtau.html . However  it reports this error -- failed to convert string to a double.
![image](https://github.com/DOI-USGS/ISIS3/assets/100507049/9d653b54-3045-469f-be8b-802565f38501)
I want to konw what cause this and hhow to  slove it ? Thanks a lot.
Here is my basic environment:
![image](https://github.com/DOI-USGS/ISIS3/assets/100507049/a75d5796-0799-4f82-8d2b-658aca38f589)

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by lwellerastro** [comment]
I can reproduce this error by creating an input text file that is identical to the example input text file found in the [documentation](https://isis.astrogeology.usgs.gov/7.0.0/Application/presentation/Tabbed/shadowtau/shadowtau.html). The input text as specified here is csv input, but a space is included after each comma.  @ldx119, edit your input text file and remove any spaces you find after commas and you should be able to execute the program. Note that if you use the documentation example data as input to the program, the last two columns will not match the documentation output.  I don't know why that is, but clearly the documentation needs some updating, output included.

Notes to Devs:
I found test input under our isis3 test data area (../isis/src/base/apps/shadowtau/tsts/hapkehen1/input/TAU_INPUT_A.LIS) which has no commas in it.  The documentation should be updated to reflect what is in the test input files.

As an aside to the dev team, my 8.0.1 output file does not exactly match the truth data under the above test area.  The last two columns are different, but I also don't know if that area is current.

**Comment by ldx119** [comment]
> I can reproduce this error by creating an input text file that is identical to the example input text file found in the [documentation](https://isis.astrogeology.usgs.gov/7.0.0/Application/presentation/Tabbed/shadowtau/shadowtau.html). The input text as specified here is csv input, but a space is included after each comma. @ldx119, edit your input text file and remove any spaces you find after commas and you should be able to execute the program. Note that if you use the documentation example data as input to the program, the last two columns will not match the documentation output. I don't know why that is, but clearly the documentation needs some updating, output included.
> 
> Notes to Devs: I found test input under our isis3 test data area (../isis/src/base/apps/shadowtau/tsts/hapkehen1/input/TAU_INPUT_A.LIS) which has no commas in it. The documentation should be updated to reflect what is in the test input files.
> 
> As an aside to the dev team, my 8.0.1 output file does not exactly match the truth data under the above test area. The last two columns are different, but I also don't know if that area is current.

Exactly ,I remove all space after comma,the programme can work.I input three columns,indeed it last two columns are disappear.
![image](https://github.com/DOI-USGS/ISIS3/assets/100507049/29153b48-92fc-487e-8344-00940b38e3f0)
As the doucmentation suggests the output are tau and albedo.Is there something wrong with my input?  because the output looks very strange

**Comment by acpaquette** [comment]
@ldx119 As input, shadowtau only takes the first 6 elements and discards anything after that. As for output I am unsure. That albedo does seem rather high though. It would be useful to know how you generated your input data
