### ISSUE TITLE
MEX hrsc2isis has the problem of processing Level 2 is radiometrically data

### ISSUE THREAD

**Issue by ldx119** [DOI-USGS/ISIS3#5320]
**ISIS version(s) affected**: x.y.z

**Description**  

I use hrsc2isis to process level 2 data from https://pds-geosciences.wustl.edu/missions/mars_express/hrsc.htm, it reports File [hd674_0000_s13.img] has keyword [PROCESSING_LEVEL_ID = 3] and can not be read by this program", and then I try to remove PROCESSING_LEVEL_ID = 3 of the image file, it tells "PVL Keyword [PROCESSING_LEVEL_ID] does not exist in [Object = Root] in file [h9302_0000_s13_reP3.img]"
**How to reproduce**  

**Possible Solution**  

How could I solve the problem? Thanks
**Additional context**

**Comment by lwellerastro** [comment]
@ldx119, the ingestion program hrsc2isis only works on "HRSC Stereo and the SRC instruments with processing level of "1" or "2" (not "3")" as referenced in the ISIS online [documentation](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/hrsc2isis/hrsc2isis.html). The program will not work on projected HRSC data.

**Comment by AustinSanders** [comment]
I'm closing this issue since this is the documented behavior of the program.

**Comment by lwellerastro** [comment]
Hi @ldx119 - to be clear, the file you are passing to hrsc2isis is map projected and that program will on work on unprojected images having PROCESSING_LEVEL_ID = 1 or 2.  

However, the program pds2isis can be run on the image and will generate an isis cube file that can be viewed in qview as well as other isis programs which work on a map projected image.

`pds2isis from=hd674_0000_s13.img to=hd674_0000_s13.cub`

**Comment by ldx119** [comment]
> Hi @ldx119 - to be clear, the file you are passing to hrsc2isis is map projected and that program will on work on unprojected images having PROCESSING_LEVEL_ID = 1 or 2.
> 
> However, the program pds2isis can be run on the image and will generate an isis cube file that can be viewed in qview as well as other isis programs which work on a map projected image.
> 
> `pds2isis from=hd674_0000_s13.img to=hd674_0000_s13.cub`

I indeed got confused. Thank you very much for your guidance.
