### ISSUE TITLE
No isd_generate

### ISSUE THREAD

**Issue by yumi-rinta** [DOI-USGS/ISIS3#5324]
**ISIS version(s) affected**: 7.1.0

**Description**  

There is no "isd_generation" function.

**How to reproduce**  

I have been working on Kaguya tutorial here: 
https://stereopipeline.readthedocs.io/en/latest/examples/kaguya.html#preparing-the-data

At "Create CSM", it calls a isis function "isd_generation" which does not exist.

**Comment by rbeyer** [comment]
Yes, I appreciate that the documentation there makes it look like the `isd_generate` program is a part of ISIS.  It is not.  It is a part of the ale library that is typically installed with modern conda-installs of ISIS, and the "bin/" directory where conda installs all of the programs from all of the packages it adds is also co-incidentally called "$ISISROOT/bin/" which explains why it is written that way.

The ale library did not always have this program, and while the ale library's CHANGELOG isn't precisely clear on when it became available, I'll note that I have an ale verison 0.8.6 on my computer that doesn't have `isd_generate` and the CHANGELOG for ale indicates that version 0.9.0 probably does have it.

When you are in your ISIS conda environment, I would suggest running `$> conda env list` and seeing what version of `ale` you have.  If it is less than 0.9.0, that is probably the culprit.  You may just want to update your ISIS install (see https://github.com/DOI-USGS/ISIS3#updating).

**Comment by yumi-rinta** [comment]
Thank you so much for this information. Just solved this issue thanks to your comments.
