### ISSUE TITLE
ISIS version

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#5363]
**ISIS version(s) affected**: latest repo source code

Latest ISIS claims to be version 7.2.0, per this: https://github.com/DOI-USGS/ISIS3/blob/dev/isis/CMakeLists.txt#L37

This later propagates to what ninja does and is recorded as the library version. The version should be instead be 8.0.1.

**Comment by acpaquette** [comment]
@oleg-alexandrov I would check the 8.0 tag/branch. We often forget to propagate the current version to dev

**Comment by oleg-alexandrov** [comment]
Yeah, tag 8.0.1 has 8.0.1. I had to build ISIS from source given the latest bump in dependencies. 

It is nice to keep the main with the latest version too, or maybe a bit ahead of the latest tag version.

**Comment by jlaura** [comment]
@acpaquette Are you saying that the dev version is correct? or that the dev version should not be updated to be 8.0.1?

**Comment by AustinSanders** [comment]
I believe that this was addressed as part of the ongoing release via #5362

**Comment by acpaquette** [comment]
@jlaura It should probably be set to the last feature release, so I think 8.1.0?

**Comment by jlaura** [comment]
> Yeah, tag 8.0.1 has 8.0.1. I had to build ISIS from source given the latest bump in dependencies.
> 
Didn't that revert? https://github.com/DOI-USGS/ISIS3/pull/5359

and then back at it?https://github.com/DOI-USGS/ISIS3/pull/5361

**Comment by oleg-alexandrov** [comment]
I don't envy Adam's job. :) Here doing analogous work and it sucks. Hope you can converge to something. I did not get to the Mac yet.
