### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#5369]
**Description**

The latest documentation version is 7.0.0, but the current LTS is 8.0.1 or 8.0.2. The docs are a full major version behind the current release. 

**Suggested Edit**

Please update the docs with the new version.

Thanks!

**Comment by lwellerastro** [comment]
Anything current would be appreciated, but I think when available, documents based on 8.10 will be critical for understanding how to access some of the numerous changes to findfeatures outlined in https://github.com/DOI-USGS/ISIS3/discussions/5375.

**Comment by jlaura** [comment]
This is more broken than I initially thought.

If one navigates to the jigsaw documentation with Public Release selected in the version drop down (in the left hand ToC), docs for version 7.0.0 are presented. @jessemapel wrote some terrific improvements to the docs that landed in 7.1.0+. 

If one modifies the URL, replacing 7.0.0 with 7.1.0, the new docs are visible. The only reason I found these was through trial and error.
