### ISSUE TITLE
Incorporate Landed Sensor (MSL) Support Into ISIS

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#5370]
**Description**  

The USGSCSM/ALE stack recently completed work to support landed sensors [#580](https://github.com/DOI-USGS/ale/pull/580). As you can see, this results in almost immediate support inside of ASP for the sensor. I do not know what the support inside of ISIS will look like. We have a demonstrated working sensor model and ISD generation capability. I am opening this issue as an exploratory, one to begin incorporating the sensor into ISIS. Off of the top of my head, the capabilities that we would want to ensure are working:

- [x] Map projection (courtesy of @thare-usgs here are a bunch that may or may not be workable using ISIS https://pds-imaging.jpl.nasa.gov/documentation/Mars2020_Camera_SIS.pdf#page=157)
- [x] Image mosaicking
- [x] Control network creation
- [x] Bundle adjustment

**Example**

**Comment by acpaquette** [comment]
@jlaura Given #5408 we would have access to orthographic and orthorectified projections (cam2map) as well as cylindrical perspective (skymap).

From here one should be able to run something like automos to get a very basic uncontrolled mosaic from the landed data.

I think a control network would also be feasible.

However if the effort of making a control network is to then bundle adjust, I don't think it's possible. MSL support comes from USGSCSM and the CSMCamera in ISIS. Once we have some bundle adjustment for the CSMCamera it should also work with the MSL data. As to when that will be available I am unsure

**Comment by acpaquette** [comment]
@jlaura All of the above can be accomplished in ISIS but likely needs some larger verification and tweaking. I can include screenshots if that would be helpful!

**Comment by jlaura** [comment]
@acpaquette thanks for the in-person demo earlier. Terrific to see landed sensor model being used to create a control network and then run a bundle adjustment with ISIS! We've got lots to write up on this (peer-review and user tutorials).

For any users watching this thread, we are working on this functionality. Feel free to reach out (jlaura@usgs.gov and acpaquette@usgs.gov) if you are interested in this "beta" capability.
