### ISSUE TITLE
Undocumented Control Network Fields

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#5388]
**Description**

The [control network format documentation](https://isis.astrogeology.usgs.gov/documents/ControlNetworks/index.html) shows a PVL rendered fixed control point. That control point includes fields which are undocumented on the page. For example, a priori and adjust covariance matrices. It is unclear which of those fields is required on input and which is populated / updated on output.

**Suggested Edit**

Please document what these fields should contain, their units, and when they are required. 

Thanks!

**Comment by Kelvinrr** [comment]
Should we consider porting these over to https://github.com/DOI-USGS/asc-public-docs along with these changes? I'm open to opinions on whether we should migrate and fix the docs as we go or let ISIS docs stay divergent.
