### ISSUE TITLE
Download monthly CTX flat files

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#5430]
**Description**  

ctx cal has a feature to use flatfiles that are updated regularly (apparently monthly?). There should be a programmatic way to download these files. The most obvious is to add them to the `downloadIsisData` configuration, but this would require a rclone supported source and I dont know where such a source exists, I only know of a git repo which would require custom code instead of a simple source addition. 

**Example**  

`downloadIsisData lro /isisdata` would also download the updated flatfiles.

**Comment by jlaura** [comment]
The new Walter and Aye flat fields are a single file. There is no need for any additional downloads at this time.
