### ISSUE TITLE
Error Encountered with spiceinit Command

### ISSUE THREAD

**Issue by squidward-qwq** [DOI-USGS/ISIS3#5450]
Hello ISIS Community,

I hope this message finds you well. I am encountering an issue while using the spiceinit command in ISIS, and I'm seeking assistance in resolving it.

When attempting to initialize SPICE data for an image file using the following command:

spiceinit from=/home/ubuntu22/mars_stereo/text3/1.cub web=true

I receive the following error message:

**ERROR** The server sent an unrecognized response.

It seems there might be a problem with connecting to the server while attempting to download the required SPICE kernels using the web=true option. I have already checked my internet connection and verified that the server is up and running.Additionally, I'd like to note that I'm using the latest version of ISIS.

Could you please provide guidance on how to troubleshoot and resolve this issue? Any assistance or suggestions would be greatly appreciated.

Thank you in advance for your help.

**Comment by AustinSanders** [comment]
Howdy @squidward-qwq ,

There's been a good number of issues coming in lately related to spiceinit using web=true, and a lot of the issues have been related to the web server issuing incorrect / incomplete responses or just outright failing. We're in the process of migrating to a new spice server, which should resolve most of these issues by default.  In the meantime, you can direct spiceinit to use the new server with
`url=https://astrogeology.usgs.gov/apis/ale/v0.9.1/spiceserver/` as an argument to spiceinit, so your call would look like
`spiceinit from=/home/ubuntu22/mars_stereo/text3/1.cub web=true url=https://astrogeology.usgs.gov/apis/ale/v0.9.1/spiceserver/`

**Comment by squidward-qwq** [comment]
Dear @AustinSanders ,

Just wanted to drop you a quick note to say thanks a bunch for your help! Your advice on dealing with the spiceinit issues using web=true has been spot on. Your tip about migrating to a new spice server was exactly what I needed to get things back on track.
Really appreciate you taking the time to share that workaround. It's awesome to see such active support in the ISIS community!

**Comment by AustinSanders** [comment]
@squidward-qwq  Right on! I'm happy to hear that it worked.  I'll close out this issue.
