### ISSUE TITLE
Unit tests take too long

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#5459]
**ISIS version(s) affected**: Latest

**Description**  

The unit test DefaultCube.FunctionalTestCamstatsDefaultParameters takes 20 minutes to run. That is a very unreasonable amount of time, and it simply looks that it stalls. 

It is suggested not to compute the stats for every line and sample but for only every 10th one, or at least every 5th one, which should make it much faster.

It is also not clear why it takes so long to run the stats, the image there is 1000 x 1000 pixels or so.

**Comment by oleg-alexandrov** [comment]
There are at least 4 such tests using camera stats. Any time the regression gets there it stalls. Very unhelpful when it comes to updating tests, one has to spend hours just go get a first pass, and go figure how many iterations are needed.

**Comment by oleg-alexandrov** [comment]
Would be nice if this is fixed. Would make it much faster to run the tests, saving hours. The suggested fix seems to be rather easy.

**Comment by Kelvinrr** [comment]
I'll get this added onto the support board

**Comment by amystamile-usgs** [comment]
Camstats has a built in option to increase the increments of lines and samples. This is linc and sinc. So the easiest fix would be to change the test to use linc=10 and sinc=10 but then this test would no longer be testing default parameters (linc and sinc defaults are 1). Another option could be to reduce the input cube's line/sample so CameraStatistics isn't iterating 1,273,685 times. @Kelvinrr do you have any thoughts on this?

**Comment by Kelvinrr** [comment]
@amystamile-usgs I would reduce the size if possible
