### ISSUE TITLE
Rewrite BundleSettings unit test in gtest

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#547]

**Comment by jessemapel** [comment]
There is some weird functionality when adding the Welsch or Chen maximum likelihood models as the first model. It throws an exception stating that if multiple models are used, then it much be Huber or HuberModified. Except, this prevents using just Welsch or just Chen.

I asked around and no one is sure if this is correct. I'm not sure if anyone is actually still using the Maximum Likelihood estimation. For now, I am testing the existing functionality.

**Comment by lwellerastro** [comment]
I use Huber, but only alone - no other models used at the same time (though I did do a bunch of tests when it was all first introduced combing methods - but that was years ago).

**Comment by jessemapel** [comment]
@lwellerastro The only time this is concerning is when someone wants to use Welsch alone or Chen alone.

I think this is small enough of a concern, that we can just move on for now.
