### ISSUE TITLE
CSM Translation File - Not PVL Compliant?

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#5484]
**ISIS version(s) affected**: 8.0.0+

**Description**  

The CSM serial number translation file is not parsable by other PVL libraries. As noted in [this issue](https://github.com/planetarypy/pvl/issues/108) on the planetarypy PVL library, this PVL is not compliant with a PVL specification.

Can this PVL be made compliant and maintain the same functionality? In order to make this work in the PVL library, "Group" inside the `Group = /End_Group` was quoted and the bare `Auto` keyword (??) was removed.

Here is the ISIS PVL file: https://github.com/DOI-USGS/ISIS3/blob/21308692275a243ff58aeefce996cb3c0d8c357b/isis/appdata/serialnumbers/CsmSerialNumber.trn#L4

**How to reproduce**  
This reproduces in an external library, so maybe this is behaving as intended. I hope not, because libraries like plio make use of these translation tables and need a mechanism to convert them into JSON. Right now, the PVL library is that means.

**Possible Solution**  

**Additional context**

**Comment by acpaquette** [comment]
Bumping this, after further discussion on the planeterypy issue the unquoted `Group` as a value is an issue in the planeterypy/pvl library but the bare `Auto` keyword is an ISIS issue and is non-compliant PVL.

A fairly easy fix is to make the `Auto` keyword have a boolean value, so all groups in translation files will have an `Auto` keyword with a value of 0|1. So it will look something like `Auto=0|1`

**Comment by jlaura** [comment]
@acpaquette Thanks for the discussion over there. Transitioning from `Auto` to `Auto=0|1` sounds like a solid plan.
