### ISSUE TITLE
Unable to add SPICE data to Galileo cube files

### ISSUE THREAD

**Issue by bensonyee88** [DOI-USGS/ISIS3#5495]
**ISIS version(s) affected**: x.y.z

**Description**  
Hello! We're facing issues with adding SPICE data to our Galileo cube files using the spiceinit function. I have pasted the error message below. Would really appreciate any help!

**How to reproduce**  
Last login: Sun May 5 22:53:24 on ttys000
(base) benson@dhcp-vl2041-18708 ~ % conda activate isis
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit
(isis) benson@dhcp-vl2041-18708 ~ % qimage
zsh: command not found: qimage
(isis) benson@dhcp-vl2041-18708 ~ % ls *.cub
7401r.cub 7452r.cub 8700r.cub 8726r.cub
(isis) benson@dhcp-vl2041-18708 ~ % qview 8700r.cub
^C
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8700r.cub attach=yes
ERROR No existing files found with a numerical version matching [kernels.????.db] in [/Applications/anaconda3/envs/isis/data/base/kernels/lsk].
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8700r.cub web=yes
ERROR The server sent an unrecognized response.
(isis) benson@dhcp-vl2041-18708 ~ % ls *.cub
7401r.cub 7452r.cub 8700r.cub 8726r.cub
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8726r.cub web=yes
ERROR The server sent an unrecognized response.
(isis) benson@dhcp-vl2041-18708 ~ % gllssi2isis from=8700r.lbl to=8700r_v2.cub
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8700r_v2.cub web=true
ERROR The server sent an unrecognized response.
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8700r_v2.cub attach=true
ERROR No existing files found with a numerical version matching [kernels.????.db] in [/Applications/anaconda3/envs/isis/data/base/kernels/lsk].
(isis) benson@dhcp-vl2041-18708 ~ %

**Comment by AustinSanders** [comment]
Hey @bensonyee88 , we'll have to track down the cause of the "unrecognized response error" to resolve the web spice issue.

In the meantime, have you downloaded the base area alongside the galileo data?  From your discussion post, it looks like you already ran `downloadIsisData galileo $ISISDATA`, but you'll also need to grab the base kernels with `downloadIsisData base $ISISDATA`.

**Comment by AustinSanders** [comment]
The "unrecognized response error" for web spice is being tracked as part of #5460.

If you've downloaded the base data area and are still experiencing this issue, then feel free to reopen this issue for discussion!
