### ISSUE TITLE
suitesparse version 7.7.0 possibly breaking ISIS build on Linux

### ISSUE THREAD

**Issue by kledmundson** [DOI-USGS/ISIS3#5496]
**ISIS version(s) affected**: x.y.z
dev

**Description**  

In attempting to build dev on Linux, encountered the following cmake error ...

-- CHOLMOD INCLUDE: CHOLMOD_INCLUDE_DIR-NOTFOUND

OS: Rocky Linux 9.3 (Blue Onyx)
Kernel:  Linux 5.14.0-362.24.1.el9_3.0.1.x86_64
Architecture:  x86-64

**Possible Solution**  

Forcing the suitesparse version back to 5.10.1 when creating the conda environment seems to make the build happy again.

Note suitesparse 7.7.0 was released ~5 days ago (May 2, 2024).

**Additional context**  

suitesparse 7.7.0 is not causing this issue on OSX.

**Comment by acpaquette** [comment]
Thank you for the heads up @kledmundson, seems like another dependency we will have to set a maximum

**Comment by kledmundson** [comment]
Closed via https://github.com/DOI-USGS/ISIS3/pull/5528.
