### ISSUE TITLE
HRSC level 3 images

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ISIS3#5497]
**ISIS version(s) affected**: latest

**Description**  

The [hrsc2isis](https://isis.astrogeology.usgs.gov/8.1.0/Application/presentation/Tabbed/hrsc2isis/hrsc2isis.html) program does not support level 3 images.

But level 2 images are no longer in PDS, it appears. At the link https://pds-geosciences.wustl.edu/mex/mex-m-hrsc-3-rdr-v4/ there are only new images that are level 3. Previous versions have been archived, per their release notes.

I was able to use  hrsc2isis with level 3 by simply changing 3 to 2 in the .img file. 

Maybe this tool can be revisited to accept level 3. Here's a recipe that shows the current workaround: https://stereopipeline.readthedocs.io/en/latest/examples/hrsc.html

**Comment by oleg-alexandrov** [comment]
To add, it appears that PDS still offers raw (non-mapprojected) HRSC images, but for some reason their img files shows "level 3", which appears to be interpreted by pds2isis to be mapprojected, perhaps. Here's a sample file: https://pds-geosciences.wustl.edu/mex/mex-m-hrsc-3-rdr-v4/mexhrs_4000/data/1995/h1995_0000_s23.img

**Comment by acpaquette** [comment]
@oleg-alexandrov This is something we have run into and should be able to address

**Comment by ballisticfox** [comment]
Has this actually been pushed to release? Doesn't seem to be working as of ISIS 8.1.0.

**Comment by ballisticfox** [comment]
For a bit of clarification here the ESA planetary science archive describes the processing levels as follows:
![image](https://github.com/user-attachments/assets/9a065364-3274-4f5e-a9e0-169befde6de2)

**Comment by amystamile-usgs** [comment]
@ballisticfox This fix is under the 8.3 release. Please see the [changelog](https://github.com/DOI-USGS/ISIS3/blob/dev/CHANGELOG.md) for release infomation. 8.3 is currently an RC. See ISIS conda versions [here](https://anaconda.org/usgs-astrogeology/isis/labels) for downloading.
