### ISSUE TITLE
About Apple M2 chip installation

### ISSUE THREAD

**Issue by ldx119** [DOI-USGS/ISIS3#5502]
For questions about using ISIS or the ISIS data area please [open a new discussion]([https://github.com/DOI-USGS/ISIS3/discussions](https://github.com/DOI-USGS/ISIS3/discussions/new/choose)). You can share a new idea, open a Q&A style question, or start a general discussion in that area. 
If I am installing isis on a M2 chip, which anoconda version should I choose to install?
<img width="1102" alt="截屏2024-05-17 10 30 13" src="https://github.com/DOI-USGS/ISIS3/assets/100507049/d87c36b7-9a3d-419c-aaf6-2c7d1a10a731">
Download for Intel or apple silicon?
Is there anything else you should be aware of?
The contirbutors on this project (developers and users) really appreciate the community interaction, so no discussion is too small to get started!

**Comment by amystamile-usgs** [comment]
If your Mac uses an M1 or M2 chip, it operates on Apple Silicon. Therefore, this is the appropriate download option for Anaconda.
