### ISSUE TITLE
mosrange error handling not implemented?

### ISSUE THREAD

**Issue by racm1906** [DOI-USGS/ISIS3#5513]
**ISIS version(s) affected**: 8.0.1 and 8.0.3

**Description**  
I tried to make a mosaic with the mosrange command, it worked a few times already but this time, an error from a file aborted the process. Documentation says that "ONERROR", "ERRORLOG" and "ERRORLIST" can prevent that, but when trying to add them, an error comes out saying that the parameter isn't recognized. I also tried the mosrange command without any parameter to open the ui for the command to see if the error parameters were there but they weren't. 

**How to reproduce**  
Using 8.0.1 8.0.3 version. Use mosrange command with "ONERROR" parameter.

**Possible Solution**  
It might be available in latest version of isis?

**Additional context**  
Do tell if further context is required.

**Comment by AustinSanders** [comment]
Hey @racm1906,  the error handling improvements are a fairly recent addition to mosrange.  These changes were considered a new feature (as opposed to a bugfix), so they will not be ported to the existing LTS release (8.0.x).

It looks like the earliest release containing the fix is 8.1.0.

**Comment by racm1906** [comment]
@AustinSanders gotcha! Thank you for the fast response!
