### ISSUE TITLE
FYI - Local 8.0.3 not fully accessible

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5524]
**ISIS version(s) affected**: isis8.0.3

**Description**  
Not really a bug...

The local version of isis8.0.3 is not fully set up. ISISROOT and ISISDATA need to be set as well as tab completion.

igs{157}> conda activate isis8.0.3
(isis8.0.3) igs{158}> printenv |egrep ISIS
(isis8.0.3) igs{159}> which qview
-/envs/isis8.0.3/bin/qview
(isis8.0.3) igs{160}> qview &
[1] 26087
(isis8.0.3) igs{161}> Please set ISISROOT before running any Isis applications

[1]    Exit 1                        qview

**Comment by acpaquette** [comment]
@lwellerastro This should be fixed now. Feel free to try it when you can and close if fixed

**Comment by lwellerastro** [comment]
all good - thanks!
