### ISSUE TITLE
Qmos - Seg faults only under isis8.2.0-RC#

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5539]
**ISIS version(s) affected**: isis8.2.0-RC1 and isis8.2.0-RC2, works under all other versions back to isis5.0.2

**Description**  
Qmos seg faults on images near the poles (not sure this is the issue) and in particular images crossing the 0/360 longitude boundary. In particular, when loading images using the default map file (equi, 0-360) the program does not seg fault. Seg fault occurs either switching to a polar stereographic projection (+/- 180 lon domain) for loaded images, or first opening the polar map file, then loading the images.

This happens with LROC NAC and Kaguya TC images (but not Cassini ISS of Titan). Seems to need a certain number of 0/360 longitude crossing images, but not sure. Have equi sets of images with 0/360 crossing images that do not make qmos seg fault, but those typically only have dozens of boundary crossing images and the polar lists have far more. But I really don't know what is causing this, only that it only occurs under the latest version of isis, but not prior versions.

**How to reproduce**  
See data under my work area /Isis3Tests/Qmos/LonBndry/
- launch qmos
- open list of cubes ktc_spole.lis (these are on scratch)
- load a new map file moon_spole_180lonsys.map (I typically use the lightening bolt/quick load icon for this)
- seg fault

**Additional context**  
I wonder if there is any relation to what is going on with #5520 and/or maybe updates to geos

**Comment by amystamile-usgs** [comment]
@lwellerastro isis8.2.0-RC2 was fixed and updated earlier this week. I would do a quick test and see if you are still seeing segfaults with Qmos.

**Comment by lwellerastro** [comment]
@amystamile-usgs, the program still segfaults using steps as described above

**Comment by amystamile-usgs** [comment]
Okay, I just wanted to make sure. I will take a look at this.

**Comment by amystamile-usgs** [comment]
@lwellerastro I was able to run the list you provide in qmos once I removed `M109088796LE.lev1.cub`. So I am going to look into why this particular cube is causing the segfault.
