### ISSUE TITLE
Install with Conda instructions have a syntax problem

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#562]
At
https://isis.astrogeology.usgs.gov/documents/InstallGuide/index.html

Where the instructions indicate to run isis3VarInit.py by specifying different arguments to isis3VarInit.py, the line reads:

`./$CONDA_PREFIX/scripts/isis3VarInit --data-dir=[path to data directory]  --test-dir=[path to test data directory]`

Which has a few of issues:
- It assumes a particular pwd
- the name of the script is missing its .py extension

**Comment by ihumphrey** [comment]
Re-built and uploaded a new conda build with these changes to the install guide.

**Comment by krlberry** [comment]
I don't see these changes on the website. We may want to update it.

**Comment by jlaura** [comment]
@kberryUSGS What is the status on this? Fixed or still lingering?

**Comment by jessemapel** [comment]
This has been fixed
