### ISSUE TITLE
ISIS Users, ISIS Contributors Sections and Glossary Missing in ISIS 8.3.0 Documentation

### ISSUE THREAD

**Issue by KrisBecker** [DOI-USGS/ISIS3#5635]
**Description**

The landing page for ISIS [8.3.0](https://isis.astrogeology.usgs.gov/8.3.0/) (also the Public Release link) is different/broken when compared to [8.2.0](https://isis.astrogeology.usgs.gov/8.2.0/)  and earlier versions.

The __ISIS Users__ and __ISIS Contributors__ sections are missing in 8.3.0. A signification portion of the left sidebar section of the 8.3.0 landing page is also missing when compared to 8.2.0.

Also, the [Glossary](https://isis.astrogeology.usgs.gov/8.2.0/documents/Glossary/Glossary.html)  does not exist in 8.3.0, therefore all ISIS documents that reference it gets the following [error](https://isis.astrogeology.usgs.gov/8.3.0/documents/Glossary/Glossary.html#SPICE) (with a SPICE reference in [campt](https://isis.astrogeology.usgs.gov/8.3.0/Application/presentation/Tabbed/campt/campt.html)):

```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: isis-site/8.3.0/documents/Glossary/Glossary.html
RequestId: XKQBTDG4F4T45ZHX
HostId: 2FrN++ZX77emygSExY+O19DOQQPTlXNc/oGfVvDdoLqj0V2KpOD5d5uBYM6hlWrv5rFw6S7T7W8=
```

**Suggested Edit**

Thanks!

**Comment by amystamile-usgs** [comment]
The isis.astrogeology.usgs.gov site is now only used to documented the isis applications. All other pages that once lived on this website has been migrated to our new software docs page here: [astrogeology.usgs.gov/docs](https://astrogeology.usgs.gov/docs/). I will add an issue to our [docs repo](https://github.com/DOI-USGS/asc-public-docs/) to update these links to the new [glossary](https://astrogeology.usgs.gov/docs/concepts/glossary/).
