### ISSUE TITLE
**ERROR** No Camera Kernels found for the LRO NAC images

### ISSUE THREAD

**Issue by DingXin998** [DOI-USGS/ISIS3#5639]
**ISIS version(s) affected**: x.y.z

**Description**  

When running spiceinit on LRO NAC images the program sends a
**ERROR** No Camera Kernels found for the image [M1472410644LE.cub] and [M1472417650RE.cub]
My isis version is 8.0.1 
I thought maybe my LRO spice data was not quite complete as these images were taken on 7 June 2024, so I downloaded it from https://naif.jpl.nasa.gov/pub/naif/LRO/kernels/ck/.Downloaded the ck file from 2024-05-10 to 2024-09-10 and put it inside the lro/kernels/ck folder on my local computer, still the same error.
**How to reproduce**  

**Possible Solution**  

What should I do to solve this problem, thanks
**Additional context**

**Comment by Kelvinrr** [comment]
I can double check the spice kernels, see if things are being updated correctly.

**Comment by Kelvinrr** [comment]
```

  Group = Selection
    Time = ("2024 JUN 05 00:01:09.239690 TDB",
            "2024 JUN 06 00:01:17.139541 TDB")
    File = $lro/kernels/ck/soc31_2024157_2024158_v01.bc
    Type = Reconstructed
  End_Group

  Group = Selection
    Time = ("2024 JUN 06 00:01:09.239541 TDB",
            "2024 JUN 07 00:01:17.139237 TDB")
    File = $lro/kernels/ck/soc31_2024158_2024159_v01.bc
    Type = Reconstructed
  End_Group

  Group = Selection
    Time = ("2024 JUN 07 00:01:09.234237 TDB",
            "2024 JUN 08 00:01:17.134079 TDB")
    File = $lro/kernels/ck/soc31_2024159_2024160_v01.bc
    Type = Reconstructed
  End_Group

  Group = Selection
    Time = ("2024 JUN 08 00:01:09.238080 TDB",
            "2024 JUN 09 00:01:17.138534 TDB")
    File = $lro/kernels/ck/soc31_2024160_2024161_v01.bc
    Type = Reconstructed
  End_Group
```

Looking at the DB, we have coverage for that time period. So it's def not that the data upstream is out of date. FYI, downloading directly from NAIF isn't enough since you also need the kernel.db files which are hosted by us. Did you update recently with `downloadIsisData lro $ISISDATA`?

**Comment by lwellerastro** [comment]
I was able to successfully spiceinit both of the mentioned images using isis8.3.0 using the local and efs mounted data areas. Seems like an lro isis data update is needed. 

Here's the kernel information from M1472417650RE's label after spiceinit:
```
  Group = Kernels
    NaifFrameCode             = -85610
    LeapSecond                = $base/kernels/lsk/naif0012.tls
    TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
                                 $lro/kernels/pck/moon_080317.tf,
                                 $lro/kernels/pck/moon_assoc_me.tf)
    TargetPosition            = ($lro/kernels/tspk/moon_pa_de421_1900-2050.bp-
                                 c, $lro/kernels/tspk/de421.bsp)
    InstrumentPointing        = ($lro/kernels/ck/soc31_2024159_2024160_v01.bc,
                                 $lro/kernels/ck/moc42r_2024152_2024183_v01.bc,
                                 $lro/kernels/fk/lro_frames_2014049_v01.tf)
    Instrument                = $lro/kernels/ik/lro_lroc_v18.ti
    SpacecraftClock           = $lro/kernels/sclk/lro_clkcor_2024290_v00.tsc
    InstrumentPosition        = $lro/kernels/spk/fdf29r_2024153_2024183_v01.b-
                                sp
    InstrumentAddendum        = $lro/kernels/iak/lro_instrumentAddendum_v05.ti
    ShapeModel                = $base/dems/ldem_128ppd_Mar2011_clon180_radius-
                                _pad.cub
    InstrumentPositionQuality = Reconstructed
    InstrumentPointingQuality = Reconstructed
    CameraVersion             = 2
    Source                    = ale
  End_Group
```

**Comment by DingXin998** [comment]
> ```
> 
>   Group = Selection
>     Time = ("2024 JUN 05 00:01:09.239690 TDB",
>             "2024 JUN 06 00:01:17.139541 TDB")
>     File = $lro/kernels/ck/soc31_2024157_2024158_v01.bc
>     Type = Reconstructed
>   End_Group
> 
>   Group = Selection
>     Time = ("2024 JUN 06 00:01:09.239541 TDB",
>             "2024 JUN 07 00:01:17.139237 TDB")
>     File = $lro/kernels/ck/soc31_2024158_2024159_v01.bc
>     Type = Reconstructed
>   End_Group
> 
>   Group = Selection
>     Time = ("2024 JUN 07 00:01:09.234237 TDB",
>             "2024 JUN 08 00:01:17.134079 TDB")
>     File = $lro/kernels/ck/soc31_2024159_2024160_v01.bc
>     Type = Reconstructed
>   End_Group
> 
>   Group = Selection
>     Time = ("2024 JUN 08 00:01:09.238080 TDB",
>             "2024 JUN 09 00:01:17.138534 TDB")
>     File = $lro/kernels/ck/soc31_2024160_2024161_v01.bc
>     Type = Reconstructed
>   End_Group
> ```
> 
> Looking at the DB, we have coverage for that time period. So it's def not that the data upstream is out of date. FYI, downloading directly from NAIF isn't enough since you also need the kernel.db files which are hosted by us. Did you update recently with `downloadIsisData lro $ISISDATA`?

I updated lro's kernels yesterday using the command downloadIsisData lro $ISISDATA，and then SPICEINIT works fine.
Thanks for your help.

**Comment by DingXin998** [comment]
> I was able to successfully spiceinit both of the mentioned images using isis8.3.0 using the local and efs mounted data areas. Seems like an lro isis data update is needed.
> 
> Here's the kernel information from M1472417650RE's label after spiceinit:
> 
> ```
>   Group = Kernels
>     NaifFrameCode             = -85610
>     LeapSecond                = $base/kernels/lsk/naif0012.tls
>     TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
>                                  $lro/kernels/pck/moon_080317.tf,
>                                  $lro/kernels/pck/moon_assoc_me.tf)
>     TargetPosition            = ($lro/kernels/tspk/moon_pa_de421_1900-2050.bp-
>                                  c, $lro/kernels/tspk/de421.bsp)
>     InstrumentPointing        = ($lro/kernels/ck/soc31_2024159_2024160_v01.bc,
>                                  $lro/kernels/ck/moc42r_2024152_2024183_v01.bc,
>                                  $lro/kernels/fk/lro_frames_2014049_v01.tf)
>     Instrument                = $lro/kernels/ik/lro_lroc_v18.ti
>     SpacecraftClock           = $lro/kernels/sclk/lro_clkcor_2024290_v00.tsc
>     InstrumentPosition        = $lro/kernels/spk/fdf29r_2024153_2024183_v01.b-
>                                 sp
>     InstrumentAddendum        = $lro/kernels/iak/lro_instrumentAddendum_v05.ti
>     ShapeModel                = $base/dems/ldem_128ppd_Mar2011_clon180_radius-
>                                 _pad.cub
>     InstrumentPositionQuality = Reconstructed
>     InstrumentPointingQuality = Reconstructed
>     CameraVersion             = 2
>     Source                    = ale
>   End_Group
> ```

Yes , the problem should have arisen because I didn't update LRO's kernels in time. it's generally fine now, thank you very much for your help!
