### ISSUE TITLE
Pattern Matching Document missing under 8.3.0

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5640]
**Description**
The link leading to the Pattern Matching Document via the Pointreg application documentation page returns a 404 error:

https://isis.astrogeology.usgs.gov/8.3.0/documents/PatternMatch/PatternMatch.html
```
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: isis-site/8.3.0/documents/PatternMatch/PatternMatch.html
    RequestId: F2FX7Q16FNKFGFQT
    HostId: fA/5vq9/tGVy4+alBNajqwKePuzytl3OMWHY7MWzPTujURjKOeDUD065hdMtFbxPTxkLJVAO2uQ=
```
The link was live under 8.2.0 and previous versions.

Thanks.

**Comment by amystamile-usgs** [comment]
This page has been migrated to https://astrogeology.usgs.gov/docs/concepts/control-networks/automatic-registration/. We just need to update the links in isis.astrogeology.usgs.gov.

**Comment by lwellerastro** [comment]
Thanks @amystamile-usgs - I see that now. But there appears to be a number of really important concepts (and figures) missing which is unfortunate since this topic is complex and defaults rarely get the job done. I guess I'd better make a copy of the old documentation.

**Comment by amystamile-usgs** [comment]
I did notice that the new page was missing a bunch of info. All of the info should have been converted to the new docs site unless it was felt the information was no longer relevant. I think it's worth keeping this issue open to make sure all the necessary information is transferred over to the new page.

The good news is that the older isis site versions will be retained for archive purposes so there is no risk of this information being lost.
