### ISSUE TITLE
Cube header support 

### ISSUE THREAD

**Issue by jmk0502** [DOI-USGS/ISIS3#5641]
Hello, 
This is a basic question from a beginner. 
Could anyone tell me how to access the cube header ? I have downloaded data(as .img file) and it has an attached label file(.lbl). After importing it into ISIS, the .cub file is created. If I want to check the base and multiplier values, how do I access the header? 
I am looking for ways to modify the low/high representation values in the cube after some mathematical operations and I would like some insight on how to go about it. 
Any help is much appreciated, thanks.

**Comment by amystamile-usgs** [comment]
It sounds like you are interested in looking at the cube's label (header). You can use the [catlab](https://isis.astrogeology.usgs.gov/8.3.0/Application/presentation/Tabbed/catlab/catlab.html) app to view the label. To edit the label, you can use the [editlab](https://isis.astrogeology.usgs.gov/8.3.0/Application/presentation/Tabbed/editlab/editlab.html) app. 

Here is the full ISIS application list if you would like to see if there are additional apps that meet your needs: https://isis.astrogeology.usgs.gov/8.3.0/Application/index.html

**Comment by jmk0502** [comment]
Thank you so much! This solves my issue.
