### ISSUE TITLE
Incorrect handling of Radius in jigsaw gui and in bundleout.txt file when running a rectangular (XYZ) bundle adjustment.

### ISSUE THREAD

**Issue by kledmundson** [DOI-USGS/ISIS3#5642]
**ISIS version(s) affected**: x.y.z
dev

**Description**  

1) In the _jigsaw_ gui, if  the CONTROL_POINT_COORDINATE_TYPE_BUNDLE under "Control Point Parameters" is RECTANGULAR, then the RADIUS checkbox under "Solve Options" should be excluded.

2) With error propagation turned on in a rectangular (XYZ) solution, uncertainty statistics for Point Z coordinates are not reported in the "POINTS UNCERTAINTY SUMMARY" section. Instead, the RMS, MIN, and MAX of RADIUS coordinates is reported as "N/A."
 
**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by AustinSanders** [comment]
Closed via #5643
