### ISSUE TITLE
spiceinit issue for DAWN FC

### ISSUE THREAD

**Issue by qingzhang-zq** [DOI-USGS/ISIS3#5667]
Hi, my ISIS version is 8.0.1 and I have downloaded base and DAWN data. 

When I run _spiceinit_ for the FC 1b data, like spiceinit from=FC21B0037363_15156174933F1I.cub, the error shows that Unable to initialize camera model. But it works for the DAWN VIR 1b data. Any ideas on how it? Thank you in advance for any help.

**Comment by qingzhang-zq** [comment]
OK, I find an alternative solution. Specifying the target name using _dawnfc2isis_ then _spiceinit_ can identify the camera model.

**Comment by Kelvinrr** [comment]
@ZinuZhang I will consider this closed, if the you still believe there is a bug to be fixed, feel free to re-open
