### ISSUE TITLE
A question about whether light time aberration correction is used when processing LROC NAC images by ISIS

### ISSUE THREAD

**Issue by Bin501** [DOI-USGS/ISIS3#5677]
# There is a ppt about aberration corrections in SPICE tutorials:
![light_time](https://github.com/user-attachments/assets/2cab3e36-94b6-4a6e-91e9-c4219dc572c4)

# Which aberration correction is used when processing LROC NAC images?
 NONE, LT ("light time only"), or LT+S ("light time plus stellar aberration")? 
It seems that LT+S would make it better.

I would be grateful for your prompt reply.

**Comment by AustinSanders** [comment]
Buried in documentation for ALE:
```
LROC is specifically set to not use light time correction because it is
        so close to the surface of the moon that light time correction to the
        center of the body is incorrect.
```

**Comment by acpaquette** [comment]
Some other relevant reading referenced in the ISIS iak for LRO, LROCNAC/WAC:
https://www.lpi.usra.edu/meetings/lpsc2013/pdf/2318.pdf

**Comment by acpaquette** [comment]
Some other context w.r.t. the paper linked. The fixes in that paper have been implemented in ISIS in 2012. The variables used for LRO are set to "NONE" for the aberration correction. So as @AustinSanders mentioned, no light time correction is applied to LRO. As for the reasoning I am not sure. The reason given in the docs seems to be correct but I don't have a source to verify it.

**Comment by AustinSanders** [comment]
Since we've found a conclusive "no," for this issue as well as some supporting documentation and reasoning, I'm going to close this issue.  For more extended discussion related to this issue, we should open a [discussion topic](https://github.com/DOI-USGS/ISIS3/discussions/new/choose).

**Comment by Bin501** [comment]
I see. Thank you very much.
