### ISSUE TITLE
Incorrect default for $ISISROOT in 3.6.0 Startup Scripts

### ISSUE THREAD

**Issue by dpmayerUSGS** [DOI-USGS/ISIS3#569]
It looks like /usgs/pkgs/isis3.6.0/isis/scripts/isis3Startup.sh is using the incorrect default for `$ISISROOT` and this is causing the wrong bin directory to be set.  As I understand it, the correct default for $ISISROOT should be `/usgs/pkgs/isis3.6.0/install`

However, when I run `source /usgs/pkgs/isis3.6.0/isis/scripts/isis3Startup.sh`, my `$PATH` gets updated to include `/usgs/pkgs/isis3/isis/bin`, but this directory no longer exists in 3.6.0. As a result, I can't run any ISIS3 programs.

I haven't tested the analogous startup script for CSH, so I don't know if that script has the same issue. Either way, this should only affect internal USGS users because external users are expected to install 3.6.0 through `conda`. I have confirmed that this has broken PDS Services (MAP2 and POW).

**Comment by jessemapel** [comment]
We still need to get this out in a release and update the internal symlink. I'm going to re-open this until the ISIS version in `/usgs/pkgs/isis3` has this change.

For anyone that this is affecting, they can use the script in tomorrow's nightly build (11/16/18) with the current 3.6.0 build we have. The script is not actually tied to the ISIS checkout that contains it.

**Comment by jessemapel** [comment]
- [x] cherry-pick to the release branch
- [ ] put out a new release

**Comment by ihumphrey** [comment]
@jessemapel the cherry-pick into release looks like it is done (#574), so i'll kick off a build.

**Comment by ihumphrey** [comment]
@jessemapel the newest stable build (build 5 on anaconda cloud) should have these changes.
