### ISSUE TITLE
Broken links in install guide on ISIS3 website

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#590]
At: https://isis.astrogeology.usgs.gov/documents/InstallGuide/index.html

Under "DTM Requirements" (which is also an odd place), all of the following links are broken:

- Getting Started With GitHub
- Building ISIS3 With cmake
- New ISIS3 environmental variables and their meanings
- Custom data and test directories
- Cleaning builds
- Building individual applications/objects
- Building ISIS3 documentation
- What to do if you encounter any problems

**Comment by twilson271828** [comment]
The URLs changed.  Was not expecting that.  I agree that this section should be moved up earlier in the document.

**Comment by krlberry** [comment]
The broken links are still up on the website. I know this was fixed in the codebase, is it okay to re-open this ticket to actually get the website updated with the latest documentation? @scsides I think you were looking into how to do this post-cmake?

**Comment by scsides** [comment]
The docs on the web site all come from a build of ISIS3 aka public release. If we push docs from a current build all changed documentation will be updated before the actual code is released. @jlaura has an issue associated with getting the docs updated for the upcoming release candidate. OR the pages could be edited by hand.

**Comment by jlaura** [comment]
I just checked all of these links and they rendered properly to the GitHub page.
