### ISSUE TITLE
Add the unlicense "license" to the root of the repository

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#591]
See #587 #588 This can be copied from http://unlicense.org/

**Comment by rbeyer** [comment]
It could be, you could also use CC0 (https://creativecommons.org/share-your-work/public-domain/cc0/), but I think they are reasonably equivalent that this point in time.

**Comment by jessemapel** [comment]
We already use the unlicense in some of our other projects so I'd like to stick to that one. This should resolve the copyright with outside contribution issue.
