### ISSUE TITLE
Can we deprecate mocuncompress?

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#593]
The app docs can be found [here](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/mocuncompress/mocuncompress.html).

I propose we remove the functionality to ingest compressed MGS MOC data. It can still be ingested with old versions of ISIS and then used in new versions.

**Comment by scsides** [comment]
What is the reason we would want to do this?

**Comment by scsides** [comment]
Confirmed with PDS: The ~= 250,000 MOC files in the archive are all compressed, and are the official archive.

**Comment by jessemapel** [comment]
All of the decompression code is C code. Part of the new setup is pushing all extra code in application directories into the ISIS3 library. Pushing the decompression methods into the library has been complex and if possible it would be nice to deprecate it.

@Kelvinrr Can comment more as to the specific issues.

**Comment by jessemapel** [comment]
I think this is resolved as a no
