### ISSUE TITLE
conda config suggestion

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#612]
Your current `conda` configuration for the ISIS 3.6 release suggests a conda-wide manipulation of the channel priorities.
Because the user might not want to have the USGS' preferred library versions to be taken into account for all their conda environments, I suggest to change your instructions to be enviroment-specific.

This is how this can be done:

* `conda create -n isis3 python=3.6`

> conda's default python 3.6 will be chosen at this point, but will be overridden later by your dependency tree

* `source activate isis3`
*  `conda config --env --add channels conda-forge`
* `conda config --env --add channels usgs-astrogeology`
> the `--env` is the crucial part here, so that these channel priorities only become true for the currently activated environment
* conda install -c usgs-astrogeology isis3
> Unless you expect other channels to have an `isis3` the provision of the channel is actually not required anymore at this point.

The rest of your instructions would stay the same. I have successfully tried this out and am personally running all my conda envs like this, so that channel-dependent configurations don't interfere with other environments. This possibility is an under-documented feature of conda. You can look at the full dependency tree for conda using `conda config --show-sources`.

**Comment by thareUSGS** [comment]
Good comments on the adding these channels only under the isis3 env. 

I also don't understand the last statements on the install page of running the Python script every time in the .bashrc. Once it is run, isn't it true one just needs to add "source activate isis3" to their .bashrc. This also assumes conda has been added to the user's environment (which is an optional step during the conda install). 

Lastly, under Ubuntu, I still need to run "**conda** activate isis3" not "source activate isis3". Perhaps that can be listed if "source" is not found.

**Comment by michaelaye** [comment]
Since conda=4.4 the default command is "conda activate <env_name>", having replaced conda from being an actual executable to be a shell-only function. After complaints, I think they put back the functionality of "source activate <env_name>" but apparently not consistently on all systems and/or shells. For example, on my zsh setup, I still can use "source activate" while on conda 4.5, while on fish I can not, using the same version of conda, and using the officially provided setup scripts for both zsh and fish. 
If you have conda>=4.4, the default is definitely "conda activate <env_name>", while the path to the conda binaries should be removed from the general path, and a setup script should be sourced instead. See details here: https://www.anaconda.com/blog/developer-blog/how-to-get-ready-for-the-release-of-conda-4-4/

I didn't dive into that weird double-call of source activate yet for my understanding, however, I'm quite happy that I can have more than one isis3 (for bugfixes and testing) but with the same data-dir now easily.

**Comment by jessemapel** [comment]
@thareUSGS That last line is a hold over from when you had to run the ISIS3 startup script every time. You are correct that the varinit script only needs to be run once.

**Comment by jessemapel** [comment]
Here's a sample install guide with updated wording and instructions. You'll have to download it and then rename it to a .html before opening it in a browser.

[index.txt](https://github.com/USGS-Astrogeology/ISIS3/files/2621453/index.txt)

**Comment by michaelaye** [comment]
but this is only the lead-in index page? I don't see any instructions? I did the rename but no URL works because the other pages are not there?

**Comment by jessemapel** [comment]
Oops my bad, I'll put the correct one up

**Comment by jessemapel** [comment]
This should be the correct one. It will look different than the website because it is missing all of the CSS.

[index.txt](https://github.com/USGS-Astrogeology/ISIS3/files/2621704/index.txt)

**Comment by michaelaye** [comment]
Looks good to me.

**Comment by thareUSGS** [comment]
Hmm - I am feeling like new users are going to still get lost. Not for getting ISIS3 binaries installed, but with steps to get the data (which is required for ISIS3 to run correctly). For example, just installing ISIS3 binaries, the apps will run but none of the "data" icons or data files (e.g. templates) are available so the GUIs and apps will only try to work (but not well). Also shouldn't we default to "conda activate" instead of "source", since that is the new recommendation (thus "source" would be the just in case line _Depending on your OS...._).

So on the original page we had a minimal example install. Perhaps bring that back. (And our continued use of "--delete" in the rsync command still freaks me out. Any chance there is a different way to do that?)

**Example ISIS3 Install**
_This is an example of downloading ISIS for an Ubuntu 18.04 LTS system using bash as your shell._

```
**First get Miniconda (or Anaconda) and install*
$ wget https://repo.anaconda.com/miniconda/Miniconda2-4.5.11-Linux-x86_64.sh
$ chmod +x Miniconda2-4.5.11-Linux-x86.sh
$ ./Miniconda2-4.5.11-Linux-x86.sh
**this will guide you through the installation. Generally all defaults are fine although it is recommended to add the conda install location to your PATH environment.**

$ conda create -n isis3
$ conda activate isis3
$ conda config --env --add channels conda-forge
$ conda config --env --add channels usgs-astrogeology
$ conda install -c usgs-astrogeology isis3
**this may take a minute to initiate and you will be prompted to confirm before installation.**
**once confirmed, the 50+ required packages, including ISIS3, will be downloaded and installed**

$ python $CONDA_PREFIX/scripts/isis3VarInit.py
**the line above will modify your conda startup environment for ISIS3. It is located here: **
    **   $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh **

**let's initialize isis3 with the new environment**
$ conda activate isis3

**now let's get some required data files and some optional mission data**
    **note the data location can be also be changed from this example location**
    **note: it is recommended to get all the data, but to exclude larger DEMs you can add --max-size=100m (100 megabytes) above to the rsync line**
$ cd $CONDA_PREFIX
$ rsync -azv --partial isisdist.astrogeology.usgs.gov::isis3data/data/base data/

**now pick your missions. For speed, this shows without kernels, but you will probably need them**
**example MRO**
$ rsync -azv --partial --exclude='kernels' isisdist.astrogeology.usgs.gov::isis3data/data/mro data/
**example LRO**
$ rsync -azv --partial --exclude='kernels' isisdist.astrogeology.usgs.gov::isis3data/data/lro data/

**Done. So whenever you want to run ISIS3, in your shell, type:**
$ conda activate isis3
```

**Comment by jessemapel** [comment]
@thareUSGS That looks good, but is a little outside of the scope of this issue. I'd be happy to see a pull request with the changes you're proposing 😃

All you need to do is modify the file that's modified in #617. It's just html.

**Comment by jlaura** [comment]
@jessemapel @michaelaye @thareUSGS Can we close this as resolved?

**Comment by michaelaye** [comment]
I'm sorry, I failed to see that the instructions are dangerously out of order on the install page.

It says to configure the extra channels before creating and entering the newly created conda environment, which can break existing setups for users!
So this needs to be fixed.

The following part needs to come **AFTER** the creation and activation of the isis3 env:
```
#Add the following channels to the Anaconda installation
          conda config --add channels conda-forge
          conda config --add channels usgs-astrogeology

          #Verify you have the correct channels:
          conda config --show channels

          #You should see:

          channels:
              - usgs-astrogeology
              - conda-forge
              - defaults

           #The order is important.  If conda-forge is before usgs-astrogeology, you will need to run:

           conda config --add channels usgs-astrogeology
```
and the activation command should be `conda activate <env>` these days in all cases now (recently was fixed to be the same on all O/S, I believe).

**Comment by jlaura** [comment]
@michaelaye Can you submit a PR?

**Comment by michaelaye** [comment]
Actually, it's correct in https://github.com/USGS-Astrogeology/ISIS3/commit/4ab2fdd940a925f4f3a53d900cd6c3db939fdb44 it's just still not pushed to the website at https://isis.astrogeology.usgs.gov/documents/InstallGuide/index.html

**Comment by jlaura** [comment]
:+1: Thanks for catching that!

**Comment by jessemapel** [comment]
I need to make a note to push the docs for 3.6.2 on Monday!

**Comment by michaelaye** [comment]
This is still not available to the public? Wouldn't it be better to not prematurely close issues, to not lose track of them?
