### ISSUE TITLE
Kernel downloads malfunctioning

### ISSUE THREAD

**Issue by USGSsakins** [DOI-USGS/ISIS3#639]
Following the conversion to the cmake build system, the scheduled cron jobs to update kernels are getting incorrect paths:

Example error:
/usgs/cpkgs/isis3/isis3mgr_scripts/distributeData: line 142: /usgs/pkgs/isis3/install/install/scripts/isis3Startup.sh: No such file or directory

**Comment by krlberry** [comment]
I think @scides fixed this earlier this week. Can this ticket be closed?

**Comment by jlaura** [comment]
@USGSsakins I am going to close this issue as no response in > a year. If this is still an issue, please reopen.
