### ISSUE TITLE
Jenkins Build Env

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#641]
These are the current machines that we have for builds. Which of these need to be set up for builds inside of Jenkins?

- [ ] Ubuntu 14
- [x] Ubuntu 18
- [ ] Scientific Linux 6.5
- [x] Centos 7.2
- [ ] Fedora 25
- [x] Fedora 28
- [ ] Debian 8

Which of these OSes should be used for building for now? Which need images on the Jenkins side?

**Comment by jessemapel** [comment]
With 3.6.0 we decided to support the following for builds:
* Fedora 28
* Ubuntu 18
* Mac OS 10.13
* CentOS 7

**Comment by jlaura** [comment]
The internally accessible jenkins-dev.wr.usgs.gov server has a docker-testing project where the we have working builds with failing tests. @kdl222 and @evindunn have done an amazing job getting the pipeline in place, containers, built, etc. I would also like to push this issue as a candidate to address in the upcoming support/maintenance sprint.

**Comment by jlaura** [comment]
This is going to be getting the ubuntu container running all tests; ideally tests passing, but not req. as of today. @jlaura will follow up with @evindunn re: webhook.

**Comment by jlaura** [comment]
Jenkins-dev is running internally. Closing.
