### ISSUE TITLE
Migrating RedMine Tickets

### ISSUE THREAD

**Issue by USGSsakins** [DOI-USGS/ISIS3#642]
This issue is to track the migration of tickets from RedMine into Git Issues.  The following criteria need to be completed or researched for this issue to be closed:

- [ ] Date stamp - does the creation time stamp from RedMine get migrated into the Git issue?
- [ ] Migrate "who" created the tickets
- [ ] Migrate watchers from RedMine tickets to Git issues?
- [ ] Some closed RedMine tickets are tied to an ISIS version number, how do we migrate this?
- [ ] Select the list of projects to migrate from RedMine
- [ ] Map projects to existing GitHub Repos (ISIS3, PDS-Pipelines, etc.)
- [ ] Migrate subset of tickets to temporary repo for review/evalution
- [ ] Prior to official migration shut down RedMine ticket submissions
- [ ] Prior to official migration, post change of operations on RedMine pointing people at GitHub repo
- [ ] Prior to official migration, update all web links referring to RedMine to point at GitHub
- [ ] Update GitHub issue template to point people at Discourse for questions and give details on how to report bugs or request features

**Comment by jlaura** [comment]
Issue have been migrated.
