### ISSUE TITLE
Test data required from outside of testData area

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#649]
These tests are dependent of data that is not located within the specified testData dir:

* chandrayaan1_unit_test_Chandrayaan1M3Camera
* lro_unit_test_MiniRF
* sumspice_app_test_dawn

**Comment by SgStapleton** [comment]
(isis3) bash-4.2$ ctest -R chandrayaan1_unit_test_Chandrayaan1M3Camera --verbose
UpdateCTestConfiguration  from :/usgs/pkgs/isis3nightly2018-12-17/build/DartConfiguration.tcl
Parse Config file:/usgs/pkgs/isis3nightly2018-12-17/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/usgs/pkgs/isis3nightly2018-12-17/build/DartConfiguration.tcl
Parse Config file:/usgs/pkgs/isis3nightly2018-12-17/build/DartConfiguration.tcl
Test project /usgs/pkgs/isis3nightly2018-12-17/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1162
    Start 1162: chandrayaan1_unit_test_Chandrayaan1M3Camera

1162: Test command: /usgs/cpkgs/anaconda3_linux/envs/isis3CentOS7/bin/cmake "-DTEST_PROG=/usgs/pkgs/isis3nightly2018-12-17/build/unitTest/chandrayaan1_unit_test_Chandrayaan1M3Camera" "-DTRUTH_FILE=/usgs/pkgs/isis3nightly2018-12-17/isis/src/chandrayaan1/objs/Chandrayaan1M3Camera/Chandrayaan1M3Camera.truth" "-DDATA_ROOT=/usgs/cpkgs/isis3/data" "-DCODE_ROOT=/usgs/pkgs/isis3nightly2018-12-17/isis" "-P" "/usgs/pkgs/isis3nightly2018-12-17/isis/cmake/RunUnitTest.cmake"
1162: Test timeout computed to be: 1500
1162: -- ISISROOT = /usgs/pkgs/isis3nightly2018-12-17/build
1162: -- ISIS3DATA = /usgs/cpkgs/isis3/data
1162: outputFile = /usgs/pkgs/isis3nightly2018-12-17/build/unitTest/chandrayaan1_unit_test_Chandrayaan1M3Camera.output
1162: ln: failed to create symbolic link ‘/usgs/pkgs/isis3nightly2018-12-17/isis/src/chandrayaan1/objs/Chandrayaan1M3Camera/unitTest’: File exists
1162: Files "/usgs/pkgs/isis3nightly2018-12-17/build/unitTest/chandrayaan1_unit_test_Chandrayaan1M3Camera.output" to "/usgs/pkgs/isis3nightly2018-12-17/isis/src/chandrayaan1/objs/Chandrayaan1M3Camera/Chandrayaan1M3Camera.truth" are different.
1162: ------------------ DIFFERENCES ------------------ 
1162: 40,46c40,41
1162: < **ERROR** Unable to initialize camera model from group [Instrument].
1162: < **PROGRAMMER ERROR** Unable to create a shape model from given target and pvl.
1162: < **I/O ERROR** Invalid shape model file [/work/projects/lro_minirf_proc/DEMS/SPOLE/141118_DEM/LRO_LOLA_SPole45S_LDEM_30m_Mar2014_NS5_radius-prep.cub] in Kernels group.
1162: < **ERROR** The given shape model file is not a valid ISIS DEM. Unable to open as an ISIS cube.
1162: < **I/O ERROR** Unable to open [/work/projects/lro_minirf_proc/DEMS/SPOLE/141118_DEM/LRO_LOLA_SPole45S_LDEM_30m_Mar2014_NS5_radius-prep.cub].
1162: < **ERROR** The given shape model file is not a valid NAIF DSK file. Unable to construct a NAIF DSK shape model.
1162: < **USER ERROR** NAIF DSK file [/work/projects/lro_minirf_proc/DEMS/SPOLE/141118_DEM/LRO_LOLA_SPole45S_LDEM_30m_Mar2014_NS5_radius-prep.cub] does not exist.
1162: ---
1162: > For a central pixel position ...
1162: > SetImage succeeded.
1162: 
1162: ------------------------------------------------- 
1162: CMake Error at /usgs/pkgs/isis3nightly2018-12-17/isis/cmake/RunUnitTest.cmake:69 (message):
1162:   Test failed - files differ
1162: 
1162: 
1/1 Test #1162: chandrayaan1_unit_test_Chandrayaan1M3Camera ...***Failed    0.50 sec

**Comment by jlaura** [comment]
Now that the migration to jenkins has been completed, are all of the test files in the expected location? I am guessing they are because of how Jenkins (Docker) is mounting the dirs, but want to confirm before closing.

**Comment by jessemapel** [comment]
Just checked these are done
