### ISSUE TITLE
Request copy/transfer of Redmine ciss2isis ticket to GH

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#671]
Hi Stuart et al,

could you please copy/transfer my ciss2isis ticket here so that I can start working on a pull request with potential solutions? I really need this fixed rather soon, currently I'm using `fillgaps` to fill the holes at 255 pixel value, which isn't nice. I'm fine exploring solutions, it will make me learn more about the interior of the ISIS code.

**Comment by jlaura** [comment]
@michaelaye We are working on a migration setup now that will carry over the conversation, tags, etc. This will not be done until sometime in the new year. If you want it over sooner, can you cherry pick the information that you need out of [the ticket](https://fixit.wr.usgs.gov/fixit/issues/5485) and open a new issue here?

If you are happy to wait for the migration, that works too.

**Comment by michaelaye** [comment]
Done: https://github.com/USGS-Astrogeology/ISIS3/issues/672
