### ISSUE TITLE
Create release notes for conda build

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#675]
Figure out how to create release notes when building to upload to anaconda.

**Comment by jlaura** [comment]
@SgStapleton Can we close this?

**Comment by jessemapel** [comment]
IMO this is not done until it is documented on https://github.com/USGS-Astrogeology/ISIS3/wiki/Public-Release-Process

**Comment by jessemapel** [comment]
Documented on the release wiki

https://github.com/USGS-Astrogeology/ISIS3/wiki/Public-Release-Process#step-7-communicate-availability-of-build
