### ISSUE TITLE
initISIS.sh: no such file or directory

### ISSUE THREAD

**Issue by lpigue** [DOI-USGS/ISIS3#677]
I updated the directory just after July to point to the /usgs/cpkgs/isis3/isis3mgr_scripts correctly (I think - it looks right in the cshrc), but when I log into PuTTY, I get the error message: "/home/isis3mgr/bin/initIsis.sh: No such file or directory"

Please speak plainly, I don't know how to speak programmer.

**Comment by lwellerastro** [comment]
Try this instead: /usgs/cpkgs/isis3/isis3mgr_scripts/initIsisCmake.csh

**Comment by lpigue** [comment]
Unless there's something I can't see in vi cshrc, it must be something else. My setisis alias is:

alias isis '/usgs/cpkgs/isis3/isis3mgr_scripts/initIsisCmake.csh'

I have user scripts that reference the bin that was removed, but they have cdev in the path, so they didn't seem to apply to Makayla's email from July. Was this in error?

I don't have anything related to ISIS in my bashrc, it's all anaconda.

**Comment by jlaura** [comment]
@lglaspie Your .cshrc is doing a ton of stuff. Can you please move that into a backup and start with a cleaner cshrc that only as an isis alias to the script above from @lwellerastro?

Also, what error are you seeing with the new alias?

**Comment by lpigue** [comment]
The error hasn't changed.

**Comment by jlaura** [comment]
It sounds like you have a PuTTY configuration error then. Also, your .cshrc has not changed. 

`6.1K Dec 20 19:11 .cshrc`

**Comment by lpigue** [comment]
I haven't moved things to backup - I have to figure out how to do that (see last line of original post).

The error not changing was in reference to changing from initIsis.sh to initIsisCmake.csh
The error message is still the same.

**Comment by jessemapel** [comment]
@lglaspie Which system are you connecting to via putty? We found that a few of the systems lost their NFS mounts, stuff like /work and /usgs.

**Comment by krlberry** [comment]
@lglaspie, check out your `.bash_profile`? 

It has:
```
alias setisis="source /home/isis3mgr/bin/initIsis.sh"

source /home/isis3mgr/bin/initIsis.sh isis3
```
in it, which may be the source of your problem.

**Comment by lpigue** [comment]
I connect on astrovm4 from PC (I'm on one of the loaner travel laptops).

I've run models from shareall and my /home directories within the last couple of weeks successfully through astrovm4 on PuTTY. Tech set it up for me, so I don't know anything about its configuration.

**Comment by lpigue** [comment]
Thank you Kristin, I will check that out!

**Comment by jlaura** [comment]
@lglaspie Is this resolved?

**Comment by lpigue** [comment]
Thank you for getting back to this so quickly! 

Kristin was right, the bash_profile seems to be the problem, but I didn't set it up and I don't know what it's supposed to be. I tried to log in to the training vm from the summer to see what that was and fix it myself, but it's inaccessible. :/

**Comment by jessemapel** [comment]
@lglaspie Looking at your bash_profile on the network home, you should replace it with the following

```
alias setisis="source /usgs/cpkgs/isis3/isis3mgr_scripts/initIsisCmake.sh"

source /usgs/cpkgs/isis3/isis3mgr_scripts/initIsisCmake.sh isis3
```

That will point you to the correct "set isis" and automatically set you to the standard ISIS3 version when you log in.

**Comment by jlaura** [comment]
@lglaspie Is this closable then?

**Comment by lpigue** [comment]
Yeah, I think so. I'm not getting any error messages rn, but there may be other reasons for that. A few of us "lunatics" may be working together on some ISIS work soon and may find out then, but I didn't get any errors yesterday. 
Thanks!
