### ISSUE TITLE
stereo_parse: symbol lookup error

### ISSUE THREAD

**Issue by phil333** [DOI-USGS/ISIS3#681]
I have isis3 up and running in conda on ubuntu18.04, but I have an issue with the ames stereo pipeline. For some reason i get the following error when running the stereo_parse command: 

stereo_parse: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_mutex_unlock

Exception: Failed executing: /home/user/anaconda3/envs/isis3/StereoPipeline/libexec/stereo_parse map1.cub map2.cub stereo-output --threads 12 --corr-seed-mode 1 --stereo-file ./stereo.default --tif-compress LZW

**Comment by rbeyer** [comment]
phil333, This sounds like an issue that you should have filed on ASP, so I posted it there: https://github.com/NeoGeographyToolkit/StereoPipeline/issues/218#issue-398942363

However, the US Federal government is closed, so most of the people that work on ISIS and ASP will be unable to help you much until the shutdown is over.

**Comment by oleg-alexandrov** [comment]
I fixed this a few days ago. I will suggest you fetch the latest build from https://byss.arc.nasa.gov/stereopipeline/daily_build/ and give it a try. A different user reported that the fix worked for him. Do let me know if this works for you or not.

**Comment by jlaura** [comment]
Closing here. Any additional discussion should be over on 
https://github.com/NeoGeographyToolkit/StereoPipeline/issues/218#issue-398942363.
