### ISSUE TITLE
Error installing ISIS3 with conda - packages not available

### ISSUE THREAD

**Issue by geomorphicjosh** [DOI-USGS/ISIS3#687]
Hi,
I've been following the USGS isis3 installation instructions for Windows 10 using Anaconda (https://isis.astrogeology.usgs.gov/documents/InstallGuide/index.html#RunningOnWindows) and run into some problems with installing the package. 

> (isis3) C:\Users\josh->conda install -c usgs-astrogeology isis3
> Collecting package metadata: done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - isis3
> 
> Current channels:
> 
>   - https://conda.anaconda.org/usgs-astrogeology/win-64
>   - https://conda.anaconda.org/usgs-astrogeology/noarch
>   - https://conda.anaconda.org/conda-forge/win-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://repo.anaconda.com/pkgs/main/win-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/free/win-64
>   - https://repo.anaconda.com/pkgs/free/noarch
>   - https://repo.anaconda.com/pkgs/r/win-64
>   - https://repo.anaconda.com/pkgs/r/noarch
>   - https://repo.anaconda.com/pkgs/msys2/win-64
>   - https://repo.anaconda.com/pkgs/msys2/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

I have searched through similar threads, but can't seem to solve the issue. Am I missing something here? Could anyone help me with this issue?

Thanks in advance,
Josh

**Comment by jessemapel** [comment]
@geomorphicjosh This looks like an issue with how we put the ISIS3 package up on Anaconda. It is under our linux/mac directories. We can fix this by putting the linux package up under the noarch directory.

I'll see about getting this done.

**Comment by geomorphicjosh** [comment]
@jessemapel I see. That would be much appreciated. Please keep me posted on this.

**Comment by jessemapel** [comment]
@thareUSGS Were you seeing similar channel listings when you tried this? specifically

```
https://some.anaconda.channel/win-64
https://some.anaconda.channel/noarch
```

@geomorphicjosh Are you using a linux install of Anaconda on the windows Ubuntu subsystem? It looks like you may be using a windows install of Anaconda.

**Comment by geomorphicjosh** [comment]
@jessemapel That may be the issue. I think I'm using the windows install rather than the linux install. I will check and verify

**Comment by jessemapel** [comment]
My previous statement about moving the linux install to noarch is probably a bad idea. I've been thinking about Python projects too much :(

**Comment by thareUSGS** [comment]
Let me give it another shot under Ubuntu 18.x for Windows Subsystem for Linux (WSL). I think the last time I tested ISIS3 under WSL, I didn't have any channel issues (so that is new), but I was plagued by an OpenCV issue that I couldn't resolve. 

We still support a prebuilt virtual machine for the free [Virtual Box](https://www.virtualbox.org/). It is running ISISI 3.5.2 so we will need to upgrade that to 3.6.0. But this might get you up and running for now.
ftp://pdsimage2.wr.usgs.gov/pub/pigpen/isis3_VM/

**Comment by geomorphicjosh** [comment]
@jessemapel OK, I have installed anaconda with Ubuntu (as it was solely installed on Windows. The issue still seems to persist, although the error has changed to include python (see below). 

> (isis3) geomorphicjosh@WaffleII:~$ conda install -c usgs-astrogeology isis3
> Fetching package metadata ...............
> Solving package specifications:
> 
> PackageNotFoundError: Packages missing in current channels:
> 
>   - isis3 -> python 3.6
> 
> We have searched for the packages in the following channels:
> 
>   - https://conda.anaconda.org/usgs-astrogeology/linux-64
>   - https://conda.anaconda.org/usgs-astrogeology/noarch
>   - https://conda.anaconda.org/conda-forge/linux-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://repo.continuum.io/pkgs/main/linux-64
>   - https://repo.continuum.io/pkgs/main/noarch
>   - https://repo.continuum.io/pkgs/free/linux-64
>   - https://repo.continuum.io/pkgs/free/noarch
>   - https://repo.continuum.io/pkgs/r/linux-64
>   - https://repo.continuum.io/pkgs/r/noarch
>   - https://repo.continuum.io/pkgs/pro/linux-64
>   - https://repo.continuum.io/pkgs/pro/noarch

**Comment by geomorphicjosh** [comment]
OK, @jessemapel - I have installed Anaconda with Ubuntu which has been successful. I have an issue with one line in the compiling code
` ./$CONDA_PREFIX/scripts/isis3VarInit --data-dir=[path to data directory]  --test-dir=[path to test data directory]`

in that it doesn't seem to recognise the file or directory. The error and code I am submitting are pasted below. This may just be me directing it to the wrong place. Any assistance would be greatly appreciated :)

> (isis3) geomorphicjosh@WaffleII:~$ ./$CONDA_PREFIX/scripts/isis3VarInit --data-dir=[/home/geomorphicjosh/anaconda3/envs/isis3/data] --test-dir[/home/geomorphicjosh/anaconda3/envs/isis3/testData]
> -bash: .//home/geomorphicjosh/anaconda3/envs/isis3/scripts/isis3VarInit: No such file or directory

**Comment by jlaura** [comment]
@geomorphicjosh Is this issue closable? Have you been successfully installing ISIS vis conda?

**Comment by jessemapel** [comment]
Closing with no response from submitter
